### ISSUE TITLE
Error notification popup stays open forever.

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#1003]
I just wrote a message to a group and lost my wifi connection. After I hit 'send', a notification popup was shown telling me that the SMS could not be delivered and that it will be sent later. The message was delivered via push eventually, but the popup obscured the screen, even after switching to another app and swiping TS from the app list. Unfortunately I did not try to force quit TS but rebooted my phone.
* TS 2.0.4
* All recipients in the group and myself are registered for push.
* Here's the error log: http://hastebin.com/cufowigeje
* This happened once before in 2.0.0.

**Comment by rhodey** [comment]
this has been fixed, messages will now wait in pending state instead of displaying errors forever.
