### ISSUE TITLE
Image flickers during send

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#1004]
I just wrote a message to a group and lost my wifi connection. After I hit 'send', an image shown in a message above started flickering rapidly. The flickering only stopped after the message was eventually delivered. Could it be the case that the image is repeatedly redrawn with each attempt to send the message?

**Comment by rhodey** [comment]
#2592 should cut down on the possible number of image flickers but every time there is a change to the databases used to build a conversation item the conversation item will automatically be redrawn, fallback and retry logic probably results in some extra database queries.

**Comment by agrajaghh** [comment]
@rhodey unfortunately #2592 doesn't solve the flickering for me, it looks subjectively the same :(

**Comment by piratenpanda** [comment]
seems to flicker seven times now with 2.14.1 when you send a message after sending an image
