### ISSUE TITLE
Amazon/Nokia X/generic support?

### ISSUE THREAD

**Issue by thors** [WhisperSystems/TextSecure#1032]
Hi, I'm a happy owner of a Nokia X device. I built TextSecure from source and was able to install it, but not to register it, since I naturally don't have any google account associated to the phone and no google play account.

Are there plans to support the Nokia push services as well? How about Amazon devices (tablets)? Is someone working on this? If not, I might have a bit time next weekend and try to work on it, but I have to admit that I currently have no clue about TextSecure internals and I'm not an experienced Android developer.

**Comment by rhodey** [comment]
support for tablets is covered by #614 and support for TextSecure without GCM (websockets only) is covered by #1000. if these two issue were resolved then TextSecure should work on your Amazon/Nokia X, so closing.

**Comment by pangyuehung** [comment]
I think it's a different issue, but filed for the task of publishing to other preloaded app stores: #10770
