### ISSUE TITLE
Reply from Notification

### ISSUE THREAD

**Issue by sabret00the** [WhisperSystems/TextSecure#1041]
This is a request to parity-match the stock AOSP SMS/MMS client and allow users to reply from the notification.

**Comment by rhodey** [comment]
@sabret00the so if #483 was implemented you wouldn't mind this issue being closed?

**Comment by sabret00the** [comment]
Nope, #483 is a good solution.

**Comment by rhodey** [comment]
cool :) then I'll close this issue so we can hone our focus in on 483, thanks!
