### ISSUE TITLE
Huawei Y300 does only receive messages

### ISSUE THREAD

**Issue by philippseith** [WhisperSystems/TextSecure#1088]
After deinstallation of the last but one version and reinstallation of 2.0.4, the app isn't able to send messages via push. They are shown as sent, but not received by the chat partner. On the other hand, the app is able to receive messages via push from the same chat partner.

Device info: Huawei Y300, Android 4.1.1

error protocol:
--------- beginning of /dev/log/main
W/RecipientsPanel(18107): org.thoughtcrime.securesms.recipients.RecipientFormattingException: Recipient List Is Empty!
W/RecipientsPanel(18107): 	at org.thoughtcrime.securesms.components.RecipientsPanel.getRecipients(RecipientsPanel.java:110)
W/RecipientsPanel(18107): 	at org.thoughtcrime.securesms.components.RecipientsPanel.addRecipients(RecipientsPanel.java:88)
W/RecipientsPanel(18107): 	at org.thoughtcrime.securesms.ConversationActivity.initializeRecipientsInput(ConversationActivity.java:776)
W/RecipientsPanel(18107): 	at org.thoughtcrime.securesms.ConversationActivity.onResume(ConversationActivity.java:200)
W/RecipientsPanel(18107): 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1184)
W/RecipientsPanel(18107): 	at android.app.Activity.performResume(Activity.java:5084)
W/RecipientsPanel(18107): 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2583)
W/RecipientsPanel(18107): 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2621)
W/RecipientsPanel(18107): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1252)
W/RecipientsPanel(18107): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/RecipientsPanel(18107): 	at android.os.Looper.loop(Looper.java:137)
W/RecipientsPanel(18107): 	at android.app.ActivityThread.main(ActivityThread.java:4838)
W/RecipientsPanel(18107): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/RecipientsPanel(18107): 	at java.lang.reflect.Method.invoke(Method.java:511)
W/RecipientsPanel(18107): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:875)
W/RecipientsPanel(18107): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
W/RecipientsPanel(18107): 	at dalvik.system.NativeStart.main(Native Method)
W/Session (18107): Checking session...
W/SessionRecordV1(18107): Checking: 1
W/KeyCachingService(18107): Incrementing activity count...
W/MmsSmsDatabase(18107): Executing query: SELECT _id, body, read, type, address, address_device_id, subject, thread_id, status, date_sent, date_received, m_type, msg_box, part_count, ct_l, tr_id, m_size, exp, st, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, 'sms' AS transport_type FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, 'mms' AS transport_type FROM mms WHERE (read = 0) ORDER BY date_received ASC)
W/KeyCachingService(18107): Decrementing activity count...
W/KeyCachingService(18107): Incrementing activity count...
W/KeyCachingService(18107): Decrementing activity count...
W/Resources(18107): Converting to string: TypedValue{t=0x10/d=0x1f4 a=-1}
W/Resources(18107): Converting to string: TypedValue{t=0x10/d=0x1f4 a=-1}
E/MediaPlayer(18107): Uri is  content://settings/system/notification_sound
W/KeyCachingService(18107): Incrementing activity count...
E/dalvikvm(18107): GC_CONCURRENT freed 753K, 41% free 11218K/18823K, paused 4ms+30ms, total 192ms
W/MediaPlayer-JNI(18107): MediaPlayer finalized without being released
W/KeyCachingService(18107): Decrementing activity count...

**Comment by rhodey** [comment]
@philippseith the 2.6.4 update includes changes that greatly improve message delivery reliability and speed, if you're still experiencing this issue please reply to this thread with an updated debug log and it will be reopened.
