### ISSUE TITLE
Reception of message often takes a very long time

### ISSUE THREAD

**Issue by maboxx** [WhisperSystems/TextSecure#1102]
The reception of messages often takes a very long time. Sometimes the message is received immediately after delivery but sometimes this takes 10 minutes.
I have one contact which it takes hours until it receives the message from me.
What can the be the reason for this? Is such a behavior already known?

**Comment by rhodey** [comment]
TextSecure message receipt time has been greatly improved in version 2.6.4, if delivery time for push messages is still slow please reply to this thread with a debug log if possible and the issue will be reopened.

**Comment by berdario** [comment]
@rhodey 
https://gist.github.com/b0205d733295077498f4

I have this issue, messages can take between 3 and 10 hours to be delivered. Both users have data network always active afaik, but it only happens with a single user  (with the other users I communicate with it seems to be mostly instant)
