### ISSUE TITLE
Textsecure to CM 11 Whisperpush = no messages?

### ISSUE THREAD

**Issue by Comp-Ex** [WhisperSystems/TextSecure#1122]
Hi, 

I have used Textsecure in the past. Now i have switched to CM 11 and enabled Whisperpush (unregistered push from Textsecure, registered  Whisperpush)

So, when I send now a message from a second phone with Textsecure to my phone with Whisperpush there seems to be a problem.

Phone 2 sends a encrypted message to my phone via network(push). Message gets send.

My phone never receives the message. There is no message, no indication, simply nothing.

Is this a known problem?

**Comment by rhodey** [comment]
@Comp-Ex still experiencing this behavior?
