### ISSUE TITLE
I get their messages, but they don't get my ones

### ISSUE THREAD

**Issue by mgkai** [WhisperSystems/TextSecure#1185]
Trying to switch family members from WhatApps -- bummer: I get their messages, and I can send off messages to them, but they do not get my messages.

I remember when setting up the app on their phones I did not set a password to protect the local message base, but I did so when setting up the app on my phone.
Probably more important difference is that I am on a Dual-SIM Huawei (with second SIM currently switched off though) while their Samsung phones are all single-SIM.

So far, I have tested only on wlan (yes, when setting up TextSecure on all phones, I "registered" the phone no of the active SIM card, so all phones should be able to use wlan, not just SMS).

Any idea what I could do so they get my messages? Thank you! -mgkai

**Comment by rhodey** [comment]
closing because of extensive changes since the opening of this issue (websockets, no encrypted SMS/MMS, etc.) and no debug log available. hope this is working better for you now :)
