### ISSUE TITLE
Wrong encrypted message after restore

### ISSUE THREAD

**Issue by huegelc** [WhisperSystems/TextSecure#1186]
Hi,

I had to restore TextSecure from a encrypted backup but experienced two issues:

1. you cannot import a previous backup if you don´t create a new key. It always says the textsecure-password is invalid. A workaround is to create a dummy key (123456789) import your encrypted backup and reboot the phone.
2. After the successful import of the backup I´ve noticed that my key has changed!!! Any of my contacts who had my key before the backup cannot decrypt my messages anymore. 

IMHO this needs a quick fix as it breaks all previously established communications with your contacts

**Comment by rhodey** [comment]
encrypted backup has been removed but will hopefully be added back in to close #1705
