### ISSUE TITLE
'Tap for SMS fallback' apparently has a malfunction

### ISSUE THREAD

**Issue by leandrosalvador** [WhisperSystems/TextSecure#1207]
Hi Everybody! Apparently, the recently implemented 'Tap for SMS fallback' function is not working correctly. Try yourselves:

Consider that everybody is a TextSecure user with 'Push messages' setted and all of them have an encrypted session established with Alice (me). I (Alice) am with all the following options setted:

[v] Push messages
[v] Receive all SMS
[v] SMS delivery reports
[v] Complete key exchanges
Allow ougoing SMS to:
    [v] TextSecure users
    [v] Ask before sending SMS
    [v] Non-TextSecure users

Step 1. Alice (online) send the message 01 to Bob, which seems to have been delivered (blue balloon, locked).

Step 2. Alice (offline) send the message 02 to Bob, which is not sent; instead, appears the 'Tap for SMS fallback' tab, and Alice clicks 'Yes' in the box 'Fallback to SMS?', so the message is sent via SMS (green balloon, locked), as expected.

Step 3. Alice (online) send the message 03 to Bob, which seems to have been delivered (blue balloon, locked).

Step 4. Alice (offline) send the message 04 to Bob, which is not sent; instead, appears the 'Tap for SMS fallback' tab (dark green balloon, locked), and Alice clicks 'No' in the box 'Fallback to SMS?', so appears the red triangle with an exclamation mark inside icon ('Error sending message' at footnote, green balloon, locked).

Observation A: I imagine that the correct reaction should be this message remain in the queue to be sent via PUSH later when the phone is online again, instead of being dismissed as a permanent error.

Step 5. Alice (online) send the message 05 to Bob, which seems to have been delivered (blue balloon, locked).

Step 6. Alice (offline) send the message 06 to Bob, which is not sent; unlike other times, the 'Tap for SMS fallback' tab appeared no more; instead, the message stayed in a sort of pending status (dark blue balloon, reticence ... and locked at footnote); however, the message details advises the following: 'Transport: PUSH'.

Observation B: as we all know, the messages sent correctly, instead of dark blue and exhibit reticence and locked, are normal blue and reports the time and locked.

Observation C: the great crash happens from now on, because the 'Tap for SMS fallback' tab will appear nevermore in the session (window) established with Bob.

Observation D: the 'Tap for SMS fallback' keeps appearing to other contacts, but if the chosen option is 'Yes', unlike other times, when the message was sent via SMS, now the message stayed in another sort of pending status (dark green balloon, reticence ... and locked at footnote); however, this time (different of the step 6) the message details advises the following: 'Transport: PENDING'.

If you thought that this was a problem, you have not seen anything. The terror begins now.

Step 7. Alice, hungry for try to make her TextSecure return to normal, have an insight which will make her to repent forever. She goes to Settings and unselect the option '[  ] TextSecure users'. So, Alice performs other tests sending messages, go back to Settings again, and reset (selecting again) the option '[v] TextSecure users': hell begins!

Observation E: from now on, an instability appears in her contact list; when she clicks Bob, opens Joshua; when clicks Joshua, open Darwin; when clicks Charlie, open Charlie himself (correctly); when clicks Bob another time, open Bob himself, or not, or even not open! Alice already restarted the TextSecure, but the bug continues. It seems to have provoked an inconsistency in some index, do not know.

Buddies, that's my 2 cents for now, ok? I believe it is important to say that my friends who are coming to TextSecure as a client of SMS mainly (for now), are having a bad experience because it is absolutely not clear how to send a simple SMS, you know.

Thank you in advance for all the attention and hard work! =)

**Comment by rhodey** [comment]
support for encrypted SMS and MMS has been dropped in the latest release, please see [this blog post](https://whispersystems.org/blog/goodbye-encrypted-sms/) for details.
