### ISSUE TITLE
Group MMS ordering while DB is locked

### ISSUE THREAD

**Issue by deusinvictus** [WhisperSystems/TextSecure#1277]
While at the gym I silenced my phone and left it (the DB is password locked, and set to lock after 1 hour of inactivity), when I got back there were 40 new messages.  39 of them were from a Group MMS Session (I'm the only one in the group with Text Secure this is a standard MMS Group Message).  The notification listed several messages from people in that group I assumed it was from the group message (although technically the notification was from the individual people) I only saw 3-4 new messages in the group.  I later noticed all the other messages came through the message thread for the individual users that sent the specific message.  They were listed as "MMS Message click to download", I had to go through the threads for 4 people and click "download message" for each one, and then as they downloaded they were moved into the MMS group message thread.  The bigger issue, is they were moved into the MMS group thread using the date stamp of the time I hit "download message", so the MMS Group thread shows them in the order I downloaded them, not in the order they were sent causing the conversation to be jumbled  (I don't know anything about the MMS spec, perhaps time stamps aren't part of it, and are created when received?).  This was on a Nexus 4, Over the Air Official Google ROM, non-rooted. on T-mobile, Wi-Fi was not on.  If it makes any difference 2 of the people in the group were on iPhones, one was on another Android phone, and I'm not sure what the fourth person was on.  I'm assuming the few new messages in the group thread showed up before the DB was locked, and the rest came through after, but I don't know for sure.  That's all I can think of at the moment that might be relevant.  Let me know if there is any other information I might be able to provide.

**Comment by rhodey** [comment]
this issue is crazy old and our MMS code has changed many times over since, unfortunately all information in this issue is stale & cannot benefit us in improving MMS further. if anyone in this thread is still having issues with MMS please find a recent issue that matches your behavior and preferably network provider and add a debug log there.
