### ISSUE TITLE
"Duplicate message." in conversation after seeing the message in a notification

### ISSUE THREAD

**Issue by gklyber** [WhisperSystems/TextSecure#1317]
In the TextSecure conversation, a message at 10:19am is listed as "Duplicate message." The message was visible as a system notification, but is not shown in the conversation window. Log located here: http://hastebin.com/kumediwame

**Comment by rhodey** [comment]
unfortunately hastebin seems to have deleted this debug log, we have since changed TextSecure to use github gists for posting of debug logs. unable to do much with this without debug log, closing :(
