### ISSUE TITLE
Messagebox is empty when using Emoticons (sometimes)

### ISSUE THREAD

**Issue by duelle** [WhisperSystems/TextSecure#1318]
Sometimes when using smileys/emoticons and question marks in a message, parts of the written content or the whole content is deleted. It seems to happen sporadicly. Sometimes it is just deleted on submission and the sent message is displayed with an empty message box (altough the recipent can read the message)
TextSecure Version: 2.0.6
Android Version: 4.2.2

**Comment by rhodey** [comment]
@duelle we just release TS 2.10.2 which now uses a different emoji keyboard than the one you would have used while experiencing this bug (was based off of android version, & I see you're on kitkat). Can you update and let us know if this still happens (sometimes :P)?

thanks for the support :)

**Comment by duelle** [comment]
@rhodey I didn't experience said bug for a long time. So I would assume it is not present anymore.

**Comment by rhodey** [comment]
thanks for checking back in @duelle :D
