### ISSUE TITLE
Not being able to send messages issue is back, this time not on sms, but push

### ISSUE THREAD

**Issue by Nordic89** [WhisperSystems/TextSecure#1336]
I opened #1038 before, which dealt with others not receiving my sms. This time, they don't receive my push messages.

http://hastebin.com/necaxogihi

**Comment by rhodey** [comment]
TextSecure now uses a combination of GCM + WebSockets, if this is still an issue the information in the debug long is no longer very relevant to the current state of the code on master. Please check back in with this issue and a new debug log if still experiencing this problem, thanks all for helping with these issue :)
