### ISSUE TITLE
extremely high battery/power usage

### ISSUE THREAD

**Issue by graingert** [WhisperSystems/TextSecure#1357]
TextSecure seems to have extremely high battery/power usage on my Nexus 5, the greatest of any other app on my phone.

![Gsam power usage](http://i.imgur.com/rM9yMgW.png)

**Comment by mcginty** [comment]
Closing as dupe of #2498. If someone is still having this issue and can dump battery stats that don't match the root cause of #2498, please open another issue. Thanks!
