### ISSUE TITLE
Disable ADB backups for security reasons

### ISSUE THREAD

**Issue by generalmanager** [WhisperSystems/TextSecure#1387]
On many Android devices ADB debugging is enabled, allowing anyone with physical access to the device to make a full backup of apps and their files/settings.

This can be disabled by setting android:allowBackup to false in the AndroidManifest.xml.
It may not add much security for cases in which the user used a strong password to encrypt the TextSecure files.

But consider the following scenario:
* unrooted smartphone
* Attacker has physical access for a short period of time
* no/weak/circumvented lockscreen password
* unknown but weak TextSecure encryption password.

Even with physical access the user isn't allowed to read the /data/data folder and can only do online attacks against the TextSecure password.
But if he/she is able to copy the whole TextSecure folder, the attacker can do offline attacks, more or less instantly breaking all simple passwords.

There is also a nice talk, demonstrating this exact problem with password container apps like LastPass (interesting part minute ~13):
http://blog.deepsec.net/?p=1740

**Comment by patzi** [comment]
At the moment having the ability of ADB backups is pretty useful because of the not working encrypted backup (https://github.com/WhisperSystems/TextSecure/issues/1705). Otherwise as far as I know one could not backup and import the TS database and migrate on other devices. So for me the option of using ADB backup is as must have.

**Comment by mcginty** [comment]
This seems like a good idea to keep enabled for the time being.

**Comment by rdoeffinger** [comment]
Unfortunately the referenced commit ended up disabling this anyway (and contrary to the commit message not only on M).
See #4577 for request to re-enable.
