### ISSUE TITLE
Shared image with another registered textsecure user and one week later an unrecognized number sent it back

### ISSUE THREAD

**Issue by raypoward** [WhisperSystems/TextSecure#1409]
This all started because TextSecure had shown an incoming picture message of a picture I had sent a friend a few days earlier from a number I did not recognize. After doing some digging I got the idea to double check my phone records to see if TextSecure had received this message via push or SMS. What I found was extremely odd because my carrier usage showed that I had sent the picture message to this random number. The reason I speculate this image has come from TextSecure local database is because I had deleted the picture, from my SD card, after I had initially sent it. There does also appear to be an issue with my TextSecure local database because I tried to send the same friend a picture of my usage summary and after the send button was pressed the picture swapped to a picture he had previously sent me in our conversation. Although it showed the incorrect picture on my end he reported the correct picture did however make it to him. I have attached my original screenshots that show the incoming picture message, an outgoing message from me, and my usage report showing that both messages were in fact outgoing. 

![screenshot_2014-04-21-22-23-57](https://cloud.githubusercontent.com/assets/7367717/2761802/2280ca88-c9e2-11e3-86e2-772d9e147ba9.png)
![usage](https://cloud.githubusercontent.com/assets/7367717/2761803/2287bb86-c9e2-11e3-972f-d4508b71c6bc.png)

**Comment by rhodey** [comment]
@raypoward I believe the behavior you experienced can be explained by #840, closing for now unless we can reproduce this with a debug log.
