### ISSUE TITLE
message being repeatedly sent

### ISSUE THREAD

**Issue by darrikmazey** [WhisperSystems/TextSecure#1436]
For reasons I have not had time to investigate (possibly overly restrictive firewall settings), receiving mms fails to work when connected to wifi

When this happens for a given contact, a message I am trying to send that contact gets "stuck" and TextSecure tries to resend it every time I unlock the lock screen.

Process is as follows:
1. I receive an mms from a contact while connected to wifi.
2. I am unable to dowload it, and TextSecure pops up an "unable to connect to mms" error.
3. I subsequently send any number of sms messages to contact.
4. One of them (the same one each time) will resend every time I unlock TextSecure.

Debug log:
http://hastebin.com/jizujofaga

Cheers,
Darrik Mazey

**Comment by rhodey** [comment]
sounds like this might have magically fixed itself in 2.1.8? closing for now as the log has disappeared from hastebin & steps to repproduce yield no results. please check back in if this happens again with a recent build of TS, thanks :)
