### ISSUE TITLE
Improve transport channel prediction

### ISSUE THREAD

**Issue by generalmanager** [WhisperSystems/TextSecure#1440]
I didn't look at the code, but from the behaviour I suspect that we only check what channel the contact supports instead of actually checking for an internet connection. Can't we just ping google or the push server as soon as text is entered, (hopefully not DOSing it) to evaluate if we have a working internet connection?
Apparently the Android framework [already offers a function for that](https://stackoverflow.com/questions/1560788/how-to-check-internet-access-on-android-inetaddress-never-timeouts). Simply checking if wifi or mobile data are enabled is probably not good enough in case of captive portals and patchy reception.

**Comment by rhodey** [comment]
support for encrypted SMS and MMS has been dropped, please see [this blog post](https://whispersystems.org/blog/goodbye-encrypted-sms/) for details. with encrypted SMS and MMS dropped the question of "channel prediction" is now pretty much voided.
