### ISSUE TITLE
Message to Groupchat with Roaming mode renders phone useless

### ISSUE THREAD

**Issue by maulwuff** [WhisperSystems/TextSecure#1441]
We were on the road when I wrote a message to a groupchat. When I was ready for sending the message, my phone has gone to roaming mode and disabled data channel.
TS did try to fall back to SMS which failes for group chats. Then a notification is shown like "SMS could not be sent, will be resent later". There seems to be an aggressive loop for this, as this notification didn't go away from my screen until my phone went out of roaming mode again. It did stay there whichever app I was starting...

**Comment by rhodey** [comment]
no longer able to reproduce on 2.10.2, closing.
