### ISSUE TITLE
Crash when reading MMS from notification bar

### ISSUE THREAD

**Issue by benmayne** [WhisperSystems/TextSecure#1456]
http://hastebin.com/bilesucove

Got a group message from several people (mix of text secure, iphone, and other android users). 

If I use the drop down notifications to click on the message, the app crashes and I have to enter my password again. If I open up the conversation list, and click on the unread message, everything works fine. 

ATT galaxy s4 android 4.4.2

**Comment by rhodey** [comment]
I believe this was fixed in 2.0.3 as referenced by #461, please check back in if this is still an issue, thanks! :)
