### ISSUE TITLE
An alternative to the painful plaintext key comparison

### ISSUE THREAD

**Issue by wiseoldman95** [WhisperSystems/TextSecure#1459]
Humans are better at comparing images than comparing a long string. Currently, the latter is used in TextSecure, and it's very inconvenient.

My proposal is to be inspired by Telegram, here is how Telegram users compare their shared key:

![key_image](https://cloud.githubusercontent.com/assets/5030488/2898441/b37f563c-d59d-11e3-95b5-5d923fd7c30b.jpg)

Important: If we take that path, there is one problem which Telegram didn't resolve and we should - Users often compare their key visualizations over an insecure channel. The most common way is for them to take a screenshot of the key visualization and then send it via Telegram itself. This defeats the purpose of key visualizations,  because Telegram should be considered an insecure channel until the keys are compared outside of it.

The solution is just a simple message like: "Please compare your key visualizations in real life / over a secure channel, never compare your key visualization via TextSecure itself"

**Comment by freddymartinez9** [comment]
An issue we have ran into is that we have a lot of TS users who we communicate with. After I verify the hash, there is no way to mark that we have confirmed the key comparison. Which isn't a security issue but it is a UX issue. Is that being considered in this issue?

**Comment by mcginty** [comment]
dupe of #817
