### ISSUE TITLE
Bad encrypted message...

### ISSUE THREAD

**Issue by tbalthazar** [WhisperSystems/TextSecure#1462]
Hi,

A friend and I are using TextSecure 2.0.8.
I'm running Android 4.4.2 and he's running 4.3.

We've exchanged dozen of encrypted messages in the past and everything worked fine. 

A few days ago, I sent him a message with an image and he replied. It worked as expected. Then I replied with a text message. It was sent as a regular SMS, the bubble color was green. (I was in a place with very bad 3G signal).

Instead of receiving the message I sent him, he received a key icon, then a couple of hours later, what looks like encrypted text :

![error-1](https://cloud.githubusercontent.com/assets/3520/2914697/7119f074-d69f-11e3-8e2b-c89601ed1bea.png)

He then sent me a message that appeared to be sent correctly from his side (blue bubble, nothing special), but appeared as "Bad encrypted message..." from my side.

I replied him, the message appeared to have been sent correctly from my side (blue bubble, nothing special), but he received a "Bad encrypted message..." too.

From this moment, all the messages we exchange are received as "Bad encrypted message...".

Here are his logs and mine : 
https://gist.github.com/tbalthazar/7afe026443ee266cb4fb

Please let me know if you need more info.

Cheers,
Thomas.

**Comment by lazlolazlolazlo** [comment]
Encrypted SMS support has been removed, so bug can be closed.
