### ISSUE TITLE
Can't send messages to recipient with key exchange

### ISSUE THREAD

**Issue by tburgos18** [WhisperSystems/TextSecure#1470]
The send button keeps changing occasionally from green to blue when sending messages to people who I've exchanged keys with a.k.a that are encrypted. When it changes to blue, I cannot send messages. It keeps saying error sending message. Help please! Please fix!

**Comment by rhodey** [comment]
this should have been resolved in the 2.6.4 release, please check back in with a debug log if you're still experiencing this issue and it will be reopened.
