### ISSUE TITLE
Can't copy message text if link is occurrence

### ISSUE THREAD

**Issue by GAS85** [WhisperSystems/TextSecure#1482]
Hi, I found a nice bug, when message is occurring the URL it can't be copied. Instead of this message it will be last, or previously one copied.
Example:
A: Hi, how are
B: Fine, thx. Check this out http://google.com
B: How is the weather?
B: Bye!

So, I tried to copy first message with the link, it will be copied second, or third one, but not the link or message with it.

**Comment by rhodey** [comment]
also unable to reproduce, any updates @GAS85 ?

**Comment by GAS85** [comment]
I try it just now and it seems solved. I can copy full message, or link only, or click on link. To be closed.

**Comment by rhodey** [comment]
thanks for checking back in @GAS85 :)
