### ISSUE TITLE
off-by-x in message deletion

### ISSUE THREAD

**Issue by amenonsen** [WhisperSystems/TextSecure#1496]
I have noticed (through several TextSecure versions running on Android 4.1.x and now 4.2.2) that if I select the second-last message in certain threads and delete it, it will reliably delete the last message instead. If I scroll up to the top and try to delete the first message, it'll delete some message below, but not the second. Same with trying to delete the second message.

It doesn't happen in all threads. I have one huge thread from "Anonymous" (various services that send messages from names like "LM-VODAFONE", for which the sender shows up in TextSecure as "Unknown" in "Message details"), and that's where I've noticed it most often.

I realise this is a rather vague report, but I'd be happy to try and help with debugging if anyone has ideas for things I should try.

**Comment by mcginty** [comment]
I can't reproduce this, so I'm assuming the recent changes to batch selection have fixed it.
