### ISSUE TITLE
waste of time..

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/TextSecure#1512]
waste of time here...

**Comment by pii100** [comment]
https://github.com/WhisperSystems/TextSecure/issues/175 has been open for over a year. This feature has huge interest just look at the number of duplicate issues. Duress passwords are not a new thing and any serious security app should have them.  Why was issue #175 locked?  http://arstechnica.com/tech-policy/2015/04/drug-dealer-cops-leaned-me-over-18th-floor-balcony-to-get-my-password/

**Comment by rhodey** [comment]
:see_no_evil:
