### ISSUE TITLE
I keep receving coded texts , after uninstallation.

### ISSUE THREAD

**Issue by Waelfz** [WhisperSystems/TextSecure#1514]
I installed text secure based off a recommendation by a friend. I realized most of my contacts don't use this service so I uninstalled it. I now have two contacts that use text secure , and whenever they attempt to text me I get a unreadable message.

Like this  : HHJABBAOOIWHAHS3123191362ASAIHASBSD814612401246+KABQIWRB7579127.

It is not a HUGE deal but its quite a hassle , for them and for me, to constantly remind them that they cant use text secure when messaging me. I assume that since I used to use TextSecure , that somehow it is still thinking that I can receive secure messagaes ? Even after uninstallation?

 ( Clarification : I can message Textsecure users , and they receive " Hey , how are you" ,  however when they respond all I receive is " KAKSHHAO+89HABIFUBIWOH+AISHBASFIUASF" , when in reality they said " I'm good how are you")

I have done alot of research and I was told that sometimes it takes the developers some time to * unregister* phone numbers ; however it has been over 2 months.

Any ideas or suggestions would be immensely helpful!

**Comment by rhodey** [comment]
support for encrypted SMS and MMS has since been dropped, please see [this blog post](https://whispersystems.org/blog/goodbye-encrypted-sms/) for details. it should no longer be possible to receive coded texts or MMS after uninstalling
