### ISSUE TITLE
Wrong contact name in thread list view after uninstall/reinstall/import from sd

### ISSUE THREAD

**Issue by liliakai** [WhisperSystems/TextSecure#152]
To repro:
Send text to one contact from TextSecure, and to a different contact from system sms app, so that you have different names at the top of each app's thread lists.
Export to SD.
Uninstall.
Reinstall.
Import messages from system sms app.
Import from SD.

The first thread in TextSecure thread list now has the contact name from the first thread in the system sms app, though the thread itself is correct and shows the correct contact in its own view.

**Comment by rhodey** [comment]
@liliakai says this was *probably* an encrypted backup which is not currently supported, closing.
