### ISSUE TITLE
Correct password won't be accepted if it contains special characters

### ISSUE THREAD

**Issue by FreebeJan** [WhisperSystems/TextSecure#1534]
I have noticed a strange behavior of Text secure on Android 4.2 and 4.3.1 which seems to be reproducable. 
A certainly correct password was not accepted by textsecure this happened not only to me but also to an acquaintance of mine. 
Both passwords ckntakned special charakters Like äüö¥π#..
Both devices are Samsung Galaxy s4 minis

**Comment by mcginty** [comment]
It could be that some files got corrupted if Android shut down improperly from a dead battery. Closing unless we see more evidence that this is a TS issue. Thanks!
