### ISSUE TITLE
waste of time..

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/TextSecure#1539]
having issues? better go somewhere else.. mods don't care.

**Comment by rhodey** [comment]
@nwdev can you be sure that the image you received was actually incorrect (after clicking on the preview) and not just the image preview rendered in the message thread? There is currently a known issue where image previews can get mixed up in an edge case.

**Comment by nwdev** [comment]
@rhodey .... Yes, the image was actually incorrect.   It would be a little hard to check now though being that I created this thread in May of last year.....

**Comment by rhodey** [comment]
couldn't ever reproduce this, :see_no_evil:
