### ISSUE TITLE
New User - Bad encrypted message... 

### ISSUE THREAD

**Issue by Satheian** [WhisperSystems/TextSecure#1548]
Testing secure sessions with myself as the sender and receiver, unsecure messages work fine but during a secure session I receive "Bad encrypted message..." as well as the red error triangle.

Also, when ending the secure session, I receive "Message encrypted for non-existing session..."

http://hastebin.com/dakemaluze

**Comment by rhodey** [comment]
sending messages to yourself via TextSecure is now considered to be undefined behavior, we hope to have an eliza-style chat bot for TextSecure users soon.
