### ISSUE TITLE
Last sent message displays 'Sending...' untill another message is sent.

### ISSUE THREAD

**Issue by hablethorn** [WhisperSystems/TextSecure#156]
I'm experiencing an issue where the last sent message continues to display as "Sending..." until you send another message. 

The message is actually delivered but the status doesn't change until you send another message. Which is a bit of a pain to know if your message was sent successfully when your in a location with questionable coverage.

I did a search on the submitted issues and this appeared to be the same as previously submitted issue. However in that issue the sending status never changed at all. Also that issue was fixed a long time ago and released, this is a new issue I've been experiencing since the latest update.

I'm running a Motorola Droid 4 with 4.1.2 Android OS.

**Comment by rhodey** [comment]
this issue contains no debug logs and is crazy old, will reopen if we can get a debug log and confirmation that it is still occurring, haven't seen any hints of this recently though.
