### ISSUE TITLE
If secure session ends due to SMS fallback on one side when other side can't receive SMS, no way exists to restart session.

### ISSUE THREAD

**Issue by gordon-morehouse** [WhisperSystems/TextSecure#1583]
I have a contact with Textsecure who at one point fell back to SMS during a conversation. My "phone" is a wifi only device and currently receives SMS via Google Voice, so this didn't work.  I sent him a message saying I can't fall back to SMS and disabled it on my side, and then got one or two from him later saying that he couldn't restart a secure session. I also got a couple "secure session ended" messages and the "send" UI element turned to the green (should be red, IMO) unlocked one.

Now, with network connectivity good, every message I send results in "Error sending message!" with absolutely no additional useful information as to WHY there was an error, WHAT the error was, and WHAT I may do to correct it.

There is no UI element to restart a secure session.  It doesn't exist, or at least, I can't find it in 5 minutes of searching, which means for all practical purposes it doesn't exist.

Thinking to "reset" the state between my contact and myself, I selected "delete thread" and erased our prior messages. He then DISAPPEARED FROM MY CONTACT LIST (wtf?) and, despite having an identity key still in my contact keys, there's no way to re-add him.  Once I stumbled upon the send message dialog (still with the green unlocked UI element) somehow - no idea how.  Otherwise, it's impossible.  I can't add him using his number, or directly from contacts.

I rebooted the phone and still can't add him from contacts or by using his number in +1xxxxxxxxxx format.  I'll file separate UI bugs, but this is the whole story.

**Comment by rhodey** [comment]
support for encrypted SMS and MMS has been dropped in the latest release, please see [this blog post](https://whispersystems.org/blog/goodbye-encrypted-sms/) for details.

**Comment by gordon-morehouse** [comment]
That's unfortunate, since the data transport is still quite unreliable.

**Comment by moxie0** [comment]
@gordon-morehouse If you're running a modern client, that's unlikely. All messages are stored on disk before acknowledged to the sender, and only removed from disk when acknowledged by the receiver.

**Comment by gordon-morehouse** [comment]
I'm going to open an issue and ask how to properly add debugging information, since this is a multi-party problem. The messages do get through - an improvement over a couple months ago, thank you for that! - but are often affected by unpredictable delays of minutes to hours, regardless of carrier and of wifi or non-wifi data access.

**Comment by kerricrawford** [comment]
What does reset the secure session mean? Plus i got a message that i couldnt open please was i deleted or what? Im new at this.
