### ISSUE TITLE
TextSecure intercepts encrypted SMS but not encrypted MMS

### ISSUE THREAD

**Issue by spiderman666** [WhisperSystems/TextSecure#1608]
Galaxy S4 i9505 Android 4.3 XXUENAA. TextSecure 2.0.8

Encrypted SMS are sent and received just fine with text secure option set to 'not handle all SMS'.

Encrypted MMS send fine but will not be intercepted by textsecure unless option to 'handle all MMS' is set to on. With option off encrypted MMS are coming through stock android messaging app. Also even with textsecure set to 'handle all MMS' set to on sometimes there will be no notification of having received a MMS at all.

**Comment by rhodey** [comment]
support for encrypted SMS and MMS has been dropped in the latest release, please see [this blog post](https://whispersystems.org/blog/goodbye-encrypted-sms/) for details.
