### ISSUE TITLE
TextSecure not initiating key exchange properly

### ISSUE THREAD

**Issue by dmelliott0311** [WhisperSystems/TextSecure#1618]
I have had multiple issues with TextSecure not recognizing another TextSecure user and automatically initiating key exchange and encryption. It ends up working eventually after minutes or sometimes hours of trying, but in the meantime I'm getting charged for international SMS that I shouldn't be paying for. I am using TextSecure with a phone number in Suriname, and I have had issues trying to communicate with 2 users who have US phone numbers.

**Comment by rhodey** [comment]
support for encrypted SMS has been dropped in the latest release, please see [this blog post](https://whispersystems.org/blog/goodbye-encrypted-sms/) for details. in dropping support for encrypted SMS and MMS, much of the code that could have potentially led to the issues you're both describing has been modified or removed. if you're still experiencing this issue please submit a debug log, post it here, and I'll reopen the issue :) thanks for the support!
