### ISSUE TITLE
Images get mixed/lost between senders

### ISSUE THREAD

**Issue by CapybaraChan** [WhisperSystems/TextSecure#1640]
I've had an ongoing issue where I'll receive an image in a text message, but it will display as an image I had already received from another sender. The new image just never displays. 

Contact A sends me a picture of her kids. I can view it.
Contact B sends me a picture, but the thumbnail is the same as the image from Contact A. I touch it to open it in my pictures. It opens as the picture from Contact A.
Contact C sends me a picture. It comes through normally.
Contact A sends another picture. It comes through as the picture from Contact C. 

Also, I've noticed that if someone sends a picture to a group, 99% of the time I get no thumbnail (just an empty box), and a "Media not Found" error when I try to open it.

**Comment by rhodey** [comment]
hi @CapybaraChan, are you still experiencing this issue where not only the image thumbnail preview are incorrect but also the image itself (when you click it)?

**Comment by rhodey** [comment]
closing as non-reproducible, if we get an updated report of this with debug log will reopen.
