### ISSUE TITLE
Received corrupted key exchange message!

### ISSUE THREAD

**Issue by TWfromSWD** [WhisperSystems/TextSecure#1650]
I experienced this Problem with two Contacts in my List. They are unable to send me messages. Instead i get: "Received corrupted key exchange message!" and so do they, when I try to send a message to them. Ending the Secure Session via the Lock Symbol didn't change the Situation.
This behavior started some time after I switched from Cyanogenmod 10 to Cyanogenmod 11 with a Factory Reset. But all other TextSecure Contacts except the two mentioned, kept working fine.
I also refreshed the Push Directory several Times after the Error started to appear but it didn't change anything.

Device Info: Nexus S, CyanogenMod 11-20140608-SNAPSHOT-M7-crespo

**Comment by rhodey** [comment]
@PrasannaVenkadesh @TWfromSWD have you received any more of these corrupted key exchange messages lately?

**Comment by TWfromSWD** [comment]
No, fortunately not since my last post. Everything works fine at the moment :)

**Comment by rhodey** [comment]
it is my guess that this weird bug was the case of some strange TS-WhisperPush interaction that we probably won't ever be able to reproduce with current versions of the app and WhisperPush, closing for now :)
