### ISSUE TITLE
Key exchange message: Cannot accept new ID

### ISSUE THREAD

**Issue by soratobukuroneko** [WhisperSystems/TextSecure#1686]
1. Contact change is ID for reinstallig extsecure or reregistring PUSH
2. I get key exchange message: Received message with unknown identity key. Click to process and display.
3. either tap or long press on the message: nothing happens.

My OS OmniROM 4.4.4 build from 20140701
Oppo FIND 7a

logs:
http://hastebin.com/kezaqirena.coffee

**Comment by mcginty** [comment]
@soratobukuroneko sorry we missed this issue. Can you reopen this issue and re-paste your logs if you're still around?
