### ISSUE TITLE
Messages not received between phone on data and phone without data

### ISSUE THREAD

**Issue by rechelon** [WhisperSystems/TextSecure#1723]
Okay, this is going to be a bad ticket without much detail, but I feel the obligation to document in at least some form.

I have data, Jenny does not (I think). We've exchanged keys before and authenticated. At some point in the last couple months her phone stopped receiving any text secure messages from my phone, whereas I continue to get her messages.

This does not occur between my phone and anyone else, but we did some experiments together on the two phones and were unable to get ours to work. Anyway, Lilia, you should poke at Jenny's phone the next time you're at Sudoroom.

/ halfassed bug report

**Comment by rhodey** [comment]
there are a couple open bugs that document late delivery of messages, however I don't believe this bug (messages never ever delivered) is still valid, and in either case we have since implemented delivery receipts which should help.
