### ISSUE TITLE
User is only able to send bad encrypted messages

### ISSUE THREAD

**Issue by mpetri** [WhisperSystems/TextSecure#1731]
Since the new version (2.11?) a specific user can only send me bad encrypted messages. I have been communicating with that user for a few month now without problems. Here the debug logs:

receiver of the "bad encrypted messages": http://hastebin.com/emirogotiw
sender: http://hastebin.com/soqoxeceha

**Comment by moxie0** [comment]
This should be fixed now, although you might need to manually clear your session with this recipient.
