### ISSUE TITLE
Timeout interval not working in 2.1.1

### ISSUE THREAD

**Issue by cyberpunklibrarian** [WhisperSystems/TextSecure#1734]
I have a Galaxy Note 3 running Kit Kat and recently updated to TextSecure v2.1.1. I have the app set to timeout the passphrase at five minutes. Since the update, if I leave the app unlocked, it will not ask for the passphrase even after remaining unlocked for hours. Manual lock works fine, so it's something wrong in the timeout.

**Comment by rhodey** [comment]
do you still have this issue @cyberpunklibrarian? I'm unable to reproduce on Nexus 5 running stock Android Lollipop and TS 2.6.4

**Comment by rhodey** [comment]
seems to be resolved now, if anything the passphrase times out too quickly as documented by #2328 -__-
