### ISSUE TITLE
Update (2.1.1) broke sending to textsecure users

### ISSUE THREAD

**Issue by tinoesroho** [WhisperSystems/TextSecure#1735]
Oy, mate!

I have some gripes with the new update, some legit, some not.

The last update broke sending SMS to textsecure users. Important ones, like my mum and dad. 

It also took away my ability to manage keys. :-1: 

Can we roll back to 2.1.0?

**Comment by mcginty** [comment]
Please reopen if you can put a debug log onto the issue, because otherwise it'll be very difficult to debug otherwise. Thanks!
