### ISSUE TITLE
Feature: Automatic deletion of old messages

### ISSUE THREAD

**Issue by coiax** [WhisperSystems/TextSecure#176]
In the spirit of https://ssd.eff.org/your-computer/protect/retention having deletion of messages older than a certain amount is probably good practice. I previously used an automated tool to delete SMS messages older than 30 days, but since TextSecure uses its own database, this no longer works.

Having the option for TextSecure to delete messages older than X (reuse of the passphrase timeout selector would be fine) would be highly helpful.

**Comment by rhodey** [comment]
Settings > Delete old messages > *check box*
