### ISSUE TITLE
Enable sender to delete own messages from all parties in the conversation

### ISSUE THREAD

**Issue by jooize** [WhisperSystems/TextSecure#1764]
While I think this is an important feature, some people were opposed to self-destructing messages. I would take it even further and do similar to [Gliph](https://gli.ph/), where anyone in a conversation can delete messages. A risk with Gliph is their effectively central control*, which the TextSecure team seems to have solved very elegantly.

_\* Gliph is quite [transparent](https://gli.ph/privacy.html), and have what they call [Lockdown™ Privacy Protection](https://blog.gli.ph/2012/05/31/introducing-gliph-app-version-1-2-powerful-privacy-for-iphone/). Unfortunately, the fact remains they are in control of the infrastructure and could theoretically capture the passphrase next time you login. Meaning we have to trust them._

> Messages I send other people should disappear on my terms. The sender should have control over her messages, as she's the one providing the content after all.

Without much insight into the project, I'd like to share my ideas. Let's hope they are of value.

# Scenarios to relate with
Imagine two journalists discussing some political issue over TextSecure, and one of them loses track of their phone. Say this journalist didn't care immensely and neglected security in a way that his messages are now available to read for anyone in possession of his phone. If the journalist's friend could trigger the phone to delete sensitive messages—provided the phone can reach the Internet—they could rest more peacefully.

**In case you are not a top secret agent**, something easier to relate to may be sending a message to the wrong person. If you realize you've sexted your family like around 10% in a [poll by Recombu](http://recombu.com/mobile/news/half-of-uk-adults-have-sent-a-sext-one-in-10-to-the-wrong-person_M17564.html) have you may want to have an undo button. (how do people accidentally do this?)

# Friends and collegues
I care quite a bit about privacy and security, and although I've managed to make my friends care more than expected, there is a limit to what they'll endure. This suggestion would ease the pressure on them to control their habits. They won't use a very secure password if they have to enter it every time to read messages.

# Implementation complicatedness
Putting this idea together into the product can get complicated. Should the recipient have the ability to disallow deletion? As he could already be in possession of the information, one could argue it may already be captured and that my idea gives a false sense of security to the sender. I think it's an issue with little impact to an otherwise very valuable feature. Anyway, if we let the recipient prevent such deletion, I would like the sender to be aware of that fact before submitting her message.

If the recipient doesn't agree with letting the sender delete their messages or having them expire, he could disable it for future messages. The recipient may have the ability to disallow deletion/expiry for (specific or all) senders, but the sender must always be aware of which before sending.

**All this causes complexity and new UI considerations. It appears we do not want more of that. Everyone should easily understand their message's fate.**

# Solution
* Let the sender delete it's own contribution to the conversation.
* Allow manual locking of messages as suggested in #283.

That's a simple and in my opinion reasonable compromise resulting in an easy to understand model avoiding added complexity.

## Model
Messages are owned by the sender, who can always delete them, but is also aware that removal from other devices (or human memories) cannot be guaranteed.

## User interface
We have the following alternatives for deletion.

Delete message or conversation...
* ...from current device only.
* ...from current device and send deletion notice for own messages to other parties.
* ...from current device and send deletion notice to other parties, regardless of sender.
* ...from other parties only, by sending a deletion notice.

## Potential problems
How can messages be kept track of, and could this kind of ownership break the plausible deniability we currently enjoy? Would the ability to delete any message in a conversation solve that problem?

### Let any party delete any message
People should manage to handle this as a social issue, where if someone disrespects the wishes of message retention, they're reprimanded appropriately. TextSecure has no role in this.
### Expiring messages (requires UI modification)
Perhaps auto-deletion after recipient specified time period suits better for TextSecure.

# Related issues
#175, #176, #226, #283.

I love that Signal was just released for iPhone!

**Comment by ghostbar** [comment]
I would like this feature. Is specially useful for political activists in authoritarian countries. Having the ability to avoid torture by writing your password and having no traces of your messages are a good idea.

(In Venezuela this would be really useful, they force you to show your messages from your devices)

**Comment by mcginty** [comment]
While it's something that could be interesting, it's not going to happen in the immediate future. For those who have higher requirements to remove sensitive content from their devices, you can still manually delete messages or turn on trimming to only keep the last N messages in your conversation.

**Comment by jooize** [comment]
Trimming sounds useful, thanks for mentioning it! Would like that or something similar to Signal iOS. Preferably that it trims after both number of (read?) messages and time, whichever comes first.

@ghostbar For that purpose, perhaps another password unlocking a collection of custom messages would be even better? An empty log could be considered suspicious. One might also want to consider what should happen when new messages come in while you're in that “secret public” collection. Imagine if they force one to show that it works properly.

Another idea is a **panic gesture** that instantly clears everything. Destructive, and would have to work reliably of course.

**Comment by TheStash** [comment]
I believe this feature could be implemented as an opt-in feature, Silent Text has this feature and it is pretty cool (link: https://support.silentcircle.com/customer/portal/articles/1645090-what-is-the-%E2%80%98burn-notice%E2%80%99-and-how-do-i-use-it- )

The user want to be the master of his communication: It could be an opt-in feature per chat/group chat or globally; sometimes an oppressive regime people need this feature as when a political opponent is caught the government forces him to hand his phone and password - you can't negotiate it, those kind of people would agree to enable this feature to protect their own selves... what they are doing doesn't have to be wrong, but the government can take this and use against him and chat participants whether it is a group or one-to-one chat.

It is technically impossible to do this in a "good" way: only developers and technically minded people could build their own builds and could disable this kind of feature, so having this feature as opt-in would preserve your right and would not encourage someone to opt-in this conversation.

This leads to a false sense of security: i believe that it is pretty doable to receive a delete confirmation from devices in which the message got deleted.
