### ISSUE TITLE
Can't send push messages, receiving is fine.

### ISSUE THREAD

**Issue by rudi4** [WhisperSystems/TextSecure#1770]
Hi.

I cannot send any more push messages. That started short time after the update to v2.1.1 was installed.

The messages have the correct blue color, the time stamp and the locker symbol in the right corner, telling "sent successfully"

But they never arrive at the recipient's phone. I even tried 50 tiny messages, content = just the numbers [1..50].

From the same senders (just two) I can *RECEIVE* textsecure push messages without any issues.

How to track down, what's going wrong here?

Push: activated
SMS in: Disabled
SMS send: none
SMS reports: disabled
Reporting in status bar: active
LED colour: green
LED flash: custom = 3003ms
sound feedback: bubbles
always inform (report, alert): on
vibration: on
activate ENTER: on
ENTER sends: off
design: dark
language: german
delete old messages: off
password: <password is defined>
automatic key exchange: on
protect screen: on
MMS: disabled

Can I send an error report to me myself?

Next step would be to try LAN tracing, when pushing some messages to see, what's going on at IP level.

Regards, Rudi4

**Comment by moxie0** [comment]
@rudi4 Sounds like the problem is on the receiver's device.  They should check out the support center for TextSecure support: http://support.whispersystems.org
