### ISSUE TITLE
Sending TextSecure messages between users works only in one direction under certain circumstances

### ISSUE THREAD

**Issue by clashman** [WhisperSystems/TextSecure#1773]
There is contact X and contact Y using TextSecure.
X and Y used to send each other TextSecure messages but recently, things changed.
X can still send TextSecure messages to Y.
Y can receive them but is not given the possibility to send back TextSecure messages to X (the interface is offering secure SMS).

The following is the story about how I fixed it and probably also contains the cause of the error:

After searching for a while I noticed the following on Y's phone:
When pressing "+" to start a new conversation, X was presented as TextSecure User with his phone number +49170854----. After clicking on the contact item of X, the conversation view opened and now on the top of the screen the was X name and below his phone number +490170854----   (note the additional 0 after the country code).

Now I searched the phones local phone book for that number. It was quite a mess with the +49170-number being part of at least two contacts. And then I found the +490170-number, which was part of a Skype-contact and could not be edited.

I asked X to delete the additional 0 from his Skype-account.
Then I deleted the local Skype-contact entry in Y's phone book.

After I cleared data and cache of TextSecure on X's device and on Y's device and re-registered both to the TextSecure push-service, everything worked again.

Debug logs (a bit messy):
X's phone: http://hastebin.com/iwipawemob
Y's phone: http://hastebin.com/xakubapiro

**Comment by rhodey** [comment]
this issue is related to secure SMS which is no longer supported by TextSecure
