### ISSUE TITLE
Vodafone: CallYa Toppings not redeemable

### ISSUE THREAD

**Issue by SecUpwN** [WhisperSystems/TextSecure#1780]
[![CallYa Toppings](http://toppings.vodafone.de/img/topping-fb.jpg)](http://toppings.vodafone.de/)

Hi there TextSecure developers, @moxie0 and all you funky freaks of the GitHub community,
let me first say that I still love TextSecure and keep using it until encrypted SMS are vanishing.

Now to the Issue several friends of mine and I do have:  For the ones that do not use [CallYa Toppings](http://toppings.vodafone.de/), here is a short explanation: CallYa Toppings is a bonus program for **prepaid** users, which is offered by Vodafone when recharging the prepaid card. Selectable toppings: Free minutes, free SMS or free surf-flats. The longer a prepaid user is using the same prepaid card from Vodafone, the more Toppings this user will get.

The usual redeeming process is the following:

1. When recharging the card, Vodafone sends an SMS from number `22990` to show available Toppings.
2. (through sending the word `AUSWAHL` to `22990` a user can change the available Topping)
3. The Prepaid user has to claim the selected Topping with sending the word `TOPPING` to `22990`.
4. Another SMS with a verification of successful claim is being sent to the user from number `22919`.

**The Issue:** When sending `TOPPING` to `22990`, my friends and I just get an SMS from number `22919` that the booking code is "wrong" and that we shall check it and try again. I've been in a huge fight with the Vodafone customer service, called them at least 10 times, have ruined their shops over here in Germany, wrote multiple heavy complaints to them and was really upset - until my girlfriend noticed that this Issue appeared since we've been using TextSecure. To verify this, I've used the standard SMS application - and there it works flawlessly. Through the standard SMS app, Vodafone recognizes the selection and grants it.

**Questions:** Does TextSecure add special characters to each SMS or modify normal SMS even though sending them unencrypted through the network? Or does Vodafone recognize that I'm using TextSecure and does not want to grant access to the Toppings for users where they can't spy on their SMS?

If there are things to test, data to collect or anything else to resolve this, please let me know.

**Comment by SecUpwN** [comment]
@tinloaf, I'm digging this up again since it is still present in the current version of TextSecure. I wonder if there wouldn't be a convenient way to detect if the number the SMS is sent to is actually a service number? I mean, TextSecure is able to warn about the "possible costs" of that SMS, why not take away the spacing at the same time when that detection happens?

**Comment by agrajaghh** [comment]
This should be fixed soon, since sending encrypted sms will not be possible anymore in the next release

**Comment by SecUpwN** [comment]
@agrajaghh, awesome! So what was the prupose of TextSecure again? :(

**Comment by jeremymasters** [comment]
Locked in 3...2...1...
