### ISSUE TITLE
I get no Push notifications with mobile data

### ISSUE THREAD

**Issue by Eplava** [WhisperSystems/TextSecure#1837]
Hey,

Since the first textsecure version I can`t receive push notification when I only get internet by mobile network. Only with wlan I receive messages. But when I send messages to my friends while mobile data is activated they receive my message.
I'm using a Nexus 5 with the german eplus network.
Another nexus user (nexus 4) in my friendlist has the same issue.

I tried the app "push notification tester".
Wlan has passed the test.

Mobile data creates this error in the debug log:
"--------- beginning of /dev/log/main
D/Push Notification Tester(19259): Step 1: Subscribe start
W/ContextImpl(19259): Implicit intents with startService are not safe: Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) } android.content.ContextWrapper.startService:494 com.firstrowria.pushnotificationtester.activities.MainActivity$2.onClick:136 android.view.View.performClick:4438 
D/Push Notification Tester(19259): Step 1: registering to push updates failed, error code: SERVICE_NOT_AVAILABLE, registrationId: null, unregistered: null"

I hope someone can help me.

**Comment by rhodey** [comment]
If you're not receiving push notifications **ever** on mobile data it is because something about your phone has prevents GCM from delivering push notifications to your device, and thus TextSecure.
