### ISSUE TITLE
Textsecure at 50 % CPU and cannot send or receive any encrypted messages

### ISSUE THREAD

**Issue by mlsxlist** [WhisperSystems/TextSecure#1843]
Hi,

after having much fun with TextSecure for a long time it stopped working today. The visual issues are:

1.) when I send a PUSH/secure SMS message it stays in status pending. Insecure messages can be sent and received.
2.) when I restart my phone before entering the TextSecure passwd I see a notification of TextSecure "4 new messages". After login to TextSecure test messages from other users are not shown
3.) In Android System Info Pro I see that the TextSecure process runs at 50 %. The battery is drained by TextSecure and the phone heats up significantly.
4.) TextSecure UI is very slow. All new encrypted messages Push or secure sms only show "Decrypting, please wait..." but that are never displayed in clear text. 

Any hint how what I can do to make it working again?

**Comment by rhodey** [comment]
hey @mlsxlist, are you still having this issue? I'm not able to reproduce.

**Comment by rhodey** [comment]
not seeing any actionable information in the debug log, not able to reproduce, and this issue is now very stale, closing.
