### ISSUE TITLE
Text messages going to default messaging app

### ISSUE THREAD

**Issue by coiax** [WhisperSystems/TextSecure#187]
I have been receiving text messages occasionally in the default app, rather than then being (as they have been until now) all processed by TextSecure. Assuming the recent update might have something to do with this.

Using a Nexus 4 with Android 4.2.2

**Comment by rhodey** [comment]
this issue contains no debug logs and is crazy old, will reopen if we can get a debug log and confirmation that it is still occurring, haven't seen any hints of this recently though.

**Comment by torrancew** [comment]
@rhodey I agree, I haven't run into this in a long time now.
