### ISSUE TITLE
Handling of new devices has security implications

### ISSUE THREAD

**Issue by rdoeffinger** [WhisperSystems/TextSecure#1872]
Currently, when a new device is set up this disables any old ones, presumably to increase security. However, due to how this is handled in details this IMHO has pretty serious security implications:
1) It makes it much easier to take over an account for prolonged periods. If someone gets access to the SIM for even just a second they can connect to that phone number. They then will receive messages directed to that number. The legitimate user will however not be warned of this in any way. He will get generic "sending failed" messages. Worse, if encrypted SMS fallback is enabled, he might not even notice anything is wrong. The recipient will get these messages, but they will not be decrypted, thus making it even easier for the attacker to appear legitimate. Even if the user figures out that someone took over his account, there is no obvious way to fix this. The only one I could figure out is clearing app data, however then he loses his private key and the people he communicates with have no reason to trust him over the attacker.
2) It makes it impossible to securely and with little effort switch to a new device. Normally this would be done by distributing a hash of the new private key via the old trusted channel. However before linking the new device its private key/hash is not known (I have not tried if skipping linking a phone number at first would be possible and help), whereas once the linking is done the old device can't be used to distribute the new hashes.

**Comment by mcginty** [comment]
Closing as essentially a dupe of non-phone-number account identifiers. Thanks!
