### ISSUE TITLE
No push notification with Nexus 5 on mobile data network

### ISSUE THREAD

**Issue by Eplava** [WhisperSystems/TextSecure#1874]
Hey,

Since the first textsecure version I can`t receive push notification when I only get internet by mobile network. Only with wlan I receive messages. But when I send messages to my friends while mobile data is activated they receive my message. Background data is active.
I'm using a Nexus 5 (stock rom) with the german eplus mobilenetwork.
Another nexus user (nexus 4) in my friendlist has the same issue.
The errorlog of textsecure: http://hastebin.com/duboqohase

I tried the app "push notification tester".
Wlan has passed the test.

Mobile data creates this error in the debug log:
"--------- beginning of /dev/log/main
D/Push Notification Tester(19259): Step 1: Subscribe start
W/ContextImpl(19259): Implicit intents with startService are not safe: Intent { act=com.google.android.c2dm.intent.REGISTER (has extras) } android.content.ContextWrapper.startService:494 com.firstrowria.pushnotificationtester.activities.MainActivity$2.onClick:136 android.view.View.performClick:4438 
D/Push Notification Tester(19259): Step 1: registering to push updates failed, error code: SERVICE_NOT_AVAILABLE, registrationId: null, unregistered: null"

I hope someone can help me.

**Comment by projectgus** [comment]
Do you have "restrict app background data" turned on for Google Play Services (under Settings->Connectivity->Data Usage)? This will cause these exact symptoms.

(From reading online, apparently some other apps set up alternative polling services to work around GCM when it's unavailable. Which may explain why whatsapp, etc. is able to receive notifications on mobile while TextSecure isn't.)

**Comment by rhodey** [comment]
@Eplava TextSecure is now using GCM + websockets, this should no longer be an issue for you after updating to 2.6.4 but please let us know if you do and will reopen.
