### ISSUE TITLE
TextSecure crashes when trying to show message

### ISSUE THREAD

**Issue by matthias-k** [WhisperSystems/TextSecure#1898]
Hi,

I got a message (via push, i.e. by a sender using TextSecure with encryption), that makes TextSecure take a long time to open or scroll over the senders entry in my message list (about 20seconds on my Moto G running CyanogenMod). If I try to open the conversation with said sender, it takes even longer and (more than two minutes). Often it just crashes while trying to preview. Once I managed to actually see the message. It looked like lots of encrypted data that TextSecure did not decode but showed it as text. I could not copy the message, as TextSecure crashed some seconds later (see log [1])

Sometimes TextSecure even crashes when trying to preview the senders message in the general (see log [2]).

When save my messages via plaintext export, the problematic message does not show up. Thus I don't know how to pass it to you. Do you have any advice?

By the way, as TextSecure crashes when showing the message, I have no idea how to delete the message to make TextSecure work again. Do you have any ideas?

My device data:
*  Motorola Moto G
*  Cyanogenmod 11-20140504-SNAPSHOT-M6-falcon
*  Android 4.4.2

If you need any other information, I will be happy to provide it.

[1] http://hastebin.com/uyinasoduh
[2] http://hastebin.com/ibamiboqij

**Comment by mcginty** [comment]
Closing as not reproducible
