### ISSUE TITLE
Delete message fails when call phone number selected

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#1918]
When I get a message containing only (or almost only) a phone number and I want to delete it this is quite difficult. When I long press the message, Textsecure both shows the upper toolbar with the delete button and I get a complete action dialog box from Android offering several ways to call the number (phone, skype, strangely not Redphone which I have also installed).

When I press back to remove this dialog and then press the delete button it does nothing (well, at leat it does not delete the selected message). It doesn't show any message or error.

**Comment by rhodey** [comment]
are you still having this issue @johanw666? I'm not able to reproduce this.

**Comment by johanw666** [comment]
Just tested with 2.6.4, I have a different issue now: when I long-press on a message (any message, doesn't need to be a link in it) it selects, but when I remove my finger from the screen it immediately deselects. Only long-pressing on the space left of the message works.

**Comment by rhodey** [comment]
thanks for checking in @johanw666 :) glad that there have been some improvements. the other issue you're experiencing is documented in #2333 and is being worked on in pull request #2648, hope to have this resolved soon!
