### ISSUE TITLE
Feature Request: Detect and warn about WhisperPush

### ISSUE THREAD

**Issue by tinloaf** [WhisperSystems/TextSecure#1926]
Hi,

TextSecure should detect if WhisperPush is enabled in the system (did not check how - I guess you can somehow read arbitrary system settings with the right permissions) and then warn the user to switch it off (and instead enable push messages in TS).

Here's why: It's actually possible to install TS on a system with WhisperPush as long as you don't turn on push messages. Obviously that makes little sense, but users might still do it, and it leads to a mess, as stated in #1925 .

**Comment by mcginty** [comment]
There should be more verbose error messages now when trying to register if a user is already on CM's servers. I think this might be in the realm of CM to solve making unregistering more usable.
