### ISSUE TITLE
textsecure picking up all mms messages

### ISSUE THREAD

**Issue by gsosure** [WhisperSystems/TextSecure#1931]
I'm noticing that textsecure is picking up all mms messages that are being sent to my regular messages app. I've tried installing 3rd party sms apps, and have the same results. 

Edit: The best example I can give is also with group messaging with stock messages on Verizon Galaxy S4. It is set to send group as mms. When the others in the group reply it will go to textsecure and give me an error "Unable to connect to MMS provider" and sometimes the messages will come through to Messages app and others they just get stuck and never come through.

**Comment by rhodey** [comment]
hey @gsosure, just checking in to see if you're still experiencing this bug or if we can close as resolved.
