### ISSUE TITLE
MMS MSISDN/Line1 headers missing

### ISSUE THREAD

**Issue by tecknicaltom** [WhisperSystems/TextSecure#1935]
I'm new to using TextSecure and I'm sorry if this is a dupe but I couldn't find a similar issue.

I just made TextSecure my default messaging app and when trying to download an MMS image, I receive "Error connecting to MMS provider..." I used the following manual MMS settings, as found in my phone's system menu (##3282#):
MMSC URL: http://mmsc.vmobl.com:8088
MMS Proxy Host: 68.28.31.2
MMS Proxy Port: 80

A debug log can be found at http://hastebin.com/idofelenev I think the log cut off the attempt to download MMS with the proxy, but in previous attempts it looked similar.

Virgin Mobile US, Android 4.4.2, TextSecure 2.1.8

**Comment by privacy1776** [comment]
I have this same issue as others of not being able to download via MMS. I am on the Virgin Mobile network, and have found a workaround (kinda) to being able to receive MMS. My phone has 4g service, and I have noticed if I change my network settings from LTE/CDMA to just CDMA and disable WIFI, I can receive MMS's. I have tried downloading with just WIFI, it does not work, the only thing that worked for me was just using CDMA without LTE. 

Hope this can help someone fix this bug.

**Comment by NTICompass** [comment]
@privacy1776 I was just reading around the internet for info about my phone (LG Volt), and I found this: http://androidforums.com/threads/mod-universal-lte-virgin-mobile-apn-fix-wip-cm-aosp-4-4-x.840298/

This is for the Galaxy S3, so I don't know if it'll work on my or your phone.  I haven't yet tried, but maybe if you looked in the file, you can figure it out what it's doing and maybe it can help.

**Comment by privacy1776** [comment]
I'm sorry I forgot to mention that the stock messaging app works fine in any configuration, the issue is only with textsecure.

**Comment by privacy1776** [comment]
Any progress with this issue? This is the only deal breaker I have with textsecure, I cannot recommend it as people I know will want to use MMS and ask me why it doesn't work.

**Comment by mcginty** [comment]
@NTICompass that forum link you sent also just adds X-MDN: ##LINE1##. Looks like that's a solution that works for more than just you :).
