### ISSUE TITLE
Virgin Mobile (US) MMS failure

### ISSUE THREAD

**Issue by Veight** [WhisperSystems/TextSecure#1950]
I haven't been able to receive any MMS messages, even on the latest update while encrypted or not encrypted. I have the proper mms settings setup and still having issues. Suggestions?

**Comment by herbsmn** [comment]
Is there a plan to make it so MMS messages can be sent &/or received while Orbot is on? Right now, Orbot must be turned off to receive MMS messages, which seems like an open bug. Can you please reopen this issue?

**Comment by moxie0** [comment]
@herbsmn That's a bug you need to file with orbot, not with us.
