### ISSUE TITLE
 sending the push messages to other textsecure user, app is crashed.. 

### ISSUE THREAD

**Issue by harishkumar143** [WhisperSystems/TextSecure#1955]
09-29 13:00:03.492: E/AndroidRuntime(7006): FATAL EXCEPTION: SendReceveService-WorkerThread
09-29 13:00:03.492: E/AndroidRuntime(7006): java.lang.UnsupportedOperationException: This is supposed to be overridden by subclasses.
09-29 13:00:03.492: E/AndroidRuntime(7006): 	at com.google.protobuf.GeneratedMessage.getUnknownFields(GeneratedMessage.java:180)
09-29 13:00:03.492: E/AndroidRuntime(7006): 	at org.whispersystems.textsecure.push.PushMessageProtos$PushMessageContent.getSerializedSize(PushMessageProtos.java:2372)
09-29 13:00:03.492: E/AndroidRuntime(7006): 	at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:62)
09-29 13:00:03.492: E/AndroidRuntime(7006): 	at org.thoughtcrime.securesms.transport.PushTransport.getPlaintextMessage(PushTransport.java:300)
09-29 13:00:03.492: E/AndroidRuntime(7006): 	at org.thoughtcrime.securesms.transport.PushTransport.deliver(PushTransport.java:90)
09-29 13:00:03.492: E/AndroidRuntime(7006): 	at org.thoughtcrime.securesms.transport.UniversalTransport.deliver(UniversalTransport.java:88)
09-29 13:00:03.492: E/AndroidRuntime(7006): 	at org.thoughtcrime.securesms.service.SmsSender.handleSendMessage(SmsSender.java:88)
09-29 13:00:03.492: E/AndroidRuntime(7006): 	at org.thoughtcrime.securesms.service.SmsSender.process(SmsSender.java:62)
09-29 13:00:03.492: E/AndroidRuntime(7006): 	at org.thoughtcrime.securesms.service.SendReceiveService$SendReceiveWorkItem.run(SendReceiveService.java:273)
09-29 13:00:03.492: E/AndroidRuntime(7006): 	at org.thoughtcrime.securesms.util.WorkerThread.run(WorkerThread.java:46)
while sending the push messages from one user to other user  app is crashed  in logcat am getting the above error..

**Comment by rhodey** [comment]
most of the classes in this stack trace no longer exist on master, closing as stale.
