### ISSUE TITLE
reading conversations during phone call not possibly

### ISSUE THREAD

**Issue by Genis-Sage** [WhisperSystems/TextSecure#1959]
In older version (can't say precisely up to which one)
I could look into conversations during a phone call (with activated speaker).

Now I can open the overview of Textsecure,
but when I click on a conversation, nothing happens.

**Comment by rhodey** [comment]
I am unable to reproduce this on Nexus 5 running stock Lollipop with or without speakerphone. Any updates on this @Genis-Sage? What model of phone and Android version are you running? Any weird ROMs or "Privacy Guard" type apps?

**Comment by mcginty** [comment]
Also please post a debug log after trying to open a conversation.
