### ISSUE TITLE
mms problem.

### ISSUE THREAD

**Issue by karlhedderich** [WhisperSystems/TextSecure#1973]
http://hastebin.com/zuyuhekedu

This is the debug log from a friend.   She can't send group mms or receive group mms to certain friends.   She also cant send pictures to some individuals.  Textsecure is not set to override mms settings.

**Comment by apmon** [comment]
Is there a way to log the raw content of outgoing and incoming group MMS? Then it might be possible to help identify what TextSecure does differently to cause trouble with group MMS by comparing the output of good messages and what TextSecure produces.

**Comment by hberntsen** [comment]
Another example of a response which TextSecure does not understand but contains Message not found in the PDU:
https://gist.github.com/anonymous/f1c2a8b50e9e5ecf9023

Message was sent by an old dumbphone directly to me. My phone was in airplane mode when it was sent so it could have expired (max 12h between the sender sending it and me trying to receive it). It would be nice if TextSecure could display that the message was not found.

**Comment by mcginty** [comment]
Agreed @hberntsen. Created #2832 for that request, closing this issue since there's nothing actionable in it. Thanks!
