### ISSUE TITLE
Feature Request: Force Encrypted Sessions

### ISSUE THREAD

**Issue by Bujiraso** [WhisperSystems/TextSecure#199]
I would like to make it clear to anyone who texts me that I use TextSecure only. I think two modes could be added:
 * Paranoid - gives you the prompt to add an exception for the contact or fire a canned response
 * Restricted - fires a canned response, optionally notifies the user

Here's the idea:

```
If (incoming session == unsecure && no exception rule exists for this contact)
    If (message != key exchange request)
        If (mode == paranoid)
            Prompt user choice: 
                1. add an exception
                2. Send a canned response "I only speak privately! Please download TextSecure to talk to me!"
        If (mode == restricted)
            Send canned response.
            Notify user if they've opted in to receive refusal notifications.
```

So you set it to paranoid for the first few days to establish who'll do encrypted and who won't or can't. Once you're adequately happy with who can text you, stop everyone else from doing so.
For the record, even in the block mode you should get to see who tried to text you in the list.
The paranoid mode is a total convenience, but I think if I proposed just the block mode only -- it would seem too harsh!

This is my first issue I've ever opened, let me know if it needs changing/moving or something.

**Comment by patcon** [comment]
Nice idea, but I don't think this feature makes sense anymore without encrypted SMS -- if you only want to use secure channels, then you should disable TextSecure's SMS/MMS features and install an autoresponder app, of which there are a few.

I think this can be closed for now.
