### ISSUE TITLE
MIUI v5 - regular messages and Inbox

### ISSUE THREAD

**Issue by Pr0metheus2** [WhisperSystems/TextSecure#2014]
In MIUI v5, all regular messages are coming to Inbox only. A tick in setting "Receive all SMS" does nothing.
(Android version: 4.1.2, MIUI version MIUI-4.8.1

**Comment by dragonfrog** [comment]
I have the same problem.
MIUI version 4.12.5
Android version 4.1.1

There is a setting in System settings > Default app settings > Messaging

I've changed it to TextSecure, and it has no effect.

**Comment by dragonfrog** [comment]
Solved!  

Settings > Apps > (find the default messaging app) > Disable.

After that, the messages show up in TextSecure.
