### ISSUE TITLE
Retry send-via-data before manual SMS fallback

### ISSUE THREAD

**Issue by devurandom** [WhisperSystems/TextSecure#2015]
Currently, when send-via-data fails, e.g. because there is no internet connectivity, TextSecure will mark the message light green and offer to fallback to SMS ("tap to ..."). There is no way back to a light blue message / send-via-data, even if the internet connection comes back online.

TextSecure should immediately and automatically retry to send-via-data, as soon as the internet connection is back online. This should be made visually obvious, e.g. by keeping the light blue background instead of switching to light green, or by adding a spinning circle icon.

**Comment by rhodey** [comment]
related to #2098

**Comment by mcginty** [comment]
this is default behavior in 2.7
