### ISSUE TITLE
TextSecure gets stuck and doesn't send messages

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/TextSecure#2023]
Hello,
sometimes it happens to me that TS doesn't send messages. The bubble of the message never turns "dark blue", you know? I am correctly connected to the internet and all the other apps work fine.
What's worse is that the stuck message seems to prevent future messages from being sent, too. I have to reboot (just deleting the message not being sent doesn't work), and it's very annoying as many times I don't even realize until hours later -- because I rely on the "background sending"... bad idea. Unfortunately I don't have a debug log (I will post one when it happens again), but I was wondering if this is a known bug...?
Thank you

**Comment by mcginty** [comment]
Closing until we can get debug logs, thanks.
