### ISSUE TITLE
Bad encrypted message

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/TextSecure#2029]
Hello, I have to report a weird bug.
The other day I sent a message to a group chat.
"N" receives the message just fine, and answers back.
"A" responds to me in a private conversation (all this is happening via push), probably saying they couldn't read my message (?), but their message appears as "bad encrypted message". Annoyed by  this problem that has always plagued me since the very day I installed TextSecure (it keeps happening every once in a while), I end the secure session with A, unregister from the push service and register again. Now A can read my messages and I can read theirs.
Yesterday I posted another message to the same group. A could read it and respond, while N couldn't. However, when N writes me in a private chat between us alone, everything works fine (we read each other's messages).
This "Bad encrypted message" has been affecting me -- and my friends -- ever since we installed the application. Is there a reason why it happens?
Please find a fix, I feel embarrassed for recommending my friends this application and causing them all these troubles.

**Comment by rhodey** [comment]
no debug log or steps to reproduce, and OP is gone. closing.
