### ISSUE TITLE
Message received multiple times

### ISSUE THREAD

**Issue by TWfromSWD** [WhisperSystems/TextSecure#2040]
A Message i sent to one of my contacts on the 6th of October gets resend every now and then. My contact keeps receiving "Bad encrypted Message" from this date and time.

Don't know if the logs are helpful here, but just in case:
http://hastebin.com/otokudowol
http://hastebin.com/ocevirusuw

**Comment by TWfromSWD** [comment]
I got another Issue that's maybe somewhat related: When having no Internet connection while someone sends you a message, the message gets delivered multiple times after the connection is restored.
I don't know about the inner workings of TextSecure but is it possible, that TextSecure tries to resend the Message after some time has passed without a receipt? If so, then maybe the received messages should be checked by using some kind of unique ID so duplicates can be deleted automatically.

**Comment by riyapenn** [comment]
Is this still an issue? I will reopen if someone can you reproduce and provide an updated debug log.

**Comment by TWfromSWD** [comment]
Hasn't happened to me anymore in the recent versions of TextSecure so I think it's OK to close this issue.
