### ISSUE TITLE
[Feature request] Permanently display typed characters indicator

### ISSUE THREAD

**Issue by pejakm** [WhisperSystems/TextSecure#2046]
This is something that I miss very much in this app. I know this isn't needed for a push message, but for an SMS it is. Current implementation of displaying number only if 15 chars are left (first image) is not very convenient, because I don't know if I'm on a first set of 120 chars or did I write more than 120 chars. Images 2 and 3 are just a sketch: what if there would be option to display this indicator permanently.

https://mediacru.sh/d71d311f7466

Or something combined: number of characters left will be displayed when 15 chars are left to second message, and if you cross to second/third/... message a permanent message number indicator would be displayed. (Just a thought.)

**Comment by mcginty** [comment]
Closing in favor of #1841
