### ISSUE TITLE
After "Bad encrypted message", receiving my own messages echoed back at me

### ISSUE THREAD

**Issue by EvanK** [WhisperSystems/TextSecure#2054]
After about a week of successful encrypted communications with a particular contact, I started receiving garbled messages. We both ended the secure session, *deleted the conversation*, and restarted it, at which point I got a "Bad encrypted message" error.

After ending this second (and apparently unsuccessful) secure session, we are communicating unencrypted and I am using plain sms (not push) messages.

When I send a message to said contact, I am (after a delay) receiving **my own message** echoed back as if the contact had sent it to me -- complete with a notification alert.

This has happened twice now. The first time my own message was echoed back 6 minutes after I sent it. The second time, 25 minutes afterward.

Here's my debug log: http://hastebin.com/nuhewuwunu

**Comment by riyapenn** [comment]
Is this still an issue?  I will re-open if it is persistent and you can provide an updated debug log.
