### ISSUE TITLE
App toast message continuous and seems not be ended.

### ISSUE THREAD

**Issue by 76260865** [WhisperSystems/TextSecure#2081]
The SmsReceiver_currently_unable_to_send_your_sms_message message is toast continuous if the wifi network is connected without internet access or the network is unstable. it toasts the message all the time while we are in a group conversation, besides that all the members will received many repeated messages if you do not force stop the app.

  if (systemStateListener.isConnected()) scheduleQuickRetryAlarm();

seems systemStateListener.isConnected() return true but have no internet access.

**Comment by rhodey** [comment]
no longer able to reproduce on 2.10.2, also this string resource and related code are all gone now, closing.
