### ISSUE TITLE
problems with nondefault textsecure

### ISSUE THREAD

**Issue by karlhedderich** [WhisperSystems/TextSecure#2090]
I have two friends who both say that when textsecure is not set to be the default messenger it will intercept normal group messages.  Both friends do use non standard texting apps as the default.  Does anyone know if this behavior happens when textsecure isn't the default and the standard messaging app is the default?

**Comment by riyapenn** [comment]
Dupe of https://github.com/WhisperSystems/TextSecure/issues/1931
