### ISSUE TITLE
"Could not grab logs from device" error message missleadingly displayed when without Internet access.

### ISSUE THREAD

**Issue by squisher** [WhisperSystems/TextSecure#2092]
Please improve the error message: "Could not grab logs from device" which is displayed when trying to submit a debug log while there is no Internet connectivity. It sounds as if there is a problem collecting the logs, and does not indicate at all that a connection to the pastebin is not possible.

**Comment by rhodey** [comment]
hey @squisher thanks for reporting this bug, this error message is actually caused by an external library used by TextSecure (but also written by open whisper systems). an issue has been filed with that library for this bug here >> https://github.com/WhisperSystems/libpastelog/issues/6
