### ISSUE TITLE
[UX] Confirmation / return receipt UI should show more useful state than it currently does

### ISSUE THREAD

**Issue by gordon-morehouse** [WhisperSystems/TextSecure#2095]
Currently the confirmation / return receipt UI shows two states:

* Receipt confirmed
* Absence of receipt confirmation

This could be more useful. It isn't so great when the remote user is e.g. in a building with poor data coverage, has their phone off, etc. Currently I often have messages get through which are never confirmed, but definitely received ... eventually.

One implementation wrinkle I can think of might be a choice between "confirm all received messages, eventually" versus "give up on confirmation after a timeout." Either way, I believe presenting information on the state of message confirmation, rather than the presence or absence, is valuable to the TextSecure user sending messages.

**These proposals are mutually exclusive.**

## Proposal 1: Confirmed, Awaiting Confirmation, Gave Up

* For messages which have been confirmed, TextSecure MUST (and does) show a "confirmed" UI element.
* For messages which have been sent but not confirmed, TextSecure SHOULD show an "awaiting confirmation" UI element. My suggestion: perhaps a clock superimposed on an envelope.
* For messages on which confirmation has been given up (perhaps after an hour), TextSecure SHOULD show a "gave up confirmation" UI element. My suggestion: A question mark superimposed on an envelope.

## Proposal 2: Confirmed, Awaiting Confirmation, Confirmation Is Taking a Really Long Time but If The Message Is Received It Will Eventually Be Confirmed

* For messages which have been confirmed, TextSecure MUST (and does) show a "confirmed" UI element.
* For messages which have been sent but not confirmed, TextSecure SHOULD show an "awaiting confirmation" UI element. My suggestion: perhaps a clock superimposed on an envelope.
* For messages on which confirmation is taking a really long time (say, more than 1 hour), TextSecure SHOULD show a "waiting a long time for confirmation" UI element. My suggestion: either a clock + question mark / interrobang (‽), or just a question mark or interrobang superimposed on an envelope. If the recipient phone is turned on 3 weeks later and old messages still exist on the sender phone, they will be confirmed.
* For unconfirmed messages which are deleted, TextSecure SHOULD discard incoming confirmation acknowledgements.

Proposal 2 should be subjected to threat analysis. (What if the recipient doesn't want their receipt of the messages confirmed after a while?) Proposal 1 seems easier to implement while still *actively* giving the user more understanding of the status of their message - either we're still awaiting confirmation for a reasonable time or we gave up after a reasonable time but the contact may or may not have received the message.

**Comment by riyapenn** [comment]
Related to #2055

**Comment by gordon-morehouse** [comment]
This feature request is mostly obsolete with the adoption of the new double-checkmark system. It's much easier to read. #2055 is conceptually related, but since I wrote it and the UI has moved on, I'm gonna close it.
