### ISSUE TITLE
SMS sending fails with spaces or hyphens in phone number

### ISSUE THREAD

**Issue by textsecureuser** [WhisperSystems/TextSecure#2102]
Importing contacts sometimes creates hyphens or spaces in the stored number. Textsecure fails to send SMS to these invalid numbers; however the regular SMS application on Android fixes this issue automatically by ignoring these characters.

**Comment by rhodey** [comment]
closing because we have no debug log and are unable to reproduce. if you are able to provide a debug log of this behavior and steps to reproduce I will reopen the issue.
