### ISSUE TITLE
Missing group messages when user is offline

### ISSUE THREAD

**Issue by josefroth** [WhisperSystems/TextSecure#2108]
Hi,

I have a group chat with two friends of mine. In the last days I noticed that I do not receive messages in this group chat while my device has no internet connection (for example because it's rebooting or I'm in a building where I have no signal). I would expect that these messages are delivered to me as soon as my device has an internet connection again.

Android version: Cyanogen Mod 11 (Android 4.4)
TextSecure version: 2.2.0

Kind regards,
Josef

**Comment by rhodey** [comment]
@josefroth we've made a bunch of changes since you opened this issue that greatly improve message delivery reliability, I expect this issue is now resolved. please check back in if it is not and include a debug log or detailed steps to reproduce and I will reopen. @fpsal that is a separate issue.
