### ISSUE TITLE
Readability of group creation message

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#2128]
There is a small text in the ConversationActivity after creating a group. At the moment (after changes regarding AppCompat It think) it's not easily readable with white text on the light-grey background. I think it should be changed back to dark grey like before.

![screenshot_2014-11-24-15-41-14](https://cloud.githubusercontent.com/assets/5296073/5166605/c1ebc2e4-73f1-11e4-854f-1cb268d85a63.png)

**Comment by mcginty** [comment]
Fixed this a couple commits ago, we no longer rely on the color styling of android's small text appearance.
