### ISSUE TITLE
Feature Request: Notification options per contact

### ISSUE THREAD

**Issue by ronem** [WhisperSystems/TextSecure#213]
I know this is a bit above and beyond the typical SMS functionality, and I totally understand if this gets dropped to the bottom of the list, but I do find I often need to find out about some SMSs far more urgently than others -- in my case, I have a critical server that tells me when it's down: I'd like that one to scream loudly at me even if I'm sleeping deeply. Some unknown number texting me about a dream vacation that I have won I am quite happy to sleep thru. :)

Awesome work regardless, team!
R

**Comment by patcon** [comment]
Dup of https://github.com/WhisperSystems/TextSecure/issues/354?

**Comment by ronem** [comment]
Fair point. Thanks!. :)
