### ISSUE TITLE
Menu in English although UI set to another language

### ISSUE THREAD

**Issue by bungabunga** [WhisperSystems/TextSecure#2145]
Steps to reproduce:

1. set language to non-english (tested in Slovenian and Deutsch)
2. go to menu/my identity key/scan to compare
3. go back to messages
4. click menu - the menu is in English (temporarily)

**Comment by rhodey** [comment]
also not able to reproduce :/ are you running stock Android @bungabunga? any custom ROM or anything?

**Comment by agrajaghh** [comment]
I'm having a similar issue sometimes: I've set TS to english but the android system language is german. Sometimes the menu is displayed in german. I didn't discover a pattern yet, it seems pretty random... I'll try to observe it better the next time it happens.

**Comment by bungabunga** [comment]
not able to reproduce on the latest TS version. closing...

@rhodey stock rom. the menu was only in english until closing TS.

@agrajaghh i could reproduce this every time so i guess this is another issue

**Comment by bungabunga** [comment]
I'd say that this is another issue. The one i described was reproducible every time with the steps i described above and the result was that the manu temporarily turned from custom language to English. It would probably be better to fire another issue with your symptoms?
