### ISSUE TITLE
double/echo message tone - when inside the app

### ISSUE THREAD

**Issue by cybershambles** [WhisperSystems/TextSecure#2148]
I've messaged my friend... closed TS and waited for the reply.. 
Single standard message tone

Replied and left the application open viewing the previous messages...
double/echoed message tone..

It sounds really really interesting.. so feature?

**Comment by bisam** [comment]
Same problem here. It happens with SMS and push-messages. Also only if Textsecure is unlocked.

**Comment by jeremymasters** [comment]
Over the weekend I ascertained that it happens to me when I already have one message from a contact and/or I'm in the thread.

**Comment by bisam** [comment]
Problem got fixed for me in the newest version. There now is an option for the number of times the notifications should repeat. It was set to "repeat one time" for me. After I changed it to "not repeat" it worked :)

**Comment by rhodey** [comment]
thanks for checking back in @bisam is anyone else able to resolve this issue using the updated version and steps @bisam provided?

**Comment by jeremymasters** [comment]
yes, I am now having the expected amount of notification sounds. :)

**Comment by icyfyer** [comment]
This bug seems to have been resolved for me too. Thanks to the team for the good work. Much appreciated.

**Comment by rhodey** [comment]
awesome :D closing as resolved, if anyone is still having issue with this please check back in so someone can reopen this.
