### ISSUE TITLE
Android Lollipop lock screen notification privacy

### ISSUE THREAD

**Issue by dvogel** [WhisperSystems/TextSecure#2151]
It would be great if I was able to see the contents of the "TextSecure is unlocked" notification while on the lock screen but treat actual message notifications as private.

Furthermore, it would be good if TextSecure could provide an option to treat the sender vs content as private separately. For example, I would like to see the sender but not the message while on the lock screen.

I have no idea whether this is possible via the new Lollipop APIs but it seems like the message content could be easily omitted from the notification by TextSecure.

**Comment by riyapenn** [comment]
This should be available now through Settings > Notifications > Display in notifications.
