### ISSUE TITLE
"Permanent TextSecure communication failure!" on Android 2.3.7

### ISSUE THREAD

**Issue by WPettersson** [WhisperSystems/TextSecure#2152]
For about the last two days, I've been getting the notification "Permanent TextSecure communication failure!" with the text "TextSecure was unable to register with Google Play Services. Com". After "Com" I'm was sure there were more letters but they are cut off. I don't know how newer Android versions work, but on 2.3.7 the notifications don't scroll so only by reading through code can I find the text that says "Communication over the data channel has been disabled, please try re-registering from the TextSecure settings menu."

Of course, the next problem I have is that I cannot find any "re-register" option in the settings menu. Again, reading code shows me that the RegistrationActivity intent is launched by enabling "Push messages", which is already enabled.

So, I do that. And now, finally, I get a warning message. Google Play Services needs to be updated to use this. So there's the issue. I'm actually guessing that I didn't need to re-register, I probably just needed to update Google Play Services. Can't say for sure though, as I've already de-registered.

Anyway, the original notification is thrown up by a failed call to GooglePlayServicesUtil.isGooglePlayServicesAvailable(context). Instead of just checking for "resullt != ConnectionResult.SUCCESS", TS could also check for the other possible return values and tell the user the actual reason behind the error.

**Comment by mcginty** [comment]
This sounds like an issue with the phone's storage capacity more than us missing something in our Play Services code. It appears google's updates are pretty big if 67MB doesn't cut it! Unfortunate, but probably messaging that should be done by the Play Store since it's doing the updates?
