### ISSUE TITLE
Notifications miss a category for Android 5.0 "Silent mode"

### ISSUE THREAD

**Issue by apollo13** [WhisperSystems/TextSecure#2156]
Adding the MESSAGE category to notifications would allow TextSecure's notification as messages and even show up in silent mode if the user configured it to do so (settings -> sounds & notifications -> interuptions).

Details are in the closed PR #2155. To implement it, the support library has to be upgraded to v21 first.

**Comment by rhodey** [comment]
looks to me like we're doing this now https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/notifications/MessageNotifier.java#L202

closing as resolved.
