### ISSUE TITLE
cant send SMS on "fairphone"

### ISSUE THREAD

**Issue by orimpe** [WhisperSystems/TextSecure#2168]
My Phone is a Fairphone with Android 4.2.2 rooted

When i send a sms with Textsecure on a normal Device without Textsecure, the sms can't send and at the Info of the sms is "Übertragung: PENDING".

The Push Message to other Textsecure Users works.

Settings:
Push messages: enabled
Receive all SMS: enabled
Receive all MMS: enabled

Allow outgoing SMS to:
TextSecure users: enabled
Ask before sending SMS: disabled
Non-TextSecure users: enabled

------Update 03.12.2014-----

This is my Log, after i try to send a simple SMS, I unregister my Phone and try again.
It does not work.

<code>--------- beginning of /dev/log/main
W/dalvikvm(26564): VFY: unable to resolve static method 1216: Landroid/provider/Telephony$Sms;.getDefaultSmsPackage (Landroid/content/Context;)Ljava/lang/String;
W/ThreadDatabase(26564): Trimming thread: 1 to: 222
E/Looper  (26564): WARNING: The Looper class instance count has over a limit(100). There should be some leakage of Looper or HandlerThread.
E/Looper  (26564): Looper class instance count = 101
E/Looper  (26564): Current Thread Name: Thread-3753
E/Looper  (26564): WARNING: The Looper class instance count has over a limit(100). There should be some leakage of Looper or HandlerThread.
E/Looper  (26564): Looper class instance count = 102
E/Looper  (26564): Current Thread Name: Thread-3754
E/SpannableStringBuilder(26564): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(26564): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(26564): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(26564): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(26564): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(26564): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(26564): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
E/SpannableStringBuilder(26564): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
D/libc-netbsd(26564): getaddrinfo: textsecure-service.whispersystems.org get result from proxy >>
E/NativeCrypto(26564): ssl=0x5ef8acf0 cert_verify_callback x509_store_ctx=0x61472a40 arg=0x0
E/NativeCrypto(26564): ssl=0x5ef8acf0 cert_verify_callback calling verifyCertificateChain authMethod=ECDHE_RSA
W/TextSecurePreferences(26564): Setting push registered: false
W/ThreadDatabase(26564): Trimming thread: 1 to: 222
</code>

**Comment by sirld** [comment]
I uploaded a debug log file now:

https://gist.github.com/anonymous/580f03d9f57075c7daab

I reset the phone to factory settings, which sould have cleared all databases, did a fresh install of Text Secure, but still have the same problem. I tried:
- switch off WiFi
- make Text Secure default app / disable as default
It all didn't have an effect: the message is not being sent, it just sits there, light green and pending... it's the same for secure and unsecure SMS.

Still: the stock SMS app works perfectly fine!

To me it seems like Text Secure just doesn't like SMS anymore... is there a workaround?

**Comment by sirld** [comment]
Alright, I just updated TextSecure to version 2.3.3. Sending SMS still doesn't work. I uploaded another log file:

https://gist.github.com/anonymous/6bbc4648562813309ad0

It seems to actually try (see last 3 lines) but fail for some reason...

Anything I should try?

**Comment by jeremymasters** [comment]
2.4.1 is the latest version.

**Comment by sirld** [comment]
Oh, alright... but why can I not install that...? I can see the latest version in the PlayStore on my laptop but not on my phone.

**Comment by sirld** [comment]
Oh, now I got it! Here's the latest log:

https://gist.github.com/anonymous/f318bf4509241cc58411

**Comment by moxie0** [comment]
Are you using wifi calling or something?

**Comment by sirld** [comment]
After I reset my phone I tested TextSecure without having SIP installed. So the log files are without SIP. (In fact, now I have intalled CSipSimple - which also worked fine together with TextSecure <2.3.?)

But as I mentioned: I have a working SIM card and also the Android SMS app sends and receives SMS.

**Comment by sirld** [comment]
I updated TextSecure to version 2.4.2, but it's the same problem. Here 's the log https://gist.github.com/anonymous/0d2bb90789a770a7d1ce

**Comment by rhodey** [comment]
I have absolutely no idea what is going on in the above log. is fairphone still unable to send SMS, on a fresh install?

at least one person in [this thread](https://forum.fairphone.com/t/secure-text-messaging/2512/11) seems to have TS running on a fairphone.

also, unfortunately, fairphone seems to have an awful SMS reputation:
https://forum.fairphone.com/t/sent-sms-incorrectly-marked-unsent-after-fp-restart-do-you-also-have-this-issue/4669
https://forum.fairphone.com/t/sending-sms-with-contact-from-contacts-does-not-work-german-localization/89
https://forum.fairphone.com/t/fp-does-not-receive-sms/3252
https://forum.fairphone.com/t/fp-crashes-restarts-reboots-when-i-make-a-call-sms/5007
https://forum.fairphone.com/t/weird-sms-behaviour/1326
https://forum.fairphone.com/t/cant-receive-some-sms-and-mms-messages/1699
https://forum.fairphone.com/t/text-messages-sms-problems/4423

**Comment by brumsoel** [comment]
> is fairphone still unable to send SMS, on a fresh install?

Sending SMS on a fairphone through TextSecure works here, never had any problems.
(disclaimer: only used it with one SIM, but it's a dual SIM phone)

**Comment by generalmanager** [comment]
Two friends of mine also have Fairphones and never had any problems with TS and SMS. I don't think this has ever been specific to this device, but merely a glitch or an old bug which has long been fixed.

Am 11. April 2015 14:43:00 MESZ, schrieb brumsoel <notifications@github.com>:

**Comment by rhodey** [comment]
thanks for the context @brumsoel & @generalmanager :)

**Comment by arnt** [comment]
I've seen this on a fairphone occasionally. It's reproducible for a while (hours), then it goes away.

ServiceRequirement.isPresent() creates a new TelephonyServiceState every time it's called instead of e.g. having a member or even static variable. Something seems to call it in a loop, which creates a large number of TelephonyServiceState threads, and on the fairphone (four cores, mediatek-modified android) a sanity check hits.

**Comment by arnt** [comment]
Looking at it more, I suspect the issue is related to mediatek's customisations to support two SIM slots.

If I compiling Signal from source, it should interoperate cleanly with the regular version, right? I don't need to do anything in particular?

**Comment by moxie0** [comment]
@arnt Yep the source build is exactly the same as the production build (reproducibly, even), but when you build from source yourself the APK signature won't match so you won't be able to cleanly install *over* an existing install (you'd have to uninstall first).

**Comment by arnt** [comment]
Fixing the Looper issue shows another bug behind it. I wonder whether the Mediatek code calls PhoneStateListener when it should...

I'm not sure this is worth fixing. I want to see whether it hits the Fairphone 2 (android 5.1.1), if it is I'll spend more time on it, if it only occurs on mediatek's forked android 4 I may not bother.

**Comment by arnt** [comment]
The problem hasn't shown up on the Fairphone 2 after three weeks, so I'm 99% sure the actual bug is in Mediatek's two-SIM code for Android 4. Since Android 4 is a while ago, I think a workaround has very little value, not enough to offset the risk of a new bug that affects more devices.
