### ISSUE TITLE
Timestamps and delivery "checkmarks" barely visible

### ISSUE THREAD

**Issue by lndshrk** [WhisperSystems/TextSecure#2170]
Tested on both a Nexus 4 on CM11 and Nexus 5 on 4.4.2..

Since the latest update, the color/luminance of the timestamp legend and the "delivered" indicator are so close to the background color of the bubble that they are nigh invisible.  Cannot tell EXACTLY what update caused this, but between TS 2.2.0 and the current version - the display changed to become significantly less legible.

**Comment by gordon-morehouse** [comment]
See #2095 for a feature request that'd blend well with this bug (which IMO is a bug, I agree with @lndshrk)
