### ISSUE TITLE
Can't click MMS notification

### ISSUE THREAD

**Issue by jjculber** [WhisperSystems/TextSecure#2182]
When I receive an MMS, I get a notification which contains a preview of the message. With MMS, when I tap the notification, it does nothing. I can tap it many times and it does not open the message/thread in TextSecure. SMS works properly, though. When I click an SMS notification, it opens the TextSecure app.

If further explanation is needed, I could probably provide a video.

**Comment by rhodey** [comment]
I'm not able to reproduce this on my nexus 5 running stock lollipop and TS 2.5.3, is this still a problem @jjculber?
