### ISSUE TITLE
Group message issues after device change

### ISSUE THREAD

**Issue by benedetto** [WhisperSystems/TextSecure#2185]
Recently as I got a new phone, I experienced some issues with group messaging. As I cannot say, how far they are related, I'll just describe, what happened.

- First of all did a backup of the messages on the old phone.
- Tried to unregister push on the old phone. This didn't work with some rather generic error message (something like "unable to perform task" or so, don't remember exactly).
- Installed Textsecure on the new phone, registered for push.
- Imported backup from the old phone.

So far, so good. The hassle began, when the first group message arrived.

- The message is shown in a conversation named "Unknown group". There's no way for me to change the group name or even leave the group to be readded.
- After someone else has added me to the group a second time (although I was already part of the group according to his phone), I can see the group name and receive messages – but only from the one who readded me. Messages from other members are not shown.
- However, now I can leave the group. After being readded again, I can now receive all messages from any group member again.

**Comment by rhodey** [comment]
this issue was posted first but I'm gonna close this because recent discussion has moved to #2581 and they're basically the same issue.
