### ISSUE TITLE
Daily MMS notifications

### ISSUE THREAD

**Issue by NTICompass** [WhisperSystems/TextSecure#2196]
Because of a 401 error, TextSecure can't download MMS.  Because of this, when I get sent an MMS, I get notified daily.
Each day, my phone's LED flashes and I have a notification in the notification bar.  In the conversation, it shows another "download" button.
Is there a way to stop these daily notifications?

**Comment by rhodey** [comment]
you should be able to long click to select the MMS notification message, then delete the message. after doing this TextSecure should stop attempting to download the message. If this doesn't work please reply back to this issue and it will be reopened.
