### ISSUE TITLE
Messages received after several days

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/TextSecure#2200]
My contacts and I are experiencing serious issues lately. We are all receiving messages from some days ago -- a friend of mine just got a message I sent him on Nov 30. What's funny is that the messages are marked as delivered on the sender's phone.
Of course we all connect to the internet every day and this behaviour is bugging us greatly.

**Comment by rhodey** [comment]
@manhole11 still having this issue? was it specific to SMS, MMS, push messages, or something else?

**Comment by mcginty** [comment]
GCM as a message transport is out, going to close this in anticipation of websockets having solved this delivery reliability issue.
