### ISSUE TITLE
Feature: Blocking

### ISSUE THREAD

**Issue by xanthine** [WhisperSystems/TextSecure#222]
Blocking by user-specified phone number, via something like an email filter rule where the messages from the number are deleted upon receipt and no notification is given.

**Comment by mxa** [comment]
This is a much needed feature. As it has been mentioned already the CyanogenMod text app has this feature and it is the main reason why I switched to CM the first place. TextSecure is not practical in countries with a high spam MMS/SMS volume.

**Comment by digitalfreak101** [comment]
I realy would appreciate this feature as spam by sms from unknown numbers is getting more often in the last month. Mostly containing virus links for android or something bad.
I would like to have a white/black list including the option to block all sources not in my contacts. Optional a dedicated spam "folder" would be nice.
