### ISSUE TITLE
SMS never delivers to some contacts, only MMS does

### ISSUE THREAD

**Issue by prestonrhea** [WhisperSystems/TextSecure#2223]
Since installing TextSecure on my Verizon Galaxy S5, I cannot send SMS texts to two specific recipients: my parents. I can send them to my sister and to everyone else in my contacts I've tried.

When I want to text to my parents, I have to send a group SMS or attach a photo to my SMS to make it an MMS to them. I receive all texts from them fine. They both have iPhones.

**Comment by prestonrhea** [comment]
Debug log: https://gist.github.com/anonymous/1a5a3efa4caad611750f

Thanks for your help @moxie0!

**Comment by zariok** [comment]
Still broke unless I reformat the DNs  on 2.4.0

**Comment by zariok** [comment]
Appears resolved in 2.5.1 (Samsung SMG900V)

**Comment by rhodey** [comment]
thanks for checking back in @zariok :D
