### ISSUE TITLE
Testing guidelines needed

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#2244]
As there are often issues with new features or fixes, there should be a guideline (or better an automated GUI test) to ensure functionality.

For these tests it would be great to have a sample database to use
~~or at least~~ and in addition dummy recipients and groups provided by the TS server that can be stressed.

**Comment by riyapenn** [comment]
No database, or automated, but general general guideline here: http://support.whispersystems.org/customer/portal/articles/2141240-testing-guidelines

**Comment by McLoo** [comment]
@riyapenn great. thanks. enough guideline to get this closed.

Only thing I miss, is the testing state "upgraded from a former/previous version if there were database changes"

This should be (linked) in building.md IMO
