### ISSUE TITLE
Contact List: Show all Numbers of one Android Contact

### ISSUE THREAD

**Issue by Deccoy** [WhisperSystems/TextSecure#2257]
If you have one Android contact with 2 mobile phones (= two Independent Text Secure Installations)  only  one of the cell phone numbers appears in the contact list under "Textsecure users". 

If you would like to add the second " hidden" number to a group, you cannot do it, because the number is not visible in the list.

Android 5 / latest TS Version

**Comment by equescalculi** [comment]
This seems to be fixed in v2.23.0. I guess this issue can be closed.
