### ISSUE TITLE
Ability to edit messages for security

### ISSUE THREAD

**Issue by bottiger** [WhisperSystems/TextSecure#226]
My understanding of OTR protocol is that you are guarantied to be the sender of a message when it is received but the protocol also guaranties that nobody can prove a message was sent by you at a later point. Like a real life conversation. "If know you said something to me, but I can not prove it at a later point".

This is great but unless TextSecure somehow allows people to alter the past of a conversation the app itself does provide a reasonable proof/indication that I said something in the past.

Example: My friends phone is ceased and he is compromised to unlock TextSecure. OTR does not in any way guarantee I had our long conversation but since my friend is not a skilled hacker/developer able to alter the TextSecure database the conversation itself it a pretty good indicator/proof of the conversation being authentic.

Solution: Add the option to edit a message (any message) from the Android Context Menu just like you can delete a message. Maybe also add the ability to insert a new message next to it.

**Comment by untitaker** [comment]
https://github.com/WhisperSystems/TextSecure/issues/1764#issuecomment-51551662:

>From a security perspective while you can prove you possess something, there's no such thing as proving you or other parties do not possess something. Because of that, any ephemeral messaging solution will, at best, be considered one party politely asking the other to "do the right thing."

**Comment by uiken** [comment]
I think the ability to edit messages would help deniability a lot. It would be a nice feature to have.

**Comment by moxie0** [comment]
thanks but i don't think we're going to do this
