### ISSUE TITLE
Error on transmission results in large message, crashing TextSecure.

### ISSUE THREAD

**Issue by phryneas** [WhisperSystems/TextSecure#2271]
Hi,

the scenario:

* B sends an image to A over encrypted channel.
* There is an error on transmission
* A cannot decrypt the message 
* Textsecure interprets the message as plaintext (in the pane with all chats it is visible in preview as some base64-string)
* On opening of the chat Textsecure tries to render the multi-kilobyte "text" message
* Crash

This is critical as A can not chat with B any more. The only hotfix so far seems that B sends 10-20 messages to A, so the corrupted message is not visible on opening the conversation, but only after scrolling.

It is still impossible to scroll behind the corrupted message this way, so this is just a temporary hotfix.

Suggested fix: all text messages with more than X characters are rendered only partially and have to be clicked on to be shown completely. This will allow for the corruped message to be rendered partially and removed by hand.

(As a side effect this will allow for easier scrolling beyond long messages)

**Comment by rhodey** [comment]
this should now be resolved thanks to #2294, if you're still having this issue I'll reopen this :)
