### ISSUE TITLE
Samsung Note 3 & Note 4: unclickable - notifications in pull down menu and new key exchange prompts in app

### ISSUE THREAD

**Issue by cyanfr** [WhisperSystems/TextSecure#2274]
For both the unmodified Samsung Note 3 (4.4.2 with build N900FUVUENK3) and Samsung Note 4 (4.4.4 with build N910FXXU1ANK4), when messages are received, the notifcation appears.  But when the pull down menu from the home screen (ie not in app) is used to view the notification, tapping the notification does nothing.  User is not taken into the app to view the message.  The "Mark as Read" in the notifcation area does work however.  Just not tapping the message.  On other phones doing so takes the user to the message in app.

Likewise, when in app, and user receives a message for the first time from any other TextSecure user, and the app prompts in app for the key exchange, while the message says to tap, tapping does nothing.  The app does not respond in any way to tapping the exchange request message.

This occurs even after waiting for a day or so.  The only way to resolve is for both parties to remove the app, re-install, and re-initialize.  This does not resolve the tapping issue.  That still exists, but the keys seem to auto-exchange on their own at that point.

**Comment by cyanfr** [comment]
This issue seems to have been resolved in the last public update (2.4.1). Pull-down notifications on Note 3 & 4 now respond to taps.

**Comment by rhodey** [comment]
thanks for checking back in @cyanfr :)
