### ISSUE TITLE
low resolution for a/v-attachment icons

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#2280]
The icons for audio and video attachments are only available in 72x72 which makes them look pretty ~~ulgy~~ retro in the draft preview. Besides that the media message bubble is too large for them.

Copied both draft preview icons next to each other:

![unbenannt](https://cloud.githubusercontent.com/assets/5326916/5583312/a42679c4-9076-11e4-9f8b-81ca10a43d9f.png)

And somehow they both don't fit into the app design...

Would b more consistent to have ic_attach_audio_holo_light/dark ![ic_attach_audio_holo_light](https://cloud.githubusercontent.com/assets/5326916/5583380/2e17a166-9078-11e4-86b5-c8655d7b46ad.png) and ic_attach_video_holo_light/dark ![ic_attach_video_holo_light](https://cloud.githubusercontent.com/assets/5326916/5583382/384f1ede-9078-11e4-8b51-3afe762358cc.png) indicate the media type.

**Comment by mcginty** [comment]
That 8-bit feel :pager:. Yeah, we can probably yoink some of the latest material icons for the cause.

**Comment by McLoo** [comment]
thanks @sebkur
