### ISSUE TITLE
Possible Denial of Service via Federated Server

### ISSUE THREAD

**Issue by Fuzion24** [WhisperSystems/TextSecure#2291]
Cyanogmod WhisperPush is currently holding my account hostage.  It will not allow me to unregister and therefore I am not able to register with TextSecure.  I also am not able to use WhisperPush as the phone I registered with was wiped and sold. WhisperPush's registration seems to be broken server-side and they don't seem to be responsive.  While I agree that this is Cyanogemod's issue, I do see this as a design flaw of TextSecure as you could create a DOS for users.

There seem to be a fair amount of people having this issue.  See the following:

https://github.com/daveio/whisperpush-unregister/issues/11
https://jira.cyanogenmod.org/browse/CYAN-4512
http://support.whispersystems.org/customer/portal/questions/8112872-how-to-register-after-exhausting-all-options-for-unregistering-from-whisperpush

I apologize if this is a proper issue, I just wanted to start some discussion around it.

**Comment by moxie0** [comment]
We have no control over WhisperPush or Cyanogenmod's servers.  You'll need to contact them for support with their product.
