### ISSUE TITLE
Message delivery unreliable

### ISSUE THREAD

**Issue by devurandom** [WhisperSystems/TextSecure#2293]
Currently message delivery is unreliable. It often happens that I send a message to someone, but do not get a message receipt (check-mark icon). Messages sent later get a receipt. When I talk to the person a few hours later, they tell me they did not receive the message.

This issue is not limited to me sending, but also happens the other way around. It also happens for other people, as I have been told. It also happens for the message receipts themselves – sometimes a message arrives on my phone, but the sender never receives the receipt. The CyanogenMod integrated WhisperPush service is not involved. The issue happens between stock Android users, as well as with CyanogenMod users.

From reading other issues I understand that GCM does not offer reliable delivery. I wonder if the equivalent of [XEP-0198 section 4 "Acks"](http://xmpp.org/extensions/xep-0198.html#acking) could be implemented on top of it in TextSecure.

**Comment by devurandom** [comment]
Possible duplicates: #679, #970, #1971, #2098, #2238

**Comment by moxie0** [comment]
duplicate
