### ISSUE TITLE
Show if other person is typing

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/TextSecure#2295]
In my opinion it would be a great enhancement to see if the other person is typing at the moment. If I write long texts for example and click on send but keep writing to send another message I often get interrupted because the other person doesn't know that some more messages will follow...

Would there be any chance to add something like "xy's typing" (WhatsApp) or some "..." (Hangouts)? Or do you think there's no need for it? Of course (if possible) you should be able to disable this feature if you think it invades your privacy!

What do you guys think?

**Comment by Undeterminant** [comment]
SMS doesn't allow that in the protocol, so, I don't see why it would be supported by an SMS app.

**Comment by Mihahn** [comment]
But what about push messages? I guess I'm not the only one who uses TextSecure just for push messages :)

**Comment by moxie0** [comment]
@Undeterminant We actually consider encrypted SMS less and less these days.

@Mihahn Thanks for the suggestion, but it's not going to happen anytime soon.
