### ISSUE TITLE
[Feature Request] Auto Forward SMS

### ISSUE THREAD

**Issue by 4science** [WhisperSystems/TextSecure#2298]
I have a couple androids floating about and I travel a lot, I was looking to setup some automatic forwarding of SMS so that friends of mine (who are silly and don't use this great service) can contact my local number still and it will be forwarded out of the country to my other number via the text secure protocol.

Warning setting a cap on the number of messages per unit time or something similar may be wise, don't want people to abuse/flood/DDOS and bring down the service.

**Comment by mcginty** [comment]
That sounds like an idea for a third party to make that's not us :).  The less we can touch SMS, the better.
