### ISSUE TITLE
Emoji-Button

### ISSUE THREAD

**Issue by kaz4r** [WhisperSystems/TextSecure#2300]
Dear developers,

first of all I would like to say thank you for your hard and great work!

I am using TextSecure for nearly one year now -  with my family, friends and in my circle of acquaintances.

During Christmas time a lot of those guys got new phones or updated to the newest available Android versions, running now mostly Android KitKat.

The problem such "normal" end-users nowadays face, is the missing Emoji-button within the version running on KitKat.
Unfortunately not everyone knows how to install alternative keyboards or is willing to do so. And not every type of keyboard offers the functionality of "Emojis" (e.g. on Huawei Ascend P7).
There are several reasons I somehow could understand those people.
 It's a pity - if such users switch back to commercial messenger apps because of this "problem".

It would be great if you could add the Emoji-button once again in the KitKat-version, so we could spread TextSecure even wider.

Thank you for your time and consideration.

kaz4r

**Comment by wp9015362** [comment]
> mcginty wrote:
> 
> use internal emoji pane for all android versions #2302 

+1

Any update?

It would be much appreciated if this change would land in TextSecure.

Regards
