### ISSUE TITLE
Can't seem to send unecrypted MMS on T-Mobile

### ISSUE THREAD

**Issue by doctorzook** [WhisperSystems/TextSecure#2303]
Hi Folks,

I seem unable to send an MMS using TextSecure. This is on T-Mobile in the US with an HTC One M2. All I get is an error that says, "Error sending message".

I'm not so expert at reading debug logs, but this looks like it might be the root of the problem:

> Connection to http://mms.msg.eng.t-mobile.com:80 refused W/OutgoingMmsConnection( 6786): at
...

A few other notes:
- I get the same error whether I send a "secure MMS" or an "insecure MMS".
- I can send via secure TextSecure message: no error, and the message goes through,
- SMS works. (But I can't send a picture, of course.)
- I have tried both with the automatic settings, and by manually setting the MMSC URL setting to the one found [here](https://support.t-mobile.com/docs/DOC-2383) (http://mms.msg.eng.t-mobile.com/mms/wapenc). Neither seems to work.

Any help would be greatly appreciated.

Thanks!

**Comment by McLoo** [comment]
@doctorzook please post the link to the complete debug log uploaded by TextSecure.

**Comment by doctorzook** [comment]
Ah! Here you go: https://gist.github.com/c560aa4dbb813e40fd8f

**Comment by apmon** [comment]
I couldn't determine from the logs, if it is indeed the case, but could it be related to IPv6 and #1937 ?

T-Mobile US has moved over to using IPv6 on its 4G networks and TextSecure / Android does not correctly handle this case.

If this is the issue, there appear to be two (ugly) workarounds.
1) Disable WiFi before sending the MMS.
2) Disable IPv6 on your APN.

**Comment by doctorzook** [comment]
Thanks @apmon. This seems to be the exact problem, and both of these workarounds seem to work. I'll nix this bug and wait patiently for the real fix.
