### ISSUE TITLE
Clearer identification of failed PUSH messages 

### ISSUE THREAD

**Issue by chmac** [WhisperSystems/TextSecure#2308]
When a PUSH message fails to send (say because there's no internet connection), it's given a green background and a red triangle icon to the left hand side. The green background is exactly the same as when a message is sent (maybe unencrypted?) over SMS because PUSH was no longer available for that user (or maybe some other reason).

When a message failed to send, and was actually not sent, and needs to either be resent or deleted, feels like there could be a better colour than green. Maybe a grey background to suggest that it's not sent, sort of greyed out, or maybe something red to suggest failure. I'll leave the specifics up to folks smarter than I. :-)

**Comment by rhodey** [comment]
closing as dupe of #1321
