### ISSUE TITLE
Bug affichage messages lus

### ISSUE THREAD

**Issue by ralevy** [WhisperSystems/TextSecure#2309]
Bonjour,
Petit bug lorsque j'ouvre un nouveau message. Il s'ouvre mais quand je reviens sur la liste de tous les messages, il est toujours en non-lu. Il faut le réouvrir à nouveau pour le passer en lu...
Le bug a lieu juste dans l'appli. Au niveau des notifications, ça marche parfaitement.

Device info : Moto G (1ere génération), Android 4.4.4, TextSecure 2.3.3

App state: Push noregistered

**Comment by jocelynthode** [comment]
Hey,
you should translate your post and write it in english so everyone can understand it :)

Salut,
tu devrais traduire éditer ton post et le traduire en anglais comme ça tout le monde peut le comprendre !

**Comment by rhodey** [comment]
translated

`Small bug when I open a new message. It opens but when I come back on the list of all the messages, it is still unread. It should reopen again for the change to read ...
The bug occurs just in App. At the level of notifications, it works perfectly.

Device info: Moto G (1st generation), Android 4.4.4, 2.3.3 TextSecure`

seems to be a duplicate of #235
