### ISSUE TITLE
Multiple Audible Notifications for Single Message

### ISSUE THREAD

**Issue by nwdev** [WhisperSystems/TextSecure#2310]
For some reason lately upon receiving a message my device will give two audible notifications for a single message, meaning the Incoming text sound happens twice.

This happens on both devices I own that have TextSecure installed.

**Comment by jeremymasters** [comment]
I am currently experiencing the same thing.

**Comment by bisam** [comment]
Same here, but it seems you can fix it by setting the alarm to silent and after that switching back to whatever ringtone you chose...

**Comment by manhole11** [comment]
Same here. Sounds twice or vibrates twice.

**Comment by rhodey** [comment]
are any of you able to reproduce this reliably? can you provide steps?

**Comment by rhodey** [comment]
seems to be a duplicate of #2148, moving discussion to there.
