### ISSUE TITLE
Contact names not showing, only numbers (Cyanogenmod 12 + Hammerhead)

### ISSUE THREAD

**Issue by dmix** [WhisperSystems/TextSecure#2313]
I'm testing Cyanogenmod's new Lollipop build [0] on a cleanly wiped Nexus 5. I imported about 200 contacts via .vcf file.

Problem: all messages displayed in TextSecure are shown only via a phone number, not synced with the contact name, even though the number exists in the Contacts database.

Stock hangouts app works properly: when I receive/send messages the names show up as the Contact names.

What I've tried that did **not** fix the problem:

- click user icon and adding number to existing contact [1]
- deleting all contacts and reimporting them
    - appending them to 'local phone', under a Google account, under Flock, and a group... no dice
- manually creating contacts from empty contacts list
- redownloading TextSecure
- clearing dalvik cache and cache partition
- clearing data in Apps settings menu for TextSecure, contact sync, contacts, phone storage, etc
- disabling Privacy Guard (which right now tells me TextSecure has *last accessed* the contacts 11min ago)

I'm running out of ideas here. There seems to be a disconnect between TextSecure<>Contacts.

[0] cm-12-20150107-NIGHTLY-hammerhead.zip from https://download.cyanogenmod.org/?device=hammerhead

[1] When I click the user icon it asks me to 'Add 555-555-5551 number to contacts'. When I click on the existing contact it ends up having 2 entries for  555-555-5551.

**Comment by mcginty** [comment]
Please post a logcat, but since you're on an early nightly build of CM it's probably your ROM. On stock Lollipop running Hammerhead, it works fine.

**Comment by dmix** [comment]
Here is a non-filtered logcat dump: 

https://gist.github.com/anonymous/3b6c1383c6180700ffbc

Over the timeframe in the log I wiped/forced killed TextSecure -> opened app -> re-registered with WhisperSystems -> rendered conversation list

Hopefully this helps. While stepping through the logs nothing jumped out at me immediately.

**Comment by bigfack** [comment]
@dmix I also have a Nexus 5 running CM nightlies and I am having the same problem, **but** it also affects the default messaging app (not Hangouts). @mcginty is right, it is likely a problem with our ROM. 

I have fixed it by exporting all my contacts into a .vcf file, then going into Settings -> Apps -> All, and clearing data and cache for both the Contacts app and the Contacts storage app, then re-importing the .vcf file into "local phone". It looks like you've already tried this, but maybe not in the exact order?

Hope this helps.

**Comment by dmix** [comment]
@bigfack I figured out the problem: before I imported contacts I had gone through the apps section and disabled Google Contact Sync. When I reenabled it and using a fake gmail account, then reimported contacts, wiped data/cache, then they appeared in Phone/Messenger.

I have a feeling Phone/Messenger/TextSecure somehow depend on Google Contact Sync in order to share contact info. There must be some primary contact DB that doesn't populate unless this service is running. 

 This was my conclusion after about 3 hours and trying 10 different things .

**Comment by bungabunga** [comment]
@dmix not correct. i removed Google Contact Sync from every phone i ever had and never had issues with TextSecure.

ps - i'm not on CM

**Comment by dmix** [comment]
@bungabunga are you using Lollipop? I never experienced this problem on versions <= 4.3, only when I upgraded to 5.0 using CM12. I also never uninstalled Google Contact Sync, only disabling it.

Maybe a TextSecure dev more familiar with how the contact database syncs with various apps (Phone/Messenger/TextSecure) can clarify what might have gone wrong.

**Comment by bungabunga** [comment]
no, i'm currently on 4.4 and was before on 4.2, 4.1, 4.0... with Google Contact Sync uninstalled on every rom.

**Comment by Hnasar** [comment]
Having this issue too. one of my contacts stopped showing up -- just the phone number -_-

**Comment by begleysm** [comment]
@mcginty Can we open this issue back up?  @bungabunga pointed out that he has removed Google Contact Sync and doesn't have this problem.  Conversely I have Google Contact Sync active and I DO have this problem so I don't think the offered "solution" is at the core of the problem.

**Comment by dmix** [comment]
I agree this problem isn't solved but I'm not sure it's an issue with TextSecure which is probably why @mcginty closed it.

I havent had any luck asking the Cyanogenmod devs about it. My only option so far is to keep Google Contact Sync and append them to a Google accout, then disabling syncing contacts in settings + firewalling all Google services.

@begleysm are you using CM, also which version, and did you add the contact to a Google account or as 'local device only'?

**Comment by begleysm** [comment]
I'm on CM12 20150308-NIGHTLY.  I have the phone synced with a Google Account and the contacts are 'Google contacts'.  I'm not sure when this started happening but there was a time when everything worked on CM12.  I think this phenomenon started in mid-February for me.  The result is that 80% of my text contacts have their names displayed and 20% (the most recent 20% to be contacted via text) have their numbers shown.

**Comment by mcginty** [comment]
It sounds to me like nobody other than those running a CM12 nightly are having this issue, which is why I closed it as a CM12-specific bug.

**Comment by Hnasar** [comment]
I too had this issue in CM. Deleting all app data (via Settings > Apps) for everything related to Contacts & Dialer, then readding my sync accounts worked fixed the issue. When the issue was occurring the default Messaging app also couldn't map from phone numbers to Contact names.

**Comment by begleysm** [comment]
@mcginty, I think you're right this is a CM12 issue.

@Hnasar, thanks for the info, this worked for me.  I went into Settings > Apps and did a "Clear Data" from Contacts, Contacts Storage, Dialer, & Google Contact Sync.  I did not have to readd my sync account because it was still there.  I then opened up Contacts/People and everyone was there (as usual).  I then opened of TextSecure and the symptoms were gone.  So this worked, at least temporarily.

**Comment by talibosmani** [comment]
I have exactly the same issue with My CM12, and Samsung Galaxy S5 (Stock ROM). This happened 4 updates back for both of my phones.

**Comment by ldwg** [comment]
A friend reported the same problem: After a text message has been exchanged, the contact name is not shown any longer (Signal _and_ default message app). Re-install of Signal did not fix this.

**Comment by rubin110** [comment]
Android 6.0.1 stock, Nexus 6, seeing the same issue. I did a factory reset on my device and managed to acciddtnally delete the backup/export of Signal that I made. Phone restored all my apps from the play store, then I tried getting Signal working. Now some of my SMS conversations in Google Hangouts are missing their names and photos. If I tap on the contact the Google account address book entry appears with all the correct details (name) and photo. A work around I found is to edit the contact and modify it slightly, then the correct name and photo will show up in Hangouts. 

I tried the wiping contact sync data trick but it did not fix my issue.

**Comment by nikolauspolak** [comment]
Had the same problem on Nexus 5x, Android 6.0.1 stock/no-root. First managed to edit/link every contact in Signal a few weeks ago, then I had to remove/readd my ActiveSync-compatible mailaccount where all my contacts are synced and had again only numbers.
This time I tried something else: In phone settings/accounts I only removed the Signal account, rebooted, start signal - and the numbers got replaced by names :-)
Guess this is the easiest workaround for now, perhaps it has something to do with which account was first added?

**Comment by tx3eh8IUD1** [comment]
I know this is an old topic, but I think it is still important. 
I, too, had (some) contacts who were only identified by their phone number within signal, even though I had those contacts in my actual local contacts as shown by the system app. This happened after updating android (CM 13 .0 / Android 6.0.1) and getting started with backups. I think issue #4338 is related. 

I also "lost" all group names - although the group names were still functioning in signal desktop, the android app only showed them as "Unnamed Group". Whenever I got a message, some cryptic "Textsecure Group ID (INSERT RANDOM NUMBERS AND LETTERS HERE)" showed up in my notifications bar. The solution below also restored the group names. (The solution posted there also works, but only for group names and not the funny contacts). See also #2581 or #2999

@nikolauspolak had the best solution offered so far: 
1) deleting the signal account via android settings (Settings -> Accounts -> Signal -> Menu: Remove Account)
_Note: This  **does not delete your messages or regular contacts**. It's a warning from android, but in the case of signal it is not correct._
2) restart the app, refresh contact list ("draft new message icon" on bottom right corner -> Menu: Refresh -> wait a minute or so)
3) by now, all should be in order. You might have to restart the app or wait a while.

**Comment by kelogs** [comment]
Similar issue here: 

Phone / Contacts apps won't show any contacts on CM 13.0-20161204-nightly-dogo

Tried without luck what @begleysm suggested on Mar 13, 2015: 

> "I went into Settings > Apps and did a "Clear Data" from Contacts, Contacts Storage, Dialer, & Google Contact Sync."


The current version of nioghtly CM is an update from a previous version where I had the same issue. Updating has solved the issue for a few days then it has resurfaced.

```
root@dogo:/data/data/com.android.providers.contacts/databases # ll             
total 6744
-rwxrwxrwx 1 u0_a4 u0_a4 3014656 2016-12-10 15:20 contacts2.db
-rwxrwxrwx 1 u0_a4 u0_a4   29240 2016-12-10 15:20 contacts2.db-journal
-rwxrwxrwx 1 u0_a4 u0_a4      73 2014-11-25 03:46 contacts2.db-mjDD7F189FD
-rwxrwxrwx 1 u0_a4 u0_a4   16384 2016-11-15 14:28 local_groups.db
-rwxrwxrwx 1 u0_a4 u0_a4    8720 2016-11-15 14:28 local_groups.db-journal
-rwxrwxrwx 1 u0_a4 u0_a4  348160 1970-01-12 17:17 profile.db
-rwxrwxrwx 1 u0_a4 u0_a4       0 1970-01-12 17:17 profile.db-journal

```

**Comment by joe621** [comment]
Hey guys, same problem. Just went through two LG G5's thinking thinking they had some sort of defect. I thought it was my phone but it looks like its the 6.0.1 OS. I turn my phone off and when I turn it back on the names show in my text messages for about 5-10 seconds then disappear when I reopen the messages app. This has got me stumped. Im having a nervous breakdown. If anybody figures it out email me j.schylaske at live.com. I've literally tried everything.

**Comment by LeeBinder** [comment]
same issue here. Any working solution? None of the tips from below solved this issue:
~~
Open Signal, tap the blue pencil ✏️ button, pull down the contact list to refresh it and see if the contacts are correctly associated again
~~
Android Settings > Accounts > Signal > Menu > Remove Account > then Resync

Note that removing the account will result in the loss of all message threads and group conversations.
~~
Re-register by switching off and back on:

Signal Settings -> Advanced Settings > Free private messaging and calling
~~
