### ISSUE TITLE
Receiving encrypted MMS causes app to stop functioning altogether

### ISSUE THREAD

**Issue by le1ca** [WhisperSystems/TextSecure#2315]
I've had no real problems with unencrypted MMS (except that they will not download while on wifi, which is apparently a known issue) but yesterday someone sent me an encrypted MMS (for the first time) and now TextSecure does not work at all.

It crashed immediately upon attempting to open the MMS, and any time I try reopening the app, it crashes right after I enter my passphrase. I get a brief glimpse of my inbox and then the crash occurs. This behavior continues after rebooting the device.

Crash log:
https://gist.github.com/anonymous/9edfed5732bcc0665ec4

I had to clear all the app's data in order to be able to use TextSecure again...

**Comment by tavianator** [comment]
Dupe of https://github.com/WhisperSystems/TextSecure/issues/2194?

**Comment by le1ca** [comment]
Yep, sorry didn't see that one before
