### ISSUE TITLE
Can't receive encrypted MMS over regular (non-push) channel

### ISSUE THREAD

**Issue by rfugger** [WhisperSystems/TextSecure#2316]
When I receive an encrypted MMS over the regular non-push channel, the received message says "downloading..." and within a few seconds, the entire app crashes and ends with an error message "app closed unexpectedly" or the like. When I restart the app, it crashes again within 5 seconds and unless I have quickly deleted the thread containing the offending MMS, it will continue to crash immediately upon app start.

**Comment by agrajaghh** [comment]
could you post a debug log please?

**Comment by rfugger** [comment]
Debug log after receiving encrypted MMS, and then crashing about 4-5 times before successfully deleting the offending message in the 5 second window:

https://gist.github.com/7ecf1dc20ee337088453

**Comment by McLoo** [comment]
Seems to be the same as #2315

**Comment by tavianator** [comment]
Dupe of https://github.com/WhisperSystems/TextSecure/issues/2194?

**Comment by rhodey** [comment]
closing as duplicate of #2194 which should have been resolved by dbd8a4083cc379a00bacfccbc8a3c2dc0ef42d71, thanks for the issue report! :)
