### ISSUE TITLE
"Message encrypted for non-existing session" 

### ISSUE THREAD

**Issue by rfugger** [WhisperSystems/TextSecure#2317]
I uninstalled and reinstalled textsecure (trying to fix another bug, without success). Now every message I get from one of my textsecure-using contacts comes up as "message encrypted for non-existing session". I'm playing around with both devices trying to sort it out, but the fact that this can even happen in the first place is definitely a bug.

**Comment by moxie0** [comment]
Are the messages you receive push or sms?

**Comment by rfugger** [comment]
Sms.

**Comment by moxie0** [comment]
Yep, one of the many reasons we want to get rid of the encrypted SMS channel -- there's no way to automatically resolve this.  I recommend that both you and your contact register for TextSecure messages (push).

**Comment by rfugger** [comment]
That works, but then when my contact disables push again, my device still
tries to send push messages to them.

**Comment by moxie0** [comment]
If your contact manually unticks 'push messages', your client should immediately stop sending push messages on the next message.  If they uninstall textsecure, it takes one message and ~15min for the TextSecure server to be notified that they've uninstalled.

**Comment by rfugger** [comment]
Ok, they unticked push messages, but my client continued trying to send
push messages (blue arrow, attempting to send fails).
