### ISSUE TITLE
Default delivery mode option

### ISSUE THREAD

**Issue by mart-e** [WhisperSystems/TextSecure#2329]
Hello,

If both contacts have configured push delivery, all messages will be sent with it by default. It's good as it means free messages but some people still wants to send SMS (as not sure the contact will be connected, cf #2222).
I know you can long press the send button to change the delivery for the current message but it's the default delivery method that I would like to change (I have a friend who refused to switch to TextSecure because still wanted to send SMS by default).

Another way to solve it, add a discrete option next to the send button, a bit like what's done in [Facebook Messenger with location](http://cnet4.cbsistatic.com/hub/i/r/2014/08/11/53f41f04-260e-4dce-bf3f-7d3ae03befc1/resize/370xauto/47f758e3c4b23a5c5d816bc6721da5ff/facebook-messenger-app.jpg).

I can try to make a pull request if that's a feature you would accept (may take a bit of time though).

**Comment by moxie0** [comment]
Thanks but this is not something we'd consider integrating.
