### ISSUE TITLE
Persistent crashing when receiving MMS

### ISSUE THREAD

**Issue by slick601** [WhisperSystems/TextSecure#2332]
I received a series of vcards interspersed with some MMS messages from one sender. At around this time, TextSecure began to crash after being open for between 10 and 40 seconds, regardless current screen or message threads having been opened.  This makes it very difficult to troubleshoot as the app dies quickly after opening.  I also experience previously sent vcards being posted again as if they were new messages after each crash.  I browsed other currently open bugs and I saw several other MMS-related issues, but this one didn't seem to fit.  

Find the logcat output here, with seemingly relevant lines beginning at around 300: 
http://hastebin.com/uxozumujen.coffee
gist link: https://gist.github.com/anonymous/505546d70c2a74a850b0

Hardware: HTC One X
TextSecure: 2.3.3
Android Version: Cyanogenmod 11 M12-endeavoru

**Comment by slick601** [comment]
Upgraded to 2.4.0.  Problem resolved.

**Comment by jeremymasters** [comment]
2.4?

**Comment by mcginty** [comment]
Good to know, thanks for reporting back @slick601! @jeremymasters release is rolling out

**Comment by slick601** [comment]
Yes, updated to 2.4. Thanks guys, sorry for the useless post.
