### ISSUE TITLE
Difficult to select some messages

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#2333]
After I upgraded from 2.3.3 to 2.4.0 I have difficulties selecting some messages. Not all messages - it seems to be just those messages where TextSecure recognises a phonenumber in the message text. When I long-press such a message and release my finger from the screen the selection disappears.

To select such a message I have to long press, don't release my finger, press another message in the thread so I select 2 messages and then short-press the last one so it leaves the selection.

Update: I tested this on 2 devices, one no-name cheap Android 4.2.2 which does not have this problem. A Sony XPeria Z1 Compact with 4.4.4 does have this problem.

**Comment by McLoo** [comment]
Workaround: If you tap next to the bubble, or at least outside the phonenumber (or hyperlink) it works.

**Comment by johanw666** [comment]
Yes, pressing outside the bubble works well. Thanks.Pressing just outside the phonenumber but within the bubble does not work on the Sony phone, that was why I reported it.

**Comment by JavaJens** [comment]
I can confirm the issue for messages with an image only.
Also can confirm the workaround.

**Comment by McLoo** [comment]
I could swear image long press has work with the PR. 
Besides that, I just noticed K9 Mail uses left swipe over an item to select it. Maybe a good alternative... @moxie0?

**Comment by JavaJens** [comment]
If you already have an image select (e.g. by clicking next to the bubble) it works without a flaw to select by tapping the image, its just the first one...
I do like long tap and find it more intuitive than swiping, but maybe thats just more common for me

**Comment by hebu** [comment]
Same issue with hypelink/phonenumber messages on my device. Good to know, that clicking outside the bubble is a workaround.

Device info from the logs:

> Device : samsung GT-I9305 (m3xx)
> Android: JSS15J.I9305XXUEMKC
> OS Host: SEP-108
> App    : TextSecure 2.4.1

**Comment by jeremymasters** [comment]
Is it different in 2.4.2 now?

**Comment by hebu** [comment]
No.

**Comment by rhodey** [comment]
this is still reproducible on TS 2.6.4 and caused by the same behavior as #2488, ie:

1) press down
2) hold until long press event fires
3) move left or right even the slightest
4) release

**Comment by 2-4601** [comment]
Not sure if #2648 will fix this but I just found out that if you come fresh (i.e. from somewhere else) to a conversation you cannot outside-select a message with a link unless you first select another message at least once.

Demonstration:
![output](https://cloud.githubusercontent.com/assets/174176/7125695/c7f46426-e23b-11e4-8a4d-24dc586380fa.gif)

This selection bug is
```
much annoying
                                        such headache
```

**Comment by ComeGitSome** [comment]
I can reproduce this on TextSecure version 2.22.0. Doesn't have to be a phone number or a picture, I get this on messages with text only. Keeps happening on the same messages but not if I copy it and paste it to another conversation.

On at least one message I'm able to select it by pressing at a particular spot, still inside the bubble though.

**Comment by 2-4601** [comment]
Blessed be this day, it works! Only sadness is that the ripple animations are gone :crying_cat_face:
