### ISSUE TITLE
Can't delete specific texts

### ISSUE THREAD

**Issue by heejtts** [WhisperSystems/TextSecure#2334]
I can't seem to delete secure texts recieved which soley contain URLs. I can select the text but the delete button does not remove it.

**Comment by McLoo** [comment]
This should be fixed in 2.4.0 (coming soon) - at least it works for me there.

**Comment by rhodey** [comment]
is this still an issue @heejtts? I am unable to reproduce on my Nexus 5 running stock Lollipop and TextSecure 2.6.0
