### ISSUE TITLE
Version 2.4 Crashing On Start

### ISSUE THREAD

**Issue by wrdixon** [WhisperSystems/TextSecure#2335]
Just updated to TS 2.4 and I'm having really  bad stability issues (it crashes).  I had never had the application stop on me in previous versions.

Here are a few repeatable ways I've found to make it crash.

- Starting a text to certain non TS contacts.
- Going to the settings menu.
- Looking at your fingerprint.

As it write this, now it crashes immediately on restarting TS, even after Rebooting the phone.  Had to switch over the the default text application. 

I'm running a Moto G 4.4.4 with TextSecure 2.4

**Comment by McLoo** [comment]
Can you post a debug log after such a crash.
Either from the TS lock screen or the settings advanced menu.
Thanks!

**Comment by wrdixon** [comment]
Unfortunately I can't get to the Settings Advanced Menu as it crashes before I can do anything.  Not sure how to generate one for the TS lock screen (or what the TS lock screen is).

I've hit the Report button when it says, "Unfortunately, TextSecure has Stopped."

**Comment by McLoo** [comment]
If you have set a password to lock text secure, 
then the lock screen is shown on start. In the upper right corner is a menu button, for the debug log.

**Comment by wrdixon** [comment]
I haven't set a lock and can't now as it's crashing on launch.  From the Google debug preview I can see a little info, if it's helpful.

Exception Class Name: java.lang.NullPointerException
Source File: UriMatcher.java
Source Class: andorid.content.UriMatcher
Source method: match
Line number: 222

**Comment by McLoo** [comment]
then this is likely to be #2336

**Comment by wrdixon** [comment]
Likely.  Happy hunting!

**Comment by wrdixon** [comment]
The 2.4.1 update fixed it!  Thanks
