### ISSUE TITLE
TextSecure stopped working after attempting to send unencrypted image

### ISSUE THREAD

**Issue by ashmastaflash** [WhisperSystems/TextSecure#2342]
Running 2.4.0 installed from Google Play.
Moto Droid Ultra, running Verizon's firmware (not rooted) Android v4.4.4
Successfully registered and set as default sms app.  Was working until I attempted to send image in an unencrypted message.

Installed TextSecure, successfully imported text messages from default SMS app, though no images were imported.  Sent and received an unencrypted text message or two successfully, then attempted to send an image (unencrypted).  Now, app does not open, "Unfortunately, TextSecure has stopped" immediately thrown on attempt to access.

**Comment by moxie0** [comment]
Hey @ashmastaflash, please update to 2.4.1.

**Comment by ashmastaflash** [comment]
Thanks @moxie0, works fine now!
