### ISSUE TITLE
2.4 changelog missing in Google Play

### ISSUE THREAD

**Issue by piratenpanda** [WhisperSystems/TextSecure#2343]
Would be nice to get the changelog there once the crashing bug has been resolved with version 2.4.1 (I assume)

**Comment by jeremymasters** [comment]
I see the changelog there for 2.4.1:
Changes in 2.4.1:
★Bug fix for MMS crash.

**Comment by jeremymasters** [comment]
One thing that might be good is a spot in the "Advanced" menu area or even in the regular stating the version of the app running.

**Comment by piratenpanda** [comment]
My changelog is at 2.3.3 so I'll have to wait for 2.4.1 I guess, but still, having this accessible from the app would also be nice as well :)

**Comment by jeremymasters** [comment]
For now you can look in your TextSecure debug (just don't actually submit it).  That will tell you which version you are actually running too, should you abhor looking in the play store at any point. :)

**Comment by McLoo** [comment]
@moxie0 2.4.1 is only now. Changelog is still on 2.3.3. At least German and French. As before Spanish is up to date...
