### ISSUE TITLE
Checkbox for Wi-Fi calling

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#2347]
I noticed that there is a checkbox for Wi-Fi calling now in the settings.  At some point here Verizon will be updating more and more phones to Wi-Fi calling ("Advanced Calling 1.0", as they have euhpamized).  Will this be needed for all large carriers at that point for unecrypted sms?  I think the Note 3 already has this.

**Comment by jeremymasters** [comment]
What I really mean is, can this be automated at some point?

**Comment by moxie0** [comment]
If the device exposes an API, sure.  But as far as I can tell they don't.
