### ISSUE TITLE
problem in send mail through send grid  in aws server in codigniter

### ISSUE THREAD

**Issue by chitragithub** [WhisperSystems/TextSecure#2348]
i use this code 
        require_once '/var/www/html/valin/vendor_mail/vendor/autoload.php';
	require_once '/var/www/html/valin/vendor_mail/lib/SendGrid.php';
	$sendgrid = new SendGrid('username', 'password');
				$email = new SendGrid\Email();
				$email->addTo('you@bar.com')->
					   setFrom('me@bar.com')->
					   setSubject('Subject goes here')->
					   setText('Hello World!')->
					   setHtml('<strong>Hello World!</strong>');
					   if(!$sendgrid->send($email))
					   {
						echo "not sent"; 
						}
						else
						{
							echo "sent";
						}
but its nat run on aws sever it show loading only can you help me

**Comment by agrajaghh** [comment]
what has this to do with textsecure?

The issues are getting more and more helpful :laughing:
