### ISSUE TITLE
MMS bugs still in 2.4.1

### ISSUE THREAD

**Issue by vocabularasa** [WhisperSystems/TextSecure#2349]
Am I doing it wrong?

https://gist.github.com/e4c4a9135f7a74e2b14c

**Comment by vocabularasa** [comment]
Samsung Galaxy S4 Android 4.4.2

I tried sending an MMS in 2.4 and TS not only crashed but it crashed upon opening consistently until I wiped its data. It worked then, but I noticed an update that claimed an MMS bug fix, so I updated.

It stopped crashing, but will not send the MMS still....

**Comment by mcginty** [comment]
2.4.2 includes a fix for this bug, sorry you're experiencing it.
