### ISSUE TITLE
Cannot mark a message as read using the notification action if it is the first message from a new contact

### ISSUE THREAD

**Issue by jlund** [WhisperSystems/TextSecure#235]
If a new message comes in from a brand-new phone number that doesn't already have an existing thread, you cannot mark that message as read. Subsequent messages from that contact can be cleared via the notification action, however.

I am running stock Android 4.2.2 on a Nexus 4.

**Comment by rhodey** [comment]
also able to reproduce on 2.6.4

**Comment by rhodey** [comment]
I am no longer able to reproduce this on TextSecure 2.7.1 or 2.8.0 running Android Lollipop 5.1, @jlund you still seeing this?

**Comment by jlund** [comment]
It's not happening for me anymore either. \o/
