### ISSUE TITLE
Frequent TextSecure Crashes (cause unknown)

### ISSUE THREAD

**Issue by tx3eh8IUD1** [WhisperSystems/TextSecure#2362]
TextSecure crashes very frequently. This might be the wrong place for the report, as the crashes started to occur after the latest update of CyanogenMod, to version 11-20141112-SNAPSHOT-M12-galaxysmtd

TextSecure Version: 2.4.2
Cell: Samsung Galaxy S, i9000
OS: CyanogenMod, 11-20141112-SNAPSHOT-M12-galaxysmtd

TextSecure log: https://gist.github.com/9b2151f1f5e81048b112 
more frequent log: https://gist.github.com/anonymous/9a1cd9546b5941d77774

The crashed occur independent of a certain thread or conversation. Sometimes when a certain thread is open, sometimes when just right after opening the app.

**Comment by manhole11** [comment]
Yeah, it's normal. It crashes pretty much all time here too.

**Comment by agrajaghh** [comment]
I can't see a crash in this log (but I'm no expert), could you post another one?

**Comment by tx3eh8IUD1** [comment]
I will post another one as soon as the app goes down again. It seems to be afraid of my bug report and behaves responsibly now, after crashing >100x per day for about a week. 
Sorry for that. :/ but thanks for the prompt response.

**Comment by ap--** [comment]
Maybe worth a try:

Since you have a Galaxy S2, check if your phone is subject to this bug: 
https://jira.cyanogenmod.org/browse/CYAN-3877
If yes, try installing this Kernel:
http://forum.xda-developers.com/galaxy-s2/development-derivatives/kernel-fpbug-stable-4-x-kernel-galaxy-t2978088

**Comment by tx3eh8IUD1** [comment]
Hey @ap-- , hey @agrajaghh 

here is another try at the log. It crashed very frequently again:
https://gist.github.com/anonymous/9a1cd9546b5941d77774 

After the crash:
If I press report, it's a message that goes to google, right? That will not be of particular help for you?!

**Comment by McLoo** [comment]
@tx3eh8IUD1 could it be that there is no more free internal storage on your device?
```
 Caused by: android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
``` 

Crash reports are sent to the app developer and *are* of help :)

**Comment by manhole11** [comment]
I don't think that's the reason, I have a lot of free space and the app still crashes

**Comment by agrajaghh** [comment]
@manhole11 then open another issue and post a debug log...

**Comment by mcginty** [comment]
We've been getting lots of reports of errors from Cyanogenmod 12's nightlies, yet no stock Lollipop users have chimed in saying they're experiencing it too. It's very likely a CM issue and nothing we can do anything about.

**Comment by mcginty** [comment]
The errors look like there's no space on the device (keep in mind that we are on *internal* storage, so there may still be external storage space which is a different partition).

**Comment by tx3eh8IUD1** [comment]
Thanks for the help, @mcginty !
