### ISSUE TITLE
Received MMS crashes app

### ISSUE THREAD

**Issue by drohhyn** [WhisperSystems/TextSecure#2370]
Hi,

I've received an MMS which crashes the app. The log from advanced settings are here: https://gist.github.com/anonymous/66550f0d961145822755

I am able to write with every other contact except the one who sent me the mms. In the recent threads list, the encoded start of the mms message is displayed, when I try to open the thread the app screen turns black and crashes to home screen a few seconds later.

Is there any option to delete only the "damaging" message?

Kind regards,
  drohhyn

Seems to be linked to #2271.

**Comment by mcginty** [comment]
Unfortunately I don't see a crash in that log. Can you try to reproduce and re-post your logs?

**Comment by drohhyn** [comment]
Can't reproduce it now - I hope it is fixed with #2294.
