### ISSUE TITLE
Unable to take screenshot when TS open

### ISSUE THREAD

**Issue by huegelc** [WhisperSystems/TextSecure#2371]
Hi,
I,m using the latest TS Version on Android 4.4.4 (Cyanogenmod ) on OnePlus. When TS is open in the foreground i cannot take a screenshot. Error message is: "Couldn't save screenshot. Storage may be in use"
However when TS is closed the screenshot function works as expected.
Thank you.

**Comment by agrajaghh** [comment]
Its intended behaviour. You can disable it in the settings under App Protection -> Screen security

**Comment by huegelc** [comment]
OMG ...yes thank you.
