### ISSUE TITLE
TextSecure crashes if I tap a photo being sent

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/TextSecure#2377]
How to reproduce:

1. Send a photo (I tried over push)
2. While it's being sent, tap the picture to open it
3. Should crash in a couple of seconds

Here's the debug log: https://gist.github.com/anonymous/4f1b40bc8d88451ad6ba

**Comment by rhodey** [comment]
I'm unable to reproduce this on my Nexus 5 running stock Lollipop and TextSecure 2.5.3. Are you still having this issue @manhole11

**Comment by manhole11** [comment]
Not happening anymore, thank you!
