### ISSUE TITLE
[Feature request] Whitespace advertisement as in OTR

### ISSUE THREAD

**Issue by d33tah** [WhisperSystems/TextSecure#2387]
Not sure if it's already there because I couldn't really test for this feature...

It would be nice to have TextSecure advertise its presence in the messages to everybody (not just the people who support TextSecure) just like OTR does - by adding a whitespace to the end to the SMS. This way I wouldn't need to know if my friends use TextSecure in order to turn it on.

**Comment by moxie0** [comment]
Already there.
