### ISSUE TITLE
Improve check mark readability

### ISSUE THREAD

**Issue by rg3** [WhisperSystems/TextSecure#2389]
The check mark that signals the message has been correctly sent was a very welcome feature. I recently introduced TextSecure to my father, who is 60 years old and, despite not having severe sigh problems at all in his life, at that age he needs to use glasses to read his phone (5" Moto G) and has it configured with very large fonts for ease of use.

In that context, we recently had minor problems with messages not arriving due to connectivity and he was unable to notice because he can barely see the check mark. I can perfectly see it in my Nexus 4 with normal fonts, but I agree it should be easier to identify. Maybe making it bigger and/or changing the character to U+2714, and maybe using a different (bright) color that helps spotting the mark way easier than it is now.

**Comment by mcginty** [comment]
Yeah, definitely an accessibility issue. Thanks for posting, I'll see what can be done about that :).

**Comment by devurandom** [comment]
@mcginty where you able to find a solution for this?

**Comment by volcano99** [comment]
In #3012 @agrajaghh proposed new icons for the delivery check mark -- they look much better and should also be easier to see. To be honest I think the current icon for the check mark looks a bit ugly. The whole conversation UI is really good and that mark stands out for how ugly it is, hehe :dancer:

**Comment by wp9015362** [comment]
@mcginty :

Please make the delivery/read checkmark(s) like in WhatsApp for Android and Telegram for Android, see for example:

http://www.androidpolice.com/wp-content/uploads/2015/04/nexus2cee_whatsapp-material-7.png ([Source](http://www.androidpolice.com/2015/04/14/hands-on-whatsapp-goes-material-with-cool-animations-fabs-and-lots-of-purty/))

![Image](http://www.androidpolice.com/wp-content/uploads/2015/04/nexus2cee_whatsapp-material-7.png)

https://telegram.org/file/811140345/1/I4cpmT-kjAk/1f7a944b623fe148bd ([Source](https://telegram.org/blog/captions-places))

![Image](https://telegram.org/file/811140345/1/I4cpmT-kjAk/1f7a944b623fe148bd)

And please also add an optional read receipt feature:

https://github.com/WhisperSystems/TextSecure/issues/3251

Regards

**Comment by agrajaghh** [comment]
These material icons could be used for sent/received:
![ic_done_black_48dp](https://cloud.githubusercontent.com/assets/5296073/7787726/391ff788-021b-11e5-9266-a676c3b79b7b.png)
![ic_done_all_black_48dp](https://cloud.githubusercontent.com/assets/5296073/7787727/39266b72-021b-11e5-9666-4cad9bc6ab1e.png)

But using the background color for sending/sent like it's now is good too :confused:

**Comment by volcano99** [comment]
The first icon could be used as "delivered".
Or we could switch to a new behavior using both icons, isn't that more similar to what whatsapp does? New users would be more familiar with those, though it keep it the way it is now

**Comment by wp9015362** [comment]
> @agrajaghh wrote:
> 
> But using the background color for sending/sent like it's now is good too :confused:

I very much disagree.

IMHO the way WhatsApp and Telegram are doing it is much better.

> @volcano99 wrote:
> 
> Or we could switch to a new behavior using both icons, isn't that more similar to what whatsapp does?

Here is the explanation from the WhatsApp FAQ:

http://www.whatsapp.com/faq/en/general/20951546

One gray checkmark means "message successfully sent", two gray checkmarks mean "message successfully delivered to the recipient's phone", two blue checkmarks mean "the recipient has read your message". Source: http://www.whatsapp.com/faq/en/general/20951546 .

In Telegram for Android it's a little bit different.

In Telegram for Android it's done like this:

While delivering a message, there is a green clock-face symbol in the message bubble. Once the message has been delivered, the green clock-face turns into one green checkmark. And once the message has been read, the one green checkmark turns into two green checkmarks.

Regards

**Comment by volcano99** [comment]
@wp9015362 man, you're so wordy. I find it hard to focus on what you're saying, you write so much.. :/

Is it possible that shifting to a behavior where we use only check marks could fix #2964 (assuming it's a problem with slow graphic)?

**Comment by wp9015362** [comment]
> @volcano99 wrote:
> 
> @wp9015362 man, you're so wordy. I find it hard to focus on what you're saying, you write so much.. :/

Let's put it that way:

If you would have googled for the WhatsApp FAQ yourself, I wouldn't have had to reply in the first place...

Well:

http://bfy.tw/54d

**Comment by wp9015362** [comment]
> @agrajaghh wrote:
> 
> These material icons could be used for sent/received:
> 
> ![Image](https://cloud.githubusercontent.com/assets/5296073/7787726/391ff788-021b-11e5-9266-a676c3b79b7b.png)
> 
> ![Image](https://cloud.githubusercontent.com/assets/5296073/7787727/39266b72-021b-11e5-9666-4cad9bc6ab1e.png)
> 
> But using the background color for sending/sent like it's now is good too :confused:

Those checkmarks are now being used in TextSecure 2.21.0.

It's much better like that now!

Thanks a lot!

I'm still missing an optional read receipt feature though:

https://github.com/WhisperSystems/TextSecure/issues/2667

And still don't understand why it's not being done.

Regards

**Comment by rg3** [comment]
With the latest version and the improved check marks, I consider this issue solved for what it's worth. Thanks a lot!
