### ISSUE TITLE
"Add picture" in conversation only leads to "Downloads" folder

### ISSUE THREAD

**Issue by mayerflash** [WhisperSystems/TextSecure#2391]
In Chat when I click on "add a picture" then the "Downloads" folder is opened.
There is no possibility to access the photo galery like in every other app.

In most other apps there is an android dialogue launched "complete action with..." and then I can select the gallery app or any other app which fits best.

Actually it would be good if both folders would be accessible, but to achieve this it would be probably better to add a "add file" menu item to the "add attachement" dialog. (And allow to select any type of file).

I'm using Samsung Galaxy Note 3 on Android 4.4.2 with Textsecure 2.4.2

Regards

mayerflash

**Comment by McLoo** [comment]
There should be a menu button in the chooser dialog where you can enable a advanced view

**Comment by mayerflash** [comment]
Ok, I've found it. That's complicated! Can't it be easier to access my gallery?!

But I still have the problem that i can't access the photos on my sd-card. All my photos are stored on the sd-card by default.

**Comment by rhodey** [comment]
this is somewhat different than the original issue raised in #1744, but #1744 has since evolved into a general 'attaching images has inconsistent UX' issue which I feel encompasses this.
