### ISSUE TITLE
Pushbullet can read "encrypted" messages

### ISSUE THREAD

**Issue by magg** [WhisperSystems/TextSecure#2392]
Hi

So first of all, great app guys. I think this is the correct place to report this kind of behavior

I was trying out the new Pushbullet OS X client and somehow noticed that I received 2 notifications when a new message arrived. I have TextSecure locked with a Passphrase.

The first message/notification said "encrypted message" and the other one had the message itself in plain text.  :worried: 

I thought the messages were encrypted while Textsecure is "locked", am i wrong?

thanks

**Comment by agrajaghh** [comment]
If TS is locked, pushbullet can't read encrypted messages. Perhaps you received a SMS? If TS is currently unlocked, pushbullet can read the secure messages from the Notification. You can prevent this by disabling the notification mirroring in pushbullet...

**Comment by magg** [comment]
W

**Comment by magg** [comment]
Hi,

I took a screenshot while my TextSecure was locked

<img src="http://i.imgur.com/gqQegCK.png">
 
I think this is a huge security flaw, could someone look into this?

**Comment by jlund** [comment]
Pushbullet is indeed a huge security flaw. You've installed an application whose sole purpose is to read your notifications (and their contents) and send them to a third-party server so they can be relayed to other devices.

If you don't feel like you can trust Pushbullet with the contents of your notifications, maybe you shouldn't be using Pushbullet?=

**Comment by JavaJens** [comment]
I have never used Pushbullet, but I believe @magg is right with his assumption that PushBullet shouldn't be able to display the message if TS was locked the whole time.

So maybe @magg you can provide more detailed information on when the message arrived, you locked or unlocked TextSecure and if this only happens with SMS.

**Comment by agrajaghh** [comment]
@JavaJens: the displayed message was a SMS (unencrypted). Pushbullet has the permission to read SMS and the permission to read all notifications (if enabled). There is nothing TS can do about this (except not showing the message content in the notification)

**Comment by JavaJens** [comment]
Of course not, I was under the impression it was an encrypted SMS or are those already disabled?

**Comment by agrajaghh** [comment]
@JavaJens ah, okay. It's still possible to send encrypted SMS. But I can't imagine how pushbullet could read them if TS is locked. @magg, can you clarify?

**Comment by magg** [comment]
Yeah sorry, I just read Pushbullet's permissions on SMS/MMS. That message was indeed an unencrypted SMS.

So according to @agrajaghh and @jlund, there is nothing the second layer of encryption of TextSecure can do to protect unencrypted SMS, as long any other app (malicious or not) has SMS permissions. That said can read all uncrypted SMS and MMS.

Well you can close this issue then... thanks!

**Comment by agrajaghh** [comment]
You can click on "Close issue" next to the "Comment" button.

**Comment by cluelessperson** [comment]
wtf is this answer.

PushBullet can **do what it's supposed to** End to End Encrypt the SMS data.

There is absolutely no reason for pushbullet servers to have raw user content when end to end encryption is enabled.
