### ISSUE TITLE
Sending SMS to users who have Tinder app installed does not work

### ISSUE THREAD

**Issue by jvbaber** [WhisperSystems/TextSecure#2393]
When sending SMS to users who are also on Tinder, SMS messages are not delivered.  This has happened only when I try to SMS someone who is also on Tinder, otherwise it works with anyone else (without Tinder).

Device:  Samsung S5, Android 4.4.4 (stock), TextSecure 2.4.2 (uninstalled and reinstalled with no change), Tinder 4.0.3

App state:  Push checked (unchecked makes no difference), incoming SMS and MMS on, App protection off

**Comment by rhodey** [comment]
is anyone else able to reproduce this? I searched around for reports of other apps having their SMS hijacked by Tinder and all I found were a bunch of reports about Tinder not receiving its own activation SMS.

**Comment by jvbaber** [comment]
I haven't, but I really only had one friend using this app and he didn't
use Tinder.

I can reproduce it, at least was able to a month ago.

**Comment by rhodey** [comment]
just tested this on a device running TS with Tinder installed, text message was received just fine. if this is a bug it is a bug in Tinder messing with SMS, and not a bug in TextSecure.
