### ISSUE TITLE
Cannot register for push service

### ISSUE THREAD

**Issue by mathijshenquet** [WhisperSystems/TextSecure#2394]
Log is here: https://gist.github.com/3c7fafb15724faa3559a

I would really like to use textsecure, it seems like a great product, so any help is appreciated.

I'm using Moto G 2013 LTE retail with stock android 4.4.4.

**Comment by mathijshenquet** [comment]
Here is more information on my android build etc http://m.imgur.com/ViFEYIL

If any more info is needed I would be glad to supply it

**Comment by rhodey** [comment]
Hello @mathijshenquet, I looked through your log and it seems like the verification SMS never arrived, is this true?

If this is still happening could you try using the verify by phone call option instead and let me know if that works?

**Comment by mathijshenquet** [comment]
Hey rhodey, thanks for your response. After I posted this msg there was an update and since then I was able the enable the push settings. Thanks for this great app! So this issue can be closed.

By the way I did always got the SMS msg's.

**Comment by rhodey** [comment]
thanks for the report back @mathijshenquet :)
