### ISSUE TITLE
Unread notification re-appears after automatic lock

### ISSUE THREAD

**Issue by drohhyn** [WhisperSystems/TextSecure#2404]
For a few days now, I always get a "1 unread message" notification after text secure locks automatically. It's always from the same contact, but there is no unread message. In fact we texted a lot in between.
I can dismiss the message from the notification bar, but when I receive a message from somebody else, two unread messages appear: the new one and the "always there message".
Reboot did not solve the issue. Any ideas? 

Thanks in advance
  drohhyn

**Comment by nwdev** [comment]
I've been experiencing this issue as well.

**Comment by zmanian** [comment]
Same as #2404

**Comment by zmanian** [comment]
Same as #2287
