### ISSUE TITLE
Another MMS issue (can'd send/receive)

### ISSUE THREAD

**Issue by bungabunga** [WhisperSystems/TextSecure#2405]
A few days ago my sister told me that she could no longer send/receive MMS messages with TextSecure. I rarely use MMS so i tested it on my device and found out that it also doesn't work with me. (I get the red triangel if I try to send MMS and I can't download other people's MMS messages). We're not on the same mobile provider but it used to work on both with default settings.

Here is my log, I can also provide my sister's if needed.
https://gist.github.com/bungabunga/04eb3fd228beb4dc0df3

**Comment by agrajaghh** [comment]
Some people have problems sending MMS on wifi, did you try it while wifi was disabled?

**Comment by bungabunga** [comment]
yes, but my fault anyway. (i'll open anotber issue for my sister if needed)
