### ISSUE TITLE
Encryptet SMS recieved but never sent

### ISSUE THREAD

**Issue by 3-14159265358** [WhisperSystems/TextSecure#2407]
Hi,

recently my Girlfriend (Galaxy S4, Android 4.4.2) and me (S3 mini, Android 4.1.2) both installed textsecure (2.4.2), I set it as my standard app for sms and she did not (we are both registerd for push).

On Friday and Saturday she recieved what looks like encryptet SMS from me, however I did neither send those (and my phone doesn't show any sent sms), nor did she not recieve any (push) messages I did send. Since she doesn't open sms with TS, we don't know the plain text of these sms either (maybe there's method to decrypt them using our keys ?).

Timestamps of push messages sent by me do not match the timestamps of her recieved sms. By now I have enable the checkbox to make TS ask me if it sends sms to another TS user, maybe that will actually resove the issue. I also tried manually sending a none encryptet sms and that works just fine.

I'm not sure how to deal with this problem, my main concern is that TS may be sending SMS (I have to pay for) without me knowing about it.

**Comment by devurandom** [comment]
Look for key symbols in your (S3) message history. If push delivery is impossible, TS will automatically fallback to SMS. For that it has to exchange keys first, which also look "encrypted". If the key exchange fails, TS maybe tries push delivery again. Please note that I do not know the TS code and this is all based on speculation.

**Comment by rhodey** [comment]
support for encrypted SMS was just recently removed by a4e18c515c61674dbe04f93fecce2b71c91f840b, please see [Saying goodbye to encrypted SMS/MMS](https://whispersystems.org/blog/goodbye-encrypted-sms/) for details. this issue will no longer exist in the next play store update you receive. thanks for documenting this issue! :)
