### ISSUE TITLE
Multipart SMS send error and delivery notification UI improvement

### ISSUE THREAD

**Issue by devurandom** [WhisperSystems/TextSecure#2409]
Recently I sent a large multipart SMS and shortly thereafter received a notification that sending failed. I tapped the notification and was brought to the just-sent message. Confusingly it had a checkmark for successful delivery.

I was not yet able to confirm with the receipient whether the message actually arrived completely, but the incident shows that the UI for multipart SMS in relation to delivery notifications as well as error messages needs to be improved. I.e. a checkmark for successful delivery should only be displayed if all parts arrived, and a send error should result in the whole message being marked as failed (light background plus red triangle icon). Additionally TS should continuously try to deliver the message again (or the failed parts thereof, if the SMS protocols allow that).

**Comment by rhodey** [comment]
@devurandom have you been able to reproduce this since? If it happens again please use the 'Submit debug log' feature in the advanced settings menu then paste the link here in this issue report. thanks!

**Comment by devurandom** [comment]
So far it only happened once. I do not send huge SMS that often, though. How does your request for debug info relate to [Saying goodbye to encrypted SMS/MMS](https://whispersystems.org/blog/goodbye-encrypted-sms/)?

**Comment by riyapenn** [comment]
Is this still an issue?

**Comment by devurandom** [comment]
I didn't encounter this again.
