### ISSUE TITLE
Push registration service not available : Error Bad response 503

### ISSUE THREAD

**Issue by git12a** [WhisperSystems/TextSecure#2411]
The textsecure-service.whispersystems.org service seems to be unavailable from my debug log here : https://pastebin.mozilla.org/8552749 

I've android 4.4.4 and running all latest updates for system and also the Textsecure app.
Push messaging worked until few days before, two days back I unregistered and then reinstalled application, now if I try to enable push messaging, neither sms nor phone verfikitaion works.

I wondered it was my isp blocked textsecure-service.whispersystems.org , so I used my vpn account to request push registration verifikation call, still the same result, so i'm sure the problem here not in my end.

**Comment by moxie0** [comment]
Looks like it's a problem just with voice call verification (not sms), just with one of our gateways.

**Comment by hope15** [comment]
I can confirm this problem, neither phone nor sms verification works atm when I try to register.

**Comment by git12a** [comment]
@moxie0 No, neither sms nor voice call verifikation works. Both seem to be down like that for the last ~30 hours. I didn't capture sms verifikation fail in debug log since sms verifikation form no longer shows up, it directly lands into voice call verifikation form as sms check had failed many times before.

**Comment by moxie0** [comment]
Try now.

**Comment by hope15** [comment]
It's now working, thanks

**Comment by git12a** [comment]
It's working now, thanks. 
Sms failed, voice call worked.
