### ISSUE TITLE
Is there a way to create an "incognito thread"?

### ISSUE THREAD

**Issue by ghostbar** [WhisperSystems/TextSecure#2412]
It would be nice to have a way to create a thread that can cleans the logs automatically based on timing.

Not only that, it would be good to have a way to delete messages from the thread and affect both parties, something like Twitter does with the DMs. So a message that gets deleted in a peer-thread gets deleted on the other peer-thread.

**Comment by agrajaghh** [comment]
Deleting messages from the remote party is a duplicate of #1764

**Comment by moxie0** [comment]
There is not.
