### ISSUE TITLE
Wrong default MMS settings for Slovenian provider Tušmobil

### ISSUE THREAD

**Issue by bungabunga** [WhisperSystems/TextSecure#2413]
My sister's phone wasn't able to send/recieve MMS messages so I checked things out. When I entered the manual settings that I copied from the default SMS/MMS app on her phone it worked. I believe that one setting is set wrong and all the others are ok.

provider: Tušmobil

WRONG: MMS Proxy: 91.185.221.085
OK: MMS Proxy: 91.185.221.85

I wanted to open Pull request and correct the setting myself but wasn't sure which is the right file to edit.

**Comment by mcginty** [comment]
Thanks! I bet we just need to remove all leading zeros from IPs in the `apns.xml` file, as it seems to be problematic.
