### ISSUE TITLE
Permanent textsecure communication failure with 2.5 version

### ISSUE THREAD

**Issue by vuwameli** [WhisperSystems/TextSecure#2420]
One of these commits give me problems:
8aa0f15740c7efb001f83be0cfe010f3cb211db8
18d4d4de24b00e61c540e29024ff8196e3529f06
b3c42dee7e0cf172b99e9c47bb4a8e5fbfe1516d
5836f35291f19b8d456ad29ca5fff77c7eef8bec
dbd8a4083cc379a00bacfccbc8a3c2dc0ef42d71

I built Textsecure from source today and now I get this error message all the time: 'Permanent textsecure communication failure' and 'Textsecure was unable to register with Google Play Services. Communication over t...' and 'Update Google Play services. This app won't run unless you update Google Play services.'

But the messages are not true - Textsecure is working fine. No Problems, I can send and receive via push, via SMS. I also very much doubt that my playstore services is the problem - I am using 6.1.83.

The build from yesterday morning does not have this problem. So one of the above mentioned commits must cause this.

**Comment by agrajaghh** [comment]
Thats weird, there wasn't changed anything regarding push messages / playstore...

**Comment by vuwameli** [comment]
Yes, weird. I assume it could have something to do with one commit that changed some strings for GcmRefreshJob or some other strings. 

The thing is textsecure works but it gives this annoying error messages all the time.
And the commit happened between yesterday and today - that is for sure.

**Comment by vuwameli** [comment]
The log tells me:

W/PartProvider(12808): Got master secret: org.thoughtcrime.securesms.crypto.MasterSecret@41cbe510
W/GcmRefreshJob(12808): GCM registrationId expired, reregistering...
W/GooglePlayServicesUtil(12808): Google Play services out of date.  Requires 6587000 but found 6183030
W/service (12808): Broadcasting new secret...
W/SendReceiveService(12808): Got a MasterSecret broadcast...
W/PartProvider(12808): Got master secret: org.thoughtcrime.securesms.crypto.MasterSecret@41d20d48

So why is this coming up as of today? I see that it expects a different play store version but why not using the old one? E.G. if one is not able to upgrade the play store.

**Comment by agrajaghh** [comment]
Are you using a custom rom? Normally the play services should update automatically, no? I have 6.5.99 on my phone...

**Comment by vuwameli** [comment]
Yes, I use OmniRom with a gapps package from paranoidandroid. It was fine until today...

**Comment by agrajaghh** [comment]
So it looks like a problem with your rom... 

btw, play services got changed from 6.1 to 6.5 here: https://github.com/WhisperSystems/TextSecure/commit/810abe0275364f11c9f1672a385048c82ba23b4b

**Comment by vuwameli** [comment]
I see. The change was made from 6.1 to 6.5. Seems I have to update play service then. 

The dependency on play services is really annoying anyways. Would be so good to have an open source alternative of that. Play services is polluting my phone... I know the blog post about the huge infrastructure that would be needed for a change. It is a pity...

Guess this ticket can be closed.

**Comment by agrajaghh** [comment]
you can close it yourself, next to the "comment" button...
