### ISSUE TITLE
Drop-down menu unreadable in dark theme

### ISSUE THREAD

**Issue by privong** [WhisperSystems/TextSecure#2422]
In 2.5.0, the drop-down menu available when selecting individual messages within a thread is not readable. The menu has a light background and light text (instead of a dark background and light text), so the text is not readable. This is the menu that has "resend message". 

The drop-down menu for the screen with the conversations list does have the appropriate light text on dark background theme.

Using TextSecure 2.5.0 on Android 4.4.4.

**Comment by mcginty** [comment]
Yeah, it looks like the batch selection actionbar isn't honoring the dark actionbar's "PopupTheme" that we set. Will look into that, thanks @privon!

**Comment by billie80** [comment]
Btw. the same goes for the context menu which opens from the text composition entry. There is light grey text on white background.

**Comment by McLoo** [comment]
:) https://github.com/WhisperSystems/TextSecure/pull/2375#issuecomment-71023176

**Comment by mcginty** [comment]
fixed in ea77191b70ae10a04ba83755abbe899fef391ab0, also good earlier catch @McLoo! Sorry I missed it.

**Comment by billie80** [comment]
There are still some issues with the dark theme.
The add user selection when creating a group:
![screenshot-1423598735797](https://cloud.githubusercontent.com/assets/9938306/6151120/0c9fba92-b214-11e4-9d81-802246e593b5.png)
The context menu from the text composition entry (also mentioned in issue #2447):
![screenshot-1423598786252](https://cloud.githubusercontent.com/assets/9938306/6151121/0ca36282-b214-11e4-97ba-6d09acd1b632.png)
