### ISSUE TITLE
End secure session

### ISSUE THREAD

**Issue by rene0720** [WhisperSystems/TextSecure#2427]
Hello,

the app is getting better and better, I really like it.

I have one small problem, I can't end a secure session, a friend has an account but he didn't use it anymore so I see him as a TS user and so I send all messages over push, if I don't send i via normal sms. When I click end secure session it sends the message that it has ended but it didn't change anything.

A friend ask me if there is a support for iOS soon? I sent him the invite link over TS and a app was available but he cound't register?

Thanks.
Regards, 
Rene

**Comment by moxie0** [comment]
Your friend needs to unregister:
http://support.whispersystems.org/customer/portal/questions/9532693-textsecure-does-not-recognize-when-a-contact-stopped-using-textsecure

In the future the best place for support is the support center.  This is for tracking issues.

**Comment by rene0720** [comment]
Sorry and thanks for the answer.
