### ISSUE TITLE
Sent time not translated

### ISSUE THREAD

**Issue by oholika** [WhisperSystems/TextSecure#2432]
The timestamp for the sent messages is not translated into German with version 2.5.0.
It is "Now" and for example "2 mins".
I wanted to contribute the translation, but German is at 100%...

**Comment by agrajaghh** [comment]
I guess it got translated after the release. It will be included in the next one...

**Comment by oholika** [comment]
just updated to 2.5.1... the strings are still not translated

**Comment by agrajaghh** [comment]
I guess this was a fast bugfix release to fix some serious problems. They should be included in the next one ;)
