### ISSUE TITLE
Error -505 upon update

### ISSUE THREAD

**Issue by thirtythreeforty** [WhisperSystems/TextSecure#2436]
I get an error when pushing v2.5.1 to my device using Google Play:

```
02-09 22:46:00.329 D/Finsky  (26189): [1] InstallerTask.startCopyFromDownload: Prepare to copy org.thoughtcrime.securesms from content://downloads/my_downloads/4145 (expect 8385365 bytes)
02-09 22:46:02.111 D/Finsky  (26189): [1] 8.onPostExecute: Successfully copied APK to update org.thoughtcrime.securesms
02-09 22:46:02.112 D/Finsky  (26189): [1] InstallerTask.startInstaller: Begin install of org.thoughtcrime.securesms
02-09 22:46:04.051 E/Finsky  (26189): [1] PackageInstallerImpl.handleCommitCallback: Error -505 while installing org.thoughtcrime.securesms: INSTALL_FAILED_DUPLICATE_PERMISSION: Package org.thoughtcrime.securesms attempting to redeclare permission org.thoughtcrime.securesms.permission.C2D_MESSAGE already owned by org.thoughtcrime.securesms
02-09 22:46:04.052 W/Finsky  (26189): [1] 4.installFailed: Install failure of org.thoughtcrime.securesms: -505 null
02-09 22:46:04.083 D/Finsky  (26189): [1] InstallerTask.cancelCleanup: Cancel running installation of org.thoughtcrime.securesms
02-09 22:46:04.143 D/Finsky  (26189): [1] PackageInstallerImpl.innerCreateSession: Created session 1954080029 for org.thoughtcrime.securesms
02-09 22:46:04.182 D/Finsky  (26189): [1] AppActionAnalyzer.<init>: org.thoughtcrime.securesms is installed but certificate mistmatch
02-09 22:46:04.232 D/Finsky  (26189): [1] AppActionAnalyzer.<init>: org.thoughtcrime.securesms is installed but certificate mistmatch
02-09 22:46:13.020 D/Finsky  (26189): [1] 5.onFinished: Installation state replication succeeded.
```

If Google Play is in the foreground, it also displays a dialog concerning "error -505."

I'm not entirely sure what's going on here, except that there is a signature mismatch.  This is a Nexus 5 running CyanogenMod `12-20150209-NIGHTLY-hammerhead`.

Note that the update doesn't show up on Google Play on my device, and I have to push it manually with the desktop web browser.

**Comment by thirtythreeforty** [comment]
Never mind, apparently I have a debug version of 2.4.3 installed on my device that I forgot about. :grin: :+1:

**Comment by Sugarfreegoodies** [comment]
Masha suggested that I post my issue here. I have a Blu Life One X running 5.1, kernel 3.10.65 - - 11/9/15.

I cannot install any version of Signal, either from the Play store or from an Apk. 

Each time it gets 60% of the way through the install, and ends with a 505 error. 

I have done all the troubleshooting suggested on the net, with no success. Since it appears the error is caused by some app already installed with the same certificate, I've even tried deleting apps one by one with an attempted Signal install after each one. No joy. 

I do not wish to do a factory reset, but would be happy to try anything else.

**Comment by moxie0** [comment]
@Sugarfreegoodies please post a debug log, but if it's something happening during the actual APK install process, that's not anything we have any control over.

**Comment by Sugarfreegoodies** [comment]
I'll be happy to post a debug log - - if someone can tell me where to find
the log and how to post it. :)

**Comment by moxie0** [comment]
Since it sounds like you can't successfully install the app, you'd have to use 'adb logcat' with your phone hooked up to your desktop via USB.

**Comment by Sugarfreegoodies** [comment]
MoxieO, 

Happy to connect phone with laptop, but have no idea what adb logcat is, how to find it, use it or - - assuming I got instructions on how to do that - - post it here. Sorry to be a complete and ignorant Noob, but there's no point in denying it. :)

**Comment by moxie0** [comment]
It depends on your system, you'll have to google how to install the android SDK, how to enable developer options on your phone, how to use adb. Once you've done that, you can get the log from an install attempt and cut/paste it into here.

However, again, it is extremely unlikely that whatever difficulty you're having is something that can we can solve in the app. The application has no  knowledge of the fact that it is being installed, no code runs during install, and the entire install process happens outside of our control. If you're having difficulty during install, it is most likely an issue that can only be resolved at the OS/ROM level.

**Comment by nrizzio** [comment]
@Sugarfreegoodies you can come post on https://whispersystems.discoursehosting.net if you want help with getting the debug log

**Comment by Sugarfreegoodies** [comment]
I have Developer options enabled, but it really sounds like only a factory reset to get rid of whatever app is using the certificate Signal needs will solve the problem. Thanks for the help, though!

**Comment by Sugarfreegoodies** [comment]
Thanks, Nicholas! Will do that now.

**Comment by Sugarfreegoodies** [comment]
Hmm. Went there, clicked login, entered GitHub id and password, clicked With GitHub - - got error authorizing account. Not sure what to do now. Create a new account there?

**Comment by nrizzio** [comment]
@Sugarfreegoodies Try to do it again. If it doesn't work, you can create an account from your email address.

**Comment by Sugarfreegoodies** [comment]
Created new account. Certified address. Went to community. Created new topic. Typed this:Can't install Signal on my Blu Life One X running 5.1. - - Error 505. Have been told to post a debug log and have no idea what that is or how to access it. Nicholas Rizzio kindly suggested I request help here. 

Tried to save several times. Each time get 403 Forbidden.

**Comment by Sugarfreegoodies** [comment]
Ah. Removed last name and it posted. Feel like an idiot, but that's not a new feeling. :)
