### ISSUE TITLE
TextSecure steals all MMS, no option to allow default app to handle

### ISSUE THREAD

**Issue by kb100** [WhisperSystems/TextSecure#2443]
For whatever reason, TextSecure's MMS support is terrible. Everyone that I've shown TextSecure to has stopped using it because it loses MMS, crashes on receiving MMS, fails to download MMS, doesn't notify on receiving MMS, or some other long standing MMS related problem.

We need an option to let the system handle MMS, while still letting TextSecure grab SMS.

**Comment by moxie0** [comment]
Android doesn't make that possible.
