### ISSUE TITLE
Edit text menu items are a bad color in dark theme

### ISSUE THREAD

**Issue by landry314** [WhisperSystems/TextSecure#2447]
In the dark theme, open any conversation and long press in the enter text area. A menu will pop up called "Edit text" with options "Paste" and "Input Method" in an almost unreadable light gray color.

This looks like an oversight because the default text colors work in the light theme but not in the dark, but I am just guessing.

**Comment by rhodey** [comment]
assuming this is also gingerbread specific because I'm unable to reproduce on my modern devices, and in that case it's likely related to #2460

**Comment by riyapenn** [comment]
Is this still an issue?
