### ISSUE TITLE
Can send with TS on jolla but not receive messages

### ISSUE THREAD

**Issue by piratenpanda** [WhisperSystems/TextSecure#2448]
I know that SailfishOS is not yet (hopefully soon) a supported OS but using the playstore there to install TS and the play services TS works for sending messages to other TS instances yet I don't receive any messages. It worked a few days before so I'm not sure if 2.5.x changed something there.

I understand that I don't get push notifications but at least I should get the messages when TS is running, right? I understand if nobody is willing to support me on this but I'd really like to find a workaround for this as other GCM based apps like Threema work in both directions so it should be possible. I'd provide any information needed if someone feels like helping me on this.

**Comment by JavaJens** [comment]
Maybe you can provide a debug log from your registration process?

**Comment by piratenpanda** [comment]
When trying to log anything there's no log, just the aliendalvik android version and after main.log theres nothing else

**Comment by moxie0** [comment]
SailfishOS is not supported.
