### ISSUE TITLE
Sms Sent from Blackberry won't be displayed

### ISSUE THREAD

**Issue by dede222** [WhisperSystems/TextSecure#2456]
All SMS messages which were sent from a BB 10.2 won't be displayed on my LGG3. On the stock/ Build in SMS App the messages work and are displayed/delivered but not on the current TextSecure App.

**Comment by agrajaghh** [comment]
please post a debug log

**Comment by dede222** [comment]
Device : LGE LG-D855 (g3_global_com)
Android: KVT49L.A1412000029
OS Host: LGEARND12B13
App    : TextSecure 2.5.1

--------- beginning of /dev/log/main
I/ActivityManager(20464): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:16372033
W/MmsSmsDatabase(20464): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, 'sms' AS transport_type FROM sms WHERE (thread_id = 26) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, 'mms' AS transport_type FROM mms WHERE (thread_id = 26) ORDER BY date_received DESC) LIMIT 1
W/RecipientProvider(20464): Cache miss [SYNC]!
W/KeyCachingService(20464): Incrementing activity count...
W/KeyCachingService(20464): Decrementing activity count...
W/RecipientProvider(20464): Cache miss [ASYNC]!
W/RecipientProvider(20464): Cache miss [ASYNC]!
W/RecipientProvider(20464): Cache miss [ASYNC]!
W/RecipientProvider(20464): Cache miss [ASYNC]!
W/RecipientProvider(20464): Cache miss [ASYNC]!
W/RecipientProvider(20464): Cache miss [ASYNC]!
W/RecipientProvider(20464): Cache miss [ASYNC]!
W/KeyCachingService(20464): Incrementing activity count...
I/ActivityManager(20464): Timeline: Activity_idle id: android.os.BinderProxy@43e7c658 time:16372523
--------- beginning of /dev/log/system
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_UP
D/BubblePopupHelper(20464): isShowingBubblePopup : false
E/ViewRootImpl(20464): mIsPenSupport: :false
D/dalvikvm(20464): GC_CONCURRENT freed 3872K, 16% free 38457K/45592K, paused 4ms+6ms, total 88ms
D/dalvikvm(20464): WAIT_FOR_CONCURRENT_GC blocked 36ms
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_UP
I/ActivityManager(20464): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:16377241
W/KeyCachingService(20464): Decrementing activity count...
E/ViewRootImpl(20464): mIsPenSupport: :false
W/KeyCachingService(20464): Incrementing activity count...
I/ActivityManager(20464): Timeline: Activity_idle id: android.os.BinderProxy@441c7c78 time:16378014
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_DOWN
W/TouchFlickNoti(20464): CAPP_TOUCH_FLICK: UP vectorVelocity:0 signal:0
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_UP
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_UP
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_UP
I/ActivityManager(20464): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:16386955
W/KeyCachingService(20464): Decrementing activity count...
D/BubblePopupHelper(20464): isShowingBubblePopup : false
E/ViewRootImpl(20464): mIsPenSupport: :false

**Comment by dede222** [comment]
I hope this will help to find a solution for this strange Blackberry issue.

**Comment by moxie0** [comment]
There's nothing in this log.  You'll need to post a full log from immediately after when an SMS should have arrived.

This is more likely an Android problem than a TextSecure problem, though.  The OS handles all the SMS stuff.

**Comment by dede222** [comment]
Strange. When I deactivate TextSecure and use the stock build in LG Sms app the Blackberry messages arrive immediately.

**Comment by dede222** [comment]
Ok. Here er go. Two Sms didn't arrive.
Hope the log showes this.

**Comment by dede222** [comment]
Device : LGE LG-D855 (g3_global_com)
Android: KVT49L.A1412000029
OS Host: LGEARND12B13
App    : TextSecure 2.5.1

--------- beginning of /dev/log/main
I/ActivityManager(20464): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:25953540
W/KeyCachingService(20464): Incrementing activity count...
W/KeyCachingService(20464): Decrementing activity count...
W/KeyCachingService(20464): Incrementing activity count...
I/ActivityManager(20464): Timeline: Activity_idle id: android.os.BinderProxy@43e7c658 time:25953828
--------- beginning of /dev/log/system
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_UP
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_UP
I/ActivityManager(20464): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:25958818
W/KeyCachingService(20464): Decrementing activity count...
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
E/ViewRootImpl(20464): mIsPenSupport: :false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
W/KeyCachingService(20464): Incrementing activity count...
D/cliptray_Editor(20464):  setInputTypeforClipTray(): 0
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
I/ActivityManager(20464): Timeline: Activity_idle id: android.os.BinderProxy@4494e830 time:25959470
D/ContactsDatabase(20464): finished populating push users.
W/RecipientProvider(20464): Cache miss [SYNC]!
W/RecipientProvider(20464): Cache miss [SYNC]!
W/RecipientProvider(20464): Cache miss [SYNC]!
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
W/RecipientProvider(20464): Cache miss [SYNC]!
D/dalvikvm(20464): GC_CONCURRENT freed 4426K, 16% free 39071K/46412K, paused 10ms+11ms, total 132ms
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_UP
W/TouchFlickNoti(20464): CAPP_TOUCH_FLICK: UP vectorVelocity:-218 signal:-1
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_DOWN
W/TouchFlickNoti(20464): CAPP_TOUCH_FLICK: UP vectorVelocity:-78 signal:-1
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_UP
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): finished populating push users.
W/RecipientProvider(20464): Cache miss [SYNC]!
W/RecipientProvider(20464): Cache miss [SYNC]!
W/RecipientProvider(20464): Cache miss [SYNC]!
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
W/RecipientProvider(20464): Cache miss [SYNC]!
D/ContactsDatabase(20464): finished populating push users.
W/RecipientProvider(20464): Cache miss [SYNC]!
W/RecipientProvider(20464): Cache miss [SYNC]!
W/RecipientProvider(20464): Cache miss [SYNC]!
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
W/RecipientProvider(20464): Cache miss [SYNC]!
D/ContactsDatabase(20464): finished populating push users.
W/RecipientProvider(20464): Cache miss [SYNC]!
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): finished populating push users.
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): finished populating push users.
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/ContactsDatabase(20464): finished populating push users.
D/dalvikvm(20464): GC_CONCURRENT freed 4393K, 17% free 38656K/46412K, paused 3ms+5ms, total 69ms
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): finished populating push users.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): finished populating push users.
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/ContactsDatabase(20464): finished populating push users.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/ContactsDatabase(20464): finished populating push users.
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): finished populating push users.
D/ContactsDatabase(20464): onCreate called for contacts database.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): populating push users into virtual db.
D/ContactsDatabase(20464): finished populating push users.
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): finished populating push users.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/ContactsDatabase(20464): finished populating push users.
D/ContactsDatabase(20464): onCreate called for contacts database.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): populating push users into virtual db.
D/dalvikvm(20464): GC_CONCURRENT freed 4084K, 17% free 38659K/46408K, paused 6ms+8ms, total 114ms
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): finished populating push users.
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): finished populating push users.
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
D/ContactsDatabase(20464): finished populating push users.
D/ContactsDatabase(20464): onCreate called for contacts database.
D/ContactsDatabase(20464): populating push users into virtual db.
E/View    (20464): hasTransientState decremented below 0: unmatched pair of setHasTransientState calls
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
W/IInputConnectionWrapper(20464): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(20464): getSelectedText on inactive InputConnection
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/BubblePopupHelper(20464): isShowingBubblePopup : false
D/ContactsDatabase(20464): finished populating push users.
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl(20464): ViewRoot's Touch Event : ACTION_UP
I/ContactSelectActivity(20464): Choosing contact from list.
W/RecipientProvider(20464): Cache miss [SYNC]!
I/ActivityManager(20464): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:25991241
W/KeyCachingService(20464): Decrementing activity count...
W/PhoneNumberFormatter(20464): Got local CC: DE
D/BubblePopupHelper(20464): isShowingBubblePopup : false
W/MmsCommunication(20464): Getting MMSC params for apn null
W/TelephonyUtil(20464): Choosing MCC+MNC info from TelephonyManager.getSimOperator()
W/ApnDatabase(20464): Querying table for MCC+MNC 26202 without APN name
E/ViewRootImpl(20464): mIsPenSupport: :false
W/ApnDatabase(20464): Returning preferred APN Apn{ mmsc: "http://139.7.24.1/servlets/mms", proxy: "139.7.29.17", port: 80, user: none, pass: none }
W/MmsSmsDatabase(20464): Executing query: SELECT _id, body, read, type, address, address_device_id, subject, thread_id, status, date_sent, date_received, m_type, msg

**Comment by dede222** [comment]
Hi all. Found a soulution myself. 
Obviously a Xprivacy setting was responsilbe for blocking those messages.
Thanks anyway for your support.

**Comment by moxie0** [comment]
And people wonder why developers hate xprivacy.
