### ISSUE TITLE
Icon design discrepancies?

### ISSUE THREAD

**Issue by aprescott** [WhisperSystems/TextSecure#2458]
After I got the latest update including the logo change from green to blue, I noticed a discrepancy at the top of the icon, where there seems to be some noise. When I looked closer, I also spotted some potential problems on the edges, where the circle seems to have been clipped.

![circle issues](https://cloud.githubusercontent.com/assets/342081/6157977/ec0042fc-b213-11e4-9ef6-d4aa3a39c14e.png)

Was this intentional? It looks like some kind of artifact.

**Comment by aprescott** [comment]
I also noticed that the bottom of the icon seems to not be center-aligned. Very roughly, just from eyeballing it:

![center alignment](https://cloud.githubusercontent.com/assets/342081/6158001/3098e9b4-b214-11e4-8956-9a104a27233a.png)

It in fact seems to be intentionally at an off angle:

![off-angle](https://cloud.githubusercontent.com/assets/342081/6158005/38149a94-b214-11e4-941a-0bf98ba9245c.png)

This seems like it could be less of a design "bug" and more of an intentional aesthetic choice, but it does look a little odd to me.

**Comment by mcginty** [comment]
This looks like flaws in the resized assets generated from my large "master" icon. The xxhdpi version that you're showing looks like it has an unfortunate shadow-hat that doesn't exist in xhdpi, for example. That's not intentional, will see what I can do about having the resized versions reflect the main icon more accurately.

The "tick" at the bottom of the icon isn't at an angle, but it is off-center, which was an aesthetic choice.

**Comment by aprescott** [comment]
:+1: good to know, thanks! (The tick at the bottom only seemed like an issue to me because I couldn't see what else it was supposed to be aligned with and was otherwise veeery close to center.)

**Comment by mcginty** [comment]
Thanks for your great images and descriptions, by the way! Very helpful to show what you're talking about like that.

**Comment by riyapenn** [comment]
Closed as old logo.

**Comment by aprescott** [comment]
Oh, neat, is there a place I can see the new logo?

**Comment by aprescott** [comment]
(Latest version of the app and various 3.x branches in GitHub all seem to have the same discrepancy of a flattened top.)

**Comment by riyapenn** [comment]
Was referring to logo available at https://www.pixelapse.com/openwhispersystems/projects/signal-android/views/assets/ in issue #2534

**Comment by aprescott** [comment]
Ah, my mistake, I thought there was a newer logo coming from a Signal app rename update. I could be over-analyzing the crop that may or may not be there, then.
