### ISSUE TITLE
IV is zero on Android 4.3

### ISSUE THREAD

**Issue by colesbury** [WhisperSystems/TextSecure#2461]
The AES-CBC encryption flow tends to look like:

    Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
    cipher.init(Cipher.ENCRYPT_MODE, key);
    byte[] ivBytes = cipher.getIV();

On Android 4.4, this will use a random IV. On Android 4.3, it will use zero as the IV.

Refer to the following files:

AttachmentCipherOutputStream.java 
ProvisioningCipher.java 
EncryptingPartOutputStream.java 
MasterCipher.java

**Comment by moxie0** [comment]
If true, that's a pretty critical Android bug. Is it documented somewhere?

**Comment by colesbury** [comment]
I haven't found any documentation about this. If your curious, I believe this the relevant change in the Android source:

https://android.googlesource.com/platform/external/conscrypt/+/3974cacc0af4d6c5e19bf290ea4cdbdc2887fe56%5E%21/#F0 (engineInitInternal)

Android 4.1 doesn't have this problem. It defaults to BouncyCastle instead of OpenSSLProvider for AES encryption, and the BC provider generates a random IV if one isn't given.

The fix is to pass in an explicit, random IV when initializing the cipher:

  byte[] ivBytes = <random bytes>
  Cipher cipher = Cipher.getInstance("AES/CBC/PKCS5Padding");
  cipher.init(Cipher.ENCRYPT_MODE, key, new IvParameterSpec(ivBytes));

**Comment by moxie0** [comment]
Android never fails to let us down.  We just removed spongycastle in the last release, looks like we should put it back in.

**Comment by johanw666** [comment]
Is this also an issue on 4.2? And is it fixed in 2.5.2 or will we see a 2.5.3 shortly?
