### ISSUE TITLE
Handle message "types" differently

### ISSUE THREAD

**Issue by jkaberg** [WhisperSystems/TextSecure#2468]
Sorry for the bad title, please adjust to your liking :)

So right now we have,
- Push message (encrypted)
- Encrypted SMS
- Unencrypted SMS

Would it be possible to adjust current settings (or create a new one, in like say a profile thingy?), so that if contact is offline (recipient wont receive push msg instantly), TS would automagicly use (secure) SMS instead?

When I send messages I like to know that messages are actully received at the other end. With current setup I just don't know if it has, and even if we could get some kind of status icon/message it would be a lot nice if this is handled automaticly

Thoughts? :)

**Comment by McLoo** [comment]
moxie0: '*The concept of "online" doesn't really exist in an asynchronous world*'
#678

**Comment by jkaberg** [comment]
Oh sorry, I did search but never found that one. Cloesing :)
