### ISSUE TITLE
no key exchange and no encryption with textsecure user

### ISSUE THREAD

**Issue by piecam** [WhisperSystems/TextSecure#2470]
HI ,

I installed Textsecure 2.5.3 from GooglePlay to my Nexsus 5 and to my wife's Nesus 5. I installed RedPhone as well.

Redphone seems working fine. However, the sms between two Textsecure account (me and my wife) always goes UNencrypted (green with lock open), even though both got registered with server and activated.

It's running on top of SLIMBean droid. 

Any ideas?

thanks

**Comment by streblo** [comment]
You could try with a third (known to be working) device and narrow down if communication is failing with both devices or just one. PM me if you want to try with my phone #

**Comment by piecam** [comment]
HI streblo,

Can you help me trying between your number and mine? mine is +1 647 648 
0992.

thanks in advance.
peng

**Comment by streblo** [comment]
I sent a text, doesn't seem secured, but you might have to reply first to
complete the handshake.

**Comment by piecam** [comment]
HI Streblo,

thanks for the help with testing. I was wondering whether this is a 
single case for me or somebody else having similar issue.

Best regards

**Comment by streblo** [comment]
I don't know. I'm not very involved with OpenWhisper Systems

**Comment by piecam** [comment]
HI,

It's working now after I reinstalled/registered my wife's phone. Not 
sure whether I have to touch the bottom right lock icon to select 
(encrypted,unencrypted) or just the two numbers didn't get registered 
properly.

thanks

**Comment by rhodey** [comment]
thanks for checking back in @piecam :)
