### ISSUE TITLE
Sending encrypted TS-message not possible (Trust anchor for certification path not found)

### ISSUE THREAD

**Issue by bartensud** [WhisperSystems/TextSecure#2471]
Hi,
since today, when I can not send a message to another TextSecure user (4 different user tested several times):
After I press the send icon it's shown very quickly (<1sec) that I can re-send as SMS (the message bubble is gray-ish green; the lock is closed; but not further info/pop-up about an error). Re-send via encrypted SMS is working then (the message bubble turns in solid green).

Debug Log: https://gist.github.com/anonymous/9262e8e11ae5949f156f
In the logs I detected the error "**Trust anchor for certification path not found.**" several times:
> W/PushServiceSocket( 4833): Push service URL: https://textsecure-service.whispersystems.org
> W/PushServiceSocket( 4833): Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+***********42
> W/PushTextSendJob( 4833): org.whispersystems.textsecure.api.push.exceptions.PushNetworkException: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

Maybe the issue comes from an **issue with the certificate**: When I open https://textsecure-service.whispersystems.org/ in Chromium browser a warning about the certificate is shown: *"This server could not prove that it is textsecure-service.whispersystems.org; its security certificate is from *.lyft.com. This may be caused by a misconfiguration or an attacker intercepting your connection."*

Device : samsung GT-I9195 (serranoltexx)
Android: KOT49H.I9195XXUCNK4  (Android 4.4.2)
OS Host: SWDD3013
App    : TextSecure 2.5.3

Btw, thanks a lot for TextSecure!:-)

**Comment by moxie0** [comment]
lyft.com? Sounds like you're on a network that has a captive portal or is otherwise redirecting/mitming your connections.
