### ISSUE TITLE
Problem with incoming group MMSs

### ISSUE THREAD

**Issue by FatherMcGruder** [WhisperSystems/TextSecure#2477]
Often, when I receive group messages, some of the messages do not make it to the group chat screen. Instead, they arrive as what appears to be a non-group MMS seperate from the group chat with no contents other than a dowload button. If I click the download button and stay on that screen, the message eventually makes it to the group chat screen. However, the messages tends to show in the order that they've been dowloaded, not sent, which makes comprehending the conversation difficult. This problem appears to only occur with messages from non-TextSecure users, although I cannot say for sure. Only one of my contacts uses TextSecure.

**Comment by moxie0** [comment]
That's just how MMS works I'm afraid.  The group information isn't available until the MMS is retrieved, so if there's a problem retrieving it, we have to show the notification in the sender thread.  We don't even know it's a group MMS until after we've retrieved it.

**Comment by FatherMcGruder** [comment]
I figured. Is there a way for TextSecure to ignore MMSs and let another app handle them?

On February 15, 2015 9:16:02 PM EST, Moxie Marlinspike <notifications@github.com> wrote:
>That's just how MMS works I'm afraid.  The group information isn't
>available until the MMS is retrieved, so if there's a problem
>retrieving it, we have to show the notification in the sender thread. 
>We don't even know it's a group MMS until after we've retrieved it.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/WhisperSystems/TextSecure/issues/2477#issuecomment-74451652

-- 
Sent from my Android device with K-9 Mail. GnuPG signing/encryption available upon request.

**Comment by moxie0** [comment]
Android does not allow that.
