### ISSUE TITLE
new conversation FAB inaccessible

### ISSUE THREAD

**Issue by the-kyle** [WhisperSystems/TextSecure#2494]
Running the latest TextSecure on an LG Optimus F3Q, I am no longer able to focus the button to compose a new message using the keyboard on the phone. I seem to have no trouble focusing any other elements on the screen, I just can't find this button. I was able to focus the button in the previous version, but I can no longer find it with my arrow keys as of today. I was able to find it by exploring the screen with my finger using both Talkback and Spiel screen readers, but in both cases, the button has no label associated with it, and is now presented to me as simply "button." In order to make best use of this app using my screen reader, the button needs to have a content description associated with it that would allow me to know what the button does. If possible, it should also be able to be focused using a hardware keyboard, whether built in or external.

**Comment by mcginty** [comment]
Thanks so much for the issue, @the-kyle. I just put a fix in master for the focusable issue, seems to work in my emulator when using the tab key.

I turned on TalkBack and was able to have it dictate "Send TextSecure message button" when focused, so hopefully it was just that "focusable" flag and "nextFocusForward" that was screwing things up.

**Comment by the-kyle** [comment]
The problem I was having was related to the button to start a new
conversation. So far, I've had no problems sending a message, I only had
problems starting a new conversation. Sorry for the confusion.
-- 
"Don't judge my disability until you are able to see my ability."
~Kyle: https://kyle.tk/
My chunk of the internet: https://chunkhost.com/r/Kyle

**Comment by mcginty** [comment]
Ah I see, this would be the FloatingActionButton then.

**Comment by the-kyle** [comment]
Possibly. It seems to appear at the lower right corner of the screen
when the list of conversations is visible. Talkback is presenting it as
"button." There is also a button appearing in the upper right corner
next to "search" that is presented as "more options." This one seems
fine, as a hardware menu button appears to open that same menu. However,
there appears to be no way to focus the "button" at the lower right
corner of the list of conversations, and it appears to have no content
description, as it was only activation of the button that indicated that
it presented the screen to start a new conversation along with the
contact selection. Hope this helps.

**Comment by mcginty** [comment]
@the-kyle I added a content description and explicitly set the button floating in the bottom right as focusable. Unfortunately, I've tried to get the right focus order set so it appears with the other menu items but haven't found a way yet. Hopefully this first small change increases usability for you at least a bit, though.

**Comment by mcginty** [comment]
Not even Google's Inbox app does this properly, so closing for now until we can work out a way to make Android's accessibility APIs behave...
