### ISSUE TITLE
Adaptive Bitmap memory consumption

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/TextSecure#2495]
Change Bitmap memory usage depending on the available heap size.

- [ ] store low-fidelity images like thumbnails and contact photos with `RGB_565` option instead of `ARGB_8888`
- [ ] lower max image dimension when sending images/video to below 1280 depending on memory constraints
- [ ] look into using `inMemory` option when available to reuse existing allocated Bitmap memory

**Comment by tinloaf** [comment]
@mcginty Are you on this? I have some time on my hands again (well, actually I have to study for exams...) and would use this to get into the code again? Or did you already start?

**Comment by mcginty** [comment]
@tinloaf i'm on this, a PR is out soon. Sorry I missed this comment earlier.

**Comment by mcginty** [comment]
Closed now that the glide PR is in
