### ISSUE TITLE
My Downloaded source has issues

### ISSUE THREAD

**Issue by zeeshan4971** [WhisperSystems/TextSecure#2496]
Hi,
My name is zeeshan and i am new to GitHub and this is my first post i have downloaded the source compiled it into APK and i am faceing these issues

1) Menus Problem in LG crashes on menu button click
2) When i send media and images to another user when the user clicks on the received media it is taken to a blank page. every time he clicks on the media he is taken to a blank page.

How can i fix these issues or if some one have the source code with the fixed issues can you give me the link thank you.

**Comment by jeremymasters** [comment]
I think when you compile the source and side load the apk you do this at the risk of not having a play-store-ready app.

**Comment by mcginty** [comment]
@zeeshan4971 are you on the most recent `master` branch? What LG device are you using that crashes on menu button clicks? Can you post a debug log?

**Comment by zeeshan4971** [comment]
@mcginty  Well my issue is resolved because i did not see that the latest <code>master</code> has been updated with this issue resolved  i will check this new <code>master</code> and update you as soon as possible.
