### ISSUE TITLE
Default SMS program

### ISSUE THREAD

**Issue by dhermosillo** [WhisperSystems/TextSecure#2497]
I installed Text Secure on my Galaxy Note 3, Android 4.4.4 and now the native Messaging SMS app will not let me send messages from it.  It fills the text box with "cannot send messages"

Also, Text Secure and the native Android Messaging app both ask if I want to set them as default when I use either.

I have a Galaxy S3 and neither TS or Messaging ask for a default.

**Comment by mcginty** [comment]
Are either TS or Messaging actually your default messaging app? You can check in your Android settings.

**Comment by dhermosillo** [comment]
I figured it out.  If I leave the Android Messaging as the default, and say No to making TS the default, then both work fine and the message doesn't pop up every time.
