### ISSUE TITLE
Send button long press to change delivery mechanism not remembered

### ISSUE THREAD

**Issue by maxchill** [WhisperSystems/TextSecure#2503]
In conversation mode, I long press send button to change from push message to secure sms.  Message is delivered successfully.

If I leave conversation and come back, the send button has now been reset to push mode.  Perhaps it should remember the last delivery type on a global or per conversation basis?

**Comment by maxchill** [comment]
Is this expected behavior? Or a previously identified issue?  I convinced a friend to use textsecure yesterday and he pointed this out to me.  He didn't want to disable push messaging globally, instead wanted to be able to be able to quickly swap on demand.

**Comment by moxie0** [comment]
Duplicate issue and expected behavior.
