### ISSUE TITLE
VCARD text support?

### ISSUE THREAD

**Issue by redragonx** [WhisperSystems/TextSecure#2504]
Is there a ETA for this?

E.G. Apple users send me a VCARD and I just get a wall of text.

**Comment by moxie0** [comment]
Duplicate of #2252, #535, and #499

**Comment by moxie0** [comment]
@redragonx This is not a discussion forum.  Please only post new issues if they aren't already documented in another issue.  Please only post new comments if you have new information to add, otherwise it just slows us down by creating more email we have to deal with.
