### ISSUE TITLE
When i compile textsecure app i it gives me this error

### ISSUE THREAD

**Issue by zeeshan4971** [WhisperSystems/TextSecure#2510]
I am downloading the lastest relese,

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:proguardDebug
Warning:can't write resource [.readme] (Duplicate zip entry [classes.jar:.readme])
:dexDebug
Error:Could not create the Java Virtual Machine.
Error:A fatal exception has occurred. Program will exit.
Invalid maximum heap size: -Xmx4g
The specified size exceeds the maximum representable size.
Error:Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	D:\Softwares installed\Android\android-sdk\build-tools\21.1.2\dx.bat -JXmx4g --dex --output D:\Softwares installed\TextSecure-master2\build\intermediates\dex\debug --input-list=D:\Softwares installed\TextSecure-master2\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
	1
Output:
	Error: Could not create the Java Virtual Machine.
	Error: A fatal exception has occurred. Program will exit.
	Invalid maximum heap size: -Xmx4g
	The specified size exceeds the maximum representable size.
Information:BUILD FAILED
Information:Total time: 4 mins 6.043 secs
Information:3 errors
Information:1 warning
Information:See complete output in console

**Comment by moxie0** [comment]
@zeeshan4971 This is an issue tracker, not a discussion forum.  We can't help you with your Android build environment.
