### ISSUE TITLE
setting issue on Nexus4-No passphrase required!

### ISSUE THREAD

**Issue by haniehm** [WhisperSystems/TextSecure#2512]
I recently installed Textsecure for the first time and was expecting to be asked about "passphrase" after searching the usual setup steps. I was asked about my phone number and got registered. I was also asked about importing the existing messages to Textsecure and setting up the app as my main sms app. However, any time that I am trying to use it, the lock beside my send arrow is open. I am not sure what I have done wrong or whether my friends should install it before having a secure text conversation. I understand that the project is dynamic but "It is not easy to find a fast setup guide online."

**Comment by grandchild** [comment]
Of course your contacts need TextSecure as well in order for the whole thing to work.
Also note that this is a bug tracker, not a support forum. See http://support.whispersystems.org/ for more help.

**Comment by haniehm** [comment]
Well I couldn't find the answer to my question easily. and yes I am aware that here is mainly a bug registry. So is it normal and not a bug that I wasn't asked for any "passphrase"?

**Comment by moxie0** [comment]
The best place for support is the support center: http://support.whispersystems.org or emailing support at whispersystems.org
