### ISSUE TITLE
Encrypted SMS/MMS over GSM optional feature

### ISSUE THREAD

**Issue by smarek** [WhisperSystems/TextSecure#2515]
Hello,

I've read whole mailing list thread discussing and few tickets here on github of TextSecure, that explains that the feature is now gone.

If I understand it correctly, in the same manner as RedPhone the feature of end-to-end encryption of SMS now works only if TextSecure is used with GCM/APN (textsecure-backend + signal-ios).

If that's correct, would it be possible to bring this feature back as optional feature in application settings?
I'm willing to invest time into putting the feature back into code, if the team of developers agree with it being put back in official releases on Google Play.

I think that application with such large community is able to push the feature forward better, than forcing users to choose between TextSecure PUSH and eg. Tinfoil SMS GSM solution, using non-compatible ciphers (see the tinfoil-sms issue 70 [3]).

Also using mobile networks is not reliable, as can be seen in many tickets here on github, as well as just thinking about Roaming cost and/or using textsecure on poor connectivity/without network connectivity. 

Related links:
1: https://lists.riseup.net/www/arc/whispersystems/2015-01/msg00022.html
2: https://github.com/WhisperSystems/TextSecure/issues/1762
3: https://github.com/tinfoilhat/tinfoil-sms/issues/70#issuecomment-71714483
4: https://github.com/WhisperSystems/TextSecure/issues/2137

**Comment by smarek** [comment]
Also if you could point me to official statement of TextSecure team, where it's said over which transport is end-to-end encryption possible and in which manner, together with the "plugin" that was said to contain this optional feature (encrypted sms without mobile data).

I haven't found that one so far.

**Comment by moxie0** [comment]
1) It's not gone yet, although it will be soon.

2) If you want to get involved with TextSecure development, the best way to start is with small bug fixes or issues marked "easy."  Showing up and offering to take responsibility for a large piece of the code base is meaningless if you haven't been involved up till now.

3) This is an issue tracker, not a discussion forum.  Discussion should be directed to the mailing list, support should be directed to the support center.  Thanks!
