### ISSUE TITLE
No inbound messages in Mobile Network

### ISSUE THREAD

**Issue by KommX** [WhisperSystems/TextSecure#2517]
I was asked to put this question to http://support.whispersystems.org/ but there I got no answer. So I will restate the question here:

A friend of mine has the problem that he doesn't receive TextSecure messages when he isn't on a wifi connection but on mobile network.
For me that works fine.

Does anyone have an idea how to solve this issue?

**Comment by moxie0** [comment]
Sounds like they have background data disabled for google play services.
