### ISSUE TITLE
Time stamps very slow to update

### ISSUE THREAD

**Issue by howdystranger** [WhisperSystems/TextSecure#2519]
Hi all! I'm running text secure 2.5.3 on a Moto G (XT1033 falcon_asia_ds). Running android 5.0 (LXB22,46-28). I'm using the app primarily as a texting replacement as none of my contacts use Text Secure. [Debug log](https://gist.github.com/anonymous/faa0bc4a16b4d923ca56)

I've noticed that time stamps are extremely slow in updating. If I've sent a text, then navigated out of the app, then go back into the app after a number of minutes, chances are the time stamp shows "now" or "1 min" or whatever. The time stamp only updates after maybe 10-20 seconds. I've never noticed this problem on any other texting app.

**Comment by rhodey** [comment]
test cases:

## update on scroll
1. send a message
2. leave the conversation view open for 2 minutes without scrolling
3. scroll up past the message
4. scroll back down to the message
5. timestamp is updated

## update onCreate()
1. send a message
2. leave the conversation view by going back to the conversation list view
3. wait 2 minutes
4. return to the conversation view
5. timestamp is updated

## update onResume()
1. send a message
2. turn off phone screen
3. wait 2 minutes
4. turn on phone screen / unlock
5. timestamp is not updated

@mcginty do we want to change the behavior of the `update onResume()` test case? as in refresh timestamps `onResume()`?

@howdystranger can you run through the above 3 test cases and let us know if you have the same results?

**Comment by mcginty** [comment]
@rhodey yep, makes sense that onResume() should update timestamps.

**Comment by rhodey** [comment]
conversation list view timestamp test cases:

## update on scroll
1. send a message
2. back out to the conversation list view
3. leave conversation list view open for 2 minutes
4. scroll down past the conversation view
5. scroll back up to the conversation view
6. timestamp is updated

## update onCreate()
1. send a message
2. back out to the conversation list view
3. leave conversation list view open for 2 minutes
4. back out of the app entirely
5. open the app
6. timestamp is updated

## update onResume()
1. send a message
2. back out to the conversation list view
3. turn off phone screen
4. wait 2 minutes
5. turn on phone screen / unlock
6. timestamp is not updated

@mcginty cool, sounds good for conversation view timestamps, assuming same should be done for conversation list view timestamps `onResume()`.
