### ISSUE TITLE
After importing backup: "Error decrypting message."

### ISSUE THREAD

**Issue by akuckartz** [WhisperSystems/TextSecure#252]
I upgraded from Android 2.1 to CyanogenMod 10.1.

I had a recent version of TextSecure (from June or July 2013) on the old system and exported an encrypted backup. I installed TextSecure on the new OS.

After importing the backup every text is displayed as "Error decrypting message." The meta-data is correct but importing does not overwrite the password which I set while installing TextSecure.

**Comment by rhodey** [comment]
encrypted backup is not currently supported, closing as stale.
