### ISSUE TITLE
Bad encrypted message

### ISSUE THREAD

**Issue by 2011** [WhisperSystems/TextSecure#2520]
I am having significant reliability problems with TextSecure.

I have installed the latest version along with two other users, and we all have enabled push messaging.

With one user, there are no issues at all. We both appear in each other's list of TextSecure users, and can both send each other TextSecure messages.

The second user also can send TextSecure messages to and receive TextSecure messages from the first user with no errors.

What doesn't work is sending messages between myself and the second user. We do both appear in each other's list of TextSecure users, but his only option to send a message is "Send secure SMS" (no option to send a TextSecure message). I do have the option to send a TextSecure message (and it is the default, of course), but most of those that I do just show up as "Bad encrypted message" on the other end (and all of the messages sent to this user take about twenty minutes to show up, whether the message actually makes it there, or there is just a "Bad encrypted mesage" notice).

I don't understand why this isn't working, and don't have any idea about how to troubleshoot the problem.

**Comment by jeremymasters** [comment]
Sometimes I've had that problem and usually hitting the little lock icon to end secure session fixes it. Maybe give that a shot?

**Comment by 2011** [comment]
Looks like that did help with the "Bad encrypted message" problem (at least temporarily), but there is still no option to send a TextSecure message in the other users app. There is just "Send secured SMS" and "Send unsecure SMS."

**Comment by jeremymasters** [comment]
Strange.  What if the other user does the same?  I would recommend uninstalling and re-installing to see if that helps.  If it doesn't, reproduce the probem and then submit a debug log here.  That will go a long way toward helping your problem if it persists.

**Comment by 2011** [comment]
I ended the sessions on both devices (they are both right in front of me at the moment). I reinstalled on the phone that was receiving the "Bad encrypted messages" (and didn't show the option to send a TextSecure message). I didn't show up in the list of TextSecure contacts, but after I sent a message (which took thirteen minutes for the other device to receive), I am back to where I was before - the other user receives my TextSecure messages, but is unable to send one to me.

How do I create a debug log, and what do I do with it after I have it?

**Comment by jeremymasters** [comment]
use the three dots on the top right to open the menu and choose "Settings".  Once opens, choose "Advanced".  Then choose "Submit Debug Log".  That will pop up a window. Copy the URL.  Paste that URL in a comment here.  m0xie and mcginty will pop in at some point.  Just use the @ sign followed by their names to let them know you added the debug log.

**Comment by 2011** [comment]
"Could not grab logs from your device. You can still use ADB to get debug logs instead."

Seems odd because it is displaying the log on the screen.

**Comment by 2011** [comment]
I was able to get a log from the sending machine (where it appears that everything is functioning normally, but maybe there is some problem there that is not obvious). The URL is:

https://gist.github.com/anonymous/147fb9f931e850868241

I sent four messages over two hours and NONE of them showed up on the other machine.

Hope this helps @m0xie @mcginty

**Comment by agrajaghh** [comment]
It seems you are running TS on the genymotion emulator. Are you experiencing these issues between two real devices too?

**Comment by 2011** [comment]
On the genymotion emulator, I am only having problems with the one particular user (everything is working perfectly with another user - who actually happens to be using the same carrier, although with a very different phone).

The two real phones seem to be communicating between themselves without any issues.

**Comment by moxie0** [comment]
Using an emulator for non-trivial testing can result in all sorts of problems.  Sorry, but we can only support actual devices.

**Comment by 2011** [comment]
@moxie0 Please reopen.

I moved everything to a real device (a Samsung tablet), and it works exactly the same is before - the one phone can receive TextSecure messages, but not send them to me. I believe there is some problem specific to that phone. Please tell me how to get the debug log off of that phone, and I will post it.

**Comment by moxie0** [comment]
How did you "move everything?"  Using tools like titanium backup or adb backup/restore will break your TS sessions.  Also, registration information does not transfer from device to device.

**Comment by 2011** [comment]
I did use Titanium backup, and everything appeared to transfer successfully (messages were there, I had the same key, tested and sent messages, which were recognized as coming from me).

I did turn the virtual device off, but just for curiosity (I will not try this because it doesn't "sound good"), what happens if there are two different devices with the same registration active at the same time?

**Comment by 2011** [comment]
I think I figured out (on the macro level) what is causing the problem. :) This should be fixed, but is not a high priority.

In the phone that could not sent TextSecure messages, I had two numbers in my contact entry on that phone - an old (non-smartphone) number which can only receive SMS messages, and the TextSecure number for the virtual device (and now tablet). The TextSecure app shows those as two different threads (correctly), but something is confusing it when it goes to send a message to the TextSecure number that prevents it from offering a TextSecure message as an option.

The workaround was just to delete the TextSecure number from my contact, and create a new contact with only the TextSecure number. Then it worked perfectly.

**Comment by 2011** [comment]
@m0xie @mcginty

Do you have what you need here, or should I write up another bug under the title of something like "TextSecure doesn't properly handle contacts with multiple phone numbers"?

**Comment by moxie0** [comment]
If I see the words "titanium backup" i generally stop reading.  If you can put together a reproducible test case that works on fresh installs with no TI involved, then yes please open a new issue with those steps to reproduce.  Thanks.

**Comment by sicofante** [comment]
I may understand the problem with Titanium Backup, but how can we backup our multimedia messages otherwise? TS only offers text messages backups.

(I'm chiming in here because I'm experiencing lots of issues and they might be related to it.)

Thanks for any help.
