### ISSUE TITLE
Remove gapps requirement for google-free phones

### ISSUE THREAD

**Issue by peper0ni** [WhisperSystems/TextSecure#2526]
Hello, 
i'm using a gapps free phone. 
Its a pity but at the moment i can't use TS without installing gapps.
So it would be great if someone can provide a fix/workaround to bypass gapps.

Br, pepe

**Comment by agrajaghh** [comment]
duplicate, have a look at:
#127 
#1000 
#1106

**Comment by peper0ni** [comment]
k...
