### ISSUE TITLE
TS sends SMS when key exchange is needed

### ISSUE THREAD

**Issue by nsteinbach** [WhisperSystems/TextSecure#2529]
I am using TextSecure only as a messenger, not for unencrypted SMS. After having my SIM transferred to another phone, thus creating new key pairs, it sent messages to a TS contact via SMS, instead of doing its key exchange thing in the background. Is it supposed to do that? I'd rather have it show me some way to exchange the keys again and send messages via PUSH, than to blow up my SMS contingent. (Android 5.0, Motorola Moto X 2014/XT1092)

**Comment by rhodey** [comment]
support for encrypted SMS was just recently removed by a4e18c515c61674dbe04f93fecce2b71c91f840b, please see [Saying goodbye to encrypted SMS/MMS](https://whispersystems.org/blog/goodbye-encrypted-sms/) for details. this issue will no longer exist in the next play store update you receive.
