### ISSUE TITLE
Polling support (until websockets work)

### ISSUE THREAD

**Issue by jensschulz** [WhisperSystems/TextSecure#2530]
Would it be possible to implement polling (e.g. every 15 minutes) until websocket support is available? I use this on Threema and it's almost as good as push and there is no heavy battery drainage. The load on the server shouldn't be too heavy as only few people are not using GCM. I really would like to switch to TextSecure, but as many others won't install Google Services for it.

**Comment by moxie0** [comment]
thanks but we're not going to do this. Would take more time than just doing websockets.

**Comment by jensschulz** [comment]
Alright, thanks for the quick reply! Just thought to mention it, as I couldn't find any discussion about this yet. So I will just hope for websocket support!
