### ISSUE TITLE
TextSecure doesn't properly handle contacts with multiple phone numbers

### ISSUE THREAD

**Issue by 2011** [WhisperSystems/TextSecure#2531]
Created contact with two phone numbers. First phone number does not have TextSecure capabilities (not a smartphone). Second phone number has text secure and is registered for push messages.

TextSecure (option selected to use TextSecure as the default SMS application) correctly creates two threads (one for each of the numbers) and can receive TextSecure messages from the second number. However, when attempting to send messages to the second number , only the "Send unsecure SMS" and "Send secured SMS" options are presented, so TextSecure messages can not be sent to the second number.

Moving the second number to a new contact allows TextSecure to present the option to send TextSecure messages. Moving the second number back into one contact again prevents the "Send TextSecure message" option from being displayed.

**Comment by jeremymasters** [comment]
Although not exactly the same is this similar in root cause to #2068?

**Comment by TWfromSWD** [comment]
I noticed the same problem. Some of my contacts contain a private and an office telephone number. And now that Signal 2.0 is out, both numbers are able to send TextSecure Messages. But Textsecure displays only on number in "TextSecure contacts". It is possible to send TextSecure Messages by manually selecting the second number from "all contacts" but I cannot add this number to a TextSecure Group.

**Comment by rhodey** [comment]
similar behavior as described in #2257, likely same cause.

**Comment by riyapenn** [comment]
Related https://github.com/WhisperSystems/TextSecure/issues/2068
