### ISSUE TITLE
Conversations are not associated with Contact even though Contact exists for that phonenumber

### ISSUE THREAD

**Issue by tannyl** [WhisperSystems/TextSecure#2533]
On my LG G2 smartphone, TextSecure is having problems associating my contacts to the conversations. Instead of using the contact image and name it will show the standard "happy face" and the phonenumber the conversation is related to, as if I did not have any contact stored for this number.

It should be noted that many of the conversations are correctly associated with the correct contact and thus shows both image and name from the contact.

It seems to be rather random what contacts are effected by this bug.

I have also seen conversations that was previously associated with the correct contact "forget" this ones a new message arrives, and just show the "happy face" and number instead.

I have tried updated the contacts and adding the phonenumber to them again (even adding them several times to the same contact). In some rare cases this made the contact show up correctly, but normally it does not fix anything.

I have not been able to find a common course for the problem yet. It does not matter if a contact have only one or several phonenumbers.

Also note that the standard message app on the phone works as it should, and shows all conversations with the correct contacts.

**Comment by moxie0** [comment]
Are you using cyanogen incognito mode, xprivacy, or any weird shit like that?

**Comment by tannyl** [comment]
I am not using any programs like that.

The phone is running the "standard LG android" (Android 4.4.2).

The only "special" thing I am doing is syncing my contacts to CardDAV server using CardDAV-Sync (https://play.google.com/store/apps/details?id=org.dmfs.carddav.Sync)

**Comment by bungabunga** [comment]
TextSecure works without those issues with CardDav on my device (now KitKat, previous JellyBean).

**Comment by tannyl** [comment]
Just want to add that I have had this problem for the last couple of months (started using TextSecure in the beginning of last November 2014), but only just now wanted to go "all in" with TextSecure as my main message application. Since I had not started using it as my main message app, I did not pay much attention to the problem.

**Comment by tannyl** [comment]
Updated to version 2.6.0. Still have the problem.
But right after updating and even after restarting the phone.

**Comment by Hnasar** [comment]
@tannyl I had the same problem, but it also affected viewing my contacts in the standard Messaging app. I was using DavDroid to sync my contacts. To fix it I deleted the DavDroid account sync and then cleared the app data for everything related to Dialer and Contacts/People from Settings > Apps. Once I reimported my contacts then everything worked in Messaging and TextSecure.

So I would just

**Comment by Hnasar** [comment]
....double check that.

**Comment by tannyl** [comment]
Hey @Hnasar 
Considering I don't have any problems in the standard messaging application, I don't think it will work. None the less I have tried removing the CalDav sync account, clearing all relevent data and setting everything up again.

It did not fix the problem.

Nor did the resent updates or updating my phone.

**Comment by tannyl** [comment]
A lot of updates later. :-)

I still have the problem. And the part where it randomly changes what conversations are connected correctly to a contact and what ain't (just show happy face and number) happens a lot more now. It changes back and forth without any clear course.

**Comment by tannyl** [comment]
I still have the problem and yet to find any "fix" for it.

Also we started using TextSecure on my wifes LG G2 mini. It is experiencing the same issues to some degree..

So it might be a problem with LGs version of Android.

**Comment by tannyl** [comment]
After updating my LG G2 to Android 5.0.2, it looks like the bug in TextSecure has been "fixed".

**Comment by rhodey** [comment]
thanks for the update @tannyl :) please check back in if this problem starts again and I'll reopen the issue.
