### ISSUE TITLE
Minor: New blue Logo not exactly round shaped

### ISSUE THREAD

**Issue by SecUpwN** [WhisperSystems/TextSecure#2534]
![TextSecure Icon](https://github.com/WhisperSystems/TextSecure/raw/master/res/drawable-xxxhdpi/icon.png)

Good evening TextSecure Developers and hi @mcginty!

I am not sure why you guys had to change the color of the App Icon (always loved the green Icon), but maybe you could correct the Icon to be exactly round shaped like the previous one? I know this sounds nitpicky, but I am a perfectionist and stuff like this is ticking me off after a while. Thank you for caring! :+1:

**Comment by agrajaghh** [comment]
looks pretty round to me, take a look at #2458

**Comment by JavaJens** [comment]
Actually it is not (not perfect, but I think it shows the point):
![logo-512-circle](https://cloud.githubusercontent.com/assets/1055879/6390901/f9be0124-bdb0-11e4-91ac-7ba287e0f887.png)
But seeing the other ticket, people obviously spent a lot of time thinking about it, so maybe it is intentional?

**Comment by agrajaghh** [comment]
@JavaJens your red circle isn't round ;)
But you're right, I checked it again, not totally round (but I guess its intentional)

![green](https://cloud.githubusercontent.com/assets/5296073/6391029/eb7da0f0-bdb1-11e4-9e37-13e5d3654b7b.png)

**Comment by SecUpwN** [comment]
Thanks for repsoning here so quickly, guys. Why is it intentional, @agrajaghh?

**Comment by agrajaghh** [comment]
@SecUpwN I have no idea, I didn't design it... I just thought that it would be weird if this happend accidentally

**Comment by SecUpwN** [comment]
>I just thought that it would be weird if this happend accidentally

Well, that is what happens too often in development. Who designed the new logo and can you link that person here so that he/she can extend upon this assumption, please?

**Comment by mcginty** [comment]
I designed it and am touched you thought it was intentional :). While it did start circular, I probably stretched the layer when fine tuning it to fit in the icon frame. I'll make a perfectly circular version and see how it looks.

PSA: interested designers can find the source assets at https://www.pixelapse.com/openwhispersystems/projects/signal-android/views/assets/

**Comment by SecUpwN** [comment]
Thanks for having the balls to tell us that it probably happened on accident, @mcginty. Would be cool if you correct the Icon to be perfectly round in all sizes on an upcoming TextSecure release. One more question: Why did the color had to be changed from green to blue?

**Comment by generalmanager** [comment]
@SecUpwN Probably to have one unified color scheme for Signal and TextSecure: https://whispersystems.org/blog/the-new-signal/ ;-)

**Comment by SecUpwN** [comment]
@generalmanager, does TextSecure and RedPhone detect Signal and encrypt between the two Apps?

**Comment by generalmanager** [comment]
@SecUpwN Yes, it worked with RedPhone before and now it also works with TextSecure:
>It is now possible to send end-to-end encrypted group, text, picture, and video messages between Signal on iPhone and TextSecure on Android, all without SMS and MMS fees.

**Comment by SecUpwN** [comment]
@generalmanager thanks for this very valuable information! @mcginty, would you please correct the Icons? I am getting constantly new updates of TextSecure, this egg-shaped Icon makes me nuts! :shipit:

**Comment by mcginty** [comment]
@generalmanager is exactly right about why we did the color change :)

@SecUpwN will take care of it, there are just more pressing issues than having an oval instead of a circle.

**Comment by SecUpwN** [comment]
Thanks @mcginty, I'm probably gonna throw away TextSecure soon anyway, so don't hurry. Would be more awesome if TextSecure would keep encrypted SMS, but I guess that decision is already unchangeable. *sigh*

**Comment by mawed** [comment]
@mcginty will the notification sign also change to the new icon?
With 2.7.1 it's still the old one.

**Comment by jeremymasters** [comment]
You mean the one in the top notification bar when you receive a message?  I think those typically are white-only, aren't they?

**Comment by mawed** [comment]
Yeah I meant this, but I didn't mention the color, but the shape.
There's still this horizontal line in the middle of the circle

**Comment by mcginty** [comment]
Tried a circular version and it looks worse to me. Closing this, going to re-do the icon as a vector soon anyway, and we can revisit then.
