### ISSUE TITLE
When compiling textsecure i am getting this error

### ISSUE THREAD

**Issue by zeeshan4971** [WhisperSystems/TextSecure#2536]
Error:Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	D:\Projects\android\android-sdk\build-tools\21.1.2\dx.bat -JXmx4g --dex --output D:\Projects\android\TextSecure-master\build\intermediates\dex\debug --input-list=D:\Projects\android\TextSecure-master\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
	1
Output:
	Error: Could not create the Java Virtual Machine.
	Error: A fatal exception has occurred. Program will exit.
	Invalid maximum heap size: -Xmx4g
	The specified size exceeds the maximum representable size.

it did not came on the older version of the source i searched the internet i tried the followning 
jvm -Xms256m
-Xmx1024m but did not help me if any body had this problem please help me i am using android studio i really need this solved

**Comment by agrajaghh** [comment]
you already posted the same in #2510 ...

**Comment by moxie0** [comment]
@zeeshan4971 Do this again and we'll ban you from the repo.
