### ISSUE TITLE
Translation not working

### ISSUE THREAD

**Issue by AlexAlexandru** [WhisperSystems/TextSecure#2537]
In the romanian translation in the app I still see hours however the hours string is translated https://www.transifex.com/projects/p/textsecure-official/viewstrings/#ro/master/40564774?q=hours

**Comment by maxauvy** [comment]
I have the same problem with the French translation :)

**Comment by agrajaghh** [comment]
strings have been updated here the last time 20 days ago, I guess these strings got translated afterwards... I guess they will be included in the next release.

**Comment by mcginty** [comment]
Yep, those are newer strings so the translations were probably not available at the time of release.
