### ISSUE TITLE
Ios user cannot recieve TS messages from me

### ISSUE THREAD

**Issue by dhermosillo** [WhisperSystems/TextSecure#2541]
When I send a message to a friend on Ios, he does not receive it.  When I send it to him through the default message app in android, he receives it and replies and it shows up in TS, but replies to him from TS do not reach him.

Please advise.

**Comment by moxie0** [comment]
You're saying your friend had TextSecure on Android, switched to iPhone, and now doesn't get your messages because they no longer use TextSecure?

**Comment by girvo** [comment]
I believe this is because Signal does not support encrypted SMS, only Push messaging: @pospi and I just did that dance ourselves, heh. See issue #1737 for more info.
