### ISSUE TITLE
Importing plaintext messages failed

### ISSUE THREAD

**Issue by mukolu** [WhisperSystems/TextSecure#2545]
Hello.

Importing plain text messages seem to fail.

First I exported them to sdcard. Then I re-flashed the rom and installed textsecure again.
Importing the exported does not work now.

Using CM11

Textsecure compiled from github yesterday.

Logcat error:

W/PlaintextBackupImporter( 1320): Importing plaintext...
W/ImportFragment( 1320): org.thoughtcrime.securesms.database.NoExternalStorageException
W/ImportFragment( 1320): 	at org.thoughtcrime.securesms.database.PlaintextBackupImporter.verifyExternalStorageForPlaintextImport(PlaintextBackupImporter.java:35)
W/ImportFragment( 1320): 	at org.thoughtcrime.securesms.database.PlaintextBackupImporter.importPlaintextFromSd(PlaintextBackupImporter.java:28)
W/ImportFragment( 1320): 	at org.thoughtcrime.securesms.ImportFragment$ImportPlaintextBackupTask.doInBackground(ImportFragment.java:180)
W/ImportFragment( 1320): 	at org.thoughtcrime.securesms.ImportFragment$ImportPlaintextBackupTask.doInBackground(ImportFragment.java:139)
W/ImportFragment( 1320): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/ImportFragment( 1320): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/ImportFragment( 1320): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/ImportFragment( 1320): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/ImportFragment( 1320): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/ImportFragment( 1320): 	at java.lang.Thread.run(Thread.java:841)
W/InputMethodManagerService(  534): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@42339e68 attribute=null, token = android.os.BinderProxy@42364220

**Comment by moxie0** [comment]
external storage isn't visible to textsecure.  Either you've got some weird permission thing running, or it's a bug with your rom.
