### ISSUE TITLE
Quick Reply Feature

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#2547]
Android supports to send a quick reply message if You miss or dismiss a call. However, this requires support by the messaging application. I'd be cool and an even more seamless integration if this TS could do this.

**Comment by JavaJens** [comment]
I think this is a dupe of #1823, #483 and #299 and possibly more.

**Comment by merkste** [comment]
I am sorry. I cannot explain how I could miss these issues. Please close this duplicate!
