### ISSUE TITLE
Missing notifications in Priority Mode / Lollipop

### ISSUE THREAD

**Issue by maxauvy** [WhisperSystems/TextSecure#2548]
When I enable "Priority" mode in Lollipop, the phone won't ring/vibrate, as expected. But I wanted to enable the "ring for starred contacts", for messages as well as incoming calls.

It works with the AOSP messaging app, but it doesn't work with TS. Is there a way to fix this?

Thx!

TextSecure 2.5.3 / LG G3 (d855) / CyanogenMod 12
App state: Push registered, incoming SMS enabled (default app), outgoing SMS enabled

**Comment by mcginty** [comment]
Yes, we haven't added support for the new notifications API that Lollipop introduced. Once that's done, the contact priority stuff should work as expected.

**Comment by maxauvy** [comment]
Everything is now working as expected, thanks! \o/
