### ISSUE TITLE
build failed with "Invalid maximum heap size: -Xmx4g"

### ISSUE THREAD

**Issue by Wikinaut** [WhisperSystems/TextSecure#2549]
I just upgraded my SDK and wanted to build the current TS version https://github.com/WhisperSystems/TextSecure/commit/7bf7acb1ffc9e0abfb72c77f35e151052d33e5c1 but ```./gradlew build``` failed. Full trace see http://dpaste.com/1PV7NXA

Can anyone help ?

```
Error: A fatal exception has occurred. Program will exit.
:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        /usr/local/src/adt/sdk/build-tools/21.1.2/dx -JXmx4g --dex --output /usr/local/src/TextSecure/build/intermediates/dex/debug --input-list=/usr/local/src/TextSecure/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
        1
  Output:
        Invalid maximum heap size: -Xmx4g
        The specified size exceeds the maximum representable size.
        Error: Could not create the Java Virtual Machine.
        Error: A fatal exception has occurred. Program will exit.

* Exception is:
```
full trace see http://dpaste.com/1PV7NXA

**Comment by JavaJens** [comment]
What Java are you running? Maybe you are running on a 32bit Java?

**Comment by Wikinaut** [comment]
Yes, it's a 32 bit system. Former builds in 2014 did work.

**Comment by JavaJens** [comment]
Try to set the dexoptions "javaMaxHeapSize" to sth. smaller, like the default value of 1024M.

It was added in https://github.com/WhisperSystems/TextSecure/commit/aa26785c008a8c028415c783a00227c6fd606a05

**Comment by Wikinaut** [comment]
Solved now. Thx for your swift help; could successfully build TS (on my 3GB-RAM box I changed that parameter to "1g", perhaps this should be documented there ? I don't know)
