### ISSUE TITLE
automatic scrolling in group chats

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [WhisperSystems/TextSecure#2557]
In group chats the scrolling behavior of TextSecure is unfavorable in my opinion. When I reopen a group chat after absence it is always scrolled all the way down to the most recent message. So in a group chat with a lot going on I have to manually scroll up to the point where I left the chat each time.

Could this be fixed easily? For most of my friends this is the main show stopper that keeps us from moving our group from whatsapp.

**Comment by moxie0** [comment]
Duplicate of #1211
