### ISSUE TITLE
Is TS sharing my location without permission?

### ISSUE THREAD

**Issue by bastiewendt** [WhisperSystems/TextSecure#2561]
Hi, i'm wondering why my XPrivacy shows, that TS is "listen" on my location without asking me for a permission to do that. I'm sorry for the german language pictures, but i don't have other ones to show my question. Maybe there is a german expert here, who is able to explain this. Please take a look to my screenshots, wich i've made on a HTC One X+ with CM 10.2.1, Textsecure Version 2.5.3 and Xprivacy Version 3.6.2

And please don't get me wrong, i'm not complaining, just asking for that...

![standortabfrage](https://cloud.githubusercontent.com/assets/11291344/6460390/2b8847ac-c197-11e4-8080-4bf4fc000801.jpg)
![function-listen](https://cloud.githubusercontent.com/assets/11291344/6460391/2b8a9bd8-c197-11e4-98d2-ed9c6f3a1da4.jpg)
![berechtigungen-1](https://cloud.githubusercontent.com/assets/11291344/6460388/2b8349f0-c197-11e4-825c-d444b7d0f20d.jpg)
![berechtigungen-2](https://cloud.githubusercontent.com/assets/11291344/6460389/2b87fcd4-c197-11e4-9492-9b9a7392fc6f.jpg)

**Comment by moxie0** [comment]
no idea, but we don't use location. look at the source if you don't believe us.

**Comment by untitaker** [comment]
Probably part of "Telefonstatus und Identität abrufen". Android's permission system sometimes forces devs to ask for alarming permissions for harmless functionality.

**Comment by McLoo** [comment]
XPrivacy says my last use of [listen()](https://developer.android.com/reference/android/telephony/TelephonyManager.html#listen%28android.telephony.PhoneStateListener,%20int%29) in TextSecure was 7 days ago - despite of daily usage?!

Used [here](https://github.com/WhisperSystems/TextSecure/blob/4397b55ceb8b82de1e8545e01dc7b6864fa85846/src/org/thoughtcrime/securesms/sms/TelephonyServiceState.java) and [here](https://github.com/WhisperSystems/TextSecure/blob/4397b55ceb8b82de1e8545e01dc7b6864fa85846/src/org/thoughtcrime/securesms/jobs/requirements/ServiceRequirementProvider.java) 
Question is if ACCESS_COARSE_LOCATION needs to be in the manifest...

**Comment by mcginty** [comment]
@McLoo that just means you haven't sent an SMS in 7 days, so I extend my congratulations to you on being secure :).

https://github.com/WhisperSystems/TextSecure/search?utf8=%E2%9C%93&q=ServiceRequirement&type=Code
