### ISSUE TITLE
Textsecure logo

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#2573]
Hopefully I don't come off as a tool,  but the Textsecure logo looks a lot like the album art for this limp biz kit album https://play.google.com/store/music/album?id=Blbu5jkv6igx3looppgxsqxsi4q

**Comment by untitaker** [comment]
Also similar to [OSI](http://opensource.org/), don't think it's similar enough.

**Comment by jeremymasters** [comment]
Yeah, I didn't mean to imply anything untoward, it was late and I probably shouldn't have posted, lol.
