### ISSUE TITLE
Crash when receiving message from Signal user when TextSecure is processing input

### ISSUE THREAD

**Issue by thoughtbox** [WhisperSystems/TextSecure#2576]
I will get in touch with the Signal user and try to get adb log output later, but was able to reproduce the bug three times.

Twice when in mid-edit of a reply, and once when I was entering the pass phrase (all three times while TextSecure was processing an incoming message).

/TB

**Comment by moxie0** [comment]
please post a debug log

On 03/04/2015 09:41 AM, thoughtbox wrote:
> I will get in touch with the Signal user and try to get adb log output
> later, but was able to reproduce the bug three times.
> 
> Twice when in mid-edit of a reply, and once when I was entering the pass
> phrase (all three times while TextSecure was processing an incoming
> message).
> 
> /TB
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/TextSecure/issues/2576>.
> 

-- 
http://www.thoughtcrime.org

**Comment by thoughtbox** [comment]
I can't reproduce it at home (where I have tried both WiFi and 2G/Edge). Will try again tomorrow at work where I have LTE coverage, which was what I had when this happened earlier. :-/

**Comment by thoughtbox** [comment]
I did send the crash log to Play w/ my email address in the comment field, but that's probably impossible to find.

**Comment by thoughtbox** [comment]
Unable to reproduce. Closing.
