### ISSUE TITLE
Message never delivered

### ISSUE THREAD

**Issue by digitalfreak101** [WhisperSystems/TextSecure#2580]
Since some days I have an issue sending messages to one of my contacts. The Message is marked as send on my device but the receiver never gets this messages. Other way seems just normal. I am receiving all his messages.
https://gist.github.com/anonymous/408d78c2ba6fb21e3192

**Comment by generalmanager** [comment]
Hi @digitalfreak101,

thanks for filing a bug report with a log, but there are already several posts about this and similar topics:
#679, #970, #1971, #2098, #2238

Please choose either the oldest or the one best fitting your problem and close this one to help us solve the problem. Thanks!
