### ISSUE TITLE
[Feature] Make phone numbers in text body clickable

### ISSUE THREAD

**Issue by brwolfgang** [WhisperSystems/TextSecure#2582]
My carrier often sends SMS saying that somebody tried to call me but failed. The SMS always has the phone number that tried to call me, it would be great if I could just tap the number to launch the Dialer already filled with the number ready for me just to tap Call.

It also would be nice if TS would identify the number in text body using my local contacts list and instead of showing the unrecognizable sequence of numbers it showed a (clickable) contact name.

A SMS example: Você recebeu ligações de: <04/03> 04111123451234 <1> 16:59hs
A processed SMS example: Você recebeu ligações de: <04/03>: Dad <1> 16:59hs

**Comment by patcon** [comment]
Hey @brwolfgang! Great suggestion. I'm going to create another issue for the second part, so this can be only about clickable phone numbers :)

**Comment by brwolfgang** [comment]
Ok =)

**Comment by rhodey** [comment]
@brwolfgang phone numbers in message text bodies should be clickable, they are for me. The XML `TextView` element for the message text body uses the attributes `android:autoLink="all"` and `android:linksClickable="true"` which should make all phone numbers launch the dialer on click. I think it is possible that the ROM on your device is not recognizing these phone numbers to be phone numbers and that this is an issue outside of TextSecure-- in fact there are a couple issue open now with the exact opposite problem, that the phone numbers are *too* clickable.
