### ISSUE TITLE
don't inflate Emoji pane with the rest of the layout

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/TextSecure#2585]
Migrate the Emoji pane inflation to a `ViewStub` so it's only inflated when set to visible. Will knock off ~100ms when creating a conversation view.

**Comment by johanw666** [comment]
Will this finally also get emojis at Android 4.4 with a custom keyboard? Or will this be just unsupported?

**Comment by mcginty** [comment]
there's another change out for that, this is unrelated
