### ISSUE TITLE
MMS Problem

### ISSUE THREAD

**Issue by zedrad1** [WhisperSystems/TextSecure#2587]
I am having trouble getting an MMS message on stock galaxy s6 with att. I tap download and nothing happens. I have tried with/ without wifi. sending from PC using gmail. and from and Iphone6. also having trouble sending mms bebug https://gist.github.com/f452544066ab1fd94bdc

**Comment by riyapenn** [comment]
Is this still an issue? 
Your debug log shows v2.5.3 and current v2.28.1.  Will re-open with an updated debug log, but consider merging with other MMS issues (https://github.com/WhisperSystems/TextSecure/issues/4096, https://github.com/WhisperSystems/TextSecure/issues/4080, or https://github.com/WhisperSystems/TextSecure/issues?page=2&q=is%3Aissue+is%3Aopen+MMS)

**Comment by zedrad1** [comment]
I just got a mms the other day and was unable to get it
