### ISSUE TITLE
Back Button doesn't bring you back from conversation to conversation list

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#2599]
For instance, two messages from one conversation partner arrive in a row and the the phone was in standby in between. Pushing the he back button brings you back to the same conversation instead of the list:
1. message arrives
2. open message from notification
3. standby
4. message arrives
5. open message from notification
6. back button jumps back to same conversation
7. back button goes to overview
Is this by design or a bug?

**Comment by rhodey** [comment]
If `RoutingActivity` is ever dropped by #2331 this issue should be resolved.

**Comment by rhodey** [comment]
closing as resolved by the no-more-RoutingActivity change.
