### ISSUE TITLE
"Bad encrypted message" when sending encrypted SMS message to oneself

### ISSUE THREAD

**Issue by untitaker** [WhisperSystems/TextSecure#2600]
*I built TextSecure from git, don't have Google Play installed. I only use SMS messages in the next steps*

1.  Add own number to contacts
2.  Open a conversation with own number
3.  Hit the lock-thingy
4.  Confirm key exchange initiated from "other side"
5.  Any message sent to own number comes back as "Bad encrypted message"

**Comment by moxie0** [comment]
self-send isn't supported

**Comment by untitaker** [comment]
I see, I thought this would be report-worthy in either case, since it's either a bug or at least a usability issue. E.g. WhatsApp doesn't allow the user to open conversations with themselves.

**Comment by moxie0** [comment]
agreed, it's already resolved for the textsecure transport.  we're resolving this case by removing encrypted sms/mms
