### ISSUE TITLE
Need ability to manually unregister from OWS to switch to CM-Whisperpush

### ISSUE THREAD

**Issue by cathalgarvey** [WhisperSystems/TextSecure#2603]
I'm in a similar boat to #1909 - I registered for OWS using a self-built RedPhone APK (because installing Google Apps to use a *privacy* system? What?), and now I find that I cannot (months later) subscribe to WhisperPush on CM11/12.

I have been happily using a self-compiled TextSecure and did not miss the data channel because screw installing Spyware in order to use Privacy apps, but now that Signal opens up a realm of iPhone recipients I'm making an effort to get a data channel that's even halfway trustworthy: WhisperPush.

When I try to subscribe by phone number, I get "push server not reachable". My dad installed Signal and sees my wife and I as valid recipients, indicating that we're registered, which must be due to the prior Redphone experimentation.

Reading around it seems that you can only be de-registered by uninstalling the app through Google Play, which is something I wish were made clear in the Github Readme for Redphone. Is installing Google Play only to install Redphone and then Uninstall Redphone and then be left with a google backdoor the only way I have available to register for WhisperPush?

**Comment by agrajaghh** [comment]
you can unregister here: https://whispersystems.org/textsecure/unregister/
