### ISSUE TITLE
Plead to reject the plans for dropping MMS/SMS support.

### ISSUE THREAD

**Issue by 0xACE** [WhisperSystems/TextSecure#2607]
I'm writing this in hope of you deciding to keep the MMS/SMS support.

My personal experience of using the push messages has been poor. Too many times has my messages never arrived to the person I'm trying to contact. This problem has been catastrophic when the arrival of the message was critical. Even worse when it's a urgent message that needs quick response, this has occurred to me on several occasions; which in turn caused me some troubles (Multiple times)! Personally I can not describe me experience with regular SMS anywhere near as poor as the push messages.

With regard to the poor experience with the push messages service and the severe limitations of the current plans; I do not believe your reasons warrant reason to remove support for MMS/SMS. I would rather have MMS/SMS only and drop the push messages.

Worth mentioning: currently contacting friends who're out of the country renders TextSecure virtually useless because no one currently has the data plan enabled while roaming. Keeping it on MMS/SMS mode circumvents this problem.

Regarding polling of new members; I don't see why the app still doesn't check for new contacts while using the MMS/SMS service, this can be worked around...

Since I've had a poor experience with the push messages on several occasions; I've been using TextSecure as a MMS/SMS client which had support for OTR, I had it all working in one single app.

If MMS/SMS is dropped from TextSecure; I'll likely discontinue my use of TextSecure.

**Comment by moxie0** [comment]
As we wrote in the announcement, we'll be addressing the delivery issues when we remove encrypted SMS.
