### ISSUE TITLE
Not able to close secure conversation

### ISSUE THREAD

**Issue by Polynomdivison** [WhisperSystems/TextSecure#2611]
Steps to reproduce:
> Klick on a Conversation
> Klick on the "lock icon"
> select "close secure conversatios" in German "Sichere Unterhaltung beenden"
> Now there is a message in blue "secure conversation is closed"
> The conversation is still secure

diagnose protokoll
https://gist.github.com/5de0907a03946f202bed

**Comment by agrajaghh** [comment]
the button is misleading, afaik it's restarting the secure conversation not finally ending it ...

**Comment by Polynomdivison** [comment]
Is it in the English version called "Refresh secure conversation"?
So it's only misleading in german?

**Comment by agrajaghh** [comment]
no its called "End secure session"

**Comment by Polynomdivison** [comment]
So this issue can be corrected by just editing the strings?:
> conversation_secure_verified__menu_abort_secure_session
> ConversationActivity_are_you_sure_that_you_want_to_abort_this_secure_session_question
> ConversationActivity_abort_secure_session_confirmation
And I don't know if this String:
> SmsMessageRecord_secure_session_ended 
or  this:
> TheadRecord_secure_session_ended

**Comment by generalmanager** [comment]
@Polynomdivison The strings should not be edited directly, but on transifex. And please don't change those, we have carefully considered how to name them. The problem is that people don't understand the underlying functionality, which is why this is probably not going to be shown to users all together in future releases.

**Comment by Polynomdivison** [comment]
Ok.
I've joined the english and german transfix group and now I have to wait for confirmation.
Here is what I want to do:

String | Old | New | German old | German(new)
------------ | ------------ | ------------- | ------------- | -------------
conversation_secure_verified__menu_abort_secure_session | End secure session | Refresh secure session | Sichere Unterhaltung beenden | Sichere Unterhaltung aktualisieren
ConversationActivity_are_you_sure_that_you_want_to_abort_this_secure_session_question | Are you sure that you want to end this secure session? | Are you sure that you want to refresh this secure session? | Wollen Sie die sichere Unterhaltung wirklich beenden? | Wollen Sie die sichere Unterhaltung wirklich aktualisieren?
ConversationActivity_abort_secure_session_confirmation  |End secure session confirmation | Refresh secure session confirmation | Beenden der sicheren Unterhaltung bestätigen | Aktualisieren der sicheren Unterhaltung bestätigen
SmsMessageRecord_secure_session_ended | Secure session ended. | Secure session refreshed. | Sichere Unterhaltung beendet. | Sichere Unterhaltung aktualisiert.
TheadRecord_secure_session_ended | Secure session ended. | Secure session refreshed. | Sichere Unterhaltung beendet. | Sichere Unterhaltung aktualisiert.

**Comment by agrajaghh** [comment]
I think the problem is that for secure sms this button really ends the session, or am I wrong?

**Comment by Polynomdivison** [comment]
@agrajaghh 
You are right. I've tried it with secure sms and then there is a warning...

I need to choose "TextSecure" message to start a conversation.
When I'm able to choose "safe sms" and when I'm able to switch between all.
After ending secure session I can't write safe sms and I can't see this option.

So the changes I wanted to do are wrong.

Maybe there should be a differentiation but I don't know.

**Comment by agrajaghh** [comment]
I guess it will resolve itself once encrypted sms isn't supported anymore...

**Comment by Polynomdivison** [comment]
So the option "end secure session" won't exist anymore.

**Comment by agrajaghh** [comment]
I think so, but its not up to me ;)

**Comment by Polynomdivison** [comment]
Ok. :)
Closed.
