### ISSUE TITLE
[Feature request] Switch easily between sms and internet

### ISSUE THREAD

**Issue by Polynomdivison** [WhisperSystems/TextSecure#2613]
Hi,

when I want to send a secure message to one of my contacts with sms and not over the internet I'm supposed to go to settings and disable "Textsecure-Messages".
After that my messages are transported with sms.
But when I want to send them over the internet I'm supposed to register again by textsecure.

So I would request a feature that I can select in a conversation how the message is transported.

**Comment by agrajaghh** [comment]
see https://whispersystems.org/blog/goodbye-encrypted-sms

in the meantime you can long-press the send button and select "secure sms" or "insecure sms"

**Comment by generalmanager** [comment]
@Polynomdivison If you choose it via long pressing the send button, you don't have to do anything if you want to stick with this transport for some time, which is rather convenient if you know your friends will only be available via SMS for the next two weeks of their vacation.

**Comment by Polynomdivison** [comment]
@generalmanager long pressing the send button activaes only unencrypted messages that can be send over sms. I wanted to send encrypted sms. ^^
But in the article @agrajaghh posted it's explained that there will be no longer support for encrypted sms. So this Feature Request can be closed.

Thanks. :)

**Comment by generalmanager** [comment]
@Polynomdivison I'm on TextSecure 2.5.3 and can still choose between TextSecure-Messages, encrypted and unencrypted SMS. You can close this ticket yourself, the close button is at the bottom.

**Comment by Polynomdivison** [comment]
Suddenly I can select the option. :)
Before I was only able to choose between "textsecure" and "unsafe sms".

Sorry for this useless thread.
