### ISSUE TITLE
Crashes when using ShareVia on any browser since 2.6.0

### ISSUE THREAD

**Issue by benefaktorix** [WhisperSystems/TextSecure#2615]
Since 2.6.0 when I want to share something from browser via textsecure, textsecure crashes 100% of the times.

**Comment by moxie0** [comment]
please post a debug log

**Comment by McLoo** [comment]
https://gist.github.com/92cd6d2e45d005a53b51
Also sent via crash report

**Comment by claenn** [comment]
I've had the same experience, but seems to be fixed with v2.6.1

**Comment by McLoo** [comment]
@claenn confirmed. Gone.

**Comment by agrajaghh** [comment]
looks like https://github.com/WhisperSystems/TextSecure/commit/da75268545c164fb19f36f445020028d005b3830 fixed it

**Comment by moxie0** [comment]
Thanks, looks like a duplicate of #2608
