### ISSUE TITLE
Texting takes over as only texting app u can use

### ISSUE THREAD

**Issue by 78matt** [WhisperSystems/TextSecure#2616]
I really wanted this to be option to only send certain messages. And or to certain people.  If it is the way this app has to be. I will be uninstalling very shortly.  And mms. Will not send on this app so I have to go change everything back in my defaults and then it doesn't let my messages that it stole from regular messaging app it won't let them come back

**Comment by 78matt** [comment]
Not taxes takes

**Comment by McLoo** [comment]
Post a debug log after a failed MMS please.

- for sending Push(TextSecure) message TextSecure does not need to be your default SMS/MMS app
- for sending SMS/MMS it needs to be the default app since Android KitKat I think

(you can change this issue's title with the Edit button on the upper right)

**Comment by rhodey** [comment]
@78matt as mentioned by @McLoo, starting with Android KitKat any app wanting to send SMS or MMS must be set as the default texting app on that device (ie "take over texting"). This limitation is now built into Android and is not something we can change.

If you're running a pre-KitKat version of Android and still having this problem please let me know and I'll reopen the issue.
