### ISSUE TITLE
push registration failure over 3g

### ISSUE THREAD

**Issue by shankarkulumani** [WhisperSystems/TextSecure#2621]
Using republic wireless 3g. Message do not send via push. Unable to deregister from the push option. Receive a connect to server error

Seems push transport is only working via WiFi

Thank you for the work

https://gist.github.com/f856a8347d455e92f7dd

**Comment by moxie0** [comment]
Hey sorry we don't support republic wireless.

**Comment by shankarkulumani** [comment]
Is there a reason republic wireless isn't supported?

Also why does the carrier have any effect when using the push protocol?

**Comment by mcginty** [comment]
@shankarkulumani the error log says that GCM isn't available. Could be Republic Wireless, could be your device. Either way there's nothing we can do about that one. Republic Wireless has a history of breaking things in a way that we're helpless to try to fix.

**Comment by shankarkulumani** [comment]
Thanks for the clarification. I appreciate all the hard work.
