### ISSUE TITLE
Minor text allignment error

### ISSUE THREAD

**Issue by NorthwestBased** [WhisperSystems/TextSecure#2624]
When SMS verification fails when first setting up textsecure and the "possible problems" link is clicked, the resulting text overflows off the screen by a few pixels (see the word "GoSMS" in the attached image).

Saumsung SGH-T399
Android 4.2.2
Textsecure 2.6.1

![screenshot_2015-03-08-11-08-38](https://cloud.githubusercontent.com/assets/10520957/6546974/9d5d4412-c585-11e4-8546-affb06b8eb7a.png)

**Comment by silentmoose** [comment]
Created a pull request to fix the issue. Changed to width to 343dp. This should fix issues with phones that wrap text all the way to the end of the screen.

**Comment by rhodey** [comment]
resolved by fab22969279b785cfa7b8566652714e3a1c339a6
