### ISSUE TITLE
Feature: create beta channel 

### ISSUE THREAD

**Issue by midi** [WhisperSystems/TextSecure#2626]
Please consider adding a beta channel over Google Groups (or G+).

Phased roll-outs really make sense, I get that.
I would really like to not have to wait days until I get the new version.
Especially right now, when many critical features are being added, like the move from GCM to your own delivery channel.
Also I'm willing and capable to provide feedback and logs, I'm guessing I'm not the only one.

**Comment by Mihahn** [comment]
Now there's a g+ community for the beta version: https://plus.google.com/communities/114424213916773497091

**Comment by midi** [comment]
Great news!

Though it would probably better to do a Google Group instead, if you don't want people posting things in the group.
I think you can make a Google group read only...
