### ISSUE TITLE
Open groups from contact list

### ISSUE THREAD

**Issue by Jens14L** [WhisperSystems/TextSecure#2628]
If you delete the chat history of a group, you cannot access the group anymore. So the groups have to be listed in the contact list. (TextSecure 2.5.3)

**Comment by mcginty** [comment]
dupe of https://github.com/WhisperSystems/TextSecure/issues/2628

**Comment by JavaJens** [comment]
@mcginty you looped the reference here. 
Did you mean #1064?

**Comment by mcginty** [comment]
Yep, copy paste error. Thanks @JavaJens.
