### ISSUE TITLE
TextSecure & PushBullet

### ISSUE THREAD

**Issue by RichardBarrett** [WhisperSystems/TextSecure#2629]
Messages from TextSecure are being pushed around the web unencrypted. Here's an example: http://imgur.com/UfQKD1v

I didn't authorise this and I'm wondering if there's a potential loophole here that needs to be plugged. These pushes originate from my smartphone, (PushBullet app installed here) and then are pushed from there to my android TV Box, Firefox, Tablet and, basically, anywhere where I have PushBullet installed, unencrypted.

**Comment by zmanian** [comment]
Previously discussed in #2392
