### ISSUE TITLE
false notifications

### ISSUE THREAD

**Issue by wynkoop** [WhisperSystems/TextSecure#2630]
phone: Motorola Droid 3

For several months TS constantly tells me that I have new messages when in fact there are none.  Sometimes it even says one of my contacts sent me a blank message.
Wish I could go back to the version before this bug, but I am pretty sure I do not have it around anywhere.

**Comment by mcginty** [comment]
dupe of https://github.com/WhisperSystems/TextSecure/issues/2630

**Comment by brumsoel** [comment]
Maybe you meant #2358? Or #2221 / #2287. From this issue's description it's not clear if it's about a launcher icon badge or not.
