### ISSUE TITLE
Fails to start on stock Note3

### ISSUE THREAD

**Issue by Chaos99** [WhisperSystems/TextSecure#2631]
Samsung Note 3 with stock Android 4.4.2

App does not start; crashes/ force-closes immediately.
Tried with a reboot. No success.

According to the crash report, it's a NullPointerException in javax.crypto.spec.PBEKeySpec from PBEKeySpec.java in the init method (Line 117).

Exception msg is  "Unable to get provider org.thoughtcrie.securesms.providers.PartProvider"

**Comment by JavaJens** [comment]
Looks like the issue here: https://github.com/WhisperSystems/TextSecure/issues/2588
@Chaos99 Could you check if it is indeed a dupe?
This was fixed and I think it should be available in the next release.

**Comment by Chaos99** [comment]
Stack trace looks almost identical. Line numbers are different, probably from another build. Looking forward to the next release.
