### ISSUE TITLE
User uninstalling App breaks Group

### ISSUE THREAD

**Issue by 1337sup3rh4x0r** [WhisperSystems/TextSecure#2638]
Hi there,
one Member of our Groupchat uninstalled the TextSecure App (Signal for iOS) without leaving the Group first. He is still listed.
Now for every message the leftover members send to the Group, we get the notification that the message could not be delivered.

So I guess this should be recognized and handled by the app in some way.

**Comment by JavaJens** [comment]
This is a dupe of https://github.com/WhisperSystems/TextSecure/issues/2408
It should be better (fixed?) with the next release.
The best would be to close this issue.

**Comment by 1337sup3rh4x0r** [comment]
Ok, my bad!
