### ISSUE TITLE
Provide a sensible error rather than crashing when permission denials cause registration failure

### ISSUE THREAD

**Issue by pde** [WhisperSystems/TextSecure#2641]
Peope are going to keep hitting issue #658 for the indefinite future.  Although it's being caused by factors outside TextSecure's control, TextSecure should catch the problem and recommend possible solutions, rather than crashing.

**Comment by moxie0** [comment]
If you've misconfigured XPrivacy, TextSecure is going to crash. There are a kadgillion places where XPrivacy can fuck us up, all of which are invalid assertions.  I think that's just the price you pay for fucking with your phone.
