### ISSUE TITLE
Select contacts wrong text

### ISSUE THREAD

**Issue by AlexAlexandru** [WhisperSystems/TextSecure#2644]
I have 2 the same contact saved on sim and phone but its saying mobile to both.The first one should say sim according to the default android dialer contact phone manager.
![sc20150311-154341](https://cloud.githubusercontent.com/assets/5292321/6597586/714a0d3c-c806-11e4-8c72-881bfd506330.png)

**Comment by agrajaghh** [comment]
hm, I thought I fixed this with #1493 ...

Is this happening for all your contacts with more than one number? Which device are you using and is it rooted?

**Comment by AlexAlexandru** [comment]
So my contact has the same number and the same name but first time is saved on sim and second time saved on phone.Android 2.3.6 no root samsung galaxy mini 2
![sc20150311-180148](https://cloud.githubusercontent.com/assets/5292321/6600535/d4adab42-c818-11e4-8360-3a8956e2c07a.png) here you see the first one has that sim next to it because its saved on sim and the second one doesn't because is saved on the phone

**Comment by agrajaghh** [comment]
Ah I understand, but I'm not sure it's really that important to know if this contact is saved on Sim or not. This may clutter the view and seems more important to a contact management app than a messenger....

**Comment by AlexAlexandru** [comment]
Well  if its all the time saying mobile its not a big deal to say sim to those contacts that are saved on sim.But yeah do how you like.

**Comment by agrajaghh** [comment]
It is not saying "mobile" because the contact is saved on the mobilephone, it's saying mobile, home, fax, work etc because the number is classified as a mobile number.

**Comment by AlexAlexandru** [comment]
Ouuuuu ok I got it know thanks for clearing this one.
