### ISSUE TITLE
Delivery checkbox, date, and privacy in message windows

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#2645]
I notice awhile back that when you send a message, it immediately gets a date "Now" and then the privacy level of a lock icon.  Then when the delivery receipt comes back, the "Now text slides left and the box with the check for delivery appears between the "Now" and the lock.  I have two ideas:

Currently:
Now{lock_icon}
Now{checked_box}{lock_icon}

Idea 1:
Now{space}{lock_icon}
Now{checked_box}{lock_icon}

Idea 2:
Now{unchecked_box}{lock_icon}
Now{checked_box}{lock_icon}

If nothing else, creating this issue allows you to say "it's in the backlog" if anyone else suggests similar. :smile:

**Comment by riyapenn** [comment]
Closed as Space/Unchecked_box is replaced w/ moving ellipsis.
