### ISSUE TITLE
Newer TextSecure version not available on older Android versions

### ISSUE THREAD

**Issue by gladiac** [WhisperSystems/TextSecure#2650]
Hello,

a friend of mine has an older Smartphone with Android 4.1.2 on it. She is not able to afford a new phone so easily. The latest TextSecure version available for this Android version is only 2.5.3. This raises some questions:

a) Did newer versions of TextSecure, drop support for older APIs?
b) If older API versions are not supported, why hasn't it been announced?
c) TextSecure 2.5.3 is not able to send pictures (text messages are working). I this cause support has been dropped or should a bug been filed (incompatible server change?)

**Comment by TheStash** [comment]
@gladiac the latest version in the market for Nexus 5 devices running 5.01 is 2.5.3, not sure why 2.6+ is not available at the store yet.

**Comment by JavaJens** [comment]
I think 2.5.3 is the latest version available on Play. There were some issues in the rollout of 2.6 so it was stopped. I don't know if the phased-rollout has started again, but I'm also on 2.5.3 from Play.

Regarding c) Then this is a another issue and you should file a bug for that, works just fine for me.

**Comment by gladiac** [comment]
My device is running CyanogenMod 11.0 and I have installed TextSecure 2.6.4 from the Play store. That's why I'm confused ...

**Comment by JavaJens** [comment]
I think it's a phased rollout, not all devices got it yet. This way if something breaks horribly, the devs can pull it quickly before too many people get affected.

**Comment by gladiac** [comment]
Ok thanks. I will then open a ticket for the issue of sending images once I got the debug log and analysed it.
