### ISSUE TITLE
Can't receive MMS after last update

### ISSUE THREAD

**Issue by jamfx** [WhisperSystems/TextSecure#2652]
Hi
I can not receive MMS after the last update on my Nexus 5 with Lollipop and root. I received mms yesterday from a group. Today (after update) ts says I have to configure My APN again. So I did but nothing changed. Still got the message to update my APN settings manually. But as I said, I've already done that at Telekom Germany. 
Here you got my log

https://gist.github.com/3ebbe1a1120c4d1b41f1

**Comment by mcginty** [comment]
Well, unfortunately that debug log has no MMS information in it, but does have another interesting exception that I don't think I've seen before:

```
E/ActivityThread( 4053): Performing stop of activity that is not resumed: {org.thoughtcrime.securesms/org.thoughtcrime.securesms.ConversationListActivity}
E/ActivityThread( 4053): java.lang.RuntimeException: Performing stop of activity that is not resumed: {org.thoughtcrime.securesms/org.thoughtcrime.securesms.ConversationListActivity}
E/ActivityThread( 4053): 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3309)
E/ActivityThread( 4053): 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3390)
E/ActivityThread( 4053): 	at android.app.ActivityThread.access$1100(ActivityThread.java:144)
E/ActivityThread( 4053): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
E/ActivityThread( 4053): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/ActivityThread( 4053): 	at android.os.Looper.loop(Looper.java:135)
E/ActivityThread( 4053): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
E/ActivityThread( 4053): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread( 4053): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/ActivityThread( 4053): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
E/ActivityThread( 4053): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by mcginty** [comment]
Did your TextSecure crash?

**Comment by jamfx** [comment]
Nope, it didn't crash at that point!
I think TS does crash sometimes, but I think it is more the so called "memory leak" in Andorid 5.0.1. But this is not my main problem. I can live with that. My bigger problem is the " I can not recieve MMS after update"-Problem. It always says: "Please enter valid MMS-Configuration for APN... But I have not changed it any time before (as written above!). I hope I helped with my Bug-Log. To be honest I don't understand anything you cite above...
If I can help in any other way, let me know.
best regards.

**Comment by mcginty** [comment]
@jamfx please try sending a message, then immediately capture and submit the debug log. Maybe then we can see MMS-specific errors. Thanks!

**Comment by riyapenn** [comment]
Is this still an issue? 
I will re-open if you add an updated debug log capturing the issue, but please also consider merging with another MMS issue as applicable (#4096, #4080, or https://github.com/WhisperSystems/TextSecure/issues?page=2&q=is%3Aissue+is%3Aopen+MMS)
