### ISSUE TITLE
Encrypted messaging not working/available

### ISSUE THREAD

**Issue by anti-todo** [WhisperSystems/TextSecure#2653]
Two TextSecure users with the latest version from play store. Only delivery method available for either of us is unencrypted sms. We both have push messages on. Tried unregistering and reregistering for push messages. Only option is to invite the other person to textsecure. 

Running CM11 d2lte

**Comment by moxie0** [comment]
Hey @anti-todo, sorry you're having trouble. The best place for support is the support center: http://support.whispersystems.org

Sounds like you need to hit the refresh button in the contacts view (after you tap the + floating action button).
