### ISSUE TITLE
new message to <phone number> does not appear if incoming sms disabled

### ISSUE THREAD

**Issue by BlacklightShining** [WhisperSystems/TextSecure#2660]
Currently, the recipient must be in the sender's contacts. Though only a minor inconvenience for those of us that do not wish to sync any personal information with Google's servers, it seems like a rather arbitrary restriction.

**Comment by jeremymasters** [comment]
You can also just type in the phone number.

**Comment by BlacklightShining** [comment]
I did try typing in the phone number (with and without the country code). The list was empty for me when I started and remained empty the entire time; tapping the keyboard's `Done` button did nothing.

**Comment by jeremymasters** [comment]
Just tap the "New Message to ###-####"

**Comment by d7415** [comment]
Also, android contacts don't have to be synchronised with Google. That's the default, but there are other options.

**Comment by BlacklightShining** [comment]
@jeremymasters No such option appeared. I have TextSecure 2.6.4, by the way.
@d7415 I beg to differ: tapping the _new contact_ button prompts me to begin syncing with one of my Google accounts. But that's neither here nor there.

**Comment by d7415** [comment]
2.5.3 definitely has the option @jeremymasters described. Start typing, and the "New message to..." option appears.
Using the stock "People" app (not any manufacturer-specific version), adding a contact gives me the option of "Phone-only, unsynced". Also Google and another contact handler I've installed. The "Phone-only" option has been on all 3 of my android phones pre- and post-root.

**Comment by jeremymasters** [comment]
I am using TextSecure 2.6.4.  When I tap the "+" button, a screen pops up with contacts.  I begin typing a number that I know is _not_ one of my contacts numbers...and it says "New Message to..." with the number below.  I tap that and can send a message to the number.

**Comment by agrajaghh** [comment]
@jeremymasters just tested with current HEAD after https://github.com/WhisperSystems/TextSecure/commit/a4e18c515c61674dbe04f93fecce2b71c91f840b, this is just possible if you use TS for SMS. The "New Message" doesn't appear if you have incoming SMS disabled.

**Comment by jeremymasters** [comment]
@agrajaghh makes sense.  I use it for all messaging so that's why I didn't see this.

**Comment by BlacklightShining** [comment]
Ah, yeah. I have that disabled completely, partly because support for encrypted text messages is deprecated.

**Comment by rhodey** [comment]
Steps to reproduce on Android Lollipop 5.2 with TS 2.7.1:

1) have TextSecure set as default SMS app
2) open the conversation list view
3) click the floating new message button
4) type in `15555555555`
5) click 'New message to...', notice it works
6) set some other app as default SMS app
7) open the conversation list view
8) click the floating new message button
9) type in `15555555555`
10) notice there is no 'New message to...' option
