### ISSUE TITLE
Some untranslated/not updated UI strings

### ISSUE THREAD

**Issue by bungabunga** [WhisperSystems/TextSecure#2662]
![screenshot_2015-03-13-09-45-35](https://cloud.githubusercontent.com/assets/2994878/6635988/fa92ba56-c96b-11e4-8a42-b1bd4db718d3.png)

**Comment by bungabunga** [comment]
![screenshot_2015-03-13-09-54-35](https://cloud.githubusercontent.com/assets/2994878/6635990/04a8f4b0-c96c-11e4-9972-9b496db6bf68.png)

**Comment by agrajaghh** [comment]
The strings in the first picture should be translated in the next release I guess (if they are translated here: https://www.transifex.com/projects/p/textsecure-official). The english date looks like a bug...

**Comment by moxie0** [comment]
translations happen at transifex

**Comment by bungabunga** [comment]
@moxie0 i appologise, but i do slovenian translations and have already translated everything.

**Comment by agrajaghh** [comment]
@bungabunga the strings were changed here: https://github.com/WhisperSystems/TextSecure/commit/7ce7ec56eb019f3c01b1f1b3c48cbc08524496ab and imported from transifex here https://github.com/WhisperSystems/TextSecure/commit/b5a2d7882ac189c4a614eb2cb422ac628201dae9 . I guess you translated them afterwards. So they will be in the next release...
