### ISSUE TITLE
Attachments are flickering when sending a message

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#2663]
Attachments thumbnails (picture, video and audio) in the ConversationActivity are flickering ~4 times if you send a new textmessage (or another attachment) after #2430 

I guess you are already aware of that, but I thought I open this for completeness...

**Comment by mcginty** [comment]
dupe of #1004 - aware and will work out a solution for that soon. It bugs me too :).

**Comment by agrajaghh** [comment]
wow, I forgot this one altough I posted there... sry ;)
