### ISSUE TITLE
Can't download MMS messages

### ISSUE THREAD

**Issue by steven0451** [WhisperSystems/TextSecure#2666]
I'm on EE in the UK and I've tried tapping the Download button when someone sends me an MMS with no luck. Tried changing to manual MMS settings for EE with no luck still.

Any suggestions?

**Comment by agrajaghh** [comment]
please post a debug log

**Comment by steven0451** [comment]
https://gist.github.com/ae2a7079ce7428c54127

**Comment by mcginty** [comment]
Looks like the carrier says the message is not there (404). Perhaps another application is stealing the message before TextSecure can get it?

**Comment by mcginty** [comment]
The APN settings look correct, matching other messenger's copies... I'm going to guess this is another app's fault or carrier.
