### ISSUE TITLE
Optionally send read receipts for TextSecure messages

### ISSUE THREAD

**Issue by BlacklightShining** [WhisperSystems/TextSecure#2667]
Currently, a small box with a tick in it appears next to the timestamp when a message has been delivered. An additional indication when the recipient has read the message ([maybe like iMessage?](http://www.everythingicafe.com/wp-content/uploads/2013/05/return-receipts-delivered-iphone.png)) would be nice. Users should probably be able to opt into (or out of?) sending read receipts.

(See #866.)

**Comment by moxie0** [comment]
Thanks but we've decided not to do this for now.

**Comment by BlacklightShining** [comment]
Uh, okay. Any particular reason for that?

**Comment by aprescott** [comment]
I'd also be interested in the reasons for not doing this.
