### ISSUE TITLE
Sony Xperia Z C6603 Keyboard Not opening

### ISSUE THREAD

**Issue by TimBo93** [WhisperSystems/TextSecure#2670]
a friend of my told me that he wanted to reply a message. And the keyboard didn't opend itself. The app hangs on and the report send notification Box opend. But it is Not deterministic. sorry for the poor descriptoon. But maybe it can help you.

**Comment by mcginty** [comment]
Hey @TimBo93, there's little we can do without a debug log. It sounds like a bug in the Sony ROM, but I can't reproduce it on my Z3C.

**Comment by TimBo93** [comment]
He did send a log in german language he said. Hopefully you can see that. If not i asked him already to do that the Next time too. (: He told me that bug appears in other applications too. So you could be right.

**Comment by mcginty** [comment]
Cool, will close. Thanks.
