### ISSUE TITLE
Fix post-encrypted SMS settings strings

### ISSUE THREAD

**Issue by jtracey** [WhisperSystems/TextSecure#2672]
In 2.7.0+, now that encrypted SMS is no longer a thing, some of the strings for settings are a bit confusing. In particular, there should no longer be a distinction between "incoming" and "outgoing" SMS settings. I'm also not sure about the description of the Push message setting, given that it's the primary feature of the app. Maybe change it to "Disable TextSecure messages" or something?
Screenshots:
![incoming on](https://cloud.githubusercontent.com/assets/2998852/6649507/f521c19c-c9a8-11e4-96f3-a77affbbb2fb.png)
![incoming sms enabled](https://cloud.githubusercontent.com/assets/2998852/6649509/f93e5510-c9a8-11e4-89a8-2efabe327c14.png)

**Comment by moxie0** [comment]
yeah we should touch these up

**Comment by moxie0** [comment]
@agrajaghh can i assign this to you? =)

**Comment by agrajaghh** [comment]
@moxie0 sure, will have a look
