### ISSUE TITLE
unencrypted group mms not delivered to signal contact

### ISSUE THREAD

**Issue by benmayne** [WhisperSystems/TextSecure#2674]
I tried to send a group message (mms, unencrypted) to a group of 2 other people. One that uses signal and one other normal ios. The message was only delivered to the person without signal when I would expect it to deliver a mms to the signal user as well. I could previously send mms to this group before one of them connected with me on signal. 

Let me know if you need more info about my device that's not in the log. 

Galaxy s4, att, android 4.4.4

https://gist.github.com/anonymous/a9fa0b741d5057104b01

**Comment by mcginty** [comment]
@benmayne v2.7.0 will have some MMS fixes that affected AT&T (it's in beta right now, so hold tight). Please update us when that update is rolled out. On that note, you have an old version of TextSecure that should be updated according to the logs.

**Comment by benmayne** [comment]
Updating fixed it. I'll close this when I'm back on a computer

**Comment by mcginty** [comment]
got it :) thanks for reporting back
