### ISSUE TITLE
Image bubble size differs in detail, outgoing/incoming messages

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#2676]
Seems as if the max width is different - didn't code check... 
Conversation 
![screenshot_2015-03-14-03-31-05 01 01](https://cloud.githubusercontent.com/assets/5326916/6649962/bd4c7058-c9fa-11e4-98da-d21d28644f76.png)

Detail 

![screenshot_2015-03-14-03-29-52 01](https://cloud.githubusercontent.com/assets/5326916/6649969/0c69ec06-c9fb-11e4-9e61-d093edef8815.png)

**Comment by mcginty** [comment]
Thanks @McLoo! Checking it out.

**Comment by manhole11** [comment]
When I receive pictures they are displayed like a narrow, vertical strip. You can't see the content really.

**Comment by manhole11** [comment]
The problem may be related to the orientation of the pictures. All the pictures I received were vertical so far
