### ISSUE TITLE
new image bubble not for all images 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#2678]
MMS is pre beta 
TS message post beta 

![screenshot_2015-03-14-03-55-23 01](https://cloud.githubusercontent.com/assets/5326916/6650081/81120c4c-c9ff-11e4-95d7-7c9dc3db671c.png)

Too small it is,  young padavan? 
![textsecure-2014-04-21-085837](https://cloud.githubusercontent.com/assets/5326916/6650083/92025192-c9ff-11e4-8b21-2480e8269a99.jpeg)

**Comment by mcginty** [comment]
If the image is significantly smaller than the message size, it's not scaled up. This is for when people send custom "emoji" images that are tiny and would look bad scaled up a lot. Currently this behavior is intended.

**Comment by mcginty** [comment]
Might tweak it a bit and scale it for images that are a bit smaller, though.
