### ISSUE TITLE
Feature request: Lock TextSecure upon connection to usb

### ISSUE THREAD

**Issue by darkwisperer** [WhisperSystems/TextSecure#268]
Just like the title says. When there is a USB plugged  into the phone (on connection event), erase the Text Secure credentials from memory and require the user to enter their password.

This is to make it harder for some one to gain access to the encrypted text message database since upon connection (via USB at least) the saved credentials are destroyed in memory and can not be gleaned from a memory dump.

**Comment by patcon** [comment]
Settings > Developer options > USB debugging notify [ ] / Revoke USB debugging authorizations

Given that the above is a good solution in stock android, could this be closed?

If you really need something, you could probably do some clever by building a simple root app that kills the KeyCachingService, which locked TS on my phone:

    adb shell su root am stopservice org.thoughtcrime.securesms/.service.KeyCachingService

**Comment by mcginty** [comment]
This seems more fit for an event-based task manager that "power users" can configure as they see fit.

**Comment by patcon** [comment]
Good call.

For later readers, Tasker has "USB plugged" condition + "Kill app" action will shut down the service. Further info available elsewhere :)
