### ISSUE TITLE
Change wording when sending SMS(2.7.0)

### ISSUE THREAD

**Issue by Geblaat** [WhisperSystems/TextSecure#2680]
In version 2.7.0, secure SMS functionality has been removed. When composing a new message, TS still displays Send unsecured SMS. Since there is no longer a secured SMS, this might confuse new users. Perhaps it would be best to change it to Send SMS, or change it somehow to reflect that TextSecure messages are secure and SMS is not.

**Comment by moxie0** [comment]
Thanks, but I think it's worth including the word "unsecured" to reiterate that they're not looking at an encrypted conversation.
