### ISSUE TITLE
Faulty new-message-notofication when textsecure locks

### ISSUE THREAD

**Issue by vanitasvitae** [WhisperSystems/TextSecure#2681]
Hi!
Everytime, I lock TextSecure (so that I have to enter my password) i get a notification about a new message in one specific chat. But when I unlock and see that chat, there is none. But when TextSecure locks again (also by timeout) I get a new notification. 

I think this bug appears since the last update.

**Comment by McLoo** [comment]
Pretty sure it's #2287 
Should be fixed in version 2.8 (current roadmap)
