### ISSUE TITLE
Dates are displayed in system locale regardless of language setting

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#2684]
Currently all the dates and times are diplayed regarding the android system locale using `DateUtils.formatDateTime`. 

Sometimes its even mixed because the plurals `hours_ago` and `minutes_ago` are translated.

My system language is set to german but I'm using TextSecure in english:
![date](https://cloud.githubusercontent.com/assets/5296073/6651669/b28cf9aa-ca4d-11e4-80f6-5054b174ba25.png)

It would be more consistent if the dates are formatted regarding the textsecure language setting I guess.

**Comment by McLoo** [comment]
for the record:
In 2.9.0 times (minutes, hours ) change between TS and system locale. Dates still show in system locale. 
Didn't figure out the when they switch. Will recheck, ones this is merged.

**Comment by agrajaghh** [comment]
@McLoo "% minutes", "% hours" are in strings.xml so they're translated and should show in the TS language. You observed them sometimes in your system locale instead of the TS language? Perhaps thats related to what I described here: https://github.com/WhisperSystems/TextSecure/issues/2145#issuecomment-79517926
