### ISSUE TITLE
Message Details v2.7.0b1

### ISSUE THREAD

**Issue by claenn** [WhisperSystems/TextSecure#2686]
There's no scrolling in Message Details. A long SMS does fill the screen, isn't fully displayed, and the details aren't shown.

Regards
C
![screenshot_2015-03-14-14-17-01](https://cloud.githubusercontent.com/assets/8040019/6651831/b18b93b4-ca56-11e4-896f-5ad45f996afc.jpg)

**Comment by claenn** [comment]
Sorry, to be more precise,
it differs with the dpi settings of your device. Mine is a Nex5, changed to 370dpi. For me the message has to be longer than 39 lines.

The Message Details window shows the upper »message« itself in total, which leads to the prob that the bottom »details« could be pushed out of sight.

**Comment by mcginty** [comment]
Thanks for the report @claenn!

**Comment by rhodey** [comment]
confirmed on 2.8.0, @mcginty didn't you mention you had this in some unrelated pull earlier this week? if not I can open something.

**Comment by rhodey** [comment]
resolved by dbc28746c0d816e74b2efb074374b1b9f689f589
