### ISSUE TITLE
Can't receive encrypted push messages or notifications after updating Android

### ISSUE THREAD

**Issue by novoid** [WhisperSystems/TextSecure#2687]
Hi!

I re-flashed my Nexus 5 from rooted stock ROM KitKat 4.4 to CyanogenMod 12 (cm-12-20150308-NIGHTLY-hammerhead, based on Android 5.0.2). Before flashing, I made a TitaniumBackup Pro backup also from TextSecure in order to migrate my private key as well as the settings I would have lost otherwise.

Basically, TextSecure v2.5.3 is working after restoring via TitaniumBackup Pro on CM12. 

What works:
* sending encrypted PUSH messages
* sending encrypted text messages
* sending unencrypted text messages
* receiving encrypted text messages
* receiving unencrypted text messages

However, some things are not working any more, most annoying: I can not receive any encrypted push messages:
What stopped working:
* receiving encrypted PUSH messages
* notifications that my PUSH messages arrived at my peers TextSecure

I don't think that my issues are related to CM12 nightly since text messages (encrypted or unencrypted) are working fine. I don't use any Android firewall or Android permission overruling settings/app (yet).

**Comment by agrajaghh** [comment]
from what I read there are some troubles with TitaniumBackup and TS...

Did you try to unregister and register again?

**Comment by novoid** [comment]
Does this lead to a new private key (and thus warnings/notifications for all my TS peers)?

**Comment by agrajaghh** [comment]
nope

**Comment by clsec** [comment]
This looks the same as #2609 which was closed.

While I didn't do all that @novoid did, I am having the same problem. TS looks to be sending encrypted push but the recipient isn't receiving and I get no check box. I also can not receive encrypted push. I have re-registered with the server and it hasn't changed anything.

Note II, stock ROM, Android 4.4.2 TS 2.6.4

log: https://gist.github.com/834122f2fa3d2e54ad9f

**Comment by agrajaghh** [comment]
@clsec pls open another issue, this looks different

at least the GCM notifications won't work without re-registering after a titaniumBackup restore, don't know how the new websocket connection is working in detail...

**Comment by novoid** [comment]
@clsec you've got a different behavior since my own encrypted push messages arrive at my peers.

**Comment by novoid** [comment]
OK, after I disabled TextSecure-Messages in the settings and re-registered again, no new key warning was issued to my peers and now their encrypted push messages reach me. Message-reception notification is working as well.

Thanks for the very quick help!
