### ISSUE TITLE
unreadable white text on gray background in settings

### ISSUE THREAD

**Issue by real-or-random** [WhisperSystems/TextSecure#2694]
This is for the light theme.

1. Enter the settings menu: the text is black.
2. Enter any sub-menu: the text in the submenu is white (on gray) and almost unreadable.
3. Go back to the settings menu: the text stays white.
4. Leave the settings menu, and re-enter it: the text is black again.

Everything is correct in the dark theme.

TextSecure 2.6.4 on Android 4.0.3 on a HTC Sensation Z710e.

**Comment by rhodey** [comment]
I'm unable to reproduce this on 2.16.1 from the google play store. @real-or-random are you still experiencing this issue?
