### ISSUE TITLE
Detail view timestamp format flaw

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#2695]
Seems as if a whitespace is missing before that AM/PM thing you 12 hour ppl use. 
Compared to the bubble time stamp. 

Sorry, german system locale: vorm. = AM

![screenshot_2015-03-14-03-29-52 01](https://cloud.githubusercontent.com/assets/5326916/6649969/0c69ec06-c9fb-11e4-9e61-d093edef8815.png)

**Comment by claenn** [comment]
Sorry, don't get this »vorm.«, maybe ROM dependent? 

v2.7.0-B1
![screenshot_2015-03-15-15-57-35](https://cloud.githubusercontent.com/assets/8040019/6656469/5d6f3962-cb2c-11e4-8e1d-657af4a1f467.jpg)

**Comment by agrajaghh** [comment]
@mcginty what do you think about making these format strings translatable? Using AM/PM is really uncommon and disturbing in some languages...

**Comment by claenn** [comment]
afaik, it occurs only if TS language is english and the mobile's locale is set to another, e.g. french or german.

I would prefer to hide this AM/PM thingie, if another locale than english rules ;)
If it's possible.

**Comment by agrajaghh** [comment]
@claenn oh you're right. I mixed this up...
