### ISSUE TITLE
Feature request: Bind keyboard language to contacts

### ISSUE THREAD

**Issue by tzaeschke** [WhisperSystems/TextSecure#2699]
I'm using TextSecure to write messages to contacts in different languages. The problem is that the auto completion of the built-in keyboard gets in the way when using the keyboard for wrong language (e.g. writing German on an English keyboard).
It is already very useful that I can change the language of the keyboard by holding down the space bar.

Requested feature: 
However, it would be really nice if TesxtSecure could remember for each contact which language I'm using with it and automatically switch to the correct keyboard when I start writing a message to a contact. 

That would save me from switching the keyboard manually (which I realize I need to do usually only after it garbled my first sentence to gibberish).
Is that possible?
What do others think?

**Comment by moxie0** [comment]
Don't think there's any way for us to do that.

**Comment by claenn** [comment]
@tzaeschke didn't heard of any app doing this for you. But keyboards may help, e.g. Swype (attached pic)
![screenshot_2015-03-16-21-51-48](https://cloud.githubusercontent.com/assets/8040019/6676383/a0017f50-cc27-11e4-8af2-b4e19b8e5f64.jpg)

**Comment by tzaeschke** [comment]
@claenn Thanks a lot, I tried SwiftKey and it seems to be exactly what I was looking for. I think binding languages to contacts would still be useful, but only marginally.
