### ISSUE TITLE
Emoji pane losing history

### ISSUE THREAD

**Issue by Joesen1** [WhisperSystems/TextSecure#2700]
Hi!

Since version 2.6, TextSecure loses the emoji history (last used emojis) from time to time.
Never happened before with older version.

Thanks for your great work!

**Comment by rhodey** [comment]
steps to reproduce:

1. open a conversation in TextSecure on a pre-kitkat Android device
2. open the emoji drawer
3. add some emoji that don't already exist in the recent emoji panel
4. notice that these emoji have now been added to the recent emoji panel
5. force stop TextSecure through the default Android settings app
6. reopen TextSecure, notice emoji history is gone
