### ISSUE TITLE
Message fails to reach all members of a group

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/TextSecure#2701]
I don't know how to describe this issue, which seems to arise randomly. Sometimes one of the members of the group would send a message that just doesn't reach all the other members. I don't know how else to explain this, and I haven't seen a pattern so far. Some messages just get lost.
I would suggest more testing of group chats (all members are running the latest version).
Thank you

**Comment by rhodey** [comment]
@manhole11 does this happen with MMS messages or TS push group messages?

**Comment by manhole11** [comment]
Happens with push messages.
The sender may not have saved the phone number of the person who doesn't receive the messages. Not sure if this may be part of the problem

**Comment by agrajaghh** [comment]
Is the recipient who didn't receive all the messages running version 2.6.4?

**Comment by manhole11** [comment]
We're all running the latest release, yes

**Comment by manhole11** [comment]
Update: everyone has everyone's numbers saved, but this is still happening.

**Comment by TheStash** [comment]
@manhole11 have you tried re-adding group members not receiving the message to the group? if not please do, as in some cases the user is just listed while not actually a member of the group as described (here: https://github.com/WhisperSystems/Signal-iOS/issues/718 , and here: https://github.com/WhisperSystems/Signal-iOS/issues/701).

**Comment by manhole11** [comment]
We found the bug! Apparently it has nothing to do with group chats.
From now on, SENDER will be the member who was sending messages that were not received by one of the users, whom I will call RECEIVER.
This is a screenshot taken from SENDER's phone
![media-20150323-1](https://cloud.githubusercontent.com/assets/6691301/6783555/8f072af8-d17a-11e4-856f-88c0f27a9892.jpg)
The contact displayed is RECEIVER. As you can see, its phone number starts with a +countrycode. When clicking on RECEIVER, this is what is displayed to SENDER:
![media-20150323](https://cloud.githubusercontent.com/assets/6691301/6783569/b23c994a-d17a-11e4-8759-4ae5dd7da609.jpg)
As you can see, SENDER doesn't have a blue arrow (not even with a long press), and RECEIVER's phone number is displayed without the "+". So for some reason, TextSecure puts RECEIVER in SENDER's textsecure contacts, but when it comes to sending them push messages, it doesn't allow them. This is why messages were not being delivered.
How to fix:
SENDER had to delete RECEIVER from their contacts and add them again. After updating the push directory, textsecure is now behaving correctly.
