### ISSUE TITLE
Group chat overhead

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/TextSecure#2702]
Is anyone working on the optimizations mentioned here (https://whispersystems.org/blog/private-groups/)?
I opened a similar issue a while ago but it got closed without an answer. That would probably solve a lot of current issues.
Thank you

**Comment by agrajaghh** [comment]
Which issues whould be solved by that?

**Comment by manhole11** [comment]
things like this: https://github.com/WhisperSystems/TextSecure/issues/1948

**Comment by mcginty** [comment]
This isn't a question/answer forum.
