### ISSUE TITLE
SMS don't come in

### ISSUE THREAD

**Issue by Tanyless** [WhisperSystems/TextSecure#2704]
My sms go through but don't come in and the other person is also using textsecure...

**Comment by rhodey** [comment]
@Tanyless did this start after you updated from one version of TextSecure to another or has this always happened for you? Also, does this happen with every contact you've tried to send and receive messages from or just a specific person?

also can you verify that you have incoming and outgoing SMS enabled:

Settings > SMS and MMS

**Comment by rhodey** [comment]
unable to proceed on this issue without further info and/or debug log.
