### ISSUE TITLE
Can't transfer pictures to pc

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/TextSecure#2705]
Someone sent me some photos that I'd like to transfer to my computer, but for some reason my pc can't display them. I saved them on my phone's SD card and I can see them from my phone, but no way I can get them on my computer. Annoying

**Comment by manhole11** [comment]
had to copy and paste them to a different location on my phone to make it work

**Comment by agrajaghh** [comment]
Can you give more details? 

If I receive a picture in TS, I tap on the picture click the save button (floppy disc) and click yes. The picture is then saved as /sdcard/Pictures/textsecure-2015-03-13-090346.jpeg so I can transfer it to my PC. What exactly is the problem?

**Comment by manhole11** [comment]
The problem is that after I touch the save button (floppy disc) and click yes, the picture is saved as /whatever.jpeg but when I copy it on my pc, it says that it can't open it -- and it doesn't display it.
There isn't much detail that I can give, since there is no debug log I can post. Have you actually tried transferring it to your pc? I'm on ubuntu

**Comment by agrajaghh** [comment]
Yes I did. Can you upload the picture somewhere?

**Comment by manhole11** [comment]
The problem is that I can't transfer them. After trying to open my phone as a different type of disk, I can transfer them but I can't see the content. I can't upload the pictures as they contain private information, sorry

**Comment by agrajaghh** [comment]
try sending a non private picture to your self

**Comment by mcginty** [comment]
Can't reproduce, works fine for me. This sounds like it's almost definitely a ROM issue, since we have no control over how you connect to your computer.
