### ISSUE TITLE
[MESSAGING] Ability to resend an encrypted message as an SMS message at any given time

### ISSUE THREAD

**Issue by 99922** [WhisperSystems/TextSecure#2709]
Sometimes when messaging (Using the Push service) the tick  box will not appear, it would be nice to be able to be able to hold down on the message and click 'Send as encrypted SMS' or something to that effect

**Comment by rhodey** [comment]
encrypted SMS and MMS are no longer supported but hypothetically the option to resend as a plaintext SMS could be added.

**Comment by d7415** [comment]
As a workaround it is possible to long click a message, copy and paste it into the compose box.

**Comment by moxie0** [comment]
I don't think we want to do this for plaintext SMS, thanks for the suggestion though.
