### ISSUE TITLE
[Beta] can't decrypt messages from 1 contact

### ISSUE THREAD

**Issue by mad-de** [WhisperSystems/TextSecure#2710]
Contact  says he is on .64. Can't reproduce with other contacts . Happened during active conversation.

https://gist.github.com/anonymous/981a873c49101334fc06

**Comment by moxie0** [comment]
There's nothing in this log.

Are either of you using Titanium Backup or anything like that?

**Comment by mad-de** [comment]
"Received a message encrypted using an old version of TextSecure that is no longer supported. Please ask the sender to upgrade to the most recent version and resend the message."

**Comment by moxie0** [comment]
What version are you running?

**Comment by mad-de** [comment]
1.70B

**Comment by moxie0** [comment]
Ok that makes sense.  Your contact sent you an encrypted SMS, which is no longer supported in your version.  Thanks for reporting it!
