### ISSUE TITLE
Fallback to SMS has stopped working

### ISSUE THREAD

**Issue by moeddlmann** [WhisperSystems/TextSecure#2714]
__Base data__
TextSecure version: 2.6.4
Device: Samsung Galaxy S4 Mini (GT-I9195))
Android version: 4.4.2 (vendor ROM)
Relevant settings:
* Push registered and enabled
* Incoming SMS enabled (use TS as standard app)
* Outgoing SMS to text secure contacts when there is no internet access available (fallback). Ask before sending.

__Detailed description of issue__
Since the update to TS 2.6.4 the fallback from Push to SMS (if there is no internet connection available) has stopped working. When I send the push, the message comes up as normal ("Do you want to use SMS...?"). If I confirm that I want to use SMS, the message turns to the usual green, indicating SMS mode, but after a while switches to blue (Push message). If I look into the "Message details" screen, it too says that it used the Push data channel. (As a footnote: the "Message details" screen doesn't respect the displkay/design options as well. I have TS set to the dark theme, the "Message details" screen, however, uses the bright theme. Maybe this contributes to the problem.)
It's not just a display issue either: TS _does_ use the push data channel although I tell it to do SMS. Once I turn on the internet connection, the message _is_ delivered via push to the recipient (they confirm that they received them).

**Comment by jlund** [comment]
Encrypted SMS/MMS has been deprecated in favor of the TextSecure data protocol. More information is available [here](https://whispersystems.org/blog/goodbye-encrypted-sms/).
