### ISSUE TITLE
[Beta] message timestamp stays at "now" doesn't get updated

### ISSUE THREAD

**Issue by mad-de** [WhisperSystems/TextSecure#2715]
V. 2.71

Messages from one contact (Data, Textsecure, plaintext) were received several hours ago. Still have the timestamp "Now". Stay on top of all messages.
Incidentally? Same contact as #2710 

https://gist.github.com/anonymous/bedea369d76fb5e14e21

**Comment by rhodey** [comment]
@mad-de, does this behavior only happen with this one specific contact?

**Comment by mad-de** [comment]
Yep. Only that spwcific contact. I got other contacts to write me encrypted SMS to See if that triggers something, but haven't been able to reproduce that error.
The wrong timestamp issue with this contact persists, although I noticed, that after approximately 6 hours or so, the timestamp gets updated. So messages sent at around 10 pm all get a 4 am timestamp.

**Comment by rhodey** [comment]
@mad-de is this still happening on the play store 2.10.2 beta build?

**Comment by mad-de** [comment]
Seems to have been fixed with 2.11 or 2.12. Not occuring anymore with that specific contact.
