### ISSUE TITLE
[Debug log] feel free to rename this to appropriate subject

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#2718]
Not sure exactly how this is affecting me but this log (https://gist.github.com/anonymous/a4d48273e45a664d09b9) shows something crashing.  It was a push message conversation.
D/AbsListView(15113): unregisterIRListener() is called 
W/OkHttpClientWrapper(15113): java.io.EOFException
W/OkHttpClientWrapper(15113): 	at okio.RealBufferedSource.require(RealBufferedSource.java:64)
W/OkHttpClientWrapper(15113): 	at okio.RealBufferedSource.readByte(RealBufferedSource.java:77)
W/OkHttpClientWrapper(15113): 	at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:130)
W/OkHttpClientWrapper(15113): 	at com.squareup.okhttp.internal.ws.WebSocketReader.readUntilNonControlFrame(WebSocketReader.java:119)
W/OkHttpClientWrapper(15113): 	at com.squareup.okhttp.internal.ws.WebSocketReader.readMessage(WebSocketReader.java:94)
W/OkHttpClientWrapper(15113): 	at com.squareup.okhttp.internal.ws.WebSocket$ReaderRunnable.execute(WebSocket.java:355)
W/OkHttpClientWrapper(15113): 	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
W/OkHttpClientWrapper(15113): 	at java.lang.Thread.run(Thread.java:841)
W/WebSocketConnection(15113): onClose()...
W/OkHttpClientWrapper(15113): Calling disconnect()...
W/WebSocketConnection(15113): WSC connect()...
W/OkHttpClientWrapper(15113): Connecting to: wss://textsecure-service.whispersystems.org/v1/websocket/?login=%s&password=%s
W/MessageRetrievalService(15113): java.util.concurrent.TimeoutException: Timeout exceeded
W/MessageRetrievalService(15113): 	at org.whispersystems.textsecure.internal.websocket.WebSocketConnection.readRequest(WebSocketConnection.java:77)
W/MessageRetrievalService(15113): 	at org.whispersystems.textsecure.api.TextSecureMessagePipe.read(TextSecureMessagePipe.java:72)
W/MessageRetrievalService(15113): 	at org.thoughtcrime.securesms.service.MessageRetrievalService.run(MessageRetrievalService.java:79)
W/MessageRetrievalService(15113): 	at java.lang.Thread.run(Thread.java:841)
W/MessageRetrievalService(15113): Network requirement: true, active activities: 0, push pending: false
W/MessageRetrievalService(15113): Shutting down pipe...
W/WebSocketConnection(15113): WSC disconnect()...
W/OkHttpClientWrapper(15113): Calling disconnect()...
W/MessageRetrievalService(15113): Looping...
W/MessageRetrievalService(15113): Waiting for websocket state change....
W/MessageRetrievalService(15113): Network requirement: true, active activities: 0, push pending: false
W/WebSocketConnection(15113): Sending keep alive...

**Comment by moxie0** [comment]
Show's something crashing? I don't see a crash in this log.

**Comment by mcginty** [comment]
I think they're saying the timeout exceptions look like crashes since they're stack traces.

**Comment by mcginty** [comment]
Closing since this is normal behavior if your connectivity isn't perfect, but maybe we should suppress those stack traces since they're expected?

**Comment by jeremymasters** [comment]
My connectivity is actually really good.  I was on wifi and have very dependable internet.  Sorry if this was a red herring.
