### ISSUE TITLE
TextSecure should be renamed and forked

### ISSUE THREAD

**Issue by landry314** [WhisperSystems/TextSecure#2728]
I have supported TextSecure since the beginning, version 1.0. I started using it because it was a way to encrypt SMS messages. Now, it is just another encrypted IM chat program, unable to do SMS, and its original point its lost. It should not be called TextSecure anymore... Call it "Signal for Android" or something and fork TextSecure at version 2.6...

I do not have a data plan.
I do not have google apps installed.
I can not use my favorite app anymore.

I was SO ANGRY today and also so sad because something i loved just died.

Moxie, you are making a HUGE mistake.

Some people don't want to use Gapps.
Some people don't have a data plan.
Some people travel through areas where they can't get data but the standard SMS channel is available.
Some people don't want to use limited data when they can use their unlimited SMS plan.

These people were just told to go fuck themselves. I feel offended, insulted, hurt.

These people are probably either highly security-conscious users who don't trust google or people who just don't want a data plan... they are not the enemy, Moxie, they WERE loyal users of TextSecure.

You could still develop the push system without taking away the SMS fallback system. There should at least be a fallback system.

And for security, what protects us from man-in-the-middle attacks now? If keys can be reissued whenever what stops a man-in-the-middle from distorting the keys to trigger a new swap then capturing the new keys? I don't feel comfortable with the push system even if I could use it.

THIS IS A TEXT MESSAGING APP, not a damn chat program.

I DONT CARE IF THE TELCOS HAVE METADATA ON ME. Why do you think you can force me to care about that? I care much more about not having Gapps on my phone.

It is a sad day... so sad.

**Comment by johanw666** [comment]
I agree. Data roaming is expensive in Europe, and many people here don't even have a local dataplan. They use wifi at home or work, but are not reachable by data when they're not on one of those locations. SMS - with all its flaws - should stay as an option. For now, I downgraded back to 2.6.4 in the hope that sms will keep working with it.

Now, the combination of data-only encryption and unencrypted sms/mms seems unlogical. If you don't want to support encrypted sms, drop support completely. We should fork the sms functionality in a new app. I'm not sure if only renaming would work so one can have 2.6.4 as default sms/mms app without push and 2.7 with push running together on the same phone.

**Comment by BastienLQ** [comment]
See SecuredText : https://github.com/SecuredText/SecuredText
It should be soon in F-Droid, and right after in the Play Store.
cc #2723 @SecUpwN

**Comment by moxie0** [comment]
Suddenly the world is full of people telling me "how easy it would be" for me to continue supporting encrypted SMS.  As the person who is actually me, however, I can report that it's not in fact easy or even sustainable for me to do.  But hey, an inbox full of hate mail (including death threats this time!) is just another day in the life of writing OSS software that I distribute *for free*.

If you think it's easy and sustainable, then go for it, but please start your own issue tracker rather than continuing to take up space here.
