### ISSUE TITLE
Several push messages delayed

### ISSUE THREAD

**Issue by manhole11** [WhisperSystems/TextSecure#2729]
Since version 2.7 or so, TextSecure has become very unreliable. Half the messages I should receive don't come through unless I deactivate/reactivate data. So every couple of hours I have to disconnect/reconnect my phone to receive all the messages that were queued on the server but never reached my phone (for some reason). This kind of problem seemed to have been fixed for a while, but now we're back to old times.
I'm running 2.8 and it's still happening

**Comment by JavaJens** [comment]
Could this be related to #2703?
Maybe you can open TextSecure before toggling data and see if the messages arrive.
