### ISSUE TITLE
Textsecure refuses to work in sms mode when there's no Play services

### ISSUE THREAD

**Issue by wiseoldman95** [WhisperSystems/TextSecure#2731]
Textsecure's sms fallback used to work even without Google Play services, as of 20/3/2015, this is not working. It won't let me bypass the registration screen, telling me that textSecure must have Google Play services in order work.

**Comment by moxie0** [comment]
Yes, TextSecure requires Google Play Service to function.  

Encrypted SMS is no longer supported:
https://whispersystems.org/blog/goodbye-encrypted-sms/

See #127 for our ongoing efforts to support a non-play world.
