### ISSUE TITLE
disable textsecure messages nag

### ISSUE THREAD

**Issue by allusernamesaretaken** [WhisperSystems/TextSecure#2734]
hi.

i made the mistake of updating textsecure to the latest version on google play (as of today) and now every time i open it there's a huge blue nag screen section right at the top. there is no way to close it, like in the previous version.

dear developers. for the love of god. why?

i will never ever ever enable textsecure messages, because (in no particular order, they're all important equally):
- sms is free and unlimited
- i only rarely connect to wifi
- sms is free and unlimited
- i don't want to register my phone number
- sms is free and unlimited
- the people i talk to using textsecure only connect to wifi rarely
- sms is free and unlimited

in previous versions there was the option to disable the nag screen, and even then it was temporary. when you least expected it it popped back up. why? for those who don't need or want this feature, why are you trying to push it down the throat? 

i really appreciate the time and effort you (the devs) put into this app but why are you trying so hard to turn into google, facebook and the like? i thought textsecure was about freedom of expression and freedom of choice. was i wrong?

**Comment by brumsoel** [comment]
Why do so many people automatically assume that there's no good reason behind a decision they don't immediately understand?
Please read ["Saying goodbye to encrypted SMS/MMS"](https://whispersystems.org/blog/goodbye-encrypted-sms/) and then close this, this is no bug report.
