### ISSUE TITLE
Signal for Android

### ISSUE THREAD

**Issue by mawed** [WhisperSystems/TextSecure#2741]
Hey Team,

Sorry for this, but I did not found any statements to the question on which timeframe (or milestone) Signal for android will be coming, including Textsecure and Redphone?

I found this question more than once, but no official answer, just guesses.

Any updates on this topic?

Regards
Mawed

**Comment by brumsoel** [comment]
As far as I know, there is no official ETA. If you want to know when it's ready, I suggest you follow the OWS [blog](https://whispersystems.org/blog/) or [twitter](https://twitter.com/whispersystems).
In the future, please don't post such questions as a bug report. I think the [support center](http://support.whispersystems.org/) would be a more appropriate place.

**Comment by cbarnsdale** [comment]
I don't believe there's any public release date, which is frustrating given that RedPhone is almost completely unusable on Lollipop.

**Comment by moxie0** [comment]
This is not a discussion forum.
