### ISSUE TITLE
message bubble too small during attachment download

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#2744]
On gingerbread the message bubble seems too small during the download of attachments (tested in the emulator). Can you confirm this on a real device?

![downloading_attachment](https://cloud.githubusercontent.com/assets/5296073/6766301/625336de-d001-11e4-971a-8f9e776649e9.png)

**Comment by bvorak** [comment]
Yep, can confirm on SGSII Android 4.1.2.

**Comment by agrajaghh** [comment]
can you close this one pls? I forgot it and opened #3259 which includes the wrong display of the picture too. Here the picture would have been displayed correctly after downloading...
