### ISSUE TITLE
Emoji-button really textual-smiley-button on Samsung S5, Android 5.0

### ISSUE THREAD

**Issue by madig** [WhisperSystems/TextSecure#2745]
I recently got a S5 and the keyboard has a textual-smiley-button (":-)", etc.) but the emoji button can only be reached by changing the "," button to the left of the spacebar, which is very inconvenient. See the attached screenshot. 

![screenshot_2015-03-21-19-31-46](https://cloud.githubusercontent.com/assets/380829/6766339/933f76a8-d002-11e4-91cf-e63a9e9c74d2.png)

The option to change the emoji-button to an enter-button changes the textual-smiley-button, so I guess TS wants the emoji-button, but the Samsung keyboard sets the textual-smiley-button instead. Can this be controlled through TS?

**Comment by johanw666** [comment]
There are more keyboard with this issue. Hackers Keyboard on KitKat has the same problem.

**Comment by madig** [comment]
Hum, if this can't be fixed for all keyboards, maybe add a dedicated emoji button like WhatsApp?

**Comment by wp9015362** [comment]
> madig@ wrote:
> 
> Hum, if this can't be fixed for all keyboards,
> maybe add a dedicated emoji button like WhatsApp?

https://github.com/WhisperSystems/TextSecure/pull/2302

**Comment by rhodey** [comment]
@madig I believe this should be resolved now since we're using our own emoji keyboard regardless of android device or version. please let me know if this is not the case and I will reopen.
