### ISSUE TITLE
Group member is listed twice in a group

### ISSUE THREAD

**Issue by gladiac** [WhisperSystems/TextSecure#2748]
I have a group where a group member is added twice and there is no option to see the difference between those too and how to remove it from the group.

It looks like I can add a member several times to a group. Why does TextSecure allow this?

**Comment by rhodey** [comment]
@gladiac do you have multiple contacts or multiple phone numbers in a single contact for this duplicate group member? when I try to add a member to a group in which they already exist the member list still only contains one entry for them, ie no duplicates.

**Comment by gladiac** [comment]
I have the member which is displayed by the name and I see an entry which only shows the phone number.

**Comment by gladiac** [comment]
This happens also with TextSecure 2.9.0.

**Comment by gladiac** [comment]
I guess the number is listed twice, once with +049xxxxxxx and once with +49xxxxxxxxxx. It might be that one of them reregistered so the contact is listed twice with different keys. However I can't remove the wrong number form the group ...

**Comment by rhodey** [comment]
thanks for checking back in @gladiac :) the UX around group updates (adding & removing members) still needs a lot of thinking and is particularly annoying in this case. issue #1591 documents the issue with not being able to remove members from groups, I'll link this issue.
