### ISSUE TITLE
secure sms don't work anymore 

### ISSUE THREAD

**Issue by gartenriese2** [WhisperSystems/TextSecure#2749]
I can't send secure sms to my friends that don't have push enabled. The only option is to send insecure sms. If this is not a bug but a feature, how can I exchange secure messages now with those friends?

**Comment by McLoo** [comment]
https://www.whispersystems.org/blog/goodbye-encrypted-sms/

**Comment by JavaJens** [comment]
The most recent TextSecure version has dropped support of secure SMS as incompatibility with iOS and limited resources didn't allow to further support them.
AFAIK there is a fork aiming to continue in providing encrypted SMS https://github.com/SecuredText/SecuredText but I have no clue if that works.

**Comment by gartenriese2** [comment]
That's unfortunate! 
@JavaJens: Thanks, but it seems to not support push messages.

**Comment by johanw666** [comment]
@gartenriese2 : It does not, but it aims to be able to run together with TextSecure. I have both on my phone (TextSecure 2.7.1 and an early beta of SecuredText) and this works now. Only issue is that an encrypted sms will show up in both apps on KitKat, with SecuredText showing me the contents and TextSecure warning that the protocol is no longer supported.

**Comment by gartenriese2** [comment]
@johanw666: For me the whole point was to be able to only use one app. I guess I have to start using insecure sms again.

**Comment by johanw666** [comment]
@gartenriese2 : In that case I would downgrade to 2.6.4.

**Comment by gartenriese2** [comment]
@johanw666: Or I could persuade my friends to activate push. Let's see what's more feasible. :-)
