### ISSUE TITLE
Cannot dismiss "Enable TextSecure messages" alert bar

### ISSUE THREAD

**Issue by tailordresden** [WhisperSystems/TextSecure#2750]
The dismiss button for "Enable TextSecure messages" from the previous version has gone missing, and the permanent option to opt out of push messageing from the version before that is also missing. 

Device info: Droid4, CyanogenMod 4.4.4, TextSecure 2.7.1

App State: Unencrypted, displaying list of active conversations

**Comment by agrajaghh** [comment]
I think this is intended behaviour since it doesn't really make sense to use textsecure now without registering for push messages...

**Comment by tailordresden** [comment]
I don't use data and I rarely have access to wifi.  I use TextSecure as a texting app, as it's labled in the play store.  It's fine. The source code is here, I'll just rip out the offending and compile my own. Thanks.
