### ISSUE TITLE
Zero character passphrases?

### ISSUE THREAD

**Issue by NorthwestBased** [WhisperSystems/TextSecure#2751]
Textsecure 2.7.1
Samsung SGH-T399
Android 4.2.2

When setting up a passphrase, textsecure accepts a passphrase that is zero characters long. From a usability standpoint and to avoid confusion, it seems like we should require passphrases to be at least one character long. What do people think?

**Comment by neuhaus** [comment]
Zero characters may be OK for certain scenarios, like when you're on a solo sail tour. TextSecure could display a warning if you pick a passphrase shorter than X characters.

**Comment by mcginty** [comment]
Yeah, zero character passwords shouldn't be a thing. If you're on a solo sail tour, you can just disable your password :).
