### ISSUE TITLE
Feature Request - Remove gapps deps

### ISSUE THREAD

**Issue by swordsteel** [WhisperSystems/TextSecure#2752]
Kill the gapps (google) dependancies. Folk with hardened roms like to be gapps free, and those who have hardened roms are gapps free for a very good reason. By making your app gapps free, both types of user can use your app, those who "trust" google, and those who trust themselves.

**Comment by agrajaghh** [comment]
duplicate of #1000 and #127

**Comment by swordsteel** [comment]
Thank you
