### ISSUE TITLE
Reopen #2730, unable to send/reply message to TS user

### ISSUE THREAD

**Issue by peter-sc** [WhisperSystems/TextSecure#2754]
TS user on 2.5.3, which is registered, sends me TS message.

To this message, I can't reply. Moxie closed the issue #2730 with explanation, that the first user is not registered... but he is. In his contact list he sees his TS users and is able to send them TS message (not encrypted SMS).
In my case, after receiving the message, I have the option to reply (TS - blue arrow, not SMS) but the message is not sent. Afterwards the blue arrow vanishes and I am offered to send only normal SMS.

**Message received:**

W/OkHttpClientWrapper(11538): onMessage: BINARY
W/WebSocketConnection(11538): WSC onMessage()
W/WebSocketConnection(11538): Message Type: 1
W/TextSecureEnvelope(11538): Our MAC: aa ae ad ac ab ee fa cc aa bb
W/TextSecureEnvelope(11538): Thr MAC: aa ae ad ac ab ee fa cc aa bb
W/MessageRetrievalService(11538): Retrieved envelope! +123456789123
W/MessageRetrievalService(11538): Network requirement: true, active activities: 1, push pending: false
W/MessageRetrievalService(11538): Reading message...
W/MmsSmsDatabase(11538): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 325) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 325) ORDER BY date_received DESC) LIMIT 1
W/MmsSmsDatabase(11538): Executing query: SELECT _id, body, read, type, address, address_device_id, subject, thread_id, status, date_sent, date_received, m_type, msg_box, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (read = 0) ORDER BY date_received ASC)
W/NotificationState(11538): Added thread: 325
W/NotificationState(11538): Pending array off intent length: 1
W/ShortcutBadger(11538): No support for: com.cyanogenmod.trebuchet
I/ExtendedUtils(  260): AV Sync late margin : Intended=40ms Using=0ms
D/ExtendedUtils(  260): printFileName fd(26) -> /system/media/audio/notifications/Lalande.ogg
D/ExtendedUtils(  260): extended extractor not needed, return default

W/InputMethodManagerService(  740): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@435245d0 (uid=10134 pid=11538)
I/Timeline(11538): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:62517515
I/ActivityManager(  740): START u0 {cmp=org.thoughtcrime.securesms/.ConversationActivity (has extras)} from pid 11538
W/KeyCachingService(11538): Decrementing activity count...
W/MessageRetrievalService(11538): Active Count: 0
E/BitmapFactory(11538): Unable to decode stream: java.io.FileNotFoundException: /: open failed: EISDIR (Is a directory)
W/BitmapDrawable(11538): BitmapDrawable cannot decode
W/MmsSmsDatabase(11538): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 325) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 325) ORDER BY date_received ASC)
W/MmsCommunication(11538): Getting MMSC params for apn null
W/TelephonyUtil(11538): Choosing MCC+MNC info from TelephonyManager.getSimOperator()
W/ApnDatabase(11538): Querying table for MCC+MNC 23101 without APN name
W/ApnDatabase(11538): Returning preferred APN Apn{ mmsc: "http://....", proxy: "1.2.3.4", port: 8799, user: "123", pass: "123" }
W/OutgoingMmsConnection(11538): org.thoughtcrime.securesms.mms.ApnUnavailableException: No parameters available from ApnDefaults.
W/OutgoingMmsConnection(11538):         at org.thoughtcrime.securesms.mms.MmsConnection.getApn(MmsConnection.java:73)
W/OutgoingMmsConnection(11538):         at org.thoughtcrime.securesms.mms.OutgoingMmsConnection.isConnectionPossible(OutgoingMmsConnection.java:114)
W/OutgoingMmsConnection(11538):         at org.thoughtcrime.securesms.ConversationActivity$7.doInBackground(ConversationActivity.java:667)
W/OutgoingMmsConnection(11538):         at org.thoughtcrime.securesms.ConversationActivity$7.doInBackground(ConversationActivity.java:664)
W/OutgoingMmsConnection(11538):         at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/OutgoingMmsConnection(11538):         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/OutgoingMmsConnection(11538):         at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/OutgoingMmsConnection(11538):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/OutgoingMmsConnection(11538):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/OutgoingMmsConnection(11538):         at java.lang.Thread.run(Thread.java:841)
W/KeyCachingService(11538): Incrementing activity count...
W/MessageRetrievalService(11538): Active Count: 1
I/ActivityManager(  740): Displayed org.thoughtcrime.securesms/.ConversationActivity: +206ms
W/IncomingBubbleContainer(11538): onCreateView()
I/Timeline(  740): Timeline: Activity_windows_visible id: ActivityRecord{42614f90 u0 org.thoughtcrime.securesms/.ConversationActivity t162} time:62517756
W/MmsSmsDatabase(11538): Executing query: SELECT _id, body, read, type, address, address_device_id, subject, thread_id, status, date_sent, date_received, m_type, msg_box, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (read = 0) ORDER BY date_received ASC)
W/ShortcutBadger(11538): No support for: com.cyanogenmod.trebuchet
I/Timeline(11538): Timeline: Activity_idle id: android.os.BinderProxy@4272a668 time:62517818

**Reply to message above:**

W/ConversationActivity(11538): isManual Selection: false
W/ConversationActivity(11538): forceSms: false
W/MmsSmsDatabase(11538): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 325) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 325) ORDER BY date_received DESC) LIMIT 1
W/MmsSmsDatabase(11538): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 325) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 325) ORDER BY date_received ASC)
W/MessageDatabase(11538): Updating ID: 1737 to base type: 22
W/MmsSmsDatabase(11538): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 325) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 325) ORDER BY date_received DESC) LIMIT 1
W/MessageDatabase(11538): Updating ID: 1737 to base type: 2097152
W/MmsSmsDatabase(11538): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 325) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 325) ORDER BY date_received ASC)
W/MmsSmsDatabase(11538): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 325) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 325) ORDER BY date_received DESC) LIMIT 1
W/PushTextSendJob(11538): Sending message: 1737
W/MmsSmsDatabase(11538): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 325) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 325) ORDER BY date_received ASC)
W/TextSecureMessageSender(11538): No attachments present...
W/PushServiceSocket(11538): Push service URL: https://textsecure-service.whispersystems.org
W/PushServiceSocket(11538): Opening URL: https://textsecure-service.whispersystems.org/v1/messages/+123456789123
W/PushServiceSocket(11538): PUT  --  {"destination":"+123456789123","messages":[{"body":"the message body here ==","destinationDeviceId":1,"destinationRegistrationId":99999,"type":1}],"relay":null,"timestamp":1427065994441}
W/PushTextSendJob(11538): org.whispersystems.textsecure.api.push.exceptions.UnregisteredUserException: org.whispersystems.textsecure.api.push.exceptions.NotFoundException: Not found
W/PushTextSendJob(11538):       at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:161)
W/PushTextSendJob(11538):       at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:245)
W/PushTextSendJob(11538):       at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:121)
W/PushTextSendJob(11538):       at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:111)
W/PushTextSendJob(11538):       at org.thoughtcrime.securesms.jobs.PushTextSendJob.onSend(PushTextSendJob.java:60)
W/PushTextSendJob(11538):       at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:38)
W/PushTextSendJob(11538):       at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/PushTextSendJob(11538):       at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
W/PushTextSendJob(11538):       at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/PushTextSendJob(11538): Caused by: org.whispersystems.textsecure.api.push.exceptions.NotFoundException: Not found
W/PushTextSendJob(11538):       at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeBaseRequest(PushServiceSocket.java:460)
W/PushTextSendJob(11538):       at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:423)
W/PushTextSendJob(11538):       at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:156)
W/PushTextSendJob(11538):       ... 8 more
W/PushTextSendJob(11538): org.thoughtcrime.securesms.transport.InsecureFallbackApprovalException: org.whispersystems.textsecure.api.push.exceptions.UnregisteredUserException: org.whispersystems.textsecure.api.push.exceptions.NotFoundException: Not found
W/PushTextSendJob(11538):       at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:114)
W/PushTextSendJob(11538):       at org.thoughtcrime.securesms.jobs.PushTextSendJob.onSend(PushTextSendJob.java:60)
W/PushTextSendJob(11538):       at org.thoughtcrime.securesms.jobs.SendJob.onRun(SendJob.java:38)
W/PushTextSendJob(11538):       at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/PushTextSendJob(11538):       at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:72)
W/PushTextSendJob(11538):       at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
W/PushTextSendJob(11538): Caused by: org.whispersystems.textsecure.api.push.exceptions.UnregisteredUserException: org.whispersystems.textsecure.api.push.exceptions.NotFoundException: Not found
W/PushTextSendJob(11538):       at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:161)
W/PushTextSendJob(11538):       at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:245)
W/PushTextSendJob(11538):       at org.whispersystems.textsecure.api.TextSecureMessageSender.sendMessage(TextSecureMessageSender.java:121)
W/PushTextSendJob(11538):       at org.thoughtcrime.securesms.jobs.PushTextSendJob.deliver(PushTextSendJob.java:111)
W/PushTextSendJob(11538):       ... 5 more
W/PushTextSendJob(11538): Caused by: org.whispersystems.textsecure.api.push.exceptions.NotFoundException: Not found
W/PushTextSendJob(11538):       at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeBaseRequest(PushServiceSocket.java:460)
W/PushTextSendJob(11538):       at org.whispersystems.textsecure.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:423)
W/PushTextSendJob(11538):       at org.whispersystems.textsecure.internal.push.PushServiceSocket.sendMessage(PushServiceSocket.java:156)
W/PushTextSendJob(11538):       ... 8 more
W/MessageDatabase(11538): Updating ID: 1737 to base type: 26
W/MmsSmsDatabase(11538): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 325) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 325) ORDER BY date_received DESC) LIMIT 1
W/MmsSmsDatabase(11538): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 325) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 325) ORDER BY date_received ASC)
I/ExtendedUtils(  260): AV Sync late margin : Intended=40ms Using=0ms
D/ExtendedUtils(  260): printFileName fd(26) -> /system/media/audio/notifications/Lalande.ogg
D/ExtendedUtils(  260): extended extractor not needed, return default

**Comment by moxie0** [comment]
The person you're communicating with is not registered.  Sounds like they did something with titanium backup or some other weird thing to their phone, such that the app thinks its registered but the server state differs.  If they re-register (untick 'push messages' and then retick in settings) things should work fine.

In any case, we can't support old versions of our software.  Tell your friend to update to the latest.

**Comment by peter-sc** [comment]
Thank you, after re-registering messages are delivered. No TB or any other
operation was done. I understand we should be running latest versions, but
because of #2753 update didn't succeed.
Dňa 23.3.2015 0:44 používateľ "Moxie Marlinspike" <notifications@github.com>
napísal:
