### ISSUE TITLE
Blank Message Input

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/TextSecure#2756]
~~still having issues? don't bother posting here... won't get you anywhere.~~ :see_no_evil: 

sometimes you type into the conversation edit text and no text actually appears.

**Comment by rhodey** [comment]
@nwdev, just checking in to see if this is still happening, the only issue I've seen that is remotely similar to this is #2523

**Comment by rhodey** [comment]
@liliakai just mentioned she has this sometimes.

**Comment by nwdev** [comment]
Yes, it happened to me yesterday but I am out of town and wasn't able to submit the debug log. I'll submit one as soon as it happens again.

**Comment by rhodey** [comment]
lol :see_no_evil:

**Comment by riyapenn** [comment]
Is this still an issue? Will re-open if anyone else provides steps to reproduce issue, other people add to experiencing this, or there's new information that can lead to a solution.
