### ISSUE TITLE
Textsecure doesn't send unencrypted messages

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/TextSecure#2763]
A friend of mine has had ts for a while now, and they never managed to make sms work.
I asked for the debug log right after trying sending a message, here it is: https://gist.github.com/7245f97a852090e66e92

**Comment by jeremymasters** [comment]
I'd imagine this is the salient part:
W/TelephonyUtil( 4336): Choosing MCC+MNC info from TelephonyManager.getSimOperator()
W/ApnDatabase( 4336): Querying table for MCC+MNC 22233 without APN name
W/ApnDatabase( 4336): No matching APNs found, returning null
W/OutgoingMmsConnection( 4336): org.thoughtcrime.securesms.mms.ApnUnavailableException: No parameters available from ApnDefaults.
W/OutgoingMmsConnection( 4336): 	at org.thoughtcrime.securesms.mms.MmsConnection.getApn(MmsConnection.java:73)
W/OutgoingMmsConnection( 4336): 	at org.thoughtcrime.securesms.mms.OutgoingMmsConnection.isConnectionPossible(OutgoingMmsConnection.java:114)
W/OutgoingMmsConnection( 4336): 	at org.thoughtcrime.securesms.ConversationActivity$7.doInBackground(ConversationActivity.java:667)
W/OutgoingMmsConnection( 4336): 	at org.thoughtcrime.securesms.ConversationActivity$7.doInBackground(ConversationActivity.java:664)
W/OutgoingMmsConnection( 4336): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
W/OutgoingMmsConnection( 4336): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
W/OutgoingMmsConnection( 4336): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
W/OutgoingMmsConnection( 4336): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
W/OutgoingMmsConnection( 4336): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
W/OutgoingMmsConnection( 4336): 	at java.lang.Thread.run(Thread.java:841)

**Comment by moxie0** [comment]
You'll have to be more specific than "they never managed to make SMS work."

**Comment by manhole11** [comment]
But all happens is they try to send an SMS and it fails. It's always been like that since they installed the application. Sorry :/ I hoped a debug log would help

**Comment by manhole11** [comment]
They literally just type something, hit send and it fails. No clue why that happens

**Comment by merkste** [comment]
Is the message being marked? @moxie Could this be similar to the SMS issue I reported? (with the empty debug log)

**Comment by moxie0** [comment]
You have to be more specific than "it fails."  Like, the app crashes, nothing appears, the message appears but has a red triangle tick next to it, the message gets stuck in the pending state forever, etc...?

**Comment by rhodey** [comment]
OP deleted their github account, closing because we don't have any specific info on this.

**Comment by Kern3l** [comment]
Hey! I've got the same (?) issue. When I type an SMS to a person without Signal, after pressing enter it shows the message with three moving dots indefinitely. After few days I open the "conversation" and it's still in this state.

It worked before I turned my phone in for a repair and they rooted it and wiped out everything (+ replaced PCB). Currently 3G is losing, not working at all.
