### ISSUE TITLE
Selecting failed messages is impossible

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/TextSecure#2764]
-send a message and make it fail (somehow)
-try to select the message to delete it
The only workaround I found is to select another message first, then select the failed one, deselect the first one and then delete the failed one
Thank you

**Comment by merkste** [comment]
confirmed

**Comment by rhodey** [comment]
related #2333

**Comment by McLoo** [comment]
@rhodey partly related. fails can only be added to a select batch (was fixed by moxie), but not selected for them selves
