### ISSUE TITLE
Simple UI for sending insecure SMS to normally secure contacts

### ISSUE THREAD

**Issue by TurkeyMan** [WhisperSystems/TextSecure#2765]
We need to be able to force send insecure SMS to normally secure contacts for times when we can't rely on the data network, or when we know the recipient has no data network.

**Comment by agrajaghh** [comment]
You can long-press the send button and select SMS. But i agree, this is too hidden. I think there should be a little triangle in the corner ...

**Comment by TurkeyMan** [comment]
Oh wow, I never would have noticed :)
Good idea! :+1:

**Comment by TurkeyMan** [comment]
Wow, did you add the little triangle indicator already? :)
