### ISSUE TITLE
Consider supporting XMPP?

### ISSUE THREAD

**Issue by TurkeyMan** [WhisperSystems/TextSecure#2766]
Hangouts is the default Google chat client, and most people I know communicate via gtalk rather than sms.
ChatSecure is very rough compared to TextSecure, and it's repelling to non-tech-savvy users to have 2 clients.
Consider supporting XMPP in TextSecure too, so we can use the one client for messaging, as a full and transparent replacement for Google Hangouts?

**Comment by agrajaghh** [comment]
I don't think the protocols are compatible...

**Comment by TurkeyMan** [comment]
Which protocol? OTA? It's the same over any comms channel.
Or do you mean XMPP/gtalk? Gtalk/hangouts is XMPP (with some minor google extension I think). Facebook is XMPP too.

Ideally, the experience would be the same as Google Hangouts; contact lists are aggregated, users are merged (I think this level of functionality is offered by the standard contacts service in Android right?), and the 'active' service used to send messages to a contact is selectable with a button.

Hangouts was originally a gtalk client, but then they aggregated SMS messages into the same client. I think their design language is familiar and solid. I would think it's chat/sms flip button is the perfect template for supporting additional protocols.

**Comment by agrajaghh** [comment]
I meant that xmpp is not compatible with axolotl (the protocol used by TextSecure/Signal).

**Comment by TurkeyMan** [comment]
Ah right, but that's precisely what I'm suggesting; consider supporting XMPP too, so that we can aggregate our messaging into the one polished app, the same way Hangouts did some years back.
I think that would be an excellent move for end-user experience, and ideally also help foster mainstream adoption by providing an out-of-the-box replacement for Hangouts.

**Comment by TurkeyMan** [comment]
Hangouts demonstrates an excellent UI mechanism for switching between protocols within conversations with contacts. There is a little button on the left that shows "chat" or "SMS" and you can flip between at will.

**Comment by piratenpanda** [comment]
There's a GSOC project for this: http://wiki.xmpp.org/web/Summer_of_Code_2015#axolotl_support_for_Conversations

**Comment by pejakm** [comment]
AFAIK, gtalk is now closed, ie, they don't support XMPP anymore.
