### ISSUE TITLE
PassphraseChangeActivity not using AsyncTask for MasterSecretUtil.changeMasterSecretPassphrase()

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#2768]
`PassphraseChangeActivity` is calling `MasterSecretUtil.changeMasterSecretPassphrase()` on the UI thread.

https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/PassphraseChangeActivity.java#L100

**Comment by adrianchifor** [comment]
I'll take care of it. Will do a pull request in a few days.
