### ISSUE TITLE
Please add option to change chat background color

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2773]
Hello,

the current TextSecure-Android version does have a white chat background.

I do not really like that and find it uncomfortable to read on it, especially with the current choice of message bubble colors (https://github.com/WhisperSystems/TextSecure/issues/2774).

Could you please add an option to change the chat background color?

It would be much appreciated.

Regards

**Comment by moxie0** [comment]
Sorry, we're not going to do this.
