### ISSUE TITLE
Please add option to change message bubble colors

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2774]
Hello,

the current TextSecure-Android version does have gray and blue message bubbles.

I do not really like that and find it uncomfortable to read with those colors, especially with the current choice of the chat background color (https://github.com/WhisperSystems/TextSecure/issues/2773).

Could you please add an option to change the message bubble colors?

Oh, and before you say "But we need those colors to indicate which kind of messaging channel is being used (Data/SMS) and to indicate if the messages are encrypted or not!" or something like that (https://github.com/WhisperSystems/TextSecure/issues/945), let me say this:

I don't think colors should be used for that. I think those things should rather be indicated via icons, not via message bubble colors.

And I don't use TextSecure for SMS anyway (IMHO TextSecure should have removed the entire SMS support, both, encrypted as well as unencrypted).

It would be much appreciated if you could add an option to change the message bubble colors.

Regards

**Comment by moxie0** [comment]
Sorry, we're not going to do this.
