### ISSUE TITLE
TextSecure 2.7.1 downloads MMS even when not default for SMS or MMS

### ISSUE THREAD

**Issue by jaxley** [WhisperSystems/TextSecure#2777]
Just installed TextSecure on my wife's phone but left it with SMS and MMS disabled by default until we could configure everything and transition her over.  However, just today, she got group MMS messages from friends that were unable to be downloaded in her default MMS app.  Upon investigation, opening TextSecure, I saw those messages downloaded in TextSecure even though it shouldn't have.  It appears somehow TextSecure is pulling down MMS when it shouldn't.  It wasn't all messages in the thread, which left some messages in the default MMS app and others inside TextSecure for some reason.

Samsung Galaxy S3 CDMA, Android 4.4.2.

**Comment by moxie0** [comment]
Hmm, that shouldn't be possible if TS isn't set as the system's default SMS app. Could you send your wife's phone an MMS, capture a debug log after it downloads, and then post that here?

**Comment by jaxley** [comment]
Certainly!  Glad to help.  I've been enjoying TS and want to spread the love.  I thought the same thing - this shouldn't happen :-)

I was able to reproduce the issue pretty easily with a group mms.  Perhaps there is some race condition involved with which app grabs the MMS first.  With the first incoming message, both Hangouts and TextSecure showed the message without issue but the next incoming message resulted in the previous situation where I got "Message not downloaded. Touch to retry." in Hangouts but TextSecure had grabbed it already.  I was never able to download the message outside of TextSecure.  Uninstalling TS ends up causing the message(s) to get lost entirely.

The logs clearly show that TextSecure is still downloading MMS messages.

https://gist.github.com/anonymous/672e96d3a59f830e1a60

**Comment by moxie0** [comment]
Hmm, in the log you can see that TS receives a `WAP_PUSH_DELIVER` Intent. The [documentation says](https://developer.android.com/reference/android/provider/Telephony.Sms.Intents.html#WAP_PUSH_DELIVER_ACTION):

```
This intent will only be delivered to the default sms app. 
```

You sure TS isn't configured as the default SMS app?

**Comment by jaxley** [comment]
Odd. Definitely not. Fresh install. Never enabled as the default.

So, is the documentation wrong or the API?  Seems perhaps the doc is correct http://android-developers.blogspot.com/2013/10/getting-your-sms-apps-ready-for-kitkat.html?m=1

Since TS knows it's not the default app, should that be used to ensure it ignores spurious received broadcasts?

**Comment by moxie0** [comment]
Looks like a ROM bug to me, but it's an easy workaround.

**Comment by jaxley** [comment]
Perfect. Thanks for the workaround. Android in the wild seems to be a source of endless fun and surprises.

**Comment by johanw666** [comment]
This problem does still occur with sms messages: I have TextSecure (built from source including this commit in MmsListener and SMSSecure on my phone (XPeria Z1C with Android 4.4.4). SMSSecure is the default sms handler, but an encrypted sms will be processed by both applications (with TextSecure giving an error about sms no longer supported).
