### ISSUE TITLE
Bad connection causes message to get sent multiple times

### ISSUE THREAD

**Issue by TWfromSWD** [WhisperSystems/TextSecure#2778]
I noticed the following behavior with Push Messages: When having limited or no Internet connection while someone sends you a message, the message gets delivered multiple times after the connection is restored.
I don't know about the inner workings of TextSecure but is it possible, that TextSecure tries to resend the Message after some time has passed without a receipt? If so, then maybe the received messages should be checked by using some kind of unique ID so duplicates can be deleted automatically.

**Comment by moxie0** [comment]
That's already true. If you receive a message multiple times, it has to have been sent multiple times.
