### ISSUE TITLE
[Feature Request] Add "seen" indicator with timestamp

### ISSUE THREAD

**Issue by mayerflash** [WhisperSystems/TextSecure#2779]
I'm really missing the "seen" indicator which is available at Threema (eye symbol). This inform me, when the recipient of the message really have red the message.
It makes me sure that really the recipient has received the message, not only his mobile.
This makes sending an acknowledgment back (e.g. "OK") superfluous.

Additionally a setting is probably needed to deactivate sending these "seen"-indicator for those, who don't want this behaviour and keep their privacy.

**Comment by JavaJens** [comment]
This has been discussed before and the general notion was denial.
See #2667

**Comment by mayerflash** [comment]
Ok.
What a bummer.
