### ISSUE TITLE
Cannot send private messages anymore

### ISSUE THREAD

**Issue by klenamenis** [WhisperSystems/TextSecure#2781]
Today I updated to 2.8.0 and all my private sessions were terminated. I'm using a google free phone, thus only SMS have been sent in the past. There isn't even an option anymore to exchange keys.

Also the "Enable TextSecure messages?" notification can't be removed anymore, which is quite annoying.

**Comment by jeremymasters** [comment]
TextSecure uses GCM for secure communication so I don't think it will work with a google free phone?  Unless you mean a free phone from google?

**Comment by klenamenis** [comment]
Nope, no Play Services or anything else propietary installed. It just worked fine all the time before updating to the latest version today.

GCM is used for sending push messages, encryption is done by TextSecure.

**Comment by fischerling** [comment]
https://whispersystems.org/blog/goodbye-encrypted-sms/

Is nobody reading changelogs or searching for informations before opening an issue ?

**Comment by mejo-** [comment]
Some people started the new project SMSSecure as a fork of textsecure.
This project aims to provide the encrypted SMS feature that just has
been ripped out of TextSecure. According to the developers, soon the
first release will arrive at F-Droid and on Google Play. Until then, you
can follow the development on Github: https://github.com/SMSSecure/SMSSecure
