### ISSUE TITLE
[Feature Request] SMS through Textsecure

### ISSUE THREAD

**Issue by Edenhofer** [WhisperSystems/TextSecure#2783]
Please add an option to switch between Textsecure-mode and SMS-mode, like there is one in hangouts (by Google). There may be some cases where sending an SMS is preferable although both parties have Textsecure.
Lets make an example: In case one side has no internet connection (e.g. in foreign contries) but may recieve SMSs. It would be great to be able to sent the person this message through Textsecure especially because this app aims to replace the default SMS-App.

**Comment by moxie0** [comment]
Long-press the send button to switch.  In general the best place for support questions is the support center, thanks.
