### ISSUE TITLE
New identity popup dialog wrong theme

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#2784]
Latest HEAD
Using dark theme, when tapping in the conversation on the "changend identiy" bubble, the popup dialog uses the white theme.
when tapping 'verify' from within the details view the dark themed popup appears.

EDIT thinking about it, the detail dialog should not show the verify message, when opening the already verified message. Does not appear after reentering the conversation and opening the message details.

**Comment by agrajaghh** [comment]
I'll have a look at the theming issue, if no one else started yet?

**Comment by mcginty** [comment]
Go for it, @agrajaghh!

**Comment by rhodey** [comment]
@mcginty what happened to #3126? I feel like this was resolved by something recently, right?

**Comment by agrajaghh** [comment]
@rhodey yep, should be fixed by https://github.com/WhisperSystems/TextSecure/commit/15b403ec0336981e9a218e07fe710a623c959c41

**Comment by rhodey** [comment]
@agrajaghh thanks for the link :) I'll make sure this get's closed once merged into master.

**Comment by rhodey** [comment]
closed by 72bd6d5844590f7087f36fafaf582acfa63a5f3f
