### ISSUE TITLE
SMS stopped working after upgrade to 2.8

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#2786]
Cyanogen, Android 4.4.4, log goes here: https://gist.github.com/anonymous/88be8ffe0f5fcd0911c6

**Comment by moxie0** [comment]
This log is empty.  Please capture a debug log after a SMS send fails.

**Comment by merkste** [comment]
Yes, that is strange. I missed it being empty since I just copied the url. How can this possibly happen? It was captured right after the message was being marked as failed send attempt.

**Comment by moxie0** [comment]
Chances are that both your SMS and debug log problems are problems with your ROM.

**Comment by merkste** [comment]
Weird. A second reboot of the phone  solved it. No idea why. Maybe just a temporary problem on the provider's side?
