### ISSUE TITLE
Username Support and Optional Phone Number Destruction

### ISSUE THREAD

**Issue by AnonymousBurner** [WhisperSystems/TextSecure#2788]
Hello,

I've vouched for this feature a lot, so I'll just write it here as a feature request hoping someone would take it seriously.

We're a group of activists in an oppressive regime, trying to establish an IM-type of secure medium to communicate our initiatives among each other.

TextSecure has been, theoretically, the ideal medium for us for so long. Yet, we never used it because it requires Phone Numbers. Hashed or not, our problem with that is not a "trust" problem against the server, but the problem is that if one of us is searched/caught, there's absolutely zero plausible deniability for him to deny his immediate knowledge if the people he's communicating with. The oppressor can simply collect the phone numbers I have on my phone (after a good beating to make me unlock the app from its passphrase), and take down all of the group.

**We need the ability to use usernames** (preferably also making an option to FORCE Tor before the app can download or upload ANYTHING). That way, if one is caught, he won't be (as much of) a danger to us all, as if he had all our phone numbers  in the chat screen. He will be able to use his cover story to deny and save us and maybe even himself.

Please consider that. We're struggling to get a secure medium for our communication. XMPP is not the way to go when it comes to Group Chat, and other Closed Source apps are just never the correct go-to app.

This app is absolutely perfect, if only it allows us to completely get rid of phone numbers. Not just for people whom I don't have their phone numbers, but even for my contacts that are in my phone book. We need a way to not reference phone numbers in TextSecure AT ALL.

Please make it happen. If I had what I could benefit you with, I'd gladly offer it, but unfortunately I'm not able to offer anything back to this great community of developers.

**Comment by moxie0** [comment]
Thanks @AnonymousBurner, but this isn't really a discussion forum.  This is a better topic for the mailing list, where I think you'll find a few threads on this subject already.

If you want burner numbers, you can use a GV, Twilio, or any VoIP number to register with TS.
