### ISSUE TITLE
Encryption no longer works on SMS

### ISSUE THREAD

**Issue by summetj** [WhisperSystems/TextSecure#2799]
In some travel situations I have only GSM network access, allowing voice and SMS, but NOT data plans. I need to be able to use  encryption over regular SMS transport. (Also, I would like to be able to enable or disable the use of TextSecure transport in the settings, without having the annoying pop up always appearing and trying to force me to use it.)

**Comment by agrajaghh** [comment]
encrypted SMS is not supported anymore: https://whispersystems.org/blog/goodbye-encrypted-sms/
