### ISSUE TITLE
WhisperPush user allowed to register for TS message

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#2805]
Just registered for TS messages for a number that is already a WhisperPush user.
WhisperPush messages came in just fine before. After that action only bad encrypted from the WP App as well as from TS.

Where's  the check for being already registered - that so many ex WhisperPush users complained about?

just in case: https://gist.github.com/anonymous/6507f227bda75b693793

**Comment by moxie0** [comment]
There was a sync delay, so it didn't have time for your registration to propagate into TS land.
