### ISSUE TITLE
SMS does not send

### ISSUE THREAD

**Issue by NTICompass** [WhisperSystems/TextSecure#2814]
I can't send SMS, when I do it just sits there (sometimes for hours).  No red triangle, no error... just sits there.  I thought this was because of "delivery reports", but toggling this has no effect on sending SMS.

This doesn't *always* happen.  Sometimes SMS works just fine, but for the most part, it just sits there.

I don't know if this is a TextSecure issue or an issue with my phone (or provider) in general.

Not sure if this log has anything useful in it: https://gist.github.com/22a283d889ab9c8d15b0

P.S. I was having MMS issues before, so I don't know if that's related.

**Comment by moxie0** [comment]
There's nothing in this debug log.  If SMS is in pending state, that means your device is reporting that it has no service.  If you have some kind of "wifi calling" device, you need to enable "wifi calling" in TS settings.

Otherwise please reopen with a log that covers the period where you send a message.

**Comment by NTICompass** [comment]
I had a feeling that log wasn't good enough, but I don't know how else to get a better one.  How can I get a log with some real info in it?

TextSecure just shows "..." as the sent time, and the message just sits there doing nothing.

I don't have any "wifi calling" or anything, just a normal Virgin Mobile phone.  I can receive SMS, so I must have some sort of service.

**Comment by NTICompass** [comment]
I enabled "WiFi Calling" and I haven't had an issue sending SMS since.
