### ISSUE TITLE
The new TextSecure is undermining my Privacy

### ISSUE THREAD

**Issue by fgrt** [WhisperSystems/TextSecure#2818]
In the past i have been able to use TextSecure to encrypt my SMS without having be online at all times.

Recently i lost the ability to communicate by encrypted SMS with a lot of people close to me because they got their TextSecure updated.

So i had to install some of the most intrusive of the Google Apps to be able to update Textsecure - only to find out that it doesn't do encrypted SMS any longer.

I just can not understand how Open Whisper Systems can deliver us to Google Cloud Messaging (GCM) and its constant tracking when this opens us to abuse by all the three letter agencies that we now know about thanks to Snowden.

Please reenable key exchange and encrypted messaging using SMS.

**Comment by agrajaghh** [comment]
see https://whispersystems.org/blog/goodbye-encrypted-sms or look at one of the 100 identical issues here at github

**Comment by fgrt** [comment]
Sorry, but i can not understand why you would want to throw under the bus that part of the user base that is not continuously online or that doesn't want to be tracked by Google Cloud Messaging at all times.

**Comment by johanw666** [comment]
You have 2 possible solutions:

1. Downgrade to TextSecure 2.6.4 (and hope it keeps working).
2. Install SMSSecure: https://github.com/SMSSecure/SMSSecure . Some links to early builds can be found in the Github comments.

**Comment by fgrt** [comment]
Actually that does not solve the issue.

As i wrote in the thread starter: i lost the ability to send encrypted SMS that could be read by the intended recipient because the recipients TextSecure was updated and telling them that my encrypted SMS had the wrong version.

So receiving and sending encrypted SMS has to be re-enabled for all the people i communicated with encrypted.

So: Please reenable key exchange and encrypted messaging using SMS.

**Comment by fgrt** [comment]
Thinking about it i a bit longer am quite appalled by the lack of consideration for the users of your app.

Could it be that "the 100 identical issues here at github" point to a larger problem? In my experience for ever user that does complain there are (depending on the size of the project) 10s to 100s that do not complain.

Perhaps you want to stop seeing this as 100 singular issues, but rather a problem that could (and probably should) be fixed? - if only to lessen the damage that you inflict on your project by alienating a significant share of your user base?

**Comment by yzrmn** [comment]
IMHO it's a good step **forward** to remove encrypted SMS. They wrote the blog so people might understand this. But I really think most people are just too demanding and have no idea what it takes to coordinate a big project like Signal.
Signal (and at some point TextSecure) should be easy and you should not tamper with settings too much (e.g. I don't want to send SMS when there is no connection, because I have to pay alot for just one SMS). Again, removing encrypted SMS makes things easier. Hopefully Signal will be on various platforms and shares the *most* features across them.

If you really need encrypted SMS try SMSSecure (hats off to them btw). They also aim to remove Google Play services dependency. So I guess it's a win-win?!

**Comment by fgrt** [comment]
Dear yzrm,

you seem to not have read what i wrote before and therefore miss the point entirely on several occasions.

First of all this an issue filed against TextSecure not Signal.

Second of all: Your use case is not everbody's use case. I and the people around me do have SMS flatrate, most of them do not have a data flat.

Third of all: as i wrote above: Migrating to SMSSecure is not an option because it is source only also all contacts would have to be migrated, most of them non-technical users who do not live in driving distance.

Forth of all: i do not want my telephone to be online constantly just to be able to receive encrypted messages, that only opens me it up to attacks from abroad through the network (me not being in the US).

I (and others) would be really grateful if you would consider reenabling key exchange and encrypted messaging using SMS.

**Comment by agrajaghh** [comment]
github is not the right place for discussions like that, its for tracking bugs, please use the mailing list: https://lists.riseup.net/www/info/whispersystems (and look in the archive, there are already a lot of threads regarding encrypted SMS)

**Comment by fgrt** [comment]
Actually this is either a feature request or an issue regarding what some consider a regression in TextSecure so the bugtracker of TextSecure seem to be exactly the right place for this to be posted an discussed.

That there are a lot of threads regarding encrypted SMS on your mailing list without apparent action on the part of the project lead makes it even more clear that this issue and its discussion should be tracked openly in the official issue tracker on github.

**Comment by aprescott** [comment]
Can you describe a situation where you must protect your privacy by not being online, but where you are unable to activate airplane mode? If you have a smartphone that is capable of running TextSecure, it seems likely that you have so many background network interactions running (probably without your complete knowledge) which themselves are violating the same sense of privacy you consider to be a bug.

**Comment by fgrt** [comment]
There are a few issues with requiring the handset to be online to be able to send and receive messages.

0. the telephone has to be online and so accrues data charges (especially if it decides to pull an update or a new blacklist of URLs for the browser).

1. you have to have Googles Play Services installed on your telephone, also Google Cloud Messaging has to run (both of this can be fixed of course)[¹]

2. third parties like Google are regularly made aware of the !identified! users IP Address, the usage of TextSecure and can correlate that with other data they collect

3. you are establishing a distinct service on the mobile handset that can be attacked remotely from an IP network (especially from abroad, knowing about NSA's Quantum Insert and all the ilk does not help trusting in US network infrastructure).

4. on the network side you are also establishing a single point of failure for rogue actors to track TextSecure users and correlate and/or block and filter usage of this service.
For example whereas switching off all SMS transaktions in case of a civil unrest seems not really viable - because this would disturb a lot of control systems - blocking access to a destinct DNS-Name, IP-Range or Autonomous Zone seems quite practical and pretty free from unintended side effects.

So please consider reenabling key exchange and encrypted messaging using SMS.

[¹]: you have a lot less unintended network traffic[²] when you remove all of Googles software from your Android handset - which you can, unless your encrypted communication solution depends on Google Cloud Messaging, like TextSecure does
[²] actually thanks to a custom kernel i am made aware of all IP transactions that my handset initiates, and at the moment there is only one service that without any action on my part tries (but of course fails) to connect to the public Internet -> it's the NTP client shipped with android

**Comment by aprescott** [comment]
My personal view, purely as a user, is that you are working with a threat model that doesn't match TextSecure's when it comes to being online versus not. Some points (e.g. (4) and (5)) seem like they would need to go beyond merely bringing back SMS to address.

**Comment by fgrt** [comment]
Points (4) and (5) were at least partially addressed by TextSecure until recently.

What US Americans might not realize is, that DNS and IP based blocking are now quite commonplace even in Europe (implemented even in Countries like France and UK).

Think about Gezi park (at Taksim place) in Instanbul two years ago - and perhaps consider there will be an election in Turkey later this year to fuel your imagination.

I would be really grateful if the project lead would at least make the impression to address the issues that i raised here.

If Open Whisper Systems decided to remove SMS to build a service (that they will be charging for in the future) that would be fine with me - it should just say so and not insult my intelligence by insinuating the axolotl ratchet is difficult to implement and maintain with SMS as the underlying transport.

**Comment by NorthwestBased** [comment]
@fgrt While your concerns may be valid, the developers have already made it abundantly clear that they will not bring back encrypted SMS, and have outlined their reasons for doing so. They don't seem that interested in discussing this further.

Textsecure is no longer an encrypted SMS app. I suggest closing this issue and looking into other projects (such as SMSsecure) if the direction of this project doesn't meet your needs.

**Comment by fgrt** [comment]
Dear NorthwestBased,

it would have been kind of you, if you would have read what i wrote before answering, or are you honestly suggesting that i ask all these less technically inclined people to build some software from source and install it on their handset?

Around here this "update" disrupted the secure and confidential communication of a whole network of people.

We came to rely on TextSecure for our communication and you just pulled the rug from under our feet.

Adding insult to injury you propose solutions that are leaving us out in the rain.

Is that kind of unreliability really the image that this project wants to project?

How can any user of TextSecure be sure that it is not her use case that will be thrown under the bus next time this project deems some core functionality to be too much of a maintenance burden?

**Comment by NorthwestBased** [comment]
@fgrt I am not a dev. I have, however, read what the devs have said about the situation. They seem to have made up their mind about this issue. I'm just saying things as they are: TextSecure doesn't support SMS encryption and the devs don't seem to have any plans to reinstate this feature. I suggested using a fork of this project as an alternative if SMS encryption is important to you as it seems unlikely that TextSecure will reimplemint this feature.
