### ISSUE TITLE
Add back arrow for RegistrationProgressActivity.java

### ISSUE THREAD

**Issue by NorthwestBased** [WhisperSystems/TextSecure#2825]
TextSecure 2.9.2
Android 4.4.2
Samsung SGH-T399

When verifying a phone number, there is no way to cancel if you are having issues, except by clicking on "Edit +[phone number]" and then exiting from that screen. The physical back button on my phone doesn't work either. I'd suggest adding a back arrow on the upper bar to return to the previous activity. Maybe the back button should only be visible when text message registration fails? Attached is a picture of the activity.

![screenshot_2015-03-29-17-58-39](https://cloud.githubusercontent.com/assets/10520957/6888927/3b8ae70c-d648-11e4-873d-a108046dfa16.png)

**Comment by moxie0** [comment]
this is intentional

**Comment by NorthwestBased** [comment]
Ok perfect. It does seem bit confusing and inconsistant as a user though when my physical back button doesn't return to the previous screen, unlike the rest of the app.
