### ISSUE TITLE
Einige Probleme bedürfen Ihrer Aufmerksamkeit ...

### ISSUE THREAD

**Issue by cwittmer** [WhisperSystems/TextSecure#2827]
... geht es auch etwas genauer ?
Der Versuch auf eine Nachricht zu antworten schlägt fehl, ebenso die Deaktivierung der sicheren Kommunikation ...
Es wäre interessant zu wissen, warum der Versand fehlgeschlagen ist ...

**Comment by grandchild** [comment]
Die Entwickler hier sind zumeist nicht deutschsprachig, Also bezweifle ich, dass dieser Report ihnen Häfen wird.
The devs here are mostly non-german-speaking, so I doubt this report will help them.
Auch wären ein paar mehr Details hilfreich. Welche Textsecure Version hast du? Ein Log ist auch immer hilfreich (Einstellungen > Weitere Einstellungen > Diagnose Protokoll übermitteln).
A few more details would be helpful. Which Textsecure version do you have? A log is also helpful (Settings > Advanced > Submit debug log).

Please try and write in english :)

**Comment by Maesto** [comment]
Dies könnte ein duplikat von #2820 sein.
@cwittmer passiert das bei einem gruppenchat?

**Comment by moxie0** [comment]
Sorry, we don't speak German. Please open a new issue in English if possible.

**Comment by Maesto** [comment]
Sorry @moxie0 I just was translating.
