### ISSUE TITLE
Group messages prompts to send message multiple times, after connection failed

### ISSUE THREAD

**Issue by mad-de** [WhisperSystems/TextSecure#2833]
After a connection failure, the resend dialoge prompts you to resend the message for each participant, resulting in multiple messages for all groupmembers. E.g: group of 5 people => TS prompts you to resend the message to 4 persons => group chat gets filled with 4 identical messages.

Version: TS 2.9.2

![ts screenshot](https://cloud.githubusercontent.com/assets/7095883/6907678/8aa6d1de-d738-11e4-8d52-a7de6e1cfba3.jpg)

**Comment by cbarnsdale** [comment]
I can confirm this behavior as well. I was about to submit the same bug report.

**Comment by brumsoel** [comment]
Duplicate of #2639?

**Comment by rhodey** [comment]
thanks @brumsoel, closing as duplicate.
