### ISSUE TITLE
Selecting/marking message with image not possible/reliable

### ISSUE THREAD

**Issue by fajabird** [WhisperSystems/TextSecure#2836]
Steps to reproduce:

touch and hold on a received message with an image until its selected/marked. After releasing selection is dropped. This does not happen with normal text messages. Though, there is a workaround: touch and hold untild the image message is selected/marked and now move finger while still holding some way up or down until scrolling has been triggered. Now release - selection should be still active.

**Comment by moxie0** [comment]
duplicate of #2488, thanks but please search existing issues before filing new ones
