### ISSUE TITLE
Contact numbers copyable

### ISSUE THREAD

**Issue by sedrubal** [WhisperSystems/TextSecure#2837]
Someone created a group conversation. You don't have every contact saved in your address book. You want to copy the number of one contact and want to create a new contract entry.

Problem: I didn't find any chance to copy a number of a contact.

**Comment by McLoo** [comment]
tap the contact's letter-avatar to open the system contact dialog - should be easier than copying the number...

**Comment by agrajaghh** [comment]
unfortunately that feature is too hidden...

**Comment by sedrubal** [comment]
Yes, but if the person didn't write anything, then there is no chance to get the number.

**Comment by McLoo** [comment]
I see. Then that group member dialog's tap handler could be of use finally. 
That should open the same dialog as the avatar tap. Maybe I can turn on that tomorrow.

**Comment by sedrubal** [comment]
:+1:
