### ISSUE TITLE
Change action bar icons to the new shape

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#2838]
The several /res/drawable-*dpi/actionbar_icon_holo_dark.png and actionbar_icon_holo_light.png need to be updated to the shape of the new icon. They still have the TextSecure <= 2.4 shape.

**Comment by agrajaghh** [comment]
duplicate of #2732

**Comment by manhole11** [comment]
duplicate of #2732 ?

**Comment by rhodey** [comment]
thanks @ghost, closing as dupe
