### ISSUE TITLE
Cannot copy or paste

### ISSUE THREAD

**Issue by dhermosillo** [WhisperSystems/TextSecure#2845]
Copy and paste are not functioning.  Holding on an area of the screen brings up the copy bar at the top of the screen, but when I lift my finger to select copy or modify the selection, the bar vanishes.  When trying to paste, same issue.

**Comment by jeremymasters** [comment]
I think if you long press to the side of a colored bubble it will stay selected.  Workaround for now.

**Comment by rhodey** [comment]
@dhermosillo is this for all messages? issues #2333 describes this behavior for media messages and some others, can you be more specific?

**Comment by dhermosillo** [comment]
As of today, the copy/paste bar is staying on now.  However, I am still unable to select portions of the text, just the whole thing.

**Comment by rhodey** [comment]
thanks for the update @dhermosillo :)

not being able to select portions of the message is expected behavior as of now. If you think partial message copy would be a nice feature you can open a new issue for that.
