### ISSUE TITLE
No encrypted sms possible anymore?

### ISSUE THREAD

**Issue by papst01** [WhisperSystems/TextSecure#2846]
I don't know how long, but today (newest textsecure update from playstore) I realised that I could not send encrypted sms anymore. 
My wife has textsecure too (android 5.0 too) and we only wanna use it for encrypted sms (push messages not activated). But till now we could only send unencrypted sms and there is no way to reenable the encryption. Also for other contacts which use plain sms apps, there is not even a way to try to start a secure sms chat. I only could send an invitation to install the app.

**Comment by agrajaghh** [comment]
see https://whispersystems.org/blog/goodbye-encrypted-sms/

**Comment by papst01** [comment]
thank you for the fast response. But for me it is a game stopper. So goodbye from me.

**Comment by mejo-** [comment]
@papst01: a new project SMSSecure has been started as a fork of textsecure. This project aims to provide the encrypted SMS feature that just has been ripped out of TextSecure. According to the developers, soon the first release will arrive at F-Droid and on Google Play. Until then, you can follow the development on Github: https://github.com/SMSSecure/SMSSecure
