### ISSUE TITLE
Can we remove the SMS feature completely?

### ISSUE THREAD

**Issue by thejeshgn** [WhisperSystems/TextSecure#2848]
Since the secure SMS option is removed. To reduce the confusion, can we remove insecure SMS option too? 

Also remove the ability to capture incoming SMS and storing it. This will make it a clear that TextSecure is data based messaging App only and has nothing to do with SMS.

**Comment by merkste** [comment]
Don't! In my opinion integrating SMS/MMS functionality is one of TS's main strength. I really don't want to bother with different messaging clients for different protocols.

**Comment by agrajaghh** [comment]
Why opening this issue and post at the same time to the mailing list? I think the mailing list is the right place for discussions...
