### ISSUE TITLE
UI :: sent sms with link -> right click to this msg failed

### ISSUE THREAD

**Issue by nickma82** [WhisperSystems/TextSecure#285]
If i write an (unencrypted or encrypted) sms with the following link in the content
```Test - http://goo.gl/maps/900foo```
I get buggy behavioural while trying to select (right click) only this specific message. -> I'm simply not able to select it.

TextSecure v0.9.9.8 from Market

**Comment by rhodey** [comment]
closing as duplicate (though older) of #2333 which is more current and contains more actionable information for the purpose of resolving the issue.
