### ISSUE TITLE
MMS download failed!

### ISSUE THREAD

**Issue by jbarone** [WhisperSystems/TextSecure#2859]
After updating to TextSecure 2.9.3 iPhone group chat messages seem to all be resolving to MMS download failed!

Device: LGE LGLS90
Android: 5.0.1

**Comment by moxie0** [comment]
You'll need to submit a debug log that you capture immediately after receiving one of these MMS messages.  Otherwise we have no information.

**Comment by jbarone** [comment]
https://gist.github.com/anonymous/379381ec816ec86d91b7

**Comment by mcginty** [comment]
Since this is another issue of never receiving an MMS broadcast - closing in favor of #2872
