### ISSUE TITLE
 Fall back to SMS if no data connection

### ISSUE THREAD

**Issue by Kixunil** [WhisperSystems/TextSecure#2867]
First, are you some kind of fascists? Why did you lock #2847 ?

Second, why TS cant's send encrypted *SMS* anymore? I tough it can. I wanted to communicate securely with certain person which doesn't want to use Internet often but we both have free SMS. I tough TS is perfect solution for us.

Can this be solved somehow?

**Comment by agrajaghh** [comment]
there might be a reason they locked it ...

there is a discussion about sms fallback on the mailing list
for encrypted sms see: https://whispersystems.org/blog/goodbye-encrypted-sms/

**Comment by moxie0** [comment]
@Kixunil This is not a discussion forum.
