### ISSUE TITLE
Unable to run instrumentation tests due to proguard

### ISSUE THREAD

**Issue by pR0Ps** [WhisperSystems/TextSecure#2871]
Running `./gradlew proguardDebugTest` now fails (probably an issue with the [refactor](https://github.com/WhisperSystems/TextSecure/commit/597f7bbafd2ff7ef2779ca5292a2fc8ef568d489)).

The log is huge so I've put it on pastebin: http://pastebin.com/rkQ0BxUZ

**Comment by mcginty** [comment]
I was able to fix the proguard errors, but the tests don't seem to be happy yet.
