### ISSUE TITLE
encrypted text sent but not received

### ISSUE THREAD

**Issue by rokuko** [WhisperSystems/TextSecure#2873]
Encrypted texts from my TextSecure to another TextSecure are successfully sent but not received there. Vice versa is not a problem. My TextSecure does receive other texts. Both systems have a stable wifi internet connection.

My TextSecure log:
https://gist.github.com/152cfa2af3e9da8f5087

How can I help resolving that issue?

**Comment by volcano99** [comment]
Does the issue happen on 3g too?

**Comment by rokuko** [comment]
yes. also resetting the encryption doesn't change the described behavior.

**Comment by agrajaghh** [comment]
I guess we need the log from the device which isn't receiving your messages (we're talking about push messages, right?)

**Comment by mad-de** [comment]
Have you tried re-registering the device, that doesn't receive the messages?

**Comment by rokuko** [comment]
@agrajaghh yes, we're talking about push messages not normal texts. yeah getting the log from the device that is not receiving is complicated, apparantly it shows the log and if he klicks submit an error message pops up. gist is not responding properly? the log is to long?

@mad-de what does that mean? how do we do that?

**Comment by mad-de** [comment]
Settings -> Advanced -> untick TextSecure messages.
Tick and re-register.

**Comment by moxie0** [comment]
@rokuko Does the person not receiving texts ever use apps like Titanium Backup or any kind of backup/restore thing? Do they have a custom rom with a custom gapps install, or are they using a stock non-rooted ROM?

**Comment by rokuko** [comment]
@moxie0 nothing like that, plain vanilla samsung android flavor.

**Comment by rokuko** [comment]
@mad-de re-registering the device doesn't help.

**Comment by rhodey** [comment]
hey @rokuko if you still have TextSecure installed and are experiencing this bug a debug log would be great help.

Settings > Advanced > Submit debug log

you'll have to do that immediately after the strange behavior happens or the log will be overwritten by newer log information.

**Comment by lrobeson** [comment]
I'm having this exact same issue, encrypted messages sent to another TextSecure user are sent but the recipient isn't getting any of them. Here's my debug log: https://gist.github.com/anonymous/7cc6ad5386545e629349.

When I disabled the 'TextSecure messages" option in Advanced settings the messages go through to the recipient fine.

**Comment by moxie0** [comment]
@lrobeson Your best bet for support is to write to support@whispersystems.org.  We can get things figured out for you there.

**Comment by lrobeson** [comment]
@moxie0 Will do, thanks!

**Comment by riyapenn** [comment]
Closing as support@whispersystems.org addresses this.  For other users also experiencing this, please read http://support.whispersystems.org/customer/en/portal/articles/2120368-how-do-i-know-if-a-textsecure-message-has-been-delivered- 
and http://support.whispersystems.org/customer/en/portal/articles/2121929-why-is-there-a-delay-in-receiving-messages-
