### ISSUE TITLE
The design of 'Possible problems' dialog is broken

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#2882]
The dialog in registration problems is broken the same way as in #2853 (except there are no crashes, just a broken design):
![screenshot_2015-04-03-06-12-14](https://cloud.githubusercontent.com/assets/174176/6988271/5e96270c-da58-11e4-9b4f-504df8c236d2.png)

Apologies for the non-English (and boring) screenshot. I run into this yesterday while setting up another device for testing purposes.

The greyed text *'Mahdollisia ongelmia'* is the string *'Possible problems'* at Transifex (**RegistrationProblemsActivity_possible_problems**).

Android 4.0.4, TS 2.9.3

**Comment by mcginty** [comment]
Closing, then creating a new issue for moving these faux-dialogs to actual dialogs.
