### ISSUE TITLE
Alignment of the keyboard / Smiley switch for long texts

### ISSUE THREAD

**Issue by mad-de** [WhisperSystems/TextSecure#2891]
If you type a long message, the keyboard / Smiley switch gets aligned vertically in the middle, thereby moving upwards the longer your message is.
Whatsapp etc. has a fixed position on the bottom, which makes it easier for unskilled users to notice it's position.
2.10.1
![screenshot_2015-04-04-12-25-18](https://cloud.githubusercontent.com/assets/7095883/6992305/20cda0b6-dac7-11e4-9d68-bfc5024268d6.jpg)

**Comment by agrajaghh** [comment]
I agree, a fixed position at the bottom would look better. Same aplies to the send button...

**Comment by wp9015362** [comment]
Hello,

yes, in Telegram it's also the same as in WhatsApp, the buttons stay fixed at the bottom in both Telegram as well as in WhatsApp.

In the TextSecure screenshot from @mad-de, which is shown above, it simply looks buggy.

So, TextSecure should also have the buttons in a fixed position at the bottom, just like in Telegram and in WhatsApp.

And the font size in the message input box should be the same as the message font size (currently it's not, see: https://github.com/WhisperSystems/TextSecure/issues/2769).

Regards
