### ISSUE TITLE
TextSecure is using an outdated emoji set

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2894]
Hello,

I am just submitting this issue just in case you will stay with the Google Emoji set, instead of changing the Emoji set as requested over there:

https://github.com/WhisperSystems/TextSecure/issues/2892

I assume the Emoji set used for the internal TextSecure Emoji drawer is the Google Emoji set residing over there:

https://github.com/WhisperSystems/TextSecure/tree/master/assets

The Google Emoji set there is an old version of the Google Emoji set though.

The Google Emoji set recently has been updated, for more details see:

http://blog.emojipedia.org/android-50-emoji-changelog

and:

http://blog.emojipedia.org/209-new-emoji-flags-available-today

So, in case you should stay with the Google Emoji set, please update it to the latest version.

Regards

**Comment by mcginty** [comment]
I really don't want to remove the hairy heart.

**Comment by wp9015362** [comment]
@mcginty :

Thanks for your response, but, not sure: Is that a serious statement or are you just kidding and making fun of the hairy heart?

It was never meant to be a hairy heart, it is meant to be a yellow heart. And now Google fixed it, so please use the updated Emojis.

Or, even better:

Just use the Twitter "Twemoji" Emoji set or the "Emoji One" Emoji set as requested in https://github.com/WhisperSystems/TextSecure/issues/2892.

Both the Twitter "Twemoji" Emoji set as well as the "Emoji One" Emoji set look better than the Google Emoji set (IMHO) and also look much more similar to the Apple Emoji set than (even the updated) Google Emoji set does, which gives them much better interoperability (of course it would be best if there would be a standardized Emoji set, and one set only, on all devices though, but unfortunately it currently is not like that).

So, as already mentioned, I only submitted this issue in case you won't switch to the Twitter "Twemoji" Emoji set or to the "Emoji One" Emoji set or something similar.

Please switch to the Twitter "Twemoji" Emoji set or to the "Emoji One" Emoji set or something similar to the Apple Emoji set.

And if you really insist on keeping the Google Emoji set (which would be unfortunate), then please at least use the latest updated and fixed version of the Google Emoji set.

Regards

**Comment by mcginty** [comment]
My personal opinion is that all other emoji packs should migrate from yellow heart (useless) to hairy heart (brilliant), but since that's unlikely to happen, yes it's worth considering a unified emoji pack or at least updating the emoji pack we include to the latest iteration.

**Comment by wp9015362** [comment]
I saw you closed https://github.com/WhisperSystems/TextSecure/issues/2892. What does that mean now?

Does closing https://github.com/WhisperSystems/TextSecure/issues/2892 mean "No, we will keep the Google Emoji set and won't switch to another Emoji set."? Or does it mean "Let's discuss this in https://github.com/WhisperSystems/TextSecure/issues/2894 and therefore let's close https://github.com/WhisperSystems/TextSecure/issues/2892 as a duplicate."?

> @mcginty wrote:
> 
> but since that's unlikely to happen, yes it's worth considering a unified emoji
> pack or at least updating the emoji pack we include to the latest iteration.

So you are still open to switch to the Twitter "Twemoji" Emoji set or the "Emoji One" Emoji set even though you closed https://github.com/WhisperSystems/TextSecure/issues/2892?

If yes, then:

Are you waiting for user input now to see if users would like to keep the Google Emoji set or if they would like TextSecure to switch to another Emoji set which is more similar to the Apple Emoji set, like the Twitter "Twemoji" Emoji set or the "Emoji One" Emoji set for example?

Or what is going to happen now?

Regards

**Comment by mcginty** [comment]
They're pretty much the same issue, so I closed one of them as dupe. No decisions have been made about which emoji pack to use in the future.

**Comment by wp9015362** [comment]
@mcginty :

I found some screenshots on the XDA Developers forum which are showing how the [Twitter "Twemoji" Emoji set](https://github.com/twitter/twemoji) and the ["Emoji One" Emoji set](https://github.com/Ranks/emojione) look like on a Emoji drawer.

Maybe those screenshots will help you in your decision about which Emoji set to use in the future.

Here's a screenshot which shows how the [Twitter "Twemoji" Emoji set](https://github.com/twitter/twemoji) looks on a Emoji drawer:

![Image](http://i.imgur.com/Bxf3oQY.png)

And here's a screenshot which shows how the ["Emoji One" Emoji set](https://github.com/Ranks/emojione) looks on a Emoji drawer:

![Image](http://i.imgur.com/a2bj6Eo.png)

Source:

http://forum.xda-developers.com/showthread.php?p=58610497#post58610497

IMHO both the [Twitter "Twemoji" Emoji set](https://github.com/twitter/twemoji) as well the ["Emoji One" Emoji set](https://github.com/Ranks/emojione) look way better than the Google Emoji set.

It would be really nice if you could use one of them instead of the Google Emoji set, especially because they are both much more similar to the Apple Emoji set, which in turn would give TextSecure-Android a better interoperability with Signal-iOS, due to a reduced risk of Emojis possibly getting lost in translation, as described in the following article:

http://www.huffingtonpost.com/2014/06/27/emoji-meaning_n_5530638.html

Regards

**Comment by wp9015362** [comment]
@mcginty :

Another reason why the Emoji set in TextSecure is outdated now, see:

http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x

Regards

**Comment by mcginty** [comment]
@wp9015362 we get it that there are new emoji that aren't included. we accept pull requests, and in the mean time there are other issues that take priority.

**Comment by wp9015362** [comment]
Even though I really really really would prefer if TextSecure would ditch the Google "Noto Color Emoji" Emoji set and would use the ["Emoji One" Emoji set](https://github.com/Ranks/emojione) or the [Twitter "Twemoji" Emoji set](https://github.com/twitter/twemoji) instead, I just want to add that I seem to have found the source of the Google "Noto Color Emoji" Emoji set, so, just in case you haven't yet:

SVGs:
https://code.google.com/p/noto/source/browse/?name=master#git%2Fcolor_emoji%2Fsvg

PNGs:
https://code.google.com/p/noto/source/browse/?name=master#git%2Fcolor_emoji%2Fpng%2F128

Regards

**Comment by madig** [comment]
How about using the native Emoji set by the phone manufacturer? I mean, that's what you get when you insert an Emoji, might as well make the pane WYSIWYG.

**Comment by agrajaghh** [comment]
@madig that looks like #2936 and should be fixed in the next release...

**Comment by rhodey** [comment]
resolved by 082b6b35f8f35fbefdaa3097d44d6440d6a967ac
