### ISSUE TITLE
Crash message during update 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#2897]
Not sure if relevant. 
Update from 2.9.3 to 2.10.1 crashed TS (i was in a convo, while update loaded in the background) . Accidently closed the send crash log dialog, so here is the debug log:

https://cloud.githubusercontent.com/assets/4541238/5655338/cb9dbc3e-96c4-11e4-81d1-e089ef965d2a.png

**Comment by moxie0** [comment]
this is a screenshot, not a debug log

**Comment by McLoo** [comment]
Ouch. Too late... Clipboard was already sleeping. Sorry 
https://gist.github.com/9e60a3c927a6f58a061a

**Comment by moxie0** [comment]
I think this might actually be an xprivacy thing. Looks like a race condition.
