### ISSUE TITLE
Timeout intervall v2.10.1

### ISSUE THREAD

**Issue by claenn** [WhisperSystems/TextSecure#2902]
Cut numbers.

Regards
![screenshot_2015-04-05-20-32-51](https://cloud.githubusercontent.com/assets/8040019/6998085/405d47ce-dbd5-11e4-88c4-cde24495c6b3.jpg)

**Comment by 2-4601** [comment]
I do not have this issue.

Tested with:
- stock Android 5.0.1, Nexus 4, TS 2.10.1
- Android 4.0.4, U8880, TS 2.10.1

**Comment by agrajaghh** [comment]
I can reproduce this on Android 2.3.7, updating to betterpickers 1.5.5 didn't solve it.

**Comment by claenn** [comment]
Hmmm. 
Nex5, 370 DPI, 4.4.4, system font Avenir.
