### ISSUE TITLE
Can't receive messages after connection is lost

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#2903]
Hello
my textsecure doesn't receive push messages after the connection is lost (even once it's restored). To receive them, I have to open the app and wait a couple of seconds.

**Comment by moxie0** [comment]
Thanks, but we'd need some actionable data (such as a debug log) as more detail to be able to help you.  
https://github.com/WhisperSystems/TextSecure/wiki/Submitting-useful-bug-reports
