### ISSUE TITLE
Text in "Verify identity" screen gets cut off when system font size is set to maximum

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2904]
Hello,

in TextSecure 2.9.3, the text in the "Verify identity" screen gets cut off when the system font size is set to maximum.

The text goes "behind" the blue bar at the top of the screen (the blue bar which has the "Verify identity" and the barcode logo on it).

Could you please fix it?

Regards

**Comment by 2-4601** [comment]
Can confirm on Android 4.0.4, TS 2.10.1, [U8800](http://www.gsmarena.com/huawei_u8800_ideos_x5-3596.php) (device with a 3.8" screen)
![404](https://cloud.githubusercontent.com/assets/174176/6999029/e16b8e8a-dbff-11e4-8e88-29d545ab4e9f.jpg)

The beginning of the fingerprint and the string "Their identity (they read)" is out of screen, i.e. it is not possible to scroll all the way up.
However it is possible to scroll all the way down.

---

Cannot reproduce on Android 5.0.1, TS 2.10.1, [Nexus 4](http://www.gsmarena.com/lg_nexus_4_e960-5048.php) (4.7" screen)
