### ISSUE TITLE
not receiving message while app is closed

### ISSUE THREAD

**Issue by namnamir** [WhisperSystems/TextSecure#2907]
I use Android 5 but when trxrsecure is closed, I receive no notification. I have to open it to get notification.

**Comment by moxie0** [comment]
This means you aren't receiving GCM messages.  That is typically a result of:

1) Using backup/restore tools like Titanium Backup.

2) Using a custom ROM with a custom gapps install.

3) Disabling "background data" for any of the Google services (including Play).

4) Being on a network that filters GCM traffic.

Duplicate of #2852

**Comment by jedie** [comment]
Same as: #4266
