### ISSUE TITLE
Simplify Identity Verification

### ISSUE THREAD

**Issue by landapfel** [WhisperSystems/TextSecure#2908]
In my mind the "Verify identity" screen as it is right now (showing two fingerprints) is not compliant with the second Development Ideology.
> The user doesn't know what a key is.

I propose the following solution which is much easier to understand for a user while providing the same amount of security:
- Show the QR code that is being displayed when clicking "Get my key scanned" instead of the fingerprints
- Add a "Scan their identity" button that opens "Scan their key to compare"

For me it would also be acceptable to have an advanced mode which shows the fingerprints but that doesn't really comply with the third Development Ideology.

PS: I'd also appreciate having an indication showing if I have already verified the identity of the person I'm chatting with.
Maybe by showing the action bar in the chat activity in orange if not verified?

**Comment by agrajaghh** [comment]
have a look at this comment https://github.com/WhisperSystems/TextSecure/issues/910#issuecomment-74779990

> @maquis trust management isn't in the near-future plans. There will be changes to how we encode fingerprints and possibly some trust indicators to show you've verified, but those aren't solidified and there are other higher-priority tasks compared to this.

**Comment by moxie0** [comment]
great topic of the mailing list
