### ISSUE TITLE
Images sent in groups not resized

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#2913]
Though I think it is a neat feature, it should be optional at least :)

Sending the same image in a single conversation leads to a 1280 px resize with 222 KB, 
while as group attachment you blow out the whole 3,6 MB at the original resolution.

Noticed while wondered about the massive memory usage for some received images. Image 3 was received in a group

![unbenannt](https://cloud.githubusercontent.com/assets/5326916/7024546/f13efbdc-dd3d-11e4-8d76-090b2d84898a.png)

2.10.1 on 4.4.4 and 5.0.2

**Comment by mcginty** [comment]
You're glorious! Great find. That seems accurate at first glance given the send job code, too.
