### ISSUE TITLE
Textsecure slow at sending push messages

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#2914]
For some reason I don't know, textsecure is extremely slow at sending messages when on wifi. On 3g it works fine (it's not as fast as other apps I've tried, but it's acceptable), but the situation on wifi is "concerning". When I send messages (especially if I send many, one after the other), it looks like it takes a while (several seconds) for textsecure to start sending the data, like I wasn't connected to the internet, but I am. In the notification bar, I don't see the upload/download arrows highlighted, it's like it's not even trying to connect. Sometimes it takes less time to turn on and back off airplane mode to fix the issue than to wait until it starts sending the data.
The wifi works perfectly fine, by the way.
Thank you

**Comment by agrajaghh** [comment]
please post a debug log after sending messages on wifi

**Comment by volcano99** [comment]
https://gist.github.com/ef3a07542f2227f391f1
There you go. I sent 7 messages right before capturing the log. It took forever to send them :/

**Comment by agrajaghh** [comment]
how long is forever? 1min?

**Comment by volcano99** [comment]
I wrote all the 7 messages in less than 10 seconds, but it probably took something like a minute to send them

**Comment by volcano99** [comment]
I know one minute is not the end of the world, but still... it feels really slow and it makes real time conversations awkward since it takes a while for my messages to be sent

**Comment by moxie0** [comment]
So you're saying it takes 8 seconds for a message to send? If it's faster on data, that sounds like a problem with your wifi to me. The code is the same in either case.

**Comment by agrajaghh** [comment]
but on 3g its working "normally"?

**Comment by agrajaghh** [comment]
could you test it on a different wifi network?

**Comment by volcano99** [comment]
It does happen on 3g too, but it seems less often. I can't test it on a different wifi network right now, but I know it still happens

**Comment by volcano99** [comment]
(Sorry moxie i didn't see your message)
It's not faster on data, it just starts sending right away (most of the time). That's why it takes less time. The wifi I'm using is way faster than my 3g connection

**Comment by moxie0** [comment]
What do you mean by "starts sending right away?" What does that mean and how are you measuring it?

**Comment by volcano99** [comment]
So when you send a message, you get the light blue bubble with the "..." right? And then you see the arrows of data in the notification bar being highlighted because data is being sent/received and the message is sent in a matter of instants. But on wifi (and yeah, sometimes on 3g too) it takes several seconds before you see the arrows "working". Does that make sense? The messages are there but for some reason no data is being sent/received

**Comment by moxie0** [comment]
I'm not really sure those arrows in the notification drawer are an accurate indication of what's happening. The code is the same for the WiFi or the mobile data case, and the message starts sending whenever the OS indicates that the network is on. I'm afraid there's not much more we can do about that at the moment.
