### ISSUE TITLE
Allow carriers add suffix in the verification code sms

### ISSUE THREAD

**Issue by kookxiang** [WhisperSystems/TextSecure#2919]
I'd received a message like:
```
Your TextSecure verification code: ***-***[CEG]
```
I think the regular expression here should be changed to ignore any suffix just like you've ignored the prefix in the message:
https://github.com/WhisperSystems/TextSecure/blob/4397b55ceb8b82de1e8545e01dc7b6864fa85846/src/org/thoughtcrime/securesms/service/SmsListener.java#L131

**Comment by rhodey** [comment]
relevant 0.o >> http://stackoverflow.com/questions/28874648/id-like-to-change-or-to-hide-ceg-when-use-twilio-sending-message
