### ISSUE TITLE
notification's contact image is square, not round-cropped

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#2923]
Thought I've read such an issue already. Didn't find though.
Also I can't recall since when that's the case, but:

KitKat Sony Z1 compact 2.10.2
The contact image in the notification is not round cropped. Noticed with Mr. Open Mouth

and on CM 12 2.10.1
round cropped with li'l paddy lock 😕

**Comment by mcginty** [comment]
Haha, Mr. Open Mouth.

I'll be addressing that hopefully within the week as I rework the notifications to be Lollipop-friendly.
