### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Rochambeau** [WhisperSystems/TextSecure#2926]
Hi there,

i have the same problem as described here:

http://support.whispersystems.org/customer/portal/questions/11473410-unable-to-register

My version is 2.9.3.

**Comment by moxie0** [comment]
My guess is that you're running a custom ROM with a bad gapps install, but you'll need to post a debug log for us to know anything. That'll require you to use adb, since it happens before you can open the application.

**Comment by Rochambeau** [comment]
You're right. I'm running CM 12 with Paranoid Android Pico gapps (just GP framework und GP store). I hoped this would be enough. Will play araound with a more full featured gapps after the weekend and see if I can make it work.

Thanks for your fast response.
