### ISSUE TITLE
emoji size not matching system font size

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2937]
Hello,

the size of the Emojis in the TextSecure Emoji drawer scales with the system font size.

So, if the system font size gets increased, the size of the Emojis in the TextSecure Emoji drawer also increases and vice versa.

First of all I am asking me:

Is that an intentional behaviour? Or is it a bug?

Second:

The size of the Emojis in the Emoji drawer actually is noticeably bigger than the height of the system font size. Or with other words: They do not match.

If the the Emoji size scaling with the system font size is intentional, then shouldn't the size of the Emojis match the height of the system font size?

Regards

**Comment by wp9015362** [comment]
PS:

I think it might actually be good if the Emojis in the Emoji drawer are a little bit bigger than the system font size, because that might make it easier to tap on them.

But currently the Emojis seem to be a little bit too big in comparison to the system font size.

When setting the system font size to maximum they become huge.

Regards

**Comment by mcginty** [comment]
I agree, they're probably a bit big. I shrunk them by about 15% so more can fit on screen, but still want them to grow with the system font. My logic with that is that if you want your fonts bigger to read characters, emoji need just as much resolution increase to distinguish the face/iconography details.

**Comment by mcginty** [comment]
pushed to 2.14.0 branch
