### ISSUE TITLE
Emoji category icons in drawer are not highlighted when selected

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2938]
Hello,

the Emoji catergory icons in the TextSecure Emoji drawer are not being highlighted when they are selected.

They simply remain gray when they are selected.

With "Emoji category icons" I mean the clock, smiley, flower, bell, car and symbol icons at the top of the Emoji drawer, which allow to toggle between the different Emoji categories.

They are all gray and remain gray when selected.

But they should turn white when being selected so that they are visibly highlighted.

They also turn white on selection on the Google (AOSP) keyboard, on the Telegram for Android Emoji drawer, on the WhatsApp for Android Emoji drawer and so on...

TextSecure should do the same.

In the Telegram for Android and WhatsApp for Android Emoji drawers, the scrollbar below the Emoji categories also has a different color than grey, it's blue/green there.

It would be nice if that scrollbar in TextSecure would also have a special color (white would be okay as well I think) to make it stick out a little more.

Could you please do that?

Regards

**Comment by McLoo** [comment]
All is fine for me on KK 
Flower selected 
Scrolling while screenshooting

![screenshot_2015-04-10-21-11-00 01](https://cloud.githubusercontent.com/assets/5326916/7094948/5b3b4470-dfc6-11e4-82a7-206899989f75.png)

**Comment by 2-4601** [comment]
In my two devices (5.0.1 and 4.0.4) the emoji category selection icons look and behave just like in @McLoo's screenshot. I.e. **no issue.**

**Comment by wp9015362** [comment]
> @McLoo wrote:
> 
> All is fine for me on KK
Flower selected
Scrolling while screenshooting

In your screenshot, the only thing that is highlighting the Emoji category icon (the flower icon), is the fact that the scrollbar below it follows the selected category (and therefore is being placed below the flower icon).

I am referring to something else though.

Here is what it looks like in [Telegram for Android](https://github.com/DrKLO/Telegram):

https://telegram.org/file/811140073/1/IP83JaSL9H8/4f056c95a1cd5f0fec

![Image](https://telegram.org/file/811140073/1/IP83JaSL9H8/4f056c95a1cd5f0fec)

As you can see, not only does the scrollbar below the category icons have a special color (green/blue), but also the category icon, in this case the recent category (clock icon), is being highlighted by being white instead of being gray.

It's done like that in Telegram for Android, in WhatsApp for Android, in the Google (AOSP) keyboard and everywhere else I know of.

So, it would be nice if TextSecure could do it as well, because it's better like that IMHO.

> @2-4601 wrote:
> 
> In my two devices (5.0.1 and 4.0.4) the emoji category selection icons look and behave just like in @McLoo's screenshot. I.e. no issue.

Please see above.

Regards

**Comment by agrajaghh** [comment]
I guess actually it's supposed to be white as well in TextSecure but it doesn't seem to work. look at this file for the "flower" category e.g.: 
https://github.com/WhisperSystems/TextSecure/blob/master/res/drawable/emoji_category_flower.xml:

````xml
<?xml version="1.0" encoding="utf-8"?>
<selector
	xmlns:android="http://schemas.android.com/apk/res/android"
	android:enterFadeDuration="200"
	android:exitFadeDuration="300"
	>
	<item
		android:state_selected="true"
		android:drawable="@drawable/ic_smiles_flower_active"
		>
	</item>
	<item
		android:drawable="@drawable/ic_smiles_flower"
		>
	</item>
</selector>
```` 

I couldn't figure out after a quick look why it's not working / how PagerSlidingTabStrip is working ...

**Comment by wp9015362** [comment]
@agrajaghh :

Yes, you seem to be correct. There actually seems to be a gray icon for when a category is inactive and a white icon for when a category is active, see for example:

Normal:
https://github.com/WhisperSystems/TextSecure/blob/master/res/drawable-xxhdpi/ic_smiles_flower.png
Active:
https://github.com/WhisperSystems/TextSecure/blob/master/res/drawable-xxhdpi/ic_smiles_flower_active.png

So it seems to be a bug that it is not working.

On the backspace icon:

Normal:
https://github.com/WhisperSystems/TextSecure/blob/master/res/drawable-xxhdpi/ic_smiles_backspace.png
Active:
https://github.com/WhisperSystems/TextSecure/blob/master/res/drawable-xxhdpi/ic_smiles_backspace_active.png

it is working though (it becomes white when being pressed).

Regards

**Comment by 2-4601** [comment]
Speaking of backspace... it has another bug too. But for clarity I will make a new issue.
