### ISSUE TITLE
Emoji drawer toggle icon is smaller than Emoji category icons in Emoji drawer and it's smiley does not match the smiley of the Emoji people category icon.

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2939]
Hello,

the Emoji drawer / keyboard toggle icon:

https://github.com/WhisperSystems/TextSecure/blob/master/res/drawable-hdpi/ic_mood_grey600_24dp.png
https://github.com/WhisperSystems/TextSecure/blob/master/res/drawable-hdpi/ic_mood_white_24dp.png
https://github.com/WhisperSystems/TextSecure/blob/master/res/drawable-hdpi/ic_keyboard_grey600_24dp.png

is (or are) smaller than the Emoji category icons in the Emoji drawer.

It looks inconsistent.

Also, the Emoji toggle icon (the smiley):

https://github.com/WhisperSystems/TextSecure/blob/master/res/drawable-hdpi/ic_mood_grey600_24dp.png
https://github.com/WhisperSystems/TextSecure/blob/master/res/drawable-hdpi/ic_mood_white_24dp.png

is a different smiley than the smiley icon which is being used for the Emoji people category icon in the Emoji drawer (the smiley between the clock and the flower).

That also looks inconsistent.

In Telegram for Android, the Emoji drawer / keyboard toggle icon has the same size as the Emoji category icons in the Emoji drawer.

And the Emoji drawer toggle icon in Telegram for Android uses the same smiley that is being used for the Emoji people category icon in the Emoji drawer (the smiley between the clock and the flower).

Which looks and feels more consistent.

So, could you please increase the size of the Emoji drawer / keyboard toggle icon in TextSecure, to make it match the size of the Emoji category icons in the Emoji drawer?

And could you please replace the [Emoji drawer toggle smiley](https://github.com/WhisperSystems/TextSecure/blob/master/res/drawable-hdpi/ic_mood_grey600_24dp.png) with the same smiley that is  being used for the Emoji people category icon in the Emoji drawer (the smiley between the clock and the flower)?

Regards

**Comment by mcginty** [comment]
They're different icons in different places, I don't think they should necessarily be the same in either size or appearance.

**Comment by wp9015362** [comment]
> @mcginty wrote:
> 
> They're different icons in different places, I don't think they should necessarily be the same in either size or appearance.

Maybe not necessarily, but it still would definitely look better IMHO.

I also noticed something else.

The Emoji drawer / keyboard toggle icon also does not align with the recent category icon (clock icon) below it (it's shifted to the left in comparison and is not centered above it), see:

https://cloud.githubusercontent.com/assets/5326916/7094948/5b3b4470-dfc6-11e4-82a7-206899989f75.png ([Source](https://github.com/WhisperSystems/TextSecure/issues/2938#issuecomment-91655510))

![Image](https://cloud.githubusercontent.com/assets/5326916/7094948/5b3b4470-dfc6-11e4-82a7-206899989f75.png)

That looks and feels wrong IMHO.

In [Telegram for Android](https://github.com/DrKLO/Telegram), the icons are aligned, which looks and feels better, see:

https://telegram.org/file/811140073/1/IP83JaSL9H8/4f056c95a1cd5f0fec ([Source](https://telegram.org/blog/stickers))

![Image](https://telegram.org/file/811140073/1/IP83JaSL9H8/4f056c95a1cd5f0fec)

So, any chance you re-open the issue and do it?

Regards
