### ISSUE TITLE
Visible glitch when toggling between keyboard and built-in Emoji drawer

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2940]
Hello,

when toggling between the keyboard and the TextSecure Emoji drawer, the TextSecure Emoji drawer appears above the keyboard for a brief momen and "fades" into the keyboard, which looks like a glitch and is uneasy on the eyes.

In Telegram for Android, that does not happen. In Telegram for Android, when toggling between the built-in Emoji drawer and the keyboard, the toggle happens instantly, the Emoji drawer instantly replaces the keyboard, without any transition or whatever, which looks much smoother.

In TextSecure it currently looks buggy and is quite uneasy on the eyes.

Could you please fix it?

Regards

**Comment by agrajaghh** [comment]
pls make the titles of your issues shorter, thats way too long...

**Comment by wp9015362** [comment]
@agrajaghh :

Done.

**Comment by 2-4601** [comment]
This bug has been on my list for a while. I can even stack the keyboards on top of each other permanently. I will post something shortly when I have more time.

**Comment by 2-4601** [comment]
1. Write something in the input box (keyboard should also be open now)
2. Open emoji drawer
3. Select text from the input box

![screenrecord](https://cloud.githubusercontent.com/assets/174176/7095044/8391f104-dfcf-11e4-9d1c-311682014d5f.gif)

**Comment by 2-4601** [comment]
Btw, when the TS emoji drawer is open and you tap the input box to move the cursor to another place the emoji drawer gets dismissed and the system keyboard pops up. This is probably one of the underlying causes for the current weird behavior.

**Comment by mcginty** [comment]
Did some research - looks like one of the only ways to actually remove this glitch is to implement our emoji pane as a PopupWindow, meaning I have to revert the changes making our drawer a Fragment so we can dump it into a popup. Don't think this will make it into 2.16.0 since there are other beefy changes that need to get in too.

**Comment by mcginty** [comment]
in 2.22.0
