### ISSUE TITLE
Emoji drawer background is too dark for dark emoji

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2941]
Hello,

the background of the Emoji drawer is a bit too dark.

Some Emojis which have black in them are hard to see on the background because there is not enough contrast between them.

Could you therefore please increase the brightness of the Emoji drawer background?

Regards

**Comment by mcginty** [comment]
making it lighter would make the gray emoji difficult to distinguish - i don't think there's a great solution here.

**Comment by wp9015362** [comment]
> @mcginty wrote:
> 
> making it lighter would make the gray emoji difficult to distinguish - i don't think there's a great solution here.

I get what you are saying. But I didn't ask to make it full gray, just increasing the brightness a bit, which might already help.

Currently the Emoji drawer background in TextSecure is RGB 51,51,51.

Maybe you could try to increase it to something like RGB 64,64,64 for example and see how that goes?

Or something in between RGB 51,51,51 and RGB 64,64,64?

For comparison, in WhatsApp for Android it seems to be RGB 54,54,54, see:

https://lh4.ggpht.com/047ASpN1aTmiy6IQR198RyGHU4JzeWMeKYE_1UpfYu7RP0XxpxWWb0gndk728OexjH8=h900 ([Source](https://play.google.com/store/apps/details?id=com.whatsapp))

I think the situation can be improved a bit without making it worse for other Emojis.

It would be much appreciated if you could try.

Regards

**Comment by wp9015362** [comment]
PS:

@mcginty :

I had a look at what the Google "Noto Color Emoji" Emoji set looks like on a brighter background.

The following page:

http://www.unicode.org/Public/emoji/1.0/full-emoji-list.html

shows all of them on a white background (it even shows [the updated set](http://blog.emojipedia.org/android-50-emoji-changelog)).

As you can see there, the set actually seems to be designed in such a way that nothing actually gets lost on a white background.

So I would assume increasing the brightness of the TextSecure Emoji drawer background should be possible in some way.

Regards

**Comment by wp9015362** [comment]
@mcginty :

WhatsApp for Android apparently has received a new material design user interface with the latest update.

The Emoji drawer in the new WhatsApp material design user interface now looks like this:

http://www.androidpolice.com/wp-content/uploads/2015/04/nexus2cee_whatsapp-material-7.png ([Source](http://www.androidpolice.com/2015/04/14/hands-on-whatsapp-goes-material-with-cool-animations-fabs-and-lots-of-purty/))

![Image](http://www.androidpolice.com/wp-content/uploads/2015/04/nexus2cee_whatsapp-material-7.png)

As you can see, the background of the Emoji drawer is now much brighter and fits better with the overall material design (IMHO).

Any chance you could do the same for TextSecure?

It would be much appreciated.

Regards

**Comment by wp9015362** [comment]
Just saying:

Telegram for Android now also uses a light background for it's Emoji drawer and has a new stickers section in it's Emoji drawer, see:

https://telegram.org/file/811140345/1/I4cpmT-kjAk/1f7a944b623fe148bd ([Source](https://telegram.org/blog/captions-places))

![Image](https://telegram.org/file/811140345/1/I4cpmT-kjAk/1f7a944b623fe148bd)

Regards

**Comment by mcginty** [comment]
blocked on #3153
