### ISSUE TITLE
SMS are not received

### ISSUE THREAD

**Issue by voxspox** [WhisperSystems/TextSecure#2942]
hi,

I installed TS some days ago. I could send and receive encrypted messages and also received SMS. Today several SMS did not appear on my phone. From another phone I send a test SMS and got a receive receipt there but still no SMS on my phone. Then I disabled SMS in TS and tried again. This time the SMS was shown (I the native message app).

Knut

Device info: Samsung Galaxy S2 (i9100g), CyanogenMod 10.1.3, TextSecure 2.9.3
App state: Push registered, SMS/MSS enabled

**Comment by moxie0** [comment]
You have to include a debug log for us to be able to do anything:
https://github.com/WhisperSystems/TextSecure/wiki/Submitting-useful-bug-reports
