### ISSUE TITLE
Where are the old text-only smileys?

### ISSUE THREAD

**Issue by sjaeckel** [WhisperSystems/TextSecure#2943]
Why did you remove the old text based smileys?
I don't like all this emoji crap and preferred the other ones.

**Comment by mcginty** [comment]
You can still typically use your keyboard's emoji pane by long-pressing the enter key, if that's where you used to access it.

**Comment by sjaeckel** [comment]
Doesn't work for me

**Comment by oezgueremir** [comment]
mcginty, would be nice, if you could read the message before answering.
He is complaining about the missing text-based smilies, like :-( not the button!

I am missing them aswell, I dislike this whole emoji stuff...

**Comment by mcginty** [comment]
I read the message. I was saying we didn't remove text-based smilies, they just never existed in our emoji drawer. This seems to be something that the keyboard's emoji supports, and we recently changed to prefer our emoji drawer over the system's.

**Comment by oezgueremir** [comment]
Ok, this is an better explanation and I am seeing them by long pressing the "enter"-key.
Is it that difficult, to add the simple smilies to "our drawer" as well?
I am only using them...

**Comment by sjaeckel** [comment]
Well I remember having the choice of 'enter key' or 'old style smileys' in some menu, but that is gone now...

**Comment by wp9015362** [comment]
> @sjaeckel wrote:
> 
> Well I remember having the choice of 'enter key' or 'old style smileys' in some menu, but that is gone now...

Yes, that was part of the change which has been mentioned by @mcginty , see the following commit:

https://github.com/WhisperSystems/TextSecure/commit/2f20bb89f3b64701d047fa3af2aa8b6e0ecfdc34

Regards

**Comment by mcginty** [comment]
this is blocked until the refactor in #3153 is complete

**Comment by McLoo** [comment]
@mcginty seems you've have 'forgotten' about the emoticons, as they already are in a string-array and have the category icons. 
Wonder what tho GO code will like for generating the PNG :-P

**Comment by mcginty** [comment]
@McLoo haven't forgotten - assets are there and I'm writing the ASCII-emoji stuff! If we're generating PNGs of ASCII emoji I'm doing it wrong :P

**Comment by sjaeckel** [comment]
awesome
thanks!
