### ISSUE TITLE
Feature Request: unlimit length of input text

### ISSUE THREAD

**Issue by mawed** [WhisperSystems/TextSecure#2947]
Hey,

I did not find a issue regarding this topic.

I tried to copy an email and send it via TS. 
I couldn't paste it completely into the input box. It was cut off after some limitation.
I request to open the input box for unlimited input length but while sending the message it could cut the messages into the amount of max length messages, if this max length of message is needed.

Regards

Mawed

**Comment by claenn** [comment]
+1

**Comment by moxie0** [comment]
Thanks but we've decided not to do this for now.
