### ISSUE TITLE
Running a Custom Server

### ISSUE THREAD

**Issue by jianminglok** [WhisperSystems/TextSecure#2948]
I would like to ask how can I can I set the URL or something in the client source so that I will connect to my server?

**Comment by brumsoel** [comment]
Please close this issue as this is a bug tracker for TextSecure, not a support forum for setting up your own server. You also have to be aware that you won't receive any *official* support for the server source - the developers don't have enough time for that.

You'll have to use some other platform to discuss your question, e.g. http://support.whispersystems.org or stackoverflow.
