### ISSUE TITLE
Textsecure receives SMS even if its disabled in settings

### ISSUE THREAD

**Issue by mlsxlist** [WhisperSystems/TextSecure#2949]
I turned off SMS/MMS for Textsecure because I am using SMSsecure for SMS/MMS. Although SMS/MMS is switched off in the TextSecure settings, Textsecure still receives SMS.

**Comment by agrajaghh** [comment]
just encryted sms or every sms?

**Comment by mlsxlist** [comment]
Only encrypted sms.

**Comment by agrajaghh** [comment]
afaik this is intended behaviour until everybody updated TS

**Comment by mlsxlist** [comment]
Really? I receive messages I cannot read. That seems not a good solution for me. I would have expected that switching off SMS/MMS in the settings turns it really off.

**Comment by brumsoel** [comment]
> afaik this is intended behaviour until everybody updated TS

It is, see #2817.

**Comment by mlsxlist** [comment]
Thanks for the link. Receiving messages with Textsecure I cannot read for the next 6 months sounds not really user friendly.

**Comment by yzrmn** [comment]
I guess it was intended to be user friendly. It's kind of unlucky that things with SMSSecury unleashed so fast...
