### ISSUE TITLE
received notification, message not visible in app

### ISSUE THREAD

**Issue by midi** [WhisperSystems/TextSecure#2952]
Using TextSecure 2.11.0
Nexus 5, Stock 5.1 Android

Received two notifications of messages from TextSecure contacts, so probably over data as usual. Could read the preview, but once inside TextSecure, there were no new messages, this happened today, with two messages.

Sadly I don't have a log just yet. Please advise on what to do now.

**Comment by moxie0** [comment]
@midi You have to immediately capture a debug log, otherwise there's nothing we can do.

**Comment by wp9015362** [comment]
Just saying:

I have had that exact same issue happen once as well.

But it was with an older version of TextSecure.

**Comment by rhodey** [comment]
hey @midi, just checking in, have you experienced this behavior since first submitting this issue? if so how recently? any chance this might have happened on a high-latency network or any other distinguishing details like that?

**Comment by midi** [comment]
@rhodey I have not. But I also don't use TextSecure frequently/not every day.
It very well could've been a throttled connection plus VPN, but I'm not sure.

**Comment by rhodey** [comment]
ok, thanks for the update @midi, let's leave this open for awhile more in case anyone else goes looking for a related issue.
