### ISSUE TITLE
A lot of Emojis are missing from Emoji drawer and Emoji ordering and categorization is incorrect

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2954]
Hello,

a lot of Emojis are missing from the TextSecure Emoji drawer.

When I say a lot of Emojis are missing, then I am not referring to the fact that [TextSecure is using an outdated Emoji set](https://github.com/WhisperSystems/TextSecure/issues/2894).

What I mean is that they are actually missing and should be there even in the oudated Emoji set.

I also noticed that the Emoji ordering and categorization is incorrect.

The Emojis in the categories have a different ordering than they should have and some Emojis are placed in the wrong categories.

The issue seems to be caused by the actual source files, see:

https://github.com/WhisperSystems/TextSecure/blob/master/assets/emoji_0_wrapped.png
https://github.com/WhisperSystems/TextSecure/blob/master/assets/emoji_1_wrapped.png
https://github.com/WhisperSystems/TextSecure/blob/master/assets/emoji_2_wrapped.png
https://github.com/WhisperSystems/TextSecure/blob/master/assets/emoji_3_wrapped.png
https://github.com/WhisperSystems/TextSecure/blob/master/assets/emoji_4_wrapped.png

Because those source files exhibit the same issues as mentioned above.

Here is a list of the Emojis which should be available in the outdated set and the list also shows the expected ordering and categorization of the Emojis, see (you can toggle between the different categories by clicking on the smiley/flower/bell/car/symbols icons in the upper right corner above the list):

http://emoji.codes/family

But please note that Apple already seems to have introduced/adopted a new Emoji category / ordering system in their latest OS updates, see:

> http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x
> 
> **Emoji Categories**
> 
> Prepare to re-learn the position of your favorite emojis,
> as they have all changed. New categories have been introduced,
> and emojis have been re-arranged within the existing categories as well.
> 
> The new categories are:
>
> 😃 People
> 🌸 Nature
> 🍔 Food & Drink
> 🎉 Celebration
> 🏃 Activity
> 🌇 Travel & Places
> 🔣 Objects & Symbols
> 
> Essentially, many emojis that were previously in the People or Objects categories
> may now be in one of the new, more-specific categories. Objects & Symbols is now
> a catch-all for the more obscure remaining characters.

So, maybe it would make sense to adopt that new system.

So, could you please add all the missing Emojis ([and ideally update to the new set while being at it](https://github.com/WhisperSystems/TextSecure/issues/2894)) and correct the ordering of the Emojis either to the [traditional system](http://emoji.codes/family) or to the [new system that Apple is already using](http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x)?

It would be much appreciated.

Regards

**Comment by wp9015362** [comment]
PS:

Seems like Emojipedia has already adopted the [new categories that Apple is using now](http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x), so you can see the categories and the Emojis in them over there:

http://emojipedia.org/

Regards

**Comment by SwartzCr** [comment]
I am also experiencing this on android (5.0.2). In addition to the missing emoji, emoji are showing up different in the keyboard and in the text box, for example the hairy heart is hairy on the keyboard and yellow in the text box. Additionally I now don't have access to my keyboard's emoji drawer since the built in textsecure emoji drawer seems to be overriding it.

**Comment by agrajaghh** [comment]
@SwartzCr thats a different issue (#2936)

**Comment by wp9015362** [comment]
> @SwartzCr wrote:
> 
> In addition to the missing emoji, emoji are showing up different in the keyboard and in the text box, for example the hairy heart is hairy on the keyboard and yellow in the text box

See:

https://github.com/WhisperSystems/TextSecure/issues/2894

> @SwartzCr wrote:
> 
> Additionally I now don't have access to my keyboard's emoji drawer since the built in textsecure emoji drawer seems to be overriding it.

Actually it doesn't. Previously TextSecure was replacing the Enter key with a smiley key.

It is no longer doing this, since you are supposed to use the built-in Emoji drawer from TextSecure now (via the Emoji drawer toggle button on the left side of the message input box).

BUT:

You should still be able to access the Emoji keyboard of your main keyboard via the traditional way.

And that is by simply pressing and holding the Enter key.

Regards

**Comment by SwartzCr** [comment]
You are correct, I updated my phone and text secure at the same time, so I thought that the smiley-replacing-enter-key was part of my OS not textsecure, I can in fact still access the emoji keyboard by long pressing on the enter key. (but the emoji that show on my keyboard and the emoji that show when I click the smiley in the text box are different)

**Comment by mcginty** [comment]
blocked on #3153
