### ISSUE TITLE
Emoji drawer wastes space on left and right side

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2956]
Hello,

the Emoji drawer in TextSecure is wasting space on the left and right side.

As you can see on the following screenshot for example:

https://cloud.githubusercontent.com/assets/5326916/7094948/5b3b4470-dfc6-11e4-82a7-206899989f75.png ([Source](https://github.com/WhisperSystems/TextSecure/issues/2938#issuecomment-91655510))

![Image](https://cloud.githubusercontent.com/assets/5326916/7094948/5b3b4470-dfc6-11e4-82a7-206899989f75.png)

there is a lot of empty space on both the left as well as on the right side.

Also the vertical scrollbar is not placed directly on the outside of the Emoji drawer. There is a lot of empty space between the right outside and the scrollbar.

Even when I reduce the system font size to minimum, [which makes the Emojis smaller](https://github.com/WhisperSystems/TextSecure/issues/2937), I only get up to seven Emojis in one row on a display with 1080 pixels in width.

In comparison:

[Telegram for Android](https://github.com/DrKLO/Telegram) does not waste as much space on the left and right side of it's Emoji drawer and has the vertical scrollbar placed almost directly on the right side without having so much empty space between it and the right outside. And in Telegram for Android I get eight Emojis in one row.

Could you please shift the vertical scrollbar more to the right and use the empty space on the left and right side for actual content (i.e. Emojis), so that the space is not being wasted?

It would be much appreciated.

Regards

**Comment by moxie0** [comment]
@wp9015362 I think @mcginty gets it. You're probably more likely to see him work on the emoji drawer if you're less verbose.

**Comment by mcginty** [comment]
fix merged into 2.14.0 branch
