### ISSUE TITLE
Deleting a pending message crashes TS after Internet connection is restored

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#2963]
0. Lose Internet connection (use airplane mode, get locked in a basement, go to space, etc.)
1. Send a TS message
2. Delete the pending message
3. Get Internet connection restored
4. Watch TS crash (and report it like a good citizen)
5. Open TS again
6. At start up you will hear a message notification sound as if someone has just sent you a message (which is of course not the case)

Here's a .gif demonstrating this with an everyday situation:
![screenrecord3](https://cloud.githubusercontent.com/assets/174176/7108359/4c94e36e-e18c-11e4-99de-416e49cc7540.gif)

Debug log:
https://gist.github.com/152572e1bbead393e134

TS 2.11.0, Android 5.0.1

**Comment by volcano99** [comment]
One question: does the message actually go through when you delete a pending message (assuming it doesn't crash)?

**Comment by 2-4601** [comment]
Just reproduced this with Android 4.0.4, TS 2.11.0 and reported it. (No debug log this time since it was "empty")

@volcano99: No, it does not go through. However a couple of versions ago it did go through and TS did not crash then.

**Comment by 2-4601** [comment]
@moxie0 Thanks for the fix! Just tested with 2.11.1 and it works.

Unfortunately TS still crashes if you repeat the steps with a picture message (push). Did not test other media.
