### ISSUE TITLE
Emoji drawer recent category is reversed

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#2967]
Hello,

the recent category in TextSecure for Android is reversed.

Recently used Emojis are being added to the bottom right (the end) of the list.

This is counter intuitive and seems illogical, since you need to scroll down to the bottom of the list to pick a recent Emoji.

Every other keyboard or built-in Emoji drawer I know does it the other way around.

Other keyboards and built-in Emoji drawers add recent Emojis to the top left (the beginning) of the list.

So, could you please fix it in the TextSecure Emoji drawer?

Regards

**Comment by agrajaghh** [comment]
there is already a PR for that #2946

**Comment by mcginty** [comment]
assigning to rhodey since he has the PR open :)
