### ISSUE TITLE
possible smssecure server handshake?

### ISSUE THREAD

**Issue by mr-gosh** [WhisperSystems/TextSecure#2968]
Could it be possible to make textsecure users available to smssecure users and vice versa?

**Comment by agrajaghh** [comment]
What do you mean? Support encrypted SMS in TextSecure or support push messages in SMSSecure? I don't think thats gonna happen... Read https://whispersystems.org/blog/goodbye-encrypted-sms/

**Comment by mr-gosh** [comment]
yeah - i know that sms support was dropped by good reasons - but i think about the possibility to get it back without need to maintain it by just handshaking between the two servers...

so the textsecure user could use the pre-signed messages handed over by the smssecure server to tramsit a message from textsecure over smssecure servers to smssecure users...

and the other way around...

**Comment by jeremymasters** [comment]
closed in 3...2...1...

**Comment by moxie0** [comment]
@mr-gosh What servers? SMSSecure doesn't use their own servers, they use the telcom servers instead.
