### ISSUE TITLE
Conversation list does not scroll to top on new message 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#2983]
If you have the conversation list open and scrolled down a few lines you'll notice that 
- the list gets resorted (entries move down by one) 
- but the scroll position remains the same 

Also after returning from a convo where you just drafted something.

**Comment by moxie0** [comment]
That seems like the intended behavior to me.

**Comment by McLoo** [comment]
Wasn't really sure. Curious what mcginty says.

**Comment by mcginty** [comment]
The notification (especially once we add support for the heads-up high priority lollipop notifications) is a less intrusive means of having the same functionality.

**Comment by McLoo** [comment]
Agree. 

It was mostly the draft that made me open the issue. 
Scroll down down down, write a Frau in some convo, exit convo,  whoop convo moved out of sight to the top...
