### ISSUE TITLE
Wrong image preview in 'all images' view

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/TextSecure#2985]
Hey guys :)

I noticed a bug where the image preview in 'all images' is not the right one. (Nexus 4, Android 5.1, TS 2.11.1)

How to reproduce:
1. Open a chat with many pictures in it and click on 'all images' (in the chat where I noticed the bug are about 150 pics I guess)
2. Scroll down to the bottom of all the images
3. Click on any image 
4. The preview is different than the actual picture you open

If I wait a few seconds and click on the preview and go back and scroll a bit and click on it again it's the right one but not on the first/second click... 

This issue may be related to #840. 

You can find the log here: https://gist.github.com/anonymous/bbb8be8f2e0fb06821f3

**Comment by mcginty** [comment]
Should be resolved by the change to migrate to Glide for image loading. Thanks for the issue!

**Comment by rhodey** [comment]
resolved by dc903e49af94de4339b90e1e757d5f2948536435
