### ISSUE TITLE
TextSecure closes directly after startup

### ISSUE THREAD

**Issue by mju0** [WhisperSystems/TextSecure#2987]
Hi everyone,

after receiving an image, Textsecure crashes directly after the start. In airplane mode, Textsecure works as aspected and shows all messages (including the last one containing the image). As soon as I'm on-line again, Textsecure crashes again. I'm using Android 4.0.4 on a HUAWEI U8825-1.

The Log shows:

W/JobConsumer( 2335): java.lang.NegativeArraySizeException: -20
W/JobConsumer( 2335): 	at org.thoughtcrime.securesms.crypto.MasterCipher.verifyMacBody(Unknown Source)
W/JobConsumer( 2335): 	at org.thoughtcrime.securesms.crypto.MasterCipher.decryptBytes(Unknown Source)
W/JobConsumer( 2335): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.createAttachmentPointer(Unknown Source)
W/JobConsumer( 2335): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.retrievePart(Unknown Source)
W/JobConsumer( 2335): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.onRun(Unknown Source)
W/JobConsumer( 2335): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(Unknown Source)
W/JobConsumer( 2335): 	at org.whispersystems.jobqueue.JobConsumer.runJob(Unknown Source)
W/JobConsumer( 2335): 	at org.whispersystems.jobqueue.JobConsumer.run(Unknown Source)
W/dalvikvm( 2335): threadid=12: thread exiting with uncaught exception (group=0x40cbd2d0)
E/AndroidRuntime( 2335): FATAL EXCEPTION: JobConsumer-0
E/AndroidRuntime( 2335): java.lang.NegativeArraySizeException: -20
E/AndroidRuntime( 2335): 	at org.thoughtcrime.securesms.crypto.MasterCipher.verifyMacBody(Unknown Source)
E/AndroidRuntime( 2335): 	at org.thoughtcrime.securesms.crypto.MasterCipher.decryptBytes(Unknown Source)
E/AndroidRuntime( 2335): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.createAttachmentPointer(Unknown Source)
E/AndroidRuntime( 2335): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.retrievePart(Unknown Source)
E/AndroidRuntime( 2335): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.onRun(Unknown Source)
E/AndroidRuntime( 2335): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(Unknown Source)
E/AndroidRuntime( 2335): 	at org.whispersystems.jobqueue.JobConsumer.runJob(Unknown Source)
E/AndroidRuntime( 2335): 	at org.whispersystems.jobqueue.JobConsumer.run(Unknown Source)

You can find a full log here: http://pastebin.com/99fEDce3

Thank you,
mju0

**Comment by moxie0** [comment]
You can delete the message and then take the device out of airplane mode.

**Comment by mju0** [comment]
Well, I could have guessed that ;-)
Deleting the message solved this issue.
