### ISSUE TITLE
Non Internet Encypted Messages

### ISSUE THREAD

**Issue by liamtr** [WhisperSystems/TextSecure#2997]
Prior versions appeared to allow encrypted smses that were sent without using the internet... once the public keys had been obtained online.

This feature is much needed as certain country areas don't have reliable mobile internet or users may have the internet turned off (to save battery life even) and it's a real pain to get messages from other TextSecure users hours or days late once the internet is available again.

Please bring back this feature.

**Comment by Thunderpig72** [comment]
SMSSecure has that. They don't have push support at all though.

**Comment by JavaJens** [comment]
Please read: https://whispersystems.org/blog/goodbye-encrypted-sms/ and have a look at the above mentioned fork.
I'd assume you can close the ticket as well.

**Comment by liamtr** [comment]
Ok thanks for that. I wasn't aware of that fork.

Much appreciated.

-------- Original message --------

**Comment by liamtr** [comment]
Thanks for the info. That explains all.

Yes, it's fine to close the ticket now.

Thanks.

-------- Original message --------

**Comment by jeremymasters** [comment]
@liamtr I think since you are the creator of the issue you have permissions to close it as well.  It will save the developers some time.
