### ISSUE TITLE
Drafts Not Saved Without An Active Conversation

### ISSUE THREAD

**Issue by liamtr** [WhisperSystems/TextSecure#2998]
Please allow drafts to be saved even when there is no conversation history with a person.

It sux loosing the message and not being able to save it to be completed later.

The default Android sms client saves these drafts but TextSecure does not.

**Comment by brumsoel** [comment]
Saving drafts for new conversations has been added with #1510 and works with version 2.9.2.
Which version do you use?

**Comment by liamtr** [comment]
As you suggested the latest version does support that.

Thanks, much appreciated.

-------- Original message --------
