### ISSUE TITLE
Unnamed Group problem

### ISSUE THREAD

**Issue by kiggs** [WhisperSystems/TextSecure#2999]
Hello
I created a group in TextSecure and the group worked well for over week.  My Textsecure then crashed and I had to clear data and clear cache and re-register to get Textsecure to work again.

1) Now I get Unnamed Group instead of the old group name where group messages come
2) I get messages from the other group members but cannot reply to them or post pictures, video etc to the group.
3) If I recreate the Group name and add the people to it they get a totally new group called Unnamed Group which we can all post to but that is unpleasing to all!

This is really frustrating 

Has Text secure assigned a new administrator for the group? If so who and how do I get back on?
It was me that convinced the whole group to leave WhatsApp for a more secure app!

**Comment by kiggs** [comment]
OK. Got a way around it.
Firstly I forgot to add in the above post that when I checked group members of Unnamed Group it only showed me as a group member but the others were sending posts and I was getting them.

How I solved it.
I got one of the other phones from a group member and updated the group name.  It then showed on my phone that all the others members had been added to the group.  I then was able to go to the settings of the group and accept changes of the new name and it worked.

**Comment by brumsoel** [comment]
> Has Text secure assigned a new administrator for the group?

Groups in TextSecure do not have administrators; everyone can change the group's name and picture or add new members. However, you cannot remove someone from the group (other than yourself).

After wiping your data, your TextSecure client no longer has the group metadata available. This includes the group's name, but also the list of members, so it doesn't know who it has to send messages to. As the TextSecure server doesn't store any group metadata, the only way to get it is from another member.

As a quick workaround for your problem, ask somebody from your group to do a group update:
When viewing the group conversation, he or she should tap the settings button, choose "Update group" and just confirm the update - there should be no need to actually change the group information. After you received the update, your client will know the group name and be able to post to it again.

This process should probably be automated somehow (as soon as a message belonging to an unknown group is received, request group update directly from the sender?).

**Comment by kiggs** [comment]
Thanks Brumsoel
Had also just stumbled upon the solution.

**Comment by brumsoel** [comment]
Good to hear!

On a side note - I just saw there's already an issue for this bug: #2581
