### ISSUE TITLE
Emoticons

### ISSUE THREAD

**Issue by lesgrossman** [WhisperSystems/TextSecure#3001]
Hope this is not a dup.

On the last couple of text secure updates (on the Droid Turbo at least).  The emoticons are 
very messed up.  Best description I can give is that if I had a tic-tac-toe grid of emoticons, 
The new text secure app is centering on the intersections of the grid.  So for each emoticon,
I see a quarter of each emoticon around the grid intersection.

**Comment by wp9015362** [comment]
@lesgrossman :

This has already been reported, see:

https://github.com/WhisperSystems/TextSecure/issues/2957

Regards

**Comment by lesgrossman** [comment]
Thanks. Following the original bug ID

**Comment by jeremymasters** [comment]
@lesgrossman you could probably close this too then to help avoid confusion.

**Comment by lesgrossman** [comment]
oops will do

Together We Win!   Looking for cloud storage, try copy.com
<https://copy.com?r=6BuEoY> (20g free <https://copy.com?r=6BuEoY>)
--
Chad - Sisel Promoter
Take Your Life Back! <http://choman.mysiselpro.com/>
Creating A More Meaningful Life

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

Some people claim if you play a Windows Install Disc backwards you'll hear
satanic Messages.
That's nothing, if you play it forward it installs Windows
