### ISSUE TITLE
No way to view updated contact identity without sending message

### ISSUE THREAD

**Issue by willscott** [WhisperSystems/TextSecure#3003]
I sent a messge in an existing conversation, and it was not sent with a warning that the contact's fingerprint had changed.

The option i was given was to 'verify identity', at which point the message was sent.  While in the warning state, i couldn't find a way to either view the new fingerprint of the contact so that I could confirm it out of band, or prevent the pending message from being sent when I verified identity in order to see the new fingerprint.

**Comment by moxie0** [comment]
Clicking verify tells you what's going on, gives you the option to check the fingerprint, and then allows you to select ok or cancel.

**Comment by willscott** [comment]
This is on 2.11.1 from play store.

Clicking verify showed the dialog you mentioned with an 'accept' and 'cancel' choice.  Cancel closed the dialog and put me back in the warning state. Accept caused the message to be sent.

The fingerprint was not shown in the dialog, and there was no way to delete my pending message while accepting.

**Comment by moxie0** [comment]
There is a link to the fingerprint in the dialog.

**Comment by agrajaghh** [comment]
you have to click on "You may wish to verify this contact"
![screenshot_2015-04-16-19-51-54](https://cloud.githubusercontent.com/assets/5296073/7191902/5f353fac-e491-11e4-93de-64bea7c0d4a7.png)

![screenshot_2015-04-16-19-52-00](https://cloud.githubusercontent.com/assets/5296073/7191906/68156930-e491-11e4-976f-2a5b848f736c.png)
