### ISSUE TITLE
Can't use TextSecure to share Glympse

### ISSUE THREAD

**Issue by chr1shaefn3r** [WhisperSystems/TextSecure#3013]
I occasionally use [Glympse](https://play.google.com/store/apps/details?id=com.glympse.android.glympse) to share my location with friends. Unfortunately I can't use TextSecure to share the link anymore.

**Experienced behaviour**
1. Press "Send Glympse" in the Glympse app
2. TextSecures main activity pops up
3. I choose a contact
4. No message is pre-filled
5. Can't send the link :(

**Correct behaviour**
1. Press "Send Glympse" in the Glympse app
2. TextSecues "share with somebody" activity pops up
3. I choose a contact
4. The message is pre-filled
5. Press send :)

**Investigation**
I used git-bisect to identify the following commit as the problem: "[move routing logic to all activities](https://github.com/WhisperSystems/TextSecure/commit/0ff99258acd8e125ae902ff749f93e05c6f8ecb0?diff=unified). Due to the far-reaching changes made in this commit, I can't tell what actually causes the problem.

Sharing with other apps (I checked Twitter, Firefox and the default browser) works as expected.

**/edit:** I"m running Glympse 2.65, TS 2.12.0, HTC One (M7) with Cyanogenmod 11 (Android 4.4.4)

**Comment by claenn** [comment]
Sorry. Can't confirm this issue.
It works for me.

Regards

**Comment by 2-4601** [comment]
Also unable to reproduce.
Tested with TS 2.12.0, Nexus 4 with stock Android 5.0.1 and another device I found on the street with some weird rom 4.0.4.

**Comment by mad-de** [comment]
Can reproduce the exact same bahaviour. TS 12.0, Android 4.4 on Cynaogenmod 11.

**Comment by mcginty** [comment]
Can't reproduce on android 5.0.2, maybe it's only for < Lollipop versions?

**Comment by 2-4601** [comment]
No. I also tested it with Android 4.0.4 and had no issues.

> Tested with Glympse 2.65, TS 2.12.0 ... **4.0.4.**

CM 11 or KitKat perhaps?

**Comment by mcginty** [comment]
Thanks @2-4601, sorry I missed that :). Will spin up an emulator.

**Comment by claenn** [comment]
No probs for me with KK 4.4.4 Slimkat, Franco kernel #63, Nex5, TS v2.12.0

Regards

**Comment by mcginty** [comment]
Since I can't reproduce this, I'm removing the milestone.

**Comment by chr1shaefn3r** [comment]
Yeah, probably some Cyanogenmod-specific quirk :/
