### ISSUE TITLE
Resending a failed message to every member of the group sends the message multiple times.

### ISSUE THREAD

**Issue by lazlolazlolazlo** [WhisperSystems/TextSecure#3015]
When a group message failed sending and you resend the failed message to every group member it is sent multiple times. For example, if you resend a message in a group of 4 and resend the message to every group member it will be sent 4 times.

Android 4.4
TextSecure 2.11.1, push messages
Motorola Moto E

**Comment by volcano99** [comment]
duplicate of #2639 ?

**Comment by lazlolazlolazlo** [comment]
Yes, indeed a duplicate of #2639.

**Comment by jeremymasters** [comment]
@lazlolazlolazlo Since you created the issue, you have permissions to close it as well since it's a dupe.
