### ISSUE TITLE
Labeled messages or a conversation search function (internal)

### ISSUE THREAD

**Issue by rigelq** [WhisperSystems/TextSecure#3016]
Why not make it possible to label certain messages? For example, me and my wife send bill related information between each other. I need to be able to find these messages in a smoother way than scrolling through the whole conversation. It also would be nice to have a normal search function inside the conversations. Cheers!

**Comment by agrajaghh** [comment]
for search see #1232

**Comment by moxie0** [comment]
Closing as duplicate
