### ISSUE TITLE
Downloading MMS Content Does Not Work

### ISSUE THREAD

**Issue by nimdajitam** [WhisperSystems/TextSecure#3019]
This is my post in another (closed) issue thread ...

I'm experiencing the same issue as Matej described here after updating TexTesecure (from 2 versions back) without changing MMS settings in any way. I've tried with Andorid defaults (TextSecure defaults) and manual settings ... No luck! Sending MMS works fine both way.

I've discovered something interesting. When I get MMS notification message, expiration time (for downloading MMS content) displayed in TextSecure is identical to time, when notification was received. What means that it's a priori expired!

Downloading MMS content on default Android app works fine too.

... And MatejKovacic previously wrote: 

"I have TextSecure 2.11.1 (the latest version) on HTC One Mini. I have received MMS in TextSecure, but cannot open it. TextSecure is connecting to MMS server, but after a while it times out. I am using Simobil (MCC: 293, MNC: 40).

My settings are:
URL MMSC: http://mmc
Proxy server for MMS: 80.95.224.46
Proxy server port for MMS: 9201
MMSC username: simobil
MMSC password: internet
MMS proxy: (without)

Any idea?"

Original post (in inappropriate and closed issue thread): https://github.com/WhisperSystems/TextSecure/issues/388

**Comment by nimdajitam** [comment]
I have one MMS notification message that I received on 11th of April. I'm unable to download it's content since I've received it. I tried to download it few minutes ago and created cat.log shortly after that. Here it is: https://gist.github.com/anonymous/604866e5c7ad271fc17b

**Comment by mcginty** [comment]
@nimdajitam that looks like the response from your carrier was empty. Could it be that your received MMS expired already if it was from 10 days ago?

**Comment by red-coracle** [comment]
I can't tell if it's the same issue, but I also had trouble receiving an MMS. It was a multi-recipient text message sent from an iPhone.

Log here: https://gist.github.com/red-coracle/83b749c7a72fc6202ee2

**Comment by mcginty** [comment]
@red-coracle yeah, that looks like a "Message not found" error from the server, where it's saying the message is not available. We see that every so often, and our best guess so far is that another Android app is downloading the MMS first and causing the server to delete the message.

**Comment by nimdajitam** [comment]
@mcginty no it's not possible as my provider keeps MMS content for at least 14 days. And in my case, I have only native Android SMS/MMS app beside TextSecure. I get no MMS notification in natibe app nor I see MMS content anywhere. If you want me to test some specific tasks, circumstances, feel free to ask. I will try to sniff the traffic while receiving notification and trying to download MMS content.

**Comment by nimdajitam** [comment]
Here is cat log of unsuccessful download of a fresh MMS content: https://gist.github.com/anonymous/efc2ace6a2b3664fb139

Here is log after another consecutive try of downloading: https://gist.github.com/anonymous/00112a103f96f448314a

**Comment by nimdajitam** [comment]
How could another app (for example: native Android's) download MMS content without knowing it's secret (receiving MMS notification that goes straight to TextSecure)? I don't get it. And why it's happening after updating TextSecure without installing any additional app? I suppose that is a flow in TextSecure, and TextSecure is messing up something when receiving MMS notification as I see expiration time for downloading content already expired when notification comes. This expiration time is equal to time when notification was received. I suppose that TextSecure tries to fetch MMS content and fails due to internal error what erases content on my provider's side.

**Comment by willbuckner** [comment]
Yeah, everyone seems in denial that it's a TextSecure bug. It's definitely a TextSecure bug, it's happening to everyone I know with TS  since a couple updates ago.

**Comment by nimdajitam** [comment]
It's a serious bug and deserves such tag!

**Comment by mcginty** [comment]
@nimdajitam if you can successfully retrieve an MMS in android's native client and can sniff traffic, it'd be great to get a sniff of both a successful native retrieve and our failed retrieve so I can see the differences in the requests.

**Comment by nimdajitam** [comment]
Sure, I can. Expect my results to be posted on 7th of May.

**Comment by eosrei** [comment]
I cannot upload/download MMS content from non-TextSecure users while wifi is connected/enabled. SMS is fine. Workaround: disable wifi, wait for the transfer, and re-enable wifi. It's a not a solution, but it works.

**Comment by nseidm1** [comment]
Message not found is a common carrier level issue. Reach out to the carrier, give them the exact url where the mms is located, and escalate to the engineering department. Many carriers prematurely delete Mms content, thus once downloaded, partially downloaded, etc... the carrier deletes the content making it UNDOWNLOADABLE. This is not a text secure issue, period.

**Comment by eosrei** [comment]
@nseidm1 It's been awhile on this issue, but it has already been covered in multiple issues that it is/was a TextSecure bug. T-mobile (and other carriers) disallow MMS downloads via the Internet, requiring the application to use the carrier's data network. I personally consider this issue fixed, but it definitely was a TextSecure issue.

**Comment by mcginty** [comment]
closing since there was never a packet capture, not much to act on
