### ISSUE TITLE
Did not detect phone number change on incoming text

### ISSUE THREAD

**Issue by jkemp814** [WhisperSystems/TextSecure#3031]
I have a friend who notified me after sending a text that her number changed. Nothing seemed different except her old number still shows and text came in automatically decrypted as usual. Shouldn't the app have noticed this? Does the app just go by the keys stored? I deleted the thread and text still come in the same. I even ended the session. Will we both have to delete the app and start over? Seems like a security flaw. When she calls her new number shows up.

**Comment by moxie0** [comment]
did your friend re-register with her new number?

On 04/21/2015 05:52 PM, jkemp814 wrote:
> I have a friend who notified me after sending a text that her number
> changed. Nothing seemed different except her old number still shows and
> text came in automatically decrypted as usual. Shouldn't the app have
> noticed this? Does the app just go by the keys stored? I deleted the
> thread and text still come in the same. I even ended the session. Will
> we both have to delete the app and start over? Seems like a security
> flaw. When she calls her new number shows up.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/TextSecure/issues/3031>.
> 

-- 
http://www.thoughtcrime.org

**Comment by jkemp814** [comment]
Its on the same phone. App still installed. SO I would say no she didn't. Thats why I thinking the app is only looking at the keys stored.

**Comment by moxie0** [comment]
There's no way for the app or the server to know that your friend got a new phone number, she has to register with the new number if that's the number she wants to use.  We should probably surface a "change number" option to be more visible, but right now she can untick TextSecure Settings -> Advanced -> TextSecure Messages, then re-tick it.

**Comment by jkemp814** [comment]
Thanks Moxie. That's what I had her do.
