### ISSUE TITLE
Speed up textsecure

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#3035]
First of all, I apologize if this is a duplicate of #981. I would like the developers to work on making TS a real instant messenger. Right now, even assuming everything goes well when sending a message, it still takes way (way!) more than other popular messengers. I don't know if it's because of the encryption or because of what mentioned in 981, or something else. What I know is that from the second I hit send, it takes some time before the message appears in the conversation, then some time to get sent and some time to get delivered (though usually the last two are inverted). It takes too long. Now, "some time" isn't a minute, but the process of sending is not at all instantaneous. I am basically begging my friends to use textsecure, but they keep complaining because "no way, it's too slow". To which I don't know what to answer. It does feel much slower than whatsapp.
Is this because you don't have enough servers? Or is it a problem of the client itself?

**Comment by volcano99** [comment]
? Why was this closed? Any reasons?

**Comment by volcano99** [comment]
I'm sorry if you're offended, but textsecure really is slower than all the competitors.. getting offended/denying the truth won't fix the problem. You should take in criticisms better, you can't succeed if you expect your app to be perfect on your first try.
Regards.

**Comment by moxie0** [comment]
You intentionally opened a duplicate issue, and are surprised that it was closed?

**Comment by volcano99** [comment]
I don't know if what makes it slow is the handshake or something else... Maybe it's something else. I can't know, this is not my app...

**Comment by moxie0** [comment]
Sounds like a good topic for the mailing list.
