### ISSUE TITLE
When adding an attachment, have "take photo" as an option

### ISSUE THREAD

**Issue by turion** [WhisperSystems/TextSecure#3040]
When I'm chatting with someone and I see something I want to take a picture of and send it to them, I have to close TextSecure, take the photo and share it on TextSecure again. That's more work than it needed to be, and furthermore the photo is stored unencrypted first. There should be an option to take the image directly and send it. Threema has such an option, that's the only thing that's better about Threema.

**Comment by volcano99** [comment]
There's a PR for that. #3018 
Please close

**Comment by turion** [comment]
Awesome! I didn't find that when I searched for it.
