### ISSUE TITLE
Error:Could not find com.afollestad:material-dialogs:0.6.4.7. Required by: TextSecure:unspecified

### ISSUE THREAD

**Issue by codelogman** [WhisperSystems/TextSecure#3049]
that, i cannot load the project on android studio

**Comment by mcginty** [comment]
sounds like you're probably in offline mode or have some other environment issue

**Comment by codelogman** [comment]
mmm, no, i try to download text-secure repository zip file and the same issue is present.

so, i update also android SDK manager :

Android Support Repository
and
Android Support Library

and update the android studio ....

what can i do, or where i can check if i have offline mode o something else?

**Comment by mcginty** [comment]
maybe try the unofficial support forums that have been created https://groups.google.com/forum/#!forum/whispersystems-community-unofficial

unfortunately we don't have the time to help debug developer environment issues and i don't think this is a probem with our build scripts

**Comment by rhodey** [comment]
@codelogman where did you get the TextSecure repository in the form of a .zip file from? The only supported build instructions are documented [here in BUILDING.md](https://github.com/WhisperSystems/TextSecure/blob/master/BUILDING.md)

can you try those instructions.

**Comment by rhodey** [comment]
sorry that this was closed @codelogman, turns out the [material dialogs library](https://github.com/afollestad/material-dialogs) we are using in TextSecure decided to remove version `0.6.4.7` from their maven repositories. we should update our build.grade to use the latest version of this library `0.7.2.8`.

**Comment by rhodey** [comment]
resolved by b37c81ddf19fbbcdcf849ceb06d08cea699d855d
