### ISSUE TITLE
Thumbnails not rendering

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#3051]
Built a RC and tried sending a few images.  This happens every so often, where the entire message bubble (except for the arrow) fails to render:

![glide-sucks](https://cloud.githubusercontent.com/assets/512439/7308349/9a4b2df4-e9c8-11e4-9a89-f476c6d24453.png)

**Comment by moxie0** [comment]
(scroll performance is also pretty degraded on GB)

**Comment by mcginty** [comment]
still haven't reproduced, both on my device and emulator

**Comment by mcginty** [comment]
YES REPRODUCED FINALLY

**Comment by mcginty** [comment]
ok will work this out

**Comment by mcginty** [comment]
If you experience this then scroll up and back down, it fixes itself which makes me think this is a race case with the thumbnail generation.

**Comment by mcginty** [comment]
ok got it. if the image isn't loaded into the thumbnail view before you hit send, this will happen.

**Comment by mcginty** [comment]
so it's caused by quickly adding an image and immediately tapping send.
