### ISSUE TITLE
End secure session doesn't seem to work

### ISSUE THREAD

**Issue by benmayne** [WhisperSystems/TextSecure#3055]
https://gist.github.com/anonymous/878bf02ca3cbc39d62c5

ATT Galaxy S4

Across several conversations, I can't seem to end a secure session. This is especially bad because at least on of the people I was trying to end the secure session hasn't used text secure in months. It seems that the sms fallback has also gone away? 

![2015-04-24 10 34 15-edited](https://cloud.githubusercontent.com/assets/3374110/7321289/484a3368-ea6f-11e4-81ba-1d8656e5b404.png)

**Comment by justin-** [comment]
Messages over data are always encrypted. You should have your contact go to https://whispersystems.org/textsecure/unregister/ to unregister their number from the TextSecure service. For now, you can long press on the send button to select "Insecure SMS". I think you can also uncheck "TextSecure messages" from the advanced settings to unregister your number but I'm not sure.

**Comment by benmayne** [comment]
Yes, but then what does end secure session do?

**Comment by moxie0** [comment]
It ends the session.  The next time you send a message, a new one is automatically started.  This is only still useful for a small set of edge cases where people mess with their phones or use things like titanium backup.  We'll eventually be able to get rid of it all together.
