### ISSUE TITLE
Can't send vor receive MMS

### ISSUE THREAD

**Issue by tobi2** [WhisperSystems/TextSecure#3057]
I have an HTC One M7 with ViperOne 8.0. running on an AT&T plan. I am working on the most recent TextSecure version from Playstore. Push is enabled and TextSecure is the default messaging app. I can't send or receive MMS. This was working on older versions of TextSecure and MMS does work with the Android/ViperOne default messaging app.

Debug log: https://gist.github.com/cb1b063a41df22271b2a

**Comment by nimdajitam** [comment]
Here is an older and more detailed description of the issue: https://github.com/WhisperSystems/TextSecure/issues/3019

And it deserves a bug tag!
