### ISSUE TITLE
Option to make encrypted backup missing from 2.12.0. How to backups keys?

### ISSUE THREAD

**Issue by jottr** [WhisperSystems/TextSecure#3062]
I just tried to export my keys and sms to an encrypted folder as described on the respective [support page](http://support.whispersystems.org/customer/portal/articles/1476131-what-happens-if-i-lose-my-phone-):

> To make a backup of your keys, settings, and messages you can go to the main conversation view and tap the TextSecure logo in the top-left of the screen. Tap the "Import / Export" option, choose the Export tab, and tap "Export Encrypted Backup."

The **Export Encrypted Backup** option is missing in `Textsecure 2.12.0` on `Android 4.4.2` though. 

Has the key export feature been removed from textsecure altogether? 
What options do I have to export my keys, i.e. when migrating to another phone?

**Comment by johanw666** [comment]
This option is missing for a long time already. If you're rooted, use Titanium Backup to backup keys. If you're not rooted, it can't be done.

**Comment by jottr** [comment]
Maybe someone with access to the wiki could update that section then?
