### ISSUE TITLE
Group message notification opens private conversation when TS is locked with passphrase

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3064]
0. Passphrase enabled
1. Get TS locked
2. Ask Cthulhu to send you a group message
3. Tap message notification to open TS
4. Enter your passphrase to unlock TS
5. TS will take you to a private conversation with Cthulhu (and display a new notification again)
6. Go to conversations list and see that the message was indeed a group message

.gif demonstration:
![output](https://cloud.githubusercontent.com/assets/174176/7340639/86709970-ec9a-11e4-8d57-36c60502c64c.gif)

If TS unlocked everything works as expected. I.e. group message notification takes you to the group conversation.

TS 2.12.0
Stock Android 5.1
Android 4.0.4

**Comment by onny** [comment]
I hope you know that one might guess your password as seen in the GIF?!

**Comment by agrajaghh** [comment]
I'm pretty sure he knows that this password he stole from snowden isn't safe ;)

**Comment by 2-4601** [comment]
Yes, the Snowden password isn't safe but _this goes to eleven!_

**Comment by krngrvr09** [comment]
Hey, I have been wanting to contribute to open source for a long time, and I dont have much idea about cryptography but I am comfortable with android development. Can I take a stab at this issue? Thanks. :) If someone is already working on it, can you point me to the one I can work on.

**Comment by agrajaghh** [comment]
@krngrvr09 I don't know if there is already someone working on this. If you're looking for some "easy" issues to fix you could have a look at: https://github.com/whispersystems/textsecure/issues?q=is%3Aopen+is%3Aissue+label%3Aeasy

**Comment by moxie0** [comment]
@krngrvr09 To resolve this would require fundamentally changing the way that TextSecure handles local encryption, I'd recommend starting with something tagged "easy" as @agrajaghh suggested.

**Comment by 2-4601** [comment]
Thanks to the magnificent commit (8d9ae731ef4124dbb3900e0b62cc98199b64c783) this is issue is (at least partly) fixed as TS does not take you to the wrong conversation anymore. Now it goes to the main conversation list which is good enough for me

Won't close this myself as I don't know if there are plans to improve it further so that the notification would take you to the actual conversation.

**Comment by riyapenn** [comment]
Is this still an issue?

**Comment by 2-4601** [comment]
No. It seems to go straight to the appropriate group now (3.0.3). (Though some times the notifications does not clear but that's probably worth another issue).
