### ISSUE TITLE
How do I downgrade back to v2.6.0 that has SMS Encryption enabled ?

### ISSUE THREAD

**Issue by textsecure** [WhisperSystems/TextSecure#3067]
Hi all,

I have been using TextSecure since the beginning

I stupidly upgraded today to the latest version (2.12) and realized that you removed SMS Encryption

I have no interest to use TextSecure for IM as it is unstable

How do I downgrade from 2.12 to the previous version I was using 2.6 or earlier ??

Thanks

**Comment by textsecure** [comment]
Moxie why did you close this thread ???

As a long time user of Text Secure, where else am I supposed to get an answer to the above 2 questions ?

**Comment by agrajaghh** [comment]
look at https://whispersystems.org/blog/goodbye-encrypted-sms/

**Comment by moxie0** [comment]
This is an issue tracker, not a support forum.  Encrypted SMS is no longer supported.
