### ISSUE TITLE
Texts that fail to be sent should automatically resend instead of failing permanently

### ISSUE THREAD

**Issue by Thunderpig72** [WhisperSystems/TextSecure#3068]
Hello. I wish that messages that fail to be sent because of connection problems should be resent automatically once the phone regains reception. As it is now you get a whiny little red box telling you to manually resend the message if you want. Why not make it automatic?

Here's an example:
1. I step into an underground supermarket.
2. My phone can't reach the operator.
3. I send a text message.
4. The message fails to be sent.
5. I have to resend it.

Here's what I feel should happen:
1. I step into an underground supermarket.
2. My phone can't reach the operator.
3. I send a text message.
4. The message fails to be sent.
5. The message is automatically resent when I step outside of the supermarket.

**Comment by rhodey** [comment]
related... #2098 & #2384

**Comment by achedeuzot** [comment]
+1 !

**Comment by 2-4601** [comment]
How is this handled in other popular messengers?
Hangouts, with 1 billion (forced?) downloads, seems to work like TextSecure. I.e. the user has to manually resend messages.

**Comment by Mihahn** [comment]
@2-4601 I guess WhatsApp automatically resends messages when the connection is available again. Until then, a little clock indicates it's waiting for a connection to be able to send the message...

**Comment by Thunderpig72** [comment]
Hangouts works just like TextSecure. Telegram on the other hand works in the "proper" way. Last time I used Viber it used the Hangouts way of doing it. No idea about WhatsApp though.

**Comment by derNarr** [comment]
Even if the message is resend later, **I would prefer to get a notification**, when connectivity should be there (not in airplane mode), but it nevertheless fails to send the message.

Sometimes it happens that my phone has connectivity, but is stuck in some weird state, where the internet access is blocked somehow. When I get the notification that the message could not be delivered I can fix the problem (i. e. reboot the phone) and resend the message. If it would fail silently and resend after connectivity is back, I would not recognize that it failed in the first place (except when I check manually).

**Comment by moxie0** [comment]
Should hopefully be fixed with 0b20e99cd261e64fb49cf58b6beeea5616ea4e53

**Comment by Dyras** [comment]
@moxie0 Nope, it isn't 
https://gist.github.com/anonymous/f054bf27479562fb83d8

**Comment by moxie0** [comment]
@Dyras What was the network situation that caused this?

**Comment by Dyras** [comment]
@moxie0 Here's what I did
Step inside McDonald's
Connect to their WiFi WITHOUT "logging in"/accepting their license crap
Write a message
Wait 15-20 seconds

Then the app whines about the message not being delivered.

**Comment by moxie0** [comment]
I see, yeah, there's not really anything we can do about that case.  Newer versions of Android handle that appropriately, but KK will happily notify us that we have a good network connection.

**Comment by Dyras** [comment]
@moxie0 So... Can't you do it the WhatsApp/Telegram way? Just take a short break with the message sending, then try again? You should at the very least make it easier to resend the messages.
