### ISSUE TITLE
What is the official MD5 Checksum for the last SMS Encrypted binary v2.6.4 ?

### ISSUE THREAD

**Issue by textsecure** [WhisperSystems/TextSecure#3069]
What is the official MD5 Checksum for the last SMS Encrypted version of the TextSecure APK Binary v2.6.4 ?

**Comment by mcginty** [comment]
The APKs in the play store are signed by us for integrity verification, we don't do any official checksums of the builds. Please keep github issues to bugs and feature requests with the client.
