### ISSUE TITLE
message emailed to <phone_num>@vtext.com gets truncated

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#3071]
In the past I have emailed myphone#@vtext.com and received it as a text in TextSecure sucessfully.  Now it seems to be getting truncated.  Tested with a couple emails and same result.
TS 2.12.0
Android 4.4.2 (stock ROM, no root, no titanium backup)
Samsung Galaxy S4

Send the following text as a plaintext email to your_phone_num@vtext.com and note that you don't even get all of the first rule! :)  Maybe this even applies to long sms?

Beginner pilot rules: 
1. The propeller is just a big fan made to cool down the pilot in the cockpit. When it stops, you can see the pilot start sweating excessively. 
2. You don't have to take off, but landing is mandatory. 
3. Pushing forward on the flight stick makes the earth look bigger, pulling makes it look smaller. If you pull too much or too long however, it will look bigger yet again. 
4. Flying is safe as long as you don't crash. 
5. It's better to wish you were flying than to wish you were on the ground. 
6. A good landing is a landing in which everyone walks away. 
7. Besides affecting apples, gravity also affects planes.

**Comment by rhodey** [comment]
@jeremymasters I tried reproducing this with a Verizon friend, the `@vtext` email gateway, and the :airplane: instructions your provided, but wasn't able to get anything through the email gateway-- kept giving me `550 - Requested action not taken: no such user here`.

can you try to reproduce this using a different SMS application and the email gateway? very little has changed in our SMS receive path lately. thanks!

**Comment by rhodey** [comment]
oh! also, a character count of exactly how many characters of the SMS get through would be super helpful also, or even the truncated result.

**Comment by jeremymasters** [comment]
(test subject) Beginner pilot rules: 
1. The propeller is just a big fan made to cool down the pilot in the cockpit. When it stops, you can see the pil

**Comment by jeremymasters** [comment]
Above is the text I receive.  The (test subject) is from putting "test subject" in the subject of the email...minus the double-quotes.  I emailed this from my desktop using outlook 2010.

**Comment by rhodey** [comment]
@jeremymasters can you verify that messages are not truncated like this when using a different SMS app? I think that's the last piece of info we'd need to confidently label this a TextSecure-specific bug. my thought is that it's possible this is a limit imposed by the SMS-email gateway.

**Comment by jeremymasters** [comment]
I earn the idiot award.  This happens with stock app.  Note to self: When testing incoming non-TS user issues, test stock SMS app.  Closing.

**Comment by rhodey** [comment]
no worries @jeremymasters :) submitting issue reports is how TS gets better
