### ISSUE TITLE
The invite link "http://sgnl.link/1IvurmD" does not exist

### ISSUE THREAD

**Issue by vitoller** [WhisperSystems/TextSecure#3073]
when sending an invite, textsecure inserts a link to "http://sgnl.link/1IvurmD".
When opening the page however, I get a "Something is wrong here" message.

**Comment by McLoo** [comment]
The link works for me. Right from your issue... 
Temporary downtime maybe?

**Comment by vitoller** [comment]
Now it does work for me as well. It did not work an hour ago.
If I can reproduce it, I will reopen the issue.
