### ISSUE TITLE
SMS fallback

### ISSUE THREAD

**Issue by TurkeyMan** [WhisperSystems/TextSecure#3074]
I have read some closed/locked issues on this matter already, but I just want to add an extra push.
There was argument that TextSecure is to be a secure messaging facility, and fallback to insecure communication is unacceptable.

I want to argue that this position is unreasonable, and undermines the effort to get the general public onto secure platforms.
The general public has practically zero concern about this; but I do. If text secure refuses to fallback to SMS, then nobody I want to communicate will install the app. The inconvenience of not being able to communicate when out of 3G range (I'm in Australia, we barely have internet in this country), or have exhausted your monthly data allowance (again, I'm in Australia), is more than anyone should have to tolerate.

There is only one reasonable solution to this as I see it:
TextSecure should attempt to send a message securely. If it can't, a popup informs the user it failed to send, and the user has an option to retry later, or send insecurely (via SMS) immediately.
There should also be a "remember my choice" checkbox, and an option in the settings.

I have people refusing to install, and uninstalling the app.

TextSecure is the only decent, otherwise user-friendly, secure messaging app I have managed to find. All others are borked in various critical ways.

Please consider the importance of this app _actually being used_ by an exponential explosion of users; 99% of whom don't give a damn whether it's secure, but must be convinced to use it by the 1% of people who do.

**Comment by moxie0** [comment]
this is an issue tracker, not a discussion forum
