### ISSUE TITLE
Emojis differ from preview/keyboard

### ISSUE THREAD

**Issue by Lem** [WhisperSystems/TextSecure#3078]
##### Versions
* Android: 5.0.2 (CM 12-20150414-NIGHTLY-bacon)
* Device: A0001
* TextSecure: 2.12.0

##### Description
I noticed that some Emojis on the keyboard are different than the one send. 
<br>For example the attached image: the mouth of the devil was flipped and the other one changed his eyes. But there are some more.

Is there a chance that the emoji-set will be updated to show the same version in the message and the keyboard-preview?
![screenshot_2015-04-28-19-48-24](https://cloud.githubusercontent.com/assets/199086/7377368/4393776a-ede6-11e4-9b66-582128ac628d.png)

**Comment by agrajaghh** [comment]
looks like dupe of #2936

**Comment by Lem** [comment]
Thanks. Didn't see this one, was searchung with filter label:ux
