### ISSUE TITLE
How to restore SMS encryption?

### ISSUE THREAD

**Issue by d33tah** [WhisperSystems/TextSecure#3079]
Hello,

I just installed latest TextSecure and if I knew what it does, I would backup the APK file. Unfortunately, I didn't and the change involving the removal of SMS encryption feature was not mentioned in the changelog, so I unwillingly removed a feature from my phone that I really care about. Is there a way to restore the SMS encryption, either by installing an older APK or by changing that using some hidden option? I evaluated the risks and while being a security conscious man, I would prefer to use outdated software in this case than no encryption at all - encryption using the internet is unfortunately out of option for me.

I really hope that somebody could help me, otherwise I would have to compile textsecure myself, which doesn't seem trivial. I am willing to donate to the project if this feature can be restored on my phone.

Jacek

**Comment by johanw666** [comment]
You can downgrade to version 2.6.4 (apk can be downloaded on several places or you can build it from source) or you can install SMSSecure alongside TextSecure. SMSsecure is a fork of TextSecure with only sms/mms encryption so they be used together.

**Comment by d33tah** [comment]
Thanks for the SMSSecure hint! They're even in F-Droid.

**Comment by d33tah** [comment]
Correction: I can't see if it was included in the changelog because the Google Play list only contains updates back to 2.9.1. I also found the justification for the removal here: https://whispersystems.org/blog/goodbye-encrypted-sms/

**Comment by moxie0** [comment]
To be clear we don't have anything to do with SMSSecure.
