### ISSUE TITLE
Everyone who has my phone number can figure out that I use textsecure

### ISSUE THREAD

**Issue by Noir-** [WhisperSystems/TextSecure#3080]
We live in times where even the fact that somebody's using encryption raises suspicions. In my eyes a first suspicious sign would be a telephone number which is stored in a database of a messenger like TextSecure. Gathering those is a low hanging fruit because we all know that the structure of telephone numbers is very deterministic and entropy of those is additionally reduced by TextSecure. Another reason is that some people just don't like that everyone who has ones telephone number knows that TextSecure is used.

I suggest to give more control over that. The easiest solution I can imagine is that there's a "cloak" mode:

Alice uses TextSecure. However, she doesn't want that Mallory knows that Alice is using that App so Alice activates the cloak mode. In this mode, every time Mallory searches for intersections on the server Alices token is ignored.

To get in touch with a cloaked user, I suggest the following approach:

Bob wants to contact Alice. Alice is still in cloaking mode. Bob can select Alice from his phone contacts for a contact request. Alice receives this request. If she acknowledges, Bob get notified that Alice is available. If Alice ignores the request, nothing happens.

Other, less convenient solutions I thought of:
* It's not possible that Mallory can see Alice in the intersection request if Alice doesn't have Mallory in her contact list. (Here the server whould have to know and store contact link information which is bad.)
* There's a kind of challenge-response technique via another channel than TextSecure which allows Bob to add Alice to the contacts. (More complicated and requires a second channel)

What do you think?

Greetings,
Noir

**Comment by agrajaghh** [comment]
related to #1085

**Comment by 2-4601** [comment]
Since this is a discussion on contact discovery and not specifically about an issue with the TextSecure Android client there's a high probability that this will be closed soon. For these kind of subjects [the mailing list](https://lists.riseup.net/www/info/whispersystems) is more suitable.

> suspicious sign would be a telephone number which is stored in a database of a messenger like TextSecure

Is using WhatsApp also suspicious? :)
All WhatsApp Android text conversations are axolotlized.

**Comment by moxie0** [comment]
Thanks but we're not going to do this.
