### ISSUE TITLE
mms issue

### ISSUE THREAD

**Issue by fabianbmnn** [WhisperSystems/TextSecure#3082]
I receive the same message over and over again. Even deleting won't do the trick, i receive it again each day. The same issue also happend when someone sends an e-card from iphone.

**Comment by volcano99** [comment]
I think it would be useful if you posted a debug log after receiving that message (not that I'd be able to help, but that's standard procedure if you want to get the help of any developer here)

**Comment by fabianbmnn** [comment]
Log:
https://gist.github.com/c52e71c72768d057974b

**Comment by fabianbmnn** [comment]
Log:
https://gist.github.com/c52e71c72768d057974b
