### ISSUE TITLE
Can't send messages when on the same wireless

### ISSUE THREAD

**Issue by eltismerino** [WhisperSystems/TextSecure#3087]
Hey,

my girlfriend and I have been using TextSecure for ages now. Somehow, with her HTC One M8 she can't send me messages when our phones are in our WLAN at home - her messages instantly get a red exclamation mark. Mine work and she receives them perfectly.

When the WiFi on her phone is turned off, it continues to work again.

Anyone ever experienced this before?

**Comment by agrajaghh** [comment]
are you talking about MMS , SMS or push messages?

**Comment by eltismerino** [comment]
Push messages.

**Comment by mcginty** [comment]
@eltismerino we'll need a debug log from your girlfriend's phone to figure out what exactly's happening

**Comment by eltismerino** [comment]
Here: https://gist.github.com/anonymous/6366907fc49e6988a0ea
I wasn't able to post this when the WLAN was on, either.

**Comment by moxie0** [comment]
Looks like some kind of problem with the device or wifi configuration.  Either it's got a proxy server configured, some weird vpn thing, or dns problems.  Our servers don't speak IPv6, so if your network is v6 only without some kind of bridge configured, it won't work.

**Comment by eltismerino** [comment]
Hmm it has IPv6 but not enforced. I'll keep trying and post back.
