### ISSUE TITLE
NewConversationActivity contact filter behaves differently on different phones

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3091]
~~[method source](https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/contacts/ContactsDatabase.java#L135)~~

~~given the above fuzzy filter ` "%" + filter + "%"` you would expect that for the string `Axolotl` the following filters would match: [`Axo`, `olo`, `otl`]. however, on certain phones only the first (`Axo`) matches. incomplete list of affected devices confirmed via TestObject:~~

EDIT: I think the root of this problem is actually in `ContactsDatabase.queryAndroidDb()`, not `ContactsDatabase.queryLocalDb()`. Give the string `Axolotl` and the filters [`Axo`, `olo`, `otl`], the following devices will only match on (`Axo`) when expected to match on all 3.

Motorola DROID X2, Samsung I9070, HTC One SV, Fairphone, Wiko Rainbow, HTC One S.

**Comment by brumsoel** [comment]
I can confirm this on a Fairphone, but only for non-Textsecure contacts. If the contact is a Textsecure user, filtering somehow works as expected.

**Comment by rhodey** [comment]
thanks for the info @brumsoel :) this issue makes more sense now because when filtering TextSecure contacts we use our own custom filter, but when filtering non-TextSecure contacts we use some Android APIs which I guess have been modified by certain ROMs or change behavior between different API versions.

**Comment by rhodey** [comment]
I wouldn't be opposed to changing our filter to work like the Android filter, ie: `filter%` vs `%filter%`, whatever happens though our filter and Android's filter should at least agree.

**Comment by McLoo** [comment]
Looks like #2378

**Comment by brumsoel** [comment]
I can confirm this exact same behaviour (filtering works as expected for TS contacts, but not for others) on a `Sony Xperia SP` (Stock Android 4.3 ROM). Are you absolutely certain it's device-specific?

**Comment by rhodey** [comment]
nice catch @McLoo :D I had forgotten about that issue report. last time I looked over #2378 I had assumed the search was starts with for all devices, now we have information that it is selectively starts with. I'll close this issue and reincorporate it into #2378.
