### ISSUE TITLE
Use circle + initial(s) as contact icon

### ISSUE THREAD

**Issue by aibaraiduas** [WhisperSystems/TextSecure#3093]
Currently the icons of all contacts look the same: a gray smiley face (unless a profile picture has been set up in the contacts app I assume—I don't actually have any so I'm not sure). It would be nice if instead the icon was a circle with the initial(s) of the person being messaged, as seen in the contacts app itself, as well as other sms clients. Perhaps this feature is already planned, since Signal on iOS uses it.

**Comment by volcano99** [comment]
I suggested the same thing in #916 . I think it would be enough to be able to set our own profile pictures, that would solve the whole problem. I don't know how other messengers handle missing profile pics, but it looks like once the users can set their own no one leaves theirs blank.

**Comment by jeremymasters** [comment]
Another idea would be something like is already in the conversation if there's not picture.  Even that first letter of their first name would be visually very helpful.

**Comment by aibaraiduas** [comment]
This is about the default for contacts that have no picture assigned to them, so the user specifically doesn't have to manually select pictures for everyone. A simple colored (or even grey) circle with their initials would make for easier idenitfication, as jeremymasters pointed out. Other messenging apps do this already (e.g. Textra), as do email applications (e.g. K-9 Mail and Gmail). 

Manually assigning pictures, as volcano99 suggested, is a separate issue in my mind (which you can already do in the contacts app anyhow, so the same picture is used system-wide).

**Comment by moxie0** [comment]
41cad291f9ce422f4d26fd536cdfbb8b80fb88a5
