### ISSUE TITLE
crash while scrolling contact list

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#3097]
You're gonna think my phone is cursed for all the crashes I get... log: https://gist.github.com/92ff902383cb1cd71286

**Comment by moxie0** [comment]
they're all out of memory exceptions, you seem to have a very low-memory device

**Comment by volcano99** [comment]
I highly doubt it's a problem with the device, all my other apps work really well :/

**Comment by mcginty** [comment]
Without more info, this isn't actionable beyond simply reducing our overall memory usage. @volcano99 if you're up for it, a heap dump would be the next step for identifying why your TextSecure is hogging so much memory. See https://developer.android.com/tools/debugging/debugging-memory.html#HeapDump for instructions on how to obtain it.

**Comment by volcano99** [comment]
Since 2.14.1 I haven't had that many crashes, though I've also been using textsecure not as often (and I haven't been sending many pictures which is something that made my phone crash like all the time). If I'll start having frequent crashes again I will try to do as you suggested!

**Comment by mcginty** [comment]
Thanks!
