### ISSUE TITLE
Problem...

### ISSUE THREAD

**Issue by OldSkoolOG** [WhisperSystems/TextSecure#3100]
One of my contacts who used TextSecure & I was synced with, switched from an Android to a  Windows phone after breaking it. But the contacts number still comes up as connected/encrypted with my number. I've had other contacts switch phones & their number hasn't stayed connected. So I'm wondering, what do I need to do to fix this issue...
Thanks

**Comment by yzrmn** [comment]
I think he needs to unregister from the server:

- Easy: Your contact could swap your SIM into an android phone with TextSecure and uncheck 'TextSecure messages' under 'Advanced'
- Expert: Or try this script: https://github.com/daveio/whisperpush-unregister (you need to set the right hostname, NOT the whisperpush hostname)

Also you can always send your messages 'insercure'.

**Comment by Mihahn** [comment]
To unregister from TextSecure push messages, use [URL=https://whispersystems.org/textsecure/unregister/]this[/URL] link.

**Comment by OldSkoolOG** [comment]
thanks for your help!
