### ISSUE TITLE
TS crashes when sending or recieciving SMS

### ISSUE THREAD

**Issue by dagaz** [WhisperSystems/TextSecure#3109]
My TS crashes everytime when i send or recieve an uncrypted SMS. Then it keeps crashing when I enter my password.

Same behaviour when I delete all data from the app (via settings) and start over with a "clean" app. So it seems it has nothing to do with previous messages.

The only solution to open TS again without crashing is to restore a Titanium Backup.

System: Oneplus One (bacon) with Cyanogenmod 12.1-20150505-nightly (Android 5.1.1). The Bug also affeced the previous 3 nighlies.

**Comment by McLoo** [comment]
You need to post a debug log after such a crash.
From the passphrase prompt 3-dot-menu or from settings advanced

**Comment by dagaz** [comment]
Did so. Should i paste it here, too or is it enough if I posted it with the app?

**Comment by dagaz** [comment]
its this one: https://gist.github.com/anonymous/fb1d032571b0e4a30575

**Comment by agrajaghh** [comment]
Are you using Xprivacy or do you somehow limit the app permissions?
````
E/AndroidRuntime( 3459): FATAL EXCEPTION: Thread-360
E/AndroidRuntime( 3459): Process: org.thoughtcrime.securesms, PID: 3459
E/AndroidRuntime( 3459): java.lang.SecurityException: Neither user 10098 nor current process has android.permission.ACCESS_COARSE_LOCATION.
E/AndroidRuntime( 3459): 	at android.os.Parcel.readException(Parcel.java:1546)
E/AndroidRuntime( 3459): 	at android.os.Parcel.readException(Parcel.java:1499)
E/AndroidRuntime( 3459): 	at com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy.listenForSubscriber(ITelephonyRegistry.java:558)
E/AndroidRuntime( 3459): 	at android.telephony.TelephonyManager.listen(TelephonyManager.java:2517)
E/AndroidRuntime( 3459): 	at org.thoughtcrime.securesms.sms.TelephonyServiceState$ListenThread.run(TelephonyServiceState.java:35)
E/AndroidRuntime( 3459): Error reporting crash
E/AndroidRuntime( 3459): android.os.DeadObjectException
E/AndroidRuntime( 3459): 	at android.os.BinderProxy.transactNative(Native Method)
E/AndroidRuntime( 3459): 	at android.os.BinderProxy.transact(Binder.java:496)
E/AndroidRuntime( 3459): 	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4200)
E/AndroidRuntime( 3459): 	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:89)
E/AndroidRuntime( 3459): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
E/AndroidRuntime( 3459): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
````

**Comment by johanw666** [comment]
AFAIK TextSecure doesn't ask for permission ACCESS_COARSE_LOCATION.

**Comment by dagaz** [comment]
OK, I think I got the reason for the crash: an outdated version of LBE Security Master with root-Access to manage app-permissions.

If LBE is updated everything runs fine again. TS was a "trusted" app for LBE, but none the less LBE seems to be responisble for the crashes.

I mark the issue as closed, because it is solved.

**Comment by McLoo** [comment]
for the record:
- related to #2561 
- ACCESS_COARSE_LOCATION is accessed when sending SMS
