### ISSUE TITLE
beta crashes when unlicking with password

### ISSUE THREAD

**Issue by vanitasvitae** [WhisperSystems/TextSecure#3133]
Hi! Since tge beta 2.14.0 the app crashes when I try to unlock with my password.
Protocoll: https://gist.github.com/2eba0c2c8fa7dd47d65c

**Comment by volcano99** [comment]
Wait for 2.14.1, it's been fixed

**Comment by vanitasvitae** [comment]
Okay. When will 2.14.1 be released? I tried to install 2.13 again, but niw I do not get an sms during registration :/ but thats another issue.

**Comment by volcano99** [comment]
I just got 2.14.1, so you should get it too soon. Try deleting data from the play store app and see if you get the update

**Comment by vanitasvitae** [comment]
Ok, the update fixed the problem for me :)
