### ISSUE TITLE
Cursor not shown when typing a message

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#3134]
You know the little pulsing bar that appears when writing something in a text box? (I'm sure i thas a name but I can't think of a better description right now). Since 2.14.1 (probably 2.14) it has disappeared from textsecure. This obviously makes it hard and uncomfortable to write messages..
I like textsecure, and I appreciate the effort you're putting into it, really. But do you even test the app before releasing updates? Missing commas that screw the phones and make us lose messages, huge usability problems that would've taken 10 seconds to notice... I mean... of course it's human to forget a comma or introduce bugs, we all know it. The problem is that testing should be considered *fundamental*, even when you have beta testers. Beta testers are supposed to find smaller problems, not sacrifice their product for the sake of bugs. That's what the developers should be doing.
Apologies if it sounds rude, and thanks again.

**Comment by 2-4601** [comment]
@volcano99 Sorry to hear about your lost messages.
The betas have so far been like stable releases for me until the _'fucking missing comma'_ bug :D
But something like that was inevitable. And after all there is a warning in the readme about betas:

> If you're interested in a life of peace and tranquility, stick with the standard releases.

But hopefully you'll stay and continue reporting bugs as you have done so far and got many issues fixed :) 

- - - - -

But back to the cursor issue. When I open a conversation I will get a missing cursor on average 5% of the cases with my Nexus 4. And when the cursor is missing it comes back immediately after I tap on the input box to open the keyboard.

I run some tests where I open every conversation in the main conversation list, count if cursor shows or not, then tap Android's back button, and repeat ad nauseam (or max 100 times).

**Nexus 4, Android 5.1, TS 2.14.1**
```
priv. conv. 1: 0/50 (ok after 50 tries nothing, i give up)
priv. conv. 2: 3/30
priv. conv. 3: 5/30
priv. conv. 4: 2/30
group conv. 1: 1/30
priv. conv. 5: 2/30
priv. conv. 6: 0/50
```
Result: in 13/250 I will get a missing cursor. The conversation that got 0% do not really differ from the others.


**Huawei U8880, Android 4.0.4, TS 2.14.1**
```
priv. conv. 1: 0/100
```
Does not seem to happen on 4.0.4. But I had just one conversation.

**Comment by volcano99** [comment]
If I were interested in a life of peace and tranquility I wouldn't be used textsecure in the first place..

> And when the cursor is missing it comes back immediately after I tap on the input box to open the keyboard.
But that's the point. It never appears whatever I tap or write

**Comment by 2-4601** [comment]
Here's [a debug log](https://gist.github.com/002810e2f0f66373fe91) after:
- Rebooting phone
- opening TS
- switching between the conversation list and a specific conversation until the cursor disappeared (took 16 tries)

Not sure if this is the relevant line:
`W/art     ( 3875): Before Android 4.1, method int android.support.v7.internal.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView`

**Comment by moxie0** [comment]
@volcano99 If you want a stable release, don't subscribe to the betas. If you have to add a disclaimer to your comment about sounding rude, you're being rude.

**Comment by volcano99** [comment]
I noticed that the problem is not present when using the dark theme, so maybe the cursor is there, but it's white instead of black

**Comment by 2-4601** [comment]
@volcano99 Nice find. On my 4.0.4 device with light theme there appears to be no cursor at all. And indeed on the dark theme the cursor is white and always visible.

On Lollipop the cursor is light blue which explains why it's visible on both themes. Except on the cases when it's not - as described above. But that is likely to be a completely different issue.

**Comment by McLoo** [comment]
Jipp, snow white cursor on light theme. Noticed when using the magnify function of the text

**Comment by johanw666** [comment]
I'm not very familiar with Android development, but searching for "text cursor color" I find this: http://stackoverflow.com/questions/7238450/set-edittext-cursor-color, where is pointed to the variable android:textCursorDrawable. Searching for this I find this referenced in only one place in the source, in the build tools in \build\intermediates\exploded-aar\com.android.support\appcompat-v7\22.1.1\res\values-v12\values.xml. The build tools have recently been upgraded from 21.0.3 to 22.1.1; in 21.0.3 there are no references to android:textCursorDrawable. Maybe the bug is related to this upgrade?

**Comment by mcginty** [comment]
Thanks for the research, @johanw666. Looks like it may be as simple as making our classes that extend EditText extend AppCompatEditText instead.

**Comment by johanw666** [comment]
In tried adding a line in themes.xml in the TextSecure.LightTheme section with
<item name="android:textCursorDrawable">@color/textsecure_primary_dark</item>
but that didn't work (it only gave a warning that this required API 12 while the manifest claimes API9 compatibility).

**Comment by johanw666** [comment]
@mcginty: that worked. Somehow I am unable to upload pull requests, but I changed /src/org/thoughtcrime/securesms/components/ComposeText.java

```java
import android.support.v7.widget.AppCompatEditText;
...
public class ComposeText extends AppCompatEditText {
```
I commented out the constructor with 4 arguments since AppCompatEditText does not have such a constructor. And the cursor is blinking again.
