### ISSUE TITLE
Possible break in Android <= 2.3.3

### ISSUE THREAD

**Issue by BastienLQ** [WhisperSystems/TextSecure#3140]
Since 41cad291f9ce422f4d26fd536cdfbb8b80fb88a5, TS uses `com.amulyakhare.textdrawable` which [requires api](https://github.com/amulyakhare/TextDrawable/blob/master/library/build.gradle#L8) >= 10, but current `minSdkVersion` value is 9.

**Comment by mcginty** [comment]
according to @moxie0, it doesn't actually use any APIs that don't exist in 9

**Comment by agrajaghh** [comment]
API 9 isn't listed there anymore since July 2013:
http://developer.android.com/about/dashboards/index.html

So since almost two years there are less than 0.1% people using version 2.3 - 2.3.2.
I guess it wouldn't be a problem to increase `minSdkVersion` to API 10 anyway...
