### ISSUE TITLE
Thumbnails disappear when scrolling in 'All images' view

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3142]
When you scroll in a certain way in the 'All images' gallery picture thumbnails at the top and bottom boundaries disappear.

Possibly related #2985 

I have only encountered this today so I guess this has been introduced fairly recently (Glide issue)?

1. Open 'All images' from a conversation that has so many of your precious photos that you need to scroll to see them all
2. Scroll down and pull up before new images are fully visible (do this move gently, don't jerk like a machine)
3. Continue scrolling down to expose new precious photos
4. Alternate between steps 2 and 3 as long as you wish (or until your lifespan expires)
5. When you do this the two leftmost boundary thumbnails will disappear like tears in the rain

.gif demonstration:
![blade runner](https://cloud.githubusercontent.com/assets/174176/7548067/5b82c9ae-f604-11e4-90ff-57ab10cd7669.gif)

TS 2.14.1, stock andy 5.1, Nexus-4 model (with [artificial snake scale back skin of finest quality](https://en.wikipedia.org/wiki/Nexus_4#/media/File:LG_Nexus_4_back_glass.jpg))

Debug log: https://gist.github.com/anonymous/2a14febcb19e54f344ca

Also happens with my old 4.0.4 skin-job model (which should be retired already).

**Comment by moxie0** [comment]
@mcginty I added this to 2.15 since it looks like a regression

**Comment by mcginty** [comment]
Looks like a Glide bug when used with RecyclerView. The RecyclerView will detach views without recycling them, Glide seems like it may be assuming detachment means recycling, and then when reattached the image will be gone.
