### ISSUE TITLE
Sent/Received Time

### ISSUE THREAD

**Issue by skulumani** [WhisperSystems/TextSecure#3143]
I have noticed that the sent time is after the received time within the details of a message. 

Are these values swapped (which would be an easy fix) or is something more complicated going on?

This seems related to #2314 which requests a display of the sent time. 

Thanks for the hard work

Receiver Device: Moto X 1st gen with stock 4.4.4, TextSecure 2.14.1
Sender Device: Samsung S5 with stock 5.1, latest stable TextSecure version

Debug Log: https://gist.github.com/5e15d31086c436cae69c

![time](https://cloud.githubusercontent.com/assets/5266022/7548256/7f1c0b10-f5c7-11e4-8822-a9592dc2cd85.png)

**Comment by volcano99** [comment]
Could this be related to #2964 ?

**Comment by brumsoel** [comment]
That's due to the sender's and the receiver's clocks not being in sync.

**Comment by volcano99** [comment]
How do you know? Could you comment in the other thread?

**Comment by brumsoel** [comment]
I'm talking about @skulumani's screenshot.
