### ISSUE TITLE
plus sign as initial, if number in contacts without name

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3145]
minor i guess:
I have a international number stored in contacts, but not assigned any name.
Therefore the contact's name is resolved as the number +123456
and therefore the initial for that contact is the plus sign.

**Comment by rhodey** [comment]
@McLoo I think we're using `#` as a avatar for all conversations where the recipient is not in contacts, are you suggesting we do the same for contacts with no name? that kinda change would make most sense to me.

**Comment by moxie0** [comment]
@rhodey already done

**Comment by McLoo** [comment]
Fixed with 833fcd1
Thanks
