### ISSUE TITLE
Feature: Add contact from number in "Group members" view

### ISSUE THREAD

**Issue by effigies** [WhisperSystems/TextSecure#3151]
In a group message (at least unsecured, not sure if true in secure chats), the "Group members" view shows a list of contacts and unknown numbers involved in the message. Each entry is clickable, and closes the view. I would think the expected behavior on unknown numbers should be to add a number to contacts, similar to tapping their avatar in a message.

Assuming that person ever actually participates in the thread, it's a somewhat moot point, as you'll be able to tap the avatar, but I've had situations where a group member doesn't participate, so the shortcut of adding a contact isn't available.

For existing contacts, I would think opening their contact information would be a good default, which would be consistent with using the same behavior as clicking their avatars in the conversation view.

Device: Samsung Galaxy S5, Android 5.0 (stock rom), TextSecure 2.13.0
App state: Push registered, SMS enabled incoming/outgoing

**Comment by agrajaghh** [comment]
should have been fixed with https://github.com/WhisperSystems/TextSecure/commit/417a4b86b6fbddeee885f2e1386fe610d9f3af46
