### ISSUE TITLE
send via sms if no internet connection

### ISSUE THREAD

**Issue by rene0720** [WhisperSystems/TextSecure#3155]
Hello, 

I've the newest version 2.13.0 but when I want to send a TS contact a SMS I always have to choose manual send via insecure SMS.
Since some version it only supports encrypted messages via Internet but there is no sms encryption anymore, is there any reason for?

Regards, 
Rene

**Comment by 5boro** [comment]
Here is the official answer : https://whispersystems.org/blog/goodbye-encrypted-sms/
But you can look at [SMSSecure](https://smssecure.org/), it's a fork dedicated to encrypted SMS.
