### ISSUE TITLE
MMS not working- need to be able to set MCC/MNC. 

### ISSUE THREAD

**Issue by DiogenesT** [WhisperSystems/TextSecure#3156]
Carrier Republic Wireless needs a custom MCC & MNC for working MMS on third party apps.
From https://community.republicwireless.com/docs/DOC-1948?forceNoRedirect=true#jive_content_id_Send_an_MMS_using_Hangouts

Name: Enter your desired name.
MMSC: Should be set to http://localhost
MMS proxy: Should be set to 127.0.0.1
MMS port: Should be set to 18181
MCC: Should be set to 310
MNC: Should be set to 000

**Comment by skulumani** [comment]
The developers don't support republic wireless. At least they didn't when I asked earlier.

I use it by not having it be the default app. Then use the stock app for SMS/MMS. 

MMS is already difficult and even more convoluted on RW

**Comment by mcginty** [comment]
@DiogenesT in the past, we haven't supported Republic Wireless because they break the rules. That said, can you post a debug log after trying to send the message? Did you try manually setting the MMSC and proxy in the manual settings and it didn't work?

**Comment by DiogenesT** [comment]
Where do I post the log? I recall there was a privacy problem with the logs some time back; has that been fixed?

Looking at the log, it appears that yes, MCC/MNC 310000 _is being used_; so my attempt at sending MMS by default (fresh install), then with manual proxy settings, then with manual proxy and WiFi calling option enabled all failed in spite of that. So the posting of logs may be unnecessary, since what I was requesting as a possible solution appears to already be in operation; RW's way about things just breaks it. AFAIK, the messaging app and hangouts are the only options. Hangouts, interestingly, now works out-of-box, without any further modifications necessary. Hangouts, of course, is not preferable; I usually have the app disabled.

**Comment by mcginty** [comment]
@DiogenesT we use Gist. If the privacy problem you're referring to is the inclusion of phone numbers in the logs, then yes, if you use the built in log submission in-app it will redact phone numbers (saving the last two digits to identify whether two numbers are the same).

If you're concerned, feel free to grab the logs yourself and paste just the area with the MMS exceptions yourself.

**Comment by skulumani** [comment]
Here's my debug log.

I noticed an incorrect IP address for the APN. Is this normal?

https://gist.github.com/a2d34c4b70c315ea628f

**Comment by mcginty** [comment]
The APN you see in the logs is the APN we *would* be trying without the override. It looks like in the logs it tries to connect to localhost at the right port and is being refused.

**Comment by skulumani** [comment]
I wouldn't spend much time on it. I'm sure whatever RW does to work is
beyond the control of TextSecure.

It would be great if we could get a developer from Republic Wireless to
chime in.

**Comment by mcginty** [comment]
Yeah, sorry. I can't do much about them refusing our HTTP connections - it seems like they do some undocumented magic that isn't what any other carrier does. Maybe get in touch with them and let them know they should play nice :).
