### ISSUE TITLE
Tablet Support - Google Play Restrictions

### ISSUE THREAD

**Issue by Manouchehri** [WhisperSystems/TextSecure#3161]
I just sideloaded TextSecure's APK and it seems to be working on my Nexus 7 (2013/Razor) with WiFi only. I confirmed with another number that I own (probably even IPKall would work) since there's no SMS/MMS capabilities. I didn't run into any of the issues mentioned in #614.

If nobody has any objections, why not remove the no tablets limitation on Google Play? Maybe @moxie0 or whoever controls the Play Store app could chime in?

**Comment by moxie0** [comment]
duplicate of #614
