### ISSUE TITLE
Unread badge on TS icon in stock launcher

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#3162]
I wonder whether the unread badge could be supported in the stock Android launcher. I am using a Motorola Moto G, Android 5.0.1.

**Comment by McLoo** [comment]
Sorry, this wont happen unless there is a official solution for this.
Current ways for doing this are unsupported hacks (with unpredictable side effects). 
Also see https://github.com/leolin310148/ShortcutBadger/issues/22

**Comment by merkste** [comment]
I see, thanks for the Info. Close.

**Comment by 2-4601** [comment]
> is there a way to close it myself?

Since you opened the issue there should be a 'Close issue' button below the text box:
![close](https://cloud.githubusercontent.com/assets/174176/7629510/cf109b0a-fa35-11e4-8804-2095dbb11411.png)

**Comment by merkste** [comment]
That was indeed obvious. I guess I wasn't logged in? =)
