### ISSUE TITLE
NewConversationActivity only shows contacts if TS is default app (on Galaxy S4)

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3164]
the contact list in `NewConversationActivity` will be empty unless TextSecure is set to be the default SMS app on Samsung Galaxy S4 devices-- or at least the one I tested. we've run into a couple issues with the contact query used in this activity such as #2378 and another mentioned by @mcginty where sometimes the query takes upwards of 5 seconds to complete. we should look into some alternatives.

**Comment by johanw666** [comment]
On my Sony Xperia Z1 Compact the list shows only other registered TextSecure users when I open this when TS is not the default  SMS app. When I make it the default SMS app I see first a list of all registered TS users and below that a list of all other contacts. Do you have othet TS users on that S4?

**Comment by rhodey** [comment]
@johanw666 the behavior you described in that first paragraph is intentional, if TextSecure is not the default SMS app on your phone then we only allow you to see contacts that have TextSecure because we will be unable to receive SMS so it makes sense to prevent the user from sending SMS. thanks for the tip though :)

**Comment by rhodey** [comment]
as of today I'm unable to reproduce this issue. when I tested this originally I had put my LG device through a lot of reinstalls and configuration changes, I suspect it was confused.
