### ISSUE TITLE
Opened from notification caused crash; now cannot access message

### ISSUE THREAD

**Issue by owenblacker** [WhisperSystems/TextSecure#3173]
I received an SMS from my boss earlier (he's an iPhone user, using the default iOS SMS client) and, for some reason, TextSecure opened from the notification but crashed afterwards, hanging on a black screen after entering my passphrase and prompting Android to ask me if I wanted to Report/Wait/Close.

I hit the app switcher button and dismissed TextSecure and tried the notification again but just got the black screen, so told Android to report the crash.

I dismissed TextSecure via the app switcher again and opened TextSecure from the app shortcut and it let me in ok, but the text message now reads, in italics:

> Received a message encrypted using an old version of TextSecure that is no longer supported. Please ask the sender to upgrade to the most recent version and resend the message.

except, as I mentioned, my boss isn't using TextSecure; he's using the default iOS SMS client.

After [whining about it on Twitter](https://twitter.com/owenblacker/status/599180779990556673), @WhisperSystems [replied](https://twitter.com/whispersystems/status/599211588202070016) asking me to open an issue with a debug log. So here I am, with a debug log at https://gist.github.com/anonymous/9111ffde3f88317b203b :sunglasses:

**Comment by moxie0** [comment]
Thanks @owenblacker, but we would have needed the debug log from the time of the incident, there's nothing in this log. I've identified what caused your initial ANR, but your received message is likely lost.
