### ISSUE TITLE
Avatar becomes smaller

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#3174]
I updated to TS 2.14.4 (from 2.13.0) last night.  At some point, some of my avatars with images became smaller.  I can't seem to reproduce it yet but I'll continue to try and post a log if I am able to repro.  Note: It never happens to the avatars that are just the initial (no image).

**Comment by moxie0** [comment]
Hey @jeremymasters you'll have to be more specific, smaller how?

**Comment by jeremymasters** [comment]
I should also note that this is in the list of conversations as well as inside the conversation threads.  Some avatars are even oval instead of round.

**Comment by moxie0** [comment]
please include a screenshot

**Comment by jeremymasters** [comment]
![avatars_small](https://cloud.githubusercontent.com/assets/4967949/7655926/4f756dda-fae4-11e4-8776-da45dbe2820e.jpg)

**Comment by moxie0** [comment]
hah yeah that looks pretty weird, thanks

**Comment by moxie0** [comment]
are the photos for those contacts really small? like were they scaled up before?

**Comment by jeremymasters** [comment]
sorry, was in a meeting.  The images before were all the same size in TS.  I never really checked what size they were as an original image.

**Comment by moxie0** [comment]
@jeremymasters I can't reproduce this, so can I send you an APK to test? send me an email at moxie.github@moxie.org and i'll get one over to you

**Comment by jeremymasters** [comment]
@moxie0 email sent.

**Comment by moxie0** [comment]
@jeremymasters Can you post a screenshot with the new APK here?

**Comment by jeremymasters** [comment]
![new_apk](https://cloud.githubusercontent.com/assets/4967949/7657800/2d679192-faf2-11e4-8744-cb6089e34a4d.jpg)

**Comment by jeremymasters** [comment]
Tested 9n my wife's phone and it fixed hers too.  Oddly enough, avatars that were fine on mine had been messed up on hers. This app fixes all of them. Thanks again.
