### ISSUE TITLE
MMS not working.

### ISSUE THREAD

**Issue by redragonx** [WhisperSystems/TextSecure#3175]
I have the same issue in this ticket #3103 on the HTC One M8. I also cannot see the MMS setting option anymore in TS running Android L.  So I cannot set my MMS settings manually, so is this a UX bug?

Carrier: VZW
Android: 5.0.1 (ViperOne M8 4.3.0)
Log: https://gist.github.com/anonymous/3a724c835e7681ab2e64

**Comment by bk10287** [comment]
Having issues with MMS as well, pictures never download.

Phone: HTC One M8
Carrier: T-Mobile
Android: 5.0.2 (LeeDroid M8 V7.3.0)

**Comment by redragonx** [comment]
Updating to 2.14 helps.
