### ISSUE TITLE
Github source code not up to date 

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#3177]
See  #3163. I build from source for some time now because I want to apply a small patch to prevent TS complaining about encrypted sms mesages I receive in another program.

**Comment by brumsoel** [comment]
If you're looking for 2.14.5, there's a branch for it:
https://github.com/WhisperSystems/TextSecure/tree/2.14.5

**Comment by johanw666** [comment]
Thanks, I had not seen that.
