### ISSUE TITLE
Messages missing + no chronology

### ISSUE THREAD

**Issue by rreeggiiss** [WhisperSystems/TextSecure#3178]
Hi everyone, after a good time using TextSecure I am starting to experience a really crippling bug that has many different outcomes:

- I am missing a certain number of messages (were sent to me but never received);
- Those I do receive are hardly ever pushed with a notification. I have to open TextSecure for them to show up, and they appear to have been sent right that minute;
- Tens of messages mark "Now" as the time they were sent/received. This is of course wrong, and fucks up the entire chronology (latest received on top);
- Whenever I try to send a text, it says TextSecure is trying to send a large quantity of messages;
- A fair amount of messages give me an "unable to send" error message.

Any idea what the problem could be? Here's the debug log: https://gist.github.com/90779d7e4406141e3efe

Thanks,
Régis

**Comment by rreeggiiss** [comment]
I have just deleted all messages that were permanently marked as "now", thinking maybe one of them is causing mayhem. It looks normal now, and new messages have the right time stamp. Now, to see if I receive all messages and get notifications.

**Comment by rhodey** [comment]
hey @rreeggiiss any updates on this situation? if you're still experiencing the "unable to send" issue please try to reproduce that issue then immediately submit a debug log after. the app debug log fills up pretty quickly and old information gets lost.

can you remember any specific event that marked the start of these weird behaviors?

**Comment by rreeggiiss** [comment]
Hey, I've actually sorted it out. My phone's time and date settings change at some point, somehow, putting my phone in the future. So the phone would have considered every message as new until we reach June 4th, date when they were supposedly sent. Now I put it back to normal, and I have another problem: everything that updated content (news, weather forecast) in the future refuses to update, because it thinks it'd downdate. Only  week to go and everything will be back to normal.

Now you know how you can piss off your friends: set their phone to the future. Woooo.
