### ISSUE TITLE
Sharing fails, when TextSecure is locked

### ISSUE THREAD

**Issue by sedrubal** [WhisperSystems/TextSecure#3179]
When TextSecure is locked with a passphrase and another app wants to share anything through TextSecure, this isn't working, because unlocking TextSecure shows the main contact list and not the sharing list.

**Comment by rhodey** [comment]
@sedrubal I'm unable to reproduce this on my Nexus 5 running Android 5.1 and TextSecure 2.14.5 from the Google Play Store, can you give me steps to reproduce and more information about your phone and TextSecure version?

what I tried:
1) open TS
2) create a password
3) lock TS using the menu item "Lock"
4) open my app "Photos"
5) chose a random photo, tap the share icon
6) chose TS
7) enter my passphrase
8) I get a list of contacts with the title "Share with", chose one, and the image is shown as a draft and sent as expected.

**Comment by sedrubal** [comment]
Ehm sorry... I can't reproduce it as well... Sorry, I don't know, why I was so confused...

**Comment by rhodey** [comment]
no worries :) thanks for checking back in
