### ISSUE TITLE
Secure message are not received until app is opened

### ISSUE THREAD

**Issue by FromBabylon** [WhisperSystems/TextSecure#3180]
Sometimes I don't receive secure messages until I manually open the app (even if phone was unlocked at time of sending). TextSecure services are running. This happen randomly but 1 times out of ten I would say. 
I've been trying to make this happen on purpose without success and I have not seen the same issue with regular SMS. 
(This is really annoying as I can't know if I've received something.) 

On Android 5.1.1

**Comment by moxie0** [comment]
This means you either:

1) Have background data disabled for TS or for google services.
2) Have a bad gapps install.
3) Have a network that blocks GCM.
4) Have used some backup/restore tool like Titanium Backup.

**Comment by FromBabylon** [comment]
I think it was restriction of background data on google services. Didn't know it was needed 

Thanks for your fast answer. I'll come back if not fixed.

**Comment by jedie** [comment]
Same as: #4266
