### ISSUE TITLE
Some avatars not rendered in contact list

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3181]
1. Go to main conversation list
2. Tap the pen icon on the lower right to get to the contact list
3. Tap your device's Back button to hide the keyboard that just popped up
4. Some contact avatars do not get rendered at all

![duncan idaho](https://cloud.githubusercontent.com/assets/174176/7668388/a8d9be98-fc3e-11e4-8a90-efd1e845e2a1.png)

This affects both picture contacts and initial creation contacts.
Scrolling usually fixes the issue or moves it to another contact.
It seems that if you dismiss the keyboard (step 3) quickly it increases the likelihood of missing avatars.

- TS 2.14.5
 * Nexus 4, stock Android 5.1
 * Huawei U8800, Android 4.0.4

Debug log: https://gist.github.com/74ba14ab06491edd4749
(On the second try 4 avatars not rendered)

**Comment by jeremymasters** [comment]
I have this too with 2.14.5. I have noticed that if I scroll around they appear.

**Comment by 2-4601** [comment]
This also happens when creating a new group and selecting contacts for it.
