### ISSUE TITLE
Select and attach several attachments (batch mode) [feature]

### ISSUE THREAD

**Issue by aurisnoctis** [WhisperSystems/TextSecure#3182]
At the moment, attachments like pictures can only be attached one at a time. This applies to

1. `Gallery > <select image(s)> > Share` (TextSecure only shows up as sharing option if 1 image is selected, starting with two, the sharing option disappears)
2. `TextSecure > <some conversation> > Add attachment > Picture`

It would be nice to have the possibility to add a batch of attachments instead of having to add them one by one.

**Comment by volcano99** [comment]
dupe #2159. Please close
