### ISSUE TITLE
SMS as auto-fallback

### ISSUE THREAD

**Issue by LeonardKoenig** [WhisperSystems/TextSecure#3193]
Hello,

I think it would be really nice if a textsecure message has not been received it auto-retries using the unsecured SMS (ofcourse, only optional, disabled by defalt).
This is useful in many situations like roaming or even when you want to save battery and disable push or mobile networking completely (and someone else tries to reach you).

So what I propose is to add an option to notify the user when his textsecure message has not been recieved for X minutes and/or add an option to automatically send the same text via SMS to make sure it reaches the other one – ditching the security for a moment when other things are more important. For "normal" textsecure users this can be a rather frequent annoyance.

EDIT: If possible, maybe one should delete the secured TextSecure message if the auto-falback SMS has been sent to avoid double-sending

**Comment by 2-4601** [comment]
See: #2847, #2384, #678, #877, #3074, #3068.

**Comment by LeonardKoenig** [comment]
My fault. As I first posted this in TextSecure-Browser (was bookmarked as "GitHub TextSecure ...") I only searched for issues there. Closing this.
