### ISSUE TITLE
Received a message that may have been incorrectly identified as encrypted with an old version of TextSecure.

### ISSUE THREAD

**Issue by Philippe23** [WhisperSystems/TextSecure#3196]
I received an SMS from Google Calendar's SMS notification short-code (48368) that TextSecure believes was encrypted with an out of date version of TextSecure.  I do not believe that Google uses TextSecure's encryption (correct me if I'm wrong), thus I'm lead to believe that TextSecure is incorrect in it's evaluation that the message was encrypted.

I am unable to retrieve the original ("encrypted") text.  TextSecure simply displays the "error" text: *Received a message encrypted using an old version of TextSecure that is no longer supported.  Please as the sender to upgrade to the most recent version and resend the message*.  Sent May 15th, 2015 02:10:02 PM EDT.  I believe I was up-to-date at that time.  My current version of TextSecure is 2.14.5 on Android 5.1.

I have since received another message from 48368 which was not evaluated as encrypted and displayed as a normal unencrypted SMS.

Is there any further information I can provide to help debug the issue?  Is there anyway to get the original ("raw") SMS message from under that error?

**Comment by moxie0** [comment]
It's possible there was a hash collision with the old encrypted SMS prefixes -- part of the reason we removed them. Should resolve itself when we remove that compatibility layer in a few months, thanks for the report!
