### ISSUE TITLE
view redraw on insert of first emoji

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3198]
tested using 4c89b242be51afee7e28861912c9e0a2b7e62ebd on my N5.

1) open conversation
2) click on the compose text section
3) click the emoji toggle button
4) type any single emoji
5) notice a redraw
6) continue typing emoji
7) notice no redraw
8) delete all the typed emoji
9) type any single emoji
10) notice a redraw

**Comment by rhodey** [comment]
additionally notice view redraws at completion of step 8, having an image message in view helps identify the redraws.

**Comment by rhodey** [comment]
rebuilt and tested on 0ee46bbe5fe199d821bb3a121ad31603bb877c09 as well (2.16.0)

**Comment by rhodey** [comment]
note this is still present on master (2cfc714b643e72b0bbc213a74319066d87b56cdb) but after 082985276f4abd066f9c4f07052ab5c82f576c34 it is no longer easy to identify using images, instead send a message containing emoji and you will observe the flicker of them being redrawn.

**Comment by boehan** [comment]
For me it seems that the input box changes it's height if you type a single emoji or only emojis. Height changes back to normal if you type any other character afterwards or rather stays normal height if you don't start your text with an emoji.
Also noticed that the blinking bar in the input box changes it's size too in the same way.

Don't know if this describes exactly the same issue as in this topic or it is a separate issue.

**Comment by McLoo** [comment]
@boehan exactly the Same on my HTC One S CM 12.1

**Comment by rhodey** [comment]
just tested this on 570f79d91ad027939c8190a95436b3749793c7b7 and am no longer able to reproduce :see_no_evil: closing.
