### ISSUE TITLE
emoji keyboard consumes all space on rotate from portrait to landscape

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3199]
tested on 4c89b242be51afee7e28861912c9e0a2b7e62ebd on my N5

1) have device in portrait
2) open a conversation
3) click on the message composition edit text
4) open the emoji keyboard
5) rotate device to landscape
6) emoji errewhere

![emoji!](http://i.imgur.com/zLAAufs.png)

**Comment by rhodey** [comment]
rebuilt and tested on 0ee46bbe5fe199d821bb3a121ad31603bb877c09 as well (2.16.0)

**Comment by agrajaghh** [comment]
@rhodey fyi its still possible to see the phonenumber

**Comment by rhodey** [comment]
lol thanks @agrajaghh, lemme try that again...
