### ISSUE TITLE
using the emoji drawer the first time opens empty recent category

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3201]
Just installed branch 2.16.0 over 2.14.1.

- opened conversation
- opend emoji pane
- category *recent* was shown
- and it was completely empty

furthermore, the recent category is always opened when changing the convo, 
rather than showing the last used category. 
Yes, you can argue that it's a personal favor that way - but at least don't show recents, when there are none :see_no_evil:

**Comment by mcginty** [comment]
:see_no_emoji:

**Comment by McLoo** [comment]
thanks for `:see_no_emoji:` :+1: :grin:
