### ISSUE TITLE
Emojis too small in compose field and message bubble 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3202]
Tested https://github.com/WhisperSystems/TextSecure/commit/0ee46bbe5fe199d821bb3a121ad31603bb877c09 on CM 12.1 HTC One S

Is this just some subjective thing? Or is my screen to small?

![screenshot_2015-05-20-16-54-25](https://cloud.githubusercontent.com/assets/5326916/7728787/80bb5ab8-ff11-11e4-8e45-3495b66a2cbf.png)

**Comment by jeremymasters** [comment]
I have a 5" 1080p screen and emojis are little on the small side, but that's how my stock ones are too.

**Comment by mcginty** [comment]
@McLoo when I was refactoring I compared our emoji to Android's, and these smaller emoji are how Android renders it (at least on my devices). I think the general note is that emoji are just other characters and should be the same line-height as our text.

**Comment by McLoo** [comment]
hey @mcginty just noticed on 2.17.0 if you have a line with only an emijo and you add any non ascii char, the line height gets extended.
 Is this due to font settings or do we have some room for stretching the emojis?!
