### ISSUE TITLE
thumbnails rendering smaller than expected for received images

### ISSUE THREAD

**Issue by claenn** [WhisperSystems/TextSecure#3204]
Hi there,

weird thumbnail rendering.
Pic used is 1080*122, http://p.twpl.jp/show/orig/ponr9

v2.14.5
![screenshot_2015-05-20-21-06-05v2](https://cloud.githubusercontent.com/assets/8040019/7734435/43be8ff2-ff36-11e4-82c4-8bf84dbf92f1.jpg)

Regards

**Comment by McLoo** [comment]
reminds me of  #2676 which I wanted to reopen already...

**Comment by rhodey** [comment]
I am able to consistently reproduce this bug with only one image in my collection, the thumbnail I see when the message is received is much different than the one I originally view when sent

![screen](http://i.imgur.com/QFoxtoW.png)

**Comment by rhodey** [comment]
cc @mcginty because they mentioned this might be intended behavior.

**Comment by 2-4601** [comment]
I believe this is not an issue anymore in 2.22.1? For intended behavior see #3579.

(Also @rhodey I've been searching for that woman in your picture for a while now. How do you know her or how have you came across this photo of her? Would you mind sharing her whereabouts? I have something very important to hell her that needs to be delivered personally. To save time could you also take this short test and send me the results: http://www.bfi.org.uk/are-you-a-replicant/
Thanks!)
