### ISSUE TITLE
Version in Google Play not matching to version on GitHub

### ISSUE THREAD

**Issue by GAS85** [WhisperSystems/TextSecure#3215]
Hey there,
 why I can see version 2.14.4 in Releases on GitHub and on Google Play it is a 2.14.5 already for a few days??? What is this version, what is inside? ~~Is this NSA?~~
![screenshot_2015-05-21-09-40-36](https://cloud.githubusercontent.com/assets/6813635/7743798/49bc8b9e-ff9e-11e4-9eee-dbe0c8384a56.png)
![textsecgithub](https://cloud.githubusercontent.com/assets/6813635/7743819/6d2e6c78-ff9e-11e4-993f-501d657ce4f9.png)

**Comment by johanw666** [comment]
There is a 2.14.5 branch, I missed that too (see  #3163). I guess they didn't want some patches that were already in master to appear in the bugfix version 2.14.5.

**Comment by GAS85** [comment]
I see now, thanks. But it would be better if releases are consistence to what is on the market.
