### ISSUE TITLE
UTF-16 messages leads to 70 characters  SMS

### ISSUE THREAD

**Issue by vincenttschanz** [WhisperSystems/TextSecure#3217]
For some reasons, textsecure on my phone seems to send 16bit encoded SMS. So I can only have 70 characters per SMS instead of 140 in 8bit or 160 in 7bit.

Is the character encoding choosed by TextSecure or is it enforced by android system?

I suspect 16bit encoding is mandatory for emoji, but in the case if I don't use them, could TextSecure switch to 8bit, or 7bit if I don't even use accents? This could cut by two my SMS budget.

**Comment by moxie0** [comment]
We have no control over this.  We hand a string to the OS and it does what it does.

**Comment by vincenttschanz** [comment]
Ok, I supected that, thank you.
