### ISSUE TITLE
Sms fallback option missing? 

### ISSUE THREAD

**Issue by MartyLake** [WhisperSystems/TextSecure#3220]
Hi, I can't find the sms fallback option. Tried to communicate with a friend today, he installed ts but couldn't send messages when no 3g and no Wi-Fi.

**Comment by agrajaghh** [comment]
you have to long press the send icon

**Comment by MartyLake** [comment]
OK ! I though it was automatically switching channel depending on the connectivity available.

**Comment by agrajaghh** [comment]
if you send a push message and have no data connection, it will be sent as soon as you have a network connection again afaik

**Comment by MartyLake** [comment]
OK ! Some people don't have data plans and are only connected when at home. Would it technically be possible to send encrypted messages over carrier? Or simply send as unencrypted after x minute without data?

**Comment by agrajaghh** [comment]
See: #2847, #2384, #678, #877, #3074, #3068

**Comment by MartyLake** [comment]
Oh! Then I'll just un install here : I wanted a sms replacement app. Thanks for your answer! Best!

**Comment by rhodey** [comment]
@MartyLake check out https://github.com/SMSSecure/SMSSecure

**Comment by MartyLake** [comment]
Thanks you sir!
