### ISSUE TITLE
draft image preview weird on rotate

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3223]
![portrait preview](http://i.imgur.com/fkBoknF.png)
![landscape preview](http://i.imgur.com/tEqJ4pP.png)

**Comment by jeremymasters** [comment]
is it not refreshing when scrolling?

**Comment by rhodey** [comment]
@jeremymasters nope, I've noticed this only for the draft image previews which are unaffected by scrolling.

**Comment by jeremymasters** [comment]
@rhodey  I actually am not running this version but it looked like it from the screen caps.

**Comment by McLoo** [comment]
Same for me 
Tested 0ee46bb on CM 12.1 HTC One S

Rotating back,  and the preview fine again

**Comment by mttwong** [comment]
It looks like the rightmost column of pixels is getting redrawn over the entire thing, making the streaks.

**Comment by riyapenn** [comment]
Is this still an issue?

**Comment by McLoo** [comment]
fixed for me
