### ISSUE TITLE
Emoji not displayed while tapping them on dark theme

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#3231]
Running 2.16. Dark theme. Android 4.1.
1. I'm typing a message
2. I open the emoji drawer
3. tap any emoji
4. it is not displayed in the textbox unless I close the emoji drawer

**Comment by agrajaghh** [comment]
can't reproduce this on Nexus 4 5.1.1 or HTC Desire 2.3.7

**Comment by mcginty** [comment]
While I can't reproduce this reliably, it looks like the result of a race condition since it happens occasionally for me.

**Comment by volcano99** [comment]
I was going to give a few more details but I see you've opened a PR already. Great! :+1:
