### ISSUE TITLE
group participant selection does unexpected stuff

### ISSUE THREAD

**Issue by sjaeckel** [WhisperSystems/TextSecure#3234]
1. create a new group
2. select a user from your textsecure contacts(TC)
3. scroll down to your non-textsecure contacts(NTC) and find a contact marked
4. remove the mark from the NTC 
5. scroll back and see that the mark from the initial TC is also gone

The first TC marks the first NTC
The second TC one well below
The third TC one in between the cases first TC and second TC
The fourth TC none (I think I quickly scrolled through all contacts)
The fifth TC also none

The NTC contacts are only marked in the list, but are not added to group!

**Comment by moxie0** [comment]
what version

**Comment by sjaeckel** [comment]
sorry

Device  : samsung SM-G388F (xcover3ltexx)
Android : 4.4.4 (G388FXXU1AOD4, KTU84P.G388FXXU1AOD4)
Memory  : 10M (0.16% used, 64M max)
Memclass: 64
OS Host : SWDD3015
App     : TextSecure 2.14.5

**Comment by 2-4601** [comment]
Tested this with my two devices and I **cannot** reproduce this. Whenever I select a TextSecure contact no other contacts get selected. It works just as expected.

However I noticed one UX inconvenience in Lollipop. The selection checkboxes are so close to the right side of the screen that it is almost impossible to tick them and instead the scroll action gets triggered. Fortunately the whole name area is tappable so this does not prevent the selection.

- TS 2.16.2
 * Nexus 4, stock 5.1.1
 * Huawei U8800, 4.0.4

**Comment by sjaeckel** [comment]
Well I'm still on 2.14.5 and the play store also doesn't propose an update.
Probably it has something to do with the fact that I had already very early versions of TextSecure installed and I recently changed phones and created a backup of TextSecure with helium... Just speculating...
I can also provide you with a screencast, but I don't know how else I could help.

**Comment by 2-4601** [comment]
Debug log right after you have experienced the issue might be helpful.
Settings->Advanced->Submit Debug Log

Titanium backups are often mentioned here as fucking things up.

**Comment by sjaeckel** [comment]
https://gist.github.com/sjaeckel/c93a14ac669ed8ba0a0b

**Comment by riyapenn** [comment]
is this still an issue?

**Comment by sjaeckel** [comment]
I was not able to reproduce the problem in a quick test with 2.28.1.
