### ISSUE TITLE
Attachment button instead of send arrow

### ISSUE THREAD

**Issue by volcano99** [WhisperSystems/TextSecure#3235]
It has happened sometimes (twice, so far) that even though I'm typing a message in the text box I don't get the arrow icon to send -- the attachment icon never goes away. When I click it, the behaviour is that of adding the attachment (so it's not just a problem of displaying the wrong icon, I am actually asked if I want to take a picture and stuff..).
Exiting and re-entering the conversation fixes it. It has happened both when talking to a Signal user and with an SMS one. It seems to be random, I'm trying to figure out how it works but I can't reproduce :/

**Comment by volcano99** [comment]
Ok I think I figured how it worked, kind of.
I have a samsung, and I use the default predictive text settings (I don't use any magical keyboard, just the normal one).
1. start typing random letters so that you don't make a known word (no spaces); [by the time you type the first character the arrow should have appeared]
2. "confirm" in the suggestions that you mean exactly that word
3. delete the last character;
4. start typing again -> you should see the arrow turn into the attachment icon again

It's like it doesn't recognize the word you've entered as "text". I have been able to reproduce consistently with this method.

**Comment by moxie0** [comment]
I'm not able to reproduce this, but I'm not sure I'm following your directions correctly. Could you post screenshots for each step?

**Comment by volcano99** [comment]
![screenshot_2015-05-22-19-11-15](https://cloud.githubusercontent.com/assets/11767388/7775844/eaf8fe98-00b6-11e5-8ca6-29f1d312187b.png)
From my phone I cab only post one pic at a time

**Comment by volcano99** [comment]
![screenshot_2015-05-22-19-11-23](https://cloud.githubusercontent.com/assets/11767388/7775861/0cb1f40e-00b7-11e5-913a-6a5899290b2a.png)

**Comment by volcano99** [comment]
![screenshot_2015-05-22-19-11-30](https://cloud.githubusercontent.com/assets/11767388/7775885/346c0872-00b7-11e5-9f0d-00ee3ee004f5.png)

**Comment by volcano99** [comment]
![screenshot_2015-05-22-19-11-37](https://cloud.githubusercontent.com/assets/11767388/7775897/42efb150-00b7-11e5-922b-041067474616.png)

**Comment by moxie0** [comment]
if you then add a space, does it switch back to the send button? or no matter what you type from then on, it remains the attach button?

**Comment by moxie0** [comment]
Also do you have WhatsApp or Hangouts installed? If you do the same series of steps on your device in those apps, what happens with their toggles?

**Comment by agrajaghh** [comment]
I experienced this as well, I didn't open an issue yet because I don't know how to reproduce it. When I was stuck with the attachment icon while there was text in the edit box, continuing typing didn't bring the send button back. Just deleting everything and start typing again...

**Comment by volcano99** [comment]
Adding a space doesn't change anything, the attachment button doesn't go away :/
I downloaded hangout and it works fine with it
@agrajaghh can you confirm my steps make the bug appear for you?

**Comment by McLoo** [comment]
Some race conditions with beforetextchanged and aftertextchanged?

**Comment by volcano99** [comment]
By the way i just found out that the bug occurs even if the word IS in the dictionary ^^"
I discovered it while typing nonsense and i thought it was necessary for the bug to arise but apparently it isn't

**Comment by McLoo** [comment]
Aahhh, doing some voice input via Google to speech brought this up. No pattern found yet. 

Noticed once fter the first word send button came up, waited for the disappearing of the delete word and whoosh  the paper clip came back

**Comment by McLoo** [comment]
Pattern :
Tell Google "okay",  have text "okay" and
 have send button, 
wait, "okay" gets "ok", 
have paper clip.

**Comment by mcginty** [comment]
can reproduce with voice input, thanks @McLoo for the steps!

**Comment by agrajaghh** [comment]
I could reproduce it with voice input as well. After saying "okay" the send button appeared and disapeared again immediately:

![gif](https://cloud.githubusercontent.com/assets/5296073/7778259/f186e21c-00c9-11e5-9cdd-eaf4b49e5380.gif)

**Comment by mcginty** [comment]
Looks like it's correlated with when that popup appears under the text.

**Comment by McLoo** [comment]
@mcginty as I wrote, the word okay gets deleted and OK gets written, all very quick. With some calculation for remaining chars. 
Log outputs for before and after text changed shos the asyncaty of the two - on quick testing. 
Breakpoints won't help break the behavior
