### ISSUE TITLE
secure connection does not work even though messages are shown blue for one side

### ISSUE THREAD

**Issue by gartenriese2** [WhisperSystems/TextSecure#3236]
I have weird problems with one of my friends. It just won't encrypt my messages anymore even though it worked before (like a couple of weeks before). She says however that the messages are shown in blue to her. But for me they are green and the lock is open. The info says that I am using insecure messages. I tried disabling and reenabling secure messages but that didn't fix the problem.

I have TextSecure 2.14.5 and my friend says that she has the latest version also. She tried reinstalling the app but it didn't fix the problem. She says that it still works fine for her other friends.

I have no problems with all my other friends.

**Comment by jeremymasters** [comment]
Try pressing the little lock icon at the top of your conversation.  This has cleared up problems for me in the past.

**Comment by gartenriese2** [comment]
Update: I have a group chat conversation with that friend from above and another friend who uses iOS version. Let's call them Alice and Bob from now on. In that group chat I can't send any messages, Alice and Bob can however. I can read messages from Bob in that group chat but not all from Alice. If I send a message directly to Bob it shows as blue and that Bob received the message. However Bob said that he didn't get any messages.

**Comment by gartenriese2** [comment]
@jeremymasters: I don't have a lock in the conversation with Alice.

**Comment by volcano99** [comment]
As for the group chat: have someone change the avatar of the group.
Did you recently reinstall or something?

**Comment by jeremymasters** [comment]
@gartenriese2 Have your friend press the lock icon then if you don't have one.

**Comment by gartenriese2** [comment]
@volcano99: This sounds very specific, can you explain why? I changed the avatar myself but it didn't fix anything. 
And yes, I recently reinstalled it and restored data with Titanium

**Comment by moxie0** [comment]
Using titanium backup with TextSecure is not supported, and will break everything. You'll need to do a fresh install.

**Comment by gartenriese2** [comment]
I did a fresh install but it's still the same. @moxie0: Can you please reopen?

**Comment by moxie0** [comment]
please post a debug log that covers a send, and a screenshot. thanks!

**Comment by gartenriese2** [comment]
Here is the debug log after sending a message that will not get delivered. 
http://pastebin.com/CkYaLQrk

**Comment by gartenriese2** [comment]
Here is the debug log after sending a message that is not encrypted even though both have encrypted messages enabled and both can send encrypted messages to other recipients. 
http://pastebin.com/YwEDgstU

**Comment by moxie0** [comment]
What do you mean by "will not get delivered?" Did the phone you're sending messages to also use titanium backup?

**Comment by gartenriese2** [comment]
The recipient confirmed that no messages were received, even though messages from other people were received. 
No, the phone did not use Titanium, it uses Signal.

**Comment by moxie0** [comment]
At the top you said that your friend was running TextSecure 2.14.5?

**Comment by gartenriese2** [comment]
Ah Sorry, should have clarified. In the update above I introduced Alice and Bob. Alice is the one where I can only send unencrypted messages (debug log #2). Alice has TextSecure.  Bob is the one where my messages won't get delivered. Bob uses Signal.

**Comment by gartenriese2** [comment]
Alice just told me that she gets the messages I sent her in her standard messaging app, not TextSecure. She can however use TextSecure to successfully message and receive encrypted messages from others.

**Comment by gartenriese2** [comment]
Here is a picture of the conversation with Alice. It seems she's still able to send me encrypted messages (see message at 00:10), but I can only respond with unencrypted messages. 
![picsart_1432366309493](https://cloud.githubusercontent.com/assets/4339033/7782950/466cbf44-012f-11e5-89ff-59173e28cfe4.jpg)

**Comment by gartenriese2** [comment]
Update: I think everything is working with Bob now, I don't know if it was just miscommunication before but she can at least now read my messages. She doesn't have a lock at the top of the conversation though, is that normal on Signal? 

On to Alice: I can start a group chat with Alice and Bob and they both can write messages in that group but I am not able to send any. This is how it looks for me:
![gruppenchat](https://cloud.githubusercontent.com/assets/4339033/7806981/99fa967c-0387-11e5-9d0e-8db86536ce49.jpg)
![message_info](https://cloud.githubusercontent.com/assets/4339033/7806995/ab81c96a-0387-11e5-8e3f-50a76cb4d859.jpg)
And this is the debug log when writing a message in that group: http://pastebin.com/ccpmM5xC
I don't know why I can't write anything to Alice. I have her in my TextSecure contacts:
![kontaktliste](https://cloud.githubusercontent.com/assets/4339033/7807023/1e10ff5a-0388-11e5-9b75-3f20271f234f.jpg)

Is there anything else I can do to help?

**Comment by moxie0** [comment]
post a debug log from after you send to the group

**Comment by McLoo** [comment]
*And this is the debug log when writing a message in that group: http://pastebin.com/ccpmM5xC* ?

**Comment by moxie0** [comment]
Ah.  Your messages are failing because one of the users in the group (who's number ends with 95) is not registered for TS messages any longer.

**Comment by gartenriese2** [comment]
@moxie0, @McLoo: Yes, that's the debug log after I sent a message in the group.

**Comment by gartenriese2** [comment]
@moxie0: But why am I still seeing her in my contact list? And why can she send me encrypted messages?

**Comment by moxie0** [comment]
@gartenriese2 My guess is that this person did something weird to their install or their device.  Maybe they have a registration id but no keys, or are in some other strange state.  Either way, this is feeling more like a support request, so I think you'll have better luck with support@whispersystems.org than here.

**Comment by gartenriese2** [comment]
@moxie0: Ok, I'll ask her, and I'll also try the support. Thanks for your help anyways, it's much appreciated!

**Comment by gartenriese2** [comment]
Just wanted to let you know that reinstalling did not help and it is not fixed either. Support could not help me either unfortunately.
