### ISSUE TITLE
Please add a way to turn off send button animation

### ISSUE THREAD

**Issue by piratenpanda** [WhisperSystems/TextSecure#3237]
Since 2.16 I'm getting headaches due to the new send button animation moving in and out all the times. It would be nice to turn this off even if that means you'd have to use attachments as before.

Maybe even add an attchment button at the top next to the telephone one.

**Comment by moxie0** [comment]
The answer is never more options:
https://github.com/WhisperSystems/TextSecure/blob/master/contributing.md#development-ideology
