### ISSUE TITLE
TextSecure doesn't intercept key exchange messages when 'use for all sms' is unticked.

### ISSUE THREAD

**Issue by mesheree** [WhisperSystems/TextSecure#324]
I want to be able to make TextSecure the default handler for _only_ encrypted texts sent from other TextSMS users.

Reason #1 -- I like being able to automagically have my regular SMS messages backed up to teh Googlez.  It seems like this could be resolved by giving SecureText an option to use the regular SMS database for unencrypted texts..

Reason #2 -- It's just not as glitzy and polished as the SMS app I usually use.  If I could talk to the couple paranoid people in my life with this app and everyone else with my regular SMS app, that would great!

**Comment by rhodey** [comment]
support for encrypted SMS and MMS has been dropped in the latest release, please see [this blog post](https://whispersystems.org/blog/goodbye-encrypted-sms/) for details. because of this you should never receive a key exchange over SMS
