### ISSUE TITLE
group chats don't work after reinstalling 

### ISSUE THREAD

**Issue by gartenriese2** [WhisperSystems/TextSecure#3246]
I reinstalled TextSecure and after that I couldn't write in the old group chats. I can see messages from others but I can't send anything. My keyboard doesn't even respond when I want to write something. I can access Smileys but I can't send them because the send button doesn't work either.

**Comment by 5boro** [comment]
Ask one of the group members to add you again. Similar to #2581

**Comment by volcano99** [comment]
Ask them to change the group chat avatars

**Comment by gartenriese2** [comment]
Ok, that seems to be exactly my issue, thanks.
