### ISSUE TITLE
pictures not displayed

### ISSUE THREAD

**Issue by devurandom** [WhisperSystems/TextSecure#3248]
Pictures I send are not displayed by my contact. On my end they are uploaded (dark blue background) and even delivered to their phone (check mark icon), they do not show up on their screen. The same happens in the opposite direction: they claim to have sent me a picture, and say it was sent and delivered, but I did not receive a message, and neither is any image displayed in the thread.

Their installation/registration of TS is very new - only about an hour old. We are connected via a very low bandwidth and high latency network.

https://gist.github.com/1651dc1d34c9b1a39572

**Comment by moxie0** [comment]
Please attach a screenshot of the message with an image that doesn't display.

**Comment by devurandom** [comment]
Image of my view of an image that is not displayed at the other end: http://i.imgur.com/i0D3sHsl.jpg

**Comment by moxie0** [comment]
I'm interested in the screenshot from the receiving party.  If there's literally nothing, I"ll need a debug log that covers the instant the message was received and acknowledged but not displayed.

**Comment by devurandom** [comment]
I'll try to get both. Will take some time...

**Comment by devurandom** [comment]
PS: on my side literally nothing was displayed, when the other side claimed to have sent me a picture.

**Comment by rhodey** [comment]
@devurandom in the context of your last comment, can you recall if the other side saw a delivery receipt (the check) for the image they tried to send you? I noticed your device is running Cyanogenmod, are you or have you ever been registered for "WhisperPush"?

**Comment by devurandom** [comment]
I was registered long ago (2 years?) and unregistered a few days afterwards (i.e. also 2 years ago).

The other side was not very specific on what they saw, I was unable to make them acquire a screenshot, and I no longer have any possibility for direct contact, either. Unless you have any suspicion you want to follow, I suggest to close this issue. If it ever happens again, we can reopen it (or create a new report).

In conjunction with issue #3250, I suspect that the really horrible internet connection causes TS to fail silently, when it fetches the images in the background. Do you have any experience with TS on high latency and low bandwidth connections with a significant amount of packet loss?

My general experience (not primarily with TS, but with HTTP) with such network: A VPN improves the stability a lot – possibly, because everything is tunnelled through one TCP connection, instead of creating one TCP connection (with all the extra round-trips this implies) for each request. Maybe this helps you to improve TS' behaviour within such networks?
