### ISSUE TITLE
Please add optional online/offline/last seen status feature

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#3252]
Hello,

could you please add an optional online/offline/last seen status feature?

Other popular messengers like Telegram for Android and WhatsApp for Android do have that feature and it can be quite useful.

Those users who wouldn't like it could simply disable it.

Telegram has a rather nice way of handling this, see:

https://telegram.org/blog/privacy-revolution

So, could you please add such a feature?

Regards

**Comment by moxie0** [comment]
thanks but not into it

**Comment by Evi1M4chine** [comment]
Too bad your reaction to this doesn’t contain a reason, moxie0. This makes it look like a purely emotional (trigger) reaction. There are good reasons for this functionality. And nobody has to be forced to actually use them. (opt-in).
Big advantages for people like me, zero disadvantages for people like you… the rational mind concludes that it should be implemented.
