### ISSUE TITLE
Emojis occasionally not rendered

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3255]
Emojis seem to be occasionally missing in conversations, message snippets, contact names and group names.
I cannot reproduce this consistently in conversations. But in the main conversation list it is consistent when TS is opened for the first time.

How to reproduce:
1. Make sure that there's at least one emoji somewhere in the main conversation list (contact/group name or message snippet)
2. Close TS from the _Recent apps_ list
3. Open TS
4. Emojis are most likely missing in the main conversation list
![markorepairs no emoji](https://cloud.githubusercontent.com/assets/174176/7789619/97c42c96-0270-11e5-947f-aac234842e57.png)
5. Open some conversation
6. Come back to main conversation list
7. The emojis are visible again
![markorepairs emoji](https://cloud.githubusercontent.com/assets/174176/7789617/8a4ce6ca-0270-11e5-8a2c-e6cd17df500b.png)

TS 2.16.1
 * U8800, Android 4.0.4
 * Nexus 4, stock Android 5.1.1

Debug log from Nexus 4: https://gist.github.com/702f556b8408664f0d5c
5/7 emojis failed to render (or 6/8 if the one under the system navigation bar is counted).

**Comment by mcginty** [comment]
prerequisite research https://www.youtube.com/watch?v=pqP3GHD3QJQ

**Comment by jeremymasters** [comment]
@mcginty that may be the worst video ever

**Comment by 2-4601** [comment]
Impressive research. :+1:
I think you are on to something here. The green flickering in the background and the effortless flow are very pleasing to the eye and ear. If that rhythm could somehow be mimicked in the way things are drawn in TS I'm confident it would solve all past, present and future race conditions for good.

:smoking::grin:
