### ISSUE TITLE
Support GSM 7-bit alphabet for SMS

### ISSUE THREAD

**Issue by athanasio** [WhisperSystems/TextSecure#3257]
Hello,
it would be useful (in order to further promote TextSecure as a full messaging replacement to friends and family) to support the GSM 7-bit alphabet, http://en.wikipedia.org/wiki/GSM_03.38 , which would allow keeping the cost of SMS low in some countries.

**Comment by moxie0** [comment]
Thanks but we have no control over how SMS is encoded or sent.  We pass a string to the OS, and it's up to your Android ROM.

**Comment by athanasio** [comment]
Hello, thank you for your reply; unfortunately your answer is not correct. It's the SMS app's responsibility to convert the text to 7-bit. I have replicated the issue; the default messaging app in Android 5.1 has the option for 7-bit and converts the text accordingly; if set to automatic, then it uses the full alphabet and the text is reduced to 60 characters per message. TextSecure defaults to automatic without the option to enable 7-bit.
