### ISSUE TITLE
broken attachment-download message bubble on GB

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#3259]
on GB (runing 2.16.1) the message bubble is not wide enough while downloading the attachment. I have to go back to the conversation list and open the conversation again to get the correct size:

![screenshot-20150526-110552](https://cloud.githubusercontent.com/assets/5296073/7809409/370cd74c-039a-11e5-814b-bb483e78b5c8.png)
![screenshot-20150526-110600](https://cloud.githubusercontent.com/assets/5296073/7809410/37d8b22c-039a-11e5-9ccb-1df031174f36.png)
![screenshot-20150526-110610](https://cloud.githubusercontent.com/assets/5296073/7809411/38fd5126-039a-11e5-9982-c509753d22fe.png)
tested on HTC Desire CM7 2.3.7

**Comment by volcano99** [comment]
On my phone, I used to get something similar to the second screenshot several versions ago, although the first screenshot is current behavior for me. Isn't that intentional? Maybe though instead of making it wider it could be made shorter until the picture has been downloaded.

**Comment by agrajaghh** [comment]
@volcano99 this is how its supposed to look:
![device-2015-05-26-192255](https://cloud.githubusercontent.com/assets/5296073/7818539/b7cfc3ca-03dc-11e5-91e0-e9612f3c642b.png)

**Comment by volcano99** [comment]
Uhm... I've definitely seen both, but I think I don't remember exactly on which phones ^^"

**Comment by agrajaghh** [comment]
Just realized that the message bubble with the correct image is too high (Screenshot Nr. 3)

**Comment by 5boro** [comment]
![screenshot_2015-06-05-20-58-03](https://cloud.githubusercontent.com/assets/3460479/8013159/5cac2946-0bc7-11e5-8c03-ab4c0d8ee2ce.png)

I just noticed the same bug as in your 3rd pic. 

But you can also see that the text that's been sent with it has a different width.
Texts seems to always take the full width of the view, why not pictures?

**Comment by oaim** [comment]
I have this bug on android 4+, TS 2.18.1. I think it had been fixed for me and was only recently reintroduced

**Comment by 2-4601** [comment]
Can confirm on Huawei U8800, Android 4.0.4. Unfortunately no debug log :{
![3259](https://cloud.githubusercontent.com/assets/174176/8273763/66a56aa2-1883-11e5-9ed0-43141ca932c0.png)
Going to conversation list and returning back fixed issue.
Picture dimensions: 1280 × 720

**Comment by moxie0** [comment]
should be fixed

**Comment by agrajaghh** [comment]
yep, just confirmed, its fixed for me
