### ISSUE TITLE
emoji not properly ellipsized in single-line textviews

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#3266]
If I send a long-ish message to someone, then go back to the conversation list, that message runs off the right side of the screen.  This might be ok since it shows as much of the message as my screen will tolerate.

**Comment by volcano99** [comment]
Can you post a screenshot? I haven't experienced any bugs with writing long messages

**Comment by jeremymasters** [comment]
I could but if you just send any message that's long enough to run off the side of the screen...like say a paragraph from the web somewhere.  Once it sends, go back to the list of conversations and note that it goes to the right edge of the screen.

**Comment by volcano99** [comment]
That's exactly the point: it doesn't happen on my phone (and I type *very* long messages). So I don't know what you're talking about...

**Comment by jeremymasters** [comment]
![20150527_115236](https://cloud.githubusercontent.com/assets/4967949/7843484/24b0a2ea-0467-11e5-8f29-2450f650cad9.jpg)

**Comment by agrajaghh** [comment]
I guess you didn't write "li..."? Its weird that half of the emoji is still displayed, it should just be "[...]We had li..."

I couldn't reproduce this yet...

**Comment by jeremymasters** [comment]
From the "We" it was "We had like 3 days of rain :umbrella:"

**Comment by 2-4601** [comment]
I've been experiencing this too. The message snippet does not seem to shrink emojis in the ellipsis (i.e. three dots). Text gets handled properly.

Nexus 4, stock Android 5.1.1
TS 2.16.2 (and at least 2.16)

**Comment by jeremymasters** [comment]
I wonder if the parsing stops at the end of the text, so it uses ellipses and pastes the rest of the message.  An interesting test would be "asdfasdfasdfasdfadsfadsfasdfasdfadsfasdfasdf :umbrella: :closed_umbrella: :cactus:" and see if all the emojis are left at the end.

**Comment by jeremymasters** [comment]
Looks like the result of that looks the same as before.
