### ISSUE TITLE
TS emoji and system emoji sizes are different when typing

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3267]
0. Go to some conversation and tap the input box
1. Type a `BANKNOTE WITH DOLLAR SIGN` (U+1F4B5) with TS emoji drawer
2. Type the same emoji with Lollipop system emoji keyboard
3. Notice that the system dollar is bigger

![mcginty dollars](https://cloud.githubusercontent.com/assets/174176/7844356/7ca780bc-04b8-11e5-88b9-4074d1a94d9c.png)

This gets fixed if you the leave conversation (draft gets saved) and then return back to the conversation. Also pasting stuff seems to affect it.
This is only an issue with the input box. Sent and received messages show emojis at one size.

Related: #2937 

TS 2.16.2, Nexus 4, stock Android 5.1.1

**Comment by mcginty** [comment]
mcgintybucks are depreciating faster than I expected
