### ISSUE TITLE
Asset path does not exist or contains no resources

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#3269]
I see this in my log as well.  Wasn't sure if this is a bug or just tried to load anything in a directory that might exist and I just don't have anything that needs to be loaded.

--------- beginning of system
V/ActivityThread(31496): updateVisibility : ActivityRecord{449e529 token=android.os.BinderProxy@2e040293 {org.thoughtcrime.securesms/org.thoughtcrime.securesms.RoutingActivity}} show : false
W/ResourcesManager(31496): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.

https://gist.github.com/anonymous/67fb32e2bcecca453b13

**Comment by moxie0** [comment]
Thanks but unless you're experiencing a bug, there's no need to open an issue.
