### ISSUE TITLE
Emoji Background Color is White with Dark Theme

### ISSUE THREAD

**Issue by wrdixon** [WhisperSystems/TextSecure#3277]
Using TS 2.16.2 on Andorid 4.4.4 running the Dark Theme

The emoji panel background is now white.  It was black before 2.16 and looked much better with the dark theme.

PS.  This app has come a long way, so props to the devs and thanks for all of the hard work!  It's so pretty now!

**Comment by 2-4601** [comment]
Duplicate of #3240

**Comment by wrdixon** [comment]
Ahh so it is.  Sorry about that!
