### ISSUE TITLE
TS emojis not used in notifications

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3278]
Some TextSecure emojis are not used in Android notifications.

Here's an example message that I received from a strange number. The message contains the `AIRPLANE` (U+2708) emoji which is displayed differently in notifications and in TS:

**Lock screen notification:**
![lock](https://cloud.githubusercontent.com/assets/174176/7869839/f41eb2a2-058d-11e5-86b6-ef9f80928ca0.png)
----------

**Notification drawer:**
![notification](https://cloud.githubusercontent.com/assets/174176/7869851/04cd6454-058e-11e5-81ff-4c75fc565855.png)

----------

**Heads-up notification:**
![headsup](https://cloud.githubusercontent.com/assets/174176/7869852/0a22db50-058e-11e5-8e04-7dfecfa93a1c.png)

----------

**And finally the actual TextSecure message:**
![message](https://cloud.githubusercontent.com/assets/174176/7869858/11196dd4-058e-11e5-8a10-c91e3e192e6f.png)

The meaning of the message changes completely depending on the emoji set used. Now I don't know if I should report this unknown sender to the authorities (like the good, law-abiding citizen I am) or just wish this person a safe trip.

I'm not certain if the emojis in the notifications can even be changed but I'm under the impression that WhatsApp does show it's own iOS-like emojis in Android notifications.

Related #2936 

TS 2.16.2
Nexus 4, stock 5.1.1

**Comment by 2-4601** [comment]
I guess #2936 was not completely resolved since typing the `AIRPLANE` with the Android emoji keyboard still gives the system emoji instead of the TS emoji.

Also on my 4.0.4 device the notifications do not show any emojis at all except the ones that conflict with system emojis. One example of such emoji is the `AIRPLANE`.

**Comment by 2-4601** [comment]
Here's a (partial) list of the overriding emojis:
![conflicting emojis](https://cloud.githubusercontent.com/assets/174176/7885674/f57a1b6e-062d-11e5-8ed1-4cb2e89d486f.png)

Same as text: https://gist.githubusercontent.com/anonymous/2bb4dc45242f0e89c0b9/raw/0ea22c3c45b155e85f2c6b8b168e2366afb2e5fe/conflicting.emojis.utf-8.txt

Most of these emojis are also visible in 4.0.4 notifications (while the rest, i.e. vast majority, are not).

If there is no convenient fix for this and it requires going through all emojis to see what works just close this issue or at least change the milestone to _when hell freezes over_.

**Comment by wp9015362** [comment]
> @2-4601 wrote:
> 
> Also on my 4.0.4 device the notifications do not show any emojis at all except the ones that conflict with system emojis.

Android did not support color system Emojis before 4.4 KitKat.

They were first introduced with 4.4 KitKat.

So, it's normal that your 4.0.4 device doesn't show them, because it simply doesn't support / have them.

> @2-4601 wrote:
> 
> I'm not certain if the emojis in the notifications can even be changed but I'm under the impression that WhatsApp does show it's own iOS-like emojis in Android notifications.

Are you sure about WhatsApp showing it's own Emojis in notifications?

Telegram for Android does not show it's own Emojis in notifications either.

Regards

**Comment by 2-4601** [comment]
@wp9015362 Thanks for confirming these!

I thought I saw all emojis in 4.0.4 notifications before but I guess I was dreaming :sleeping: 

I only assumed that WhatsApp has its own emojis in notifications. In fact I spent an hour searching for screenshots and YouTube videos of a single WA emoji notification but failed and just assumed :)

So it seems my bloated-wall-of-text bug report is even more useless now.

@rhodey Seems like you are on a closing spree :) Do you have any objections for not closing this? I'm mainly asking since I see you have added the _bug_ label.

**Comment by rhodey** [comment]
@2-4601 emoji is @mcginty's domain for the time being :P in another week or two I expect the velocity of the emoji code will slow down and maybe then I'll open some emoji PRs. I added the bug label because proper labeling of issues is a strange fixation of mine

**Comment by 2-4601** [comment]
Alrighty then, I will close this since it appears that only system emojis are available for notifications (thanks @wp9015362)

**Comment by KyleGospo** [comment]
This actually bothered me enough to start working on making emoji sets selectable in a TextSecure build of my own. If I finish this feature and do a pull request, is this something that would be acceptable? Right now I'm only making it possible to select between Android and iOS emoji, though other sets like HTC's Sense could be added later.

Thanks in advance!

**Comment by StefanBossbaly** [comment]
@KyleGospo :+1:

**Comment by kb100** [comment]
@2-4601 Duplicate yes, but why is this issue closed? I'm on Android 5.1.1 and the issue persists. Time to reopen?

**Comment by 2-4601** [comment]
@kb100 this was closed because
> it appears that only system emojis are available for notifications

i.e. can't be fixed, or can someone prove otherwise?
