### ISSUE TITLE
Key generation fails

### ISSUE THREAD

**Issue by vaeth** [WhisperSystems/TextSecure#3286]
After complete removal and reinstalling 2.14.5 from GoogleStore, the registration procedure reproducible seems to fail at the step "Key generation".
(Samsung Galaxy S3 LTE, German Telekom branding)
With "adb logcat", the following messages appear after starting the registration procedure:

<code>D/STATUSBAR-NetworkController( 2723): refreshSignalCluster: data=-1 bt=false
D/STATUSBAR-IconMerger( 2723): checkOverflow(336), More:false, Req:false Child:2
D/STATUSBAR-NetworkController( 2723): onSignalStrengthsChanged signalStrength=SignalStrength: 99 -1 -1 -1 -1 -1 -1 25 -86 -6 230 -1 2147483647 gsm|lte 0x3 level=3
D/STATUSBAR-NetworkController( 2723): onSignalStrengthsChanged signalStrength=SignalStrength: 99 -1 -1 -1 -1 -1 -1 25 -86 -6 230 -1 2147483647 gsm|lte 0x3 level=3
E/Watchdog( 2375): !@Sync 64
D/SSRMv2:Monitor( 2375): SIOP:: AP = 340 (read only)
D/STATUSBAR-NetworkController( 2723): refreshSignalCluster: data=-1 bt=false
D/STATUSBAR-IconMerger( 2723): checkOverflow(336), More:false, Req:false Child:2
I/InputReader( 2375): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.450 ] when=1947917920000
I/InputDispatcher( 2375): Delivering touch to: action: 0x4
I/InputDispatcher( 2375): Delivering touch to: action: 0x0
I/InputReader( 2375): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=1947960774000
I/InputDispatcher( 2375): Delivering touch to: action: 0x1
E/DatabaseUtils( 2375): Writing exception to parcel
E/DatabaseUtils( 2375): java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
E/DatabaseUtils( 2375): 	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:13101)
E/DatabaseUtils( 2375): 	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2038)
E/DatabaseUtils( 2375): 	at com.android.providers.settings.SettingsProvider.callFromPackage(SettingsProvider.java:607)
E/DatabaseUtils( 2375): 	at android.content.ContentProvider$Transport.call(ContentProvider.java:279)
E/DatabaseUtils( 2375): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:273)
E/DatabaseUtils( 2375): 	at android.os.Binder.execTransact(Binder.java:388)
E/DatabaseUtils( 2375): 	at dalvik.system.NativeStart.run(Native Method)
W/ActivityManager( 2375): Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
V/WindowManager( 2375): Window{4361c1c0 u0 Keyguard}mOrientationRequetedFromKeyguard=false
I/SurfaceFlinger( 1968): id=276 createSurf (1x1),1 flag=4, Segistratio
V/WindowManager( 2375): Window{4361c1c0 u0 Keyguard}mOrientationRequetedFromKeyguard=false
E/EnterpriseContainerManager( 2375): ContainerPolicy Service is not yet ready!!!
D/EnterpriseDeviceManager( 2375): ContainerId: 0
W/LicenseLogService( 2375): log() is called by non admin
I/InputReader( 2375): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.451 ] when=1949325203000
I/InputDispatcher( 2375): Delivering touch to: action: 0x4
I/InputDispatcher( 2375): Delivering touch to: action: 0x0
D/STATUSBAR-NetworkController( 2723): onSignalStrengthsChanged signalStrength=SignalStrength: 99 -1 -1 -1 -1 -1 -1 25 -87 -6 204 -1 2147483647 gsm|lte 0x3 level=3
I/InputReader( 2375): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=1949379080000
I/InputDispatcher( 2375): Delivering touch to: action: 0x1
E/DatabaseUtils( 2375): Writing exception to parcel
E/DatabaseUtils( 2375): java.lang.SecurityException: Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
E/DatabaseUtils( 2375): 	at com.android.server.am.ActivityManagerService.handleIncomingUser(ActivityManagerService.java:13101)
E/DatabaseUtils( 2375): 	at android.app.ActivityManager.handleIncomingUser(ActivityManager.java:2038)
E/DatabaseUtils( 2375): 	at com.android.providers.settings.SettingsProvider.callFromPackage(SettingsProvider.java:607)
E/DatabaseUtils( 2375): 	at android.content.ContentProvider$Transport.call(ContentProvider.java:279)
E/DatabaseUtils( 2375): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:273)
E/DatabaseUtils( 2375): 	at android.os.Binder.execTransact(Binder.java:388)
E/DatabaseUtils( 2375): 	at dalvik.system.NativeStart.run(Native Method)
W/ActivityManager( 2375): Permission Denial: get/set setting for user asks to run as user -2 but is calling from user 0; this requires android.permission.INTERACT_ACROSS_USERS_FULL
E/Parcel  ( 2375): Class not found when unmarshalling: org.thoughtcrime.securesms.crypto.MasterSecret
E/Parcel  ( 2375): java.lang.ClassNotFoundException: org.thoughtcrime.securesms.crypto.MasterSecret
E/Parcel  ( 2375): 	at java.lang.Class.classForName(Native Method)
E/Parcel  ( 2375): 	at java.lang.Class.forName(Class.java:204)
E/Parcel  ( 2375): 	at java.lang.Class.forName(Class.java:169)
E/Parcel  ( 2375): 	at android.os.Parcel.readParcelableCreator(Parcel.java:2091)
E/Parcel  ( 2375): 	at android.os.Parcel.readParcelable(Parcel.java:2055)
E/Parcel  ( 2375): 	at android.os.Parcel.readValue(Parcel.java:1971)
E/Parcel  ( 2375): 	at android.os.Parcel.readMapInternal(Parcel.java:2255)
E/Parcel  ( 2375): 	at android.os.Bundle.unparcel(Bundle.java:223)
E/Parcel  ( 2375): 	at android.os.Bundle.getString(Bundle.java:1082)
E/Parcel  ( 2375): 	at android.content.Intent.getStringExtra(Intent.java:4961)
E/Parcel  ( 2375): 	at com.android.server.am.ActivityStack.startActivityLocked(ActivityStack.java:3761)
E/Parcel  ( 2375): 	at com.android.server.am.ActivityStack.startActivityMayWait(ActivityStack.java:4981)
E/Parcel  ( 2375): 	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:3163)
E/Parcel  ( 2375): 	at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:3119)
E/Parcel  ( 2375): 	at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:157)
E/Parcel  ( 2375): 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2115)
E/Parcel  ( 2375): 	at android.os.Binder.execTransact(Binder.java:388)
E/Parcel  ( 2375): 	at dalvik.system.NativeStart.run(Native Method)
E/Parcel  ( 2375): Caused by: java.lang.NoClassDefFoundError: org/thoughtcrime/securesms/crypto/MasterSecret
E/Parcel  ( 2375): 	... 18 more</code>

**Comment by 2-4601** [comment]
Do you have a rooted device? Are you using some permission manager such as XPrivacy?

**Comment by vaeth** [comment]
The device is not rooted.
"App Ops Starter" was used, but all permissions were restored and the problem remains.

**Comment by vaeth** [comment]
I flashed the firmware (an upgrade to kitkat was available for my device).
Unfortunately still the same issue after the upgrade...

**Comment by MacGyverNL** [comment]
I've just run into a probably related bug: After unregistering by unchecking TextSecure messages, then registering again by rechecking it (without leaving that screen), I input my phone number and the phone re-registers. It does not actually fail during this procedure. However, after this process, my identity fingerprint has not changed and my contacts do not need to re-verify my identity.

**Comment by mcginty** [comment]
`Class not found when unmarshalling: org.thoughtcrime.securesms.crypto.MasterSecret`

**Comment by moxie0** [comment]
@MacGyverNL That's the intended behavior.

@vaeth There's something seriously wrong with your device, your OS, or the APK you've installed.  The classloader isn't finding a basic class that's included with the package.

**Comment by MacGyverNL** [comment]
@moxie0 It was my understanding that the fingerprint is derived from the key in use; does this imply that regenerating keys this way does not actually change the key, or is my understanding of the source of the fingerprint incorrect? I agree that from a usability perspective this may be desired, but I'm confused about what I just achieved by re-registering.

**Comment by moxie0** [comment]
@MacGyverNL The best place for support questions like this is the support center (http://support.whispersystems.org) or emailing support@whispersystems.org Thanks!

**Comment by vaeth** [comment]
After a factory reset, TextSecure is now working again.
Whatever it was: It had survived a full firmware flash, reinstallations of TextSecure and deinstallation of almost all apps, but not a factory reset...

It is strange that TextSecure was essentially the only app exhibiting some broken behaviour (otherwise, I would not have opened the bug). For instance, RedPhone had no such problem...
