### ISSUE TITLE
Received messages info always has received timestamp before sent timestamp

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#3289]
When I look at my sms/TS message info for received messages they always have the received time before the sent time. So received time could be 8:01:25 and sent time would be 8:01:30, for example.  This is with users of any network and timezone as far as I can tell. Did they happen to get switched accidentally in the code? The difference in time is just a few seconds which would look right to me. Running 2.16.3 on galaxy s4 stock Verizon 5.0.1.

**Comment by claenn** [comment]
Can't confirm in general. Happens only with one special contact, android based. 
Don't know whether I should point her to https://play.google.com/store/apps/details?id=ru.org.amip.ClockSync ;)

Regards

**Comment by moxie0** [comment]
someone's clock is incorrect somewhere

**Comment by jeremymasters** [comment]
@claenn thanks for the tip! @moxie0 must have been my upgrade to 5.0.1. Before that it was dead on. Sorry about that. :-(

**Comment by safiely** [comment]
NO



Sent from Windows Mail



From: jeremymasters
Sent: ‎Sunday‎, ‎May‎ ‎31‎, ‎2015 ‎11‎:‎26‎ ‎PM
To: WhisperSystems/TextSecure


@claenn thanks for the tip! @moxie0 must have been my upgrade to 5.0.1. Before that it was dead on. Sorry about that. :-(
