### ISSUE TITLE
Add encrypted phone calls to textsecure

### ISSUE THREAD

**Issue by gonzalezb** [WhisperSystems/TextSecure#3294]
Having a completely separate app for encrypted phone calls on android is really odd you should make it like signal all in one.

**Comment by 1337sup3rh4x0r** [comment]
That is the long term plan. It was communicated here somewhere. I guess closing this topic is his way to say that. :)

**Comment by mawed** [comment]
unfortunately there is no official statement about this.

Original there was the plan to publish textsecure & Redphone as two apps on android and iOs.
Later it was said, on iOS it will start directly with Signal without any comment about this topic.

Also on  the support page of whispersystems.org there is no official statement about it.
As Redphone is really buggy, I understand totally the interest in the next steps regarding Signal/Redphone.

This shouldn't be a critism, I'm really happy with textsecure!
