### ISSUE TITLE
units

### ISSUE THREAD

**Issue by maniette** [WhisperSystems/TextSecure#3295]
On the textSecure panel showing the list of threads, each of them has a field showing the time elapsed since the last message. 

typically I read something like "11 mins".

I wonder what the s after min stands for. Unit for minute is min, and units do not take plural form.

Unfortunately I must say that this trend of putting plural mark to units is more and more common in the US, and it appears that it is getting more common in other countries as well. Spreading that nonsense is definitely not good so I suggest that the "plural unit issue" be taken care of as soon as possible.

Check also for the hour, I am pretty sure that soon some "hrs" will show up. "h" would actually be the best, while "hr" being also accepted. 

Thank you

**Comment by 2-4601** [comment]
Yeah, it's a plural abbreviation. I thought at first that this is an issue with the Java date libraries used (as they seem to suck) but its defined here: https://github.com/WhisperSystems/TextSecure/blob/master/res/values/strings.xml#L700

**Comment by maniette** [comment]
That is an error. How can we correct that library? Units do not take plural.

**Comment by jeremymasters** [comment]
This seems a little pedantic, imo.

**Comment by maniette** [comment]
No, I see that this error spreads automatically in other languages, that is a real issue.

**Comment by mcginty** [comment]
definitely pedantic... and accurate. http://physics.nist.gov/cuu/Units/checklist.html

**Comment by agrajaghh** [comment]
I could fix it, you got more important stuff to do ;)
