### ISSUE TITLE
Can receive but not send secured texts

### ISSUE THREAD

**Issue by ktlewin** [WhisperSystems/TextSecure#3298]
Samsung Galaxy S5 Android 5.0
Could send encrypted texts even after update of 1 June 2015.

**Comment by ktlewin** [comment]
All Gists

ktlewin

 Star0 Fork0

 anonymous / cat.log SECRET

Created 16 minutes ago

 Code Revisions1

Embed URL

" readonly="readonly" style="box-sizing: border-box; font-family: Consolas, 'Liberation Mono', Menlo, Courier, monospace; font-size: 11px; margin: 0px; line-height: 1.4; font-style: normal; font-variant: normal; font-weight: normal; min-height: 26px; padding: 4px 5px; outline: none; color: rgb(153, 153, 153); background-color: rgb(255, 255, 255); border: 1px solid rgb(204, 204, 204); border-top-left-radius: 3px; border-top-right-radius: 0px; border-bottom-right-radius: 0px; border-bottom-left-radius: 3px; -webkit-box-shadow: rgba(0, 0, 0, 0.0745098) 0px 1px 2px inset; box-shadow: rgba(0, 0, 0, 0.0745098) 0px 1px 2px inset; vertical-align: middle; display: table-cell; width: 135px; white-space: nowrap; background-position: 100% 50%; background-repeat: no-repeat no-repeat;">

HTTPS clone URL

You can clone with HTTPS or SSH.

 Download Gist

 cat.log

Raw

123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899100101102103104105106

Device : samsung SM-G900T (kltetmo) 

Android : 5.0 (G900TUVU1DOB1, LRX21T.G900TUVU1DOB1) 

Memory : 25M (0.11% used, 128M max) 

Memclass: 128 

OS Host : SWDD5507 

App : TextSecure 2.16.3 

  

--------- beginning of main 

W/PassphraseRequiredActionBarActivity( 3146): routeApplicationState(), state: 0 

W/PassphraseRequiredActionBarActivity( 3146): initializeClearKeyReceiver() 

W/DirectoryRefreshListener( 3146): Scheduling for: 1433225312625 

D/Activity( 3146): performCreate Call secproduct feature valuefalse 

D/Activity( 3146): performCreate Call debug elastic valuetrue 

D/ResourcesManager( 3146): creating new AssetManager and set to /system/priv-app/SecMms_Candy/SecMms_Candy.apk 

W/KeyCachingService( 3146): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT 

W/KeyCachingService( 3146): Incrementing activity count... 

W/MessageRetrievalService( 3146): Active Count: 1 

W/MessageRetrievalService( 3146): Network requirement: true, active activities: 1, push pending: 0 

W/MessageRetrievalService( 3146): Making websocket connection.... 

W/WebSocketConnection( 3146): WSC connect()... 

W/OkHttpClientWrapper( 3146): Connecting to: wss://textsecure-service.whispersystems.org/v1/websocket/?login=%s&password=%s 

W/MessageRetrievalService( 3146): Network requirement: true, active activities: 1, push pending: 0 

W/MessageRetrievalService( 3146): Reading message... 

I/Timeline( 3146): Timeline: Activity_idle id: android.os.BinderProxy@38ef7c06 time:2330756 

W/WebSocketConnection( 3146): onConnected() 

W/KeyCachingService( 3146): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT 

W/KeyCachingService( 3146): Decrementing activity count... 

W/MessageRetrievalService( 3146): Active Count: 0 

I/Timeline( 3146): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:2337146 

E/SELinux (28647): [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL 

D/TimaKeyStoreProvider(28647): TimaSignature is unavailable 

D/ActivityThread(28647): Added TimaKeyStore provider 

D/ResourcesManager(28647): creating new AssetManager and set to /data/app/org.thoughtcrime.securesms-2/base.apk 

W/PartProvider(28647): onCreate() 

D/Activity(28647): performCreate Call secproduct feature valuefalse 

D/Activity(28647): performCreate Call debug elastic valuetrue 

W/MessageRetrievalService(28647): Waiting for websocket state change.... 

W/MessageRetrievalService(28647): Network requirement: true, active activities: 0, push pending: 0 

W/MessageRetrievalService(28647): Network requirement: true, active activities: 0, push pending: 0 

W/PassphraseRequiredActionBarActivity(28647): routeApplicationState(), state: 0 

W/PassphraseRequiredActionBarActivity(28647): initializeClearKeyReceiver() 

W/DirectoryRefreshListener(28647): Scheduling for: 1433225312625 

D/Activity(28647): performCreate Call secproduct feature valuefalse 

D/Activity(28647): performCreate Call debug elastic valuetrue 

D/ResourcesManager(28647): creating new AssetManager and set to /system/priv-app/SecMms_Candy/SecMms_Candy.apk 

D/OpenGLRenderer(28647): Render dirty regions requested: true 

W/KeyCachingService(28647): onCreate() 

W/service (28647): Broadcasting new secret... 

W/KeyCachingService(28647): onStartCommand, null 

W/KeyCachingService(28647): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT 

W/KeyCachingService(28647): Incrementing activity count... 

W/MessageRetrievalService(28647): Active Count: 1 

W/MessageRetrievalService(28647): Network requirement: true, active activities: 1, push pending: 0 

W/MessageRetrievalService(28647): Making websocket connection.... 

W/WebSocketConnection(28647): WSC connect()... 

W/MmsSmsDatabase(28647): Executing query: SELECT _id, body, read, type, address, address_device_id, subject, thread_id, status, date_sent, date_received, m_type, msg_box, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (read = 0) ORDER BY date_received ASC) 

W/OkHttpClientWrapper(28647): Connecting to: wss://textsecure-service.whispersystems.org/v1/websocket/?login=%s&password=%s 

W/MessageRetrievalService(28647): Network requirement: true, active activities: 1, push pending: 0 

W/MessageRetrievalService(28647): Reading message... 

I/Adreno-EGL(28647): <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: () 

I/Adreno-EGL(28647): OpenGL ES Shader Compiler Version: E031.25.01.03 

I/Adreno-EGL(28647): Build Date: 10/28/14 Tue 

I/Adreno-EGL(28647): Local Branch: LA.BF.1.1_RB1_20141028_021_patches2 

I/Adreno-EGL(28647): Remote Branch: 

I/Adreno-EGL(28647): Local Patches: 

I/Adreno-EGL(28647): Reconstruct Branch: 

I/OpenGLRenderer(28647): Initialized EGL, version 1.4 

I/OpenGLRenderer(28647): HWUI protection enabled for context , &this =0xaefa41f0 ,&mEglDisplay = 1 , &mEglConfig = 8 

D/OpenGLRenderer(28647): Enabling debug mode 0 

W/EmojiProvider(28647): draw size: 102.0x96.0 

W/RecipientProvider(28647): Cache miss [ASYNC]! 

W/RecipientProvider(28647): Cache miss [ASYNC]! 

W/RecipientProvider(28647): Cache miss [ASYNC]! 

W/RecipientProvider(28647): Cache miss [ASYNC]! 

W/RecipientProvider(28647): Cache miss [ASYNC]! 

W/RecipientProvider(28647): Cache miss [ASYNC]! 

W/RecipientProvider(28647): Cache miss [ASYNC]! 

W/RecipientProvider(28647): Cache miss [ASYNC]! 

W/WebSocketConnection(28647): onConnected() 

I/Timeline(28647): Timeline: Activity_idle id: android.os.BinderProxy@e024efe time:2371326 

D/ViewRootImpl(28647): ViewPostImeInputStage ACTION_DOWN 

D/AbsListView(28647): Get MotionRecognitionManager 

D/ViewRootImpl(28647): ViewPostImeInputStage ACTION_DOWN 

I/Timeline(28647): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:2377639 

E/ViewRootImpl(28647): sendUserActionEvent() mView == null 

W/KeyCachingService(28647): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT 

W/KeyCachingService(28647): Decrementing activity count... 

W/MessageRetrievalService(28647): Active Count: 0 

W/PassphraseRequiredActionBarActivity(28647): routeApplicationState(), state: 0 

W/PassphraseRequiredActionBarActivity(28647): initializeClearKeyReceiver() 

D/Activity(28647): performCreate Call secproduct feature valuefalse 

D/Activity(28647): performCreate Call debug elastic valuetrue 

D/AbsListView(28647): Get MotionRecognitionManager 

W/KeyCachingService(28647): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT 

W/KeyCachingService(28647): Incrementing activity count... 

W/MessageRetrievalService(28647): Active Count: 1 

I/Timeline(28647): Timeline: Activity_idle id: android.os.BinderProxy@20ef9842 time:2377885 

D/ViewRootImpl(28647): ViewPostImeInputStage ACTION_DOWN 

D/AbsListView(28647): Get MotionRecognitionManager 

D/ViewRootImpl(28647): ViewPostImeInputStage ACTION_DOWN 

I/Timeline(28647): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:2389007 

W/KeyCachingService(28647): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT 

W/KeyCachingService(28647): Decrementing activity count... 

W/MessageRetrievalService(28647): Active Count: 0 

D/Activity(28647): performCreate Call secproduct feature valuefalse 

D/Activity(28647): performCreate Call debug elastic valuetrue 

Write PreviewParsed as Markdown Edit in fullscreen

Comment

Status API Blog About© 2015 GitHub, Inc. Terms Privacy Security Contact

**Comment by agrajaghh** [comment]
readable:
````
Device : samsung SM-G900T (kltetmo)
Android : 5.0 (G900TUVU1DOB1, LRX21T.G900TUVU1DOB1)
Memory : 25M (0.11% used, 128M max)
Memclass: 128
OS Host : SWDD5507
App : TextSecure 2.16.3
 
--------- beginning of main
W/PassphraseRequiredActionBarActivity( 3146): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity( 3146): initializeClearKeyReceiver()
W/DirectoryRefreshListener( 3146): Scheduling for: 1433225312625
D/Activity( 3146): performCreate Call secproduct feature valuefalse
D/Activity( 3146): performCreate Call debug elastic valuetrue
D/ResourcesManager( 3146): creating new AssetManager and set to /system/priv-app/SecMms_Candy/SecMms_Candy.apk
W/KeyCachingService( 3146): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService( 3146): Incrementing activity count...
W/MessageRetrievalService( 3146): Active Count: 1
W/MessageRetrievalService( 3146): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService( 3146): Making websocket connection....
W/WebSocketConnection( 3146): WSC connect()...
W/OkHttpClientWrapper( 3146): Connecting to: wss://textsecure-service.whispersystems.org/v1/websocket/?login=%s&password=%s
W/MessageRetrievalService( 3146): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService( 3146): Reading message...
I/Timeline( 3146): Timeline: Activity_idle id: android.os.BinderProxy@38ef7c0 time:2330756
W/WebSocketConnection( 3146): onConnected()
W/KeyCachingService( 3146): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService( 3146): Decrementing activity count...
W/MessageRetrievalService( 3146): Active Count: 0
I/Timeline( 3146): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:2337146
E/SELinux (28647): [DEBUG] get_category: variable seinfo: default sensitivity: NULL, cateogry: NULL
D/TimaKeyStoreProvider(28647): TimaSignature is unavailable
D/ActivityThread(28647): Added TimaKeyStore provider
D/ResourcesManager(28647): creating new AssetManager and set to /data/app/org.thoughtcrime.securesms-2/base.apk
W/PartProvider(28647): onCreate()
D/Activity(28647): performCreate Call secproduct feature valuefalse
D/Activity(28647): performCreate Call debug elastic valuetrue
W/MessageRetrievalService(28647): Waiting for websocket state change....
W/MessageRetrievalService(28647): Network requirement: true, active activities: 0, push pending: 0
W/MessageRetrievalService(28647): Network requirement: true, active activities: 0, push pending: 0
W/PassphraseRequiredActionBarActivity(28647): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity(28647): initializeClearKeyReceiver()
W/DirectoryRefreshListener(28647): Scheduling for: 1433225312625
D/Activity(28647): performCreate Call secproduct feature valuefalse
D/Activity(28647): performCreate Call debug elastic valuetrue
D/ResourcesManager(28647): creating new AssetManager and set to /system/priv-app/SecMms_Candy/SecMms_Candy.apk
D/OpenGLRenderer(28647): Render dirty regions requested: true
W/KeyCachingService(28647): onCreate()
W/service (28647): Broadcasting new secret...
W/KeyCachingService(28647): onStartCommand, null
W/KeyCachingService(28647): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService(28647): Incrementing activity count...
W/MessageRetrievalService(28647): Active Count: 1
W/MessageRetrievalService(28647): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService(28647): Making websocket connection....
W/WebSocketConnection(28647): WSC connect()...
W/MmsSmsDatabase(28647): Executing query: SELECT _id, body, read, type, address, address_device_id, subject, thread_id, status, date_sent, date_received, m_type, msg_box, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (read = 0) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (read = 0) ORDER BY date_received ASC)
W/OkHttpClientWrapper(28647): Connecting to: wss://textsecure-service.whispersystems.org/v1/websocket/?login=%s&password=%s
W/MessageRetrievalService(28647): Network requirement: true, active activities: 1, push pending: 0
W/MessageRetrievalService(28647): Reading message...
I/Adreno-EGL(28647): : EGL 1.4 QUALCOMM build: ()
I/Adreno-EGL(28647): OpenGL ES Shader Compiler Version: E031.25.01.03
I/Adreno-EGL(28647): Build Date: 10/28/14 Tue
I/Adreno-EGL(28647): Local Branch: LA.BF.1.1_RB1_20141028_021_patches2
I/Adreno-EGL(28647): Remote Branch:
I/Adreno-EGL(28647): Local Patches:
I/Adreno-EGL(28647): Reconstruct Branch:
I/OpenGLRenderer(28647): Initialized EGL, version 1.4
I/OpenGLRenderer(28647): HWUI protection enabled for context , &this =0xaefa41f0 ,&mEglDisplay = 1 , &mEglConfig = 8
D/OpenGLRenderer(28647): Enabling debug mode 0
W/EmojiProvider(28647): draw size: 102.0x96.0
W/RecipientProvider(28647): Cache miss [ASYNC]!
W/RecipientProvider(28647): Cache miss [ASYNC]!
W/RecipientProvider(28647): Cache miss [ASYNC]!
W/RecipientProvider(28647): Cache miss [ASYNC]!
W/RecipientProvider(28647): Cache miss [ASYNC]!
W/RecipientProvider(28647): Cache miss [ASYNC]!
W/RecipientProvider(28647): Cache miss [ASYNC]!
W/RecipientProvider(28647): Cache miss [ASYNC]!
W/WebSocketConnection(28647): onConnected()
I/Timeline(28647): Timeline: Activity_idle id: android.os.BinderProxy@e024efe time:2371326
D/ViewRootImpl(28647): ViewPostImeInputStage ACTION_DOWN
D/AbsListView(28647): Get MotionRecognitionManager
D/ViewRootImpl(28647): ViewPostImeInputStage ACTION_DOWN
I/Timeline(28647): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:2377639
E/ViewRootImpl(28647): sendUserActionEvent() mView == null
W/KeyCachingService(28647): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService(28647): Decrementing activity count...
W/MessageRetrievalService(28647): Active Count: 0
W/PassphraseRequiredActionBarActivity(28647): routeApplicationState(), state: 0
W/PassphraseRequiredActionBarActivity(28647): initializeClearKeyReceiver()
D/Activity(28647): performCreate Call secproduct feature valuefalse
D/Activity(28647): performCreate Call debug elastic valuetrue
D/AbsListView(28647): Get MotionRecognitionManager
W/KeyCachingService(28647): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_START_EVENT
W/KeyCachingService(28647): Incrementing activity count...
W/MessageRetrievalService(28647): Active Count: 1
I/Timeline(28647): Timeline: Activity_idle id: android.os.BinderProxy@20ef984 time:2377885
D/ViewRootImpl(28647): ViewPostImeInputStage ACTION_DOWN
D/AbsListView(28647): Get MotionRecognitionManager
D/ViewRootImpl(28647): ViewPostImeInputStage ACTION_DOWN
I/Timeline(28647): Timeline: Activity_launch_request id:org.thoughtcrime.securesms time:2389007
W/KeyCachingService(28647): onStartCommand, org.thoughtcrime.securesms.service.action.ACTIVITY_STOP_EVENT
W/KeyCachingService(28647): Decrementing activity count...
W/MessageRetrievalService(28647): Active Count: 0
D/Activity(28647): performCreate Call secproduct feature valuefalse
D/Activity(28647): performCreate Call debug elastic valuetrue
Write PreviewParsed as Markdown Edit in fullscreen
````

**Comment by ktlewin** [comment]
Still cannot send encrypted texts after update of 2 June.

**Comment by riyapenn** [comment]
Is this still an issue?

**Comment by ktlewin** [comment]
No, since I uninstalled it and installed SMSSecure. 

On Wednesday 21/10/15 6:00 PM, riyapenn wrote:
>
> Is this still an issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WhisperSystems/TextSecure/issues/3298#issuecomment-150037331>.
>


-- 
"Language shapes the way we think, and determines what we can think about."
 Benjamin Lee Whorf
