### ISSUE TITLE
crash when updating push directory

### ISSUE THREAD

**Issue by ghost** [WhisperSystems/TextSecure#3300]
Updating push directory crashes textsecure if there is no internet connection

**Comment by moxie0** [comment]
can't do anything without a debug log

**Comment by volcano99** [comment]
Can't post a debug log with no Internet connection -.-

**Comment by 2-4601** [comment]
@volcano99 The text area in the in app _Submit Debug Log_ view is copyable. So it's possible to paste it to a file for later use.

**Comment by volcano99** [comment]
I can't click submit though, it says network failure...

**Comment by agrajaghh** [comment]
You don't have to click submit, just copy the text above the submit button like @2-4601 said

its looks like that for me:
![screenshot_2015-06-02-13-55-22](https://cloud.githubusercontent.com/assets/5296073/7935181/17bef4fc-092f-11e5-81ce-475f5f9bb784.png)

**Comment by volcano99** [comment]
Oh I see, sorry I didn't understand what he (he?) meant. I will do that when I get the chance

**Comment by riyapenn** [comment]
Closed for no new information (no log or other users with same issue) in over 4 mo.
