### ISSUE TITLE
Emojis are badly cropped

### ISSUE THREAD

**Issue by Murazaki** [WhisperSystems/TextSecure#3308]
On LG G3 running Android 5.0, I have this bad emoji issue : http://imgur.com/MK9ckFK

**Comment by 5boro** [comment]
similar to #2957

**Comment by Murazaki** [comment]
I'm on 2.16.3

**Comment by 5boro** [comment]
This should be fixed in the next beta : 964a24d32bcd88a93c86bb28e58d6642f0c52152

**Comment by 2-4601** [comment]
Not only similar to #2957 but **duplicate**.
@Murazaki Please close this.
