### ISSUE TITLE
No media thumbnail when opening from notification 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3309]
On my Z1 compact with  5.0.2
Tapping to heads up notification 
I just get the download arrow, until I reenter the convo. 

https://gist.github.com/993f5ebff6327e9e2dc8

**Comment by McLoo** [comment]
Seems to be only happening when going through the passphrase prompt. 
Can't reproduce unlocked

**Comment by McLoo** [comment]
Oh, rapping the download arrow brings the correct image view, so it's only a thumbnail thingy...

**Comment by mcginty** [comment]
@moxie0 you sure this isn't to do with https://github.com/WhisperSystems/TextSecure/commit/082985276f4abd066f9c4f07052ab5c82f576c34? In that change I don't see any checks for if the message is "pendingPush" in `equals`

**Comment by McLoo** [comment]
whatever that was, it's gone
