### ISSUE TITLE
Attached jpeg files aren't correctly displayed (orientation)

### ISSUE THREAD

**Issue by arichnad** [WhisperSystems/TextSecure#331]
Using a samsung note 2.  I can test this on some other devices if you'd like.

I'm not sure if it's a problem that would show up in the MMS or not, but this image isn't correctly displayed.  The orientation in the jpeg isn't being used correctly to display the image.  I can send you the source jpeg if you'd like.

The screenshot doesn't have the hue correctly, but that was just a problem with my screenshot application.

![image-not-correctly-rotated](https://f.cloud.github.com/assets/501773/1049957/b17903bc-10b1-11e3-80b5-5346da0b5aac.png)

Also attached is what happens when I use the default messaging app.

![default-app](https://f.cloud.github.com/assets/501773/1049985/54d9c2b2-10b2-11e3-938e-75eb5aaf1359.png)

**Comment by KostyaBakay** [comment]
I had the same problem, maybe this solution will be useful for you.
`                Matrix matrix = new Matrix();
                matrix.postRotate(getImageOrientation(data));

    private int getImageOrientation(Intent data) {
        Uri imageUri = data.getData();
        String[] orientationColumn = {MediaStore.Images.Media.ORIENTATION};
        Cursor cur = getActivity().getContentResolver().query(imageUri, orientationColumn, null, null, null);
        int orientation = -1;
        if (cur != null && cur.moveToFirst()) {
            orientation = cur.getInt(cur.getColumnIndex(orientationColumn[0]));
            Log.d("orientation", "Picture orientation: " + orientation);
        } else {
            Log.d("orientation", "Wrong picture orientation: " + orientation);
        }
        if (cur != null) cur.close();

        return orientation;
    }
`

**Comment by keithzg** [comment]
Very confused that this issue is closed, and every related issue seemingly closed as a dupe of this issue or one that ultimately dupes to this issue, yet I still see an utter failure to have photos taken be properly rotated when I or anyone I converse with takes and sends photos via Signal.

**Comment by alan-signal** [comment]
@keithzg I think there are several open ones, like #8611 and #7671.

Possibly more here: https://github.com/signalapp/Signal-Android/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+orientation

Please find the suitable one and add any additional information you may have.
