### ISSUE TITLE
Block texts/messages from users you don't like.

### ISSUE THREAD

**Issue by Thunderpig72** [WhisperSystems/TextSecure#3310]
Hi. I think it's time for TextSecure to join the 21st century by adding one of the most basic features in existence: A blocklist.

If some moron starts sending me push messages, or text messages, I should be able to block the person. I don't really care how, if there is a list I have to add people to or if I press their name in the Text list and choose block, but the matter of fact is that this feature is waaaaaaaaay overdue.

**Comment by agrajaghh** [comment]
duplicate of #222, please close it

**Comment by Thunderpig72** [comment]
It's locked. Thus I made this new thread.

**Comment by 2-4601** [comment]
It's locked for a reason. The devs are aware of it. Opening a new issue does not help it get addressed faster (in fact the opposite).
