### ISSUE TITLE
Make paperclip green or blue to indicate non-secure or textsecure status of attachment

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#3313]
Currently the paperclip in the sending field is a black/white icon. Prior to the paperclip, it was a green or blue airplane indicating transport protocol.  Could that be done to the paperclip as well to be in sync with the airplane to be green or blue?

**Comment by ComeGitSome** [comment]
Unless I'm misunderstanding this issue it seems to be solved. Paperclip is now a blue/white icon when encrypted and grey/white otherwise. 

Version 2.22.2
