### ISSUE TITLE
Feature request: integration with KK Widget

### ISSUE THREAD

**Issue by c-prompt** [WhisperSystems/TextSecure#3314]
[KK Widget](https://play.google.com/store/apps/details?id=com.kk.widget&hl=en) (aka DashClock) has the ability to show text messages on its screen saver but, unfortunately, TextSecure messages don't show. As a result, I no longer can easily see when I receive a text. Would be nice to see these two somehow integrated.

**Comment by claenn** [comment]
@c-promt
Try Dashnotifier.

https://play.google.com/store/apps/details?id=com.umang.dashnotifier

Regards

**Comment by c-prompt** [comment]
Thanks @claenn. I had tried Dashnotifier and it didn't work, which is why I thought there might be something in TextSecure that prevents the integration.

**Comment by c-prompt** [comment]
Nevermind @claenn, it was my bad. For some reason, I had Dashclock Widget set as my Daydream mode instead of KK Widget. Dashnotifier shows when in KK Widget mode.
Please close feature request.
