### ISSUE TITLE
Make the colored first letter symbols as optional [Feature]

### ISSUE THREAD

**Issue by rdbcasillas** [WhisperSystems/TextSecure#3315]
After last week's update I noticed 'colored first letter of the name" symbols inside a circle next. I guess this feature might help in group chats or maybe it was added after noticing it in telegram. But I would love a toggle for this new feature because its making the dark theme look very ugly and functionally it isn't helpful at all. I guess this is super low priority but do consider adding an option to turn this UI design off.

**Comment by moxie0** [comment]
Thanks but we're not going to do this.  The answer is never more options:
https://github.com/WhisperSystems/TextSecure/blob/master/contributing.md#development-ideology
