### ISSUE TITLE
Emojis in messages and message input box are not centered and also do not scale with system font size

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#3317]
Hello,

using TextSecure 2.16.4 on an LG G2 running latest stock ROM (Android 5.0.2 Lollipop), the Emojis in messages and in the message input box are not centered and also do not scale with the system font size.

Here is a screenshot with system font size set to maximum:

![Image](https://cloud.githubusercontent.com/assets/7558360/7948647/41ff6e52-0986-11e5-98a0-2db064d72e31.png)

Here is a screenshot with system font size set to medium:

![Image](https://cloud.githubusercontent.com/assets/7558360/7948648/48393b9a-0986-11e5-8954-368bab834074.png)

Here is a screenshot with system font size set to minimum:

![Image](https://cloud.githubusercontent.com/assets/7558360/7948649/4ddfca3c-0986-11e5-9c45-45552c411432.png)

As you can see, it's more noticeable at larger system font sizes, but still there even at the smallest system font size.

As you can see, the Emojis in the messages and in the message input box are shifted towards the bottom (i.e. not centered) and also obviously do not scale with the system font size.

Could you please fix that?

Regards

**Comment by 5boro** [comment]
This is most visible when comparing to other apps: 
![screenshot_2015-06-03-00-59-05](https://cloud.githubusercontent.com/assets/3460479/7949324/0dc37730-098d-11e5-8561-f2dc8e3541fe.png)
![screenshot_2015-06-03-00-59-11](https://cloud.githubusercontent.com/assets/3460479/7949325/12605fd8-098d-11e5-94ca-43bac4170512.png)
You can also see a difference in size, but that may be more related to #3267
