### ISSUE TITLE
Emojis are full of jaggies / have low resolution 

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#3318]
Hello,

using TextSecure 2.16.4 on an LG G2 running latest stock ROM (Android 5.0.2 Lollipop), the Emojis are full of jaggies / have a low resolution.

It becomes especially noticeable in the Emoji drawer when the system font size is set to a large value, which in turn lets the Emojis become bigger in the Emoji drawer.

Here is a screenshot with system font size set to maximum:

![Image](https://cloud.githubusercontent.com/assets/7558360/7948884/9a5766a2-0988-11e5-898f-31b51417f143.png)

As you can see, the Emojis show a lot of jaggies and seem to have a low resolution.

This can't be an issue with the Google "Noto Color Emoji" Emoji set itself, since it is even available in SVG format from source, see:

https://code.google.com/p/noto/source/browse/?name=master#git%2Fcolor_emoji%2Fsvg

So, could you please fix that?

Regards

**Comment by mcginty** [comment]
They're shrunk for memory and disk consumption reasons. Having a system font at max is an edge case that doesn't warrant the general increase in memory, so that was an intentional decision.

**Comment by wp9015362** [comment]
> @mcginty wrote:
> 
> They're shrunk for memory and disk consumption reasons. Having a system font at max on a large high-density screen is an edge case that doesn't warrant the general increase in memory, so that was an intentional decision.

What do you mean by "shrunk"? They even show the jaggies at the minimum system font size, see (please make sure to watch the screenshot at native resolution):

![Image](https://cloud.githubusercontent.com/assets/7558360/7949526/ee78a7b8-098e-11e5-95c5-d3f64f42834e.png)

Are you sure even that is intentional?

Regards

**Comment by mcginty** [comment]
Yes.

**Comment by wp9015362** [comment]
> @mcginty wrote:
> 
> Having a system font at max on a large high-density screen is an edge case that doesn't warrant the general increase in memory, so that was an intentional decision.

I have now tested it on a small (3.7 inch) low resolution (480×800 pixel) screen.

And it's even noticeable there.

Please do something about those blurry Emojis. They are full of jaggies.

Regards
