### ISSUE TITLE
1. Unregister from Cyanogen 2. Download TS 3. "Bad Encrypted Message"

### ISSUE THREAD

**Issue by NorthwestBased** [WhisperSystems/TextSecure#3322]
Hi. Bear with me here. This could be a problem with Cyanogen, or may be more appropriate for the support form. Feel free to close if either of these are the case.

Android 4.2.2/Samsung SGH-T399/TextSecure 2.16.4
Debug log: https://gist.github.com/35c5e8f3086090a31234

I've mysteriously been registered to Cyanogen's whisperpush server for awhile now (I've never installed cyanogenmod on my device), and finally got around to unregistering myself. Previously, while I was registered, my friend who uses cyanogenmod tried to send me multiple encrypted messages, which would silently fail.

After unregistering from Cyanogen's servers today, I downloaded TextSecure, and successfully registered with my phone number. However, when my friend with cyanogenmod and I tried sending encrypted messages to each other, we received "bad encrypted message" for each message we sent. He tried disabling encryption on his end (in which case i could only send him sms messages) and re-enabling it, but we still got "bad encrypted message" errors. Maybe some sort of problem with key exchanges failing when I was registered to cyanogen servers?

**Comment by 5boro** [comment]
Did you try "end secure session" from the lock on the top right corner?

**Comment by agrajaghh** [comment]
is your friend using TextSecure (if yes, which Version?) or the CyanogenMod Stuff?

**Comment by moxie0** [comment]
unfortunately this is a CM bug, I'm trying to work with them to get their stuff up to speed. @5boro's "end secure session" suggestion is your best bet
