### ISSUE TITLE
Display app version in settings dialogue

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/TextSecure#3324]
The version number is not displayed within the TextSecure app. I suggest to display it at the bottom of the settings dialogue.

Please let me know if I have missed something.

**Comment by 2-4601** [comment]
I usually check the version number from _Settings --> Advanced --> Submit Debug Log_

**Comment by Norbert80** [comment]
Thanks. But I still prefer my suggestion. :-)

**Comment by claenn** [comment]
+1

**Comment by Mihahn** [comment]
Duplicate of #1356 #1501 #2053  #2742
But I'd love to see that feature, too!

**Comment by RiseT** [comment]
The fork SMSSecure has already completed this. One possibility is just pulling their code.
