### ISSUE TITLE
Can't forward picture message

### ISSUE THREAD

**Issue by peskykid** [WhisperSystems/TextSecure#3341]
Picture message sent via mms or textSecure protocol cannot be forwarded to another recipient.

**Comment by peskykid** [comment]
Samsung Gs4... Android version.. 4.2.2 - root access

**Comment by 5boro** [comment]
Are you asking for

**Comment by McLoo** [comment]
PR #3311 looks like it takes care of that behavior :grin:

**Comment by peskykid** [comment]
My apologies...
