### ISSUE TITLE
Picture message failure

### ISSUE THREAD

**Issue by skulumani** [WhisperSystems/TextSecure#3347]
I am running into a problem trying to send a picture on my 1st Gen Moto X running 4.4.4. I'm using TextSecure 2.16.4 in data mode.

I took a photo in potrait mode using both the camera app and the in-app option to take a photo. Both times the message will appear in the text window but fail to send. 

Here's a log from immediately after the failure

https://gist.github.com/anonymous/52824d6ed48b2be2a32f

I verified that I could send a different photo (in landscape mode) and captured another debug log here

https://gist.github.com/anonymous/7f056f9973425195b26c

I have tried closing and reopening TextSecure without success. It seems specific to this photo as other photos (both taken on the phone or from other sources) are able to be sent. I'm not sure if it's the subject (as other issues mentioned grass being hard to compress) or the orientation of the photo.

This seems similar to #3070 or #3028. Also seems like this might have just recently been fixed in version 2.17. Sorry if this is a duplicate.

Picture [here](http://i.imgur.com/fxUaZoM.jpg)

**Comment by 2-4601** [comment]
I tried sending your photo of this magnificent cat stretching on the grass.

**TS 2.17.0, Nexus 4, stock Android 5.1.1:**
Could **not** reproduce. Everything works as expected.

**TS 2.17.0, Huawei U8800, Android 4.0.4**
Cat refuses to get sent. It just lays on the grass and does not wan't to go to the Internet.
![screenshot_2015-06-05-14-45-21](https://cloud.githubusercontent.com/assets/174176/8005459/f938d622-0b92-11e5-9219-424ffb2c5097.png)
![screenshot_2015-06-05-14-45-42](https://cloud.githubusercontent.com/assets/174176/8005463/003bf1de-0b93-11e5-8da8-85017e5aca63.png)
![screenshot_2015-06-05-14-45-50](https://cloud.githubusercontent.com/assets/174176/8005465/072a6bf6-0b93-11e5-9fdc-4dd15d16308f.png)
Resending always fails.
And clicking on the thumbnail preview opens a the image view but the picture is not there. Just black background.

**Comment by mcginty** [comment]
The OutOfMemoryError we see was actually caught and handled correctly, and it seems like some normal pictures are still too large at 50% quality to fit in 420k.

**Comment by mcginty** [comment]
OH dude! I think my bitmap fallback logic is off. `W/BitmapUtil( 7873): rough scale 2432x4320 => 1216x2160` should be scaling to 721-ishx1280-ish

**Comment by mcginty** [comment]
Ok well that explains things.

**Comment by mcginty** [comment]
thanks very much for the clean bug report with sample image @skulumani and @2-4601 for the added testing and garfield references

**Comment by jeremymasters** [comment]
Probably depends on sharpness and detail in the picture.  I have pictures that are double size just by having lots of leaves or grass in the shot.  Maybe after the picture is sized down, you could double-check that size before sending and then re-size again if it's above 420k?  Shouldn't happen often enough for performance concerns on the double-resize.

**Comment by skulumani** [comment]
@mcginty glad I could finally be of assistance. 

I had an idea based on your previous comment. I'm not sure how the compression works within TextSecure but it seems like more useful method would be to vary the compression to fit the requirements.

Given: Image size requirements and original image
Find: Compression ratio such that output is 420k (or some other requirement)

**Comment by skulumani** [comment]
@mcginty glad I could finally be of assistance. 

I had an idea based on your previous comment. I'm not sure how the compression works within TextSecure but it seems like more useful method would be to vary the compression to fit the requirements.

Given: Image size requirements and original image
Find: Compression ratio such that output is 420k (or some other requirement)

**Comment by skulumani** [comment]
@mcginty glad I could finally be of assistance. 

I had an idea based on your previous comment. I'm not sure how the compression works within TextSecure but it seems like more useful method would be to vary the compression to fit the requirements.

Given: Image size requirements and original image
Find: Compression ratio such that output is 420k (or some other requirement)

**Comment by jeremymasters** [comment]
If this is only for TS/push pictures, could we just make it like 512K or is there something magic about 420K?

**Comment by mcginty** [comment]
@skulumani that's exactly what we do already, the resize logic just wasn't working right for particularly large images.
