### ISSUE TITLE
Cannot send SMS to abbreviated dialing (RuntimeException)

### ISSUE THREAD

**Issue by jensseidel** [WhisperSystems/TextSecure#3348]
Sending an SMS to the number 74696 (Simyo, my provider in Germany) fails since upgrading to Android 5.1 (CyanogenMod nightly). I can contact people which normal phone number without problem and also the data connection (without SMS) works. Another SMS application can also send my message, it is only TextSecure which has trouble ...

Model: Samsung Galaxy S3 (Intl)
TextSecure version: 2.14.5

adb logcat

D/lights  ( 2370): set_light_buttons: 0
D/lights  ( 2370): set_light_buttons: 1
W/ConversationActivity( 3815): isManual Selection: false
W/ConversationActivity( 3815): forceSms: false
W/AudioTrack( 2370): AUDIO_OUTPUT_FLAG_FAST denied by client
E/AudioTrack( 2370): AudioTrack::set : Exit
I/LatinIME( 2743): Starting input. Cursor position = 4,4
D/audio_hw_primary( 1974): select_output_device: AUDIO_DEVICE_OUT_SPEAKER
W/MmsSmsDatabase( 3815): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 19) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 19) ORDER BY date_received DESC) LIMIT 1
W/PhoneNumberFormatter( 3815): Got local CC: DE
W/MmsSmsDatabase( 3815): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 19) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 19) ORDER BY date_received ASC)
W/PhoneNumberFormatter( 3815): Got local CC: DE
W/MessageDatabase( 3815): Updating ID: 3356 to base type: 22
W/MmsSmsDatabase( 3815): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 19) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 19) ORDER BY date_received DESC) LIMIT 1
W/MmsSmsDatabase( 3815): Executing query: SELECT _id, body, type, thread_id, address, address_device_id, subject, date_sent, date_received, m_type, msg_box, status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, transport_type FROM (SELECT DISTINCT date_sent * 1 AS date_sent, date * 1 AS date_received, _id, body, read, thread_id, type, address, address_device_id, subject, NULL AS m_type, NULL AS msg_box, status, NULL AS part_count, NULL AS ct_l, NULL AS tr_id, NULL AS m_size, NULL AS exp, NULL AS st, delivery_receipt_count, mismatched_identities, NULL AS network_failures, 'sms' AS transport_type FROM sms WHERE (thread_id = 19) UNION ALL SELECT DISTINCT date * 1000 AS date_sent, date_received * 1000 AS date_received, _id, body, read, thread_id, NULL AS type, address, address_device_id, NULL AS subject, m_type, msg_box, NULL AS status, part_count, ct_l, tr_id, m_size, exp, st, delivery_receipt_count, mismatched_identities, network_failures, 'mms' AS transport_type FROM mms WHERE (thread_id = 19) ORDER BY date_received ASC)
W/SmsSendJob( 3815): Sending message: 3356
D/AndroidRuntime( 4529): Shutting down VM
E/AndroidRuntime( 4529): FATAL EXCEPTION: main
E/AndroidRuntime( 4529): Process: com.android.phone, PID: 4529
E/AndroidRuntime( 4529): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.NEW_OUTGOING_SMS flg=0x10 (has extras) } in com.android.internal.telephony.UiccSmsController$1@1a0382a
E/AndroidRuntime( 4529):        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:877)
E/AndroidRuntime( 4529):        at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 4529):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 4529):        at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 4529):        at android.app.ActivityThread.main(ActivityThread.java:5289)
E/AndroidRuntime( 4529):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4529):        at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4529):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 4529):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 4529): Caused by: java.lang.SecurityException: Calling uid 1001 gave packageorg.thoughtcrime.securesms which is owned by uid 10065
E/AndroidRuntime( 4529):        at com.android.internal.telephony.SmsUsageMonitor.checkCallerIsSystemOrSameApp(SmsUsageMonitor.java:630)
E/AndroidRuntime( 4529):        at com.android.internal.telephony.SmsUsageMonitor.getPremiumSmsPermission(SmsUsageMonitor.java:583)
E/AndroidRuntime( 4529):        at com.android.internal.telephony.SMSDispatcher.checkDestination(SMSDispatcher.java:1168)
E/AndroidRuntime( 4529):        at com.android.internal.telephony.SMSDispatcher.sendRawPdu(SMSDispatcher.java:1107)
E/AndroidRuntime( 4529):        at com.android.internal.telephony.gsm.GsmSMSDispatcher.sendText(GsmSMSDispatcher.java:209)
E/AndroidRuntime( 4529):        at com.android.internal.telephony.ImsSMSDispatcher.sendText(ImsSMSDispatcher.java:220)
E/AndroidRuntime( 4529):        at com.android.internal.telephony.IccSmsInterfaceManager.sendText(IccSmsInterfaceManager.java:494)
E/AndroidRuntime( 4529):        at com.android.internal.telephony.UiccSmsController$1.onReceive(UiccSmsController.java:125)
E/AndroidRuntime( 4529):        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:867)
E/AndroidRuntime( 4529):        ... 8 more
W/DropBoxManagerService( 2370): Dropping: system_app_crash (1984 > 0 bytes)
I/OpenGLRenderer( 2370): Initialized EGL, version 1.4

**Comment by agrajaghh** [comment]
````
D/AndroidRuntime( 4529): Shutting down VM
E/AndroidRuntime( 4529): FATAL EXCEPTION: main
E/AndroidRuntime( 4529): Process: com.android.phone, PID: 4529
E/AndroidRuntime( 4529): java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.NEW_OUTGOING_SMS flg=0x10 (has extras) } in com.android.internal.telephony.UiccSmsController$1@1a0382a
E/AndroidRuntime( 4529): at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:877)
E/AndroidRuntime( 4529): at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime( 4529): at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 4529): at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 4529): at android.app.ActivityThread.main(ActivityThread.java:5289)
E/AndroidRuntime( 4529): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 4529): at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 4529): at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime( 4529): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime( 4529): Caused by: java.lang.SecurityException: Calling uid 1001 gave packageorg.thoughtcrime.securesms which is owned by uid 10065
E/AndroidRuntime( 4529): at com.android.internal.telephony.SmsUsageMonitor.checkCallerIsSystemOrSameApp(SmsUsageMonitor.java:630)
E/AndroidRuntime( 4529): at com.android.internal.telephony.SmsUsageMonitor.getPremiumSmsPermission(SmsUsageMonitor.java:583)
E/AndroidRuntime( 4529): at com.android.internal.telephony.SMSDispatcher.checkDestination(SMSDispatcher.java:1168)
E/AndroidRuntime( 4529): at com.android.internal.telephony.SMSDispatcher.sendRawPdu(SMSDispatcher.java:1107)
E/AndroidRuntime( 4529): at com.android.internal.telephony.gsm.GsmSMSDispatcher.sendText(GsmSMSDispatcher.java:209)
E/AndroidRuntime( 4529): at com.android.internal.telephony.ImsSMSDispatcher.sendText(ImsSMSDispatcher.java:220)
E/AndroidRuntime( 4529): at com.android.internal.telephony.IccSmsInterfaceManager.sendText(IccSmsInterfaceManager.java:494)
E/AndroidRuntime( 4529): at com.android.internal.telephony.UiccSmsController$1.onReceive(UiccSmsController.java:125)
E/AndroidRuntime( 4529): at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:867)
E/AndroidRuntime( 4529): ... 8 more
````

**Comment by moxie0** [comment]
looks like a CM bug (or some other weird selective permissions junk)

**Comment by jensseidel** [comment]
Am Freitag, 5. Juni 2015 schrieb Moxie Marlinspike :

> looks like a CM bug (or some other weird selective permissions junk)
>
I agree for the second backtrace but for the first?

Jens
