### ISSUE TITLE
Keyboard doesn't open to unlock application

### ISSUE THREAD

**Issue by aliceriot** [WhisperSystems/TextSecure#3358]
Device info: Cyanogen Mod 12.1 on a Verizon Galaxy S III. 

App state: open, not unlocked. App is set to use a password to unlock on open or after 4 hours inactivity. 

Basically the screen looks like this:
![textsmall](https://cloud.githubusercontent.com/assets/6207644/8021961/99006d1e-0c83-11e5-9d78-a2fcd4ae6fe0.jpg)
and tapping on the text field or the 'submit' button does not cause the keyboard to come up. I usually have to close and reopen TextSecure to fix the problem. 

[Debug log](https://gist.github.com/anonymous/b6ec87f8633132b44511#file-cat-log)

**Comment by mcginty** [comment]
Thanks for the well-formed bug report! Will look into it.

**Comment by aliceriot** [comment]
This may not be a bug with TextSecure, but instead with CM - I just had the same thing happen with Gmail, and the keyboard wouldn't come up to fill in the 'to' field in a new email until I tapped the 'subject' field. TextSecure only presents one text field, so this workaround is not possible when the application is locked.

**Comment by McLoo** [comment]
@aliceriot should work to tap the menu and then back to the textfield for your workaround

**Comment by aliceriot** [comment]
Tapping the menu icon once doesn't fix the problem, but clicking 'submit debug log' does!

**Comment by Thunderpig72** [comment]
This exact same thing happens for me about one in 50 times with Paranoid Android 4.44 on Galaxy Nexus. It never happened on stock so I think it's a rom issue.

**Comment by aliceriot** [comment]
Alright, well in that case I'm getting a new phone next week on which I probably won't be running a custom rom, so I'll go ahead and close this.
