### ISSUE TITLE
TextSecure incorrectly thinks recipient is registered

### ISSUE THREAD

**Issue by cberzan** [WhisperSystems/TextSecure#3359]
Over the past week I've experienced a very strange failure mode.

1. Me and person P were exhanging unsecured text messages. I was using TextSecure (push registered), while P was using a stock messaging app.
1. At some point, TextSecure on my phone started thinking that P was registered with TextSecure, and switched to sending encrypted messages. I sent a few encrypted messages to P, which P never received.
1. Upon learning that P wasn't receiving my messages, I tried ending the secure session with P on my phone. This had no effect: TextSecure still insisted on sending encrypted messages. I tried de-registering my phone and then registering it again, but that didn't help. Ultimately the only way to reach P was to de-register my phone and keep push disabled :(

The most pressing issue is: Why did TextSecure think P was registered? P never installed TextSecure or Signal, and did not change their phone number, or anything like that.

The secondary issue is: Why did TextSecure not allow me to send plain SMS, even after I selected "end secure session"?

I looked at the log, and the only potentially relevant line I could find was this:

`W/Directory(22806): Adding active token: +*********xx, 47+CqoNE/Fv5gw`

(where `xx` is the last 2 digits of P's phone number, so I know the line corresponds to their account.)

(PS. Is the debug log designed to be safe for posting in public, or is there a document describing which fields should be censored?)

Version info for my device:

```
Device  : LGE Nexus 4 (occam)
Android : 5.1.1 (1836172, LMY47V)
Memory  : 33M (0.13% used, 192M max)
Memclass: 192
OS Host : wpiw7.hot.corp.google.com
App     : TextSecure 2.16.4
```

**Comment by brumsoel** [comment]
> Why did TextSecure think P was registered? P never installed TextSecure or Signal

Does the WS unregister page work for P? https://whispersystems.org/textsecure/unregister/
If not, P is probably registered with Cyanogenmod's Whisperpush service.

**Comment by johanw666** [comment]
How long does P have this number? It could be that the previous owner of the number registered and didn't deregister when the number expired. In that case the unregister link above would also be the answer.

**Comment by cberzan** [comment]
After looking into this further, it is true that P had an old phone that used Cyanogenmod. The unregister link @brumsoel sent says "your number is registered with a different server", which suggests that P is indeed register with Cyanogenmod's Whisperpush. AFAICT there is no easy way to unregister from that (see https://github.com/CyanogenMod/android_external_whispersystems_WhisperPush/issues/8), so I guess we're at a dead end for now. I'm closing this since the issue is more with Cyanogenmod than with TextSecure.

**Comment by brumsoel** [comment]
@cberzan did you try their unregister app? https://plus.google.com/+CyanogenMod/posts/ZdP44tAE9J3

**Comment by brumsoel** [comment]
Ha! Apparently, there is a website for unregistering. Seems like no one found it yet?
https://whispertool.cyanogenmod.org/ (you'll get a warning about an expired SSL cert, dunno if the thing actually works)

**Comment by deekthesqueak** [comment]
I've tried both and they don't seem to work. Anyone have any other suggestions?

**Comment by brumsoel** [comment]
FYI, someone from CyanogenMod confirmed that https://whispertool.cyanogenmod.org/ is the tool to use for unregistering:
https://twitter.com/CyanogenMod/status/618580635804954624

You may need to wait a couple of hours for your un-registration to propagate to the Whispersystems servers before registering with Textsecure.
