### ISSUE TITLE
emojis are too small (2.16.4)

### ISSUE THREAD

**Issue by Hasmaux** [WhisperSystems/TextSecure#3366]
Hello and thank you for doing a nice job!
After updating to 2.16.4 emojis are too small in compose field and message bubble on (similar to issue #3202).
Device info: Samsung Galaxy 3 Mini, Android 4.1.2 and Huawei U8860, Android 4.0.3

**Comment by wp9015362** [comment]
Probably a duplicate of:

https://github.com/WhisperSystems/TextSecure/issues/3317

?

**Comment by mcginty** [comment]
yep looks like it, thanks
