### ISSUE TITLE
TS shows number instead of contacts names in the main screen

### ISSUE THREAD

**Issue by ahamrani** [WhisperSystems/TextSecure#3376]
Hello,

When I open textsecure in the main screen, it displays the number/contacts names just like a flash, every second it displays numbers or contacts names.

Device : Honor 3C Jelly Bean 4.2.2 Emotion UI 2.0

Here is a debug log : https://gist.github.com/anonymous/cc03830f4322e1c1a1f4

Thanks

**Comment by 2-4601** [comment]
Sounds like #3275.

**Comment by ahamrani** [comment]
@2-4601 Many thanks !

I will try to disable thoses managers this evening and give a feedback !

**Comment by ahamrani** [comment]
@2-4601 The only manager that I have allow me to specify if an app can send push notification to the notifications bar (options = Not authorized/Authorized/Notify) also if an app is authorized to startup with android and if an app is allowed l working when the screen is locked(for battery saving). I gave all authorizations but the pictures/names/phone numbers stil flickering. I tried to disable the huawei phone manager but I'm not allowed. I think this is a limitation of this version of EmotionUI/Android jelly bean.

**Comment by 5boro** [comment]
My Friend was able to get it all working, if I remember well the problematic settings were in Security > Privacy for the contacts and in the battery for GCM.

**Comment by ahamrani** [comment]
@5boro Does your friend has the same device with the same version of Emotion UI ? In the configuration panel I didn't find any privacy settings for the contacts. I will post screenshot of the configuration panel as soon as possible.

Cheers.

**Comment by 5boro** [comment]
It's actually an Huawei Honor 6, but with EMUI 3.0.

On mer., juin 10, 2015 at 1:43 PM, Hamrani ahmed < notifications@github.com [notifications@github.com] > wrote:
@5boro [https://github.com/5boro] Does your friend has the same device with the same version of Emotion UI ? In
the configuration panel I didn't find any privacy settings for the contacts. I
will post screenshot of the configuration panel as soon as possible.

Cheers.

—
Reply to this email directly or view it on GitHub
[https://github.com/WhisperSystems/TextSecure/issues/3376#issuecomment-110713454] .[https://github.com/notifications/beacon/ADTNf-7IqksgUpcqZY5MKnOkt1TpZzSWks5oSBpogaJpZM4E8z_n.gif]

**Comment by ahamrani** [comment]
Here screenshots of the phone manager, there is no privacy settings for apps. Also I can't disable the phone manager :+1: 
![textsecure-2015-06-10-235509](https://cloud.githubusercontent.com/assets/1475879/8102501/e29a6326-1020-11e5-8acc-781aca54fd24.jpeg)
![textsecure-2015-06-10-235709](https://cloud.githubusercontent.com/assets/1475879/8102507/e579f408-1020-11e5-967a-776ea66c48d4.jpeg)
![textsecure-2015-06-10-235757](https://cloud.githubusercontent.com/assets/1475879/8102603/8d0aa1fe-1021-11e5-9e10-d001d1cdc5a2.jpeg)

![textsecure-2015-06-10-235839](https://cloud.githubusercontent.com/assets/1475879/8102509/eb89a1a4-1020-11e5-83dc-35f066c9dce7.jpeg)
![textsecure-2015-06-10-235948](https://cloud.githubusercontent.com/assets/1475879/8102510/edfddc3e-1020-11e5-9d81-918b50e37577.jpeg)

**Comment by 5boro** [comment]
@ahamrani Apparemment les paramètres dont je parlait ont été implémentés dans la version 3.0 d'EmotionUI : http://www.anandtech.com/show/8655/the-huawei-ascend-mate-7-review/2 (dernière partie de l'article)

Je reste convaincu que c'est un paramètre de sécurité de l'os qui empèche l'accès aux contacts, tu n'utilise pas Xprivacy ou App Ops?

**Comment by Mihahn** [comment]
@5boro please discuss in english so everybody can understand what you say, not just french speaking people ;)

"Apparently the settings I talked about were implemented in version 3.0 of Emotion UI: http://www.anandtech.com/show/8655/the-huawei-ascend-mate-7-review/2 (last part of the article)

I'm still convinced that there are some security settings in the OS that deny the access to the contacts. You don't use Xprivacy or App Ops?"

**Comment by 5boro** [comment]
@Mihahn :+1: You should join the [French translation team](https://www.transifex.com/projects/p/textsecure-official/language/fr/)

**Comment by Mihahn** [comment]
@5boro nah, I'm not a native speaker and I'm just learning french at school... and I'm not really good at it :see_no_evil:

**Comment by ahamrani** [comment]
The device is not rooted, so cannot install Xprivacy or App Ops.

That's what I thought, I think I will have to wait that Honor deploy an update for the european version of my device or I will have to root it.

I found a huawei home made privacy gard in the app manager, but unfortunatly I cannot disable it and it hasn't control panel for app settings, it's shame.

P.S: Honor est réelement une sous-marque de huawei...

**Comment by 5boro** [comment]
It does seem to exist though : https://youtu.be/swrT6ePAvlo?t=60

**Comment by ahamrani** [comment]
In the panel "Applis protégées" there is the list of apps allowed to run when the screen is locked. I think this is for battery optimisation. I already Allowed TextSecure without any change in the behavior.

Yes it's strange that in the video there is a permissions manager, but believe me I didn't find it in mine, maybe it's a feature for the EMUI 2.3 ?

**Comment by 5boro** [comment]
If the permission manager is not installed, there is no reason for TSecure not to be able to access your contacts. It has to be present, maybe it's only accessible to root users...

**Comment by ahamrani** [comment]
@5boro Yeah you're right, I think I don't have choice, I'll have to root it.

**Comment by Mihahn** [comment]
You could try [this app](https://play.google.com/store/apps/details?id=com.huawei.pmplus&hl=de) from the Google Play Store!

**Comment by ahamrani** [comment]
Since there is no other solutions than root my device or wait for an update from Honor, I guess it's better to close this issue.

Thanks everyone !

**Comment by 5boro** [comment]
@ahamrani If I were you I would go ask on Huawei/EmUI related forums before voiding my warranty...

**Comment by Mihahn** [comment]
A friend of mine owning a Huawei P6 with Android 4.4.2 and EmotionUI 2.3 has the same problem. Contacts are kind of flashing every few seconds and he only receives messages on opening TextSecure. There has to be a solution without rooting the phone...

**Comment by ahamrani** [comment]
@5boro This morning I called Huawei/Honor support center, they told me that my device is not produced anymore, that they don't know if an update will be deployed for the European version and if it is, it will available automatically on my device.
In xdadevelopers forums(http://forum.xda-developers.com/t/honor-3c), there are some guides showing how to update to another version, but this is not official...

@Mihahn I thought that Emui 2.3 has the permissions manager ? The real question is why the home made permissions/privacy manager doesn't allow TextSecure accessing contact properly ? Does TextSecure behavior is considered as malware/bloatware ? Why ?

**Comment by ahamrani** [comment]
I have a good news and a bad news, good news is that pictures/names/numbers aren't flickering anymore since the latest update 2.18.2. Bad news is that the app is very slow. I will open a new issue and close this one. thanks every one !
