### ISSUE TITLE
unstable network - an sms sent 46x

### ISSUE THREAD

**Issue by smidm** [WhisperSystems/TextSecure#3379]
I sent an sms to a non TextSecure user while riding a subway with the gsm network available only on stations. TextSecure tried to deliver the message and sent it by an error 46 times.

Device  : HTC HTC One V (htc_primou)
Android : 4.0.3 (92876.6, IML74K)
Memory  : 6M (0.20% used, 48M max)
Memclass: 48
OS Host : abm024
App     : TextSecure 2.16.2

**Comment by agrajaghh** [comment]
we need the full debug log not just the device information

**Comment by smidm** [comment]
I got only this when I used the "send debug log" feature.

**Comment by moxie0** [comment]
Can't do anything without a debug log.  TS does retry sending, if the OS reports that a message failed to send when it was actually sent successfully, there's nothing we can do but believe what the OS tells us.
