### ISSUE TITLE
Not possible to know if a contact is verified or not

### ISSUE THREAD

**Issue by ElucGeek** [WhisperSystems/TextSecure#3385]
If I look at my TextSecure contact list or directly in a contact conversation, there is no way to know if a contact has been verified or not. In case I'm not sure I can only verify the contact again to be 100% sure. It would be nice to have an indication of verified contact. I.e. it could be an orange dot for unverified and green dot for verified, or the lock in the conversation view could change is color when it's verified. Or at least on the "Verify identity" screen you should write: "Successfully verified", Verified" or "Verified on + date/time", I don't know what is more suitable but I'm sure it would be a very useful and important feature to help people use the app in the best possible way.

**Comment by agrajaghh** [comment]
duplicate of #910

**Comment by ElucGeek** [comment]
Ok sorry, I've searched with verify, veried, verification in the issue titles but I haven't noticed this one.
