### ISSUE TITLE
tile person images to denote group mms chats

### ISSUE THREAD

**Issue by ewmalmbe** [WhisperSystems/TextSecure#3386]
When viewing the conversation list, all mms group conversation icons only display for THE FIRST PERSON listed in the group chat. If a image is available, it will display only one contact image, otherwise if an contact image is not available, the the first letter of the first contact's first name is shown. 

I would like to see group chat icons in the conversation list denoted with a tile view comprised of the group contacts (possibly up to 4 tiles). It seems the special TextSecure groups have a stock grey icon to denote those type of chats since they have a group title/name.

For example, if there are 3 contacts in the group MMS (2 friends plus yourself) the visual icon on the conversation list would show a vertically split tile view of your contacts photo or the Letter of their first name if a photo is not available. For reference, is similar to the Google hangout view.

[_][_]

[_][_]
[ __ ]

[_][_]
[_][_]

Consider similar feature for the special TextSecure group icon. 

 version 2.16.4

**Comment by rhodey** [comment]
basically same as #2558 & #1033, closing. @moxie0 I fixed this months ago, please take another look at my fix or assign these two issues to yourself >> #3020

**Comment by brumsoel** [comment]
@rhodey aren't these separate issues? I think @ewmalmbe's report is about how groups with non-TS-users (via MMS) show up in the conversation list, not in a notification. There's of course no possibility to set a group avatar for these, so TS simply displays the first group member's picture.

This is by no means a huge problem, but from the picture you cannot immediately tell it's a group conversation.

**Comment by rhodey** [comment]
@brumsoel you're right, thanks for the help :) I think I've read too many issue reports today.
