### ISSUE TITLE
"New group" view title when changing an existing group's picture

### ISSUE THREAD

**Issue by 5boro** [WhisperSystems/TextSecure#3390]
Steps:
 * Go into update group and tap the picture
 * Choose a new one and resize

The view title is "New group" instead of "Update group"
![screenrecorder_exported_20150611005653](https://cloud.githubusercontent.com/assets/3460479/8096342/7eb4bd60-0fd6-11e5-9c80-47ba9d2b2e82.gif)

**Comment by 2-4601** [comment]
Seems like a duplicate of #1347

**Comment by 5boro** [comment]
Oops
