### ISSUE TITLE
I can mute from the options menu and the recipient preferences screen?

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3395]
I knew contact blocking and muting was implemented so went to search for it, found the muting real quick in the options menu but surprised to find that block was not right next to it. it took me ~3 minute of searching followed by a text to @moxie0 to figure out where block was, found it by tapping on contact name.

**Comment by rhodey** [comment]
I feel like I would have found the block contact option on my own if the mute contact option was only in one place, and next to the block, in the recipient preferences.

**Comment by agrajaghh** [comment]
you're not the first one searching for it, me and @McLoo where looking some time as well. Afaik its too hidden.

I'm working on a PR which will put `Notification settings` in the menu, doing the same as clicking the name in the conversation view. What do you think?
