### ISSUE TITLE
per-recipient ringtone setting dialog does not represent setting state

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3397]
1) start conversation with A
2) tap A in the top left corner
3) Ringtone > `<whatever>`
4) notice summary says `<whatever>`
5) tap Ringtone
6) notice dialog always defaults to nothing selected

**Comment by moxie0** [comment]
This is a deficiency in the ringtonepreference code. Gonna live with it for now.

**Comment by Owen66** [comment]
I've written some code to fix this but I've never contributed to a project before. Do I just go ahead an make a pull request?

**Comment by McLoo** [comment]
@Owen66 have a look here: https://github.com/WhisperSystems/TextSecure/blob/master/contributing.md and here https://github.com/WhisperSystems/RedPhone/wiki/Code-style-Guidelines

Just pull request.
The PR should work for you (testing on different Android version is welcome), should be one commit for a specific fix/change and you should have had fun when coding :)

**Comment by Owen66** [comment]
@McLoo Ok cool. So I did a pull request. Thanks for your help.
