### ISSUE TITLE
adding blocked contacts to groups

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3400]
I can create a group and add a blocked contact as a member. I can also create a group and update it to add a blocked contact as a member.

In both of these scenarios it is possible to send messages to a blocked contact but I do not receive messages from the blocked contact.

**Comment by rhodey** [comment]
group updates from me are also received by the blocked contact, but not the other way around.

**Comment by McLoo** [comment]
What's the definition for blocking?
I expected an incoming block only - You still might still want to text the blocked contact?!

**Comment by rhodey** [comment]
for non-group messages the message compose text area is disabled, whatever we decide on i think it should be consistent between traditional conversations and groups.

**Comment by moxie0** [comment]
This is the expected behavior.
