### ISSUE TITLE
per-recipient vibrate is OK-on-select while ringtone requires explicit OK

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3401]
I think we should drop the "OK" from the ringtone dialog in favor of the OK-on-select behavior of the vibrate setting + the existing optional cancel.

**Comment by McLoo** [comment]
How can you :bee: sure to choose the correct ring tone? I always have to tap through the list to find something suitable when choosing one. (If you go through ring tones and not well known MP3s)
For changes you'd have to go back to the dialog again...
Would you play the selected tone and wait 'til it's finished before closing?

**Comment by rhodey** [comment]
lol. good point though, a message tone preview would also improve this dialog greatly. I've got a very simple example of using the `Ringtone` class to do this [here](https://github.com/WhisperSystems/TextSecure/pull/3342/files#diff-e58de40942d2bd2d9edf608320b23cdbR315), should only be an extra 2-3 lines.

**Comment by McLoo** [comment]
@rhodey I can choose between "media store" (translated) and a ring tone picker I installed. The CM 12.1 picker from media store, has that preview built in - Android version or manufacturer depended?!

**Comment by moxie0** [comment]
This is already how it works. The dialog is system provided, and previews the tones when you select them.  Then you click 'ok' to confirm.

**Comment by rhodey** [comment]
ah, my bad, seems the ringtone preview is tied to the notification stream sound volume. if you have your phone set to vibrate only you will not hear the previews.
