### ISSUE TITLE
Change mute strings and times

### ISSUE THREAD

**Issue by 5boro** [WhisperSystems/TextSecure#3403]
When looking over at other apps for translation hints, I found Facebook messenger's way of handling the new feature :
![textsecure-2015-06-11-204749](https://cloud.githubusercontent.com/assets/3460479/8117135/57706c9e-1086-11e5-9ee1-54239379b39f.jpg)

The time options make more sense IMO, and as you can see "Mute" has no literal translation in French and needs at least 3 words.
Replacing "Mute for 1 hour" with "For 1 hour" helps a lot and "Mute" is already mentioned in the title.

**Comment by 2-4601** [comment]
Yeah, the extra _Mute_ at the beginning of every option is a bit repetitive.

Btw, you don't necessarily have to translate the _mute_ in the French strings. Just use _pendant 1 heure_ etc. if it suits the language better :)
