### ISSUE TITLE
Translations for "Block", "Unblock", "Enabled" and "Disabled" not used

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3405]
In the contact specific notification/block view the translations for _"Block"_ and _"Unblock"_ are not used. The former is `recipient_preferences__block` but I'm not sure of the latter.
![mark gormley](https://cloud.githubusercontent.com/assets/174176/8122208/49b33ba2-10bf-11e5-8f1e-1bb0208ce8f6.jpg)
(Not that I would ever want to block this contact:)

Edit: Also the translations for _"Enabled"_ and _"Disabled"_ for vibration are not used.
Too lazy to edit the screenshot.

**Comment by oaim** [comment]
You're running a beta, right? I think moxie has yet to fetch the translations from transifex, which will be the last thing he does before pushing it to the play store as a final version. He submitted the new strings yesterday and he's probably giving some time to the translators.
This is my guess

**Comment by 2-4601** [comment]
@oaim 
Yeah, Play Store beta 2.18.0 apk. There are 100% Transifex-completed translations in there for a couple of languages. The screenshot also shows the other strings translated from the same batch ;)

@agrajaghh seems to have already fixed this :cake:

**Comment by 2-4601** [comment]
Paging @agrajaghh 
In 2.18.2 the vibration status (after selecting) is still English only (_Enabled_ and _Disabled_)
Or maybe I'm dreaming, had a rough day and not sure if I'm awake or not...

**Comment by McLoo** [comment]
? 

![screenshot_2015-06-17-11-23-35](https://cloud.githubusercontent.com/assets/5326916/8203615/76186c6c-14e3-11e5-8160-16e3f150a28b.png)

**Comment by 2-4601** [comment]
:+1: Yeah, it's only after you have selected on of the non defaults.

Btw, the text under _Notification sound_  should not be "Standard" (the second screenshot). Unless you have a ringtone named "Standard" of course?

**Comment by McLoo** [comment]
code is ok. Just the translations haven't been pulled yet for Enabled/Disabled

For "Standard": not sure why the German translation is still there. Can't reproduce. Some language switching weirdness maybe

**Comment by 2-4601** [comment]
Yes, you are right. I didn't check thoroughly this time. 

Maybe the "Standard" got stuck after you rotated your device? :D (_you are holding it wrong_:)

**Comment by agrajaghh** [comment]
@2-4601 is it fixed fo you with 2.19.0?

**Comment by 2-4601** [comment]
Yes :+1: 
![josef matula](https://cloud.githubusercontent.com/assets/174176/8242999/07a13554-161c-11e5-9b49-0dea77df2a63.png)
