### ISSUE TITLE
2.18.0: s/App protection/Privacy/g

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3406]
![screenshot_2015-06-12-05-38-44](https://cloud.githubusercontent.com/assets/174176/8122716/c48be30e-10c6-11e5-96d3-617289a81632.jpg)

**Comment by 2-4601** [comment]
@agrajaghh :cake:

**Comment by agrajaghh** [comment]
the :cake: is a lie

**Comment by 2-4601** [comment]
:fire:
