### ISSUE TITLE
TextSecure crashes, when message with Picture is forwarded to other person

### ISSUE THREAD

**Issue by vanitasvitae** [WhisperSystems/TextSecure#3413]
Hi
Im using the beta and TS seems to crash when I try to forward a message with an attached Image I wrote to A to person B. Im on Paranoid Android 5 alpha 2 on Nexus 5.

**Comment by 5boro** [comment]
Settings > Advanced > Submit debug log

then post the URL here

**Comment by vanitasvitae** [comment]
According to the crash report, ShareActivity throws a Nullpointerexception in the method getStreamExtra.

**Comment by 5boro** [comment]
Seems related to #3341 and #3311

**Comment by McLoo** [comment]
Besides that, only text forwarding works currently. So if there is no crash, you only have the text forwarded. 
Should be fixed with #3311

**Comment by vanitasvitae** [comment]
https://gist.github.com/dea1b07a5d8bb309c8ca

**Comment by vanitasvitae** [comment]
That was fast. Thanks :)
