### ISSUE TITLE
Group messages are sorted incorrectly

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/TextSecure#3421]
Please look at tahe attached screen shot:

10 minutes
12 minutes
9 minutes
![screenshot_2015-06-06-21-31-39](https://cloud.githubusercontent.com/assets/6921696/8144140/75171e16-11ce-11e5-9c67-086833dac735.png)

Found with TextSecure 2.16.4.

**Comment by onny** [comment]
Note that Thomas is responding to the image, saying "Wow thats nice" :)

**Comment by 5boro** [comment]
It may be too late but try to post a debug log :

Settings > Advanced > Submit debug log
then post the URL here

**Comment by Norbert80** [comment]
Does debug log reveal any kind of private data?

**Comment by moxie0** [comment]
Messages are always sorted the order they arrive, rather than the order they were sent.  If they're out of chronological order, it means the message was likely delayed either on the sending side or when your device was retrieving it.
