### ISSUE TITLE
One more untranslatable "UNBLOCK"

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3422]
![monkey island stan blocked](https://cloud.githubusercontent.com/assets/174176/8145522/f4e77678-1213-11e5-99d9-f673fd09a185.png)

**Comment by McLoo** [comment]
Every time you post something I think "what a nerd"... 
... and then I catch me laughing - cause I know all the things.  Man, am I a nerd :eyeglasses: 
look behind you 🙈🙉🙊

**Comment by 2-4601** [comment]
:laughing: 
wow, there was actually a three-headed monkey behind my back just now! How could you know?!? :astonished:
