### ISSUE TITLE
Receiving delivery receipt when being blocked

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3425]
- contact A has blocked me
- I sent him a message
- I received a receipt, though he  ~~received~~ sees nothing

intended? Somehow this shows false information, on the other you might not want to let ppl know that they were blocked.

**Comment by moxie0** [comment]
Yeah we thought through this.  It's not a good situation either way.  In the end we did it this way because it was the easiest way of two bad situations.
