### ISSUE TITLE
Feature Request: Different notifications for groupmsg and PM

### ISSUE THREAD

**Issue by itschytoo** [WhisperSystems/TextSecure#3427]
I would like to set different notifications for group and direkt messages.
When I get a direct message I like a rather intrusive notification while I don't want group messages to play the same ringtone all the time (example: threema).
If you are bothered with the additional settings for this, please at least consider an option to only allow the first new message to spawn a notification and suppress the rest (for 1h?).

**Comment by McLoo** [comment]
@itschytoo wait for the next release. There you can set the tone and the mute duration for single contacts and groups. 
Not in general for all groups, but each individual. See #3378. This should for you.

**Comment by itschytoo** [comment]
That sounds good. Thanks for pointing out.
