### ISSUE TITLE
Wrong timestamp on resend 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3429]
If you have a message failed to send and you resend it 15 minutes later,  the time info reads `15 min` instead of `Now`

So it shows time for the first send attempt. Not quite accurate :hourglass_flowing_sand:

**Comment by moxie0** [comment]
The moment you hit send after composing your message is the "sent" timestamp, even if you don't have network access and the message is delayed.

**Comment by dcherian** [comment]
It would be useful if Signal showed the time when the message was successfully sent.
