### ISSUE TITLE
Repackage TextSecure for BlackBerry

### ISSUE THREAD

**Issue by devurandom** [WhisperSystems/TextSecure#3430]
The [BlackBerry Runtime For Android] supports repackaging Android apps to run in an Android runtime / emulator on current BlackBerry devices. This would be an interesting way to quickly target BlackBerry as an additional OS for TextSecure / Signal.

[The BlackBerry Runtime For Android]: http://developer.blackberry.com/android/

**Comment by moxie0** [comment]
Unless blackberry supports GCM, not gonna work.

**Comment by devurandom** [comment]
They write [[1]], that one could use a "standalone GCM SDK" to make the app work outside of a Google Play Services environment.

Apparently the runtime / emulator then inserts some kind of compatibility layer between BlackBerry Push Service delivering the message and the Google Cloud Messaging endpoint inside the Android app running on BlackBerry. I.e. the Signal/TextSecure server needs to send the message to the BlackBerry Push Service, which will relay it to the right device, which will then hand it over to the app via the GCM API.

[1]: http://developer.blackberry.com/android/apisupport/creating_push-enabled_android_apps.html

**Comment by moxie0** [comment]
Sounds flaky, and we don't have the ability to support it.

**Comment by devurandom** [comment]
The "standalone GCM SDK" now seems to be entirely dropped by Google - there seems to be no way around Google Play Services anymore, thus BlackBerry cannot be supported anymore just by adding a codepath for the different SDK.

Thus, unless they implement support for Google Play Services, #1000 is needed before this can be started.

**Comment by vaskas** [comment]
@moxie0 have you guys considered https://pushy.me/?
