### ISSUE TITLE
Textsecure causes huge wakelocks

### ISSUE THREAD

**Issue by RoBi89** [WhisperSystems/TextSecure#3433]
![screenshot_20150615-233326](https://cloud.githubusercontent.com/assets/6862450/8180277/f7c08c12-141c-11e5-9c13-c04048c1f77a.png)

Can't really say precisely what's causing them, but it seems like every time I receive a message textsecure holds a wakelock for 26-30 seconds.

Nexus 5 Android 5.1.1 stock

**Comment by moxie0** [comment]
Yep, we need a wakelock in order to retrieve the message, get it into the database, and notify you.

**Comment by RoBi89** [comment]
Well, I understand that textsecure has to hold a wakelock in order to do that, but half a minute for every single message? That really adds up if you get a lot of messages. Textsecure has become the number one app when it comes to wakelocks on my phone. It used to not do that, and the issue has only popped up recently. What changed? Can there not be made any improvements in order to shorten the wakelock?

**Comment by moxie0** [comment]
Yes, for every message we need a wakelock.
