### ISSUE TITLE
Unblock crashes if custom ringtone is set

### ISSUE THREAD

**Issue by boehan** [WhisperSystems/TextSecure#3434]
Steps to reproduce:

1. Set a costum rintone for a specific contact
2. Block this contact
3. Unblock the contact from the conversation view (button wich replaces input field)
4. TS crashes

log:
https://gist.github.com/anonymous/31c17bf711aae49c3b46

Additional notes:
Does not happen if no custom ringtone is set.
In spite of the crash "unblocking" is successful.

**Comment by boehan** [comment]
After further investigation it seems that it doesn't matter which method is used to unblock (conversation view or per-recipient-notifications menu). When leaving the per-recipient-notifications menu all methods trigger a crash.

**Comment by Mihahn** [comment]
Can't reproduce on Nexus 4, 5.1.1, TS 2.18.1

**Comment by moxie0** [comment]
Looks kinda like a CM bug to me.

**Comment by rhodey** [comment]
looks like `getActivity()` returned null in `RecipientPreferenceActivity.setSummaries()`, this method is called from `onResume()`, `MuteClickedListener`, and notably from a `Handler.post()` `Runnable` in `RecipientsModifiedListener.onModified()`

Seems like an edge case but given the handler runnable thing I don't think this has to be a CM-specific bug, null check seems reasonable.

```
FATAL EXCEPTION: main
E/AndroidRuntime(25578): Process: org.thoughtcrime.securesms, PID: 25578
E/AndroidRuntime(25578): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object android.content.Context.getSystemService(java.lang.String)' on a null object reference
E/AndroidRuntime(25578): 	at android.media.RingtoneManager.getRingtone(RingtoneManager.java:600)
E/AndroidRuntime(25578): 	at android.media.RingtoneManager.getRingtone(RingtoneManager.java:586)
E/AndroidRuntime(25578): 	at org.thoughtcrime.securesms.RecipientPreferenceActivity$RecipientPreferenceFragment.setSummaries(RecipientPreferenceActivity.java:176)
E/AndroidRuntime(25578): 	at org.thoughtcrime.securesms.RecipientPreferenceActivity$RecipientPreferenceFragment.access$500(RecipientPreferenceActivity.java:131)
E/AndroidRuntime(25578): 	at org.thoughtcrime.securesms.RecipientPreferenceActivity$RecipientPreferenceFragment$1.run(RecipientPreferenceActivity.java:210)
E/AndroidRuntime(25578): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(25578): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(25578): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(25578): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(25578): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25578): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(25578): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
E/AndroidRuntime(25578): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by rhodey** [comment]
yeah, actually we add ourselves as a `RecipientsModifiedListener` in `onCreate()` but never remove ourselves.
