### ISSUE TITLE
TS very slow since update 2.18.2

### ISSUE THREAD

**Issue by ahamrani** [WhisperSystems/TextSecure#3447]
TextSecure is very slow since update 2.18.2, Log : https://gist.github.com/anonymous/7965c9fb90b90d89e3e3

I had an issue that this update solved : #3376 

Thanks

**Comment by agrajaghh** [comment]
What exactly is slow?

**Comment by ahamrani** [comment]
Launching the app, scrolling contact list, opening conversations, exiting the app.

Writing messages and sending them is not slow.

**Comment by peterpanondrugs** [comment]
S3 (5.1.1 Lollipop)
Yeah, i found scrolling/searching in contact list also extremly slow.

**Comment by rhodey** [comment]
@peterpanondrugs is this also something that changed for you only recently? can you remember an approximate time of release version?

**Comment by jeremymasters** [comment]
For the record, Sam. Galaxy S4 stock rom 5.0.1 here and it doesn't seem appreciably slow on my device.

**Comment by peterpanondrugs** [comment]
I would say...at least 3-4 releases before...
