### ISSUE TITLE
SMS invite strings are schizophrenic

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3448]
Attention seeking @2-4601 here,
I'm here to inform you that the SMS invite strings (`ConversationActivity_get_with_it`, `ConversationActivity_lets_use_this_to_chat`) are schizophrenic. It's like TS can't decide which one should be used. When you tap the invite menu item they seem to come out so random that I'm gonna use this as a CSRNG.

Here's an intense video I made for you to show this – only on Github:
![phil thomas katt invites](https://cloud.githubusercontent.com/assets/174176/8272534/e5809dae-184e-11e5-93fe-e867c5d68056.gif)

Stay still now:
![phil thomas katt invites still](https://cloud.githubusercontent.com/assets/174176/8272545/599cfb56-184f-11e5-8f19-7a2e1cf4311c.png)

- TS 2.19.0
 * Nexus 4, stock Android 5.1
 * Huawei U8800, Android 4.0.4

**Comment by agrajaghh** [comment]
You can use this as a CSRNG :grimacing: :

``` java
boolean a = SecureRandom.getInstance("SHA1PRNG").nextBoolean();
if (a) composeText.appendInvite(getString(R.string.ConversationActivity_get_with_it, "http://sgnl.link/1IvurmD"));
else   composeText.appendInvite(getString(R.string.ConversationActivity_lets_use_this_to_chat, "http://sgnl.link/1CYCQQN"));
```
https://github.com/WhisperSystems/TextSecure/blob/master/src/org/thoughtcrime/securesms/ConversationActivity.java#L424

**Comment by moxie0** [comment]
Yeah we were doing some a/b testing to see which string would get more clicks, so this is the intended behavior.

**Comment by 2-4601** [comment]
Lool, I should have looked at the code :blush: 
Since "get with it" sounded strange to non-native ears I just assumed it was an older version that was still lying around.

**Comment by Meteor0id** [comment]
For future reference, this A/B testing has become subject of debate on the unofficial community forum:
https://community.signalusers.org/t/why-are-get-the-app-invite-links-unique/6796

It makes use of Bitly.com, a webservice with a hideous privacy policy to which potential Signal users will be subjected when they click on one of these links. Hopes are the A/B testing will soon be removed and replaced by a weblink to Signal.org, subject to a better privacy policy.
