### ISSUE TITLE
TextSecure 2.18.2 -- Unable to Verify Phone #

### ISSUE THREAD

**Issue by serty4011** [WhisperSystems/TextSecure#3451]
What's your device? LG L90 D415 (Also confirmed issue on a Nexus 5.)
What Android version is it running? 5.0.2 (Nexus 5 is running 5.1.1)
What version of TextSecure do you have? 2.18.2
Are you push registered? Yes

What are the relevant preferences that you have set that may be related to the issue? Friend installed TextSecure from the Play Store on his Nexus 5 and received a "Connectivity error" message during phone # verification. I then uninstalled the same version of TextSecure and reinstalled from the Play Store. I also received the same error message. The app was working fine prior to its reinstallation.

Full logcat: http://pastebin.com/BvJ6CpAP

Of Interest:

06-22 00:26:25.754 W/RegistrationService(14902): org.whispersystems.textsecure.api.push.exceptions.NonSuccessfulResponseCodeException: Bad response: 500 Internal Server Error

**Comment by moxie0** [comment]
Thanks, this is fixed in production now.
