### ISSUE TITLE
receiving sms twice

### ISSUE THREAD

**Issue by Genis-Sage** [WhisperSystems/TextSecure#3452]
Since the last few updates of TS (since 2.17.0 or so), I sometimes receive normal sms twice, although the other person only sent it once...
it happens with different contacts and with around 1 in 15-20 sms...

https://gist.github.com/381e55cf8f655ba2e186

I had the same problem in the past while using Android 4.1.2 (and I thought it was a problem with the ways, TS catches the SMS before the standard app), but with installing nAOSP 5.0.2 / 5.1.1 the problem ended, now it happens again

**Comment by moxie0** [comment]
In this log, the system gives us two SMS messages in a row.  Whatever the system gives us, we display, so this seems like a ROM bug.
