### ISSUE TITLE
Mute group doesn't work if locked

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3459]
this is a side effect of #3064.

If TS is locked, the group is muted and the sending recipient is NOT muted, you'll get disturbed...

**Comment by moxie0** [comment]
Yeah that's just the way of the world.  No way for us to know it's a group message until after we've decrypted it.  Hopefully one day we can get rid of local encryption, or at least only use it for message storage rather than session information as well.
