### ISSUE TITLE
Notifications are missing 

### ISSUE THREAD

**Issue by uncovery** [WhisperSystems/TextSecure#3461]
HTC M8,Android 5.0.1

The only notification I receive are the numbers on the app icon. Sound, vibration, LED and status bar messages are all missing.

**Comment by McLoo** [comment]
@uncovery what TextSecure version?
If you had notifications turned off in settings, the numbers on the icon wouldn't appear either...
Can you post a debug log, after you received a message?

**Comment by uncovery** [comment]
https://gist.github.com/anonymous/0bd65b19ef8646fbb4e8

Seems like there is an error:

--------- beginning of system
W/ResourcesManager( 1445): Asset path '/system/framework/com.google.android.media.effects.jar' does not exist or contains no resources.
--------- beginning of main

Anything I can do there?

**Comment by rhodey** [comment]
@uncovery is this something that just started happening recently? the missing jar is unrelated to TextSecure.

**Comment by uncovery** [comment]
No, it's been always like this, I don't remember  when I installed the software,  maybe 2 or or month ago, whatever was the current version then.

**Comment by rhodey** [comment]
everything about this reads like a ROM specific bug, all we can recommend is that you configure your ROM to interact with TextSecure just as a stock ROM would. check privacy managers, task killers, firewalls, all that mess.
