### ISSUE TITLE
Typo on the TextSecure Private Messenger beta news

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/TextSecure#3462]
For starters, thanks for a wonderful app.

There is a typo in the description for the latest update, 2.19.1

"Changes in 2.19.1:
★ Bug fixes and performance enhnacements."
"enhancements" isn't spelled like that.

I slept like a rock last night, so I figured I should include a picture showing what I'm talking about in case that isn't clear. Also, next time I find something like this, should I write here or in the mail list? I already posted it in the Google+ Community Beta group, but I figured no one ever goes there.

![image](https://cloud.githubusercontent.com/assets/12563436/8335822/591c1f2e-1aa0-11e5-8aa7-017c4ed5fcab.png)
Really offtopic question, but is there any point in fixing the RedPhone translations? The program hasn't been updated for quite some time, and I'm not a collaborator in the Swedish translation so I can't actually edit the reviewed strings.

**Comment by rhodey** [comment]
thanks for pointing this out @Dyras, as far as I can tell that specific text now seems to have been corrected in the play store, at least in the publicly viewable listing from the browser.
