### ISSUE TITLE
Clicking on unloaded picture asks for saving external

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/TextSecure#3467]
Clicking on unloaded picture (arrow icon) asks for saving external (decrypted).

I think nothing should happen when clicking on unloaded pictures.

Build 2.19.1

**Comment by 2-4601** [comment]
Hmm... didn't #3412 fix this?

**Comment by McLoo** [comment]
was this really an image or na audio or video?

**Comment by Norbert80** [comment]
Picture (now it is loaded)

**Comment by riyapenn** [comment]
Is this still an issue?

**Comment by Norbert80** [comment]
@riyapenn I cannot reproduce the bug with Signal 3.0.3 Android anymore. Thanks!
