### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#3475]
TS crashed a few times while being in background since the update  to 19.1.
https://gist.github.com/b1bedec0ff004bd1a288

**Comment by moxie0** [comment]
@merkste You're not using the browser extension or anything like that are you?

**Comment by moxie0** [comment]
@merkste Nevermind I see what's up, thanks for the report.

**Comment by moxie0** [comment]
Did a server deploy to fix this.

**Comment by merkste** [comment]
Wow, that was damn fast. Thanks Moxie!

Am .06.2015, 20:15 Uhr, schrieb Moxie Marlinspike  
<notifications@github.com>:
