### ISSUE TITLE
TextSecure messages are delivered with delay

### ISSUE THREAD

**Issue by lazlolazlolazlo** [WhisperSystems/TextSecure#3476]
Since the upgrade to TextSecure 2.19.1 messages to other TextSecure users are received with very large delays up to 7 hours. Are there network problems with TextSecure or GCM?

Device info: Moto E, stock Android 4.4, TextSecure 2.19.1
App state: Push registered, receiving SMS

**Comment by moxie0** [comment]
If people aren't receiving GCM messages it means either: 1) They have disabled background data for TS or Google services 2) They have a bad gapps install 3) They used a tool like Titanium Backup 4) They have some kind of xprivacy something something installed or 5) They are on a network that blocks GCM.

**Comment by moxie0** [comment]
There was also a "background crash" that was happening for some users and has already been resolved. It's possible that if TS crashed in the background, the system didn't restart it when new GCM messages came in.

**Comment by lazlolazlolazlo** [comment]
Thanks, I think this was a case of the "background crash".
