### ISSUE TITLE
Pre-pairing group not synced until update

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3482]
After pairing a new device (browser), messages to a group that existed before don't get sync, neither is the group itself.

As I just notice, a group update helps to solve this (except for the avatar).

reference: https://github.com/WhisperSystems/TextSecure-Browser/issues/276
Edit: and probably related to #2581

**Comment by moxie0** [comment]
We don't sync message history.  The group information is actually synced, there's just no message history to view in the conversation list.

**Comment by McLoo** [comment]
For me, new messages in that group just where not synced until I updated the group information.

**Comment by McLoo** [comment]
Just verified. Doesn't matter which of the two group holding devices sends a message - TS-Browser just ignores it.

*Don't want to add more less useful information than I do already - a bit hard to determine which component's fault this is*
