### ISSUE TITLE
Opening the emoticon chooser overlays quick reply

### ISSUE THREAD

**Issue by mad-de** [WhisperSystems/TextSecure#3485]
Steps to reproduce:
Receive message
Open via quick reply
Select emoticon panel

Android 4.4 CyanogenMod 11
![tmp_3831-img_20150627_212633-796096837](https://cloud.githubusercontent.com/assets/7095883/8393521/72107ba4-1d13-11e5-83ec-23cda27fef1a.jpg)

**Comment by mawed** [comment]
Already mentioned in #3455.

Using the back button works, but it should get more intuitive.
