### ISSUE TITLE
Muting dialog background color inconsistent

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/TextSecure#3486]
The muting dialog from a conversation itself has a grey background and the muting dialog in the (hidden) menu has a white background... 
Could be my mind playing tricks on me as I can't see any difference after cropping the screenshots but I just thought of reporting it anyway.

TS 2.20.0

**Comment by McLoo** [comment]
Only thing I noticed is the alpha(?)  layer in per-rec-pref in light theme 

![screenshot_2015-06-28-11-21-25](https://cloud.githubusercontent.com/assets/5326916/8395867/572cd4b8-1d8b-11e5-8125-337374592ffc.png)
![screenshot_2015-06-28-11-21-16](https://cloud.githubusercontent.com/assets/5326916/8395868/630b6fce-1d8b-11e5-8e96-61dbff3c770e.png)

**Comment by Mihahn** [comment]
Yep, I meant the pop-up  :see_no_evil: 
Looks like on screenshot 1 it is white and on screenshot 2 it's grey?

**Comment by agrajaghh** [comment]
@Mihahn they have exactly the same color, the second one just seems to be darker because the background is white

**Comment by Mihahn** [comment]
So my mind is playing tricks on me. Thanks for clarifying it :smile:
