### ISSUE TITLE
2.19 is slower than previous versions

### ISSUE THREAD

**Issue by benefaktorix** [WhisperSystems/TextSecure#3487]
It's more of general rant but - i have updated from i have updated from 2.6 version (the last before elimination of encrypted sms). But this new 2.19.1 is slower and more laggy. Is it my imagination or there are others who think alike? I have samsung S4 so it shouldn't be the lack of specs

**Comment by moxie0** [comment]
@benefaktorix This is an issue tracker, not a discussion forum.  If you post here, you need to at minimum include a debug log or some basic information about what version of Android you're running, etc.  Just saying "it's slow" is not at all helpful without providing specific reproducible behavior and quantifying what you mean.
