### ISSUE TITLE
Pebble (Time) Watch: Replies to messages notifications via watch are logged using stock sms app

### ISSUE THREAD

**Issue by cybershambles** [WhisperSystems/TextSecure#3488]
Incoming messages are stored in TS, and the alert triggers on my pebble.. 

Replies from the watch (voice to text or template replies) are sent? (and stored) using the stock sms app and not textsecure.. so I lose messages until I import messages in... but that results in dupes

work around: I'd need to change back to the stock, delete all of the old messages. change to TS and import the messages I care about. change back to stock and delete the new messages.

**Comment by moxie0** [comment]
I think the notifications you're seeing are originating *from* the stock SMS app, which is why replies are happening there too.
