### ISSUE TITLE
Pebble (Time) Watch receives SMSes while locked

### ISSUE THREAD

**Issue by cybershambles** [WhisperSystems/TextSecure#3489]
This is a dataleak issue really..
1a) The messages sent are received on the watch 
1b) Notifications are also saved on the watch.
2) The lock status of the application doesn't matter.

I would have expected the notification for an encrypted message from contact X.. which is shown on my phone

**Comment by moxie0** [comment]
The notifications we send to the watch are identical to what we send for the phone (in fact they're the same notification).  If you're seeing different things in different places, it has to be a different app.
