### ISSUE TITLE
Password not working

### ISSUE THREAD

**Issue by sicofante** [WhisperSystems/TextSecure#3491]
I've been using Textsecure for more than a year without a password. Today I decided I wanted to work with one. I used my SIM's PIN as the password (that's four digits). Now I can't enter the app. It says my password is invalid.

I know the consequence is that I've lost all my messages. Not a drama but very annoying indeed. I've warned all of my friends using Textsecure to not use a password.

It's simply not possible that I typed my PIN incorrectly when creating the password. I type it everyday many times and Textsecure asked me to repeat it before accepting it as the password, so something's definitely wrong with Textsecure regarding passwords.

**Comment by moxie0** [comment]
Sorry to hear it, but there's nothing we can do without a debug log from when the incident occurred. That code has been stable and untouched without problems for close to three years, so it seems unlikely that there's a major issue there, but it's possible.

**Comment by sicofante** [comment]
Well, I'm definitely not using a password with Textsecure, that's for sure. It wasn't asking me for it anyway unless I rebooted the phone, so it doesn't seem to be terribly useful either. I guess encrypting the whole phone (in Android at least) is easier and more reliable.

**Comment by moxie0** [comment]
Yeah you have to explicitly lock it or set it to time out if you want it to prompt you. But FYI a 4-digit pin isn't going to do anything meaningful for you in either case.

**Comment by sicofante** [comment]
I used the PIN just to test the feature because I "knew" I wouldn't forget it. If it had worked I would have obviously used a real password.

Just so that I know, what's the procedure to make a debug log in a case like this?

**Comment by moxie0** [comment]
TextSecure Settings -> Advanced -> Submit debug log.  There's also an option from the passphrase screen before you unlock (or can't unlock in your case).

**Comment by sicofante** [comment]
Thanks. I just reinstalled Textsecure so the issue is no longer there, but I'll remember next time.
