### ISSUE TITLE
How do I send a message to several people WITHOUT creating a group?

### ISSUE THREAD

**Issue by sicofante** [WhisperSystems/TextSecure#3495]
I'm not interested in groups. It's the very feature why I run away from Whatsapp. It creates too much noise. I'm not interested in having a chat room, which is what groups seem to be like (yes, I'm *that* old).

But I do want to send messages to several people at once in many occasions. Is that possible at all with Textsecure? How do I do that?

**Comment by moxie0** [comment]
Duplicate of #3301
