### ISSUE TITLE
Importing messages from just one contact

### ISSUE THREAD

**Issue by sicofante** [WhisperSystems/TextSecure#3496]
I just destroyed my message history when trying to use a password for Textsecure (I won't try it again...). Most of the lost messages were not important, but I'd like to keep my wife's ones. They also live in their phone, so I was thinking of backing them up, moving the backup to my phone and then import them into my new Textsecure install.

Can I do that? How? (If it involves the use of a PC, I'm an Ubuntu user and consider myself "computer literate", so feel free to suggest any solution no matter how convoluted. :-))

**Comment by moxie0** [comment]
Hey this isn't really a discussion forum, the place for that kind of Q/A is over on the support center: http://support.whispersystems.org

To answer your question, TS can import/export in the format compatible with the app "SMS Backup And Restore, " but it won't work for just one contact.  You'll have to export your wife's entire history, import them on your device, and delete every other thread.  But what will be left is an "inverted" thread with yourself.

**Comment by sicofante** [comment]
I'm sorry. I'll use the support center. Please feel free to delete this thread and another support question I just asked.
