### ISSUE TITLE
Don't ask contacts to reconfirm after reinstalling Textsecure.

### ISSUE THREAD

**Issue by sicofante** [WhisperSystems/TextSecure#3497]
I have family and friends using Textsecure. ALL of them asked me what was going on when I reinstalled Textsecure and they received a message telling them something about confirming me to their contact list again. The message looked scary to all of them and they didn't know what was going on.

Why exactly is this being done? The phone number is the same. It should be trivial for the server to know this is just a reinstall. What am I missing?

**Comment by moxie0** [comment]
> What am I missing?

The cryptography part.  Can't trust the server and all that (https://en.wikipedia.org/wiki/Man-in-the-middle_attack).  We're working on ways to make the authentication process easier and less confusing, but it will never disappear entirely.

**Comment by sicofante** [comment]
That still doesn't explain why the message is hard to understand by ordinary users who tipcally (in my experience) get scared and confused. I also don't quite understand why a MITM attack can't generate identical messages to the real servers.

On a side, note, why do you close threads after your first reply? Doesn't sound too friendly.

**Comment by agrajaghh** [comment]
> The identifying key material for %1$s has changed. This could either mean that someone is trying to         intercept your communication, or that %2$s simply re-installed TextSecure and now has a new         identity key.

This seems pretty clear to me. I guess most users don't understand the first sentence, but since its explained afterwards it should be clear to an ordinary user what happened...

**Comment by sicofante** [comment]
I can guarantee you that Textsecure has lost two users on my side only for the "computer speech" message. Everything using that style looks like those fake anti-virus pop-ups you see on the internet every other day, and people have been trained to be suspicious about any such message which they simply can't decipher, no matter how "clear" it looks to a developer. I had to explain my other 8 Textsecure contacts what it meant, so no, it's not non-geek friendly at all.

How about "Your friend Peter had to reinstall Textsecure. Please accept him again in your Textsecure account. If you're not sure about this, please contact Peter", or something along those lines?

(BTW, the two "lost for the cause" are iOS users. Since Signal does not replace the SMS client in iOS, they are very reluctant to add another app and go away immediately if that app speaks geeky.)

I understand one of the goals of Textsecure is to be easy to adopt for non-technical users (aka "convenience"). In my anecdotal evidence, I can assure you it's not accomplishing that mission. I'll keep using it because there's no better alternative for a private messaging service, but I don't think I can evangelize it a lot more. :-(

**Comment by moxie0** [comment]
@sicofante As I said, we're working on it.
