### ISSUE TITLE
Incoming bubbles too narrow on 2.21

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#3499]
I am using a TS version from the 2.21 branch. I *really* like what I see! It just looks so good, I could spend the whole day scrolling my conversations up and down, lol
However... my phone has a 4-inch screen; it's not huge, I know, but it's not that small either (to me it is just fine). And the incoming bubbles for messages I receive are a bit too narrow. Half the space of the screen is being wasted :/ Could you reduce the right margin?

This is what a long message looks like (narrow and consequently very very tall)
![a](https://cloud.githubusercontent.com/assets/12774519/8426747/7fd4f1f6-1f12-11e5-9e72-c36e1a4e474b.png)

**Comment by agrajaghh** [comment]
Just tried to run 2.21 on my small screen HTC Desire with 2.3.7:
```
06-30 10:53:35.420    2857-2857/? D/dalvikvm﹕ creating instr width table
06-30 10:53:36.611    2857-2857/? D/dalvikvm﹕ DexOpt: couldn't find static field
06-30 10:53:37.092    2857-2857/? D/dalvikvm﹕ DexOpt: couldn't find field Landroid/graphics/BitmapFactory$Options;.inBitmap
06-30 10:53:37.192    2857-2857/? D/dalvikvm﹕ DexOpt: couldn't find field Landroid/content/res/Configuration;.screenWidthDp
06-30 10:53:37.562    2857-2857/? D/dalvikvm﹕ DexOpt: couldn't find field Landroid/content/res/Configuration;.smallestScreenWidthDp
06-30 10:53:40.155    2857-2857/? E/dalvikvm﹕ LinearAlloc exceeded capacity (5242880), last=468
06-30 10:53:40.155    2857-2857/? E/dalvikvm﹕ VM aborting
06-30 10:53:40.325      299-299/? W/installd﹕ DexInv: --- END '/data/app/org.thoughtcrime.securesms-2.apk' --- status=0x000b, process failed
06-30 10:53:40.325      299-299/? E/installd﹕ dexopt failed on '/data/dalvik-cache/data@app@org.thoughtcrime.securesms-2.apk@classes.dex' res = 11
```
LinearAlloc :angry:

**Comment by mcginty** [comment]
I'm leaning towards removing the avatar from message items and instead putting it in the action bar.

**Comment by oaim** [comment]
I think that would make group chats harder to read, but it's an option. Why not just reduce all the unused space on the right?

**Comment by mcginty** [comment]
Group chats would now have different colored bubbles per person and would still have their name above the bubble.

**Comment by oaim** [comment]
If the group has a few participants, yes, the bubbles would help. But if there are like 20 people, I doubt you would remember all the colors (besides some people will have the same one). Yes, you may say there is still the name, which is harder to read than looking at a profile picture..
You decide though, I'm just giving my opinion. I think the space on the right could still be used..

**Comment by 2-4601** [comment]
This margin change was introduced in 2.21?
At least I still see full wide bubbles in 2.20 with my 3.8" screen:
![cide hamete benengeli](https://cloud.githubusercontent.com/assets/174176/8452844/05274a7c-1ff7-11e5-8170-a1dac2eaf13e.png)

I agree with @oaim that group chats would get confusing if avatars were dropped. In fact I just had a conversation with the union representatives of the avatars and they said this will not do. You cannot just lay off an entire work force like that. Think of the children! General strike incoming! (Their words, not mine.)

**Comment by oaim** [comment]
Yes, the space was introduced in 2.21. In 2.20, which you're running, you can see the incoming bubble ending right at the end of the screen. That's not good either. I think there should be a space, just a thin one

**Comment by oaim** [comment]
I see 2.21 has been pushed to master, no intention to broaden the bubbles?

**Comment by mcginty** [comment]
@oaim please refrain from these "bump" messages, it doesn't help.

**Comment by oaim** [comment]
Sorry, I didn't mean to bump. I thought you wold fix it before releasing since it is pretty narrow on small screens.

**Comment by whispy** [comment]
Avatars should definitely be removed from message items in threads between two people. They take up far too much unnecessary space.
