### ISSUE TITLE
Links should be white in 2.21

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#3500]
I noticed that in some conversations (depending on the color) links are hard to read because of their blue color. I think they should be just white and underlined, maybe bold?

**Comment by moxie0** [comment]
They should be as of e5035a9c4b7cc82b8329104c43ca8ed41d3709ff, you running the latest?

**Comment by oaim** [comment]
https://github.com/WhisperSystems/TextSecure/commit/e5035a9c4b7cc82b8329104c43ca8ed41d3709ff has just appeared for me, so no, I was running until the previous commit.
