### ISSUE TITLE
can't see all emojis in quick replies

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#3501]
When i click to open the quick reply box and then open the emoji drawer, i can't scroll all the way down to see the emojis at the bottom. Is it just me?
Android 4.1.2

**Comment by mad-de** [comment]
Like #3485 ?

**Comment by oaim** [comment]
No

**Comment by 2-4601** [comment]
This is as low as it gets for me on the people/smiley category:
![screenshot_2015-07-01-14-08-28](https://cloud.githubusercontent.com/assets/174176/8453359/83075f7c-1ffc-11e5-9e93-8323f2fd48c3.png)

TS 2.20.0, Nexus 4, stock 5.1.1

Also the _RecipientPreferenceActivity_ opens if you tap the contact name/number in the quick reply. Is this intended?
