### ISSUE TITLE
wrong colors in 2.21

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#3502]
1. Open a conversation with someone (say their color is green)
2. Close ts
3. Receive a message from another contact (say they're red)
4. Click quick reply
5. The top bar and message bubbles are still green until you scroll up&down/wait a few seconds
(Can't send a debug log right now, I'm using Android 4.1.2)

**Comment by rhodey** [comment]
using the steps given I'm unable to reproduce this on my N5 running Android Lollipop or my LG 4.1.2 device. the Lollipop device is running 2.21.0 from Google Play, the 4.1.2 device is running a debug build I made from b7492ebdfa580687b44f1aa31410931f0b92dcdd.
