### ISSUE TITLE
Make 'Submit debug log' fully translatable

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3507]
TS 2.20.0
The following strings are not available for translation at Transifex:

`This log will be posted publicly online for contributors to view, you may examine and edit it before submitting.`

`DON'T SUBMIT`

`SUBMIT`

`Uploading logs...`

`Success!`

`Copy this URL and add it to your issue report or support email:`

`GOT IT`

`Copied to clipboard`

**Comment by 2-4601** [comment]
Should this be reported to _libpastelog_?

**Comment by ChaoticMind** [comment]
It's already reported in WhisperSystems/libpastelog#7
