### ISSUE TITLE
Darker recipeint colors only for recipeint preferences  

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3514]
https://github.com/WhisperSystems/TextSecure/commit/59c51127f62bfa3a829da9c98b0d29054c859ccd
DarkTheme
In the convo list and convos the colors are still light, they change to dark though for the per-rec-pref

*You should try that light orange on dark theme, it burns yours eyes :)*

**Comment by moxie0** [comment]
beat you to it 48bf65db74c379cda7d6c7f9749b651d1ecf6444

**Comment by McLoo** [comment]
now, that is fun :D
