### ISSUE TITLE
Register time too short, cannot register without both wifi and phone network

### ISSUE THREAD

**Issue by neocogent** [WhisperSystems/TextSecure#3529]
I've tried over and over and cannot register my phone for TextSecure. I live in a remote rural area and cannot get decent phone reception at the same time that I have a wifi connection. If I drive to a spot to receive the SMS then I lose the wifi connection. If I try to do Voice Verify then it says no network - presumably meaning no wifi connection. 

So it's impossible to register here. I almost got it once by driving out to get reception but the short time limit of 2 minutes cut off before the SMS that came in moments later. 

I don't understand why you have to make it so difficult to register the phone, or even why a secure messaging app needs to have my phone number registered in the first place. Is this some hidden tracking agenda - why need the phone number for text messaging.

But my real point here is to let you know that registration is broken for people like me in rural areas. It seems the only way for me to do this is to wait for some day when I'm at some cafe with free wifi and decent phone reception both together. Can this not be made less onerous?

**Comment by moxie0** [comment]
You can use a GV or VoiP-based number if you want.  In any case, this is isn't a discussion forum.
