### ISSUE TITLE
bad encrypted message

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/TextSecure#3531]
this debug log is from the phone of a friend (Friend), situation:

1) Friend has ongoing conversation with Person
2) Person has TextSecure installed, conversation is secure
3) Friend has no cell reception for 1 week
4) Friend regains cell reception
5) Friend receives a bunch of messages, one being from Person
6) Person's message reads "Bad encrypted message" and below it another messages reads "Secure session ended"

debug log: https://gist.github.com/anonymous/c93f461080d609d777cc

**Comment by rhodey** [comment]
7) Friend asks person to resend message
8) Person receives Friend's message securely, replies securely, no crypt errors this time

**Comment by moxie0** [comment]
looks like a TiBackup situation on the part of Person.  Sent a message for a prekey that doesn't exist.
