### ISSUE TITLE
Adding per-contact notification preferences

### ISSUE THREAD

**Issue by doozan** [WhisperSystems/TextSecure#354]
I'm working to add functionality to TextSecure to allow customization of notifications (ringtone, vibrate pattern, led color) on a per-contact basis.  I've got two questions:

1) Is this a feature that you'd be interested in including in mainline TextSecure, and

2) If so, would it be better to let android store the per-contact preferences in the usual preferences location or would it be better to add them to the IdentityDatabase?

Thanks!

**Comment by bill-mcgonigle** [comment]
@doozan would you please commit your work in progress to github so others may assist rather than starting from scratch?

**Comment by doozan** [comment]
@bill-mcgonigle The code for this is in #366 but needs refactored.  I started the refactoring work with issues #558 #564 and #5

**Comment by wp9015362** [comment]
> @doozan wrote:
> 
> Is this a feature that you'd be interested in including in mainline TextSecure

Yes, as a user I can say it would be really nice if TextSecure would have this feature.

Regards

**Comment by jocelynthode** [comment]
Yeah most of the people that use TextSecure with me always ask for this feature. Maybe we're a strange group but I'm sure the majority of users would like this functionality especially when using groups.

**Comment by sarciszewski** [comment]
I, too, would like to see this implemented. Especially w.r.t. ringtones.

Is this a development priority? If not, is a pull request welcome? :)

**Comment by generalmanager** [comment]
@moxie0 Any chances the vibration patterns from https://github.com/WhisperSystems/TextSecure/pull/564 are getting in now? Many people have their phones muted all day and want to be able to tell by vibration when they get a message from their significant other or boss. 8 out of 22 TS contacts requested this without me asking.
