### ISSUE TITLE
MMS Issue

### ISSUE THREAD

**Issue by Ste4thOverride** [WhisperSystems/TextSecure#3542]
After sending an MMS to a contact I get a continuous spinning white circle on the image even though the message has been sent and the recipient has received the message.

**Comment by rhodey** [comment]
@Ste4thOverride just to clarify, was this an actual old-school MMS to a non TextSecure user or a TextSecure message containing media to another TextSecure user?

our terminology is weird 0.o

**Comment by mcginty** [comment]
closing as dupe of #3546
