### ISSUE TITLE
Missing ability to send PDF

### ISSUE THREAD

**Issue by Wblw** [WhisperSystems/TextSecure#3544]
I wanted to send a PDF to one of my contacts, which isn't possible at the moment. I estimate this missing feature as really important due to the fact that it might be relevant to security measures being able to send documents encrypted.

**Comment by mawed** [comment]
I'm not sure, but there is a big media update soon to come: #520 milestone 2.22
Maybe pdf is included there together with bigger videos.

**Comment by Mihahn** [comment]
@mawed the milestone is updated with every new release. I'm not sure if this tells us anything :cry:

**Comment by McLoo** [comment]
duplicate of #993
