### ISSUE TITLE
Colors palette in 2.20 much prettier (and more functional!) than 2.21

### ISSUE THREAD

**Issue by wrdixon** [WhisperSystems/TextSecure#3545]
My phone just updated from 2.20 to 2.21 (Moto G on 4.4.4).  I think the new colors are not nearly as pretty or as useful as the 2.20 colors were.  2.20 was beautiful and extremely functional!!!  You had it right!  :-)

The two major issues I find with the new colors are...

Insufficient Variability:  Before you had a nice wide array of colors for the recipient names.  It was great because I didn't have to read, I knew which text was which user with a simple glance at the colors.  Now most things are dark green/gray/blue and that information is lost, I'm back to reading the names to find the thread I want.

Dark/Intense: The new colors are quite dark and quite intense.  It almost looks like they're all some sort of warning messages.  The last colors were calm and reassuring. 

Awesome work overall! Textsecure has come so far from where it was a year ago!

**Comment by johanw666** [comment]
In 2.21.0, when in a conversation, you can click on the person's name and then you can select a color for that conversation. It will keep it the same for the conversation throughout sessions as well.

**Comment by wrdixon** [comment]
It's great that you can now customize, but I think that the default palette is really important.  We want a great out-of-box experience and I think it was better with 2.20 (TS was actually more functional).  These changes are actually pretty important to the UX.

**Comment by moxie0** [comment]
The colors that you can customize *are* the default palette.  The 2.21 colors are exactly the same as in 2.20 (the material palette), just the 500 tone instead of the 300 tone.  We have to do this because the chat bubbles are colorized now, and the contrast is too hard to make out at 300.  We only pulled a single color (lime), because it was too hard on the eyes.

**Comment by Wikinaut** [comment]
In case that someone needs that: https://github.com/davidmerfield/randomColor is a "pseudo" random colour generator which claims to be "A tiny script for generating attractive random colors."
