### ISSUE TITLE
Upload indicators gone wild

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3546]
**Edit: official 2.21 play release on Sony Z1 compact 5.0.2**

- new group (to be clean)
- send image 1, wait for completed upload 
- send image 2, notice the indicator shortly popping up on image 1
- send image 3, have the 2 circles of eternal life on image one and two

![screenshot_2015-07-07-17-23-01](https://cloud.githubusercontent.com/assets/5326916/8549800/06bccd50-24cd-11e5-8785-990483051f8d.png)

**Comment by McLoo** [comment]
aaand
- leave and reenter convo
- have a short circle popup on image 3
- and still have your fellow circle indicators on image 1 and 2 (or do we have gif support already? :wink: )

**Comment by oaim** [comment]
I was going to submit the same bug. Happened with sending only one photo though. It started spinning while uploading and just never stopped

**Comment by McLoo** [comment]
related to #3542 i guess

**Comment by oaim** [comment]
Possibly. I was sending to a group though. May have something to do with sending failing/retrying

**Comment by 2-4601** [comment]
This got just triggered after I sent an emoji message. Now the two last images in the group have these endlessly rotating wheels and nothing seems to fix them.

TS 2.21.0, Nexus 4, stock 5.1.1
