### ISSUE TITLE
Dark theme groups use light theme's color

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3548]
The group color in 2.21.0 dark theme is the same blue as in light theme:

![conversation](https://cloud.githubusercontent.com/assets/174176/8552822/27e4f3c0-24e8-11e5-91c0-6af86f69be6f.png)

![contact preferences](https://cloud.githubusercontent.com/assets/174176/8552826/2d5bc176-24e8-11e5-8da5-15152673392f.png)

The dark theme should have it's own color in groups as it has with private chats.

_(N.B.: The colors in the above screen shots are not accurate. I forgot to turn off my screen shading/color temperature altering app before taking those shots. But the issue is still valid :)_

**Comment by moxie0** [comment]
In 2.22.0
