### ISSUE TITLE
colorize Action Bar

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3549]
![face with open mouth and cold sweat](https://cloud.githubusercontent.com/assets/174176/8554863/15dd52f0-24f5-11e5-8681-b9552e15d548.png)
TS 2.21.0

**Comment by 2-4601** [comment]
Doh, they are not even colorized in 2.20.0
FAIL!

**Comment by McLoo** [comment]
@2-4601 thanks for honoring Mr. "Hey-you'll-become-dad-once-more". His personal situation could soften the hairiest heart :haircut:

**Comment by 2-4601** [comment]
Lol, we should arrange a funeral for him and his friends :rose::skull::tulip:
