### ISSUE TITLE
Ticks as status indicators are not intuitive

### ISSUE THREAD

**Issue by FelixHaller** [WhisperSystems/TextSecure#3550]
The double ticks that were introduced in version 2.21.0 as status indicators are **not** intuitive.

 I guess they mean:

* one tick for "message delivered to server"
* two ticks for "message delivered to chat partner(s)"

but these icons have nothing to do with the status. Even the former design (light blue until delivered to server and tick once it was delivered) was way more clear than now.

What will happen if one day tha status for "message read" will be added. Three ticks?

My suggestion:
Look at Threema's status icons (grey envelope --> dark envelope --> mailbox --> eye).

I think this is one of these example where design killed usability.

**Comment by 2-4601** [comment]
WhatsApp with its hundreds of millions of users uses the same two ticks: https://www.whatsapp.com/faq/en/general/20951546

**Comment by FelixHaller** [comment]
Ok? So what? Is TextSecure Whatsapp? Or is this a project, that tries to bring the best to its users? Do you have another argument except "Whatsapp does the same"?

**Comment by moxie0** [comment]
Best place for opinions is the mailing list.
