### ISSUE TITLE
Contact colors

### ISSUE THREAD

**Issue by drhirn** [WhisperSystems/TextSecure#3554]
Hi,
using 2.21.0 on Android 4.4.4
Since the update to 2.21.0 all my contacts have different colors. Apart from the ugly brown color for my girlfriend, I can't differ between a secure message and SMS now. Which was very easy in past (green/blue). Except for the small lock-icon in the message, which is really small.
How about a possibility the change the contact-color? And make the difference between secure and not-secure more noticeable?
Thx!
Stefan

**Comment by agrajaghh** [comment]
you can change the color by clicking on the contact name in the conversation.

please ask support questions at: http://support.whispersystems.org/
