### ISSUE TITLE
Doesn't handle group updates in sync messages

### ISSUE THREAD

**Issue by liliakai** [WhisperSystems/TextSecure#3566]
Per https://github.com/WhisperSystems/TextSecure-Browser/issues/274, group updates aren't getting processed for synchronized sent messages.

**Comment by liliakai** [comment]
Similar behavior when leaving a group from the browser: Message appears on my android client as a blank chat message from myself, and still allows me send messages to the group.

**Comment by moxie0** [comment]
in 3.1.0
