### ISSUE TITLE
Conversation list visible when opening direct capture

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3576]
On my HTC One S CM 12.1 with https://github.com/WhisperSystems/TextSecure/commit/d6d881b0cac20ecb5915cf094386aa44662e4ec6

the conversation list is visible in the place of the camera preview until the camera preview has loaded

when I open direct capture
or switch from/to 2nd camera
or when the orientation changes
or when coming back from screen lock with camera preview still open
(not when toggling from half to full screen camera) 

Hard to screen-shoot this... it's like the convo itself only fills half (or nothing on full screen camera) the screen letting the previous activity sneak through (popup-like).

**Comment by McLoo** [comment]
ah, wasn't on https://github.com/WhisperSystems/TextSecure/commit/d6d881b0cac20ecb5915cf094386aa44662e4ec6
but the issue is still there

**Comment by turtlekiosk** [comment]
Sounds like the camera needs a second to initialize but the background color is the same as that of the ConversationActivity view, so it's peaking through?

**Comment by McLoo** [comment]
@turtlekiosk yes camera needs a second. 
It's not the background,  it's the ConversationListActivity.  See #3592

**Comment by McLoo** [comment]
@mcginty in the 2.24.0 branch at commit https://github.com/WhisperSystems/TextSecure/commit/891fdfaaecefce0d64dc2093f955ec066e411efc I still/again(?) notice that on my CM 12.1 device.

But only the first time I open direct capture inside a conversation
Exit conversation and enter (another) conversation, open direct capture, see part of the conversation list.

reopen please (why can't I do that?!)

**Comment by mcginty** [comment]
@McLoo are you still seeing this issue?

**Comment by McLoo** [comment]
HEAD of 2.24.0
:sob: yeeeheeheess
![device-2015-07-30-091122](https://cloud.githubusercontent.com/assets/5326916/8977627/1d88e46c-369b-11e5-8fd3-2e50d7ce90a4.png)

**Comment by McLoo** [comment]
Ah, does not happen on my Z1 compact 5.0.2 with the 2.24.0 play release

So it's either CM being nasty or me not being able to properly build

**Comment by mcginty** [comment]
okey so i'll close this assuming it's fixed in the 2.24.0 release, re-open if you can repro!

**Comment by McLoo** [comment]
this is still the case on my HTC One S running CM 12.1 (self built apk)

**Comment by mcginty** [comment]
i'm wondering if this is something to do with the hardware and how empty TextureView/SurfaceView layers are rendered.
