### ISSUE TITLE
Half screen camera preview not working

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3577]
HTC One S CM 12.1

this time definitley on https://github.com/WhisperSystems/TextSecure/commit/d6d881b0cac20ecb5915cf094386aa44662e4ec6

tapping direct capture button in vertical mode hides action bar and moves compose region half way out of the screen.

works in horizontal mode though
and when switching from horizontal back to vertical, cause it's full screen then
tapping half screen leads to same behavior, as when opening direct capture

![screenshot_2015-07-09-09-49-58](https://cloud.githubusercontent.com/assets/5326916/8590406/a2b4b64c-2620-11e5-840b-ca16b4625d12.png)

**Comment by McLoo** [comment]
this didn't happen with #3509 (which i tested before)

**Comment by McLoo** [comment]
@rhodey this feature can be espresso tested, right?

**Comment by mcginty** [comment]
I don't think I understand. I can't reproduce this by being in portrait orientation. Can you clarify how to make this happen?

**Comment by McLoo** [comment]
Just tapping the direct capture button...

Going to do clean build, not merging into my forked master to verify

**Comment by McLoo** [comment]
Tried the *same 2 branches* as 11 hours ago. Not reproducible any more. :-1: 
Sorry!

Will keep an eye on it though.

**Comment by McLoo** [comment]
this really nags me... could it be, that the camera API had some issues?
Tried some fast orientation changes, then suddenly the preview only showed the underlying convo list, no more camera preview

rebooted, then no more half screen in portrait but somehow in landscape  o O

orientation change seems to work portrait (orientation 0) , landscape (orientation 3)   
I also get `W/QuickAttachmentDrawer﹕ HALF_EXPANDED init` but no more half screen

Think I'll wait for some else to stress the feature or test again on the official beta

**Comment by McLoo** [comment]
Just occurred in 2.23 on another device 
https://gist.github.com/dfabb7d783fb83e42bb3

Happened suddenly, was texting and tried another QC
Force close does not fix this 
Goes directly into full-screen (proper preview) 
Landscape always  looks like this 
![screenshot_2015-07-18-10-59-56](https://cloud.githubusercontent.com/assets/5326916/8761036/c0fa6bc4-2d3c-11e5-82b7-c77475d501d4.png)
