### ISSUE TITLE
thumbnail has wrong aspect ratio

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#3579]
Tested with a Nexus 4 (5.1.1) and a HTC Desire (2.3.7) on current master (https://github.com/WhisperSystems/TextSecure/commit/d6d881b0cac20ecb5915cf094386aa44662e4ec6):

**correct:**
![screenshot_2015-07-09-11-12-40](https://cloud.githubusercontent.com/assets/5296073/8591916/ba0c957a-262b-11e5-80c4-97bd5361a73a.png)
**square thumbnail:**
![screenshot_2015-07-09-11-13-03](https://cloud.githubusercontent.com/assets/5296073/8591918/bb6a1780-262b-11e5-8081-7c6d7ff25025.png)

The fullscreen picture is displayed correct. Leaving and re-entering convo doesn't fix it.

*edit:* Just saw that normal attachments are affected too

**Comment by moxie0** [comment]
I believe this is the intended behavior.  The aspect ratio should be correct, but the actual bounds are set so that thumbnail previews are always square.

**Comment by agrajaghh** [comment]
you're right, its just cropped. But I think I prefer it the old way... Just close it, if its intended and you like it like that.

**Comment by mcginty** [comment]
@agrajaghh From a memory usage and logic simplicity perspective, this way wins. It was a lot of work to make all images look good in different sizes/aspect ratios and if we have a fixed size for thumbnails then Glide can efficiently reuse the bitmaps. This should lead to big savings.

**Comment by agrajaghh** [comment]
didn't thought about that, good point :blush:
