### ISSUE TITLE
weird little white rectangles on 2.3 with direct capture 

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#3583]
I'm experiencing some weird visual glitch with direct capture on a HTC Desire with CM7 2.3.7 when I minimize the camera or after taking a picture.

sorry for the *manual* screenshots, the screen "refreshed" while taking a normal screenshot and the issue disappeared:
![minimized](https://cloud.githubusercontent.com/assets/5296073/8596166/deb31576-264d-11e5-8735-59ede0b41425.jpg)
![preview](https://cloud.githubusercontent.com/assets/5296073/8596164/dc88ee56-264d-11e5-8414-2578db12ec74.jpg)

**Comment by wp9015362** [comment]
Why are you using such an old 2.3.7 ROM, when there are 4.4.4 ROMs available as well?

**Comment by agrajaghh** [comment]
It's not my current smartphone, I'm just using it for testing... 

Btw, this is a bug report not a discussion about other things :smirk:

**Comment by mcginty** [comment]
I applaud your manual screenshotting technique. Thanks for the bug! :)

**Comment by mcginty** [comment]
I haven't been able to reproduce this, so not sure what the right fix is. Might pop this open in TestObject or something on an HTC device to see if it's specific to that. I tried on two other 2.3.x devices without this bug.

**Comment by agrajaghh** [comment]
maybe its a CM bug, but that would surprise me...
I'm not sure how TestObject is working, but if I'm not able to capture this bug with a screenshot, you might not be able to see it there?

**Comment by agrajaghh** [comment]
fixed with #3608 :blush:
