### ISSUE TITLE
Make dark theme conversation background darker

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#3584]
Hi,
since the introduction of the new colors, the dark theme has become brighter. It's good on one hand, but it's slightly annoying on the other. I think the background in conversations should be darker (maybe pure black? I think it used to be darker). This way it would be less similar to the color of sent bubbles and the general look would be less bright. Does that make sense?

**Comment by oaim** [comment]
This would also fix another problem... When using dark theme, gray contacts turn the same dark gray of the background and top bar, so that it becomes impossible to tell the avatar from the background from the bubbles -- they're all the same color.

**Comment by Thunderpig72** [comment]
I like the brighter background. Make it optional please!

**Comment by oaim** [comment]
Open the conversation with a gray contact and you won't be able to tell the borders of avatars/bubbles.

**Comment by oaim** [comment]
Fixed in 2.25
