### ISSUE TITLE
Switching between encrypted/unencrypted choppy when using Swiftkey

### ISSUE THREAD

**Issue by ComeGitSome** [WhisperSystems/TextSecure#3587]
Using Swiftkey, write something and hold the send button.
 
The bar with word suggestions in Swiftkey disappears when the options unencrypted sms and Textsecure shows up, making the animation reload.

**Comment by McLoo** [comment]
Confirmed. Did not dare to file this issue...

**Comment by agrajaghh** [comment]
me too :laughing:

**Comment by agrajaghh** [comment]
its fixed for me now, for you guys too? @ComeGitSome @McLoo

**Comment by McLoo** [comment]
@agrajaghh yep, can't reproduce. fixed for me.

**Comment by ComeGitSome** [comment]
Fixed for me too.
