### ISSUE TITLE
Restore from old app data

### ISSUE THREAD

**Issue by kaimast** [WhisperSystems/TextSecure#3589]
Hi,

I bricked my old phone. I don't have a proper backup of textsecure but the whole /data/data/org.thoughtcrime.securesms folder. Is there way to restore from that data? 

The problem is I don't have root on my new phone, so I cannot just copy it. 

Thanks a lot and sorry if that has been asked before!

**Comment by moxie0** [comment]
Hey @kaimast, sorry this isn't a support forum.  The best place for support is the support center: http://support.whispersystems.org Thanks!
