### ISSUE TITLE
direct capture preview gone wild while keyboard open

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3592]
CM 12.1, Keyboard SwitfKey, https://github.com/WhisperSystems/TextSecure/commit/d6d881b0cac20ecb5915cf094386aa44662e4ec6

Sometimes the preview stays above the keyboard. But most of the time it behaves like shown in the video. Guess focus of the compose field is lost...

What I did:
- have convo open with keyboard
- tap direct capture
- tap into compose again
- tap direct capture

hope 5 fps is enough
![device-2015-07-09-221700 2](https://cloud.githubusercontent.com/assets/5326916/8606077/956c8a82-2689-11e5-8e4c-67395302836a.gif)

**Comment by McLoo** [comment]
Still in 2.23
Though it looks slightly different

**Comment by McLoo** [comment]
Keyboard is SwiftKey

**Comment by mcginty** [comment]
in 2.24.0
