### ISSUE TITLE
translation in notification action "mark read" missing in German

### ISSUE THREAD

**Issue by mawed** [WhisperSystems/TextSecure#3593]
Hey Team,

I'm not sure if I have to report missing translation here because it's just a bug tracker. Where should I do it?

Never the less if you use textsecure in German and you get a message it shows as possibilities "Mark read" and "Antworten".

Shouldn't be it "Gelesen markieren" and "Antworten"?
Maybe even just "Gelesen"?

**Comment by 2-4601** [comment]
Here: https://www.transifex.com/p/textsecure-official/language/de_DE/

**Comment by mawed** [comment]
Sorry I missed this.
