### ISSUE TITLE
Apple emoji small, difficult to read in conversation

### ISSUE THREAD

**Issue by unrulygnu** [WhisperSystems/TextSecure#3595]
The implementation of Apple emoji in 9a18be0 is difficult to read in conversation (Nexus 5, xxhdpi), due to reduction in displayed size, as well as more colors and details in Apple's emoji images.  For reference, behold a short story about MERS, preferably on an xxhdpi mobile screen:

Google Emoji (fa62b9b 2015-07-02)
![emoji-mers-google](https://cloud.githubusercontent.com/assets/11031903/8612758/b5c4bd2c-2710-11e5-9855-48fe3adae79f.png)

Apple Emoji (9a18be0 2015-07-06)
![emoji-mers-apple](https://cloud.githubusercontent.com/assets/11031903/8612761/bc39d1d8-2710-11e5-94d6-7b8bebfc2626.png)

A quick code comparison:

`src/org/thoughtcrime/securesms/components/emoji/EmojiProvider.java` (Google emoji, fa62b9b)

      public static final double EMOJI_SMALL      = 0.60;
      public static final int    EMOJI_RAW_HEIGHT = 96;

`src/org/thoughtcrime/securesms/components/emoji/EmojiProvider.java` (Apple Emoji, 9a18be0)

      public static final double EMOJI_SMALL      = 0.60;
      public static final int    EMOJI_RAW_HEIGHT = 64;

Changing `EMOJI_SMALL` to `0.90` (96 * .6 / 64) restores emoji height to where it was before:
![emoji-mers-apple-scale-90](https://cloud.githubusercontent.com/assets/11031903/8613410/cd21e3c4-2719-11e5-8959-a0ea49c1966e.png)

**Comment by wp9015362** [comment]
@unrulygnu :

Maybe this is also related to:

https://github.com/WhisperSystems/TextSecure/issues/3317

?

@mcginty :

From his screenshots it seems like you are mixing Google "Noto Color Emoji" flags with Apple Emoj flags?

Why?

The following issue is locked:

https://github.com/WhisperSystems/TextSecure/issues/3316

So, asking here:

[You have replaced Google Emojis with Apple Emojis](https://github.com/WhisperSystems/TextSecure/commit/9a18be0a6194d4dd8ef420e9b567b1d7ce69c613). So, could you please also replace the Google flags with Apple flags?

They would be available from the set, see:

http://blog.emojipedia.org/apple-2015-emoji-changelog-ios-os-x

Regards

**Comment by unrulygnu** [comment]
#3317 is related, but it's a bigger issue: the emoji scaling factor seems to be fixed and not dynamic.  This is probably noticeable with changes to not only system font size but also screen density.  The issue I posted here is smaller in scope, focusing on getting emoji appearance/behavior back to where it was before the switch to Apple emoji.

As for the flags, I didn't use the emoji drawer; I cheated and copied and pasted the flag characters from a web page.  Since the flags don't seem to be explicitly defined in TextSecure's emoji, I'm assuming the system is pushing those pixels, but I'm not sure.
