### ISSUE TITLE
"x" to cancel attachment misaligned

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#3597]
If you attach a portrait picture, the "x" isn't next to the picture:
![screenshot_09-47-49](https://cloud.githubusercontent.com/assets/5296073/8614318/d9fd515e-26e8-11e5-950d-e3746b8e52da.png)
![screenshot_09-51-07](https://cloud.githubusercontent.com/assets/5296073/8614366/3d8d73fc-26e9-11e5-85d1-54e778b3bc70.png)

**Comment by brumsoel** [comment]
I think this can be closed now that #3849 is merged :)

**Comment by agrajaghh** [comment]
unfortunately its still not 100% fixed for me:

**good:**
![x_working](https://cloud.githubusercontent.com/assets/5296073/9645289/ebf594f4-51ca-11e5-97e0-fcb69b7692e7.png)

**misplaced:**
![x_not_landscape](https://cloud.githubusercontent.com/assets/5296073/9645291/eeabfa58-51ca-11e5-9f51-819cba5d8e07.png)
![x_not_portrait](https://cloud.githubusercontent.com/assets/5296073/9645295/f01e985a-51ca-11e5-8026-b349bf4ebfd0.png)

**Comment by rmueller83** [comment]
Although @agrajaghh mentioned in #3849 that this should be fixed, the misalignment still occurs for me in 2.26.0

**Comment by mcginty** [comment]
should be fixed in 2.27.0 now
