### ISSUE TITLE
search messages

### ISSUE THREAD

**Issue by bntspcht** [WhisperSystems/TextSecure#3598]
when you click at the magnifier in the main screen textsecure should search all messages instead of searching a contact.

why?

(1) because it is an inbox of messages and most email-programs behave like this
(2) when you compose a new message then you already got a contact search
(3) nearly every android smartphone has a contact manager where you can search for contacts and open the corresponding chat from there (if you've set ts as the standard messenger you'll be redirected to ts..)

**Comment by moxie0** [comment]
dupe of #1232
