### ISSUE TITLE
Different actions from contact info depending on whether hitting back key or back arrow in top left

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#3602]
1. open message thread
2. tap on contact name at the top

Note two different behaviors:

3a. return to thread by hitting back arrow for android device
3b. see cool animation moxie0 made

OR

3a. return to thread by hitting back arrow in the top left corner
3b. note missing cool animation
3c. sob uncontrollably

**Comment by McLoo** [comment]
sounds familiar 😀 #3523

**Comment by jeremymasters** [comment]
Closing as dupe of #3523

**Comment by claenn** [comment]
Sorry, both ways offer no animation here.

Device  : LGE Nexus 5 (hammerhead)
Android : 4.4.4 (8166, slim_hammerhead-userdebug 4.4.4 KTU84Q 8166 test-keys)
Memory  : 58M (0.06% used, 192M max)
Memclass: 192
OS Host : slimgerrit
App     : TextSecure 2.21.0

**Comment by jeremymasters** [comment]
@claenn I'd put your info in the other issue, #3523
