### ISSUE TITLE
HTC One m8 can't recieve MMS.

### ISSUE THREAD

**Issue by bk10287** [WhisperSystems/TextSecure#3606]
I've opened an issue for this previously, and it is still happening for me.  I have trouble sending and receiving insecure MMS.  Here is the attached debug log: https://gist.github.com/b505b5b9a6ba47f1dece
I've made sure to not be on Wifi while sending, verified my APN settings, and done everything under the sun.  With Android messages, I have no issues.

**Comment by bk10287** [comment]
Actually to update, I didn't open the issue but commented on it and it was closed as me needing to update, which did not fix it: https://github.com/WhisperSystems/TextSecure/issues/3175

**Comment by 5boro** [comment]
Are you on T-Mobile ?
Check out #3270

**Comment by bk10287** [comment]
Thanks, and yes I am.  This seems to be the same issue, so I can close this issue as it is a dupe of #3270
