### ISSUE TITLE
Lock symbol and date have very low contrast in incoming message bubbles (phone number in conversation toolbar has the same issue)

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#3611]
Hello,

the incoming message bubbles in TextSecure 2.21.0 have a colored background (color depends on setting per contact) and the text inside those incoming message bubbles is white.

So far that is fine.

But:

The lock symbol and the date in those incoming message bubbles basically have the same color as the bubble's background, which results in a very low contrast and bad readability.

In comparison:

The outgoing message bubbles in TextSecure 2.21.0 have a white background and the text inside those outgoing message bubbles is black/dark gray.

And the lock symbol and the date in those outgoing message bubbles have the same (or similar) contrasting color as the message text (black/dark gray), which results in a much better readability.

So:

Could you please change the lock symbol and the date in the incoming message bubbles to a white color?

With white they would have a much better contrast to the colored background and would have a much better readability.

PS:

The phone number in the conversation toolbar (the phone number that is being displayed below the chat partner's name) has the same issue.

So it would be nice if you would change that to a white color as well.

Regards

**Comment by moxie0** [comment]
we're not going to do that
