### ISSUE TITLE
Please add option to change default theme color globally

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#3613]
Hello,

with TextSecure 2.21.0 you can change the color for each contact.

When changing the color, the color for the conversation toolbar changes as well.

So it's a bit like changing the theme color.

However, the attachment button inside the conversation remains blue (default theme color) for example.

It would be really nice if you could add an option to TextSecure which would allow to change not just the color for each contact, but also change the theme color globally, so that the color is changed everywhere, including the main screen and settings and so on.

Or with other words:

Currently the default color in the TextSecure "Light" theme is blue.

I'd like to have an option to change this default color to something else.

Any chance you could do that?

It could be placed under Settings -> Appearance.

It would be much appreciated.

Regards

**Comment by moxie0** [comment]
we're not going to do that
