### ISSUE TITLE
Color selector cut off

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#3614]
Tested with current master (https://github.com/WhisperSystems/TextSecure/commit/75939180068c9eb1de06d0a293bcf3661aba3321) on a HTC Desire with 2.3.7 CM7:
![screenshot-20150711-110549](https://cloud.githubusercontent.com/assets/5296073/8633186/087aa0ca-27bd-11e5-9dcf-51e25eb9927e.png)

**Comment by moxie0** [comment]
cb5b05acba9cef5628ef1d3e60c67a8a6c2f21b5

**Comment by agrajaghh** [comment]
@moxie0 its working on 2.3:
![screenshot-20150723-121022](https://cloud.githubusercontent.com/assets/5296073/8848098/f28f393e-3134-11e5-90be-5999cef0306e.png)

but its now broken (too much padding) on 5.1.1 :stuck_out_tongue_closed_eyes: 
![screenshot_2015-07-23-12-10-06](https://cloud.githubusercontent.com/assets/5296073/8848107/0843a2a6-3135-11e5-8bdd-db9ebc16906c.png)

master:
![screenshot_2015-07-23-12-17-23](https://cloud.githubusercontent.com/assets/5296073/8848109/0c372b80-3135-11e5-927d-2d33869445a3.png)

**Comment by agrajaghh** [comment]
and why is it black on 2.3 but white on 5.1.1?

**Comment by moxie0** [comment]
that's the expected behavior

**Comment by agrajaghh** [comment]
The white space on the right and left? Looks much better to me without :confused:
