### ISSUE TITLE
Gigantic landscape IME send button 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3620]
HTC One S CM 12.1 
a44a4bc

Was this input mode supposed to come back or is my screen to small? 
Anyway, that send button is really big... 

![screenshot_2015-07-11-22-50-02](https://cloud.githubusercontent.com/assets/5326916/8635353/e5bf0dd8-281f-11e5-9bd1-3f5bfc4aa464.png)

**Comment by moxie0** [comment]
Yep, these days the send button is the primary indicator of textsecure vs sms.  We brought back the landscape keyboard view because the keyboard pushed the compose edittext off the top of the screen on some devices.  We can't style the button in there, so we have to name it.

**Comment by 2-4601** [comment]
When in landscape and the TS emoji drawer is open there is still the regular compose edittext. Or am I missing something?
