### ISSUE TITLE
In the ConversationActivity, selected emoji do not match displayed emoji

### ISSUE THREAD

**Issue by ehartsuyker** [WhisperSystems/TextSecure#3621]
Phone: Moto G 2014
TS version: commit 7593918

Steps to reproduce.
1) Open coveation
2) Click smiley face emoji button to pull emoji drawer
3) Attempt to make a selection while the screen is scrolled down n > 2 rows 

Expected outcome: The selected emoji is displayed.

Actual outcome: No emoji is displayed. Incorrect emoji is displayed.

Example: While the emoji selection box is scrolled exactly two lines down, clicking [fearful-face](http://emojipedia.org/fearful-face/) yields [face-savouring-delicious-food](http://emojipedia.org/face-savouring-delicious-food/), and clicking [weary-face](http://emojipedia.org/weary-face/) yields [face-with-medical-mask](http://emojipedia.org/face-with-medical-mask/). Further, with the box scrolled exactly three lines down, clicking [fearful-face](http://emojipedia.org/fearful-face/) yields [confounded-face](http://emojipedia.org/confounded-face/).

**Comment by 2-4601** [comment]
Confirmed on Nexus 4, stock 5.1.1, TS 2.22.0.
After this bug is triggered some of the bottom row emojis don't yield anything at all.
