### ISSUE TITLE
Crash while inside conversation

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3624]
https://github.com/WhisperSystems/TextSecure/commit/3ae1c5ccc8eca2ce299936fe8636ddc2869ab2ea

https://gist.github.com/0ee0dbe5f17c5551b9cf

*may contain traces of camera*

**Comment by McLoo** [comment]
Couldn't reproduce with flipping, so changed title

**Comment by Dyras** [comment]
I'm not sure if this is the same issue, it probably is but just making that clear.

Whenever I flip inside a conversation, TextSecure crashes. 
I'm using a Galaxy Nexus, with Paranoid Android 4.44.
The crashing started with the last beta update, TextSecure 2.22.0

https://gist.github.com/anonymous/5f498d7ded9b3ef481a4
https://gist.github.com/anonymous/37aeaf4fdb47a57689aa
https://gist.github.com/anonymous/3f58bd8afa9771daa700
https://gist.github.com/anonymous/dbc9b559c414ff1dada1
https://gist.github.com/anonymous/e7240857228536e89b95

**Comment by McLoo** [comment]
Looks pretty related. 
And as mentioned, I had then crash on flipping, but could not reproduce since.

**Comment by Dyras** [comment]
@mcginty Any chance you should push an update with this as soon as possible? I want to continue beta testing to help you people find problems etc but it's impossible to do so when it crashes, and crashes, and crashes, and...

**Comment by moxie0** [comment]
@Dyras 2.22.1 (with this fix) has been in the beta channel for the past day.  Let us know if this is still present with that release.

**Comment by Dyras** [comment]
@moxie0 The update just got available for me. I'll write back if the crashing persists.
