### ISSUE TITLE
Conversation colors don't update while in keyboard

### ISSUE THREAD

**Issue by derfasthirnlosenick** [WhisperSystems/TextSecure#3626]
Only minor and very rare case but eh...
Right after the reboot of my phone (when it is still sluggish), I could quickly open Textsecure to see the contacts/conversations only listed by numbers & marked as gray. If I quickly open one of the conversations and klick the compose message box before the color has updated/refreshed, the conversation bubbles do not update their color until I close the keyboard.

**Comment by luksen** [comment]
I had the same happen when I got a call while I was typing a message. After coming back from the call the conversation was colorized in gray until I closed the keyboard. Before the call the colors were normal and the call lasted about 15 minutes.

**Comment by moxie0** [comment]
In 2.24.0

**Comment by moxie0** [comment]
for real this time
