### ISSUE TITLE
can't scroll all the way up in most conversations

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#3627]
Both with ts users and sms conversations. Ts 2.22, android 4.1.2

**Comment by ComeGitSome** [comment]
Same problem here, the bar at the top covers the message.

**Comment by 2-4601** [comment]
Confirmed on Nexus 4, stock 5.1.1, TS 2.22.0.

**Comment by 2-4601** [comment]
There's also curious behavior when you scroll really fast up and when you reach the top it starts to scroll down instead of stopping at the top. Does not happen always. I guess you have to scroll fast enough.
This also occurs in 2.20.0.

**Comment by turtlekiosk** [comment]
Is the padding (with the height of the action bar) to compensate for the window actionbar overlay mode in ConversationActivity missing?
