### ISSUE TITLE
Option to hide/replace emoji button

### ISSUE THREAD

**Issue by Ede123** [WhisperSystems/TextSecure#3634]
It would be great if one could hide the emoji button and/or replace it with something more useful (e.g. attachment button).

There are various reasons why one might not need the emoji button:
* The keyboard used might already provide an emoji button (as in my case).
* One might prefer to use/type old-fashioned ASCII emojis, therefore not needing the advanced emoji menu provided by TextSecure.
* One might not want to use emojis at all.
* and probably some more that I can't think of...

**Comment by moxie0** [comment]
Thanks @Ede123, but for us the answer is never more options.
