### ISSUE TITLE
Use system look for emoji or add a "compatibility mode"

### ISSUE THREAD

**Issue by ComeGitSome** [WhisperSystems/TextSecure#3637]
Some want uniformity and emoji can get lost in translation but this is not a TextSecure problem and shouldn't be fixed here. Even if it were to be fixed here, why settle on the Apple ones? I can't see how many people have installed Signal but there are 253 ratings, compared to 19,627 ratings for TextSecure. Would iOS users like Android emoji? Probably not. Most people likely prefer whatever they're used to, so it's better to let the system handle the look instead of forcing everyone to use the Apple ones which look really cheap and doesn't fit in at all on Android.

TextSecure uses one set of emoji while the rest of the system and other apps uses another now. Also notifications still use the system emoji and apparently nothing can be done about this. The inconsistencies look really sloppy. 

Adding options is usually not a good idea but the same goes for changing the look that people are used to, so if anything there should be a "compatibility mode" where those who want to make sure nothing gets lost in translation can switch to Apple emoji.

**Comment by moxie0** [comment]
thanks but we're not going to do this

**Comment by wp9015362** [comment]
@ComeGitSome :

A lot of users do not like the Google "Noto Color Emoji" Emoji set, see the following two issues on the AOSP bug tracker for example:

https://code.google.com/p/android/issues/detail?id=69755
https://code.google.com/p/android/issues/detail?id=73248

I also do not like the Google "Noto Color Emoji" Emoji set.

And WhatsApp for Android and Telegram for Android also use their own built-in Emoji set and overwrite the native Emojis.

So, WhatsApp and Telegram are doing it exactly like TextSecure is doing it.

And WhatsApp and Telegram arguably are currently one of of the most popular messengers.

So a lot of users are actually used to it.

IMHO it is very good what TextSecure is doing. And it should stay like this (at least until Android provides a better Emoji experience).
