### ISSUE TITLE
Sending encrypted through google voice

### ISSUE THREAD

**Issue by yestertester** [WhisperSystems/TextSecure#364]
Allow for the extra header that google voice attaches text messages and still allow decryption.  currently a msg received is recognized as a text secure msg but the return key and further msgs are wont work as google uses a token text msg phone number and puts the real txt caller id in the msg as a header.  text msgs to the reciever with the extra header are still encrypted

**Comment by patcon** [comment]
With encrypted SMS being dropped, I think this can be closed, yes?

**Comment by rhodey** [comment]
@patcon indeed!
