### ISSUE TITLE
Crash on message received (with bonus "Bad encrypted message")

### ISSUE THREAD

**Issue by timewasted** [WhisperSystems/TextSecure#3642]
First off, the gist of the debug log: https://gist.github.com/anonymous/b4bd3001d8c0525e81c9

I've used TextSecure for a long while, but I only very recently picked up my first contact who also uses it.  I was so excited when I sent my first message!  I was slightly less excited when she said that all she received was a "Bad encrypted message" error.  I did some debugging on my end, which led to a debug log that looked something like the one that I posted above (but without the crash).  This morning however, her "Bad encrypted message" to me also resulted in TextSecure crashing upon receiving the message.

I don't know why today's message exchange led to a crash but the previous ones didn't.  I'm also confused as to why I'm trying to JSON decode an HTML error message.

Any ideas as to what could be going on and/or suggestions on what to try next?

**Comment by moxie0** [comment]
The crash is already fixed in master, and is unrelated to your bad encrypted message.  As for the latter, it looks as if one of you has used a tool like titanium backup.

**Comment by timewasted** [comment]
Sigh, sadly the titanium backup user was me, before I realized that it's very much a bad idea to use with something like TextSecure.  If only I'd known then..!

Is there any way to unfuck it without losing my message history?  I know I could export a plain text backup, wipe TS, then import the plain text backup.  That'd cost me my MMS history, which isn't the end of the world, but isn't strictly ideal.

**Comment by moxie0** [comment]
Sorry I don't think there's any other way, fuck with your phone and fucked up shit happens.  =(

**Comment by timewasted** [comment]
Damn, oh well.  At least now I know for future reference.  Thanks!
