### ISSUE TITLE
Sms verify and callback do not work

### ISSUE THREAD

**Issue by backgammon84** [WhisperSystems/TextSecure#3657]
Im using A Samsung Galaxy Note 4 with the latest version of text secure 2.21.0 and I cannot get past the second step of SMS verification. It won't verify my phone and it wont call me to do a voice verify either. I have uninstalled and reinstalled numerous times. I have tried it on 3g and wifi no luck. There are no logs to send as I cannot even get past the second stage of setup.

**Comment by skulumani** [comment]
Have you tried another number, eg. a Google voice number? This would narrow down the problem to your specific phone number or something on the TextSecure side?

**Comment by backgammon84** [comment]
I used another number and it called right away. What could the issue be?

**Comment by skulumani** [comment]
I'm not really sure but I would bet that there may be something unique about your number that the verification software doesn't catch. 

Would it be possible to give some more information about your number? I'm sure there are lots of privacy concerns so take that into consideration.

It might be your carrier, region of the world, number formatting etc?

**Comment by backgammon84** [comment]
I have Sprint service but I had the same carrier as before just a different number but text secure worked fine. I live in the USA its a 303 area code

**Comment by moxie0** [comment]
for support questions please see the support center: http://support.whispersystems.org

**Comment by backgammon84** [comment]
Moxie, I was at that support site. No developers or agents have been answering. So I was advised to post the problem here.

**Comment by backgammon84** [comment]
No developers or support staff are answering support requests, Moxie. I was advised to post to issue here on github.
