### ISSUE TITLE
Bad encrypted message from WhisperPush user

### ISSUE THREAD

**Issue by timewasted** [WhisperSystems/TextSecure#3659]
Starting off with the debug log: https://gist.github.com/anonymous/76b13998ebfb86b7142c

As we discussed in #3642, I had previously used Titanium Backup, which I had learned after doing so is frowned upon.  So I went with the nuclear option of nuking my TextSecure install (wiped data, reinstalled too just for good measure), and starting fresh.  The above debug log is after nuking everything.

I have a bit more details about what's going on this time, too.  First, and probably most importantly, is that the person on the other side of this issue is running WhisperPush version 5.0.2-30bd462d41 on a OnePlus running CM (which is the stock OS on the device).  My encrypted push messages to them are good, but I just receive the "Bad encrypted message" error.  They can exchange messages with other WhisperPush users, but I'm currently not sure about other TextSecure users.  Normal SMS works, but that's probably not shocking.  Normal MMS also works.

Thoughts/suggestions?

**Comment by Dyras** [comment]
Can you get encrypted messages from other CM users?

**Comment by moxie0** [comment]
Sounds like a bug in WhisperPush. CM is working on fixing/updating it, I'd recommend asking them to install TS in the mean time.

**Comment by timewasted** [comment]
OK.  Well, I'm working on finding someone else running WhisperPush on CM to test with anyways, just to have another data point.

**Comment by riyapenn** [comment]
Closing b/c no new information or other users with the issue of it being a TS bug.
