### ISSUE TITLE
emoji drawer incorrectly sized after swiftkey relayout

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3661]
Play version 2.22.1
Z1 compact 5.0.2 

*without words*,  literally 🙊

![screenshot_2015-07-14-21-20-02](https://cloud.githubusercontent.com/assets/5326916/8682819/4c9f719a-2a6f-11e5-8f5d-dad2f40ae145.png)

**Comment by McLoo** [comment]
ahh, this only happens when opened while keyboard is not visible

**Comment by McLoo** [comment]
wtf? now it's always in correctly sized!
There seems to be some learning process for the emoji drawer... Just rebooted, unlocked TS, opened convo: emoji about keyboard height, but not until I changed between emoji and keyboard a few times.

**Comment by mcginty** [comment]
@McLoo did this happen on first install per chance? Or is this from an existing installation.

**Comment by McLoo** [comment]
Was an update from 2.19
also notice some delay, the first time opening the drawer after updating

**Comment by mcginty** [comment]
Restarting the process means the shared preferences for recents isn't cached, which explains the delay. There's an issue open to make that request async.

**Comment by McLoo** [comment]
@mcginty just to be clear: noticed the delay only the very first time after updating - not after rebooting or force closing TS. But it was the recent's tab indeed, that showed up...

Have to revise my version info! it was an update from 2.21.0 to 2.22.1. Sorry, my math-lib is a bit buggy.

**Comment by sweah** [comment]
I've faced the problem with the large emoji drawer several times since TS version 2.21. Unfortunately it happens quite randomly...no success in reproducing it till now!

**Comment by sweah** [comment]
At the moment I use TS 2.22.2 on my Galaxy s3 mini (Android 4.2.2).

**Comment by McLoo** [comment]
Not fixed in 2.23
Was so happy to have my half screen capture back, that I started tapping in flipping wildly between keyboard emoji and direct capture 

Last time was change from keyboard to emoji
Short freeze with empty (White) drawer and 🎆
![screenshot_2015-07-18-17-23-47](https://cloud.githubusercontent.com/assets/5326916/8762219/dc463d1e-2d72-11e5-88ef-2b9820eef211.jpg)

**Comment by McLoo** [comment]
Tapping the keyboard in the top to right corner fixed that you

**Comment by McLoo** [comment]
Yeah,  no fixed pattern yet, but the steps above mixed *wildly* makes this happen

**Comment by McLoo** [comment]
Also as mentioned before 
This is persistent until the keyboard gets opened again 
And if you open the keyboard while the monster drawer is closed, the next time you open the drawer the height  is below keyboard height until you toggle once between them

**Comment by 2-4601** [comment]
When quick capture is open and you tap emoji drawer there's an animation where the drawer comes down from the top. Is this supposed to happen? Why would the emoji drawer cascade from the top? Normally in TS the emoji drawer just appears without animation. The system keyboard has an animation where it raises from the bottom of the screen.

**Comment by mcginty** [comment]
i can't reproduce with your steps on my z3 compact 5.0.2

**Comment by McLoo** [comment]
Try harder 😜

Assuming you're using Sony stock keyboard I went through the steps with that too. Can't reproduce. (also no strange redraw) 

Switch keyboard back to SwiftKey exit convo,  go through the steps. Successfully reproduced again...

**Comment by mcginty** [comment]
Yep, reproduced. This seems specific to SwiftKey, that was the... key.

**Comment by sweah** [comment]
Happened again with TS 2.23.1 installed (using SwiftKey)
![screenshot_2015-07-22-09-40-10](https://cloud.githubusercontent.com/assets/1198892/8820534/b3e70cb8-3056-11e5-8852-296ac3b03c1f.png)

**Comment by McLoo** [comment]
yeah, same steps as mentioned above make this happen
@mcginty reopen please

**Comment by moxie0** [comment]
in 2.24.0
