### ISSUE TITLE
received text (SMS) several times

### ISSUE THREAD

**Issue by whatever2** [WhisperSystems/TextSecure#3668]
I installed the app only today. However the text I got send to me, in order to try if the app works all fine, was received more then ten times.
Motorolla XT910
Android 4.1.2

**Comment by generalmanager** [comment]
Was the SMS sent by someone using TextSecure? If not, it's probably a problem on their side and it was actually sent several times. Please also check how many messages are shown on the sending device.
And last but not least: please create a debug log in the settings the next time something funky happens, otherwise it's basically impossible to debug even if it's a real bug.
Thanks!

**Comment by moxie0** [comment]
Yep, thanks for the report @whatever2 but there's nothing we can do without a debug log.  If it happens again, please submit another report with a log.

**Comment by whatever2** [comment]
Hi Moxie,

how can I upload the log? I know where to generate it, but I don't know where it is saved or how to upload it? Thanks for your help :)

**Comment by whatever2** [comment]
Same happend again:
https://gist.github.com/64204673d508ba1118b2

**Comment by whatever2** [comment]
The sending device showed only one message forwarded.

**Comment by whatever2** [comment]
https://gist.github.com/anonymous/64204673d508ba1118b2

**Comment by whatever2** [comment]
Hi Moxie,
I uploaded the current log, as it happened again, it would be great if you reopened the "issue"

Moxie Marlinspike <notifications@github.com> schrieb:

Yep, thanks for the report @whatever2 but there's nothing we can do without a debug log.  If it happens again, please submit another report with a log.

---

**Comment by McLoo** [comment]
@whatever2 doesn't this  happen with the stock SMS too? (change default app)

**Comment by moxie0** [comment]
There's nothing in those logs. You need to generate the log immediately after the issue happens.
