### ISSUE TITLE
Selection for failed or upload pending messages is not sticky

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/TextSecure#3674]
Selection for failed or upload pending messages is not sticky. After removing the finger the item is deselected. So it is difficult to delete them. It happens independent of message type  (plain text or media).

Build 2.22.2.

**Comment by johanw666** [comment]
Same issue as selecting messages with phone numbers or weblinks in them?

**Comment by Norbert80** [comment]
Maybe that's the problem and perhaps it is not related to the states uploading or failed. If for the problem you describe already an issue has been filed please set this issue as duplicate.

**Comment by Dyras** [comment]
Also happening for me.

**Comment by moxie0** [comment]
this is a duplicate

**Comment by Norbert80** [comment]
@moxie0: Thanks. Duplicate of which issue number?
