### ISSUE TITLE
Some views are still using previous emoji set

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3676]
(Since [the last issue](https://github.com/WhisperSystems/TextSecure/issues/3662) was kidnapped I made this.)

Per-recipient preferences are using the old emoji set.
Screenshot from group preferences:
![screenshot_2015-07-14-22-48-27](https://cloud.githubusercontent.com/assets/174176/8683417/5f4d0594-2a7b-11e5-9855-ca45a13f99a6.png)

**Comment by 2-4601** [comment]
> @McLoo wrote:
> and in group name settings (no emoji drawer, but also no replacement)

![screenshot_2015-07-17-15-25-28](https://cloud.githubusercontent.com/assets/174176/8747084/4d197b9a-2c98-11e5-9190-eac946027c41.png)

**Comment by 2-4601** [comment]
All images:
![screenshot_2015-07-17-15-29-49](https://cloud.githubusercontent.com/assets/174176/8747125/c364ab1c-2c98-11e5-9563-5a972a1ecbc6.png)

**Comment by JoeJJJoe** [comment]
That means that emoji set is till in the package and usable? So why can't I switch back to it in the other places? Is it a matter of adding a checkbox?

**Comment by johanw666** [comment]
No, that means that in these textedits the system emoji set is used (if present) so they will look different on differenmt phones.

**Comment by JoeJJJoe** [comment]
So they will look the way they were intended to look on different phones you mean.

**Comment by 2-4601** [comment]
Oh Mother Kali, please make it stop :......(

**Comment by JoeJJJoe** [comment]
Yes please make it stop indeed.

**Comment by johanw666** [comment]
@JoeJJJoe , stop whining and learn to compile your own version!

**Comment by JoeJJJoe** [comment]
What a stupid thing to say.

**Comment by agrajaghh** [comment]
OMFG, cant believe this... :scream:

![emoji](https://cloud.githubusercontent.com/assets/5296073/8748536/6ec284aa-2c9b-11e5-8492-a2a4c974b871.png)
