### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by karlhedderich** [WhisperSystems/TextSecure#3680]
I had textsecure installed and then upgraded my phone from kitkat to lollipop, my phone is a moto x second gen.  For the first day after I upgraded I was able to send and receive encrypted texts.  Now I can no longer receive or send texts.  I tried texting on wifi, the cell network, with and without a VPN, no combo worked.  I uninstalled the app and then reinstalled it.  When I tried to register it gives me a connectivity error and can't register.  It says "Textsecure was unable to connect to the push service."  I am not behind a restrictive firewall and I do have a functioning internet connection.

**Comment by McLoo** [comment]
same as #3678
