### ISSUE TITLE
Textsecure is overriding the device's default Emoji set by forcing a third-party font on the user

### ISSUE THREAD

**Issue by JoeJJJoe** [WhisperSystems/TextSecure#3681]
...leading to an inconsistent user experience on their devices.

Possible solution:

In order to enable a more unified experience accross different devices and platforms, Textsecure could use the same Emoji set as the default setting for the app, but allow the user to fall back to the device's system Emoji set if the user prefers a more consistent experience on their device.

(Sorry for abusing the issue tracker as a discussion forum earlier, I wasn't aware that this was frowned upon here.)

**Comment by ncruces** [comment]
@moxie0, I understand this is not a discussion forum, but similar concerns to my own were raised in the mailing list, to no reply.

Is there a license for the image files in eef0bcae5075d0419838b74fc8fc82bba7d98698?
If not, why not an opensource alternative?

**Comment by moxie0** [comment]
Holy shit, @JoeJJJoe please just uninstall the app and leave us alone.

@ncruces I don't know what to tell you, if nobody responded to you, then apparently nobody was interested in responding.
