### ISSUE TITLE
[Feature Request] Per contact notification tone 

### ISSUE THREAD

**Issue by dirtvoyles** [WhisperSystems/TextSecure#3686]
The only reason TS isn't my default messenger is because per user tones help me decide if the contact is worthy of a reply at any given time. For example if my wife texts I will pull over and see what she needs. If it is a business contact after hours I can safely check it at any convenient time or the next day. Thanks for all you do.

**Comment by 2-4601** [comment]
Open the conversation with your wife.
Tap your wife's name.
Choose a ringtone.

**Comment by dirtvoyles** [comment]
User is an idiot. Only tried menu, not tapping contact. Thank you and sorry to bother.

**Comment by McLoo** [comment]
just for completeness
> Only tried menu

in 2.22.2 the menu got extended with 'Conversation settings'
