### ISSUE TITLE
Allow Android emoji for those who prefer them

### ISSUE THREAD

**Issue by smerritt** [WhisperSystems/TextSecure#3690]
Some users really, really don't like the Apple emoji, and won't use TextSecure any more because of that.

I know, it sounds really petty. However, I have (or rather, had) five contacts using TextSecure (4 Android, 1 iphone), and since the release to the Play Store of version 2.22.2, two of the Android contacts have stopped using it and gone back to unencrypted SMS because of the Apple emoji.

I've seen the contributing guide: "[t]he answer is not more options". I'm not saying the right thing to do is add a user-visible preference. I don't know what the right action is. However, I've gone from having the majority of my texts encrypted to having virtually none of them encrypted, and the new emoji are what touched it off.

**Comment by moxie0** [comment]
This isn't a discussion forum, please use the mailing list for discussion.
