### ISSUE TITLE
Make "Enter name or number" translatable in the new contact view

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3703]
2.23.0
![extract string](https://cloud.githubusercontent.com/assets/174176/8761091/dbae25be-2d46-11e5-9b4a-e08a710a8877.png)

**Comment by Mihahn** [comment]
Another issue with the new contact view: please disable the keyboard popup on opening the contact view as it covers many contacts and I think many people don't like to search for contacts in the first place!

**Comment by 2-4601** [comment]
@Mihahn For clarity perhaps it would be best to open a new issue for that?

**Comment by Mihahn** [comment]
@2-4601 I'll do, just liked your screenshot to show what happens on opening :see_no_evil:
