### ISSUE TITLE
Disable keyboard popup on opening the new contact view

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/TextSecure#3704]
I think you should disable the keyboard popup on opening the new contact view as it covers many contacts and many people don't like to search in the first place.

**Comment by moxie0** [comment]
Thanks but that's how it used to be, and we intentionally changed it to this after many requests and some consideration.

**Comment by mammuth** [comment]
Okay, interesting. Wouldn't have assumed that this is the normal behavior of the user. :+1:
