### ISSUE TITLE
Update strings to reflect the change in local encryption

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3705]
`ApplicationPreferencesActivity_warning_this_will_disable_storage_encryption_for_all_messages` still talks about keys:
```
Warning, this will disable storage encryption for all messages and keys. Your encrypted
sessions will continue to function, but anyone with physical access to your device will be
able to access them.
```

Also the title `ApplicationPreferencesActivity_disable_storage_encryption`
```
Disable storage encryption?
```
might need a revise.

The new setting does not explicitly say anything about encryption anymore:
```
Enable lock screen for messages
```
Is this intentional (as in _"There are no power users"_)?

If so then some of the above strings need more adjustments.

TS 2.23.0

![screenshot_2015-07-18-12-53-56](https://cloud.githubusercontent.com/assets/174176/8761246/bf0bc800-2d4e-11e5-894c-fa5647a143ce.png)

**Comment by Dyras** [comment]
So... How does the new encryption work anyway?
