### ISSUE TITLE
Half screen direct capture no more available

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3707]
Just occurred in 2.23 on my Z1 compact 5.0.2 stock
https://gist.github.com/dfabb7d783fb83e42bb3

No more half screen, 
- not by opening direct capture --> goes to full screen directly
- not by swipe from full screen --> closes preview
- not by toggle --> no change
- landscape view looks like screenshot below

Happened suddenly, was texting and tried another direct capture

Force close does not fix this (but reboot does hopefully, waiting for battery charge...)

Landscape
![screenshot_2015-07-18-10-59-56](https://cloud.githubusercontent.com/assets/5326916/8761036/c0fa6bc4-2d3c-11e5-82b7-c77475d501d4.png)

related to https://github.com/WhisperSystems/TextSecure/issues/3577#issuecomment-120144680

**Comment by McLoo** [comment]
Nope, reboot did not fix this :sob:

**Comment by McLoo** [comment]
Good heavens, either this was pure coincidence, 
but I think there is healing power in that  apple  emoji drawer! 

- Just opened TS through recent drawer into open convo
- opened emoji drawer 
- opened direct capture 
- half screen preview is working again :clapper:

**Comment by McLoo** [comment]
Seems to be related to #3661 
While. Emoji is in the state of beeing too large, direct capture just goes along. 
Emoji go normal size, direct capture offers half screen again.

**Comment by sweah** [comment]
Same here, including the "Emoji drawer too large" correlation.

**Comment by mcginty** [comment]
Both the emoji drawer and direct capture use the same soft keyboard size guess as their measurement, so that makes sense. Solving #3661 should resolve this as well then.

**Comment by mcginty** [comment]
in 2.24.0
