### ISSUE TITLE
"Apple emojis" are really annoying. What about a user option to have the original Android AOSP emojis?

### ISSUE THREAD

**Issue by tueftl** [WhisperSystems/TextSecure#3712]
Today I got TextSecure 2.22.2 and am really sad to see these annoying apple emojis. I want the good emojis back, please!!!

I can imagine the change was done to have TextSecure running on iOS, or am I wrong? Sigh. Then please offer an option to use the original Android smilies forever, at least on Android. I would really appreciate that!

**Comment by 2-4601** [comment]
You say in #3709 that you have looked in to the old issues: #3681, #3690, #3675, #3662 and still decided to open a new one?
Please close this.

**Comment by gartenriese2** [comment]
Hello, I would also like to have an option which emoji set I want to use. Thank you!

**Comment by tueftl** [comment]
@moxie0 No, sorry, I noticed none of the others as they don't have the emoji label and I'm completely new to github (didn't manage to add that label to this...).

I'm sorry that obviously I created spam. I went here because some descriptive text told me here would be the place to tell wishes etc.

**Comment by GAS85** [comment]
Hello! I would like to notice that it was asked to have "nice" smiles in #2183, but than it was coming back to Apple. Now it is function "Use system Emoj" is available, but unfortunately some kind of users have Apple like system emoj.
 Could it be possible to have a choice between "google" like and "apple" like. Thanks you.

**Comment by moxie0** [comment]
@GAS85 No sorry we're not going to do that.
