### ISSUE TITLE
Camera out of focus

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#3713]
I can't find a way to change the camera focus when I use the quick capture. All the pictures I take are blurred :/
Edit: TS 2.23, Android 4.1.2, Samsung galaxy s3 mini (maybe it's a problem with my phone?)

**Comment by mammuth** [comment]
FYI: The quick capture in Facebook's messenger app is similar - you're not able to shoot a well focused picture.

It's definitely no individual case that it's not focusing properly. Many others I know (including me) are facing the same with text secure aswell as with the messenger.

**Comment by oaim** [comment]
I didn't know that about fb messenger -- i don't have it.
Let's wait to hear from the developers if this is intentional - though doesn't that make the quick capture kind of useless?

**Comment by 2-4601** [comment]
Duplicate of #3575

**Comment by oaim** [comment]
Sorry, I looked among the recent issues but didn't expect someone to have posted the same issue 9 days ago since the update just came through :)

**Comment by 2-4601** [comment]
@McLoo is always ahead of his time 
![face with open mouth and cold sweat emoji small](https://cloud.githubusercontent.com/assets/174176/8761790/039b930c-2d6c-11e5-9337-959b7b4df752.png)
