### ISSUE TITLE
ContactSelectionActivity doesn't resolve one phone number on GB

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#3715]
One specific phone number doesn't get resolved on my HTC Desire with 2.3.7 running 2.23.0. This just happens in the `ContactSelectionActivity`. Inside the conversation or conversation list, everything is fine. The blurred part just consists of 5 more digits, no special chars..

here is a debug log:
https://gist.github.com/anonymous/4ba23cbf6af52f7125f3

How else can I help to debug this?

![screenshot-20150718-153143](https://cloud.githubusercontent.com/assets/5296073/8761777/e5c65aa0-2d62-11e5-883f-cdbabb2df993.png)
![screenshot-20150718-153156](https://cloud.githubusercontent.com/assets/5296073/8761778/e6c55bb8-2d62-11e5-8f8d-f4b6529679e4.png)

**Comment by moxie0** [comment]
@agrajaghh How many "raw contacts" do you have for that number?  Like how many different "accounts" is it aggregated into from your contacts app?  Do all of those accounts have a name associated with the number?

**Comment by agrajaghh** [comment]
It was just a normal contact with this single number, no whatsapp, no email, no other number, nothing.

weird thing is, that its displaying the name now. I restarted the phone in between, maybe it was that... I tried reinstalling TS too, but its working now. So I can't reproduce this anymore...

**Comment by agrajaghh** [comment]
@moxie0 sorry, I was too fast. You're right. Its two contacts (I don't know why, don't even know how...)
One is named "Es......" the other one "Home Es....." with the same number but one time without spaces:

![screenshot_2015-07-21-01-05-38](https://cloud.githubusercontent.com/assets/5296073/8789643/ddc65858-2f44-11e5-9715-032589c0e717.png)
![screenshot_2015-07-21-01-05-46](https://cloud.githubusercontent.com/assets/5296073/8789644/df56e034-2f44-11e5-9298-e55bac40779b.png)
![screenshot_2015-07-21-01-06-00](https://cloud.githubusercontent.com/assets/5296073/8789646/e087eb7e-2f44-11e5-9c2b-9e2ee2aeae0c.png)

**Comment by agrajaghh** [comment]
Sorry, I'm too tired... I just checked it on my Nexus 4, but the issue was on the HTC Desire...
So the issue still persists! On 2.3.7 the contacts are not aggregated, they or both listed in my contact app.

**Comment by moxie0** [comment]
Thanks, so just to be clear, rebooting this phone didn't help?

In the contact selection screen, the names we're rendering are the names that are associated with the raw contact that we queried and displayed. So somehow it seems as if the TS raw contact isn't being aggregated with your google account's raw contacts.  On >GB we explicitly tell the contacts provider to aggregate them, but apparently on GB that will sometimes cause your phone to reboot.

**Comment by agrajaghh** [comment]
Nope, rebooting the Desire didn't fix it. I'm still just seeing the number like in my original/first post. 

The "Home" has it saved as a home number and the contact without "Home" as a mobile number if that matters...

**Comment by moxie0** [comment]
@agrajaghh ...and there's not a separate un-aggregated contact with just the phone number in it?

**Comment by agrajaghh** [comment]
@moxie0 nope, I scrolled through all the contacts in the contacts app, and every one of them has a name.

**Comment by moxie0** [comment]
Can you install the app "content provider helper" and see what's up for that record?  Does the row for that number with the "vnd.android.cursor.item/vnd.org.thoughtcrime.securesms.contact" mimetype have a display name? Is it aggregated into the same contact id as the rest of the raw records?

**Comment by moxie0** [comment]
(content://com.android.contacts/data) is the provider you'd query from that app

**Comment by moxie0** [comment]
(on second thought, it seems some raw contacts are always going to fail to aggregate, particularly on GB, so I'll just go ahead and use the standard resolution process)

**Comment by agrajaghh** [comment]
In case you still need it:
https://gist.github.com/anonymous/0cf32394a3035472d734

the only line with "vnd.android.cursor.item/vnd.org.thoughtcrime.securesms.contact" mimetype and the specific number

**Comment by moxie0** [comment]
Thanks for doing that!  It indeed looks like an Android bug, where the raw contact is failing to aggregate and get the display name.  I think my last commit should work around that, if you can give it a go.

**Comment by agrajaghh** [comment]
already building :P gimme a sec

**Comment by agrajaghh** [comment]
fixed! Thanks :+1:
