### ISSUE TITLE
(rfe) Swipe to call

### ISSUE THREAD

**Issue by thoraxe** [WhisperSystems/TextSecure#3717]
In the default Android messaging app it is possible to swipe a person from the list of text messages and call. 

It would be nice if textsecure would support this. Granted I can click into a message thread and click the call button, or click the person's icon and then the call button...

**Comment by Dyras** [comment]
I suggest adding this when Signal gets integrated. Would be amazing to be able to call someone over Signal simply by swiping their name.

**Comment by thoraxe** [comment]
I'm not sure why we would have to wait. The swipe should call the native system call dialog, whether or not Signal / Redphone / whatever is the default calling program...?

**Comment by moxie0** [comment]
Thanks but I don't think we're going to do this.
