### ISSUE TITLE
Contact name inconsistently ellipsized in landscape

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3718]
1. Use a device with a screen so small that the string _"Send TextSecure message"_ (`conversation_activity__type_message_push`) gets ellipsized in portrait
2. Rotate to landscape
3. The string is still ellipsized even though there's enough space for it

**GOOD:**
![portrait](https://cloud.githubusercontent.com/assets/174176/8762104/bb2e619c-2d77-11e5-9206-e9194eab27bd.png)

----------

**BAD:**
![landscape-1](https://cloud.githubusercontent.com/assets/174176/8762107/c5394166-2d77-11e5-9888-bb9ec4aa8aa9.png)
^ Also note that the same thing happens to the contact name above

![landscape-2](https://cloud.githubusercontent.com/assets/174176/8762005/e09ee120-2d74-11e5-87b3-fca091321111.png)

TS 2.23.0, Huawei U8800 (480 x 800 px), Android 4.0.4

**Comment by McLoo** [comment]
Going to replace my xkcd feed subscription with  your issues, to start my day 😜

**Comment by 2-4601** [comment]
That wouldn't help because I've outsourced my issue reports to the xkcd guy (or someone who claims to be him). E.g. this cost only two cups of raisins.

**Comment by mcginty** [comment]
what a hot mes...

**Comment by 2-4601** [comment]
If fixing this is not very time consuming and to strike while the mes... iron is hot #3731 is a very similar new issue.

**Comment by mawed** [comment]
Maybe even the name is not fully shown?

**Comment by 2-4601** [comment]
@mawed That's right. I wrote about it under the screenshot but I guess it was missed :)

However the contact name misellipsizeation does not always happen.
Here's how to reproduce:
- Tap the contact name to open recipient preferences
- Go back to conversation
- Rotate to landscape

**Comment by mcginty** [comment]
temporarily removing ellipsizing in 2.24.0
