### ISSUE TITLE
Registration trouble : Indian number

### ISSUE THREAD

**Issue by dcherian** [WhisperSystems/TextSecure#3719]
My friend recently updated his Moto X (2nd gen) to Android 5.1. Since then he's had trouble receiving group messages. He has uninstalled and reinstalled 2.22.2 but now it doesn't receive the SMS for verification, so he's unable to register.He's using an Indian phone number to register.

**Comment by agrajaghh** [comment]
We need a debug log from your friends phone to see whats happening

**Comment by moxie0** [comment]
If the voice call registration option doesn't work, unfortunately there's nothing we can do.
