### ISSUE TITLE
Emojis still not centered

### ISSUE THREAD

**Issue by wp9015362** [WhisperSystems/TextSecure#3720]
Hello,

this is a follow-up issue to:

https://github.com/WhisperSystems/TextSecure/issues/3317

I know that this should have been fixed by @mcginty via https://github.com/WhisperSystems/TextSecure/commit/9b2aabfdc8ece6c1002176ae75abe98229a46054 and yes, it's much better now (thanks for that), but it's still not solved.

You can easily reproduce it by doing the following steps for example:

1. Have an empty message input box
2. Insert an Emoji into the message input box via the TextSecure Emoji drawer
3. Hit the space key on the keyboard to insert a space after the Emoji
4. Now you should see that the Emoji has suddenly moved it's position a bit down
5. Press backspace on the keyboard to remove the space again
6. Now you should see that the Emoji is centered again

Could you please fix it?

Regards

**Comment by Dyras** [comment]
Yup, can confirm this is also happening for me.

**Comment by 2-4601** [comment]
But... this would remove the surf feature
![surf](https://cloud.githubusercontent.com/assets/174176/8765652/f7e4f09a-2e1e-11e5-8e74-8918784268c2.gif)
