### ISSUE TITLE
Can't import backup

### ISSUE THREAD

**Issue by IOAyman** [WhisperSystems/TextSecure#3723]
I've exported a backup of 2920 sms' on an older version (can't remember which one exacytly), but I can't import it back now!
 
***EDIT :***
The app crashes after few seconds

Device  : Samsung GT-S6102
Android : 2.3.6 (JPMA3, GINGERBREAD.JPMA3)
Memory  : 6M (0.35% used, 64M max)
Memclass: 64
OS Host : DELL218
Current App     : TextSecure 2.22.2

**Comment by agrajaghh** [comment]
we need a debug log to see whats happening...

**Comment by IOAyman** [comment]
Is the debug submission from the app enough?

**Comment by agrajaghh** [comment]
yes, generate the debug log after the import failed

**Comment by IOAyman** [comment]
Already (did that)[https://gist.github.com/anonymous/71991620244304d2db36] few minutes ago.

But didn't notice any additional info than these in the gist :/

**Comment by agrajaghh** [comment]
ah damn, didn't notice that you're running android 2.3 (debug log is empty on 2.3)
Could you generate a debug log with adb?

**Comment by IOAyman** [comment]
I will, once I figure out how to enable usb debugging on 2.3. I don't have it on the settings!

**Comment by McLoo** [comment]
@IOAyman would you mind checking if the second line in the backup XML is 
`<!-- File Created By TextSecure -->`?
Can you browse the XML with SMS Backup & Restore?

**Comment by IOAyman** [comment]
@agrajaghh I'll do as soon as possible.

@McLoo Sure. The second line comment is there.

I also checked if the XML file is correct too; I mean no missing quote or something likewise (because it happened with me on an earlier version) ... It is correct.

**Comment by moxie0** [comment]
Can't do anything without a debug log. You'll have to use adb.

**Comment by riyapenn** [comment]
Closing as there has not been any new information over the past ~3 months, and no other users being able to provide information on this.
