### ISSUE TITLE
"Enter key sends" doesn't work with SwiftKey

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#3724]
It just dismisses the keyboard but the message isn't sent. If I long press the enter key, the keyboards emoji drawer gets open with another enter button. This enter button inserts a new line which is shown as a space in the EditText but as a new line in the sent message.

Tested on N4 Android 5.1.1 and HTC Desire 2.3.7 both running TS 2.23.0

**Comment by 2-4601** [comment]
Ice Cream Sandwich (or the specific 4.0.4) system keyboard has the same issue. Enter key is labeled as _Done_ and it just dismisses the keyboard and does not send.

**Comment by mcginty** [comment]
fixed in 12b8eee86ffbc2bf286c1218c58ee6cb0d6017fd

**Comment by agrajaghh** [comment]
confirmed :blush:
