### ISSUE TITLE
"Send TextSecure Message" inside enter button too long (Google Keyboard)

### ISSUE THREAD

**Issue by agrajaghh** [WhisperSystems/TextSecure#3725]
With "enter key sends" enabled, the enter key of the google keyboard displays "Send TextSecure message" which looks really weird. I'm not sure if we can fix this without changing the landscape send button..

![screenshot_16-04-06](https://cloud.githubusercontent.com/assets/5296073/8766241/f67afb3a-2e2f-11e5-9348-cf44101df45e.png)

Tested on a N4 with 5.1.1 and TS 2.23.0

**Comment by mcginty** [comment]
![thanks](https://cloud.githubusercontent.com/assets/373823/8774260/211ce784-2e91-11e5-9405-fea7af4f3c5d.png)
