### ISSUE TITLE
Conversation List Fails to Adjust to Landscape Mode

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/TextSecure#3731]
When rotating the conversation list from portrait to landscape mode (by rotating the phone), the message previews of the conversations are often not adjusted to the new (wider) screen width. They then stay exactly at the same length they had in portrait mode.

Most often, this happens after returning from (single) conversation view to the conversation list via the "Back" button.

I'm currently using v2.23.0.

**Comment by 2-4601** [comment]
Related #3718 

Also happens when switching to another app and then switching back to TS and rotating.

**Comment by RiseT** [comment]
Issue still present in v2.23.1.

**Comment by mcginty** [comment]
What version of Android are you on? I can't get this to happen on my Lollipop device.

**Comment by 2-4601** [comment]
Reproducible on Nexus 4, stock 5.1.1, TS 2.23.3
1. Open a conversation
2. Go back to conversation list
3. Rotate device to landscape
4. Snippets ellipsized as if device was still in portrait

**Comment by mcginty** [comment]
ohhh, just the ellipses. Yeah so this is vacuously fixed in 2.24.0 as I work out how to get InputFilters to react to layout changes.
