### ISSUE TITLE
Change inputType to textShortMessage

### ISSUE THREAD

**Issue by cygairko** [WhisperSystems/TextSecure#3738]
I am using SwiftKey, but I think this also fits to other keyboards.
When typing a message on other messages, the Enter button is replaced by a Smiley button.

If inputType for EditText field of messaging would be changed to textShortMessage the behavior would be adjusted to match other messengers, where a smiley is more likely used than Enter.

**Comment by 2-4601** [comment]
The IME's smiley button summons the system emoji keyboard which is inconsistent with the Apple-like emoji set that TextSecure currently uses. So I think this would not suit TextSecure that well.

**Comment by cygairko** [comment]
But having a look to 
https://developer.android.com/reference/android/widget/TextView.html#attr_android:inputType
and following
https://developer.android.com/reference/android/text/InputType.html#TYPE_TEXT_VARIATION_SHORT_MESSAGE
it says
"Variation of TYPE_CLASS_TEXT: entering a short, possibly informal message such as an instant message or a text message."

And TextSecure is about instant messaging and not writing emails...

**Comment by 2-4601** [comment]
Just recently there was a desire to **turn off the system emoji button** completely (#3722) for better emoji ux. If the change you proposed would display it on the keyboard by default (instead of hiding it behind the _Enter_ key as is the current behavior) it would make the situation worse.
This is more about emoji ux rather than the ability to enter line breaks.
Besides WhatsApp has the exact same issue and same solution.

**Comment by cygairko** [comment]
Ok, if you wanna force the app specific emojis you may be right.
I always prefer the IME ones, as they offer text only smileys.

For me in WhatsApp, Hangouts a short click on enter opens smileys and a long click inserts a line break.
With TextSecure, k9 it is vice versa.

**Comment by 2-4601** [comment]
If you dislike the _Enter_ key as breaking new lines you can at least change it's function to send the message: _Settings -> Advanced -> Enter key sends_
Perhaps not fully satisfying but at least it won't break new lines anymore :)

**Comment by cygairko** [comment]
No, I dislike having to long press Enter to reach (IME) smileys.

And as I read that textShortMessage is supposed by Google for instant messaging forms, I opened this issue. If the TextSecure team is not following those "guidelines" in order to privilege the own emojis, it is ok and I will (and have to ;)) live with it.

**Comment by moxie0** [comment]
thanks but we're not going to do this
