### ISSUE TITLE
SecurityException Crash on sharing link from chrome 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3740]
https://gist.github.com/e3f83f07f23e3a9b22ab

Also sent crash report. 

- Selected share link in Chrome 
- Chose TS 
- Unlocked with passphrase 
- crash 

Edit: reproducible with chrome and locked TS
not reproducible with chrome and unlocked
not reproducible e.g. with sharing from famous e-auction platform app
not reproducible with sharing image and locked TS

**Comment by McLoo** [comment]
persists with
new Chrome version (44)
new TS version (2.24.0)

**Comment by Dyras** [comment]
Still happening for me.
https://gist.github.com/anonymous/7701883ecf43508c0d94

**Comment by McLoo** [comment]
closing in favor of #3990
