### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by JeremyWW** [WhisperSystems/TextSecure#3744]
Hi,

Just started using TextSecure. I have a few requests / suggestions but for starters could we have more choice of theme colours? For example I'd like to have a white background for the main window with the title bar and new message 'bubble' in black. So, I guess a full palette of colours would be best that can be chosen with a white or black background, with the option to have contact 'bubbles' match the chosen theme colour.

Thanks

**Comment by JeremyWW** [comment]
... also to chose monochrome contact 'bubbles' if desired.

**Comment by moxie0** [comment]
thanks but we're not going to do this

**Comment by JeremyWW** [comment]
Could we at least have the option to have black on a white background?

**Comment by moxie0** [comment]
@JeremyWW this isn't a discussion forum
