### ISSUE TITLE
Mobile Numbers Only

### ISSUE THREAD

**Issue by JeremyWW** [WhisperSystems/TextSecure#3745]
Could we have the option to display only mobile numbers / contacts with mobile numbers in the contact list.

Thanks.

**Comment by mcginty** [comment]
Hey @JeremyWW, welcome to the TextSecure repo! Please search our open and closed issues before posting - it saves us some overhead from filtering.

Closing as dupe of https://github.com/WhisperSystems/TextSecure/issues/1011.

**Comment by JeremyWW** [comment]
Apologies. It was done late last night from my phone. Not as easy to search as it is from the desktop.
