### ISSUE TITLE
No keyboard in contact list

### ISSUE THREAD

**Issue by JeremyWW** [WhisperSystems/TextSecure#3746]
Could we have an option (at least) not to automatically display the keyboard when accessing the contact list? Very often it suffices to scroll through the contacts and then select the one you want, particularly as TextSecure contacts are all listed at the top.

Thanks

**Comment by moxie0** [comment]
duplicate issue

**Comment by JeremyWW** [comment]
Apologies. It was done late last night from my phone. Not as easy to search as it is from the desktop.
