### ISSUE TITLE
Non-ts Messages arriving late

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#3747]
https://gist.github.com/42eb010107ccf658f1d6
Received mms message one hour late from time zone one hour behind me.  Message details had the time as 3 seconds before received time even though my wife received the message earlier when it really was sent. Let me know if this sounds like horrible network or something like that.

**Comment by moxie0** [comment]
Sounds like an issue with your carrier. We don't have any control over delivery of MMS/SMS messages, and just insert them as soon as they arrive.
