### ISSUE TITLE
Some contact pictures are not round

### ISSUE THREAD

**Issue by mammuth** [WhisperSystems/TextSecure#3749]
[Screenshot](https://imgur.com/HNXaSbw)

Some of the contacts images are not shown in a circled shape. I didn't find out, how to reproduce this so far... however it looks like this can be "solved" by changing or even re-adding the contact picture via the Android contacts.

Edit: Of course the original Android contact images are "normal", squared images without any white margins.

**Comment by RiseT** [comment]
Is it possible your original image has white margins on both sides...?

**Comment by riyapenn** [comment]
Closed for not reproducible and no other users reporting the same issue.
