### ISSUE TITLE
Can't update push directory

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#3754]
Since 2.23.1 there is no way to update push directory. There was some discussion here (https://github.com/WhisperSystems/TextSecure/commit/f2a323ef7f0513cdad8516af736e56781e06c085) as to whether or not pull to refresh should be activated on jelly bean. In any case, there should be a way for everyone to update the push directory

**Comment by moxie0** [comment]
I'll enable PTR for JB, otherwise you can do it through your normal system sync settings.

**Comment by 2-4601** [comment]
The system settings sync for TextSecure was off by default. Is this a bug or intended behavior?
Nexus 4, stock 5.1.1, TS 2.23.1

**Comment by agrajaghh** [comment]
> The system settings sync for TextSecure was off by default. Is this a bug or intended behavior?
> Nexus 4, stock 5.1.1, TS 2.23.1

same device, same version, same problem

**Comment by 2-4601** [comment]
> same device, same version, same problem

I'm agrajaghh[!!!](https://www.youtube.com/watch?v=-8h_v_our_Q)

Also my Huawei U8800, Android 4.0.4 was not synced by default.

**Comment by moxie0** [comment]
In 2.24.0

**Comment by moxie0** [comment]
@2-4601 Yeah it's cool that it's disabled by default, we primarily sync through an alarm that we run in the app, precisely because otherwise users might disable system sync without knowing what the implications of that are.

**Comment by johanw666** [comment]
Tested the swipe with my tablet (Asus Transformer TF101G with Android ICS 4.0.4. I changed the source and enabled the change in https://github.com/WhisperSystems/TextSecure/commit/87401a5ba70b0192bd8c8abb9ca5b9d707639e2d for all Android versions.

Swiping worked OK on this setup.
