### ISSUE TITLE
Can't use TextSecure without registering?

### ISSUE THREAD

**Issue by michaelsproul** [WhisperSystems/TextSecure#3755]
Unfortunately my number is registered on the CyanogenMod servers and I've been unable to unregister it. Regardless, I'd been using TextSecure anyway as I like it as a messaging app. Having just reinstalled from source I now can't seem to get past TextSecure's registration phase, which I recall bypassing previously when I got the Cyanogen error. I'm guessing this is an intentional policy change? Can't use the app at all without registration? Sorry for the banal issue but I haven't been able to find another issue or pull request about this.

Thanks!

**Comment by agrajaghh** [comment]
try unregistering from Cyanogen WhisperPush here: https://whispertool.cyanogenmod.org/

**Comment by moxie0** [comment]
@michaelsproul http://support.whispersystems.org is your best place for support

**Comment by michaelsproul** [comment]
@agrajaghh, thanks so much! Unlike every other unregister solution I've tried that actually worked!

I'll definitely use http://support.whispersystems.org for future enquiries, thanks!
