### ISSUE TITLE
Recent Text Secure version: Not possible to end secure session and display key of partners.

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/TextSecure#3756]
In recent versions of TextSecure I am missing two things, that have been available in older releases.

- Ending a secure session in order to iniate new key exchange

- Displaying keys of alle communcation partners (not only the own key)

Why these changes? NSA?

Please re-add these functions.

**Comment by skulumani** [comment]
Do you have a lock icon at the top of the conversation?

Within that menu are the options to "Verify Keys" and "End secure Session"

**Comment by Norbert80** [comment]
Sorry, my mistake. I have found the lock. Thanks.

But how to display the other keys?

**Comment by skulumani** [comment]
Github isn't meant to be used for support questions but rather for the active development of the app, support.whispersystems.org is meant for app help. 

But do you see an option for "Verify Keys". It might help if you post a screen shot of what is your issue.

**Comment by Norbert80** [comment]
I am ashamed. I found everything. Please close and forget this issue. If possible please delete it. 😬

I don't now why I have been confused...

**Comment by skulumani** [comment]
You can close the issue yourself. 

It's not a problem.

**Comment by Norbert80** [comment]
Perhaps I didn't see these items because I had a group open.

What are the reasons why these two things are not available for groups?

**Comment by skulumani** [comment]
I just created a group and agree that it's not possible to directly verify the keys in a group. 

Maybe the rationale is that group members would also be in individual conversations where the keys are verified. 

You might want to consider adding a different issue with some screenshots and detail on adding the ability to verify the keys within a group conversation?

**Comment by Norbert80** [comment]
@skulumani 
I have filed issue  #3792. But I am not experienced in GUI design. I hope someone else comes up with a good idea how to implement this in the GUI.
