### ISSUE TITLE
Emoji peeking through behind ellipsis 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3765]
... If conversion list was closed with back button and re-entered through app icon - guess that's OnCreate()  then? 

If you come back from a convo,  no emoji shows up 

![screenshot_2015-07-22-23-47-13 01](https://cloud.githubusercontent.com/assets/5326916/8838502/4f4ef550-30cd-11e5-92d4-418842655cbe.png)

(~~could swear the android emoji were not that keen 😜~~ hm,  I was wrong then 3266)

**Comment by McLoo** [comment]
Sample msg:
`I crèvent das cost Möbel what toujours Abitur necromancer 😱`

**Comment by 2-4601** [comment]
#3266 has risen from the grave?

**Comment by 2-4601** [comment]
I was able to summon this satanic bug on my Huawei U8800, Android 4.0.4 by rotating the device in evil ways. Can't figure out exact steps now. Too tired. My Nexus 4 was blessed and saved from this.

**Comment by mcginty** [comment]
@McLoo can you reproduce in 2.24.0?

**Comment by McLoo** [comment]
nope.
