### ISSUE TITLE
Quick camera icon wrong dimensions in hdpi

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3769]
on my HTC One S CM 12.1

when switching to front camera the icon changes  as expected, but also it get's smaller

guess cause of the different image dimensions in hdpi
`quick_camera_rear.png` is 36x36
whereas `quick_camera_front.png` is 54x54

*someone didn't use the cool svg to png script...*

**Comment by agrajaghh** [comment]
looks like a job for me :grin:

**Comment by McLoo** [comment]
:imp:licated that :grimacing:
