### ISSUE TITLE
New permissions in TextSecure 2.32.2

### ISSUE THREAD

**Issue by mackrauss** [WhisperSystems/TextSecure#3771]
Hi,
I am a big fan of TextSecure and just discovered the new version (2.32.2) in the Google Play store. Unfortunately, the app is requesting a lot of new permissions. The stated reason is so you can integrate RedPhone later on, which makes sense to make TextSecure more like Signal.

While I don't want to imply that I think you guys are doing anything fishy with my data, you will surely understand that people might not install a secure messaging app that has just about access to anything. 

For example, I cannot see how access to my Calendar is important to exchange messages nor to make phone calls. 

I think it would really serve you and the community well if you would put an explanation of all the permissions in a prominent place on the open whisper systems website. Having this information easily accessible (link from Google store to that site?) will help users to build trust. 

Of course anyone can read the code to see that you are not up to anything, but that isn't a good enough answer here since not many people will have the time nor the technical expertise to do so. 

If your code is audited you could add information about audits on your website, stating who did the audit, with which version of the app and link to their results.

Thanks!

**Comment by moxie0** [comment]
This is an issue tracker, not a discussion forum. Please respect our time by keeping this kind of thing to the support center or the mailing list.
