### ISSUE TITLE
Wrong emoticons in Android

### ISSUE THREAD

**Issue by jvlatzko** [WhisperSystems/TextSecure#3772]
Hi, 

seems there was a mixup - in the latest TextSecure for Android, Apple's Emoticons are bundled with the app. 
This doesn't fit the system, obviously. 

Revert should be trivial, no?

**Comment by Fanch3n** [comment]
It's intentional and was done to provide a consistent user experience across several devices. It won't be reverted and there are lots of (closed) issues about this already.

**Comment by jvlatzko** [comment]
Oh wow, I had no idea. 
This goes against everything I expected, as an android user I don't care how it looks on iOS, and vice-versa. 
Why converge on the smaller ecosystem?

**Comment by Fanch3n** [comment]
https://github.com/WhisperSystems/TextSecure/issues/3709
If you need it. As was stated before, this isn't a discussion forum, you'll have to go to the mailing list for that. All necessary information can be found in the link.

**Comment by jvlatzko** [comment]
Thanks, I'm closing this.
