### ISSUE TITLE
Missing camera controls after turning screen on again

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3775]
2.23.2 and 2.24.0 branch

- open direct capture
- go landscape
- turn screen of / wait till screen turns off
- go portrait
- turn screen on
- have camera preview in full screen portrait without controls
- (#3767 tap focusing works, but shows no circle animation)

**Comment by turtlekiosk** [comment]
I can confirm experiencing this issue too.

**Comment by mcginty** [comment]
damn, good find

**Comment by McLoo** [comment]
would have been more flattered without the comma :wink:

**Comment by mcginty** [comment]
in 2.24.0
