### ISSUE TITLE
Large GIFs not thumbnailed or viewed

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3778]
Tried some GIFs on my HTC One S

for that I had no DRAFT thumbnail while the phone lagged (cause of to many open apps??)
http://laps.noaa.gov/albers/slides/ast/eclipse12_large.gif

for that I had no draft thumbnail, no thumbnail and an empty image view
http://www.diplom.org/Online/maps/20th-large.gif
GIF was perfectly received though on an 2.23.2 device

Log right after added the latter as draft: https://gist.github.com/7754133739d24d662ef9

**Comment by mcginty** [comment]
Yeahhhhh, looking into how we can support dimension limits on gifs in a way that works in both the animated and un-animated varieties. There's also, as far as I know, no easy way to detect if a gif being loaded is animated or not so we can't just say "treat all the non-animated gifs like regular images."

**Comment by f41c0r** [comment]
This is what the hard way looks like, in javascript... https://github.com/mailcharts/animated-gif-detector/blob/master/index.js

**Comment by McLoo** [comment]
@mcginty didn't look further, but what about Glides getFrameCount() https://github.com/bumptech/glide/blob/master/third_party/gif_decoder/src/main/java/com/bumptech/glide/gifdecoder/GifDecoder.java#L250
