### ISSUE TITLE
2.23.2 higher memory usage

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#3780]
https://gist.github.com/545b3e8b12d586446a18
Memory usage seems noticeably higher now. Was @ 111M at one point. Not doing anything too special. Mostly TS contacts.

**Comment by oaim** [comment]
Are you by any chance experiencing similar issues to the ones I'm experiencing? https://github.com/WhisperSystems/TextSecure/issues/3651

**Comment by jeremymasters** [comment]
@oaim I haven't noticed that

**Comment by jeremymasters** [comment]
https://gist.github.com/ef273ed984448c07a5d9
So I think I see one thing that makes it jump up.
Go into a conversation thread in portrait. 
Tap to start typing a message but don't type message.
Rotate to landscape.
Rotate back to portrait. 
Note big lag.  Keyboard (SwiftKey) doesn't appear for awhile and that made my memory usage jump 20M,from 69M to 87M.

**Comment by McLoo** [comment]
Confirmed With SwiftKey, but not with Sony stock keyboard...

**Comment by jeremymasters** [comment]
Rename SwiftKey to Lethargic Key?

**Comment by Dyras** [comment]
Confirmed here as well with SwiftKey.

**Comment by RupertPaulson** [comment]
Here as well with SwiftKey...

**Comment by mcginty** [comment]
fucking SwiftKey again!

**Comment by Dyras** [comment]
Since SwiftKey is obviously problematic I have to ask, what are you using?

**Comment by mcginty** [comment]
I use the Google Keyboard, personally. It's more responsive for swipe gestures, fewer noticed bugs.

**Comment by moxie0** [comment]
in 2.24.0
