### ISSUE TITLE
2.32.2 really wants to have a lot of permissions

### ISSUE THREAD

**Issue by pnathan** [WhisperSystems/TextSecure#3782]
Hi,

TextSecure now wants permissions that allow TextSecure to know about...

* 'Device and app history', which gives a readout about activity on the device, including which apps are running, browsing history & bookmarks, 

* my calendar

* my physical location

* my microphone

* and the name of my wifi connection.

**This is not cool.**

Your update notes say that permissions are being upgraded in relation to merging with RedPhone. Some of these things make sense in relation to that, but I fail to understand:

* why you want my calendar

* why you want my physical location

* why you want the ability to read my wifi infomation

Please advise, as this level of permissions is really not something I like giving out at all.

**Comment by Dyras** [comment]
Not sure about calendar. Maybe to make it easy for people to invite each other to events?

Physical location has to do with sending your... location. Try Telegram and you will see that they have it.

Wifi info has something to do with MMS. Or maybe that was in a dream I had.

Here's Moxie's explanation about the security thinking:
https://github.com/WhisperSystems/TextSecure/issues/3781#issuecomment-124559223

**Comment by moxie0** [comment]
@pnathan This is an issue tracker, not a discussion forum.  Please direct these kinds of questions to the support center (http://support.whispersystems.org) or the mailing list.

> This is not cool.

I guess I'm not entirely surprised that someone with a GNU avatar considers themselves the standard for cool.

> why you want my calendar

So you can send event info to people.

> why you want my physical location

So you can send your location to people.

> why you want the ability to read my wifi infomation

So we can fix some MMS bugs that happen when some devices are connected to wifi.

As always, all of our software is open source, so it's pretty easy to verify that we're using these permissions appropriately.  If you don't want to send your location to people, then don't send it.
