### ISSUE TITLE
crash upon opening from notification 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3787]
Also sent crash report. 

Was a group creation message (that was what I got after reopening TS, crash free this time) 
Just two words in the group name and two group members 

https://gist.github.com/3aa7890111ca6421487d

**Comment by moxie0** [comment]
I think this is a duplicate of #2971?

**Comment by McLoo** [comment]
curses.
more a duplicated of #3466 :tired_face: 

maybe of use: I tapped the notification on the lock screen
