### ISSUE TITLE
2.23.3 fails to build

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#3789]
After the Gradle bump, I get this: 
``` 
Error:(145, 66) error: 
<anonymous org.thoughtcrime.securesms.jobs.CleanPreKeysJobTest$TestModule$1> is not abstract and does not override abstract method create() in SignedPreKeyStoreFactory
```
and
```
Error:(91, 51) error: <anonymous org.thoughtcrime.securesms.jobs.DeliveryReceiptJobTest$TestModule$1> is not abstract and does not override abstract method create() in TextSecureMessageSenderFactory
```
After reverting https://github.com/WhisperSystems/TextSecure/commit/20313127f598a42cc22ed5c15a193314c0e9412e the build went OK (after Android Studio made me change the Adroid plugin version)

I'm using Android Studio 1.2.2 on Windows 7 64 bit, JDK 1.7.75.

The odd thing is, when I downgrade I get the same error but the build still succeeds???

**Comment by rmueller83** [comment]
You should simply need to remove the `MasterSecret masterSecret` argument from the parantheses in CleanPreKeysJobTest line 147.

**Comment by johanw666** [comment]
Is that related to https://github.com/WhisperSystems/TextSecure/commit/8d9ae731ef4124dbb3900e0b62cc98199b64c783 ? I don't quite understand what that update does anyway. Has local encryption om some files been removed?

**Comment by johanw666** [comment]
OK, I see it now, these files are only related to the tests. Build works OK now after changing both files in that directory the build succeeds with the new Gradle.

**Comment by brumsoel** [comment]
I guess this can be closed? I see no problems when building current versions.
