### ISSUE TITLE
Keep state of the send button

### ISSUE THREAD

**Issue by sweetdub** [WhisperSystems/TextSecure#3790]
If I send an insecure sms to a friend who also have TextSecure, when I close and launch the application, the send button state will be in "secure" mode per default.

Would it be possible to maintain the last state of the send button between launches of the app?

May refer to #3639

**Comment by moxie0** [comment]
This is by design.  If your friend no longer has TS installed, they can unregister here: https://whispersystems.org/textsecure/unregister

**Comment by sweetdub** [comment]
I may not explain this really clearly I'm sorry.

I meant this regarding 2 users that are registered to TS but sometime you don't have an internet connection during a period so you send insecure sms to your friend. When you restart TS, the app select per default the secure sms even if you were sending insecure sms to this friend for a while because you don't have an internet access.

It just an idea of UX improvement to automaticly select the last type of sms (insecure or not) you sent to this contact.

**Comment by Bastelbursche** [comment]
@moxie0 Please reopen. This is an annoying behaviour. Have to reselect SMS dozens of times. Already switched back to standard SMS app because of this. It's hard to write with friends if the app switches back to secure messages all the time and he or she can't receive at a certain period.
