### ISSUE TITLE
Feature Request: manually force contact synchronization/add some (visual) feedback

### ISSUE THREAD

**Issue by mawed** [WhisperSystems/TextSecure#3791]
The new contact screen is really nice, but I miss the possibillity to synchronize the contacts manually to find new TS/Signal users faster.

Maybe this coul be possible via menu button?

Regards

**Comment by McLoo** [comment]
just pull the list down (pull to refresh)

**Comment by mawed** [comment]
Nothing's happening.

If this is the answer could there be some feedback?

**Comment by McLoo** [comment]
There  is a visual feedback. 
Are you on Android Jellybean? #3754

**Comment by mawed** [comment]
I'm on 4.2.2.

How should it look like?
