### ISSUE TITLE
Group Chats: Not possible to end secure session and display key of partners

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/TextSecure#3792]
Please support end secure session and display key of partners also for group chats. In recent builds this only works for normal chats.

**Comment by moxie0** [comment]
Ultimately we're going to remove "end secure session" all together.

**Comment by Norbert80** [comment]
@moxie0 why? Letter of intent?

**Comment by Norbert80** [comment]
@moxie0 and what about the second part of this issue to compare keys?

**Comment by Norbert80** [comment]
I have filed issue #3800 for the second part of this issue.

@kulumani if @moxie0 still resists to explain why he removes security related features it looks like he has got an letter of intent from the nsa.

If end secure session is unavailable, there is no way to break up a MITM attack.

**Comment by ChaoticMind** [comment]
See point 2 [here](https://github.com/WhisperSystems/TextSecure/blob/master/contributing.md) and the article [here](https://en.wikipedia.org/wiki/Jumping_to_conclusions).

**Comment by moxie0** [comment]
lol, @Norbert80 that's not what that "feature" does.  Perfect example of why it shouldn't be visible.
