### ISSUE TITLE
identify signal/textsecure users in contact list

### ISSUE THREAD

**Issue by grrrrr** [WhisperSystems/TextSecure#3796]
I found it very useful to be able to identify which users are signal/textsecure users. e.g. I know person_A is traveling to country_X and should not be contacted over SMS, before the contact list revamp I could very easily see whether a message to them would be via sms or TextSecure.

Following the revamp I have to. 

1. go to contacts
2. select contact
3. start typing something to see if I get TS or SMS send (because "attach" is the default option on a new message)

**Request**

Can we can some sort of visual indication of whether a contact is a TextSecure user in the contact list?

**Comment by mammuth** [comment]
The new contact list is "seperated" into two sections:
- TEXTSECURE USERS
- ALL CONTACTS

Those are below each other.
So in the contact Listview the contacts on top are all TS users. After them all other contacts are following.

Isn't that exactly the *visual indication of whether a contact is a TextSecure user in the contact list* your're looking for?

**Comment by moxie0** [comment]
also the attach will have a blue or grey background depending on whether they're registered or not

**Comment by grrrrr** [comment]
@mammuth  

Umm, that was the old contact list, non? The one I have in 2.23.3 just shows all contacts with no distinction between TS and regular users.


@moxie0 good to know but it's still an unnecessary step to have to go through to see what can receive secure messages

**Comment by f41c0r** [comment]
![screen_1](https://cloud.githubusercontent.com/assets/4326714/8890579/ae6ad31a-32cb-11e5-88b5-6481fb70d6f0.png)

![screen](https://cloud.githubusercontent.com/assets/4326714/8890582/b5ea76ea-32cb-11e5-9e64-f5891c6ba363.png)

![screen_1](https://cloud.githubusercontent.com/assets/4326714/8890585/bad9cf20-32cb-11e5-9fcf-20a9fc9a2485.png)

**Comment by grrrrr** [comment]
@f41c0r  the 1st screen I don't get that any more, it has disappeared since two updates ago.

the other two screenshots, yes i am aware of the color differentiators on the chat screen.

**Comment by grrrrr** [comment]
removed and re-installed TextSecure,  still only see "All Contacts"  and no "TextSecure Users"

@moxie0 can this be re-opened as a bug or should I open a new ticket?

**Comment by f41c0r** [comment]
Take some screenshots of your app? are you hitting the little pencil button at the bottom?

**Comment by grrrrr** [comment]
@f41c0r 

I am not in a position to take screenshots as I can not redact them at the moment.  Rest assured I am doing what I normally do, as you say pressing the pencil and know how to get to the screen depicted in your 1st shot.

**Comment by grrrrr** [comment]
More details

Samsung Galaxy S4
CyanogenMod CM11 M11
TextSecure 2.23.3

**Comment by f41c0r** [comment]
Why can't you just take a screenshot and cover the names/phone numbers with little black boxes like I did?

**Comment by grrrrr** [comment]
I am on phone, not able to do that on phone.

All you sill see in any screenshot of the contact list is as I have said a couple of time now. just the "All Contacts" at the top of the screen where you have "TextSecure Users".   "TextSecure Uses" does not appear at all.

**Comment by f41c0r** [comment]
Oh. Either there is a bug, or the app doesn't see that your contacts are registered on the server. Try going into the android system settings,
Accounts->TextSecure->Contacts (touch to sync now)

Also, make sure you have friends registered on the TS server? 

Maybe this is a side-effect of cyanogenmod's federating server?

**Comment by grrrrr** [comment]
> Oh. Either there is a bug, or the app doesn't see that your contacts are registered on the server. 
> Try going into the android system settings,
> Accounts->TextSecure->Contacts (touch to sync now)

Was not aware of that setting, sync was off.   Not sure if it was ever on. I assume it must have been given I could see the "TextSecure Users" list before.   Syncing does nothing

> Also, make sure you have friends registered on the TS server?

I do,  despite the "TextSecure Users" not showing up, I can send textsecure messages as well as end secure sessions and restart them

> Maybe this is a side-effect of cyanogenmod's federating server?

I've never used CyanogenMod's implementation.  Everything is with the Whispersystems TextSecure client.
