### ISSUE TITLE
Contact check prooves only Phone Numbers and not E-Mail, etc.

### ISSUE THREAD

**Issue by MrStefanNo1** [WhisperSystems/TextSecure#3797]
Hello everybody,
I really like this app but my contact list has only a very limited number of Textsecure users.
Why isn't it possible to add contacts of which I don't have stored the phone number, just other identifiers like an e-mail-adress or a second phone number for example, like it is possible in Threema?

**Comment by ChaoticMind** [comment]
duplicate-ish of #1085
