### ISSUE TITLE
Not obvious how to send basic SMS when messaging another TextSecure user

### ISSUE THREAD

**Issue by netm** [WhisperSystems/TextSecure#3801]
Love this project.

My gf and I both have TextSecure and can't find a way to send each other a basic SMS, expecting a behaviour like Hangouts where you click and select on if you want to send via SMS or Hangouts

**Comment by McLoo** [comment]
Long tap the send arrow, to choose the message type

**Comment by netm** [comment]
Ah - I see from another issue it is a long press on the send button.

This is a core UI action and needs to be more obvious, hard in the minimal space. Maybe make it part of the drop down menu from the lock icon in the header bar, that being the obvious goto for if you are in secure or not?

**Comment by netm** [comment]
The fact that you can't make the change until you start typing a message is counter intuitive as well. I wonder if the camera icon needs to be relegated to the attachment menu and be replaced by a 'lock' or 'SMS' selector?

**Comment by mawed** [comment]
Maybe there should be an intro feature with first steps with TS, if you just installed it.

With this new user would have some guide to start with TS.
