### ISSUE TITLE
2 Emoji not correctly displayed in compose

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3802]
‼ and ⁉
Should be red and more bold⁉

![screenshot_2015-07-26-11-34-29 01](https://cloud.githubusercontent.com/assets/5326916/8893270/a4f753de-338a-11e5-8f8f-669ad5906256.png)

**Comment by Dyras** [comment]
This was the case even with the Android emojis

**Comment by McLoo** [comment]
for faster lookup:
double exclamation mark "\u203c"
exclamation question mark  "\u2049"
