### ISSUE TITLE
Name display wastes screen space in group conversations

### ISSUE THREAD

**Issue by lhitc** [WhisperSystems/TextSecure#3805]
Before every group message the sender's name is displayed in a separate screen row.
It would save space when the name would be displayed e.g. within the message bubble before or after the time.
Alternatively/additionally, displaying names in group conversations might be a setting (ideally on a per-group basis), since there may be no need for names when avatars are distinctible.

**Comment by moxie0** [comment]
I think we're cool with this for now, or at least we don't need an issue to track it.  Thanks.
