### ISSUE TITLE
TextSecure changes colors of Google contacts

### ISSUE THREAD

**Issue by aibaraiduas** [WhisperSystems/TextSecure#3809]
Contacts without assigned images in the default Google contacts app (also used in the default phone dialer) are assigned a color which normally cannot be changed. Recently however, I've noticed that contacts of the people who are TextSecure registered users *do change*. The color changes are seemingly random (one was grey, then light blue, red, orange, now purple), and I have yet to find a pattern as when they happen (once it occurred right after I switched back to the contact screen from TextSecure; sometimes I only notice when I open the phone dialer). When it happens all of the contacts of TextSecure users change at once.

I'm not exactly sure what causes the problem, but I'm pretty sure it is an issue with TextSecure since all my contacts' colors stay the same *except* for those who also use TextSecure (even one whom I've never actually texted). 

Note that this does not apply to the colors that you can assign people within TextSecure; those remain the same. Changing them within TextSecure is probably not the impetus for a change in contacts either, since one that I've never changed within TextSecure has changed in Google contacts.

I wonder if it has something to do with the new searching contacts screen in TextSecure? I feel it happens more often after I go to that screen, but that's just a guess.

I'm using TextSecure 2.23.2 on a Nexus 5 running Android 5.1.1. 

Here is a log, if that helps: 
https://gist.github.com/e5166ff4b9b0ea4b55e0

**Comment by aibaraiduas** [comment]
Figured out how to reproduce the problem:
In TextSecure, hit the pencil icon to bring up the contacts list.
Pull down on the list to refresh it.
The colors of the contacts of those who use TextSecure will be changed in the default contacts app and those that rely on it like the default dialer. 

What should happen, of course, is that the colors remain the same.

**Comment by moxie0** [comment]
This is an issue with the contacts app.  TS isn't "setting" any kind of color information, we're just adding a raw contact record to the contact, which the contacts app apparently includes as part of its key into a color array.
