### ISSUE TITLE
Landscape orientation broken in ConversationActivity

### ISSUE THREAD

**Issue by exploide** [WhisperSystems/TextSecure#3816]
After opening TextSecure from a new message notification (via notification bar), it is not possible to switch ConversationActivity into landscape mode by rotating the phone. The orientation simply doesn't change.

This is not reproducible by opening TS normally via launcher icon. In this case everything is fine.

I'm using an HTC One S with Cyanogenmod 11 M12. The problem exists approximately since v2.22. I can't remember the exact release, sorry.

Let me know if more information is needed.

**Comment by 2-4601** [comment]
Confirmed on:
- Nexus 4, stock 5.1.1, TS 2.23.3
- Huawei U8800, 4.0.4, TS 2.23.3
Especially if TS is swipe-killed before receiving the notification.

**Comment by exploide** [comment]
Fixed since 2.25.x
