### ISSUE TITLE
Change icon for Take photo

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#3819]
In the attachment dialog  _Take photo_ and _Contact info_ use the same icon.
The camera icon used in quick camera would suit _Take photo_ better.
![reinhold attachment](https://cloud.githubusercontent.com/assets/174176/8915245/8e2eebda-34ac-11e5-8286-7703cee6a5c2.png)

TS 2.23.3

**Comment by RiseT** [comment]
I guess I'm missing something here, but isn't "Take Photo" obsolete with the introduction of Direct Capture/Quick Camera button...?

**Comment by f41c0r** [comment]
I have a quick fix for this but because the icon isn't the same size, it'll probably be better to add a new icon that's the right size
![adb-screenshot-2015-07-27-14-57-38-415589020](https://cloud.githubusercontent.com/assets/4326714/8916262/f515d8be-346f-11e5-842b-5f912d94031a.png)

**Comment by McLoo** [comment]
@RiseT you must have missed https://github.com/WhisperSystems/TextSecure/pull/3664#issue-95050487 (3rd note)

**Comment by agrajaghh** [comment]
did I hear "Icon"? :laughing:

**Comment by 2-4601** [comment]
Suggestion: How about changing _"Take photo"_ to _"Camera"_ while we are at it?
All the other options in the dialog are nouns.
