### ISSUE TITLE
Add option to disable MMS.

### ISSUE THREAD

**Issue by jcsx** [WhisperSystems/TextSecure#3821]
E.g.:

![screenshot](https://cloud.githubusercontent.com/assets/12969275/8920028/3168f816-34b4-11e5-94a7-a061d0bc7f90.png)

**Comment by moxie0** [comment]
thanks but I don't think we want more options

**Comment by apexo** [comment]
The is connected to the Stagefright vulnerability:
http://blog.zimperium.com/experts-found-a-unicorn-in-the-heart-of-android/

Disabling MMS at least allows users to close one attack vector.

**Comment by agrajaghh** [comment]
for reference:
@apexo https://github.com/WhisperSystems/TextSecure/issues/3817#issuecomment-125300940

**Comment by rugk** [comment]
Even if this would not be a Stagefright issue it's still nice to be able to disable MMS retrieval. Possibly you just do not want to get MMS or you are abroad where some network providers even charge for *receiving* MMS.
Disabling MMS retrieval is a basic functionality of almost all SMS apps, so I do not see any reason why Signal has any reason to not have such an option.

**Comment by borsti67** [comment]
Sorry for commenting on a quite old feature request, but after giving Signal a try for some time now, I'm facing exactly the problem @rugk mentioned in his latest posting: MMS are quite expensive, so I NEVER want to use it (neither sending nor receiving). At the moment it seems I cannot use Signal as a replacement for the standard SMS/MMS because of this?
I also noticed that groups which do not only consist of Signal users will be sent as MMS, even if only text is transmitted, is that true? Then I need to carefully check I won't have such...

**Comment by filius-martis** [comment]
Here in Germany most tarrif plans iclude unlimited SMS nowadays, while MMS are still quite expensive. Therefore I also cannot use or recommend Signal as a replacement for the Standard SMS/MMS App, although this widespread option should be an easy fix for lots of users without cluttering the UI or confusing anyone.

Please reconsider...

**Comment by E3V3A** [comment]
I'm quite disturbed that this simple option have been ruled out. MMS is probably the number one remote attack vector currently available for Android, even on Marshmallow. Seeing how many people post issues about using MMS on devices far below that, while being interested in security by using Signal, is mind boggling. I wish @moxie0 et.al. could explain on their FAQ, Readme, Wiki or Blog, whether or not Signal is vulnerable to Stagefright-like attacks, as it seem. 

Preventing MMS use is trivial for an android developer, but for the average/common user, nearly impossible to get it right. (E.g. If you disable MMS in a non-default messaging app, it still gets through.) I really suggest to take @rugk concerns a little more serious.

**Comment by Hate9** [comment]
Why is this still closed, and why has it still not been implemented? It's not even a complicated feature.

**Comment by Rockvole** [comment]
This would be a useful option for me. Where I live it is much cheaper to purchase a data only sim and a separate text / phone sim. I bought a 2 sim phone for this purpose, since the savings are hundreds of dollars per year. 

Unfortunately, this means that mms messages are not supported by my text provider since their data plan is required to download the mms messages. I get mms attempt to retry messages every day for many days. Currently on day 4. I don't know when these messages will stop.

**Comment by AVHoecke** [comment]
My provider charges me for mms. It would be really heady for me.
🙂

**Comment by fionnb** [comment]
@moxie0 please look at the constant requests here and reconsider reopening this. There are quite a few good arguments for having such a switch, be it security, be it financial risk in many countries. Thank you.

**Comment by Rockvole** [comment]
The attempt to retry message I mentioned before ended up continuing for 10 days. My easiest option was to uninstall signal to make it stop.
Now that google is abandoning hangouts I am considering trying signal again with the hope that no-one sends me another mms.

**Comment by fionnb** [comment]
> This all works fine for me. My wife is on the same phone plan as I have (and so we both moved from hangouts to signal at the same time). I get my message notifications fine on my garmin watch from signal and messages. My wife has a fitbit versa 2 and on there it only lets her choose one messaging app to send messages to the watch. So she is stuck with only getting messages on the watch from signal, and has to look at her phone for sms messages.

While working around the issue using other apps may work fine for you, it does not solve the issue itself.

Having separate Messaging Apps for SMS/MMS and Signal is an approach that is too complicated and counter-intuitive for many technically unsavoury, especially elderly people. So when helping this kind of people I only have the choice of not giving them secure messaging or introducing a financial risk for them.
@moxie0 I'd like to add that this way of silenty ignoring/closing issues (for which this one is by far not the only example) is what made me refrain from becoming a sponsor so far.

**Comment by Skgland** [comment]
Looks like some German Providers are going to drop MMS Support [^1]  Telekom on 2022-12-31 and Vodafon on 2023-01-17. 

[^1]: https://www.teltarif.de/mms-abschaltung-telekom-vodafone/news/86775.html

**Comment by E3V3A** [comment]
4.5 years later, still 🙉 🙈 
That's why I stopped using Signal. The potential to properly secure Signal was there, but the will never was.

**Comment by UserX404** [comment]
@E3V3A 
Why you stopped using Signal?
If you have concerns about Signal's sms and mms handling you can disable it.

**Comment by fionnb** [comment]
> @E3V3A Why you stopped using Signal? If you have concerns about Signal's sms and mms handling you can disable it.

Have you read this ticket? It is here solely because you can NOT disable MMS. Dude.

**Comment by Hate9** [comment]
@UserX404 I've also quit using it, partly because of this, and partially because of the 🤮 crypto integration.

**Comment by corydodt** [comment]
When will this ticket get re opened? 

I am now getting constant group MMS spam that I cannot turn in signal. This makes my entire Android device unusable, so I have no choice but to stop using signal.
