### ISSUE TITLE
Emoji drawer and direct capture at the same time 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3824]
Now that the large emoji drawer is fixed
I went for Squirrel style swapping between direct capture and the emoji drawer. Sorry for doing that :flushed: 

![screenshot_2015-07-28-02-36-54](https://cloud.githubusercontent.com/assets/5326916/8921147/390db02a-34d2-11e5-88f8-4d05c6c3f05e.png)

**Comment by McLoo** [comment]
2.24 branch

**Comment by mcginty** [comment]
can't repro on HEAD of 2.24.0, is this still happening for you?

**Comment by McLoo** [comment]
This was at 9eed886
Can try HEAD though

**Comment by McLoo** [comment]
Keyboard also has to pop up.  But no fixed pattern yet -  as usual. 

![screenshot_2015-07-28-07-57-47](https://cloud.githubusercontent.com/assets/5326916/8924580/7e73ecb0-34ff-11e5-89c6-63055d5974a4.png)

**Comment by McLoo** [comment]
try tapping direct while smashing the emoji toggle

**Comment by McLoo** [comment]
Maybe while SwiftKey resizes? 
Other result:

![screenshot_2015-07-28-08-08-32](https://cloud.githubusercontent.com/assets/5326916/8924646/fd342786-34ff-11e5-830f-ce407a98087b.png)

**Comment by mcginty** [comment]
hahaha ok, yeah i can reproduce

**Comment by mcginty** [comment]
fixed in 2.24.0

**Comment by McLoo** [comment]
@mcginty which commit did fix this?

**Comment by mcginty** [comment]
https://github.com/WhisperSystems/TextSecure/commit/e054ffbb3597da2dd4e3d6bcec796e6811e20b47#diff-9c3232b8423379e12396a74540e72debR483

**Comment by McLoo** [comment]
I can haz reopen?
2.24.0 branch at https://github.com/WhisperSystems/TextSecure/commit/99d3a76b56a82099c3d6c1b9d4cf9b44f0332cc0
CM 12.1

reproduce with
- rapid toggling between keyboard an emoji with you left thumb
- while tapping a bit slower (or at the speed) the direct capture button with your right thumb

![device-2015-07-30-091712](https://cloud.githubusercontent.com/assets/5326916/8977727/ceb52516-369b-11e5-9f4c-1cf873abce4c.png)

**Comment by jeremymasters** [comment]
I received a new SwiftKey update to 5.3.4.58. Does that change this behavior/behaviour at all?

**Comment by McLoo** [comment]
@jeremymasters no change with SwiftKey 5.3.4.67 but with d6f0a10 this gets fixed
