### ISSUE TITLE
Crash on tapping "blocked contacts" in preferences

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3825]
Also sent crash report 
Reproducible. 
https://gist.github.com/6fd49b96bf5375d5d1d7

**Comment by mcginty** [comment]
i'm not crashing, can you specify the exact steps? I did:

1. open conversation, click name, block contact
2. leave conversation, settings -> privacy -> blocked contacts -> tap on blocked contact
3. ??? works for me.

**Comment by McLoo** [comment]
oh my! Never going to learn to be precise I guess... sry!

Go to TS preference - privacy 
there: tap block contacts
that's where it crashes for me

**Comment by McLoo** [comment]
There are blocked contacts on the crashing device, just added one. Now I see the activity poping up before the crash occurs. New log: (with update)

**Comment by mcginty** [comment]
Thanks @McLoo, looks like when a recipient is modified there are UI operations happening off the UI thread
