### ISSUE TITLE
Multi-device strings inconsistent, confusing

### ISSUE THREAD

**Issue by unrulygnu** [WhisperSystems/TextSecure#3830]
The act of adding a device uses at least 5 verbs:
* Create
* Link
* Add
* Register
* Pair

The act of removing a device uses only 1 verb, but it is unrelated to any of the positive actions:
* Disconnect

This inconsistency is both confusing to end users and troublesome for translators.  It would be awesome if we had a single positive action verb, with a related single negative verb.  For example:
* Add / Remove
* Register / Unregister
* Link / Unlink
* Authorize / Deauthorize (used in Google Play Music)

The related string resources follow:

        
        <string name="DeviceListActivity_disconnect_s">Disconnect \'%s\'?</string>
        <string name="DeviceListActivity_by_disconnecting_this_device_it_will_no_longer_be_able_to_send_or_receive">By disconnecting this device, it will no longer be able to send or receive messages.</string>
        <string name="DeviceListActivity_disconnecting_device">Disconnecting device...</string>
        <string name="DeviceListActivity_disconnecting_device_no_ellipse">Disconnecting device</string>
        
        
        <string name="DeviceListItem_created_s">Created %s</string>
        
        
        <string name="DeviceProvisioningActivity_link_this_device">Link this device?</string>
        <string name="DeviceProvisioningActivity_title">Link this device?</string>
        <string name="DeviceProvisioningActivity_content_progress_title">Adding device</string>
        <string name="DeviceProvisioningActivity_content_progress_content">Adding new device...</string>
        <string name="DeviceProvisioningActivity_content_progress_success">Device added!</string>
        <string name="DeviceProvisioningActivity_sorry_you_have_too_many_devices_registered_already">Sorry, you have too many devices registered already, try removing some...</string>
    
        
        <string name="device_list_fragment__no_devices_paired">No devices paired...</string>
        
        
        <string name="AndroidManifest_manage_paired_devices">Manage paired devices</string>

I will submit a PR with Register / Unregister as a suggestion, pending an official decision on what words to use.

**Comment by 2-4601** [comment]
- **Add / Remove:** perhaps too general
- **Register / Unregister:** might be confused with the initial registration and the setting to unregister/re-register push
- **Pair / Unpair:** gives the impression of only two devices, or that this action is done two devices at a time (I guess this term is mostly familiar from Bluetooth?)
- **Link / Unlink:** this sounds like the plural version of pair/unpair and I think this would be a good candidate
- **Authorize / Deauthorize:** sounds bit too technical, crypto-oriented and power usery to me 😰

I'd vote for link / unlink.

**Comment by unrulygnu** [comment]
New PR uses "Link / Unlink".  See https://github.com/WhisperSystems/TextSecure/pull/3831#issuecomment-126124579
