### ISSUE TITLE
Detailed status information missing

### ISSUE THREAD

**Issue by sjaeckel** [WhisperSystems/TextSecure#3835]
In the light of #3834 it would be great to have some status signalling to the users of the app.

1. I think of something like https://status.github.com/ for the server infrastructure

2. more detailed output for the user (yes I'm aware that most users don't care, but some would know why message sending fails, so hide it by default and add a button 'detailed error messages' or sth)

Thanks.

BTW you rule ;-)

**Comment by moxie0** [comment]
thanks but i don't think we're going to do this

**Comment by MartinX3** [comment]
Why not?
That would be very informative.
Today the world wide Signal Service was down and people spammed github and twitter about "why is it down" or "it is down for me".
That would reduce the spam.
