### ISSUE TITLE
Textsecure ignores sound settings

### ISSUE THREAD

**Issue by xshadow** [WhisperSystems/TextSecure#3836]
I'm running Textsecure (2.23.2) on a Samsung Galaxy S4 Mini ( GT-I9195 ) with CM  11 (Stable: cm-11-20150626-SNAPSHOT-XNG3CAO1L8-serranoltexx).  

Unfortunately Textsecure ignores the soundsettings of my phone. It rings the bell either if its set to vibration or if the sound is disabled. No difference between push message or sms.

Device info:  Samsung Galaxy S4 Min, CM 11 (latest), TextSecure 2.23.2
App state: Push registered, incoming SMS enabled, outgoing SMS fully enabled

Thanks for your great tool.

**Comment by xshadow** [comment]
Follow up: 

It only happens in CM standard profile when I turn down the volume to silent / vibration. 

If I use the CM silent profile - Textsecure stays silent too.

**Comment by Dyras** [comment]
Are you sure this isn't a problem with CM?

**Comment by xshadow** [comment]
Seems to be fixed in CM12.
