### ISSUE TITLE
Icon always shows "4" unread when using Aviate launcher

### ISSUE THREAD

**Issue by ascorbic** [WhisperSystems/TextSecure#3842]
This seems similar to #2358, but is still present in the latest version. I use Aviate launcher (3.0.1.3). After installing TextSecure I imported my device SMS database. Initially the unread badge is not shown, but after a few minutes the "4" appears. I marked all as read using "Mark all read" in the context menu (though none were actually unread). This had no effect. Uninstalling and reinstalling the app made the badge go away, but it returned as soon as I imported SMS.

Log, including my system and version details: https://gist.github.com/anonymous/4f9112b7c7a3ea8e5b49

**Comment by McLoo** [comment]
@ascorbic didn't check import code, but are there any unread or failed SMS in your stock SMS app?

**Comment by ascorbic** [comment]
Ah, good point. I uninstalled it and checked Hangouts and yes, there are some unread messages in there, which weren't showing as unread in TS. After deleting them, reinstalling TS and importing again, the badge has gone away. Not 100% sure it's been fixed, as previously it took a few minutes to appear, but looking good so far.

**Comment by jeremymasters** [comment]
Sounds like this bug 🐛 might be worthy of a title change to something like "Unread hangouts messages not showing up as 'unread'  on import into TS"?

**Comment by McLoo** [comment]
@ascorbic if you unread count behaves well now, you're welcome to close the issue :)

**Comment by McLoo** [comment]
@ascorbic finally fixed for you?

**Comment by ascorbic** [comment]
@McLoo I no longer have the unread count as I worked-around it by deleting the messages before importing them, so I don't know if the underlying issue has been fixed. Shall I close this anyway?
