### ISSUE TITLE
2.24.0 fails to build

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#3847]
Checksum fails for textsecure-android 1.6.2. This version is not in Github yet.

**Comment by moxie0** [comment]
might take a second for your mirror of maven central to get it

**Comment by johanw666** [comment]
A, I get it now, tried to be too quick. Sorry for that. ;-)

**Comment by johanw666** [comment]
However, I still get a checksum failed for textsecure-java and textsecure-android. When I remove them from the dependencyVerification block in build.gradle the build works.

**Comment by Wikinaut** [comment]
@johanw666 This problem appears to be solved as the current version 2.24.1 git 27aabbc4d9f188acd1674c78577443205b07b258 (Mon Aug 3 14:13:21 2015 -0700) can be built and works.
