### ISSUE TITLE
Gradle error: checksum failed for textsecure-android 1.6.2

### ISSUE THREAD

**Issue by unrulygnu** [WhisperSystems/TextSecure#3853]
`textsecure-android` was upgraded from 1.6.1 to 1.6.2 in 964171b.  This is causing a gradle sync failure (Android Studio 1.3, Gradle 2.5):

    Error:Checksum failed for org.whispersystems:textsecure-android:46fbc2133cfe25c35d6006f90babcfc7f85ef34ffd365133af3cdaf692c7785c

Manual `sha256sum` checks match `build.gradle` for 1.6.1, but don't match for 1.6.2.  `Invalidate Caches / Restart` still results in the error.

**build.gradle** (964171b)

                'org.whispersystems:textsecure-android:46fbc2133cfe25c35d6006f90babcfc7f85ef34ffd365133af3cdaf692c7785c',
                
                'org.whispersystems:textsecure-java:7be6c8f6b12a5d1a98c3dc02b8f9d033271fb6fb5daad91ddf19c7b5798cde94',

**Actual checksums**

    $ sha256sum ~/.gradle/caches/modules-2/files-2.1/org.whispersystems/textsecure-android/1.6.2/a14517dee2cee09e9d1cd1c0fad174fccee4eff3/textsecure-android-1.6.2.aar 
    6fc3a127b4ab63533e571066a8c6686e82d071d804f4563eee66a3773dd094e0
    
    
    $ sha256sum ~/.gradle/caches/modules-2/files-2.1/org.whispersystems/textsecure-java/1.6.2/f011b0c199e9e718c7a76a9627665b083007f179/textsecure-java-1.6.2.jar 
    9167ae6cbc34b62b5d51b2dd687306ca94eab6cf5fa7cf426f40ec32d3d37cf8

**Comment by johanw666** [comment]
When I remove these 2 from the dependencyVerification block in build.gradle I get a working 2.24.0 apk.

**Comment by bkchr** [comment]
I got the same problem.

**Comment by agrajaghh** [comment]
https://github.com/WhisperSystems/gradle-witness/pull/7 would make it easier to fix the checksums :stuck_out_tongue_winking_eye:
