### ISSUE TITLE
Not securing my texts

### ISSUE THREAD

**Issue by MrRecklessness** [WhisperSystems/TextSecure#3854]
On the type in bar it says "Send unsecured SMS" it happens when I send a text to someone with or without Textsecure.  How do I make it secure.

**Comment by johanw666** [comment]
Both you and your contact need to install software to decrypt encrypted messages. So you both need to install TextSecure to exchange encrypted messages over the internet. If you want encrypted sms, look at SMSSecure.

**Comment by MrRecklessness** [comment]
Is there a way to switch it back to MMS mode i can't seem to find a way to change it back.

**Comment by ComeGitSome** [comment]
You need to write something, then press and hold the send button #3689

**Comment by moxie0** [comment]
@MrRecklessness This isn't a support forum, the best place for support is http://support.whispersystems.org or emailing support@whispersystems.org
