### ISSUE TITLE
General rules for translations?

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#3863]
I'm on the translate team for TextSecure and SMSSecure for the Dutch language, and I noticed in both projects some inconsistencies. In Dutch, you have 2 forms for the English "you" (ignoring the "thou" form here): the informal "jij", and the more formal "u". I noticed both forms are used in translations, probably depending on the personal preference of the translator of the specific string. In French you have "tu" and "vous", in German "du" and "sie", but I didn't check the French and German translations to see if the forms are mixed there too. I don't know any other languages well enough to say if it can be an issue there.

In current Dutch both forms are socially acceptable (although some mostly elder people frown on the use of the informal form).

I would suggest the app choose one of the forms to be more consistent. Having both forms mixed makes a sometimes strange impression. I have no strong personal preference for either form.

What is the opinion of the developers?

**Comment by 5boro** [comment]
I'm very active in the French translation team and we almost exclusively use 'Vous', most other messaging apps do as well...

**Comment by McLoo** [comment]
German translation tried to avoid the yous. 
If not possible we go the formal way 'Sie'

**Comment by RiseT** [comment]
You and your translation team just have to choose the one you feel is most appropriate and then stick with it (personally I would add "stand by it" as I am no fan of this "avoiding" thing).

And of course you should correct any existing inconsistencies.
