### ISSUE TITLE
Single thread notification overflow not ellipsisified 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#3867]
If you expand the notification drawer, there are 9 lines (in my case) of message text shown.
There is no indication for how many messages were received or if there is more text.

If you received more than 9 lines (wrapped single message, multi line single message, multiple messages) then there should be ellipsis in the ninth line, like it is done for the multiple thread notification.

And as of the current sort order this gets even more confusing. You see the most recent message in the collapsed notification and it is not shown (or indicated to be anywhere) when you expand the notification (when there 9+ lines of notification)

Can screenshoot if my description is too confuse :wink: 

Edit: ... and totally forgot to demand a message count indicator

**Comment by moxie0** [comment]
We don't really have any control over how notifications are rendered.  We set the text, hand it to Android, and it does the rest.  We also set a message count on each notification, whether it's rendered by Android is likely device/version specific.
