### ISSUE TITLE
Keyboard not showing up in one specific group chat

### ISSUE THREAD

**Issue by markusr815** [WhisperSystems/TextSecure#3872]
This is TextSecure 2.23.3 running on and LG L40 with the default LG Android 4.4.2 (Build number KOT49I.A1399985852, Software version V10d-EUR-XX).

In one of my group chats the keyboard is not showing when I try to focus the text input. It works as expected in "singe user chats" and the only other group chat I'm part of. The broken group chat looks like this:

![1](https://cloud.githubusercontent.com/assets/11480107/9034869/48ae48a4-39d3-11e5-9590-b496c7bc9632.png)

When I hit the text field labelled "Send TextSecure message" nothing happens.

I suspect that the group chat is in some strange state as the group is named "Unnamed group" and I can't see any other group members from the menu:

![2](https://cloud.githubusercontent.com/assets/11480107/9034907/83c02d0e-39d3-11e5-8e1c-e13f964307b9.png)

Navigating to "Conversation settings" I get the following screen:

![3](https://cloud.githubusercontent.com/assets/11480107/9034925/aaa23f3e-39d3-11e5-922d-6b965224d9f5.png)

Also, I can add for example a picture but can't hit the send button, i.e., the send button doesn't do anything when I hit it.

![4](https://cloud.githubusercontent.com/assets/11480107/9035088/0ac29fb6-39d5-11e5-9cf6-6d033c5d2466.png)

As far as I recall I have reinstalled my phone (and thereby TextSecure) since the group chat was created.

**Comment by agrajaghh** [comment]
duplicate of #2581

thats unfortunately currently the normal behaviour if you reinstall TS. Someone has to select "Update group" (no changes needed) to make it work for you again.

**Comment by markusr815** [comment]
Oh, thanks. I didn't find that bug report previously.
