### ISSUE TITLE
Orange contact color in dark theme burns my retinas

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#3879]
The orange color in the dark theme in 2.24.1 is really bright.  I know @moxie0 had toned down some colors.  Maybe this one got missed.

**Comment by McLoo** [comment]
dark theme fan boy here says: that orange is totally fine for me

**Comment by jeremymasters** [comment]
Using Samsung Galaxy S4 bone stock 5.0.1 if that matters at all.

**Comment by jeremymasters** [comment]
Just adding the screen cap for the record.  It's not that I really care but that it appears to be much brighter than the other colors in dark theme.
![0](https://cloud.githubusercontent.com/assets/4967949/9074645/d5483fe0-3ac8-11e5-923f-e70afeae1e3f.jpg)
