### ISSUE TITLE
Linking device with no TS groups crashes

### ISSUE THREAD

**Issue by berdario** [WhisperSystems/TextSecure#3882]
This is the stacktrace:

    W/JobConsumer(10381): java.lang.IllegalArgumentException: No length specified!
    W/JobConsumer(10381): 	at org.whispersystems.textsecure.api.messages.TextSecureAttachment$Builder.build(TextSecureAttachment.java:80)
    W/JobConsumer(10381): 	at org.thoughtcrime.securesms.jobs.MultiDeviceGroupUpdateJob.sendUpdate(MultiDeviceGroupUpdateJob.java:101)
    W/JobConsumer(10381): 	at org.thoughtcrime.securesms.jobs.MultiDeviceGroupUpdateJob.onRun(MultiDeviceGroupUpdateJob.java:68)
    W/JobConsumer(10381): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
    W/JobConsumer(10381): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
    W/JobConsumer(10381): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
    E/AndroidRuntime(10381): FATAL EXCEPTION: JobConsumer-3
    E/AndroidRuntime(10381): Process: org.thoughtcrime.securesms, PID: 10381
    E/AndroidRuntime(10381): java.lang.IllegalArgumentException: No length specified!
    E/AndroidRuntime(10381): 	at org.whispersystems.textsecure.api.messages.TextSecureAttachment$Builder.build(TextSecureAttachment.java:80)
    E/AndroidRuntime(10381): 	at org.thoughtcrime.securesms.jobs.MultiDeviceGroupUpdateJob.sendUpdate(MultiDeviceGroupUpdateJob.java:101)
    E/AndroidRuntime(10381): 	at org.thoughtcrime.securesms.jobs.MultiDeviceGroupUpdateJob.onRun(MultiDeviceGroupUpdateJob.java:68)
    E/AndroidRuntime(10381): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
    E/AndroidRuntime(10381): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
    E/AndroidRuntime(10381): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)

Basically, I wanted to check the current status of the [TextSecure-Browser](https://github.com/WhisperSystems/TextSecure-Browser) project.

Since I'm lazy, rather than rebuilding the android application to use the staging server and create another account, I wanted to try to use it to contact my mother and I modified the javascript sources to not use the staging servers (I just removed the `-staging` string from the urls, as a wild guess)

I thought:

> what's the worse that could happen? the messages might just fail to be delivered

well, apparently I was wrong... maybe because the browser plugin expects a newer version of the app, but now I always get the above exception.

The problem still happens even after removing/disabling the extension on my browser. The exception doesn't happen if I put the phone in airplane mode, but otherwise it keeps crashing (and showing the related popup)

I tried to find a way to disassociate my browser from the phone, but apparently there's no such option. Rebooting the phone didn't help.

I frankly could do without TextSecure for a few days... I'd switch back to the normal sms app until this issue would be fixed.

But afaik, the only way I could do that, is by uninstalling textsecure/removing the account. Unfortunately this would then create a new key and I'd need to notify my new contacts of the changed fingerprint.

I'd like if there was a day to do one of the following things:

- Tell textsecure to stop connecting altogether
- Tell textsecure to disable automatic restart
- Export my textsecure's private key (ok, this is less than ideal, but I'm already suffering from a self-inflicted DOS :P )

Also, I understand that an Android application's lifecycle is not as simple as a normal Java app, so it might not be that easy. But is there no way to have a top-level catch-all exception that recognizes such an issue, increments a counter to detect if the failure was a one-off or is cronical, and does something sane (temporarily disabling itself... don't let the exception bubble up to the system, etc.)?

Thank you

**Comment by moxie0** [comment]
Apparently this is what happens when you link a device that has no TS groups.

@berdario If you fuck with your phone, fucked up shit is going to happen.  Sorry that this happened to you, but I don't know how many more ways we could have warned you not to do exactly what you just did.  You're probably going to have to reinstall; unfortunately we're not able to support users of unreleased software.  I'll see if I can get a fix in the next release, but no promises.

**Comment by berdario** [comment]
Fair enough, Thank you anyhow.

I now uninstalled/reinstalled TS, let my contacts know about it, and all should be good

btw, I knew that I was venturing into a potentially unsupported situation, but the only warning I got was in the TextSecure-Browser readme:

> This is unfinished, unreleased software.
> Please refrain from installing until our first release. 

Was there supposed to be a warning shown by my app as well when pairing it up?

**Comment by moxie0** [comment]
lol, the sentence that says "don't use this" surrounded by yellow exclamation marks wasn't enough?

**Comment by berdario** [comment]
if you're being serious: No, if one truly wants to prevent users harming themselves, they need to repeat the same message in different places, and explain the consequences... otherwise people might read the warning and deem it unwarranted. warning-symbol-emoji looks good and attract attention, but they don't really add information to the message. Then again, you might not really care about it, since I expect that only a few dozen of people would want to try to run unfinished code.
if you're being flippant: well, people are interested in code because it solves some practical problem. That's the reason they'll try to use it in the first place... some of them will misuse it. But it shouldn't surprise you that much either (murphy's law and all that)

**Comment by moxie0** [comment]
I'm not surprised you ignored the warnings and fucked up your phone, I'm surprised you're seriously complaining about not being warned.
