### ISSUE TITLE
Improperly scaled (animated) GIFs

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#3886]
A rather small (animated) GIF is display strangely scaled:
1. The picture appears far to big.
2. It is zoomed in and cut of.
My device is a Motorola Moto G 1st gen LTE. It has a rather high resolution, about 300ppi. TextSecure is at version 2.24.1. Please see the images below. 
Original: ![image](https://dl.dropboxusercontent.com/u/106181/_smooch__remake_by_darkmoon3636.gif)
Screenshot: ![image](https://dl.dropboxusercontent.com/u/106181/_20150805_084634.JPG)

**Comment by mcginty** [comment]
yeah, it will always scale to fit and center crop regardless of the input size/aspect ratio

**Comment by merkste** [comment]
How about composing small images with a suitable (transparent) border to prevent scaling?

**Comment by mcginty** [comment]
@merkste when I did that there were bugs being opened that thought it was a bug that images were appearing small in the message (especially on devices with high dpis), so it's unfortunately not going to be as easy as simply refusing to upscale imo.
