### ISSUE TITLE
Small text size for contact name when coming from a notification in landscape mode

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#3888]
When I receive a notification of a new message in landscape mode and tap on it, it takes me into the thread I have with that contact but the contact's name is in a smaller font than normal. If I use the top left arrow button to go to the list of threads, then go back into that contact it is back to normal. This does not occur if I receive the notification and tap it in portrait mode.

**Comment by 2-4601** [comment]
Related or duplicate of #2930

**Comment by jeremymasters** [comment]
Closing this like a boss.
