### ISSUE TITLE
Crash on searching for contact 

### ISSUE THREAD

**Issue by jandechent** [WhisperSystems/TextSecure#3899]
Reproducible:
Open ts
Click on search
Enter "e"
Crash.

There is no contact starting with e in my contacts yet.

https://gist.github.com/5e33b2fb154c34c2b600

**Comment by moxie0** [comment]
Are you running a weird ROM?  That crash is actually happening inside the Android system contacts provider, not on the TS side.

**Comment by jandechent** [comment]
Okay - sorry. I'm on rooted android m, so crashes elsewhere, so I thought its ts. My bad - awesome work from your side :)
