### ISSUE TITLE
Can't send to another TextSecure user after changing handsets

### ISSUE THREAD

**Issue by andy47** [WhisperSystems/TextSecure#3910]
I had to revert to using my backup handset and now I don't seem to be able to send sms messages to a friend who is also running TextSecure. I checked and normal SMS go through OK. Is this because I changed handsets and then changed back to my original one?

When I try and send a message using TextSecure it fails to send. I've uploaded my debug log;

https://gist.github.com/anonymous/50d59c24fa2fcf21c814

**Comment by Dyras** [comment]
Have you tried deactivating TextSecure messages, then tried activating it again?

**Comment by moxie0** [comment]
There's nothing in this log, you have to capture it immediately after whatever problem you experience.

You can't have two devices registered for the same number at the same time.  You have to re-register your first device.
