### ISSUE TITLE
2.25 notification problem

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#3912]
I am not sure if this is the way to reproduce it, but here is what I did

1. Change private notifications settings so that TS only displays the name
2. I chatted for a while, etc etc, everything works fine (by the way I think that "Contents hidden" should be in italics in the notification area)
3. I switched back to the standard setting so that TS displays name and message
4. Now TS doesn't ring anymore when I receive messages, unless it's a message from a contact that has a custom ringtone

**Comment by moxie0** [comment]
can't do anything without a debug log

**Comment by oaim** [comment]
You could try to reproduce it...
do you need a debug log captured after what? After receiving a message that didn't make TS ring?

**Comment by oaim** [comment]
https://gist.github.com/anonymous/d7c98630d6e06d4a2465
