### ISSUE TITLE
Local Attack on Secure Screen in Android

### ISSUE THREAD

**Issue by Dedal0** [WhisperSystems/TextSecure#3916]
Local Attack:
If an attacker gets my phone when it's unlocked and my TextSecure is also unlocked, the attacker is able to go to preferences, disable Secure Screen and take screenshots out of my phone from my Textsecure conversations.
 
Fix:
Everytime I want to change preferences, I should get my password asked.

**Comment by agrajaghh** [comment]
I don't see a security issue here. If the attacked has your unlocked phone with TS unlocked you lost. He can read the messages, write them down, make photos/videos, etc. Where is the difference if he is able to take screenshots?

**Comment by Dedal0** [comment]
It's easier to take screenshots and sending them from the phone than running to get a camera trying not to get the device locked...

**Comment by moxie0** [comment]
The only reason the "screen security" feature is there is to prevent screenshot caching by the OS that happens for the "recent tasks" switcher.  It's not meant for anything else.
