### ISSUE TITLE
Local Attack on changing password

### ISSUE THREAD

**Issue by Dedal0** [WhisperSystems/TextSecure#3917]
Local Attack:
If an attacker gets my phone when it's unlocked and my TextSecure is also unlocked, the attacker is able to go to preferences and disable the "Enable Passphrase" feature.

Fix: 
Everytime I want to change preferences, I should get my password asked.

Kind of same "bug" as https://github.com/WhisperSystems/TextSecure/issues/3916

**Comment by agrajaghh** [comment]
I don't think thats an issue. Changing the password to something you don't know is the same as deleting the data. And deleting data/uninstalling TextSecure will always be possible to someone with access to your unlocked phone...

**Comment by Dedal0** [comment]
Check 3916, both combined is the problem.
