### ISSUE TITLE
bring back contact list refresh

### ISSUE THREAD

**Issue by karlhedderich** [WhisperSystems/TextSecure#3922]
When I get a friend to sign up on textsecure they don't automatically show up in my textsecure contact list.  There used to be an option to refresh and update the contact list.  Any chance of bringing that feature back?

**Comment by moxie0** [comment]
Pull to refresh.

**Comment by karlhedderich** [comment]
thanks

**Comment by moxie0** [comment]
fyi support at whispersystems.org is the best place for support questions in the future
