### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by eosrei** [WhisperSystems/TextSecure#3924]
Could this project have a permanent changelog? The only historical list I can find is the commit log 

There used to be a changelog at: https://github.com/WhisperSystems/TextSecure/wiki/History-of-changes according to this [Support question](http://support.whispersystems.org/customer/portal/questions/6120714-changelog) but it no longer exists. The Play Store lists "What's New", but it only contains the last few versions of data. Actually, just storing the entire list of previous "What's New" entries at: https://github.com/WhisperSystems/TextSecure/wiki/changelog would cover it.

Thanks!

**Comment by moxie0** [comment]
Thanks but we're not going to do this.  Also, this isn't an appropriate place for Q&A, discussions, or support.  Please write to support at whispersystems.org or see the support center for that stuff.
