### ISSUE TITLE
Blackphone / no play store

### ISSUE THREAD

**Issue by mpiscaer** [WhisperSystems/TextSecure#3927]
Hi,

I would like to install TextSecure, but I have an Blackphone, witch means I don't have play store.

How can I install the app?

Kinds regards,

Michiel Piscaer

**Comment by Dyras** [comment]
I think you would be better off asking this at http://support.whispersystems.org/

**Comment by moxie0** [comment]
Correct, this is an issue tracker not a discussion forum.
