### ISSUE TITLE
After leaving a group message, the "type here" field still appears, which is confusing.

### ISSUE THREAD

**Issue by wslack** [WhisperSystems/TextSecure#3929]
Noticed this when https://github.com/WhisperSystems/TextSecure/issues/3928 popped up - it looked like I could tap and type out a message, but the field wasn't responsive. (it "felt" as a user like I was tapping wrong) However, the emoji button was working - can you send emojis after leaving a group?

**Comment by 2-4601** [comment]
Duplicate of #3334

**Comment by wslack** [comment]
+1 feel free to close.
