### ISSUE TITLE
how do i find my text?

### ISSUE THREAD

**Issue by alom923** [WhisperSystems/TextSecure#3935]
i downloaded this app and then after messaging people with it i took it off my phone but the messages are now gone. how do i get those messages back? even if i reinstall the app the messages dont show up.

**Comment by moxie0** [comment]
Hey @alom923 the best place for support is the support center (support@whispersystems.org or http://support.whispersystems.org), this is an issue tracker.

When you removed the app you removed the messages. The only copy was on your device.

**Comment by alom923** [comment]
Ok sorry I'm not techy. But the "saved message" is in code. And the app
made it so that the messages could only go through it
