### ISSUE TITLE
Stuck on 2.22.2

### ISSUE THREAD

**Issue by funkydude** [WhisperSystems/TextSecure#3938]
I appear to be stuck on 2.22.2 of TextSecure. When I visit the Google Play page, it tells me "Your device isn't compatible with this version".

I can use the latest WhatsApp just fine, and this is the first time I've ever encountered this issue with an app so I don't think this is a permissions problem. Any ideas why the latest version would be incompatible? Do we need Android > 4.1.2 to get the latest versions now?

**Comment by moxie0** [comment]
You'd have to tell us what kind of device you have.

**Comment by funkydude** [comment]
Hmm if that matters then I assume there's some kind of blacklist/whitelist of devices?

I'm actually trialling a Jolla phone which runs sailfish OS and has android app compatibility. I've yet to have any issue with the vast array of apps I've tested so far.

Anyway I've tried to dig up what it reports itself as in the hope this can be resolved:
>ro.product.model=Jolla
>ro.product.brand=Jolla
>ro.product.name=alien_jolla_bionic
>ro.product.device=alien_jolla_bionic

**Comment by funkydude** [comment]
According to an Android app:
>Model: Jolla (alien_jolla_bionic)
>Manufacturer: unknown
>Brand: Jolla

**Comment by moxie0** [comment]
We don't have any phones blacklisted, but I have no idea why you're not seeing the update.  We only support Android.

**Comment by funkydude** [comment]
If you have no phones blacklisted, why even bother asking my device? Cmon Moxie, you're a smart guy, I'm sure you can spare a few minutes of work to look into something that could also potentially affect Android users. (Since it's not a blacklist issue, it's obviously a code issue)

Like previously stated, all other apps work fine, and this app has worked fine for months on end, until now. It would be nice if you could actually look into this, rather than me dragging all my friends (that were hesitant to even try TS) back to WhatsApp.

**Comment by moxie0** [comment]
Why ask?  Because "it doesn't work" isn't enough for me to go on.  It turns out you're not even running Android.  Unfortunately I *can't* spare a few minutes on an unsupported platform, you can see the number of open issues here which affect actual android users.  We don't even support weird modifications of Android itself.  If people want to do something extremely non-standard with their phones, that's on them to diagnose and maintain, we have more than enough work to do supporting the stock experience.

**Comment by funkydude** [comment]
AFAIK the reason you closed this was because I mentioned a non-Android device, one that works perfectly fine with other Android apps, including WhatsApp, which to my knowledge, requires MORE permissions than TS does.

My point is that I believe you were rash with closing this when it may very well affect others. https://github.com/WhisperSystems/TextSecure/issues/3944 is a ticket that happens to also be on 2.22.2.

IMO this should have been left open for possible investigation.

**Comment by funkydude** [comment]
It seems as of the latest release, 2.26.5, I am now able to update to the latest release, and I'm no longer stuck on 2.22.2. Hoorah!

May I ask what was changed to resolve this issue? Was it the removal of a required permission?
