### ISSUE TITLE
Feature Request: Add option to refresh GCM-registration

### ISSUE THREAD

**Issue by mawed** [WhisperSystems/TextSecure#3939]
I did not find an issue for this or close to this.

For some of the GCM problems it could be helpful to register the phone new at GCM. 
When messages arrive only after openting TS, doing this (via Threema) helps sometime.

Maybe it would be helpful to implement it directly in TS (maybe in the advanced settings?).

Regards

**Comment by brumsoel** [comment]
It's already there (kind of): Simply disable and re-enable "TextSecure messages" in the advanced settings.
