### ISSUE TITLE
Can't send messages (Sending fails)

### ISSUE THREAD

**Issue by duelle** [WhisperSystems/TextSecure#3940]
When trying to send a message, I get a notification that the message could not be sent.
Message status: "Not delivered"
"Samsung Galaxy S4 mini" with Android 4.4.2
This problem persists for at least 20 minutes now.
Rebooting the phone did not help in any way.
TextSecure version: 2.25.3

Debug log:
https://gist.github.com/anonymous/bad722a16067d8fe58ab

**Comment by drt24** [comment]
Not just you. I am experiencing the same problem on a Nexus 4 with Android 5.1.1. Looks like it might be a problem with the configuration of TextSecure's servers TLS.

**Comment by s-k-y** [comment]
ok then I'm at least not alone with this problem.

**Comment by Dyras** [comment]
Servers are probably down. Let's all stay calm and try not to spam this thread.

https://gist.github.com/anonymous/2546708352da8847fd45

**Comment by janvlug** [comment]
I'm also experiencing this problem. Debug log: https://gist.github.com/6ba1cf4296a7d0133714

**Comment by janvlug** [comment]
See also: http://support.whispersystems.org/customer/portal/questions/13199409-textsecure-servers-down-

**Comment by Mihahn** [comment]
For me it's working fine again. Looks like the server is up again :+1:

**Comment by carolyna** [comment]
Down for me too, but now it's sending the messages. One set to another Android seems to have been received (double checks) however test messages to my iPhone show sent but not received. The iPhone did show a notification, but Signal is not loading the new messages.

**Comment by Calrama** [comment]
I have the same problem, I can no longer send any messages at all. Neither via WLAN nor mobile data, regardless of the recipients.
Android: 5.1.1 (Cyanogenmod 12.1)
TextSecure: 2.25.3
One thing to note: There was a recent automatic update to TextSecure via the PlayStore, it did not happen in the previous version and it happened with the first message I wanted to send on this new version.

**Comment by gartenriese2** [comment]
Same problem here, me and my friends can't send any messages. Today is not the first time it happened, I think about two weeks ago there was a downtime of a couple of hours, too. Any explanations from the TextSecure team why the servers are down sometime?

**Comment by RiseT** [comment]
@Calrama I've successfully sent & received a couple of messages with 2.25.3, so I don't think that's the culprit.

**Comment by bossfong** [comment]
Having the same problem today. I don't want to be that guy, but these little things is why I can't yet recommend TextSecure/Signal to my friends :/ 
I hope this issue gets resolved soon, I'm loving TextSecure.
Is there something a cs student with very little to no java experience can help with?

**Comment by oaim** [comment]
Same here. This has been happening way too often lately and we never got answers (nor did it get fixed). I think it may be time to uninstall textsecure

**Comment by RiseT** [comment]
Keep calm - WhatsApp had various outages over the years.

**Comment by oaim** [comment]
Not one every other week.. I love textsecure, but I can't recommend it to people given its many bugs, performance issues and server problems. Plus no one is currently working on the ios bug fixes, etc... I mean, too many cons compared to the few pros that come with using it

**Comment by RiseT** [comment]
I'm using TS for a pretty long time and this is my very first outage. I might have been lucky, though, i. e. I guess I wasn't trying to send a message when one of the prior outages hit.

**Comment by oaim** [comment]
> I guess I wasn't trying to send a message when one of the prior outages hit.


Exactly. Search among old closed issues, you'll find many similar to this ones that were opened just a month ago or so

**Comment by 5boro** [comment]
Did anybody email moxie ?
There's [a support thread](http://support.whispersystems.org/customer/portal/questions/13199409-textsecure-servers-down-), but no answers...
I tried with tweeter but without success.
Maybe they're not even aware of the outage.

**Comment by RiseT** [comment]
Speaking of outages, Surespot had a couple of those some time ago. Some time after that, their (warrant) canary tipped over...

**Comment by RiseT** [comment]
@5boro @mcginty mentioned in the mailing list that some of them are over near Berlin at CCC's summer camp.

**Comment by oaim** [comment]
They probably aren't aware, it's like 5:40am in san Francisco. 

As for the outages being related to something worse... yeah, I thought of that too

**Comment by mathieueh** [comment]
Can't send either

**Comment by turtlekiosk** [comment]
Should be fixed now.

**Comment by johanw666** [comment]
This is where encrypted sms might have been a nice backup. Unfortunately one has to load another app for that now.

**Comment by carolyna** [comment]
Exactly... or maybe even starting to encourage people to run servers in a nice community-supported decentralized fashion...

**Comment by duelle** [comment]
From my end sending messages works fine again. I also get message receipts. Closing the ticket.

**Comment by Calrama** [comment]
@duelle Works for me, thank you.

@oaim Considering TextSecure/Signal and surespot are the only available (mobile) cross-platform crypto-messengers they can - although I obviously do not like it - afford to have some outages. I have been using TextSecure daily for about a year now and I have not experienced weekly outages like you describe; although I do admit it is possible I (and my social circle) was (were) just lucky. I do agree with you on the IOS bugs, but that's a topic for another issue.

**Comment by moxie0** [comment]
For the record, I also happen to know WA's precise uptime numbers for the year, and ours is still better.  There are going to be problems as TS continues to grow, and sometimes we're asleep when those problems come up.  We learn a little more each time, and eventually things will stabilize completely.
