### ISSUE TITLE
Automatically switched from one number to another when using Google Voice

### ISSUE THREAD

**Issue by aesahaettr** [WhisperSystems/TextSecure#3950]
I installed TextSecure and used my Google Voice number to verify. I then texted someone to test it out and it successfully used my Google Voice number to send the text message. Then, a day or two later, I noticed that I was receiving my text messages in Hangouts and not in TextSecure anymore. I texted someone to see what number it was using and it was my other, non-Google Voice number. I did not do anything in the settings that I think could have caused it to switch to that.

**Comment by moxie0** [comment]
If you send someone a regular unencrypted SMS with TS, it'll use your phone number on your SIM card (there's no other way).  If you send someone a TextSecure message, it'll use the number you register with.
