### ISSUE TITLE
Additional notification method - briefly flash screen when receiving new message

### ISSUE THREAD

**Issue by Pa9an** [WhisperSystems/TextSecure#3956]
(At minimum) Samsung S2 SMS app has this feature on stock rom; when you receive a new message, the screen briefly lightens up. Fairly handy if you got used to it, especially at work with the phone on silent. (LED notification doesn't work with that phone).

**Comment by agrajaghh** [comment]
This looks like a OS/Rom feature, not something a simple app should implement...

**Comment by Pa9an** [comment]
There's a whole setting page on TextSecure on notifications, what would be the problem with one more option?
I'm talking TS notification *only* anyway, so no need for an OS/ROM side implementation, IMHO...

**Comment by moxie0** [comment]
Sorry but there's no Android API for that which I know of, it sounds like an OEM specific thing.

**Comment by Mihahn** [comment]
I guess there has to be some way to enable this as snapchat has the same feature...

**Comment by moxie0** [comment]
let us know if you find the api!

**Comment by Mihahn** [comment]
I'm sorry but I'm not a dev and I have no idea how to implement a feature like that or which api snapchat uses... I just know that snapchat has this feature on android :wink:

**Comment by Pa9an** [comment]
Now, is this now closed or will anyone look into the mentioned api ?

**Comment by Pa9an** [comment]
Appears to be implemented in the latest CM12.1 nightly for at least i9100:

Lights with Screen On [2/2]: Optional allowment of lights (android_packages_apps_Settings)
Lights with Screen On [1/2]: Optional allowment of lights (android_frameworks_base)
