### ISSUE TITLE
I can't see which contacts I have already verified.

### ISSUE THREAD

**Issue by KommX** [WhisperSystems/TextSecure#3958]
When I manually verify a contact's identity by comparing the fingerprint or scanning the corresponding QR code I can't later see that I have verified the identity, can I?
I am expecting that TextSecure helps me remember which contacts I already have verified.

Is this feature missing on purpose?

**Comment by RiseT** [comment]
duplicate of #910

**Comment by KommX** [comment]
Ok, but that one's dead for a long time. :(

**Comment by jeremymasters** [comment]
@KommX To show mercy to the super-busy devs, discussion should be sent to the mailing list instead of creating a duplicate issue.  You can read some mailing list items here:  https://lists.riseup.net/www/arc/whispersystems/
