### ISSUE TITLE
Request: Choosing SMS or encrypted message when sending to TextSecure user

### ISSUE THREAD

**Issue by R1ckM** [WhisperSystems/TextSecure#3960]
By default when you send a message to an other TextSecure user it needs a data connection to be delivered. Sometimes I know the recipients to my messages (TextSecure users) are not in data range at their location.
It is frustrating to think you can send a message to a non-user in that same location and he/she will get it (as it will be a SMS over the regular cellular network), whereas a user won't...
Sometimes having the message reach its destination is more important than keeping the content private.

I wish I could have an option to 'just once' send the message as regular SMS when texting other users.

**Comment by jeremymasters** [comment]
Long-press the send icon and it will let you choose.

**Comment by R1ckM** [comment]
Brilliant! Thanks!
