### ISSUE TITLE
[Feature Request] New design for attachment drawer 

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/TextSecure#3967]
First of all: I'm not a dev but I really like the style of the attachment drawer in the stock android messenger. So I wanted to know if it would be possible to implement some similar style in TextSecure as it offers all the "features" we have or we will have in the future (except stickers). It has the same quick capture layout, a gallery, (stickers), audio messages (push-to-talk style) and send location. 

Maybe some dev could take a look at it and tell us if this would be possible. I (personally) think the design is just great :smile: 

![screenshot_2015-08-19-12-53-44](https://cloud.githubusercontent.com/assets/3447340/9354663/b718e62c-4672-11e5-9399-00b9b9ffe387.png)

**Comment by mammuth** [comment]
Although this is not the place for this (the mailing list is better for discussing), I like the idea, which seems to be oriented on Facebooks messenger. 

Side note:
With this, all attachments, which don't directly forward to another 3rd party activity (like contact choosing does) would need to have their UI inside the container where the camera preview is now. This might be a problem regarding the limited space.

**Comment by moxie0** [comment]
Thanks but this isn't a discussion forum.
