### ISSUE TITLE
Icons for contacts flicker/disappear as message list loads

### ISSUE THREAD

**Issue by gusandrews** [WhisperSystems/TextSecure#3968]
On a Kyocera Rise C5155 running Android 4.0.4, in TextSecure 2.17.0, the icons for contacts take a long time to load, and often flicker from the contact's initial to the image saved for that contact while the list loads. This makes it hard to quickly scroll down the list of messages to find a conversation you want to add a message to (which is generally an easier way to find a contact in TextSecure than to search for a contact, I find on this device).

Note the Rise is a piece of crap ;) and also one of the last slide-out keyboard phones out there, meaning there might be the mitigating factor of switching from portrait to landscape and the keyboard kicking in. This issue *may* have improved slightly with the latest release, but loading is still frustratingly slow.

**Comment by moxie0** [comment]
You're 19 releases behind.  Update and the flickering will stop.

**Comment by gusandrews** [comment]
welp, Jake said file it anyway because you need to hear about older phones :\

**Comment by moxie0** [comment]
is there some reason your phone can't run a recent version of textsecure? even if we made some change, it wouldn't have any effect on the version you're running.

**Comment by gusandrews** [comment]
It's weird, I'm actually not sure why I was so far behind -- I thought it was because I can't move beyond Android 4, but I appear to have updated to the most recent now and it definitely looks better.
