### ISSUE TITLE
With Google Play services requirement and SMS encryption disabled, TextSecure is just a SMS/MMS messanger?

### ISSUE THREAD

**Issue by mitar** [WhisperSystems/TextSecure#3969]
Since [SMS encryption was disabled](https://whispersystems.org/blog/goodbye-encrypted-sms/) and while Google Play services, which I lack on my phone, is still a requirement for push messages, it seems that after the upgrade to newer version TextSecure works for me just as a fancy SMS/MMS messenger, without any extra functionality. That is a sad evolution of the product.

**Comment by moxie0** [comment]
ok
