### ISSUE TITLE
Unable to add ASCII emoticons

### ISSUE THREAD

**Issue by mitar** [WhisperSystems/TextSecure#3970]
After upgrade to latest TextSecure, I lost ability to add ASCII emoticons. Instead, in its place there is now a newline button. And far away there is now an emoticons button, but for icons, not ASCII.

Enabling enter to send makes things even worse. Then there is a button "Send" instead of emoticons, but also the input box becomes one line. So very hard to read a longer message.

**Comment by moxie0** [comment]
Click on the emoji button in the compose text to open the emoji pane, then tap on the :-) to select the ascii emoji.  Also this is not a support forum, please post support questions on the support center (http://support.whispersystems.org) or email support@whispersystems.org

**Comment by mitar** [comment]
Oh, I missed that. Too many new things in new version. :-)
