### ISSUE TITLE
Beta download not working?

### ISSUE THREAD

**Issue by smichel17** [WhisperSystems/TextSecure#3972]
I've gone to the link (https://play.google.com/apps/testing/org.thoughtcrime.securesms) and it says I am a beta tester (double-checked that I'm using the right account) and that an update will be available in a few hours. However, I waited 24 hours and see no updates.

Should I wait longer, is there not a beta release out right now, or is this a bug? Should I go to you or to google for help with this?

**Comment by McLoo** [comment]
there not a beta release out right now
compare TS version in play with https://github.com/WhisperSystems/TextSecure/commits/master

**Comment by smichel17** [comment]
Duh. Thank you.

**Comment by moxie0** [comment]
In the future please post support questions to the support center (http://support.whispersystems.org) or email support@whispersystems.org for help.  Thanks.
