### ISSUE TITLE
remove number from "text secure users"

### ISSUE THREAD

**Issue by itbusters** [WhisperSystems/TextSecure#3973]
One of my friend, was text secure user, but he is not now. I'm unable to send any message to him, cause app says - he is still textsecure user. In fact, he gets nothing (also no notification).

**Comment by piratenpanda** [comment]
Long press the send button and select SMS. And there is some unregister page on whispersystems.org

**Comment by jeremymasters** [comment]
You could also have your friend re-install TS, then go into "Settings", then into "Advanced" then choose to not use "TextSecure messages".  Then they could uninstall the program.

**Comment by siccovansas** [comment]
Let your friend unregister on this page: https://whispersystems.org/textsecure/unregister/
