### ISSUE TITLE
Impossible to force SMS for TextSecure users

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/TextSecure#3974]
Hi,

When long pressing on the send button  (in a chat with another TextSecure user) there is a menu popping up that should allow to send unsecure SMS. Nothing happens if I press on this Unsecure SMS menu item. The text just stays unsent in the edit field.

(Sending SMS to non-TextSecure contacts works perfectly.)

Found in build  2.25.3. Phone is Samsung Galaxy Note 4.

**Comment by McLoo** [comment]
Did you press send after switching to sms? 
Long tap opens a dialog to choose the send mode

**Comment by Norbert80** [comment]
@McLoo thanks! This was exactly my mistake. I expected that clicking the menu item should directly trigger message sending. But it is implemented as sticky switch. And this is a good solution.

Please close this issue. Sorry for the circumstances.

**Comment by McLoo** [comment]
you're welcome
you can close this yourself - but you need to finally press the close button :wink:

**Comment by Norbert80** [comment]
OK.  Thanks. 😊
Closed.
