### ISSUE TITLE
No way to disable "Enable TextSecure Messages?" Nag popup

### ISSUE THREAD

**Issue by snuq** [WhisperSystems/TextSecure#3979]
Please add an option to disable this nag.  I am only wanting to use TextSecure as an sms client, I have no interest in encrypting my messages and if I do so, I cannot send or receive those messages because I usually have no data.
This is not the first time this has been requested:
https://github.com/WhisperSystems/TextSecure/issues/1891
https://github.com/WhisperSystems/TextSecure/issues/1966
https://github.com/WhisperSystems/TextSecure/issues/2734

Unfortunately, these threads are all closed so I cannot add my request to them... the explanation appears to be that encrypted standard sms support is going away, but I don't understand how this is an explanation for this request, isnt non-encrypted standard sms still to be available?
It appears that all those thread writers are not interested in encrypted sms, but rather just plain sms, as am I, and as far as I can tell, this issue has not been addressed yet for us.

Again, my reasons for using textsecure is not encryption, but rather that it has some nice features as an sms application, and is not as vulnerable to the stagefright bug.

**Comment by johanw666** [comment]
In that case you could install SMSSecure (https://github.com/SMSSecure/smssecure), a fork of TextSecure aimed at SMS.

**Comment by moxie0** [comment]
So you intentionally opened a duplicate issue.
