### ISSUE TITLE
Make TextSecure and Redphone more visible on the website

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#3981]
At https://www.whispersystems.org/ there are two sections, "Private Messaging" and "Private Calling". At the bottom of each there are two buttons to download Signal-iOS, but there are no links to the Android apps. I looked at the code in the repository (https://github.com/WhisperSystems/whispersystems.org/blob/fadab052e66bde5689ea0b2c234d35f8f4919050/index.html) and it looks like the buttons should be there. So either my browser has a problem or the website isn't running the same code of the repository. Either way, the buttons should be made visible

**Comment by moxie0** [comment]
This is not an issue tracker for the website, that's in the repository that you link to.
