### ISSUE TITLE
Brand new Signal user's attempt to start session crashes ALL other TextSecure sessions permanently

### ISSUE THREAD

**Issue by gordon-morehouse** [WhisperSystems/TextSecure#3992]
Well this is an interesting one. TS 2.25.3 on Android 2.3.4. I coaxed somebody into installing Signal and after some confusion about a verification code (I was getting texts that didn't tell me to send it to her, eventually we figured out that I should do that) she attempted to start a session with me. It failed.

At that point, every other active textsecure session I have with *every _other_* contact is now completely broken. I get a "failed to send" both on regular messages and on attempts to end the secure session. The 'tap for details' UI just says "failed to send" in red, and the "tap to resend" button will fail again.

With another TextSecure user in the same house, now *he* cannot send me messages ("failed to send") or end a secure session with *me.*  He also reports that it's asking him to verify my new identity key (?!).

It appears to have persisted one reboot and I will try another.

**Comment by gordon-morehouse** [comment]
Some errors (AuthorizationFailedException, another) at https://gist.github.com/gordon-morehouse/593e3291d616d19dcdc9

SecureSMS is also installed on this device. I disabled it from receiving all SMS after the first attempt (with the remote Signal user not understanding she needed a verification code from me, I guess), and set TextSecure to receive all SMS for now. Didn't help after the first reboot.

**Comment by gordon-morehouse** [comment]
A second TextSecure user is now reporting that, quote, "it won't let me resecure.  because you don't have an identity key."

**Comment by mawed** [comment]
If you got her verification SMS, are you shure she registered with her own number? Or did she put in your number, because she wanted to contact you?

If so there could be a problem by writing wit yourself, as long as multiclient support is missing.

**Comment by jensMF** [comment]
May be it could help, if you unregister from TextSecure an reregister afterwards...
If you can't unregister in the app try to unregister here:
https://whispersystems.org/textsecure/unregister/
May be you have to reinstall the app as well. I had a similar problem (without signal involved)  and these steps helped me. I recommend you to backup you data before uninstalling. (If you have pictures you want to keep and did not save them out of TextSecure an export of you messages is not enough.)
For Backups (is you have root and /system is writable): https://f-droid.org/repository/browse/?fdid=dk.jens.backup

**Comment by moxie0** [comment]
Sounds like your friend registered with your number instead of their own (shouldn't be possible, but you sent her the verification code), so now anytime someone sends you a message it goes to her.  Every time you try to send someone a message, it fails, because your client isn't authorized to send messages as your number (only your friends' is).  You need to reregister in order to recover.

In the future, please post to support.whispersystems.org or email support@whispersystems.org for support questions.
