### ISSUE TITLE
forgot password

### ISSUE THREAD

**Issue by 85windsor** [WhisperSystems/TextSecure#4003]
Anyway to find out my password or if it was changed through the debug log? 
If so:
https://gist.github.com/anonymous/551b885313090da64418

**Comment by jeremymasters** [comment]
I think the whole point is not to be able to do that, otherwise it would be too easy to break passwords in general.

**Comment by mcginty** [comment]
http://support.whispersystems.org/customer/portal/articles/1468950-i-forgot-my-passphrase-can-you-reset-it-for-me-

**Comment by chronometric** [comment]
moved here: http://support.whispersystems.org/hc/en-us/articles/213190667
