### ISSUE TITLE
BOSH support?

### ISSUE THREAD

**Issue by pgnd** [WhisperSystems/TextSecure#4008]
I use TextSecure on Android.

Works well with my Prosody XMPP server -- until I inject a public VPN (PIA, HMA) into the mix.  I'm working (around) the WHY, but both seem to block/prevent XMPP traffic.

I suspect, but don't yet know, that that's due to port(range) blocking, not to packet inspection.

So, currently, to use TextSecure's security I need to drop VPN's security :-/  Bit of a Catch22.

One way around it is to enable Prosody's BOSH server, where BOSH allows XMPP where only a unblocked HTTP(S) connection is available, front-ending it with an nginx proxy.

    XMPP Technologies: BOSH
        https://xmpp.org/about-xmpp/technology-overview/bosh 

    Setting up a BOSH server
        https://prosody.im/doc/setting_up_bosh

With nginx's SNA support, the BOSH proxy could easily be added to an existing webserver-occupied IP.

For this to be useful, however, the Client needs to support BOSH as well.

Afaict, TextSecure does not.

Looking around, the closest I've found to bosh support for XMPP on Android is Smack (https://www.igniterealtime.org/projects/smack/).

Smack API runs native under Android, and provides bosh libs,

 https://github.com/igniterealtime/Smack/tree/31c53f094c9a613821b9e101f9d7f9bfd775b4e1/smack-bosh/src/main/java/org/jivesoftware/smack/bosh

(1) Does TextSecure -- in release or dev -- currently have BOSH client support?
(2) If not, can it be added? 

Given TS's security focus, I'm guessing this is most likely an issue that'd be dealt with here, sooner than elsewhere.

**Comment by mcginty** [comment]
You might be thinking of ChatSecure.

**Comment by pgnd** [comment]
GAGH! Sorry.
