### ISSUE TITLE
SMS fallback not triggered if recipient offline

### ISSUE THREAD

**Issue by jonathancross** [WhisperSystems/TextSecure#4009]
#### Use case:
I and my contact are "push registered", but at various times one of us goes offline for a few hours and would like to seamlessly switch to SMS.

Explanation: I only use data when connected to WiFi, so SMS is prefered communication channel much of the time.  This is common amongst my contacts here in Europe, but some have mobile data.

#### Issue:
TS seems to switch to PUSH whenever sender has data (or even if previous conversation was PUSH). This leads to frustrating undelivered messages if sender simply hits reply without deliberately forcing SMS.

#### Feature request:
When there is evidence that the sender **or** recipient is offline, there should be some way to prefer SMS.  

Two possible ways to avoid these undelivered PUSH replies:

1. Seamless SMS fallback if **either** person is not online.
2. If "seamless" is not an option: receiving an SMS should trigger SMS mode for the conversation.  I understand that defaulting to SMS is problematic now that SMS encryption is gone, but this could be an "Advanced" option for nerds like me.

Can add a warning as modal, or in settings: *"Warning: this could cost you money or accidentally lead to insecure SMS communication."*

#### Related:

This behavior was outlined by @cramu here:  https://github.com/WhisperSystems/TextSecure/pull/984#issuecomment-36750018

> If sender or recipient are not reachable (because mobile data is not available) a popup appears, warning the sender that the message could be delayed and asking him for confirmation or to edit his message and send via SMS/MMS.

Issue #678 looked promising, but that bug is huge, stale and it is unclear what was finally decided upon / implemented.

**Comment by JavaJens** [comment]
The TextSecure protocol is asynchronous. So there is no such thing as an "offline" contact. I think moxie outlined it quite detailed in the references issue.

**Comment by moxie0** [comment]
Yep
