### ISSUE TITLE
[Feat. Request] Contact/Thread Grouping 

### ISSUE THREAD

**Issue by livmackintosh** [WhisperSystems/TextSecure#4010]
The ability to add contacts into groups would be lovely as people often get lots of messages in a day. I understand this might be a challenge but if its possible and realistic, I think it would be appreciated by lots of people :)

**Comment by jeremymasters** [comment]
Sounds like what you're saying is a "low-priority" set of users/notifications?  I think if you give the scenario your idea will be more clear.  This seems like something capable with the "inbox" idea Moxie mentioned elsewhere.

**Comment by livmackintosh** [comment]
I usually get quite a few texts a day and when combined with TextSecure messages it's pretty frustrating sometimes. I'll have to look at Moxie's suggestion but some type of foider system would be useful. This would allow users to sort incoming messages into folders based on who they're from. (E.g. Work, friends/familly, spouse etc). I think this is important because the direction of TextSecure seem's to be in increasingly complete solution in that it can be a replacement SMS app and also provide encrypted push and SMS messages with calling, photos, attachments etc.

I'm trying to resist giving a complete picture of what this system would be like because everyone's needs are different and I would feel biased to comment on my own.

Also I'd be more than happy to develop some code but it would be nice to discover if it's a feature many people would find useful and also what would work well and not add clutter.

Liv

**Comment by moxie0** [comment]
Thanks but I don't think we're going to do this.
