### ISSUE TITLE
[Feat. Req.] Modules welcome

### ISSUE THREAD

**Issue by lustigo** [WhisperSystems/TextSecure#4011]
Hi,
i would love to see an App in an App functionality:
So that third-parties can develop own apps that need a friendship/messaging functionality and use Textsecure for that, so the messages can be encrypted. So no user has to have 10 Apps that have their own messaging and contacts. You only have one installed and you can use every feature of this 10 Apps in one.

A Permission System should be included.

**Comment by moxie0** [comment]
Thanks but we're not going to do this.
