### ISSUE TITLE
new media download control preference strings not i18n

### ISSUE THREAD

**Issue by RiseT** [WhisperSystems/TextSecure#4015]
Including the title ('Chats and media').

v2.26.0

**Comment by moxie0** [comment]
Please do not open transifex issues here.

**Comment by RiseT** [comment]
@moxie0 And where I am supposed to open them, if I may ask? It has happend a couple of times in the past that due to some oversight in the code some strings were untranslatable. As this has to get corrected within the code, I would think this is the correct place to report them, no?

In this current case, the strings have appeared at Transifex in the meantime btw. Don't know if this time the reason has been something different than the one mentioned above.

**Comment by 2-4601** [comment]
`strings.xml` is still missing strings for:
* _Media auto-download_
* _When using mobile data_
* _When using Wi-Fi_
* _When roaming_
* _Message trimming_

I.e. those are untranslatable.

**Comment by RiseT** [comment]
@2-4601 You're correct, of course. When I noticed the new strings at Transifex, I incorrectly thought they were complete. They are not.

**Comment by RiseT** [comment]
@mcginty It has been correct to report this here, no? Asking for clarification.

**Comment by mcginty** [comment]
@RiseT yes definitely, I updated the title to be more accurate (making it clear it's not a transifex issue)

**Comment by RiseT** [comment]
@mcginty Thanks very much. I wouldn't have been able to come up with this title on my own, though, as I have no idea what 'i18n' is :-)

**Comment by jeremymasters** [comment]
i18n = "internationalization"
another one l10n = "localization"

**Comment by RiseT** [comment]
@jeremymasters Jesus... thanks!
