### ISSUE TITLE
leading chars dropped from message

### ISSUE THREAD

**Issue by zooko** [WhisperSystems/TextSecure#4021]
Sending side (me): TextSecure 2.25.3 on Android 5.x. Receiving side: Message+. I sent a 162-char (ASCII) message. My friend received only the trailing 9 chars! The first 153 chars were dropped.

**Comment by zooko** [comment]
My friend's version of Message+ is v5.6.7.

**Comment by moxie0** [comment]
Message+ is a regular SMS app, so it sounds like these are plain old unencrypted SMS messages.  Since we don't do any processing on those, and the Android OS is responsible for delivery, it seems likely that this is a problem with your mobile service.

**Comment by zooko** [comment]
Okay, thanks!
