### ISSUE TITLE
Stop responding to encrypted SMS

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#4026]
Now that the official binary of TS 2.6.4 has expired, it would make life easier for SMSSecure users if you implemented PR 2817 to stop complaining when an encrypted sms is received by the device and TS is not the default SMS provider.

**Comment by bungabunga** [comment]
@moxie pretty please, it won't hurt anyone.

**Comment by DonaldMorden** [comment]
totaly agree with you

**Comment by DonaldMorden** [comment]
I totally agree with you
