### ISSUE TITLE
Missing thumbnail for pending image download

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#4027]
If an **image** download is pending
there is only the download arrow (and maybe a text)
but no indication (thumbnail) of what will be downloaded.

For audio and video there are the specific built in icons/thumbnails. So maybe we should have that for images too.
Alternative would be to have an ultra low resolution image that is sent with the message as thumbnail.

**Comment by McLoo** [comment]
![screenshot_2015-09-06-13-10-39 01 01](https://cloud.githubusercontent.com/assets/5326916/9704059/0414f2a2-5499-11e5-99bf-a93bd9c09e8c.png)

**Comment by Dyras** [comment]
This happens for me even AFTER I've downloaded the picture.

**Comment by mcginty** [comment]
fixed in 2.27.0
