### ISSUE TITLE
SMS sent through Google now do not appear in Textsecure

### ISSUE THREAD

**Issue by jandechent** [WhisperSystems/TextSecure#4037]
1. Use "OK Google send message to moxie lets rock"
2. confirm Sending SMS
3. Open default messaging app: the sent SMS doesn't show up, although the SMS was sent and received by the other one. 

Expectation: content of SMS appears in default SMS app - in this case ts. 

Not expected : to have a private conversation this way.

**Comment by moxie0** [comment]
Unfortunately that's not possible.  Google doesn't give us any indication that it is sending an SMS message on your behalf.  It writes to the shared SMS store, which of course TS doesn't use.
