### ISSUE TITLE
Regression: Clicking on Foto does not display full screen in build 2.26.2.

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/TextSecure#4051]
This is broken in 2.26.2.

**Comment by dcherian** [comment]
For me, this happens only for photos I *send* to other people. Received photos open fine.

2.26.2, stock 4.4.4

**Comment by Norbert80** [comment]
Can confirm that received fotos are not affected.

**Comment by 2-4601** [comment]
Still broken for sent group photos.
TS 2.26.4
Nexus 4, stock 5.1.1.

**Comment by dcherian** [comment]
Works for me. 2.26.4, moto g 4.4.4

**Comment by Norbert80** [comment]
Works for me (both chats and groups ) with build 2.26.4 on Samsung Galaxy Note 4.

**Comment by 2-4601** [comment]
Strange. It works for me for in regular chats but in groups sent pictures don't react to taps.
Debug log (with lots of useless info): https://gist.github.com/anonymous/ff3e99f7f899ca9e0799

**Comment by Norbert80** [comment]
Can confirm that it does NOT work for group chats with pictures that have been sent with build 2.26.4!

But it works with outgoing  pictures from the group chat history that have been sent with older builds than 2.26.3.

REOPENED

**Comment by Norbert80** [comment]
@mcginty pleas re-open. I don't have the privileges.

**Comment by Norbert80** [comment]
I can confirm that the issue is completely fixed in build 2.26.5.

**Comment by mcginty** [comment]
Thanks for following up @Norbert80
