### ISSUE TITLE
Crash after unlock. Again. 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#4061]
Just updated to innocent looking 2.26.4
Shouldn't have. 
https://gist.github.com/550eff75697fea56861d

Log looks pretty much like #4054 

Hey,guess who didn't backup again :cry: 

Stupid glide asserts. wtf.

**Comment by moxie0** [comment]
Something is very seriously wrong with your install.  The code that you're running isn't the 2.26.4 code.  Check out the stack traces and where they line up with the source, it's totally off.  Do you have anything else weird on your device?  Is it rooted, or is this all totally vanilla?

**Comment by mcginty** [comment]
Yeah so it looks like the error section of the log doesn't clear between installs and the real crash is this one:

```
W/DatabaseUpgradeActivity( 4811): queuing new attachment download job for incoming push part (row id: 457, unique ID: 0).
W/DatabaseUpgradeActivity( 4811): queuing new attachment download job for incoming push part (row id: 463, unique ID: 0).
W/CanonicalAddressDatabase( 4811): Hitting DB on query [ID].
W/DatabaseUpgradeActivity( 4811): corrected a pending self-sent media part (row id: 857, unique ID: 1436282162502).
W/MediaNetworkRequirement( 4811): part transfer progress is 1
W/AttachmentDownloadJob( 4811): Downloading push part (row id: 457, unique ID: 0)
W/DatabaseUpgradeActivity( 4811): corrected a pending self-sent media part (row id: 858, unique ID: 1436282185732).
W/JobConsumer( 4811): java.lang.NegativeArraySizeException: -20
W/JobConsumer( 4811): 	at org.thoughtcrime.securesms.crypto.MasterCipher.verifyMacBody(MasterCipher.java:157)
W/JobConsumer( 4811): 	at org.thoughtcrime.securesms.crypto.MasterCipher.decryptBytes(MasterCipher.java:98)
W/JobConsumer( 4811): 	at org.thoughtcrime.securesms.crypto.MediaKey.getDecrypted(MediaKey.java:28)
W/JobConsumer( 4811): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.createAttachmentPointer(AttachmentDownloadJob.java:129)
W/JobConsumer( 4811): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.retrievePart(AttachmentDownloadJob.java:104)
W/JobConsumer( 4811): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.onRun(AttachmentDownloadJob.java:77)
W/JobConsumer( 4811): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/JobConsumer( 4811): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/JobConsumer( 4811): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

That means there is an incoming part marked as pending that is not self-sent or is self-sent with a content location that's non-null. One hint is that this appears to be an *older* self-sent message (before unique IDs were added), so there's a chance that the self-send code has changed since then and older ones had a non-null content location.

**Comment by McLoo** [comment]
Nothing better than a root enabled dB editor. 
Unpended the following parts 
Now all is well again. 
Did all at once, though I guess 457 was the bad guy.( Part id max()  is 1021 right now) 

![screenshot_2015-09-10-23-16-15 01](https://cloud.githubusercontent.com/assets/5326916/9802187/bfd1e022-5818-11e5-8eea-53f9481f8920.png)

**Comment by mcginty** [comment]
@McLoo can you email me the full column values of that row that was causing problems? I want to know what kind of part is causing the problem with the migration.

**Comment by McLoo** [comment]
Alas, it's gone - vanished into nothingness?!
Sorry, just edited the pending field.

Resurrected the line from a month-ago-backup. Seems to be slightly different though, as there is an entry in the *cd* field.
![unbenannt](https://cloud.githubusercontent.com/assets/5326916/9810207/1936bac4-586f-11e5-9bea-2c021ef4b352.png)

in the first screenshot, the red fields are nulls 

first unique_id != 0 is at ID 741

**Comment by jrudolph** [comment]
Has this fix been released already?

I've got this after a recent upgrade to 2.28.1 on OPO and now cannot start TextSecure any more which is a bummer obviously...

```
W/KeyCachingService(16711): onCreate()
W/MediaNetworkRequirement(16711): part transfer progress is 1
W/AttachmentDownloadJob(16711): Downloading push part (row id: 328, unique ID: 1442595057368)
W/JobConsumer(16711): java.lang.NegativeArraySizeException: -20
W/JobConsumer(16711): 	at org.thoughtcrime.securesms.crypto.MasterCipher.verifyMacBody(MasterCipher.java:157)
W/JobConsumer(16711): 	at org.thoughtcrime.securesms.crypto.MasterCipher.decryptBytes(MasterCipher.java:98)
W/JobConsumer(16711): 	at org.thoughtcrime.securesms.crypto.MediaKey.getDecrypted(MediaKey.java:28)
W/JobConsumer(16711): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.createAttachmentPointer(AttachmentDownloadJob.java:133)
W/JobConsumer(16711): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.retrievePart(AttachmentDownloadJob.java:108)
W/JobConsumer(16711): 	at org.thoughtcrime.securesms.jobs.AttachmentDownloadJob.onRun(AttachmentDownloadJob.java:81)
W/JobConsumer(16711): 	at org.thoughtcrime.securesms.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
W/JobConsumer(16711): 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
W/JobConsumer(16711): 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

Any idea how to work around this?

**Comment by McLoo** [comment]
By updating the specific row (328) to "push_pending" = 0
with a sql editor, that can a access TS's data directory (root needed afaik)

@mcginty very likely want's to have the complete information of that row...

**Comment by mcginty** [comment]
@jrudolph if you do have root I'd love to see what your DB looks like (specifically that row, as @McLoo said).

**Comment by moxie0** [comment]
shouldn't crash anymore

**Comment by jrudolph** [comment]
Yes, I would like to look at the db, as well, but, unfortunately, I haven't rooted my phone (and I feel stupid for it). It seems I may get at a db snapshot through a backup, that's what I'm currently trying.

**Comment by jrudolph** [comment]
@moxie0 wdym? Should it be fixed in 2.28.1, or is there a new version available?

**Comment by mcginty** [comment]
@jrudolph it will be out in 3.0

**Comment by jrudolph** [comment]
I got it fixed by following the hint from @McLoo (though not doing it live (no root) but by operating on a backup).

Here's the original row btw:

```
328|424|0|image/jpeg||||||2593287528633778189|||0|1|||||1442595057368
```

Thanks for your help. Much appreciated!
