### ISSUE TITLE
Individual notification settings for contacts

### ISSUE THREAD

**Issue by Kazpers** [WhisperSystems/TextSecure#4064]
Currently you can only set the ringtone and vibration individually for each contact/thread. It would be very useful to be able to set the LED color so you can see at a glance who wrote, also it'd be useful to be able to set notification level (name, message, none) shown on an individual basis so I can see the messages eg my wife writes at a glance but business contacts are more confidential and only show the name.

**Comment by moxie0** [comment]
Thanks but I don't think we're going to do this.
