### ISSUE TITLE
After update: no notification sent with TextSecure message. I have to open the app to see if there's something new

### ISSUE THREAD

**Issue by DigitalGrinch** [WhisperSystems/TextSecure#4070]
After latest update, there is no notification sent with TextSecure message. No sound alert, no number appearing to show me i have 1 unread message. It has been happening past few days, maybe a week.
I have to open the app to see if there's something new. I have missed messages because I saw them too late.
I almost missed out on Football today when a friend invited me last night and I never got alert. I had the thought to open the app this morning and luckily was able to respond in time. Serious issue ;)

and yes I looked in Settings, Notifications is still set to On. (This was my first time in Settings, so I know I have not changed anything there myself)

**Comment by DigitalGrinch** [comment]
Some more info:
I am using ANDROiD version. Friend was using iOS version(Signal)
TextSecure is default messages app for me. I just had iOS friend send me sms through his messages app, and that came right through, sound alert, icon in notification area and little number letting me know I had unread messages in app.

So it appears to only be an issue with secure messages

**Comment by AlfonsoMuskedunder** [comment]
It could be a problem with Google Play Services. Try the following: go to advanced settings, and unregister for TextSecure messages; then reregister (you'll have to submit your phone number again). That should be it.

**Comment by 2-4601** [comment]
What's your device, OS/ROM? Are you using permission managers?
Post a debug log after it happens: **Settings -> Advanced -> Submit debug log**
and paste the link here.

Also see: 
http://support.whispersystems.org/customer/en/portal/articles/2121929-why-is-there-a-delay-in-receiving-messages-

**Comment by rypervenche** [comment]
I have had this problem for a little while now and finally decided to do something about it. The above mentioned unregister and reregistering fixed my problem. I don't know if this will help now that my problem has been fixed, but here is my debug information:

https://gist.github.com/5da0cd6d4ce94028fc2d

I hope this can help some of you.

**Comment by rypervenche** [comment]
It looks as though I spoke too soon. It worked for a little bit and now I am having the same problem again. New log: https://gist.github.com/02d06fa228c28a7b554a

**Comment by moxie0** [comment]
If you're not receiving push messages, it means either: 1) You've disabled background data for TextSecure or for Google services, 2) You're running a custom ROM with a bad gapps install, 3) You've used an app like Titanium backup, or any other backup app, or 4) You're on a network that's blocking GCM.

**Comment by DigitalGrinch** [comment]
1. have not disabled. If I had, push never would have worked
2. stock rom, rooted, bloat removed
3. I've used titanium Backup to remove some bloatware, but that was when I first got phone and have not used since. TextSecure was installed after this work, and TextSecure used to work. I am not sure "what changed" that could have caused this. How does Titanium backup screw up TextSecure, and how do I fix it?
4 no, again, push never would have worked if thise were the case, but push used to work.

**Comment by merkste** [comment]
@moxi I am a bit puzzled, why you closed that issue. It's there another one which this is a duplicate of? Since this problem still happens to a friend of mine and today to myself and others as I can see in the play store comments, I think it hasn 't been solved yet.

However, maybe I can provide additional information.
* It happened for me after power saving more kicked in and persisted even afterwards.
* Strangely, one contact is not affected.
* https://gist.github.com/anonymous/d007cb906566b7fac012
* https://gist.github.com/anonymous/2cec2cc95ee90295f3da
* Sometimes, de- and re-registering fixed the issue temporarily. However, that's hard to tell the average user TS is meant to be for.

Needless to say that none of your possible explanations fit here.
I wonder, whether it might possible to detect those situations automatically and fix it or request user action?

**Comment by 2-4601** [comment]
@merkste If this issue is not only related to a specific version (update) then this is a duplicate of #970.

Lollipop's power saving mode disables background data.

**Comment by merkste** [comment]
@2-4601 I'll add my logs an stuff there. Thanks.

**Comment by jedie** [comment]
Same as: #4266

**Comment by DigitalGrinch** [comment]
Seems to be fixed after update. Thanks.
