### ISSUE TITLE
Check whether new phone numbers can receive encrypted texts

### ISSUE THREAD

**Issue by effigies** [WhisperSystems/TextSecure#4071]
Would it be possible, if I start a message to a new phone number, to check whether that number can receive push messages and perform the handshake prior to the first message? I recently added a contact I knew would have TextSecure, so I was able to verify that this either isn't supported or isn't working.

I have a suspicion that this might not easily work with the [contact discovery](https://whispersystems.org/blog/contact-discovery/) mechanism, and if so, I can continue creating contacts before texting them.

**Comment by riyapenn** [comment]
Related to https://github.com/WhisperSystems/TextSecure/issues/2785

**Comment by effigies** [comment]
Thanks. Missed that in search.
