### ISSUE TITLE
highlight text then replace it by emoticon makes the app crash

### ISSUE THREAD

**Issue by Wohlraj** [WhisperSystems/TextSecure#4078]
Steps to reproduce :
1) Type some text in TextSecure (do not send it)
2) Highlight it
3) Replace the highlighted text by an emoticon

Tested on Z3 Compact (Android 5.1.1) and Nexus 4 (Nexus 5.1.1)

**Comment by McLoo** [comment]
Confirmed https://gist.github.com/d512e6935f90c5fed4e6

**Comment by mcginty** [comment]
in 2.27.0
