### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by MeMaxHello** [WhisperSystems/TextSecure#4088]
I know it's unimportant, but on textsecure I enjoyed having android emojis and don't like being forced to use apple's. 
It would be wonderful if we were allowed to choose, or if the app just used whatever the phone's default is. 

Thanks.

**Comment by jeremymasters** [comment]
I think they already took care of this in the upcoming 2.27 release...https://github.com/WhisperSystems/TextSecure/commit/e077cc658122251b1a20508841e94d2e02c00901

**Comment by moxie0** [comment]
please please please check existing issues before opening new ones.
