### ISSUE TITLE
Self sends get notified after some time 

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#4089]
Bit in a hurry, so short :
Send self non sms 
Leave TS 
After some time the self send is notified

**Comment by McLoo** [comment]
Ahh, the notification rides along with another,  regulations one or seems. 
Thread is shown as unread  but once notified, the self sent notification waits for being tapped...

**Comment by Dyras** [comment]
https://github.com/WhisperSystems/TextSecure/issues/3877

**Comment by mcginty** [comment]
we'll call this a dupe of #3877
