### ISSUE TITLE
Minor Dark theme gripe

### ISSUE THREAD

**Issue by kpuljek** [WhisperSystems/TextSecure#4092]
When using the Dark theme, the main android status bar remains brightly colored and really draws attention to itself. Even worse - depending on conversation color, it can look really ugly. Can it just become darker like the rest of the app? Thanks!

**Comment by moxie0** [comment]
thanks but this has already been discussed in the many color issues

**Comment by signalguest** [comment]
Please rename to a more meaningful title.

Can we get a reference to the discussion?

**Comment by kpuljek** [comment]
Sure, I'll rename right away. This is the only thing keeping me from using the dark thene
