### ISSUE TITLE
textsecure notifications without data? 

### ISSUE THREAD

**Issue by petetridish** [WhisperSystems/TextSecure#4093]
i usually leave data off on my phone, to conserve battery life.  in the default message app, when i receive a text  to multiple recipients, i have to turn data on to receive it, but i get a notification that it is there even with the data off.  

is that possible with text secure, for when messages come in? i'd really rather not have to have the data on just to know that there is a text message that someone sent me...

thanks,

**Comment by moxie0** [comment]
Sorry @petetridish if you don't have data by default then TS is probably the wrong messenger for you.
