### ISSUE TITLE
MMS not imported on fresh install

### ISSUE THREAD

**Issue by michaelbartnett** [WhisperSystems/TextSecure#4095]
Just installed TextSecure (from Play store) for the first time send/receive all worked great and SMS import worked, but none of the MMS messages were imported. Sending/receiving them worked fine but I don't see any of the old group messages in TextSecure.

Is this supported?

Phone model: Verizon HTC One (HTC6500LVW)
Android version: 5.0.2

**Comment by moxie0** [comment]
Not supported.  Best place for support questions is the support center (http://support.whispersystems.org) or emailing support@whispersystems.org thanks!
