### ISSUE TITLE
Picture received with data refused to load

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/TextSecure#4097]
Hi. I'm going to join the club with picture related issues this week, and report that today at the university a picture downloaded indefinitely. I even tried restarting the app and it didn't help. It only worked when I restarted the phone. And yes, I killed the TS process.

When I was trying to press download, but nothing happened:
https://gist.github.com/anonymous/f0115d3e50dc26e701f6

When it finally started "downloading":
https://gist.github.com/anonymous/2b31b5988868c75115ee

When it kept downloading with nothing happening:
https://gist.github.com/anonymous/67c7160595bbde0e758f

What happened was this: I was on my mobile data at the university, and after pressing download I turned off mobile data and connected to WiFi. I could send messages just fine, and I could send other pictures, it's just that this one picture just didn't want to download.

**Comment by mcginty** [comment]
The logic around the download button has changed enough between 2.26.5 and 2.27.0 (and your logs don't show anything specific to a download job) that I'd like to see if you can try and reproduce this with the new 2.27.0 release.

**Comment by mcginty** [comment]
removing the 2.28 milestone for now until we can determine if it's still reproducible

**Comment by Dyras** [comment]
I'll post next week if this happens at the university again.

**Comment by mcginty** [comment]
Thanks!

**Comment by Dyras** [comment]
This hasn't happened for me in 2 weeks, so I'm closing this.
