### ISSUE TITLE
Problems with properly accessing contacts stored via CardDAV on older Android devices?

### ISSUE THREAD

**Issue by AlfonsoMuskedunder** [WhisperSystems/TextSecure#4100]
Could it be that TextSecure has problems with contacts stored via CardDAV on older Android devices?

Since a couple of weeks (then on 2.25.3, now 2.26.5) I'm experiencing some problems. I have all my contacts stored via CalDAV, none on the SIM card and none on the phone (that runs on 4.2.2).

1) Since a couple of weeks almost all TS-using contacts are shown twice in the list of TS users (and once under "All contacts"). Only newly added TS contacts are listed once. It started when I used TS 2.25.3.

2) Today I noticed that one contact was listed (in the conversations list and in TS' contacts list) without her name, only by her number. Although the native contacts app shows a perfectly fine entry, when I tried to call that person, her name was not shown when dialing (as it would normally happen); instead her number was listed as an "other" number---in the native contacts app, her number is labeled "mobile". In fact, when I tried to edit the contact in the native contacts app, at the bottom there is an entry for TextSecure (that cannot be edited) that indicates that the number is stored on the phone with the label "other". (In turn, when I restrict the contacts to app to show contacts stored on the phone only, it lists none, as I would expect.)

Does that imply that TS creates a local copy of the CardDAV phone number on the phone? In fact, said contact is one the many duplicates.

3) I played around and "separated" and re-"joined" the varying accounts via which I'm connected to said person in the native contacts app. Now her name (instead of her number only) is listed twice again in the list of TS users, but the two entries are not listed in two subsequent rows, but the first entry jumped to the very top of the list, before the names starting with an A. I repeated that exercise with another duplicate entry, to the same effect: it seems that a second list of TS users is created that is alphabetically ordered and stacked on top of the other one.

Apologies for this lengthy post. The only previous issue I found that mentions CardDAV is https://github.com/WhisperSystems/TextSecure/issues/2533, which "solved" itself when the user updated to a higher Android version.

**Comment by brumsoel** [comment]
I'm on 4.2.2 too and my contacts are also synced via CardDAV (using DAVdroid), but I can't confirm the behaviour you described.
The only contacts listed twice under "TS users" are those who actually are registered with two different numbers - they're also displayed twice under "All contacts".

**Comment by AlfonsoMuskedunder** [comment]
Reinstalled Signal; no duplicates anymore.
