### ISSUE TITLE
Emoji Selection missing with system emoji (2.27)

### ISSUE THREAD

**Issue by Ahoipirat** [WhisperSystems/TextSecure#4101]
With enabled system emoji, the shortcut to the emoji selection in the bottom left corner is removed.

My keyboards (Swype and Google Keyboard) show an emoji button instead the normal enter button, which I used for line breaks.
This is not possible anymore with enabled system emoji.

Please don't change the behavior of the layout with enabled system emoji, it's just irritating.

**Comment by moxie0** [comment]
By disabling TextSecure emoji, you get the *system* emoji experience.  That means we do nothing with emoji, including a custom emoji keyboard.  If your system keyboard doesn't support line breaks, that's beyond our control and something you should take up with the authors of those keyboards.

In the future, the best place for support questions is the support center or support@whispersystems.org, thanks!

**Comment by dcherian** [comment]
It would be a more consistent experience if the emoji shortcut button remained. Would that be possible?

**Comment by mcginty** [comment]
not possible afaik

**Comment by Ahoipirat** [comment]
Thanks for the clarification moxie.
I'm still happy the system emoji were added. :)

**Comment by bungabunga** [comment]
i'm afraid this solution is not well thought enough and there's gonna be a lot of unnecessary duplicates of this issue in the future.

**Comment by Ahoipirat** [comment]
I tried many keyboards now (AOSP, Google, Swype, Swiftkey). Most of them have a dedicated emoji button in all of my apps, except in Textsecure.

In Textsecure, the enter button gets replaced with the emoji button after activating system emoji of all my tested keyboard apps.

So I don't think it's only about the keyboard apps. Your implentation seems to change the normal behavior.

I need my enter button and prefer system emoji. Right now I can't use them because of that.

Can't you just let the emoji button in the bottom left corner be available and show system emoji instead of IOS emoji?

This is be the most consistent way in my eyes and you would prevent future issue duplicates.

Would be glad if you think about a possible solution.

**Comment by McLoo** [comment]
Long tap enter works for me with SwiftKey 
![screenshot_2015-09-22-12-55-51](https://cloud.githubusercontent.com/assets/5326916/10016721/5ea52952-6129-11e5-8797-e1cc08cc4219.png)

**Comment by RiseT** [comment]
I can confirm @McLoo 's statement regarding SwiftKey.
Tap = Emoji selection, Long tap = Enter

**Comment by Ahoipirat** [comment]
After longer research I have to confirm this, too. For Swiftkey and Swype.

The Google and AOSP keyboard don't show enter on longer press of the emoji button, sadly.

Still prefered the dedicated emoji button, long press wasn't needed at all.

**Comment by wickedshimmy** [comment]
@Ahoipirat With the Google Keyboard, press Shift to toggle the emoji/enter key.

**Comment by moxie0** [comment]
Thanks everyone, this is a great support discussion to continue over at the support center.
