### ISSUE TITLE
Can't share large attachment from gallery

### ISSUE THREAD

**Issue by Mihahn** [WhisperSystems/TextSecure#4107]
When I try to share a large attachment (e.g. video, gif) from the gallery, I get the toast saying it exceeds the limit. When I click on the attachment button in TS however, I can select the file and send it just fine...

Android 5.1.1, TS 2.27 https://gist.github.com/anonymous/78cdc21496f95b2038d2

Just a side note: I deleted the video while sending it to see if it stops, but it obviously doesn't...

**Comment by mcginty** [comment]
yeah, looks like this is because initializeDraft() happens before initializeSecurity(), so it doesn't think the user is a push recipient.

**Comment by mcginty** [comment]
closed in e574bcf15c95c72d3b159dc7e0af245004549fa5

**Comment by Mihahn** [comment]
Fixed in 2.27.1! Thanks :+1:
