### ISSUE TITLE
Tapping a selected picture message opens "View secure media?"

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#4120]
99d3374d35b5027850fdc31c8a2620fb5f83fbf7 seems to cause this behavior:
1. Select a picture message
2. Tap the selected picture message (inside the thumbnail)
3. TS opens the _"View secure media?"_ dialog

If you tap outside the message it deselects the message as expected.

**Comment by 2-4601** [comment]
I should have been a bit more patient. Fixed with 6576b72280ceb9073b0683b6f0c11071a15c7aa5

**Comment by mcginty** [comment]
:)
