### ISSUE TITLE
Goes "back" when typying text in recipient field/creating new message

### ISSUE THREAD

**Issue by misioooo** [WhisperSystems/TextSecure#4124]
Hi!
V 2.27.2
Meizu MX4
FlymeOS 4.5.5I
Android 5.0.1
Great app! But i have some issues:
1. When i press "Create new" (bottom-right icon) it opens window to create new message. When i press any keyboard button it goes back to previous screen...
Same thing happens when i go to Settings and press first option there (to select default SMS/MMS app). Text secure is default messaging app.

**Comment by jeremymasters** [comment]
I'm on Samsung galaxy s5 stock verizon rom 5.0 and do not encounter this behavior.

**Comment by moxie0** [comment]
Thanks but it sounds like a bug in FlymeOS, whatever that is.
