### ISSUE TITLE
SMS messages received from TextSecure users are blue not green

### ISSUE THREAD

**Issue by p8952** [WhisperSystems/TextSecure#4126]
Device Model: MotoG
Android Version: 5.1.1 (CyanogenMod 12.1.20150820-NIGHTLY)
TextSecure Version: 2.26.5

Situation:
* PersonA and PersonB both use TextSecure.
* PersonA uses TextSecure as their default SMS application.
* PersonB does not use TextSecure as their default SMS application.
* PersonB does not always have a network connection and will at times send SMS messages to PersonA.

Expected Behaviour:
* SMS messages sent from PersonB to PersonA will be shown as green in TextSecure.

Current Behaviour:
* SMS messages sent from PersonB to PersonA are shown in blue.

Problems Caused:
* PersonA does not know if the message sent from PersonB was sent securely.
* PersonA may assume PersonB has connectivity due to them sending messages, and thus wrongly assume their messages have been received.
* PersonA may not know over which medium (SMS/TextSecure) they are expected to reply to PersonB.

**Comment by 2-4601** [comment]
Colours are not used to distinguish the message channel any more. TextSecure messages have a lock next to the date. SMS messages don't have a lock.

The compose field tells you which message you are about to send.
* _Send TextSecure message_
* _Send unsecured SMS_
You can change the type by long pressing the send button. It always default to TS for TS users.

 Also it's not possible to send SMS accidentally if the recipient is "offline" and is a TS user.
