### ISSUE TITLE
MMS not working (various errors on sending and recieving)

### ISSUE THREAD

**Issue by ERamseth** [WhisperSystems/TextSecure#4127]
Sending MMS either ends up with a blank message or with duplicate messages or with no message received.

Receiving seems to fail almost every time with a message not found error.

Whats the most useful way to provide info so this can be fixed?

**Comment by 2-4601** [comment]
Immediately after the issue happens go to **Settings -> Advanced -> Submit debug log**
and paste the link here.

**Comment by mcginty** [comment]
closing until we can get logs
