### ISSUE TITLE
Crash when I closed TextSecure

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/TextSecure#4130]
Hi. I closed TextSecure and it crashed. No idea why
https://gist.github.com/anonymous/30e3f5d62df715f033fe
Never happened with any previous version of TS.

**Comment by mcginty** [comment]
Wow, that exception is totally outside of any code that we control. It sounds like an issue with hardware acceleration? Most people don't seem to have a root cause when they experience this which makes me think it's an Android OS bug.
