### ISSUE TITLE
Delete Drafts

### ISSUE THREAD

**Issue by Ede123** [WhisperSystems/TextSecure#4134]
It does not seem possible to delete drafts (at least I'm not able to find any possibility to do so).

If the possibility exists a pointer how to do it would be welcome, otherwise this would be a very useful feature since it's not uncommon to start a message which becomes obsolete shortly after.

A quick way to get rid of the obsolete draft would increase usability considerably.

**Comment by jeremymasters** [comment]
I just hold down my keyboard backspace key to remove all words and the draft is erased

**Comment by Ede123** [comment]
Yes, exactly... It's a pain in the a** to delete a draft right now. ;)

**Comment by jeremymasters** [comment]
I guess my keyboard deletes fast enough it hasn't bothered me too much.

**Comment by mcginty** [comment]
double tap on the text to open the selection contextual menu (select all, cut, copy, etc)

**Comment by Ede123** [comment]
Yeah, so I understand there is no interest in making this any more user friendly... Message received (although you could have just said so).

**Comment by mcginty** [comment]
At the moment I don't think it's super necessary (so much that all the other messengers that have draft functionality also don't have a "clear" option for text drafts), but am always open to arguments otherwise.

I agree it's weird that on Android long-pressing doesn't work but double-tapping does for selection, but I don't know that adding another button is worth it to make that more clear.

**Comment by kriks57** [comment]
I'm currently stuck in a strange state : I started to reply to a message (with a quote) in a group conversation, and didn't get through it.
But i don't want to reply any more, and the quote stays in my input field, I could delete the text I started to write, but the quote won't disappear, (I tried "select all" and delete, with no luck)
Am I missing something ?

**Comment by Makeem95** [comment]
> I'm currently stuck in a strange state : I started to reply to a message (with a quote) in a group conversation, and didn't get through it.
> But i don't want to reply any more, and the quote stays in my input field, I could delete the text I started to write, but the quote won't disappear, (I tried "select all" and delete, with no luck)

I just had the same issue. Only workaround I could come up with was just to reply and delete the message. You can select a different quote to replace in your reply, but could not get rid of the quote at all.

**Comment by strotter** [comment]
Same issue here.  Draft is empty but the quote stays there regardless.  No context, double tap, swipe, anywhere in the message or screen... I am forced to quote something no matter how many times I backspace/delete/etc.

**Comment by spudunk** [comment]
You can just clear Signal from the recent apps menu to close it. That cleared the draft with a quote for me. Still not ideal but makes it low priority to fix.

**Comment by jaimet** [comment]
I just had exactly the same problem/issue/bug - I (accidently) somehow managed to a start a reply to a message in a "secure" signal conversation, and I couldn't see how to delete the reply (adding and deleting some text didn't delete the reply, closing the app from the recents menu didn't delete the reply, and restarting my phone didn't delete the reply either).
Eventually I noticed a tiny cross on the top-right-hand side of the reply - it's very difficult to see the cross (in my case it's grey on a grey background image so it's almost imperceptible), but if you can find it, pressing it will delete the reply.  HTH

**Comment by auv-ee** [comment]
Wow! Thanks.  I could not find a way to delete a draft in which I had "quoted" an image someone sent.  I tried lots of stuff as previously mentioned without success. But this last post... 

There was nothing but a thumbnail of the image in the upper right corner.  No cross on in the top right, no grey background, nothing but the image.  But touching the top right corner made the draft disappear!  That's a fail of the user interface.  Thanks for the help.

**Comment by jaimet** [comment]
> That's a fail of the user interface.

Totally agree. And it wouldn't be the first.

**Comment by juhalindfors** [comment]
Same, had to close and restart the app to get rid of this usability bug.

**Comment by ateuber** [comment]
Hi, I accidentally shared something via Signal with someone who is no longer on Signal.

It shows up as draft in the messages overview, but when I open the chat with that contact I can only invite the contact to Signal, not modify or delete the draft. The draft survives completely closing Signal and clearing the cache.

Nothing private in my draft, but I can imaging this could be a bigger issue in some cases.
