### ISSUE TITLE
Differences between the APK offered in Playstore and the Sourcecode on Github

### ISSUE THREAD

**Issue by xamor** [WhisperSystems/TextSecure#4149]
Why is there a file called "gtm_analytics" in the /res/raw folder of the APK but there is no such file in the source on github. This file looks like a container file for Google Tag Manager. What's the purpose of using GTM in Textsecure and why is this file only in the APK and not on github?

**Comment by moxie0** [comment]
This is an issue tracker, not a discussion forum.  For questions, please contact support@whispersystems.org or post on the mailing list.  Thanks.

**Comment by johanw666** [comment]
When I build TextSecure myself with Android Studio these files also appear in the APK. They seem to be generated, not manually added.
