### ISSUE TITLE
TextSecure Crashing on OPO with CM12.1 nightly after last update

### ISSUE THREAD

**Issue by marsmensch** [WhisperSystems/TextSecure#4155]
TextSecure crashes right after launch on my OPO (bacon) running CyanogenMod 12.1-20150807-NIGHTLY-bacon. CM has not been updated for weeks, TextSecure worked until yesterdays TextSecure Update was installed.

CyanogenMod 12.1-20150807-NIGHTLY-bacon
Android Version 5.1.1
SELinux enforcing

Gist with logcat https://gist.github.com/marsmensch/29e944a9d4bb9345651f

**Comment by moxie0** [comment]
weird, looks like there are a few lines missing, is that the full stack trace?

**Comment by marsmensch** [comment]
Hi @moxie0, this is the logcat with TextSecure as display filter set. I will see if i can get more via adb.

**Comment by mcginty** [comment]
@marsmensch you should be able to get a debug log from settings -> advanced -> submit debug log

**Comment by moxie0** [comment]
@mcginty he can't open the app =(

**Comment by marsmensch** [comment]
I hope i got all relevant output via adb, just udpated the gist with the stacktrace:
https://gist.github.com/marsmensch/29e944a9d4bb9345651f

**Comment by moxie0** [comment]
Super weird, looks like some pretty hardcore data corruption.  What version did you update from?  Have you done weird things with your install, like using TiBackup or strange ROM management stuff?

**Comment by marsmensch** [comment]
Nothing special. I was recent with the version before and auto updates activated.

The only thing that comes to mind is a SMS TAN message i received a couple of minutes before the crash. I was not able to read it, that's how i discovered here might be a problem. Switched to SMS app to read the SMS and deleted it to see it would help, but Textsecure kept crashing.

**Comment by moxie0** [comment]
Unfortunately, it's unlikely that you can do anything to recover this install of TS.  The local storage keys have basically disappeared.  There's no code that ever does that, so it's most likely a result of system-level corruption.  Sorry, I know that's not good news!
