### ISSUE TITLE
[Signal] Calling shows Viber

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#4167]
I replaced TS 2.28.1 on my tablet with TS master at 1fd8025cb5. Redphone, Viber and WhatsApp are also installed on that tablet. When I press the call button on the conversation Viber gets called instead of a Redphone interface. Is this to be expected with current master or not?

**Comment by moxie0** [comment]
sounds like that's the app you selected to handle the dial intent on your device

**Comment by johanw666** [comment]
I know that Viber is the default calling app, but the number I tried to call was registered for Redphone so shouldn't it come up with Redphone?

**Comment by McLoo** [comment]
RedPhone users are currently not know to Signal. Missing secure call flag.  
Just (Android) Signal users right now. 
RedPhone users can call signal users  though.
