### ISSUE TITLE
Proposal to speed up QR code verification

### ISSUE THREAD

**Issue by maqp** [WhisperSystems/TextSecure#4171]
The prequisite would be including barcode scanner into TextSecure/Signal and to move the "end secure session" to the three dot menu. Tapping the lock would enable QR code verification immediately.

When Axolotl protocol assigns Alice and Bob roles to devices by comparing the base key, they could also be used assign roles for QR-code verification: e.g. display QR code on Alice's device and open camera on Bob's device. 

Bob could then scan both fingerprints from Alice's device at the same time: It could both verify that Bob's device had received the proper key from Alice, and that the proper key was delivered to Alice's device. After verification, Bob's device would either report successful verification or MITM risk. Here's a mockup I made: 

![textsecure new fingerprints](https://cloud.githubusercontent.com/assets/7425650/10236413/ced229e2-68ad-11e5-8b45-eb23871e80a4.jpg)

This approach would reduce the amount of user interaction from nine taps to two, and after crude measuring, verification would be 20 seconds faster.

**Comment by moxie0** [comment]
Hey @maqp, we prefer not to use github as a discussion forum.  If you have ideas you want to throw out, the mailing list is the best place for that.  Fixing all this stuff is on our roadmap, just not the highest priority right now.  Thanks!

**Comment by maqp** [comment]
Thanks Moxie. I'll join the mailing list if further ideas come up.
