### ISSUE TITLE
Drawing Navigation

### ISSUE THREAD

**Issue by aytronic** [WhisperSystems/TextSecure#4176]
Hallo

wie und wo kann man am besten einen Drawer wie bei Telegramm einbauen?

Gruß
Marc

**Comment by Mihahn** [comment]
Hey Marc, bitte schreib hier auf Englisch, da dies sozusagen die "offizielle Sprache" ist :wink:

**Comment by aytronic** [comment]
Hello

how and where you can install a Navigation Drawer like telegram best?

Marc

**Comment by piratenpanda** [comment]
Without screenshots non telegram users probably don't understand what you're talking about, me neither.

**Comment by moxie0** [comment]
thanks but i don't think we're going to add a drawer
