### ISSUE TITLE
Signal icon

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#4179]
I'm not sure if this is a bug or a question. Shouldn't Signal on Android use the same icon as Signal on iOS (and the browser extension)? Or should the iOS version use this icon instead?
Either way consistency isn't being respected.

**Comment by moxie0** [comment]
For the one millionth time, @oaim, this is not a discussion forum.  You know the drill.

**Comment by oaim** [comment]
For the one millionth time, consistency bugs are bugs.
You won't find many apps which have a different for every operating system. Sorry to spoil that for you moxie. Yeah, lock the conversation to collaborators

**Comment by moxie0** [comment]
ok
