### ISSUE TITLE
Name on play store is still "TextSecure .." even after updating

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#4180]
I'm a beta tester and even though the app is called Signal on my phone, it's displayed as the old "Textsecure private messenger" on the play store

**Comment by moxie0** [comment]
Yep, the name will change when it's released.

**Comment by mammuth** [comment]
FYI oaim: You can only change the whole package name via the Android Developer Console. 
Since the Signal update only is in the beta release channel, it would not make any sense renaming the whole application in Google play ;-)
