### ISSUE TITLE
Can't call some of my friends securely

### ISSUE THREAD

**Issue by oaim** [WhisperSystems/TextSecure#4181]
Updated to Signal 3.0.0
Whether I open a conversation with a contact who has redphone or a contact who has Signal on iOS I am not allowed to call securely. The phone icon in the top right corner doesn't have the lock -- but I remember seeing it while testing the app I built myself. I have refreshed the push directory several times, both using wifi and mobile data.
Clicking the phone icon opens the usual dialling app. From here, calling doesn't prompt any "call securely with Signal" either.

Android 4.1.2

**Comment by oaim** [comment]
update: some of them actually do have the lock icon. But I do have contacts both on redphone and Signal-iOS for whom no lock is displayed

**Comment by moxie0** [comment]
If there's no lock, it means they're not running Signal, or their Signal installed isn't registered for calls.

**Comment by oaim** [comment]
I talk to them like every day, how can a signal user on ios unregister from calls while still sending messages?

**Comment by moxie0** [comment]
most likely they're not running the most recent version, less likely there's a bug in signal-ios

**Comment by McLoo** [comment]
Is ios signal sending the flag 'secure call enabled' there hasn't been an update for a while there...

**Comment by McLoo** [comment]
But I am right, that RedPhone only users are not recognized?!  At least for  me
