### ISSUE TITLE
Getting server error when trying to call someone

### ISSUE THREAD

**Issue by namlit** [WhisperSystems/TextSecure#4182]
I just received the signal 3.0.0 update and tried to call someone. Unfortunately I only get a server error on the sending side. However, the receivers phone is ringing anyway, but I can not establish a connection.

Debug Log of Sending Phone: https://gist.github.com/anonymous/2c7bc62830af1d92ddcf
Debug Log of Receiving Phone: https://gist.github.com/anonymous/0406bb14102e578e0ff4

**Comment by moxie0** [comment]
hah good catch, looks like initiating calls probably won't work anywhere  but on the us-west coast with this build!
