### ISSUE TITLE
Can't call other Signal Users

### ISSUE THREAD

**Issue by mad-de** [WhisperSystems/TextSecure#4193]
I have around 5 other Signal users in my contact list (all IOS). I can't call them with Signal due to lack of an option to do so. When clicking the telephone Icon only thing to come up is the mobile call.
Android 4.4 CM 11. Device FP1. Signal 3.0.1

**Comment by HostFat** [comment]
http://lifehacker.com/5637923/change-the-default-application-for-any-android-phone-task

You have to disable the default Caller app of Google/Android.

**Comment by mad-de** [comment]
I think you got me wrong. As options I only have: 
* Phone
* Skype

Signal doesn't come up at all even though its a definite Signal User (IOS).

**Comment by Dyras** [comment]
I have the EXACT same problem.

**Comment by 2-4601** [comment]
https://github.com/WhisperSystems/TextSecure/issues/4189#issuecomment-145166987

**Comment by moxie0** [comment]
Is your ios friend running the most recent version?

**Comment by moxie0** [comment]
Also have you tried pull-to-refreshing your Signal contact list on Android?

**Comment by mad-de** [comment]
@moxie0 1) Quite certainly but will verify 2) yes.

**Comment by Dyras** [comment]
"pull-to-refreshing" What?

**Comment by mad-de** [comment]
@Dyras click in blue plus Symbol in message overview, then you are in the contact list with all Signal / TS Users. Now drag down the contacts. A circle indicating the update of the database will appear.

**Comment by moxie0** [comment]
@mad-de Also are you sure those contacts have opened Signal since the last update on iOS?

**Comment by mad-de** [comment]
@moxie0 i'm going to double check with my friends using IOS in the next days. Calling another Android Signal user worked. He can't call me back, as I have no valid registered telephone number, as the App states, although the call icon was switched with the Signal call icon. Going to double check on that as well in a couple of hours.

**Comment by moxie0** [comment]
@mad-de We're blocking the release on this report, so the sooner you can get us confirmed reproducible info the better.

**Comment by claenn** [comment]
Hi there, 
did experience the same as @mad-de with a iOS user, 
but many thanks for the clarification @moxie.

After getting confirmed that the iOS user has got the newest version, opening the app for texting on both sides, and my contact refreshing, 
the telephone symbol in the conversation's status bar switched to the crypto one, and signal calling worked out of the box =D

**Comment by mad-de** [comment]
@moxie0 @claenn Multiple refreshings and texting on both side also did resolve this with one Signal (ios) contact at some point. So I can confirm that this method seems to work at some point.

Other one, where I'm having issues is currently abroad, so I'll close down this issue for now. I'll reopen if problem if persists with this user.
As for the valid registered number I'll check if problem persists and if so will open a different issue.

**Comment by johanw666** [comment]
I had no issues calling someone with Signal on iOS. I started with a build from https://github.com/WhisperSystems/TextSecure/commit/c04149583438177d296692b08efeaf69160557d6, and this and later builds gave no problems (other than what I reported about the speaker settings).

**Comment by JFHCFC** [comment]
I've got similar problem.
Calling with WiFi connection works fine, but on LTE/3G (Orange Poland) i can't talk with no one, dialing dialing all the time.
Interestingly, when I share WiFi on other phone (also with Orange Poland connection), and connect to this WiFi, calling works.
