### ISSUE TITLE
Incoming calls set media volume permanently to zero

### ISSUE THREAD

**Issue by 2-4601** [WhisperSystems/TextSecure#4201]
1. Set media volume to non-zero
2. Someone calls you with Signal
3. Answer the call and end it (or just directly reject it, doesn't really matter)
4. Note that media volume is zero

![rubber chicken with a pulley in the middle](https://cloud.githubusercontent.com/assets/174176/10268424/db26fba4-6ac0-11e5-823b-b8617ebd3c43.gif)

Does not seem to happen with missed calls. Only answered and rejected.

Signal 3.0.1
Nexus 4, stock 5.1.1

**Comment by claenn** [comment]
Confirmed @2-4601

**Comment by moxie0** [comment]
in 3.3.0
