### ISSUE TITLE
Direct captures (image only) cannot be copied or forwarded (do not show actions which are unavailable for d-cs)

### ISSUE THREAD

**Issue by Wikinaut** [WhisperSystems/TextSecure#4210]
I tested and found that a "direct capture" (image only, no text) which I sent to someone **cannot be resent, or copied/pasted** into a new message. The only way is to decrypt/save into a file, and then to compose a new TS with that image as attachment.

If my observation is correct - that a "direct capture" cannot be copied, or resent, for technical reason, --> then I suggest 

* to disable those context menu items (long-click onto d-c-message) which are not available in that case (do not show the copy/paste item, do not show the resend function, but show the save-to-file icon for a direct capture message).

**Comment by 2-4601** [comment]
Never tried forwarding before but I cannot forward any type of picture messages. I guess there are three ways to send a picture: 1) attach image file, 2) take photo within Signal, 3) use direct capture. None of those can be forwarded.

Maybe this is #1362?

**Comment by Wikinaut** [comment]
Yep. Duplicate of #1362.
