### ISSUE TITLE
Cannot end secure session. 

### ISSUE THREAD

**Issue by sam1am** [WhisperSystems/TextSecure#4212]
My friend has removed text secure from his device, and I can no longer communicate with him because the secure session cannot be ended. I will correctly see a "Secure session ended" message, but then the very next message will be sent secured.

**Comment by 2-4601** [comment]
It is actually a reset and the strings have been fixed in the next release to reflect that.

**Comment by AlfonsoMuskedunder** [comment]
@sam1am Probably your friend hasn't unregistered from push messages yet. Please have a look at the support page, http://support.whispersystems.org/customer/en/portal/articles/2126080-how-do-i-unregister-why-is-my-message-undelivered- and ask your friend to unregister in one of the ways described.
