### ISSUE TITLE
Group invitation qr codes

### ISSUE THREAD

**Issue by sedrubal** [WhisperSystems/TextSecure#4215]
What do you think about a feature to create qr codes to automatically create a group request on scanning?

**Comment by brumsoel** [comment]
You can't join a group on your own and there are no invitations. Instead, a member can directly add you to the group (which takes 5-10 seconds). I don't understand how this process could be made any faster or more convenient with the help of a QR code.

**Comment by bartz1** [comment]
Whenever I hear of qr codes I think of people sticking qr codes everywhere at parties. If the developers of textsecure are serious about privacy they will *never* implement anything like a qr-invite

**Comment by sedrubal** [comment]
I see, that this idea is not the most important thing in the world, but it was a quick idea to make textsecure more fancy. Things like this make apps interesting, companies famous, etc.

But lol. Why should qrcodes concern security?!?

**Comment by bartz1** [comment]
Yes, I use textsecure and yes I've authenticated a contact before

**Comment by sedrubal** [comment]
did you use QR Codes or did you compare the fingerprints :P Sorry, I don't want to troll but I didn't understand what the problem with QR Codes is...

**Comment by jeremymasters** [comment]
I think they typically want discussion of ideas in the mailing list: https://lists.riseup.net/www/arc/whispersystems/2015-10

**Comment by bartz1** [comment]
using qr codes to verify contacts has NO connection to using qr codes to join groups. Worst case scenario when scannin qr codes to verify a contact is that you'll verify a contact (even if you scan a random qr code stuck to a wall). If you scan a code stuck to a wall and automatically or accidentally join a group, that's a privacy problem.
however this repository is a lot like a dictatorship, this issue will be closed soon, so post it to the mailing list -- not that anyone but other users will respond you anyway

**Comment by sedrubal** [comment]
> If you scan a code stuck to a wall

Then you shouldn't do this?

> automatically or accidentally

Lol. Then one has to implement a box which asks you, if you want to do
this. That's not the problem... Anyway, you have to hit a button to scan
the qrcode.

> this issue will be closed soon

Ok

**Comment by bartz1** [comment]
the problem is that if signal wants to become popular they have to consider that not everyone is careful as the tech-savvy users that are currently using the app. they want to gain traction, so they must start thinking of protecting the users rather than let them protect themselves

**Comment by sedrubal** [comment]
I randomly found this issue and wanted to apologize for my comments. They're inappropriate 🙈
