### ISSUE TITLE
Single/Default color for all contacts

### ISSUE THREAD

**Issue by denisq** [WhisperSystems/TextSecure#4216]
Colors per contact is a nice feature but I would prefer to have a default color for each contact until I want to customize. The reason is that most colors look quite aggressive and I would prefer to have the system theme applied instead (which is softer for the eyes).

Could you foresee an option/default behavior where all chats have the system theme and contact color customization remains available in individual conversion settings?

**Comment by moxie0** [comment]
Thanks @denisq but we're not going to do that.  In the future, the best place for discussion is the mailing list, and the best place for questions is the support center or support@whispersystems.org.

Thanks!
