### ISSUE TITLE
How to do a signal-call?

### ISSUE THREAD

**Issue by jensMF** [WhisperSystems/TextSecure#4218]
I am using Signal 3.0.2 but I can not make calls with it. When I click the phone-button my normal phone-app starts and I do not get an 'upgrade phone call' dialog or something like that…

**Comment by mammuth** [comment]
This is an issue tracker, no support center. You might shout out at support@whispersystems.org.

Please close this issue.

**Comment by mad-de** [comment]
Your question is probably answered here: https://github.com/WhisperSystems/TextSecure/issues/4193
