### ISSUE TITLE
Settings: Wrap text - Possible?

### ISSUE THREAD

**Issue by smarek** [WhisperSystems/TextSecure#4219]
Hello,

would it be possible to include in settings "Wrap text" option, because long messages on single row can quickly become unreadable. Similar behavior is in different messaging apps, and would be great to have.

**Comment by 2-4601** [comment]
Settings -> Advanced -> Enter key sends (disable it)

**Comment by smarek** [comment]
Well, I'm sorry, this is correct solution. Thank you @2-4601
