### ISSUE TITLE
Can't Send Group Messages

### ISSUE THREAD

**Issue by Adalan** [WhisperSystems/TextSecure#4220]
I've lost the ability to send any group messages. I've tried this on an off of wifi, creating new groups, groups with text secure only users and groups with SMS only users and they all fail.

Logs:  https://gist.github.com/8bab79612f69110846ac

**Comment by moxie0** [comment]
Hey @Adalan there's nothing in this debug log.  You would need to capture a debug log immediately after one of the activities you're attempting that fails.  This sounds like a support question as well, which you might have better luck writing to support@whispersystems.org about.  Thanks!

**Comment by Adalan** [comment]
Here's an updated log. https://gist.github.com/anonymous/fd6c98aaa8067282af14

I'll try emailing support, but this appears to have stopped working after the Signal update.
