### ISSUE TITLE
Message not sent but really was sent to one of two in group

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#4222]
https://gist.github.com/3bb295ab03afc5a64409

Sent message to group of two other TS users. Message could not be delivered  so I tapped on it and tapped both members since both showed unsent. One member received two messages and the other received one message.

**Comment by riyapenn** [comment]
Was one contact an iOS Signal user? You can refer to the iOS GH issue https://github.com/WhisperSystems/Signal-iOS/issues/755 to monitor progress.

**Comment by jeremymasters** [comment]
No, both were TextSecure users, not Signal users.

**Comment by riyapenn** [comment]
Looks like https://github.com/WhisperSystems/TextSecure/issues/2639.

**Comment by ralexrdz** [comment]
same issue here. I have a duplicate contact don't know why and after that messages said to not be sent, but sended to just some of the group.
