### ISSUE TITLE
Crash during unregister

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#4223]
A friend of mine tried to unregister from TextSecure temporarily to fix some messaging issues. However, TS crashed after removing the checkmark from "enable textsecure messages". After a restart, TS messages were enabled again. He can still send me encrypted messages, but I have to fall back to SMS since I am told that he doesn't use TS anymore.

TS 2.28.1, Samsung Galaxy S2, Cyanogen 12.1.
Debug Log: https://gist.github.com/anonymous/f7fbef557a4fa318104e

Edit: De-registering via the website and re-register in the app leads to a register cycle. https://gist.github.com/anonymous/0171717818e9501b5135

**Comment by moxie0** [comment]
looks like a cyanogen bug / bad gapps install.

**Comment by merkste** [comment]
Indeed. As it turned out, an CM update somehow damaged the TS install.  
Backup + Reinstall TS solved the problem.

Am .10.2015, 07:00 Uhr, schrieb Moxie Marlinspike  
<notifications@github.com>:
