### ISSUE TITLE
Feature: export single conversation

### ISSUE THREAD

**Issue by uffze667** [WhisperSystems/TextSecure#4224]
it would be nice to just export a single conversation into a text file.
not important but nice :).

**Comment by brumsoel** [comment]
Probably a duplicate of #1146? The only difference being that you explicitly mention exporting "into a text file". If you meant the text file to be human readable, this could count as a different feature

**Comment by johanw666** [comment]
Are you suggesting xml files are not human readable? :-)

**Comment by uffze667** [comment]
duplicate of #1146
