### ISSUE TITLE
bad encrypted messages

### ISSUE THREAD

**Issue by uffze667** [WhisperSystems/TextSecure#4227]
i got several "bad encrypted messaged" from two senders today.
also my textsecure messages are reported to be "bad encrypted messages" from one sender, the other one is able to read them.
i have no idea whats going on :)

![screencap3](https://cloud.githubusercontent.com/assets/2582248/10372478/37e45f56-6de8-11e5-929c-90fc7148d069.png)

of course sms are working but text secure messages do not.

here is my log file:
https://gist.github.com/anonymous/d2d767e0b068a76a0528

**Comment by jeremymasters** [comment]
Have you tried tapping the lock button in the top right?  it actually resets the session instead of ending it.  This has ironed out some issues for me.

**Comment by RiseT** [comment]
Have you recently restored some kind of backup on your phone? I second @jeremymasters suggestion.

**Comment by janimo** [comment]
Do you know what version those two contacts are running?

**Comment by uffze667** [comment]
Those Contacts are both running 2.28.1.
Didn't do any backups.

Tapping the lock button did fix the issue.
Thank you very much.
