### ISSUE TITLE
What to do with old colors?

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#4228]
The available colors for conversations have changed somewhere in the 2.26 or 2.27 range I believe, brown is no longer available. However, I have a few conversations which I gave that color and it remains working. In recipient_preferences it has still "brown" in the color field, although I can't select it anywhere. When I manually edit an color field to "brown", FC Signal and then restart it the conversation gets that color too.

Is this the intended behaviour or should there be some change in the UI about this?

**Comment by moxie0** [comment]
this is intended
