### ISSUE TITLE
UNKNOWN dialing screen and crash

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/TextSecure#4234]
I found the following issue in Signal for Android build 3.0.2 with Samsung Galaxy Note 4.

Steps to reproduce:

- Switch your phone into off-line (flight) mode

- Try to secure-call a contact

- Immediately press the red hang-up button to cancel the call

- Now again try to secure-call that contact

You will get the following dialing screen with UNKOWN name, number and picture.

![screenshot_2015-10-09-21-35-43](https://cloud.githubusercontent.com/assets/6921696/10403926/858e1b6a-6ecf-11e5-80cb-2def4f74bba6.png)

If you repeat dial, hang-up, dial, hang-up multiple times, Signal crashes. It looks like the bad (UNKNOWN) dialing screen always first appears with the second call attempt.

**Comment by Norbert80** [comment]
Build 3.0.3 is still affected.

**Comment by Norbert80** [comment]
@moxie0 can you reproduce this bug? Please let me know if you need additional information.

**Comment by Norbert80** [comment]
@moxie0: Build 3.1.0 still displays the UNKNOWN screen.

**Comment by dcherian** [comment]
Possibly related: I see this screen briefly when I end a call.

**Comment by peterpanondrugs** [comment]
https://gist.github.com/anonymous/3a80bb56d7307ad11093

**Comment by moxie0** [comment]
in 3.3.0
