### ISSUE TITLE
[Protocol,Question] Unknown key share (UKS) attack

### ISSUE THREAD

**Issue by Calrama** [WhisperSystems/TextSecure#4240]
Going over the paper [How Secure is TextSecure?](https://eprint.iacr.org/2014/904.pdf) I saw that the authors both describe a so-called UKS attack and state having had discussions with @moxie0 and others. I was, however, not able to find any specifics on whether this has been addressed in TextSecure, so I would like to ask if it was.

**Comment by 2-4601** [comment]
The developers prefer to keep this issue tracker for bug reports. Discussions should go to the mailing list (https://lists.riseup.net/www/info/whispersystems) or to the support center (http://support.whispersystems.org/).
You can also find discussion about UKS and TextSecure from your favorite search engine. moderncrypto.org probably has the answers you are looking for.
