### ISSUE TITLE
Can't load TS in Android Studio

### ISSUE THREAD

**Issue by stefficle** [WhisperSystems/TextSecure#4241]
Error:Could not find com.afollestad:material-dialogs:0.7.3.1.
Required by:
    :TextSecure-master:unspecified

Is it possible there's been a version change again and/or this version has been removed from the maven repositories? (Trying to understand the problem I went to afollestad's page and saw him mentioning another maven repository, but maybe that's just for the version 0.8.2.0.)

If that's not the problem I'll try to keep on battling Android Studio and my laptop to get them loading TextSecure properly.

**Comment by johanw666** [comment]
This version is indeed removed from Maven but there are other repositories. I have no problems building TS, build.gradle has pointers to these other repositories. If this keeps a problem, apply https://github.com/SMSSecure/SMSSecure/commit/30032918a94e7def54fa46c574a94830a2747a1e .

**Comment by stefficle** [comment]
Thank you! 
The link did the trick for me. Gradle Build completed and now it's indexing.
