### ISSUE TITLE
Can't update due to device compatible list.

### ISSUE THREAD

**Issue by Mr-Pi** [WhisperSystems/TextSecure#4247]
Since a few hours textsecure isn't more able to send messages on my nexus 7. at the home screen is a messagebox, which tells me to update my textsecure version to the most recent version. But the google play says: "Your device isn't compatible with this version". Please fix this.

**Comment by mammuth** [comment]
This is an issue tracker, no support center. 
You might shout out at support@whispersystems.org, the guys can help you out with everything.

Please close this issue.

**Comment by moxie0** [comment]
TextSecure has never been supported on tablets.  How did you install it to begin with?

**Comment by Mr-Pi** [comment]
I initially installed it via the Google Play App Store without any problem. I was even able to update my textsecure version on this way, until the latest update. I'm quite surprised that it shouldn't be supported for tablets, since I'm still able install it on a samsung galaxy note 8.
