### ISSUE TITLE
don't annoy users to rate app immediately after installing

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/TextSecure#4249]
after a fresh install, Signal immediately wants to check if I've been enjoying it.

**Comment by NorthwestBased** [comment]
I just did a fresh install of TextSecure on my Samsung SGH-T399 (Android 4.2.2) and upgraded to signal 3.0.3. It never asked me to rate the app. Maybe there is different behavior if you install signal directly, not via upgrade?

**Comment by mcginty** [comment]
You're right - this is only if the data is cleared. Didn't know the install date was coming from Android which knows better.
