### ISSUE TITLE
No working migration process for new phones specified on the website

### ISSUE THREAD

**Issue by turion** [WhisperSystems/TextSecure#4254]
In the documentation site http://support.whispersystems.org/customer/en/portal/articles/1476131-what-happens-if-i-lose-my-phone-, it says 'Tap the "Import / Export" option, choose the Export tab, and tap "Export Encrypted Backup."' This button does not exist. You've disabled encrypted backups for whatever reasons and the documentation should reflect this huge gap in the app. (Or else reenable encrypted backups and make a lot of users very happy.)

**Comment by mcginty** [comment]
Hey @turion, this is an issue tracker for our Android client - this would definitely be something for support@whispersystems.org to hear and get feedback on :).

Thanks!

**Comment by Mihahn** [comment]
To migrate TextSecure to a new phone try this method: https://github.com/WhisperSystems/TextSecure/wiki/Backup-and-restore-Signal-messages
