### ISSUE TITLE
Message notification not working (Notification + receiving messages only when opening TextSecure)

### ISSUE THREAD

**Issue by mad-de** [WhisperSystems/TextSecure#4255]
Two of my contacts are reporting (both on 2.28.1 with different phones) to only see messages from me after opening TextSecure. Messages had been sent for hours. No prior system notification. They were also displayed to me as sent, not received as well (with only one checkmark). As I'm the only TS contact they have, I can't say if this only affects messages sent from me or others as well.

Log from one of my contacts (FP1 1.8.2 on Android 4.2.2)
https://gist.github.com/anonymous/504c0c3ebb3668879e2a

if it's any good, I can get a debug log from the other device as well.

**Comment by moxie0** [comment]
This means either: 1) They've disabled background data for TS or Google services, 2) They're running a custom ROM with a bad gapps install, 3) They've used a tool like TiBackup, 4) They're on a network that blocks GCM.

**Comment by jedie** [comment]
Same as: #4266
