### ISSUE TITLE
Problems with ending secure session

### ISSUE THREAD

**Issue by ajay340** [WhisperSystems/TextSecure#4256]
My mom and I used textsecure until she broke her phone. She switched from android to iPhone, but in text secure when I want to end secure texting, and went back to the conversation, it reappeared as a secure texting. My mom doesnt receive the secure texts on her iphone. End secure session doesn't work, please fix.

**Comment by 2-4601** [comment]
Duplicate of many issues such as #4212 (which has more info how to handle this)
