### ISSUE TITLE
Reminder View Regressions

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#4261]
1) Fresh install, prompts for default SMS.  Select 'Close'.  Create a new conversation, send a message, go back to conversation list, suddenly prompts 'Import system SMS?'.

2) Close button is unintuitive.

3) Text is all squished up on the left side and hard to read.

**Comment by mcginty** [comment]
285bd3de0e2000ff6087fef03c64437132eb9e33
