### ISSUE TITLE
When upgrading to Signal (on beta channel), the homescreen icon doesn't update

### ISSUE THREAD

**Issue by NorthwestBased** [WhisperSystems/TextSecure#4263]
Samsung SGH-T399
Android 4.2.2
Signal 3.0.3

When Upgrading to Signal via the beta channel, the TextSecure icon on my Android home screen doesn't update. It does, however, update to signal in the list of installed apps. 

So I have to make a new signal shortcut, and delete the old shorcut (which still opens the app). See image:

![screenshot_2015-10-17-00-20-35](https://cloud.githubusercontent.com/assets/10520957/10557543/ea1a3cee-7465-11e5-871b-f707351ebcdf.png)

I'm unsure if this is just a buggy version of android, or if there is a way to force the icon to refresh from within our code.

**Comment by johanw666** [comment]
These kind of things happen in some launchers when the application name changes.

**Comment by mammuth** [comment]
This seems to be a misbehavior in your launcher and not in TextSecure. 
You might close this issue yourself.

**Comment by NorthwestBased** [comment]
http://stackoverflow.com/questions/9939552/android-application-name-and-icon-doesnt-change-until-phone-is-rebooted-after

Yeah, I think you're right.
