### ISSUE TITLE
Notifications from Pebble no longer possible

### ISSUE THREAD

**Issue by tribut** [WhisperSystems/TextSecure#4264]
With a recent version (I'm currently on 3.0.3) Signal is "greyed out" in the Pebble app. I have not updated the Pebble app in a while which leads me to believe this has to be related to a change in Signal.
Did you do anything that prevents third-party apps from accessing the notifications of Signal? Would you consider reverting or making said protection optional?

**Comment by chr1shaefn3r** [comment]
Weird, I'm also on TS 3.0.3 and it's not greyed out for me.
Which Pebble versions are you running?
For me, its App: 2.4.1 and Smartwatch: v2.9.1

**Comment by tribut** [comment]
I played around with it a bit and I've found the culprit now: When "Forward SMS messages" ("SMS-Mitteilungen weiterleiten" in German) is checked, SMS apps are apparently greyed out.
Thanks a lot for helping me debug this and sorry for wasting everyone's time.

**Comment by chr1shaefn3r** [comment]
Thanks for posting your solution!
