### ISSUE TITLE
Automatic contact sync does not work correctly for calling

### ISSUE THREAD

**Issue by johanw666** [WhisperSystems/TextSecure#4265]
I use Signal 3.0.3 on Android. I tried to call an iPhone with Signal 2.1.3, but I saw only the option to send encrypted messages, calling showed the default system dialer. The iPhone has Signal installed for several weeks now so I assumed the numbers had been synced by now. When synced by hand, pulling down in the contact list, the option to call appeared. Perhaps the automatic syc does not yet sync the encrypted call option?

Edit: had the same results from another phone and a tablet. The phones run both Android 4.4, the tablet 4.0.3.

**Comment by moxie0** [comment]
This means that at the time of your last sync, your contacts either weren't running the latest version of signal or hadn't yet opened the app after updating to the latest version of signal.
