### ISSUE TITLE
Does not automatically retrieve messages on android 6

### ISSUE THREAD

**Issue by nubix** [WhisperSystems/TextSecure#4266]
Even though App-Optimization is turned of for TextSecure messages are only received when the app is opened.

Android Build MRA58K on Nexus 5

**Comment by moxie0** [comment]
Typically this means you've used TiBackup, have a custom ROM with a bad gapps install, have background data disabled for TS or Google services, are on a network that blocks GCM, or are using some weird xprivacy shit.

**Comment by jedie** [comment]
I have also problems like this. Galaxy S3 and CyanogenMod.

Is there a FAQ to find the problem?!?

**Comment by nubix** [comment]
I actually did `adb backup` followed by a clean install of android 6. Rooted the now cleanly installed android and did `adb restore`.

Uninstalling and Reinstalling the app solved my Problem. 


Why does it happen? Still looks like a bug to me.

**Comment by jedie** [comment]
> Uninstalling and Reinstalling the app from the play store solved my Problem. 
With deleting the app data? (So with new keys generated etc.)

**Comment by AlfonsoMuskedunder** [comment]
Yes, there is a FAQ: http://support.whispersystems.org/customer/en/portal/articles/2121929-why-is-there-a-delay-in-receiving-messages-
Typically it suffices to unregister and reregister for push messages under advanced settings; reinstalling the entire app is not necessary.

**Comment by nubix** [comment]
@AlfonsoMuskedunder Thanks. Didn't thought of that.

I now consider this solved.

**Comment by frewsxcv** [comment]
FWIW, I also had this problem after upgrading to Android 6.

**Comment by mcginty** [comment]
Sounds like this might be a GCM-related OS upgrade issue. @frewsxcv did other apps have similar problems of not notifying after the upgrade?

**Comment by frewsxcv** [comment]
I've only had Android 6 it for a couple days, but I haven't noticed any other apps struggling with this issue

**Comment by AlfonsoMuskedunder** [comment]
@mcginty In case it is of interest, I have experienced this after after each and every OS upgrade. (I have a so-called Fairphone which has an OS derivative of Android 4.2.2; the OS updates were all within the 4.2.2 framework.) Reregistering always solved the issue. TextSecure is the only GCM-dependent app that exhibited such problems on my phone.

**Comment by frewsxcv** [comment]
Even after toggling the notification settings for TextSecure, they still aren't showing up. This is the only app I have that has this issue. Definitely makes the app unusable unfortunately. Let me know if I can send any logs to help debug this.

**Comment by moxie0** [comment]
@frewsxcv "typically this means you've used TiBackup, have a custom ROM with a bad gapps install, have background data disabled for TS or Google services, are on a network that blocks GCM, or are using some weird xprivacy shit."  

The original poster used adb backup and restore to move an install across devices, for instance. If you still need support, the best place to write is support@whispersystems.org.  Thanks!

**Comment by Dyras** [comment]
Yeah so I'm going to join the club here. Sometimes, like 10% of the time, messages only arrive when I open the app. I have a Galaxy Nexus and this happened with bot Kitkat PA and stock Jelly Bean. I'm running the latter now, and I'm really curious what's up. I did a clean install and everything, so I doubt it's my phone.

I personally think it's GAPPS screwing me over, but I'm not sure. Any ideas?

**Comment by moxie0** [comment]
@Dyras If you're running a custom rom it's most likely your gapps install.  In any case, this issue is about Android 6, which it doesn't sound like you're running.

**Comment by Dyras** [comment]
@moxie0 Nope, JB here. Just checking if there's interest in this problem. I'm using stock now though so I don't know what's causing it.

**Comment by jedie** [comment]
Is there no way to:
* TextSecure check if "GCM is turn off" and warn the user ?!?
* TextSecure can automatic turn on GCM?

**Comment by 2-4601** [comment]
@jedie 
> One question to this work-a-round: Did i get a new encryption key?

No.

https://github.com/WhisperSystems/TextSecure/issues/970#issuecomment-139432981
> if you just unregister and reregister, your keys won't change

**Comment by thirtythreeforty** [comment]
I just got bitten by this; I had used Titanium Backup when doing an otherwise clean install.

I know it gets a GCM tickle upon a new message, but I also understand that it maintains its own connection directly to the Signal server.  Do I need to disable "app optimization" (doze mode) for Signal under Android 6.0?

**Comment by McLoo** [comment]
Doze sounds like the app gets suspended. That needs to be avoided, if you want Signal to notify you  while it's in background.

**Comment by thirtythreeforty** [comment]
Well, the GCM service is exempt, so a tickle can still awaken Signal. Does
Signal always send such a message, or does it at any point rely entirely on
its own server connection?  If it always sends a message, it should be OK
even with Doze kicking in.

**Comment by jedie** [comment]
I open #5370 because i have recognizes that GCM is always off, after i update CyanogenMod.
