### ISSUE TITLE
Enquiry: please check the increase in required permissions

### ISSUE THREAD

**Issue by Oneiroi** [WhisperSystems/TextSecure#4274]
I've noticed an increase in permissions requirements; some of which appear to not make any sense
Examples follow, can someone pleas clarify why these are presently required?

# Device & app history

Allows the app to view one or more of: information about activity on the device, which apps are running, browsing history and bookmarks

# Microphone
Uses the device's microphone(s)

# Device ID & call information
Allows the app to determine the phone number and device IDs, whether a call is active and the remote number connected by a call

# Location
Uses the device's location

**Comment by skulumani** [comment]
This is not the place to post support issues, but rather to track bugs and modifications to the code.

The correct place for these types of concerns is the support forum.

For example, at [support.whispersystems.org](support.whispersystems.org) there is this link

http://support.whispersystems.org/customer/en/portal/articles/2161127-what-are-all-these-permissions-

which explains all of the permissions and their respective functions.

**Comment by Oneiroi** [comment]
ack, closing and if required will re-raise in @ support.whispersystems.org
