### ISSUE TITLE
Not able to call Redphone users with Android Signal 3.0.3

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#4280]
I'm using Signal 3.0.3 and have been using it for awhile now.  I'm not seeing Redphone users as "signal-callable" users: no phone with lock, just a plain phone icon.  I am able to text them securely just fine though.  I DO however see my lone iPhone Signal user as a callable contact.  I then got together with a friend using 2.28.1 and Redphone.  From their Redphone contact list I'm still registered there and called my phone from there and I received it inside of Signal and was able to talk.  I have of course pulled to refresh numerous times and even re-registered Redphone on my friend's phone thinking maybe that would alert something as to being callable.

**Comment by dcherian** [comment]
I think this is intended. Redphone is being deprecated. You'll have to wait for Signal to hit the app store so everyone can upgrade

**Comment by moxie0** [comment]
yep
