### ISSUE TITLE
audio doesn't restart playback when play is hit again after first play finished

### ISSUE THREAD

**Issue by mcginty** [WhisperSystems/TextSecure#4286]
Makes sense that the SeekBar might not reset when playback is finished, but if a user hits play when the seekbar is at 100% they probably want the whole clip played again.

**Comment by moxie0** [comment]
You're encountering a situation where the play head doesn't reset to the starting point?

**Comment by mcginty** [comment]
yep

**Comment by moxie0** [comment]
Can you post steps to reproduced and a debug log?
