### ISSUE TITLE
TS resending the last sent SMS some 100 times after "network unavailable" and flight mode cycle

### ISSUE THREAD

**Issue by GfEW** [WhisperSystems/TextSecure#4296]
The following has happened for the first time, after many months of TS working flawlessly on this phone: https://gist.github.com/anonymous/723ba29a67dcafdd3664

I sent a plain SMS message as expected (and done many times before) with TS. It was received by the adressee. Hours later, I found the GSM network "unavailable" (supposedly due to GSM hiccup, as the phone wasn't moved nor touched). I enabled, then re-disabled flight mode in order to cleanly reconnect to the tower. As soon as this happened, I was briefly notified that TS had troubles sending a message, and TS apparently started to flood the send queue with hundreds of resending attempts. Unfortunately, many (if not all) succeeded, giving the stunned recipient a massive SMS flood / DOS experience.
There was a system popup dialog asking if I wanted to allow TS to send the high number of SMS messages it tried to, but the phone (S5, normally very fast and slick ROM) was so busy sending and playing sound alerts that dialog didn't seem to care about my answer (or was immediately replaced by a new instance, I don't know). I shut off the phone and restarted, but as soon as GSM was connected, the mess continued.

Alas, I did not manage to capture any logs. When the phone finally got reponsive again, they appeared empty (I looked with System Tuner Pro).

**Comment by Dyras** [comment]
Haha yeah this happened for me once with a data message when my WiFi jumped from a passworded network onto a network requiring a login. The other person got my message 7-8 times. Haven't happened since, but I imagine this being worse because of it being an ordinary SMS.

**Comment by GfEW** [comment]
Oh right, it could have been even worse! (By "hundreds" I mean hundreds, not exaggerating.) 
Luckily, I have a flat SMS plan.

I guess resending could seriously use a throttle. Flooding doesn't give any real advantage over one attempt every 10 s or so, which would be easily interruptable.

**Comment by mattdale77** [comment]
I was asked to add debug logs to this bug for a possibly related issue. 

During a particularly bad incident where I had to perform a hard reset I captured a couple of error logs although only 1 I could access after the reset. 

https://gist.github.com/anonymous/4bb1d455a767be02e216

**Comment by moxie0** [comment]
Not really sure what to do about this.  @GfEW the log you posted is entirely empty.  @mattdale77 the log you posted shows that every time we try to send the SMS, Android is reporting that it failed to send due to no service.  Our requeue logic waits until the system reports that service is available, and then retries.  That cycle is allowed to continue for up to 100 times.

@mattdale77 in your case the system *immediately* notifies us that service is available, we retry, and it fails to send with an error that indicates service is unavailable.  If we decided to wait a minimum amount of time before retrying, it wouldn't really help -- the recipient would still get the SMS 100 times.

Ultimately there's not much we can do if Android is lying to us, other than retry fewer times.

**Comment by GfEW** [comment]
@Moxie Right - unfortunately, I didn't manage to save any logs while the 
phone was so busy resending, and after a couple of kill attempts, a hard 
reboot and further kill attempts (not sure which succeeded), there was 
nothing left to be posted.

Wouldn't a minimum delay of, say, 5 s between retries allow interactive 
interruption? (Regardless of the system's "service available" notification 
frequency, that is.)
Given that such resending loops, when they occur for whatever reason, can 
be costly in various ways, the user might prefer to stop the 100 retries 
logic far before its end.

**Comment by moxie0** [comment]
@GfEW I'm not sure how you'd even notice that it's happening if you waited between retries, it would just appear to be a pending message.

**Comment by Dyras** [comment]
@moxie0 One advantage in attempting the retry every 5 seconds or whatever is that it gives the phone more time to fix the connectivity problem, assuming it's temporary of course. I don't see the disadvantage of it, either way.

**Comment by mattdale77** [comment]
It may be the cyanogenmod that's on my OnePlus 1 that is the problem. The
biggest problem is that the phone becomes unusable. I would suggest as a
solution that there is a suitable time between tries and some way to
prevent the message from trying again until manually told to do so by the
user.

I'm just upgrading to a OnePlus 2 so I'll see if the problem persists there.

**Comment by moxie0** [comment]
in 3.3.0
