### ISSUE TITLE
Media messages & group updates shown many times in a row

### ISSUE THREAD

**Issue by brumsoel** [WhisperSystems/TextSecure#4299]
On current master, I found that many, but not all picture & group update messages get shown multiple times in a row (I counted everything from 3 to 28 times).
Which messages are affected and how often they're displayed doesn't change when re-entering the conversation or restarting the app.
Apparently, only long conversations are affected (both groups and one-to-one).

When long-pressing one of these faulty messages, it acts like one large message (all duplicates get selected with it, but the (i) button to enter Message Details is still visible, as if I had selected a single message):
![screenshot_2015-10-24-22-13-14](https://cloud.githubusercontent.com/assets/264472/10712696/e32844c0-7aa1-11e5-9033-e1c3ec60e5f0.png)

Log: https://gist.github.com/anonymous/1e4c9d2b0cc25d8b782c (essentially the same as in #4298)

**Comment by moxie0** [comment]
Thanks, I can't reproduce this. Can you test something for me and see if cb3f9a6805e5b118e0bfa4bc0d4445aa70511bc4 helps?

**Comment by brumsoel** [comment]
No, unfortunately that didn't help.

**Comment by moxie0** [comment]
Thanks, would have been too easy.  Can you try this commit on this branch? I think it should do the trick: ac10e21912a24071cfe0d2e6ee35b8980a116e08

**Comment by brumsoel** [comment]
Yep, that one works perfectly. Thank you!
