### ISSUE TITLE
Feature request: Tasker Intents

### ISSUE THREAD

**Issue by nxfifteen** [WhisperSystems/TextSecure#430]
I know Tasker integration has been brought up before  in https://github.com/WhisperSystems/TextSecure/issues/96 but not since, and I've been thinking of it more and was thinking of how it could be implemented from within TextSecure.

Baring in mind Tasker has no access to TextSecures database so can not be responsible for checking for new messages. Realistically TextSecure would have to notify Tasker of a new message.

Could TextSecure be used to send a Broadcast Intent when a new message is received? Then Tasker would only have to listen for them. You could also setup extra variables for senders name or message, configurable from with-in TextSecure so the user could decided how much or how little information is then available to the system.

My specific use case at present is Tasker speaks the sender name of a message to me and while I'm driving it reads out the message aloud so having the extra variables set would be helpful.

I don't think my Java programming it up to doing this alone, but I have cloned the TextSecure repository and will give it a try, but what does anyone else think?

**Comment by rhodey** [comment]
seems that it was concluded in #96 that this requires changes to Tasker or a Tasker extension and not changes to TextSecure. if this is incorrect please update this issue with some reading info and we'll reopen this.

**Comment by hstock** [comment]
I would like you to reconsider this. Typically applications allow interaction with other applications by sending and receiving intents. Basically Tasker allows system automation by allowing the user to configure actions based on received intents (among other things) and controlling other apps by sending intents.

See also http://developer.android.com/guide/components/intents-filters.html

Signal would need to create an implicit intent when a message was received and listen to an intent for sending messages. 

Both would be custom intents defined by Signal. 

Of course one would have to examine whether broadcasting an intent for received messages could be a privacy problem. 

The benefit of using intents is that it is not limited to Tasker and therefore an open API. 

Example of an app specifying an intent api: http://www.angrygoatapps.com/sqzctrl_tasker.html
