### ISSUE TITLE
different certificates served to my home internet connection vs. cell data

### ISSUE THREAD

**Issue by bdimcheff** [WhisperSystems/TextSecure#4300]
I don't know if this is the proper place for this, but I get different certificates when I'm on my comcast connection vs. tmobile data.  The cert I receive on comcast prevents me from sending texts due to an SSLHandshakeException in my textsecure logs.

See https://gist.github.com/bdimcheff/b1511b1e101ed3424a58 for what I get from openssl on each connection.

**Comment by bdimcheff** [comment]
I tried a different comcast connection today and I got the "correct" cert.  I say "correct" because I assume it's the right one, since TextSecure accepts it and I can actually send messages.

**Comment by moxie0** [comment]
this is a problem with your dns configuration or home routing setup

**Comment by johanw666** [comment]
A msn in the middle attack from some virusscanner who wants to inspect https traffic perhaps?

**Comment by bdimcheff** [comment]
aha, it is a DNS issue apparently... I don't know why the TTL would be over a year, but good call @moxie0.

```
; <<>> DiG 9.10.3 <<>> textsecure-service.whispersystems.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 49120
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;textsecure-service.whispersystems.org. IN A

;; ANSWER SECTION:
textsecure-service.whispersystems.org. 35404534 IN A 54.152.44.3

;; Query time: 2 msec
;; SERVER: 192.168.111.1#53(192.168.111.1)
;; WHEN: Mon Oct 26 20:09:48 EDT 2015
;; MSG SIZE  rcvd: 71
```
