### ISSUE TITLE
Failed incoming media messages are weird.

### ISSUE THREAD

**Issue by moxie0** [WhisperSystems/TextSecure#4308]
If you receive an MMS that fails to download, the "tap for details" hanger on the bottom of the message actually shows up on the *right* side of the conversation row, instead of under the bubble on the left side.  When you tap it, it then shows a message details activity with a "resend" button, even though this is a received message.

Been this way for a while.

**Comment by unrulygnu** [comment]
Related to #4153 

>  the "tap for details" hanger... shows up on the right side

Confirmed in 3.1.0 (79313c8).

> When you tap it, it then shows a message details activity with a "resend" button, even though this is a received message.

I haven't encountered this behavior since 56ae12a.

**Comment by mcginty** [comment]
i have been spoiled by not seeing this on my device, haha. yeah that needs to be fixed.

**Comment by ericjs** [comment]
This seems to have started only recently for me. (I'm used to seeing the failed MMS download...which always happens for me if I have data off and get then via wifi).

**Comment by mcginty** [comment]
in 3.3.0
