### ISSUE TITLE
Incoming media messages are put in a new group

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/TextSecure#4312]
Hi, using the latest beta on 4.3 Stock Google Nexus, every incoming media message is put in a newly created group. One group per person. Only the picture and with the included message is put there.

Happens with two different people. From their point of view everything is sent normally.

**Comment by moxie0** [comment]
Please post complete steps to reproduce and a debug log.

**Comment by rmueller83** [comment]
I just got an image from an iOS user which opened in a new group chat on my side. The same user sent me images previously in the same chat without problems and did not alter anything in his "workflow" sending the last problematic one. In the new group chat, the send button is gray (input field says "Send unsecured MMS"). Here is my log: https://gist.github.com/anonymous/75f93236fa15d335c2b4

**Comment by rmueller83** [comment]
So I just could reproduce this, catching logs & screenshots of iOS sender and Android receiver.
![ios-sender](https://cloud.githubusercontent.com/assets/2698076/10774423/4b74c628-7d01-11e5-8482-c4925aee7be7.png)
https://gist.github.com/367a2c46eeddb8f78a19



![android-receiver1](https://cloud.githubusercontent.com/assets/2698076/10774483/afe88b44-7d01-11e5-809a-266c5f3e0ae7.png)
![android-receiver2](https://cloud.githubusercontent.com/assets/2698076/10774487/b3e9b204-7d01-11e5-9203-000ca6c663f0.png)
https://gist.github.com/anonymous/70abbb40bfb3af0da182

**Comment by moxie0** [comment]
if you tap the group avatar button in the action bar, who is in the group?

**Comment by jtracey** [comment]
I'm being hit by this as well. Ever since upgrading to 3.1, every time someone sends me a textsecure message with an image (maybe other multimedia too, haven't tested it), it sends it instead to a "group conversation" with just me and the sender. You'll also notice that even though it's receiving secure multimedia messages, the group conversation is an unsecured group conversation (i.e. if I reply in that thread, it's sending it unencrypted with no alternative). Not good.

**Comment by moxie0** [comment]
@jtracey When you tap button in the action bar that displays the members of the group, who is in the group?

**Comment by jtracey** [comment]
"Me" and the person who sent the picture.

**Comment by jtracey** [comment]
Ah, I wonder if it's because I listed myself as a contact.

**Comment by rmueller83** [comment]
Yeah, here the same. The group consists of 2 persons: the sender and me.

**Comment by Dyras** [comment]
I haven't got myself in my address book, yet this is also happening for me.

**Comment by rainerzufall** [comment]
I can confirm this and I don't have myself in the adress book.

steps to reproduce:
- A (TS 2.28.1 Samsung Galaxy S6) sends B (me; Signal 3.1.0 Fairphone 1) picture via secured data channel.
- B gets a new group conversation created with media message. B can only answer via unsecured MMS. see pictures below
- A writes B text messages (via secured data channel) = no problems. messages are in normal group (consisting of just 2 persons) conversation.

log: https://gist.github.com/94d14a4cdeb8b961bc09

![screenshot_2015-10-28-09-09-26](https://cloud.githubusercontent.com/assets/12666598/10786089/af4346c2-7d68-11e5-8d97-8704a3db47d4.png)

![screenshot_2015-10-28-09-09-30](https://cloud.githubusercontent.com/assets/12666598/10786110/d172439c-7d68-11e5-9e71-bcf4a575fa85.png)

![screenshot_2015-10-28-09-09-38](https://cloud.githubusercontent.com/assets/12666598/10786116/d58ea74a-7d68-11e5-8475-1487227bd3b2.png)

Please let me know if you need anything else!

**Comment by bartz1** [comment]
Same here on 3.1, it is displayed as a group chat but there is no option to leave the group. It's a weird group chat

**Comment by vanitasvitae** [comment]
I can confirm this. If I try to answer to the group, the messages cant be delivered.

**Comment by moxie0** [comment]
I wasn't able to reproduce this, but think I got it in this commit. Anyone able to test it?

**Comment by Dyras** [comment]
@moxie0 Push a beta with it and I'll download it asap.

**Comment by rainerzufall** [comment]
Unfortunately I (also) can't build it from source... I will have a look and see if I manage with my limited technical capacity.

**Comment by rmueller83** [comment]
The error is gone for me in version 3.1.1. But I previously also deleted my own number from the adress book.

**Comment by vanitasvitae** [comment]
I can confirm that it is working now.

**Comment by rainerzufall** [comment]
I can also confirm - with 3.1.1 the pictures arrive in the same conversation again!

**Comment by Dyras** [comment]
Yup, this is fixed for sure. Thanks mox!
