### ISSUE TITLE
Incoming SMS triggers invitation bar for Whisper PUSH enabled contacts

### ISSUE THREAD

**Issue by Norbert80** [WhisperSystems/TextSecure#4316]
Blue invitation bar is triggered by incoming SMS from contacts that already have Whisper PUSH enabled.

For example an automated SMS from the ISP that notifies about a missed call, that integrates into the PUSH message thread for this contact, triggers display of the invitation bar.

Found in Signal 3.1.0 Android.

**Comment by mcginty** [comment]
Signal 3.1.0 conversation with push user, I get an SMS from them, don't see an invitation bar. Can't reproduce :/. Is there something weird about the phone number the ISP is sending from?

**Comment by Norbert80** [comment]
I don't think so. If you find a way to provide me your number I could forward that SMS to you.

**Comment by moxie0** [comment]
more likely the contact just isn't registered anymore. is the send button blue or grey?

**Comment by Norbert80** [comment]
It's blue. It is my most frequently used Signal contact. I just have sent a push message to that contact again and got two check marks.

**Comment by Norbert80** [comment]
Addional information:
That SMS also contains other numbers (for example a time) that are underlined and can be clicked for dialing.

**Comment by Norbert80** [comment]
I cannot reproduce this bug again. So I will close it. I will inform you here if it happens again.
