### ISSUE TITLE
Messages from the future

### ISSUE THREAD

**Issue by devurandom** [WhisperSystems/TextSecure#4321]
My friend is in a timezone 1h ahead of mine. When they send me a message, TS shows the time as one hour ahead of the current local time.

There are two problems with this:
1. It is confusing for the user when following the conversation / reading the message.
2. The conversation list shows the conversation as 23h *in the past*, sorted below a conversation that was only a few "proper" hours in the past.

Possible reason for the time difference:
1. My friend did not set the timezone, but the time, when traveling to their current location. Thus our timezones are the same, but their time is wrong. I did not ask them to confirm that, yet.

What I would expect from TS:
1. When a conversation is in the future, show it above all others (sorted by relative/signed time difference), instead of sorting it by absolute/unsigned time difference.
2. The server could append its own time, so that the receiving client has three times: sent-by-sender, received-by-server, received-by-recipient. Then:
  1. TS could show all three times in the message details.
  2. In the conversation view, it could show the time that (roughly) agrees with the others, filtering the third from the user's view by default. E.g. show an average of the two (of all three) times with the least difference.

**Comment by bartz1** [comment]
I message with people on different time zones all the time and all is good. So it's probably not related to just being in different time zones

**Comment by devurandom** [comment]
Thanks for the information. I modified "Possible reasons for the time difference" accordingly.

I still think such obvious user error could be handled by TS more gracefully.

**Comment by jeremymasters** [comment]
Are they TS contacts or regular SMS?

**Comment by 2-4601** [comment]
I've experienced this before and initially thought it was caused by different time zones but the real reason turned out to be that my contact had set the OS time manually. This is probably not a very common issue as automatic time (NTP) seems to be default both on Android and iOS.

**Comment by devurandom** [comment]
I just realised that my peer not only had the time, but also the day setup wrongly. Thus the messages are sent with a timestamp of 23h in the *past*. And further examination shows that the version of TS I use right now shows both the Sent and Received timestamps in the message details. (It didn't when I originally checked, a few days before the report - no idea why.) Thus there is nothing left to change for TS and I'll close this as invalid.

**Comment by nmousa** [comment]
+1
