### ISSUE TITLE
TextSecure version 3

### ISSUE THREAD

**Issue by sebastianv89** [WhisperSystems/TextSecure#4328]
I was told on the [support forum](http://support.whispersystems.org/customer/portal/questions/14428171-protocol-version-3) that my question belongs here:

It appears that the Axolotl protocol is at version 3, but I can find no documentation on what has changed since version 2 of the protocol?

I am trying to understand the function of:

1. The signed prekey
2. The last resort key (this might already have been there in v2)

Can you point me at the documentation?

**Comment by moxie0** [comment]
This is an issue tracker not a discussion forum, that's what the support center or the mailing list are for.
