### ISSUE TITLE
TextSecure keeps crashing

### ISSUE THREAD

**Issue by cocheese** [WhisperSystems/TextSecure#4330]
Hi, I am running updated textsecure on an HTC One M7 with Android 5.0.2.

Yesterday, a friend with Signal on iOS tried to send me a picture. I have received messages and pictures from that person just fine before. But I got the "incoming MMS failed" instead of the actual picture. When I clicked on the "resend" link to the right of the message, it crashed the app. I then tried to re-open the app, but it immediately crashed and then gave the "Unfortunately, TextSecure has stopped" pop-up, and that pop-up comes up twice. 

I have tried restarting and powering off/on my phone, but still can't open TextSecure and get the same error message twice. The strange thing though is that I can see my new messages (from a different Signal user) that have come in by swiping down on the notification banner. But I can't reply because that would require actually opening the app, which isn't happening.

I don't know how to send a log, but if this is something you can look into, please respond and I'll try to work with you on it. Thank you!

**Comment by mcginty** [comment]
Hey @cocheese, sorry you ran into this. It's fixed in the beta, but you can work around this by putting your phone in airplane mode, opening TextSecure, and deleting the incoming failed message.

**Comment by mcginty** [comment]
(#4099)
