### ISSUE TITLE
Sending a media message randomly fails

### ISSUE THREAD

**Issue by Dyras** [WhisperSystems/TextSecure#4332]
Hi. Sending a media message using data randomly fails for me. It works 9/10 times, but 1/10 times it fails. I'm at home with a stable WiFi connection. This has happened for the last 2-3 beta releases from what I can remember. 

Typically when it happens I'm just writing to someone, then I send a picture and it fails after a second. I then retry and it works right away.

https://gist.github.com/anonymous/0ca64a7e5009968a8cc3
https://gist.github.com/anonymous/c8e46db6b402fb06171d

**Comment by moxie0** [comment]
The network is failing, but the strange thing is that it doesn't retry on a failure. I'll try to figure out why I did things that way.
