### ISSUE TITLE
Awkward/uncomfortable fingerprint-verification word combinations

### ISSUE THREAD

**Issue by andy11** [WhisperSystems/TextSecure#4337]
Hi, one issue that comes up frequently when I make TextSecure/Signal calls with extended family is uncomfortable fingerprint-verification word choices.

For example, today I had to explain to my parents why the words "retouch puberty" came up on their phone.

Some other possibilities that will probably happen to people at some point:
- "newborn puberty"
- "showgirl penetrate"
- "facial escapade"
- "adult visitor"

95% of the time it doesn't matter at all, but if it were possible, I'd prefer that the word combinations be **extremely boring**.

I want to be able to recommend Signal to anyone without worrying about whether they'll get weird words and end up being creeped out.

I'd be happy to go through and change the words in src/org/thoughtcrime/redphone/crypto/zrtp/SASCalculator.java,  but I think there may be some additional work to do around versioning.

Is changing this list possible / realistic? 

If you all think this should be changed too, I'm happy to help... I was building TS from source for a while but stopped a few months ago. I don't mind getting everything set up again if it means this will get changed.

**Comment by moxie0** [comment]
This is the "pgp wordlist," which a lot of thought already went into. It's not possible/realistic to change, but we will probably be phasing it out all together in the future.
