### ISSUE TITLE
encrypted phone work in Galaxy S1 but not S6

### ISSUE THREAD

**Issue by loneuron** [WhisperSystems/TextSecure#4343]
I can send encrypted message between both phones.
I can call from S1 to S6 encrypted.
But I can't call encrypted from S6 to S1.
The lock symbol over the phone symbol is missing.
When I try to start a phone call in the signal app it starts the normal phone function from the phone!

**Comment by moxie0** [comment]
Hey @loneuron the best place for support questions is support@whispersystems.org  Thanks!
