### ISSUE TITLE
Noticed UnauthorizedException after update to 3.1.1

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#4344]
Came from 2.28.1
Though nothing seemed to fail:
After the Signal welcome and before entering the passphrase I captured this log:

https://gist.github.com/395181917b3ec5550d9a

**Comment by moxie0** [comment]
Yep that's fine.  The update code queues a job to re-set the GCM id, but your device hasn't registered with the RP server yet (happens in a separate job).  Everything works itself out.
