### ISSUE TITLE
Image thumbs in conversation list only after entering convo

### ISSUE THREAD

**Issue by McLoo** [WhisperSystems/TextSecure#4345]
Update from 2.28.1 to 3.1.1
In the convo list I then had a group and a single convo saying "media message" but showed no thumbnail preview.
The thumbnail appeared after entering end leaving the specific convo.

Log right after leaving such a convo:
https://gist.github.com/154094c07769e4518916

**Comment by moxie0** [comment]
This was a conscious tradeoff in order to avoid long-running migration code.  It should just affect this one instant post-upgrade.
