### ISSUE TITLE
Signal 3.1.1: When sending picture with text, text does not show until you scroll after message is sent.

### ISSUE THREAD

**Issue by jeremymasters** [WhisperSystems/TextSecure#4352]
When sending a picture, the conversation scrolls so that the bottom of the picture is at the bottom of the screen.  If you have included text as part of the picture message and send it, the text will not show until you scroll further.  I would expect the text to show as well.  Thanks again guys for the awesome software.

Signal 3.1.1

**Comment by 2-4601** [comment]
#4347?

**Comment by jeremymasters** [comment]
@2-4601 Yes! Thanks! Closing!
