### ISSUE TITLE
Verifying number fails

### ISSUE THREAD

**Issue by invapid** [WhisperSystems/TextSecure#4354]
I receive SMS, but it fails to automatically identify number, and I have to wait at least 1 minute before letting it call me to give me a code.

Solution.
* let user manually enter the SMS code

**Comment by mammuth** [comment]
Can you link to a debug log, which covers the time the problem occured? 

(You can create a log in settings>advanced)

**Comment by invapid** [comment]
I'm using signal (not textsecure), maybe posting in the wrong place.

settings > advanced (Is this in the android settings or signal settings)

When I pressed call, that actually didn't work either.

**Comment by jeremymasters** [comment]
Signal is now the name for the app on both iOS and Android.  Which are you using?

**Comment by invapid** [comment]
android

**Comment by invapid** [comment]
I had the same issue with textsecure, but the "call me" feature worked for it. Using Nexus 5, android 6.0 october patch set.

phone number is provided by google voice.

**Comment by moxie0** [comment]
If you're using GV, there's no way for Signal to "see" the incoming SMS and process the verification code, so you have to use the voice verification feature.  I understand this is not ideal since you have to wait, but it's also not the common case we're optimizing for.

**Comment by invapid** [comment]
this is a design flaw, it's silly to waste user's time

Options
* let someone press a button to trigger a call
* let someone manually enter the code

**Comment by invapid** [comment]
you may not care, but not every user will report usability issues. 

They'll simply give you a one star review and never use the product again.

**Comment by invapid** [comment]
@moxie0, @jeremymasters, @mammuth - this also means it doesn't work on google fi network.

**Comment by bfrog** [comment]
This fails to work on my Google Fi Nexus 5x, super annoying I can't just enter the code

**Comment by lucasduffey** [comment]
this fails to work on ALL project fi devices
