### ISSUE TITLE
Secure call problem

### ISSUE THREAD

**Issue by cylou77** [WhisperSystems/TextSecure#4355]
Hi, the keylock drawn on the phone icon don't appear with my correspondant who has the new version of app. I received his crypted call without problem but I cannot call him with the same way.

https://gist.github.com/b43c5b53a5eaf96321e0

**Comment by jeremymasters** [comment]
@cylou77 Try using the "pull to refresh"...tap the pencil icon, when you see the list of users, pull it down and let go.  Then see if you have the lock icon and can call.

**Comment by 2-4601** [comment]
There's a support article for this exact problem: http://support.whispersystems.org/customer/en/portal/articles/2172142-who-can-i-call-
(Except desk.com is in maintenance now :)

**Comment by moxie0** [comment]
closing as support question. @cylou77 the best place for support is support@whispersystems.org, thanks
