### ISSUE TITLE
Making a new call immediately results in RedPhone_login_failed error

### ISSUE THREAD

**Issue by agutl** [WhisperSystems/TextSecure#4358]
When I try to initiate a new call I immediately get an error "Anmeldung fehlgeschlagen!" (RedPhone_login_failed).
This is on a OnePlus 2 with latest Oxygen version.
The phone seems to have some issues regarding not knowing if it wants 32 or 64 bit. I had that with another app (https://github.com/schwabe/ics-openvpn) where it tried to use the 32 bit libs instead of the 64 bit ones. I don't know how this was fixed though.
This is just an estimated guess, if I can help with debugging, let me know (but you have to tell me how).

**Comment by 5boro** [comment]
You can submit a debug log by going into settings -> Advanced -> Send a debug log, and posting the gist link here :smile:

**Comment by agutl** [comment]
Totally forgot about that function :D

https://gist.github.com/anonymous/fbde3e66d3f3136137be

Interesting part seems to be around line 103/107, no clue what it means though.

**Comment by moxie0** [comment]
Looks like you might have reregistered RedPhone after upgrading to Signal, or something like that.  In any case, reregistering Signal (untick Settings -> Advanced -> Signal and retick) should fix it.

In the future you can send support related questions to support@whispersystems.org
