### ISSUE TITLE
Cannot un- and re-register

### ISSUE THREAD

**Issue by merkste** [WhisperSystems/TextSecure#4362]
A friend of mine received the update to 3.1.1 today but calling me didn't work. Therefore he tried to unregister but constantly gets an error that the server connection cannot be established. Furthermore, neither encrypted messages but calls with since then.

https://gist.github.com/anonymous/1e0f0769024acb0d92c6

**Comment by moxie0** [comment]
don't see any attempt to unregister in this log

**Comment by agutl** [comment]
I can't unregister, too. Version also is 3.1.1.

https://gist.github.com/anonymous/3b738bef520c9e2ba293

Will try to un-/reinstall now.

**Comment by moxie0** [comment]
Thanks for the log! Fixed in 3.3.0

**Comment by agutl** [comment]
You're welcome. Reinstalling worked as a workaround. I wish I made a backup of my keys.

**Comment by merkste** [comment]
Just to verify that the issue is fixed, I managed to obtain another more useful log. Does this look familiar to you?
https://gist.github.com/cc105b1d85d07d7daa17
