### ISSUE TITLE
Update from Textsecure to Signal on Play Store will not give you encrypted calls function

### ISSUE THREAD

**Issue by therealmarv** [WhisperSystems/TextSecure#4363]
Steps to reproduce:
1. I had Textsecure installed and registered.
2. I had Redphone installed and registered in the past. But uninstalled for a long time.
3. Update to current Signal (3.1.1) via Google Play.

Result is that I could not see any encrypted calling functionality with Signal with no contact!

Unregistering and reregister Signal resolved the issue and let me call old Textsecure only Android users.

What you need to do is offer a seamless upgrade path for old Redphone users (and I was only trying it out in the past!). A normal user will never discover such a hackerish way of a solution. Some users even telling to completely uninstall and reinstall or delete app cache to get it working:
http://support.whispersystems.org/customer/portal/questions/14599990-signal-for-android-unable-to-call-via-secure-method-

**Comment by jeremymasters** [comment]
For calls:
Signal <==> Signal
Redphone ==> Signal

**Comment by TheNain38** [comment]
You only need to sync contacts, and then it should work

**Comment by 2-4601** [comment]
There is no need to unregister and re-register. Did you read the answers in the link you posted?

**Comment by therealmarv** [comment]
Resync contacts did not work here.
What helped for me was only this solution in the link posted above. As I said I have not had Redphone installed for a long time:
> Once you have updated to Signal, uninstall RedPhone. If you have re-registered with RedPhone because you did not see calling compatibility, please re-register with Signal (Settings > Advanced > Signal > Un-register then Re-register) and then uninstall RedPhone.

**Comment by TheNain38** [comment]
Do your contacts have installed Signal at that time or did they have Redphone still installed?

**Comment by therealmarv** [comment]
I don't have any Redphone contacts. Only Android & Textsecure only or iOS & Signal. I can contact the Android & Textsecure ones now (which never used Redphone) but at the moment not my one iOS&Signal contact (probably because he is offline?! My Signal contact list is very small so I cannot give valid helpful information there)

**Comment by jeremymasters** [comment]
When you say "contact the Android & Textsecure ones" are you saying you contact them by text or by calling them?

**Comment by therealmarv** [comment]
edited my post to make it more clear. Texting never a problem.

**Comment by jeremymasters** [comment]
so let me see if this is right:
1. You are using Signal 3.1.1.
2. Secure Texting is never a problem.
3. Secure calling works fine to other Signal users on Android
4. Secure calling to iOS Signal users you are not sure of because your one contact might be asleep?

**Comment by therealmarv** [comment]
Yes right. And point 3 (& 4?)
- only works because of reregistering Signal
- I was a Redphone user from the past which seems the root cause of this problem.

**Comment by jeremymasters** [comment]
I was a redphone user from the past as well.  All I had to do was the contact refresh: tap the pencil icon (FAB), 2. pull down list of users to refresh.  3. go back to users and see the lock icon (if they are using signal)

**Comment by moxie0** [comment]
I can't reproduce the behavior you describe with those steps.  I'm not entirely clear on what it is that you're reporting, but it sounds more like a support related issue.

**Comment by therealmarv** [comment]
@moxie0 
Maybe I was also doing the resync wrong and @jeremymasters is right (hard to say because problem now gone). I'm not 100% sure now.

Nevertheless I think a forced resync on first start of new Signal app update would help the Android user base use and discover the encrypted calling functionality (it was not visible for me).

It was also really hard to discover for me that tiny lock on the phone icon for certain users in the contact list. I don't know how Signal UI looks/works on iOS and I only tried out Redphone in the past. But this is more a usability/UI problem.
