### ISSUE TITLE
Signal 3.1.1 Suggestion: Long-press phone icon to choose secure/insecure call

### ISSUE THREAD

**Issue by TheNain38** [WhisperSystems/TextSecure#4364]
You can't long press the phone+lock icon for choosing between secure/insecure call like the send button for texting

**Comment by jeremymasters** [comment]
Are you asking for a way to make a non-secure call from within Signal?

**Comment by TheNain38** [comment]
Yes

**Comment by jeremymasters** [comment]
And do so by having the phone+lock button be able to be long-pressed to choose secure or non-secure?

**Comment by 2-4601** [comment]
The title is not very clear. Suggestion: Long-press phone icon to choose secure/insecure call

**Comment by jeremymasters** [comment]
and I would add to the body of the request something like "like the send button for texting"

**Comment by TheNain38** [comment]
Is it better? Btw I'm French and I'm only 15, so, sorry if it wasn't very clear :)

**Comment by moxie0** [comment]
Thanks but we're not going to do this.  You can always tap the contact's avatar and select "call" from the quick contact popup there.
