### ISSUE TITLE
Signal 3.1.1 should provide a way to register to secure messaging and secure call separatly

### ISSUE THREAD

**Issue by TheNain38** [WhisperSystems/TextSecure#4365]
Contacts who don't have unlimited 3G, wouldn't want someone to call them using secure call because it uses a lot more internet than secure messaging

**Comment by jeremymasters** [comment]
You are not forced to answer the call.

**Comment by TheNain38** [comment]
Yes, but he could receive a secure call and accidently think it was an unsecure call and anwser

**Comment by jeremymasters** [comment]
No, it's a different screen for a secure or non-secure call.  A secure call will have the redphone screen while a non-secure call will have the phone's normal answering screen, won't it?

**Comment by moxie0** [comment]
Thanks but we're not going to do this.
