### ISSUE TITLE
When taking an image using embeded photo taker it gives me an image with a lot of green vertical line

### ISSUE THREAD

**Issue by TheNain38** [WhisperSystems/TextSecure#4368]

**Comment by mcginty** [comment]
Hey @TheNain38, please remember to include more verbose debugging information otherwise we can't act on these kinds of reports.

https://github.com/WhisperSystems/TextSecure/wiki/Submitting-useful-bug-reports

Thanks!

**Comment by mcginty** [comment]
Likely a dupe of #3752

**Comment by TheNain38** [comment]
Oh, thanks, didn't seen that issue
