### ISSUE TITLE
Group replies try to send to myself

### ISSUE THREAD

**Issue by keraba** [WhisperSystems/TextSecure#517]
When I receive a group text from another phone also running TextSecure,
it includes me in the recipient list. That is, the sender might see, "2 recipients
in group" while I will see 3. When I reply, it fails, I assume, because it is trying
to also send to myself. The third recipient looks like +1xxxyyyzzzz while the
other recipients have their first names.

Is there some setting that I'm missing where I can tell TextSecure my phone
number so that it leaves it out of replies? I've tried making sure that "my"
contact card in contacts/people has my phone number, including the leading "+1".

**Comment by rhodey** [comment]
@privong, @keraba are either of you still experiencing this issue? thanks for checking in with the update about BB and duplicate messages :)

**Comment by privong** [comment]
@rhodey No, I am no longer experiencing this issue.

**Comment by rhodey** [comment]
thanks a lot for checking back in @privong!
