### ISSUE TITLE
Failed SMS message resent only after 24 hours

### ISSUE THREAD

**Issue by SlavikCA** [WhisperSystems/TextSecure#519]
Using Text Secure v1.0.6, released on Dec 7 to Google app store.
Using Nexus 4, with Android 4.4.2 on WIND Mobile network.

**Step to reproduce:**
- Using app, send SMS message whenever there is no service (or bad service), so SMS is failed to send.

**Defect:**
- There is no indication, that SMS is failed to sent. SMS resent (retry) only after 24 hours.

**Expected:**
- There is indication, that SMS is failed to sent. SMS resent after short period of time (ideally as soon, as there is a service available)

**Comment by rhodey** [comment]
the gist of this issue seems to be with message resend behavior which is being more actively discussed in #2384 and #2098, closing as stale, please continue discussion in whichever of the previously mentioned threads you feel is most appropriate, thanks!
