### ISSUE TITLE
Feature: Direct Photo/Video/Audio attachments while staying in app (API calls to camera, sound recorder, video camera) instead of multistep separate apps

### ISSUE THREAD

**Issue by travisnj** [WhisperSystems/TextSecure#520]
I love the app... I want to replace it full time from Textra, BUT there is a big draw back, why don't you allow for direct photos, video and sounds to be taken. So you don't have to use two apps to get the file to send. 

Example: My wife takes a photo of something she wants my opinion on buying, (in textra or native) presses add, camera comes up, takes photo and sends

Example: Same situation, but with Text Secure you have to take the photo first and save image, then goto app and add via the menu of "where" the documents are to attach and send

So, as you can imagine carrying on a conversation and needing to send several photos during that conversation it would be a bit frustrating and very time consuming using Text Secure. 

Native, Textra and about all others I have used use API's and directly use the photo/audio to send.

**Comment by Mihahn** [comment]
+1 I think this would be a great improvement!

**Comment by ole-tange** [comment]
+1 with #345

**Comment by andunix** [comment]
+1

**Comment by streblo** [comment]
+1

Here's a SO post on how to use contentproviders to do this securely: https://stackoverflow.com/questions/20058793/android-how-to-save-the-camera-result-to-a-private-file

**Comment by GeniusKratos** [comment]
+1

**Comment by mcginty** [comment]
Closed in favor of #3563 and #3564 since all these different types of media captures will be separate PRs, making it easier to track progress.
