### ISSUE TITLE
Errorneous display of encrypted/clear SMS in the status bar

### ISSUE THREAD

**Issue by grk-** [WhisperSystems/TextSecure#528]
From time to time a SMS from someone not using TextSecure is advertized in the status bar as "Encrypted message" whereas it is obviously not encrypted.

More worrying is that some encrypted messages are displayed in clear in the status bar sometimes too although the message is encrypted using TextSecure.

I'm using TextSecure on FreeXperia Android based on CyanogenMod 10.

**Comment by rhodey** [comment]
if you have passphrase protection enabled and the database is locked (ie passphrase no in memory) this is expected behavior. if passphrase protection is disabled or the database is unlocked this is a bug.

is anyone in thread still experiencing this issue? I'm unable to reproduce.

**Comment by grk-** [comment]
I haven't seen this behavior for a while now.
