### ISSUE TITLE
Problem with flash sms in 4.4

### ISSUE THREAD

**Issue by arj03** [WhisperSystems/TextSecure#551]
Hello

I was running cyanogenmod 10.2 before (android 4.3) and using text secure there was no problem with flash sms, but in 11 (4.4), I have to enable hangout as my default sms application before I get flash sms. I use flash sms for remote login, so you can understand its a bit tedius to change back and forth all the time :)

Thanks for an otherwise great piece of software!

**Comment by rhodey** [comment]
related to #950, #105
