### ISSUE TITLE
RecipientFormattingException: Recipient: 012-345-678901 is badly formatted.

### ISSUE THREAD

**Issue by fnawothnig** [WhisperSystems/TextSecure#557]
TextSecure decides to use US formatted numbers instead of my regional or national numbers. I tried both international and regional numbers for this contact but when attempting to setup a secure session I get:

org.thoughtcrime.securesms.recipients.RecipientFormattingException: Recipient: 012-345-678901 is badly formatted.

The behavior seems to be somewhat random - sometimes I get it for the key exchange, sometimes for non-encrypted messages while the session is being set up (which fails as the exchange message is not sent) - now, after setting my phone language to local I got it to work (although it took a few attempts).

So this means for me:

When I set my phone to English it never works, as TextSecure always attempts to use the US numbering scheme. Doesn't matter whether or not the number is stored as an international one (+49012345678901) or a regional one (012345678901).

When I set my phone to my native Language it sometimes works.

**Comment by rhodey** [comment]
@fnawothnig are you still having this issue? if you could provide a copy of your debug log that documents this behavior it would be a great help, thanks!
