### ISSUE TITLE
LongClick on a URL doesn't work correctly

### ISSUE THREAD

**Issue by SquiggsWOW** [WhisperSystems/TextSecure#577]
If you send a text message that includes a URL and you have a default action specified for that protocol, the action is performed on the release instead of allowing you to choose an action from the context menu.

For example, if you have a default browser and send the text:
"Check out this website: http://www.google.ca"

If you LongClick on the text (anywhere, not just on the URL), you will see the the context menu appear with 4 options, but as soon as you release, the browser will open.  Pressing back from the browser does not allow you to select one of the context menu options.

The only work around I've found is to use 2 fingers and choose the option you want with the other finger before the browser opens.

If you don't have a default browser, you can hit back to open the context menu after the 'open with...' dialog appears.

No other applications should be launched on a LongClick.

**Comment by rhodey** [comment]
unable to reproduce this, I believe it has been resolved though more issues now exist with batch selection of URLs as documented in #2333
