### ISSUE TITLE
Number registration (for push messaging) doesn't work with Google Voice

### ISSUE THREAD

**Issue by csoghoian** [WhisperSystems/TextSecure#604]
The new push based TextSecure doesn't seem to like using Google Voice numbers (which are then forwarded to my phone's real number via SMS).

* Although there are of course privacy downsides associated with letting Google see all of your incoming/outgoing SMS data, there are also serious privacy harms associated with letting people know your actual phone number, rather than a number that will just forward texts to you*

The first step of the TextSecure number registration process ("Connecting") works fine. An incoming text message with the verification code is received by the default Android SMS app, but TextSecure doesn't catch it.

Thankfully, after 2 minutes of waiting, I am given the opportunity verify by voice, which does work.

**Comment by patcon** [comment]
Just to put it on the radar, it's less and less just a Google Voice phenomenon. There are an increasing number of MVNOs offering easy SIP numbers and special texting apps:

- http://www.touch.com/
- http://www.freedompop.com/

These companies mainly offer their own devices, but let you show up with your own device, which may be wifi only.

Also, not to mention [Hushed app](http://hushed.com/), which isn't an MVNO, but allows wifi-only devices to act as phones.

**Comment by rhodey** [comment]
this is working for me now on Nexus 5 w/ stock Lollipop 5.1 & TextSecure 2.10.2. anyone still experiencing this issue and on what device, build, etc?

**Comment by gordon-morehouse** [comment]
* Do I need to reinstall to find out?
  * Has work gone into fixing this? IIRC, last I registered, the app told me Google Voice wouldn't work.

**Comment by rhodey** [comment]
@gordon-morehouse when registering, enter your google voice number-- you should receive an SMS verification code, if that does not arrive you will receive a phone call where the code will be read to you. I've been using a google voice number on my test device for months, let me know if this doesn't work for registration and I will reopen.

**Comment by gordon-morehouse** [comment]
Zero offense intended, but that didn't really answer either of my questions.

I don't see any way to re-register in the app UI. I would like to test this, but not at the expense of blowing away my key, my history, etc. I am already using TextSecure registered to my carrier number on my only device, because it refused to work with Google Voice.

This is quite an old version of Android (2.3.4). If it's not worth testing on such an old version, I'd rather not go through the pain of reinstalling to test until I next wipe the device.

**Comment by rhodey** [comment]
thanks for the clarification, sorry I didn't understand your original post. you can re-register with a different number by going to **Settings > Advanced > TextSecure messages**, toggle this option and your current number will be unregistered then you will be prompted again to register with a different number.

**Comment by moxie0** [comment]
This will mess up your existing sessions if you change your number, though.

**Comment by eligrey** [comment]
Why isn't there an option to manually enter the text verification code, for users of Google Voice? It seems unnecessary to have to wait 2 minutes to enter a code that you already received immediately.

**Comment by lommaj** [comment]
I have the same issues, cant register with google voice.  I get the reg code via sms but the signal app doesnt pick it up.

**Comment by gaetawoo** [comment]
@moxie0 Couldn't you export your "chat", change your number, and import the "chat"? Would that work?

**Comment by Consequences** [comment]
Hang the same issue with Google Fi phone. Tried the verification via SMS message, and then also the voice verification. SMS times out and even when I get the voice call/code when I input it I get "Network error!"
