### ISSUE TITLE
Are groups persistent?

### ISSUE THREAD

**Issue by okiedude** [WhisperSystems/TextSecure#608]
First, THANK YOU for the latest version. It is rocking for me so far.

Question: Where do MMS groups go when you create them? I create and name a group, and am able to start a group MMS convo. That is working flawlessly.

But, if I delete that particular thread, I cannot seem to locate the  previously created group to re-use. Note: None of the people in the group I created use Textsecure, if that makes a difference.

Rooted Nexus 5 with stock ROM.

Again, thank you for this product!
Thanks!

**Comment by mcginty** [comment]
The group is the thread, so to speak. It hangs around as long as you find the conversation useful, then you can re-create it if you have deleted it!
