### ISSUE TITLE
Sending all SMS generates "!  Error sending message"  MMS works

### ISSUE THREAD

**Issue by vader716** [WhisperSystems/TextSecure#637]
I have tried with both fellow Text Secure users and those without.  All SMS messages generate the error above.  Uninstalled and installed.  Tried with and without Push Messages.  MMS works fine.  Worked great with previous version.  By the way the recipient gets the message but my device show the error.  Razr Maxx Jellybean.

**Comment by rhodey** [comment]
unable to take any action in resolving this issue without debug log or further information, closing for now.
