### ISSUE TITLE
Can't unlock app coming from new message notification

### ISSUE THREAD

**Issue by andreimarcu** [WhisperSystems/TextSecure#640]
When TS is locked, and I receive a new message, tapping the notification gets me to a screen to unlock TS. 

After I enter my passphrase and hit enter, I am stuck in the same unlock screen that prompts me for the passphrase.

However I get a new notification with the decrypted message, when I tap *that one* is when I'm finally in the unlocked app.

Using TS on a Moto X, with 4.4.2 and only PUSH enabled.

**Comment by rhodey** [comment]
I'm unable to reproduce this on my Nexus 5 running stock Android Lollipop and TS version 2.5.3, still having this issue @andreimarcu ?

**Comment by andreimarcu** [comment]
I wasn't able to reproduce it myself. Thanks!
