### ISSUE TITLE
Support animated gifs

### ISSUE THREAD

**Issue by Azertooth** [WhisperSystems/TextSecure#643]
Will be added? By now if i send a gif it arrives as a static image (first frames)

**Comment by mcginty** [comment]
The gif part works, but is blocked by an issue with RoundedImageView not supporting animated Drawables. For tracking: https://github.com/vinc3m1/RoundedImageView/issues/86

**Comment by mcginty** [comment]
Now pending glide integration.

**Comment by mawed** [comment]
It's still not working, even if the milestone 2.12 is closed.

So is there another problem I do not understand?

**Comment by Mihahn** [comment]
I guess this issue is solved as sending animated gifs is implemented now!
