### ISSUE TITLE
pebble intents

### ISSUE THREAD

**Issue by midi** [WhisperSystems/TextSecure#662]
feature request:

add pebble intents, so that pebble users can get notifications without needing another application.

guide for android: http://developer.getpebble.com/2/mobile-app-guide/android-guide.html/

it would be lovely if this could be added.

**Comment by dd23** [comment]
With firmware v2.9 and their recently released android app v2.3 the pebble got support for actionable notifications, such that you can trigger the sending of short, predefined replies from the watch to messaging apps. However, TextSecure doesn't seem to support that yet and it would be great if it could be added.

Of course, that feature should only work if TS is unlocked.

Details on the feature:
http://help.getpebble.com/customer/portal/articles/1819783-android---actionable-notifications

**Comment by xris** [comment]
Would very much appreciate this working as it is precluding me using text-secure. Working in hospital w inability to get phone out (e.g. doing procedure) enjoy pebble notifications to stratify message importance...care more about about MITM and general privacy more than local phone security (as the latter is sort of a general joke at the moment anyhow given backdoors...). Thanks!

**Comment by midi** [comment]
This can be closed, as Pebble has finally started using the notification API.

For the reply feature aka Android Wear support, these issues exist:
https://github.com/WhisperSystems/TextSecure/pull/1808 https://github.com/WhisperSystems/TextSecure/issues/1699
