### ISSUE TITLE
message lost in 2.0.1

### ISSUE THREAD

**Issue by lfarkas** [WhisperSystems/TextSecure#679]
after we start to test 2.0.1 it seem to working. but when i turn of my phone for 5 minutes and my friends send me a new message during this time the message lost forever.  the strange thing is that after turn on and send a new message it is arrived. so in his message list "test, test2, test3" while mine is "test, test3" and the message detail of test2 also said "sent/received ..."!!! but there is only one date.

so it's actually arrived 5 hours later, BUT on the sender side there is only one "Sent/Received" line which is the real send date, but on the receiver side there are two "Sent" "Received" line where the second is 5 hours later. even if the phone was offline only for 5 minutes.

it'd be very useful like in case of viber:
- sent
- delivered
- read
status for all message and not only in the message details, but inline with the messages.

**Comment by devurandom** [comment]
Copying my issue description from #2293:

> Currently message delivery is unreliable. It often happens that I send a message to someone, but do not get a message receipt (check-mark icon). Messages sent later get a receipt. When I talk to the person a few hours later, they tell me they did not receive the message.
>
> This issue is not limited to me sending, but also happens the other way around. It also happens for other people, as I have been told. It also happens for the message receipts themselves – sometimes a message arrives on my phone, but the sender never receives the receipt. The CyanogenMod integrated WhisperPush service is not involved. The issue happens between stock Android users, as well as with CyanogenMod users.
>
> From reading other issues I understand that GCM does not offer reliable delivery. I wonder if the equivalent of XEP-0198 section 4 "Acks" could be implemented on top of it in TextSecure.

**Comment by rhodey** [comment]
@generalmanager is correct that the behavior documented in this issue report is covered by #970 and #957, both of which have been closed. closing now, please check in with a debug log if this problem persists and this issue will be reopened, thanks! :)
