### ISSUE TITLE
Feature request: Make SMS mode optional on first start

### ISSUE THREAD

**Issue by prinz-z** [WhisperSystems/TextSecure#697]
I would like to have the option to opt-out of the SMS functionality on first start.. Many people don't have an unlimited plan on SMS or would like to send international messages. Especially for non-technical users, the SMS functionality can be very confusing and can result in (high) costs. A dialog asking whether this app should be used as SMS app with optional PUSH service or as PUSH service with optional SMS fallback or only SMS or only PUSH would help a lot.

**Comment by nysatrok** [comment]
@mcginty This issue should probably be closed because it's fixed now.

**Comment by mcginty** [comment]
Thanks @nysatrok
