### ISSUE TITLE
"Fallback to SMS" should not be enabled when the other side does not have TextSecure as their SMS app

### ISSUE THREAD

**Issue by Natanji** [WhisperSystems/TextSecure#699]
I just got disconnected from data right before messaging another TextSecure v2 user, who only uses TextSecure with Push and does not have SMS/MMS enabled.

Since I have "Allow SMS Fallback" enabled, this made my phone send out the message as an SMS (green background). That message is still "sending" now that I came back to have a data connection.

But TextSecure should know that the other side cannot receive an encrypted SMS, right? So I think this is a bug: encrypted SMS should only be sent if both sides use TextSecure for SMS.

**Comment by rhodey** [comment]
support for encrypted SMS and MMS has been dropped in the latest release, please see [this blog post](https://whispersystems.org/blog/goodbye-encrypted-sms/) for details.
