### ISSUE TITLE
No automatic download of attachments

### ISSUE THREAD

**Issue by monreal** [WhisperSystems/TextSecure#721]
It would be nice TextSecure hat an option to not download attachments automatically.

When you are part of many groups you get a lot of pictures and videos that you do not really care about. This may be fine on a free WiFi but can quickly reduce volume of a mobile data plan.

I propose a setting "Automaitc download of attachments" with options "always", "only on wifi" and "never".

**Comment by dcherian** [comment]
Can be closed now?

**Comment by mcginty** [comment]
yep. thanks @dcherian.
