### ISSUE TITLE
Persistent Notification ("TextSecure is unlocked") does not obey language preference

### ISSUE THREAD

**Issue by Natanji** [WhisperSystems/TextSecure#737]
I just noticed that while I set my language to "English" and all of TextSecure is English now, the persistent notification in Android is still displayed in the system language (German for me, "TextSecure ist entsperrt"). I have restarted TextSecure since changing the language preference in TextSecure to English, so it's not that.

**Comment by rhodey** [comment]
closing as resolved by #1328 :)
