### ISSUE TITLE
passphrase timeout does not work

### ISSUE THREAD

**Issue by rndhro** [WhisperSystems/TextSecure#748]
AOSP 4.4.2
TextSecure 2.0.1
```
W/KeyCachingService( 4362): Decrementing activity count...
W/KeyCachingService( 4362): Starting timeout: 180000
[...]
W/ActivityManager(  627): Permission Denial: Accessing service ComponentInfo{org.thoughtcrime.securesms/org.thoughtcrime.securesms.service.KeyCachingService} from pid=-1, uid=10102 that is not exported from uid 10103
```

**Comment by rhodey** [comment]
@rndhro I'm trying to reproduce this bug, can you be more specific?

You create a passphrase, set a timeout, and the passphrase does not timeout/expire after the set timeout? What timeout intervals have you tried?

**Comment by rndhro** [comment]
oh, this issue is quite old, I didn't notice it is still open.
I cannot reproduce this anymore, the current version works fine - I'm closing this issue
