### ISSUE TITLE
First SMS sent went to incorrect recipient

### ISSUE THREAD

**Issue by drewstiff** [WhisperSystems/TextSecure#760]
I set up TextSecure, then sent an SMS to (non-TS User) person A.

I then got a reply from person B (also not a TextSecure user) "?".

When I asked them what they were referring to, they explained they had received my first SMS intended for A.

The SMS in question is still listed under the conversation with A and has never shown under the conversation list of person B in TextSecure.

I have not tried to send an SMS with TextSecure since for obvious reasons, and have reverted back to my default SMS app (Hangouts) with which I have had no problems.

Is there any kind of log I can provide to help with investigating this issue?

**Comment by rhodey** [comment]
@drewstiff have you experienced this bug again since first reporting?

**Comment by drewstiff** [comment]
I stopped using the app permanently after this bug first occurred.

**Comment by rhodey** [comment]
thanks for the update :)
