### ISSUE TITLE
TextSecure can't be installed/isn't listed in Play Store

### ISSUE THREAD

**Issue by virtualritz** [WhisperSystems/TextSecure#774]
TextSecure was 1st listed as incompatible and is now completely missing in the Play Store on a ``Sony Xperia Z LTE`` tablet running ``Android 4.3``.

This is a fairly mainstream device. WhatsApp, Threema, Telegram, ChatSecure, etc. are all listed as compatible in the Play Store and work fine.

**Comment by rhodey** [comment]
TextSecure is not listed on the play store for you device because TextSecure currently doesn't support tablets, please use issue #614 for discussion of tablet support.
