### ISSUE TITLE
SMS receipt notification tones now handled (very) differently (presume accidentally)

### ISSUE THREAD

**Issue by lndshrk** [WhisperSystems/TextSecure#811]
Previous version "cooperated" with programs such as Ringo Pro and No Disturb to allow selective people to "SMS thru" when in nightly No Disturb mode.  Since update, this doesn't work at all.  Important SMS don't tone thru.

Was something changed in the notification handler?

**Comment by rhodey** [comment]
just checking in, one year later 0.o haven't seen any reports of this in recent times-- anyone still experiencing this?
