### ISSUE TITLE
Disabling push messages / While registering, crashes when non-numeric is typed

### ISSUE THREAD

**Issue by highPriestLOL** [WhisperSystems/TextSecure#812]
In disabling push messages there is no confirmation box before it unregisters me. I've had a couple of instances where the settings menu delays in loading / double tap and got unregistered, just like that. A popup would prevent such annoyances since I can use cancel if I tapped it by mistake. 

Also, while registering. Typing non-numeric like * crashes the app and locks you out.

**Comment by rhodey** [comment]
@highPriestLOL are you still able to reproduce the issue where TS crashes when typing `*` and other non-numerics? I just tried and was unable too. It seems like at least 1/2 of this issue was resolved, the push message confirmation dialog.
