### ISSUE TITLE
Fake notification saying "Encrypted message"

### ISSUE THREAD

**Issue by tnmnt114** [WhisperSystems/TextSecure#814]
Every time I start the app I get a fake notification from a contact that also has TS with the italic text "Encrypted mesaage" and a time stamp of the current time. If I click on it it takes me to the conversation with that contact,  but there is no new message. This happens every single time I open up the app after clearing it from recent apps. I do not have encrypted storage enabled. 

Edit: it seems that after doing this a few times it turned into a bad encrypted message.  All messages I send to that contact show up as bad encrypted message.  So do the ones I get from them.

**Comment by rhodey** [comment]
related #2287, #2522, #2221

**Comment by rhodey** [comment]
this issue is over a year old, all the debug logs 404, and related issues have all been marked as resolved. closing as resolved, please check back in and comment here with a fresh debug log and I will reopen this issue.
