### ISSUE TITLE
Message Duplication on Bad Connection

### ISSUE THREAD

**Issue by tinloaf** [WhisperSystems/TextSecure#843]
A friend tries to chat with me but has low connectivity. This causes messages to be sent with a delay, of course. It seems like TS re-sends those messages after a while, but the first message still is "queued" somewhere and gets delivered, too. This way, I get the message twice (with different "sent" timestamps...).

**Comment by obifur** [comment]
I face the same problem in group chat as @patzi describes. I'm pretty sure that the sender has Android 4.xx. If it's important I will confirm.

**Comment by manhole11** [comment]
I face the same problem as well, and in group chats it's more evident

**Comment by rhodey** [comment]
this is resolved now for push messages, queued until network is available.
