### ISSUE TITLE
Unable to send non-encrypted SMS to previous TextSecure user

### ISSUE THREAD

**Issue by carpenma** [WhisperSystems/TextSecure#845]
A friend of mine had TextSecure installed on their device and we exchanged keys.  They have since uninstalled the app.  My device hasn't realized that they no longer use the service so it continues to try to send encrypted push messages to them.  I have tried clearing the app data and refreshing the push directory through the settings to no avail.  I have also tried ending the secure session from the padlock menu in the thread but when I do it just changes back to secure before it sends the next message (presumably because it needs confirmation from the other user?).  I'm not sure if this is a bug or if I am missing something but I would appreciate some guidance either way.  Thank you.

**Comment by gordon-morehouse** [comment]
I opened a feature request for what was discussed in the last few comments (lack of "stickiness" in message transport method when selecting from the Send button) - please see #2285.

**Comment by wrought** [comment]
Having just gone through this issue with a friend, it seems to me that the behavior of the Lock / Unlock icon (button) is not intuitive.

When I select the closed Lock icon, I should be able to clearly end the secure session, even if I am registered to use the Push feature and currently using the Push transport mode. To me, "clearly ending the secure session" would mean that sending new messages should default to the insecure SMS transport mode, I should have an option to re-initiative a secure session, and the "Locked" lock icon should change to the "Unlocked" lock icon. 

If you think that the changes ya'll have specified so far as a result of this thread deliver the experience I've described above (or an equivalent), then I am satisfied. Otherwise, please let me know.

**Comment by rhodey** [comment]
with the dropping of encrypted SMS and MMS and some bug fixes related to transport selection on the send button this should no longer be an issue, closing.

**Comment by fersingb** [comment]
@rhodey Maybe I missed something but I think it's still an issue.

When I try to send a SMS to a friend who used to have TextSecure but uninstalled it, the default behavior in TextSecure is still set to TextSecure. I've to long press on the arrow and select SMS.

Also, my friend is still appearing in the TextSecure users list.

Or have some bug fixes you talked about not been released yet?

**Comment by agrajaghh** [comment]
your friend can unregister here: http://whispersystems.org/textsecure/unregister

**Comment by fersingb** [comment]
That's the info I was missing, thanks !

**Comment by mgraupner** [comment]
@rhodey I don't understand why this is closed. Until reading this thread it was impossible for me to send a normal SMS to somebody who uninstalled but did not unregister TextSecure first. I'm an experienced user and Android developer but holding down the send button which in no way indicates that there is another option to send a message is not a good user interface design decision in my opinion.

Why is it not possible to select on a per user base if I want to use the encrypted TextSecure Channel or SMS permanently? I was under the impression that holding down the big secure Lock and selecting 'End secure conversation' would end the secure conversation and switch back to SMS. But I guess it just means that my messages are not being encrypted anymore but still sent via the TextSecure channel but I could not figure this feature out too...
After giving my contact the link you posted still does not make them available via SMS. The 'Check contact' tells me that my contact has no key anymore but the UI stays in TextSecure Channel mode and I can only send encrypted messages if I don't hold down the send button.

Being able to select by myself what channel to use would be the best user experience. I hope this will find it's way into future versions of your superb messanger App! Keep up the good work.

**Comment by xavihernandez** [comment]
@mgraupner if you long tap on send you can choose between non encrypted SMS and encrypted TextSecure message.
What I regret tho is that TextSecure does not store preference. So when I choose to talk with unencrypted SMS to someone, I think it should be stored. Then I don't need to long tap again to select unencrypted SMS
