### ISSUE TITLE
Add a help button to explain why you should set a passphrase

### ISSUE THREAD

**Issue by gladiac** [WhisperSystems/TextSecure#864]
When you first start up TextSecure it wants you to choose a passphrase. There should be a help button which explains what it is and why it is needed. Why it is a bad idea to go without one ...

**Comment by gladiac** [comment]
You closed it cause it is fixed or you closed it cause you wont fix it?

**Comment by mcginty** [comment]
We no longer prompt for passphrase on registration and have decided to put less focus on it, and I think supporting it without excessive encouragement is a good place for us to be right now.
