### ISSUE TITLE
Messages sent during network outage are not automatically resent

### ISSUE THREAD

**Issue by phime42** [WhisperSystems/TextSecure#877]
I could not find a matching issue, correct me if I'm wrong.

A message sent while having no data connection keeps being stuck on a green background (message details are showing sent by SMS), even though the SMS fallback is deactivated. Furthermore, when reconnecting to network the message is not automatically resent.

**Comment by rhodey** [comment]
related #2098

**Comment by agrajaghh** [comment]
isn't this fixed now? Push messages should be sent as soon the network is back...
