### ISSUE TITLE
Not displaying message until app restart

### ISSUE THREAD

**Issue by monreal** [WhisperSystems/TextSecure#899]
I ran into the following situation: 
- phone vibrates and LED flashes green (=> Textsecure)
- There's a notification, I click it to open TextSecure.
- However, there is no new message available in the app.

I killed TextSecure and restarted it and the message is now displayed. I think I ran into this one or two times before already.

TextSecure 2.0.3 on Android 4.4.2 (Nexus 5).

**Comment by rhodey** [comment]
are you still experiencing this issue @monreal? if so could you provide a debug log that documents this behavior? thanks! :)

**Comment by monreal** [comment]
I have not seen this in a long time... closing.
