### ISSUE TITLE
Add our Details to (system-wide) Contact

### ISSUE THREAD

**Issue by tinloaf** [WhisperSystems/TextSecure#902]
I think it would be nice to add our contact details ("has TextSecure" / "is registered for Push") to the system-wide contact list, just as Threema / Telegram / WhatsApp / ... do it. Then, for a contact in my address book that has TS installed, the contact would show this piece of information in the contact screen and take me to the TS-Conversation with one tap.

My usual "workflow" for contacting someone is: I open my address book, open his contact, and then have a look at the options I have. There I see "Oh, I can contact him via SMS, WhatsApp, or Threema" (for example). I do not open all my installed messengers and look around in which messenger I can contact him..

**Comment by Mihahn** [comment]
I guess this can be closed as TextSecure appears in the contacts app now?
