### ISSUE TITLE
Tell the user what the blue and what the green colored messages mean

### ISSUE THREAD

**Issue by funk78** [WhisperSystems/TextSecure#908]
1. Show an AlertDialog telling the user that the message will be sent via SMS provider and might cost him cash.

2. Show the user a toast telling him that the message he just sent was for free because the other user is also using TextSecure.

Show both for the first 3 blue/green messages ever sent.

I came to this idea because i have read some german feedback in the Play Store and the users are confused if their messages cost money or not.

**Comment by McLoo** [comment]
@moxie can be closed
