### ISSUE TITLE
Refuse to receive Attachment / Pictures

### ISSUE THREAD

**Issue by logan82** [WhisperSystems/TextSecure#930]
I would like to refuse receiving attachments and pictures while I am online using 3G. 

I can think of a checkbox that enables / disables receiving attachments.

Optionally, the attachments are not loaded automatically but loaded upon request by the receiver. (this is a whatsapp feature, but that is maybe more complicated).

Thank you for your great app!

**Comment by dcherian** [comment]
Can be closed now?

**Comment by logan82** [comment]
Sure. I dont use TextSecure anymore.
Am 28.10.2015 3:51 vorm. schrieb "dcherian" <notifications@github.com>:
