### ISSUE TITLE
Changing the group picture spawns an empty notification

### ISSUE THREAD

**Issue by vascorppor** [WhisperSystems/TextSecure#936]
Consider the following situation: Alice invites Bob to a 2-people group. Later, Alice changes the group picture.

* Expected behaviour: The group chats reads "Alice has changed the group picture." The message looks similar to "xyz has joined the group chat."
* Actual behaviour: Bob receives a notification reporting an empty message from Alice.

Just a little something I noticed.

**Comment by rhodey** [comment]
unable to reproduce this on nexus 5 running stock lollipop, steps:

1. create a group
2. add friends to group
3. change group image
4. friends receive notification 'Rhodey: updated the group"

still having an issue with this @vascorppor? anyone else able to reproduce?
