### ISSUE TITLE
Improve message coloring

### ISSUE THREAD

**Issue by generalmanager** [WhisperSystems/TextSecure#945]
The colored messages are supposed to convey to the user the difference between push messages and SMS.

But the green color has confused myself, @sagischwarz, @phenx-de and literally everybody I have told to install the app. 

@phenx-de and myself have had a rather extensive discussion about the whole shebang in #908.

What we came up with:
* Use orange instead of green
  * Green is widely used to indicate security aka encryption (green traffic light -> you're safe / good to go) and people are used very to it.
  * Green is already used to indicate encryption / TS users in the contact list 
  * It also collides with several ideas in #741 and #910 to indicate trust
  * Orange is the only color left in the Android color scheme, apart from purple: https://developer.android.com/design/style/color.html
  * It doesn't have such a direct association as green and red have

* Use toned down colors to indicate the most likely transport for messages that aren't sent yet (#796)
  * Provides information about the most likely transport
  * Indicates that the message hasn't been send yet

* We should use color strips on a light grey message body. Either on the speakers' side or on top of the messages
  * A whole window of completely colored messages looks very playful/cartoonish
  * It improves the contrast of the gray message-delivered text and icons below the message, making it easier to read
  * Scale down the importance of the transport information to a reasonable level 

* Color both the messages of sender and receiver
  * While roaming and in some countries people have to pay (a lot) for incoming texts, so knowing if it's an SMS or not is important.
  * The current implementation is inconsistent from a UX perspective.

This is what @phenx-de came up with:

**Blue message sides for data and orange message sides for SMS:**
![phenx_blue](https://f.cloud.github.com/assets/6797943/2306175/f6c9bfa2-a27d-11e3-9ac5-b862f93f24da.png)____![phenx_orange](https://f.cloud.github.com/assets/6797943/2306177/fe8b3982-a27d-11e3-80ff-e2623f780581.png)

Those are two of my own mockup sets, one with white and one with grey backgrounds.
The first one doesn't have the nice new send icons because I couldn't be bothered to put them in after I made the mockups.

**Colorset 1: Blue message headers for data, grey background:**
![android_blue2_100_50_partly_grey_horizontal](https://f.cloud.github.com/assets/6797943/2306428/1ab6f3a6-a285-11e3-8df8-e80860aea8e9.jpg)

**Colorset 1: Orange message headers for SMS, grey background:**
![android_orange2_100_50_partly_grey_horizontal](https://f.cloud.github.com/assets/6797943/2306431/30ef168a-a285-11e3-9dae-9eab02852bb7.jpg)

**Colorset 2: Blue message headers for data, white background:**
![android_blue2_100_50_partly_white_horizontal_closed](https://f.cloud.github.com/assets/6797943/2307141/6e2b0812-a2a1-11e3-8cb5-fab22dac2ca7.jpg)

**Colorset 2: Orange message headers for SMS, white background, encryption:**
![android_orange2_100_50_partly_white_horizontal_closed](https://f.cloud.github.com/assets/6797943/2307143/75851422-a2a1-11e3-8561-5649d03e51ba.jpg)

**Colorset 2: Orange message headers for SMS, white background, no encryption:**
![android_orange2_100_50_partly_white_horizontal_open](https://f.cloud.github.com/assets/6797943/2307146/9b9f96b4-a2a1-11e3-9c3b-ec9ea5c485b4.jpg)

Please tell us what you think ;-)

### I did a quick count for several different preferences.
*If I misunderstood anybody, just tell me and I'll change your vote. If you have an opinion to one of those topics and aren't listed, just answer in the thread.*

The first two are about the **shape** of the messages **only**, the colors are to be discussed apart from the way we use them.

* **New style messages with colored bands (colors to be discussed) on top or on the side:**
@lindworm, @phenx-de, @noschinl, @Anaron, @monreal, @tinloaf @maulwuff

* **Old style messages but with toned down colors:**
@virtualritz, @0xACE, @L3st3r

* **Message color should indicate encryption**
@virtualritz, @lindworm, @mcginty 

* **Message color should indicate transport method**
@Anaron, @Cimbali, @0xACE, @L3st3r, @backspace

* **Colors should stay the same (blue and green)**
@Anaron, @monreal, @sagischwarz, @0xACE, @L3st3r

* **Colors should change**
@lindworm, @phenx-de, @maulwuff

Everybody seems to like the toned down colors for sending, so at least we have one thing in common ;-)

**Comment by wp9015362** [comment]
Hello,

as already mentioned in:

https://github.com/WhisperSystems/TextSecure/issues/2774

I think the message bubble colors should not be used to indicate what messaging channel (Data/SMS) is being used or if the message is encrypted or not or if the message has arrived or not.

I think those things should instead be indicated via icons.

So, it would be nice if you would use icons as indicators instead of the message bubble colors.

Regards

**Comment by moxie0** [comment]
@wp9015362 Please don't open an issue, link it to another issue, and then immediately repeat yourself in the issue you're linking to.  Just linking to it is enough.  We're very busy, please respect our time by keeping the amount of email we receive to a minimum.

**Comment by McLoo** [comment]
@moxie0 fixed with 2.21.0?!

**Comment by moxie0** [comment]
Why not!
