### ISSUE TITLE
Change the Lock action to Exit = Lock + [Back].

### ISSUE THREAD

**Issue by donjoe0** [WhisperSystems/TextSecure#985]
If I have a passphrase set, whenever I want to lock and hide TextSecure I have to press [Menu] -> Lock -> [Back]. But I don't see the point of this separate Lock action that takes me back to the login screen - typically if I've decided to explicitly lock the app it means I'm done using it and I want to exit it as well, I'm not trying to go stare at the login screen. :)
So I'd find it more user-friendly to just have [Menu] -> Exit, with Exit performing a Lock followed by a [Back] action (or whatever it's called when you hide/suspend a mobile app), and thus be able to leave the app in a secure state via two taps instead of three.

**Comment by rhodey** [comment]
the lock action in modern TextSecure behaves in the way I've interpreted this issue to be requesting, closing.

**Comment by donjoe0** [comment]
No it doesn't. I just updated to the latest version and I see the Lock action still takes me to the passphrase screen instead of "exiting" the app completely.
